# Generated by Django 6.1 on 2026-08-19 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('easypaisa', 'EasyPaisa'), ('sadapay', 'SadaPay')], default='easypaisa', max_length=20),
        ),
    ]
