# Generated by Django 6.1 on 2026-08-19 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethodOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('easypaisa', 'EasyPaisa'), ('sadapay', 'SadaPay')], max_length=20, unique=True)),
                ('label', models.CharField(max_length=50)),
                ('instructions', models.CharField(help_text="Shown to the student, e.g. 'Send to 0321-3529795 · Jawad Zain'.", max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'method'],
            },
        ),
    ]
