"""Clean, text-only extraction of the UHS MDCAT 2011 paper.

Source: MDCAT Past Papers (2008-2016) Solved(1).pdf
The source paper contains 220 MCQs. Images/diagrams are intentionally not embedded.
For visual questions, ``diagram_text`` gives a text description. This file contains
question content only; no answer key is added.
"""

YEAR = 2011
TOTAL_QUESTIONS = 220

QUESTIONS = [
    {'number': 1,
     'subject': 'Physics',
     'question': 'When the dimensions of both sides of an equation are equal, then the equation is said to be',
     'options': {'A': 'Simultaneous', 'C': 'Instantaneous', 'B': 'Homologous', 'D': 'Quadratic'},
     'diagram_text': ''},
    {'number': 2,
     'subject': 'Physics',
     'question': 'Radian is a unit of angular displacement which can also be measured in degrees. How many radians are '
                 'equal to one degree? 180 2π',
     'options': {'A': '180/π', 'C': '2π/180', 'B': 'π/180', 'D': 'π/57.3'},
     'diagram_text': ''},
    {'number': 3,
     'subject': 'Physics',
     'question': 'An elevator is moving upwards with constant velocity of ‘v’. What is a weight of a person of a mass ‘m’ '
                 'inside the elevator during upward motion?',
     'options': {'A': 'mg + mv', 'C': 'mg ― mv', 'B': 'mg', 'D': 'zero'},
     'diagram_text': ''},
    {'number': 4,
     'subject': 'Physics',
     'question': 'An object having spherical shape of radius ‘r’ experiences a retarding force F from a fluid of co- '
                 'efficient of viscosity ‘η’ when moving through the fluid with speed ‘v’. What is the ratio of retarding '
                 'force to speed?',
     'options': {'A': 'K.E. = e²V', 'C': 'K.E. = hf²', 'B': 'K.E. = hc/λ', 'D': 'K.E. = eV'},
     'diagram_text': ''},
    {'number': 5,
     'subject': 'Physics',
     'question': 'When the drag force is equal to the weight of the droplet, the droplet will fall with:',
     'options': {'A': 'High Speed', 'C': 'Certain acceleration', 'B': 'Low Speed', 'D': 'Constant Speed'},
     'diagram_text': ''},
    {'number': 6,
     'subject': 'Physics',
     'question': 'A simple pendulum of length L with bob of mass m is slightly displaced from its mean position so that '
                 'the string makes an angle θ with the vertical. The bob is then released. What is the expression for the '
                 'torque with which the bob starts to move towards the mean position?',
     'options': {'A': 'mgL', 'C': '0', 'B': 'mgL sin θ', 'D': 'mgL cos θ'},
     'diagram_text': 'A simple pendulum of length L has a bob of mass m displaced by angle θ from the vertical. The figure '
                     'shows the bob hanging on the string and the gravitational force acting downward.'},
    {'number': 7,
     'subject': 'Physics',
     'question': 'The density of blood is:',
     'options': {'A': 'Less than water',
                 'C': 'Greater than water',
                 'B': 'Nearly equal to water',
                 'D': 'Three times that of water'},
     'diagram_text': ''},
    {'number': 8,
     'subject': 'Physics',
     'question': 'A monochromatic light of wavelength λ is used to produce the diffraction pattern through a single slit '
                 'of width X. Which one of the following represents the intensity distribution across the screen?',
     'options': {'A': '[Visual option shown in source]',
                 'C': '[Visual option shown in source]',
                 'B': '[Visual option shown in source]',
                 'D': '[Visual option shown in source]'},
     'diagram_text': 'A single-slit diffraction question showing four alternative intensity-versus-position graphs across '
                     'the screen (A–D).'},
    {'number': 9,
     'subject': 'Physics',
     'question': 'For interference of light waves to take place, the required condition is',
     'options': {'A': 'The path difference of the light waves from the two sources must be large',
                 'B': 'The interfering waves must be non-coherent',
                 'C': 'The light waves may come from different sources',
                 'D': 'The light waves must come from two coherent sources'},
     'diagram_text': ''},
    {'number': 10,
     'subject': 'Physics',
     'question': 'The property of bending of light around an obstacle and spreading of light waves into geometric shadow '
                 'of an obstacle is called:',
     'options': {'A': 'Diffraction of Light',
                 'C': 'Quantization of Light',
                 'B': 'Polarization of Light',
                 'D': 'Interference of Light'},
     'diagram_text': ''},
    {'number': 11,
     'subject': 'Physics',
     'question': 'The normal human eye can focus a sharp image of an object on the eye if the object is located at certain '
                 'distance called',
     'options': {'A': 'Least Point', 'C': 'Far Point', 'B': 'Near Point', 'D': 'Distinct Point'},
     'diagram_text': ''},
    {'number': 12,
     'subject': 'Physics',
     'question': 'A source of sound wave emits waves of frequency ‘f’. If ‘v’ is speed of sound waves, then what will be '
                 'the wavelength of the waves v v uo',
     'options': {'A': 'v/f', 'C': '(v − u₀)/f', 'B': 'vf', 'D': '(v − u₀)f'},
     'diagram_text': ''},
    {'number': 13,
     'subject': 'Physics',
     'question': 'The spectrum of a star’s light is measured and the wavelength of one of the lines as the sodium’s line '
                 'is found to be 589 nm. The same line has the wavelength of 497 nm when observed in the laboratory. This '
                 'means the star is',
     'options': {'A': 'Moving away from the earth',
                 'C': 'Stationary',
                 'B': 'Moving towards the north',
                 'D': 'Revolving around the planet'},
     'diagram_text': ''},
    {'number': 14,
     'subject': 'Physics',
     'question': 'What is the period of mass spring system during SHM if the ratio of mass to spring constant is ¼?',
     'options': {'A': 'π', 'C': '1/π', 'B': '2 π', 'D': '½ π'},
     'diagram_text': ''},
    {'number': 15,
     'subject': 'Physics',
     'question': 'Waveform of SHM is given in the figure. At what time/times is displacement equal to zero?',
     'options': {'A': 'T/4 only', 'C': '0, T/4, 3T/4 and T', 'B': '3T/4 only', 'D': '0, T/2 and T'},
     'diagram_text': 'A sinusoidal SHM displacement-versus-time graph is shown, with marked times T/4, 3T/4 and T and '
                     'points A–D.'},
    {'number': 16,
     'subject': 'Physics',
     'question': 'A wire is stretched by a force which causes an extension. The energy is stored in it only when:',
     'options': {'A': 'The extension of wire is proportional to force applied',
                 'B': 'The cross-section area of the wire remains constant',
                 'C': 'The wire is not stretched beyond its elastic limit',
                 'D': 'The weight of wire is negligible'},
     'diagram_text': ''},
    {'number': 17,
     'subject': 'Physics',
     'question': 'Which statement is correct:',
     'options': {'A': 'Elasticity is that property of body which enables body to regain its original dimension',
                 'B': 'Elasticity is that property of a body that does not allow it to return to its original shape',
                 'C': 'Elasticity is that property of a body that allows it to retain its original shape and dimension '
                      'after the stress is removed.',
                 'D': 'Elasticity is that property of a body that obeys Hooke’s law.'},
     'diagram_text': ''},
    {'number': 18,
     'subject': 'Physics',
     'question': 'Which of the following is the expression of root mean square speed of a gas having n number of molecules '
                 'contained in the container? v1 2 + v2 2 +…+ vx 2 v1 + v2 +…+ vx',
     'options': {'A': '√[(v₁² + v₂² + … + vₙ²)/N]',
                 'C': '(v₁ + v₂ + … + vₙ)/N',
                 'B': '(v₁² + v₂² + … + vₙ²)/N',
                 'D': '(v₁ + v₂ + … + vₙ)/N'},
     'diagram_text': ''},
    {'number': 19,
     'subject': 'Physics',
     'question': 'For a gas of volume V in its equilibrium state, if the pressure does change with time then total kinetic '
                 'energy of gas is constant because',
     'options': {'A': 'Collisions between gas molecules occur',
                 'C': 'Collisions must be elastic',
                 'B': 'Collisions between gas molecules occur linearly',
                 'D': 'Collisions must be inelastic'},
     'diagram_text': ''},
    {'number': 20,
     'subject': 'Physics',
     'question': 'Which of the following is the proper way to study the sinusoidal waveform of the voltage?',
     'options': {'A': 'Voltage is connected to X input and the time base is switched off',
                 'B': 'Voltage is connected to Y input and the time base is switched on',
                 'C': 'Voltage is connected to Y input and the time base is switched off',
                 'D': 'Voltage is connected to X input and the time base is switched on'},
     'diagram_text': ''},
    {'number': 21,
     'subject': 'Physics',
     'question': 'Electron gun in cathode ray oscilloscope contains',
     'options': {'A': 'Filament, cathode, grid, anodes',
                 'C': 'Emitter, base, collector',
                 'B': 'Cathode, anode, capacitor, screen',
                 'D': 'Resistance, capacitor, inductor'},
     'diagram_text': ''},
    {'number': 22,
     'subject': 'Physics',
     'question': 'In which of the following, the change in internal energy is more? B A B P(Pa) P(Pa) A C D C 3 V(m3) V(m '
                 ')',
     'options': {'A': 'In system A',
                 'C': 'Cannot be predicted',
                 'B': 'In system B',
                 'D': 'Change is zero in both. (both are cyclic)'},
     'diagram_text': ''},
    {'number': 23,
     'subject': 'Physics',
     'question': 'Pressure-volume graphs of two systems A and B are plotted under isothermal and adiabatic conditions. '
                 'Which of the following observations of the graphs represents the two systems?',
     'options': {'A': '[Visual option shown in source]',
                 'B': '[Visual option shown in source]',
                 'C': '[Visual option shown in source]',
                 'D': '[Visual option shown in source]'},
     'diagram_text': 'Two alternative pressure–volume graphs compare isothermal and adiabatic curves for systems A and B.'},
    {'number': 24,
     'subject': 'Physics',
     'question': 'Which of the following curves is an isotherm?',
     'options': {'A': '[Visual option shown in source]',
                 'B': '[Visual option shown in source]',
                 'C': '[Visual option shown in source]',
                 'D': '[Visual option shown in source]'},
     'diagram_text': 'Four pressure–volume curves (A–D) are shown; the task is to identify the isotherm.'},
    {'number': 25,
     'subject': 'Physics',
     'question': 'If 2 A current passes through a resistor when connected to a certain battery. If the resistance is '
                 'replaced by the double resistance, then the current will become',
     'options': {'A': '2 A', 'C': '6 A', 'B': '4 A', 'D': '1 A'},
     'diagram_text': ''},
    {'number': 26,
     'subject': 'Physics',
     'question': 'In Helium-Neon laser, population inversion of _________ atoms is achieved which emit radiations, when '
                 'they are stimulated to fall at lower level.',
     'options': {'A': 'Neon', 'C': 'Helium and Neon', 'B': 'Helium', 'D': 'Chromium'},
     'diagram_text': ''},
    {'number': 27,
     'subject': 'Physics',
     'question': 'Three resistors each having value R are connected as shown in the figure. What is the equivalent '
                 'resistance between X and Y?',
     'options': {'A': '3R', 'C': 'R/3', 'B': 'R', 'D': 'R3'},
     'diagram_text': 'Three equal resistors R are connected between X and Y in the arrangement shown: one resistor in each '
                     'of three parallel branches.'},
    {'number': 28,
     'subject': 'Physics',
     'question': 'If the number of turns of a solenoid circular coil is doubled, but the current in the coil and radius of '
                 'the coil remains same, then what will be the magnetic flux density produced by the coil?',
     'options': {'A': 'Magnetic flux density will be halved',
                 'B': 'Magnetic flux density increases by different amount at different points',
                 'C': 'Magnetic flux density remains unchanged',
                 'D': 'Magnetic flux density will be doubled'},
     'diagram_text': ''},
    {'number': 29,
     'subject': 'Physics',
     'question': 'Two long parallel wires, Wire 1 and Wire 2, repel each other as shown in the figure. What could be the '
                 'reasons?',
     'options': {'A': 'Both carry current in same direction',
                 'C': 'Wire 1 has current, but Wire 2 has no current',
                 'B': 'Both carry current in opposite direction',
                 'D': 'Wire 2 has current, Wire 1 has no current'},
     'diagram_text': 'Two long parallel wires, Wire 1 and Wire 2, are shown carrying opposite-directed currents and '
                     'exerting repulsive forces F on each other.'},
    {'number': 30,
     'subject': 'Physics',
     'question': 'The diagram shows a wire carrying a current I placed between the poles of a magnet. In which direction '
                 'does the force on the wire act?',
     'options': {'A': 'Upwards',
                 'C': "Towards the 'N' pole of the magnet",
                 'B': 'Downwards',
                 'D': "Towards the 'S' pole of the magnet"},
     'diagram_text': 'A straight current-carrying wire is placed between the N and S poles of a magnet; the current I is '
                     'shown upward in the wire.'},
    {'number': 31,
     'subject': 'Physics',
     'question': 'Wavelength of X-rays is the order of:',
     'options': {'A': '10-6 m', 'C': '10-13 m', 'B': '10-10 m', 'D': '100 m'},
     'diagram_text': ''},
    {'number': 32,
     'subject': 'Physics',
     'question': 'Laser beam can be used to generate three-dimensional image of object in a process called:',
     'options': {'A': 'Computed technology',
                 'C': 'Holography',
                 'B': 'Computed tomography',
                 'D': 'Computerized axial tomography'},
     'diagram_text': ''},
    {'number': 33,
     'subject': 'Physics',
     'question': 'Which of the following is true for Lasers?',
     'options': {'A': 'Electrons are emitted',
                 'C': 'Coherent monochromatic light is emitted',
                 'B': 'Stimulated emission of electrons is needed',
                 'D': 'There is a population inversion of photons'},
     'diagram_text': ''},
    {'number': 34,
     'subject': 'Physics',
     'question': 'Three resistors of resistance R1, R2 and R3 are connected as shown in the figure. Equivalent resistance '
                 'is:',
     'options': {'A': 'R₁ + R₂ + R₃',
                 'C': '(R₁R₂ + R₂R₃ + R₂R₃)/(R₁ + R₂)',
                 'B': '(R₁ + R₂ + R₃)/(R₁R₂)',
                 'D': 'R₁R₂R₃/(R₂R₃)'},
     'diagram_text': 'R1 is connected in series from X to a junction; R2 and R3 form parallel branches between that '
                     'junction and Y.'},
    {'number': 35,
     'subject': 'Physics',
     'question': 'What is meant by spontaneous emission of electrons in solids?',
     'options': {'A': 'Electrons being emitted by the solids through photoelectric effect when irradiated with '
                      'electromagnetic radiation',
                 'B': 'Incident electrons colliding with electrons in solids and releasing doubling the number of incident '
                      'electrons',
                 'C': 'Electrons in solids are emitted without any external stimulus through radiation',
                 'D': 'Excited electrons going back to lower energy states immediately by releasing energy.'},
     'diagram_text': ''},
    {'number': 36,
     'subject': 'Physics',
     'question': 'When electrons lose all their kinetic energy in the first collision, the entire kinetic appears as an '
                 'X-ray photon of energy: hc',
     'options': {'A': 'K.E. = eV', 'C': 'K.E. = hc/λmin', 'B': 'K.E. = hλmin/c', 'D': 'K.E. = h/λmax'},
     'diagram_text': ''},
    {'number': 37,
     'subject': 'Physics',
     'question': 'The characteristic X-ray spectrum is due to:',
     'options': {'A': 'The absorption of neutrons by target material',
                 'C': 'The bombardment of target material by electrons',
                 'B': 'The bombardment of target material by protons',
                 'D': 'The bombardment of target material by alpha particles'},
     'diagram_text': ''},
    {'number': 38,
     'subject': 'Physics',
     'question': 'Ionizing capability of gamma rays is:',
     'options': {'A': 'Equal to alpha and beta particle',
                 'C': 'Less than both alpha and beta particles',
                 'B': 'Less than alpha but greater than beta particles',
                 'D': 'Less than beta but greater than alpha particles'},
     'diagram_text': ''},
    {'number': 39,
     'subject': 'Physics',
     'question': 'Half-life of a radioactive element is:',
     'options': {'A': 'Inversely proportional to square of decay constant',
                 'C': 'Directly proportional to decay constant',
                 'B': 'Directly proportional to square of decay constant',
                 'D': 'Inversely proportional to decay constant'},
     'diagram_text': ''},
    {'number': 40,
     'subject': 'Physics',
     'question': 'The transformation of a neutron into proton in the nucleus gives rise to emission of:',
     'options': {'A': 'Beta particles', 'C': 'Gamma particles', 'B': 'Alpha particles', 'D': 'X-rays'},
     'diagram_text': ''},
    {'number': 41,
     'subject': 'Physics',
     'question': 'The ratio of the rate of decay of a parent atom to the number of radioactive nuclei present at that time '
                 'is equal to:',
     'options': {'A': 'Half-life of radioactive element',
                 'C': 'Decay constant of radioactive element',
                 'B': 'Mean life',
                 'D': 'Activity if radioactive element'},
     'diagram_text': ''},
    {'number': 42,
     'subject': 'Physics',
     'question': 'Which one of the following particles is emitted as a result of the nuclear reaction Ra-226 → Rn-222?',
     'options': {'A': 'Beta', 'C': 'Gamma rays', 'B': 'Alpha', 'D': 'One alpha and one beta'},
     'diagram_text': 'The nuclear transformation shown is Ra-226 → Rn-222; the question asks which particle is emitted.'},
    {'number': 43,
     'subject': 'Physics',
     'question': 'Which of following is used to estimate the circulation of blood in a patient?',
     'options': {'A': 'Carbon-14', 'C': 'Phosphorus-32', 'B': 'Carbon-12', 'D': 'Sodium-24'},
     'diagram_text': ''},
    {'number': 44,
     'subject': 'Physics',
     'question': 'For the radiotherapy of a patient, it is required to double the absorbed dose in gray. What step must be '
                 'taken?',
     'options': {'A': 'Energy must be quadrated',
                 'C': 'Energy must be raised four times',
                 'B': 'Energy must be halved',
                 'D': 'Energy must be doubled'},
     'diagram_text': ''},
    {'number': 45,
     'subject': 'Chemistry',
     'question': 'In mass spectrometer, detector or collector measures the:',
     'options': {'A': 'Masses of isotopes',
                 'C': 'Relative abundances of isotopes',
                 'B': 'Percentages of isotopes',
                 'D': 'Mass numbers of isotopes'},
     'diagram_text': ''},
    {'number': 46,
     'subject': 'Chemistry',
     'question': "How many 'Cl' (chlorine) atoms are in two moles of chlorine?",
     'options': {'A': '2 × 6.02 × 10²³ atoms',
                 'C': '2 × 10²³ atoms',
                 'B': '35.5 × 6.02 × 10²³ atoms',
                 'D': '2 × 6.02 × 10²³ atoms'},
     'diagram_text': ''},
    {'number': 47,
     'subject': 'Chemistry',
     'question': 'Melting point of water is higher than petrol, because intermolecular forces in water are:',
     'options': {'A': 'Weaker than petrol', 'C': 'Same as in petrol', 'B': 'Stronger than petrol', 'D': 'Negligible'},
     'diagram_text': ''},
    {'number': 48,
     'subject': 'Chemistry',
     'question': 'DNA molecule is double stranded, in which two chains of DNA are twisted around each other by:',
     'options': {'A': 'Hydrogen bonds', 'C': 'Covalent bonds', 'B': "Vander Waal's force", 'D': 'Dative bonds'},
     'diagram_text': ''},
    {'number': 49,
     'subject': 'Chemistry',
     'question': 'The elements for which the value of ionization energy is low, can:',
     'options': {'A': 'Gain electrons readily',
                 'C': 'Loss electrons less readily',
                 'B': 'Gains electron with difficulty',
                 'D': 'Lose electrons readily'},
     'diagram_text': ''},
    {'number': 50,
     'subject': 'Chemistry',
     'question': 'The nature of cathode rays in discharge tube:',
     'options': {'A': 'Depends on the nature of gas taken in the discharge tube',
                 'B': 'Depends upon the nature of cathode in discharge tube',
                 'C': 'Is independent of the nature pf the gas in discharge tube',
                 'D': 'Depends upon the nature of anode in the discharge tube'},
     'diagram_text': ''},
    {'number': 51,
     'subject': 'Chemistry',
     'question': 'The ability of an atom in a covalent bond to attract the bonding electrons is called:',
     'options': {'A': 'Ionization energy', 'C': 'Electronegativity', 'B': 'Ionic bond energy', 'D': 'Electron affinity'},
     'diagram_text': ''},
    {'number': 52,
     'subject': 'Chemistry',
     'question': 'The paramagnetic character of a substance is due to:',
     'options': {'A': 'Bond pairs of electrons',
                 'C': 'Unpaired electrons in atom or molecule',
                 'B': 'Lone pairs of electrons',
                 'D': 'Paired electrons in valence shells of electrons'},
     'diagram_text': ''},
    {'number': 53,
     'subject': 'Chemistry',
     'question': 'Lattice energy of an ionic crystal is the enthalpy of:',
     'options': {'A': 'Combustion', 'C': 'Dissolution', 'B': 'Dissociation', 'D': 'Formation'},
     'diagram_text': ''},
    {'number': 54,
     'subject': 'Chemistry',
     'question': 'In standard enthalpy of atomization, heat of the surrounding:',
     'options': {'A': 'Remains unchanged', 'C': 'Increases than decreases', 'B': 'Increases', 'D': 'Decreases'},
     'diagram_text': ''},
    {'number': 55,
     'subject': 'Chemistry',
     'question': 'Mole fraction of any compound us the ratio of moles of all components in a:',
     'options': {'A': 'Compound', 'C': 'Molecule', 'B': 'Solution', 'D': 'Solid'},
     'diagram_text': ''},
    {'number': 56,
     'subject': 'Chemistry',
     'question': 'Molarity is defined as the number of moles of any substance dissolved:',
     'options': {'A': 'Per dm3 of water', 'C': 'Per m3 of water', 'B': 'In one gram of water', 'D': 'In 100 ml of water'},
     'diagram_text': ''},
    {'number': 57,
     'subject': 'Chemistry',
     'question': 'In electrolytic cell, a salt bridge is used in order to:',
     'options': {'A': 'Pass the electric current',
                 'C': 'Mix solution of two half cells',
                 'B': 'Prevent the flow of ions',
                 'D': 'Allow movement of ions b/w two half cells'},
     'diagram_text': ''},
    {'number': 58,
     'subject': 'Chemistry',
     'question': 'In all oxidation reactions, atoms of an element in a chemical species lose electrons and increase their:',
     'options': {'A': 'Oxidation states', 'C': 'Electrode', 'B': 'Reductions', 'D': 'Negative charges'},
     'diagram_text': ''},
    {'number': 59,
     'subject': 'Chemistry',
     'question': "In 'AgCl' solution. Some salt of NaCl is added, 'AgCl' will be precipitated due to:",
     'options': {'A': 'Solubility', 'C': 'Unsaturation effect', 'B': 'Electrolyte', 'D': 'Common ion effect'},
     'diagram_text': ''},
    {'number': 60,
     'subject': 'Chemistry',
     'question': '‘Ka’ for an acid is higher, the stronger is the acid; relate the strength an acid with ‘pKa’',
     'options': {'A': 'Higher pKa, weaker the acid',
                 'C': 'pKa has no relation with acid strength',
                 'B': 'Lower pKa, stronger the acid',
                 'D': 'Both A and B'},
     'diagram_text': ''},
    {'number': 61,
     'subject': 'Chemistry',
     'question': 'It is experimentally found that a catalyst is used to:',
     'options': {'A': 'Lower the activation energy',
                 'C': 'Lower the pH',
                 'B': 'Increase the activation energy',
                 'D': 'Decrease the temp of the reaction'},
     'diagram_text': ''},
    {'number': 62,
     'subject': 'Chemistry',
     'question': 'According to collision theory of bimolecular reaction sin gas phase, the minimum amount of energy '
                 'required for an effective collision is known as:',
     'options': {'A': 'Heat of reaction',
                 'C': 'Has no effect on the reaction',
                 'B': 'Rate of reaction',
                 'D': 'Energy of activation'},
     'diagram_text': ''},
    {'number': 63,
     'subject': 'Chemistry',
     'question': 'Carbon exists as allotropes, which are different crystalline or molecular forms of the same substance. '
                 'Graphite and diamond are allotropes of carbon. Diamond is a non-conductor whereas graphite is a good '
                 'conductor because:',
     'options': {'A': 'Graphite has a layered structure',
                 'C': 'In graphite one of valence electron is free to move',
                 'B': 'In graphite, all valence electrons are tetrahedrally',
                 'D': 'Graphite is soft and greasy bound'},
     'diagram_text': ''},
    {'number': 64,
     'subject': 'Chemistry',
     'question': 'The diagram below is a plot of melting points of elements of the second period against their atomic '
                 'numbers. Lithium and fluorine are placed at the extreme ends of the plot. On the basis of melting '
                 'points, where will you place carbon among the empty slots on the plot?',
     'options': {'A': '1', 'C': '4', 'B': '2', 'D': '3'},
     'diagram_text': 'A plot of melting point versus atomic number for the second-period elements is shown, with empty '
                     'positions numbered 1–4 and lithium/fluorine at the ends; carbon must be placed in the appropriate '
                     'position.'},
    {'number': 65,
     'subject': 'Chemistry',
     'question': 'When elements of group II-A (alkaline earth metals) are exposed to air, they quickly become coated with '
                 'a layer of oxide. What is the purpose of this oxide layer?',
     'options': {'A': 'The oxide layer exposes the metal to Atmospheric attack',
                 'B': 'The oxide layer increases the reactivity of metal',
                 'C': 'The oxide layer protects the metal from further atmospheric attack',
                 'D': 'The oxide layer gives the metal a shiny silvery appearance'},
     'diagram_text': ''},
    {'number': 66,
     'subject': 'Chemistry',
     'question': 'In silicon dioxide each silicon atom is tetrahedrally bonded to four oxygen atoms and each oxygen atom '
                 'is bonded to two silicon atoms. The ratio of silicon to oxygen atoms is:',
     'options': {'A': '2:2', 'C': '2:1', 'B': '1:2', 'D': '1:4'},
     'diagram_text': ''},
    {'number': 67,
     'subject': 'Chemistry',
     'question': 'Hydrogenation of unsaturated oils is done by using:',
     'options': {'A': 'Finally divided nickel', 'C': 'Vanadium pentaoxide', 'B': 'Finally divided iron', 'D': 'Copper'},
     'diagram_text': ''},
    {'number': 68,
     'subject': 'Chemistry',
     'question': 'Pick the correct statement:',
     'options': {'A': 'Chelates are usually more stable than ordinary',
                 'C': 'Monodentate ligands form the chelates complexes',
                 'B': 'Ordinary complexes are more stable than chelates',
                 'D': 'Chelates have no ring structures'},
     'diagram_text': ''},
    {'number': 69,
     'subject': 'Chemistry',
     'question': 'In contact process, the catalyst used for the conversion of Sulphur dioxide to Sulphur trioxide is:',
     'options': {'A': 'Magnesium oxide', 'C': 'Silicon dioxide', 'B': 'Aluminum oxide', 'D': 'Vanadium pentoxide'},
     'diagram_text': ''},
    {'number': 70,
     'subject': 'Chemistry',
     'question': 'The unpolluted natural rain water is slightly acidic due to the reaction of rain water with:',
     'options': {'A': 'Sulphur dioxide', 'C': 'Carbon dioxide', 'B': 'Oxides of nitrogen', 'D': 'Hydrogen present in air'},
     'diagram_text': ''},
    {'number': 71,
     'subject': 'Chemistry',
     'question': "In the Haber's process for the manufacturing of ammonia, nitrogen is taken from:",
     'options': {'A': 'Proteins occurring in living bodies',
                 'C': 'Air',
                 'B': 'Ammonium salts obtained industrially',
                 'D': 'Mineral containing nitrates'},
     'diagram_text': ''},
    {'number': 72,
     'subject': 'Chemistry',
     'question': 'In comparison with oxygen gas, a strong triple bond is present between two nitrogen atoms in a molecule '
                 'and therefore nitrogen gas is:',
     'options': {'A': 'Highly reactive gas',
                 'C': 'Very less reactive gas',
                 'B': 'Completely inert like noble gases',
                 'D': 'Moderately reactive gas'},
     'diagram_text': ''},
    {'number': 73,
     'subject': 'Chemistry',
     'question': 'The compound with an atom, which has unshared pair of electrons is called:',
     'options': {'A': 'Nucleophile', 'C': 'Protophile', 'B': 'Electrophile', 'D': 'None of the above'},
     'diagram_text': ''},
    {'number': 74,
     'subject': 'Chemistry',
     'question': '1-chloropropane and 2-chlorpropane are isomers of each other, the type of isomerism in these two is '
                 'called:',
     'options': {'A': 'Cis-trans isomerism',
                 'C': 'Position isomerism',
                 'B': 'Chain isomerism',
                 'D': 'Functional group isomerism'},
     'diagram_text': ''},
    {'number': 75,
     'subject': 'Chemistry',
     'question': 'Benzene in the presence of AlCl3 produces acetophenone when reacts with:',
     'options': {'A': 'Acetyl chloride', 'C': 'Ethyl benzene', 'B': 'Acetic acid', 'D': 'Ethanoic acid'},
     'diagram_text': ''},
    {'number': 76,
     'subject': 'Chemistry',
     'question': "The substitution of a '-H' by '-NO2' group in benzene is called:",
     'options': {'A': 'Nitration', 'C': 'Sulphonation', 'B': 'Ammunolusis', 'D': 'Reduction of benzene'},
     'diagram_text': ''},
    {'number': 77,
     'subject': 'Chemistry',
     'question': 'When purely alcoholic solution of sodium/potassium hydroxide and halogenoalkanes are reacted an alkene '
                 'is formed, what is the mechanism of reaction?',
     'options': {'A': 'Elimination', 'C': 'Debromination', 'B': 'Dehydration', 'D': 'Reduction of benzene'},
     'diagram_text': ''},
    {'number': 78,
     'subject': 'Chemistry',
     'question': 'The organic compound carbon tetrachloride is used as:',
     'options': {'A': 'Lubricant', 'C': 'Oxidant', 'B': 'Solvent', 'D': 'Plastic'},
     'diagram_text': ''},
    {'number': 79,
     'subject': 'Chemistry',
     'question': 'An alcohol is converted to an aldehyde with same number of carbon atoms as that of alcohol in the '
                 'presence of K2Cr2O7/H2SO4 the alcohol is:',
     'options': {'A': 'CH₃CH(Cl)CH₂OH', 'C': '(CH₃)₃COH', 'B': 'CH₃CH₂CH₂OH', 'D': '(CH₃)₃CHOH'},
     'diagram_text': ''},
    {'number': 80,
     'subject': 'Chemistry',
     'question': 'Which of the following is a secondary alcohol?',
     'options': {'A': 'CH3', 'C': 'CH3 CH3 H3C CH CH2 C CH3', 'B': 'H3C CH2 CH2 OH', 'D': 'CH3 OH'},
     'diagram_text': 'Four structural formulas (A–D) of alcohols are shown; the task is to identify the secondary alcohol.'},
    {'number': 81,
     'subject': 'Chemistry',
     'question': 'Which enzyme is involved in the fermentation of glucose:',
     'options': {'A': 'Zymase', 'C': 'Urease', 'B': 'Invertase', 'D': 'Diastase'},
     'diagram_text': ''},
    {'number': 82,
     'subject': 'Chemistry',
     'question': 'Relative acidic strength of alcohol, phenol, water and carboxylic acid is:',
     'options': {'A': 'Carboxylic acid > Alcohol > Phenol > Water',
                 'C': 'Phenol > Carboxylic acid > Alcohol > Water',
                 'B': 'Carboxylic acid > Phenol > Water > Alcohol',
                 'D': 'Water > Alcohol > Phenol > Carboxylic acid'},
     'diagram_text': ''},
    {'number': 83,
     'subject': 'Chemistry',
     'question': 'Consider the following reaction: R―CHO + 2[Ag(NH3)2]OH R―COONH4 + 2Ag + 2NH3 + H2O This reaction '
                 'represents one of the following tests.',
     'options': {'A': 'Fehling test', 'C': 'Ninhydrin test', 'B': 'Benedict test', 'D': 'Tollens test'},
     'diagram_text': ''},
    {'number': 84,
     'subject': 'Chemistry',
     'question': 'In the reaction HCHO + HCN → cyanohydrin, the nucleophile is:',
     'options': {'A': 'CN―', 'C': 'Cl', 'B': 'HCl', 'D': 'OH'},
     'diagram_text': 'A reaction HCHO + HCN → cyanohydrin is shown; the nucleophile in the reaction must be identified.'},
    {'number': 85,
     'subject': 'Chemistry',
     'question': 'Which one of the following compounds belongs to the homologous series of aldehydes?',
     'options': {'A': 'H C Cl', 'C': 'H C H O O', 'B': 'H C NH2', 'D': 'H C OC2 H5'},
     'diagram_text': 'Four structural formulas (A–D) are shown; the task is to identify the compound belonging to the '
                     'aldehyde homologous series.'},
    {'number': 86,
     'subject': 'Chemistry',
     'question': 'CH3COOH + PCl5 ? The products of the above reaction are:',
     'options': {'A': 'CH₃COCl + POCl₃ + HCl',
                 'C': 'CH₃Cl + POCl₃ + HCl',
                 'B': 'CH₃COCl + POCl₂ + HCl',
                 'D': 'CH₃COCl + POCl₃ + H₂'},
     'diagram_text': ''},
    {'number': 87,
     'subject': 'Chemistry',
     'question': 'CH3CN + HCl A + B (in the presence of water) In the above reaction, A and B are:',
     'options': {'A': 'Acetic acid and acid amide',
                 'C': 'Acetic acid and methyl chloride',
                 'B': 'Acetic acid and ammonia',
                 'D': 'Acetic acid and ammonium chloride'},
     'diagram_text': ''},
    {'number': 88,
     'subject': 'Chemistry',
     'question': 'Consider the following reaction: CH3COOH + Mg (metal) ? What product will form?',
     'options': {'A': 'Magnesium formate', 'C': 'Magnesium ion', 'B': 'Magnesium acetate', 'D': 'Carboxylate ion'},
     'diagram_text': ''},
    {'number': 89,
     'subject': 'Chemistry',
     'question': 'The ―NH―CO is called:',
     'options': {'A': 'Amide group', 'C': 'Protein linkage', 'B': 'Amino group', 'D': 'Peptide linkage'},
     'diagram_text': ''},
    {'number': 90,
     'subject': 'Chemistry',
     'question': 'Which one of the following is an alpha amino acid?',
     'options': {'A': 'CH₃–CH(NH₂)–COOH (alanine)',
                 'C': 'CH₃–CH(NH₂)–CH₂–COOH',
                 'B': 'H₂N–CH₂–COOH (glycine)',
                 'D': 'HOOC–CH(NH₂)–CH–CH₃'},
     'diagram_text': 'Four structural formulas (A–D) of amino acids are shown; the task is to identify an alpha amino '
                     'acid.'},
    {'number': 91,
     'subject': 'Chemistry',
     'question': 'Which of the following has an amino R-group?',
     'options': {'A': 'Lysine', 'C': 'Valine', 'B': 'Proline', 'D': 'Alanine'},
     'diagram_text': ''},
    {'number': 92,
     'subject': 'Chemistry',
     'question': 'At intermediate value of pH, amino acids form Zwitter ions containing:',
     'options': {'A': '―N+H3 and COO―', 'C': '―N+H3 and COOH', 'B': '―NH3 and COO―', 'D': '―NH3 and COOH'},
     'diagram_text': ''},
    {'number': 93,
     'subject': 'Chemistry',
     'question': 'When hexane dioic acid is heated with hexamethylene diamine, the compound formed is:',
     'options': {'A': 'Polypeptide', 'C': 'Ester', 'B': 'Addition polymer', 'D': 'Nylon 6,6'},
     'diagram_text': ''},
    {'number': 94,
     'subject': 'Chemistry',
     'question': 'A polymer in which the number of amino acid residue is greater than 100 or molecular mass is greater '
                 'than 1000, is known as:',
     'options': {'A': 'Protein', 'C': 'Dipeptide', 'B': 'Polypeptide', 'D': 'Tripeptide'},
     'diagram_text': ''},
    {'number': 95,
     'subject': 'Chemistry',
     'question': 'Aspartic acid is an acidic amino acid. Which of the following has its chemical formula?',
     'options': {'A': 'CH₃–CH(NH₂)–COOH',
                 'C': 'CH₃–CH(NH₂)–CH₂–COOH',
                 'B': 'HOOC–CH(NH₂)–COOH',
                 'D': 'CH₃–C(H)(NH₂)–CH–COOH'},
     'diagram_text': 'Four structural formulas (A–D) are shown; the task is to identify the chemical formula of aspartic '
                     'acid.'},
    {'number': 96,
     'subject': 'Chemistry',
     'question': 'Glucose and fructose are common examples of:',
     'options': {'A': 'Pentoses', 'C': 'Heptoses', 'B': 'Hexoses', 'D': 'Butoses'},
     'diagram_text': ''},
    {'number': 97,
     'subject': 'Chemistry',
     'question': 'The reaction between fats and caustic soda is called:',
     'options': {'A': 'Hydrogenolysis', 'C': 'Carboxylation', 'B': 'Fermentation', 'D': 'Saponification'},
     'diagram_text': ''},
    {'number': 98,
     'subject': 'Chemistry',
     'question': 'Macromolecules are described as large molecules built up from small repeating units known as:',
     'options': {'A': 'Monomers', 'C': 'Metameres', 'B': 'Isomers', 'D': 'Tautomer'},
     'diagram_text': ''},
    {'number': 99,
     'subject': 'Chemistry',
     'question': 'Polyvinyl chloride is an example of:',
     'options': {'A': 'Addition polymer', 'C': 'Biopolymer', 'B': 'Condensation polymer', 'D': 'Thermosetting polymer'},
     'diagram_text': ''},
    {'number': 100,
     'subject': 'Chemistry',
     'question': 'Terylene, a polyester is an example of:',
     'options': {'A': 'Biopolymer', 'C': 'Condensation polymer', 'B': 'Lipids', 'D': 'Addition polymer'},
     'diagram_text': ''},
    {'number': 101,
     'subject': 'Chemistry',
     'question': 'The suspected liver carcinogen which also has negative reproduction and developmental effect on humans '
                 'is:',
     'options': {'A': 'Iodoform', 'C': 'Tropoform', 'B': 'Bromoform', 'D': 'Chloroform'},
     'diagram_text': ''},
    {'number': 102,
     'subject': 'Chemistry',
     'question': 'Peroxyacetyl nitrate is an irritant to human beings and it effects:',
     'options': {'A': 'Nose', 'C': 'Ears', 'B': 'Stomach', 'D': 'Eyes'},
     'diagram_text': ''},
    {'number': 103,
     'subject': 'English',
     'question': 'She managed to __________ a ticket for the cricket match.',
     'options': {'A': 'Procure', 'C': 'Improvise', 'B': 'Obscure', 'D': 'Preclude'},
     'diagram_text': ''},
    {'number': 104,
     'subject': 'English',
     'question': 'Things have got out of hand; we must take steps to _________ the situation',
     'options': {'A': 'Rectify', 'C': 'Purify', 'B': 'Pacify', 'D': 'Testify'},
     'diagram_text': ''},
    {'number': 105,
     'subject': 'English',
     'question': 'George Orwell’s animal farm is a stinging ________ on the Russian revolution',
     'options': {'A': 'Myth', 'C': 'Fallacy', 'B': 'Satire', 'D': 'Legend'},
     'diagram_text': ''},
    {'number': 106,
     'subject': 'English',
     'question': 'All the _______ and ceremony of the royal wedding was telecast on the national television circuit.',
     'options': {'A': 'Festival',
                 'C': 'Pomp',
                 'B': 'Romp',
                 'D': 'Happiness SPOT THE ERROR: In the following sentences, some segments of each sentence are '
                      'underlined. Your task is to identify that underlined segment of the sentence, which contains the '
                      'mistake that needs to be corrected. Fill the Circle corresponding to that letter under the segment '
                      'in the MCQ Response From.'},
     'diagram_text': ''},
    {'number': 107,
     'subject': 'English',
     'question': 'The patient’s blood analysis shows that there is a big number of amorphous cells which are quiet '
                 'unidentifiable.',
     'options': {'A': '[Underlined segment A in source]',
                 'B': '[Underlined segment B in source]',
                 'C': '[Underlined segment C in source]',
                 'D': '[Underlined segment D in source]'},
     'diagram_text': ''},
    {'number': 108,
     'subject': 'English',
     'question': 'The police, in their investigation, used coercive measure to get favorable statement from the accused.',
     'options': {'A': '[Underlined segment A in source]',
                 'B': '[Underlined segment B in source]',
                 'C': '[Underlined segment C in source]',
                 'D': '[Underlined segment D in source]'},
     'diagram_text': ''},
    {'number': 109,
     'subject': 'English',
     'question': 'Your argument is simply abstruse as there is no clarity of thought and coherence in ideas and it also '
                 'lack vision.',
     'options': {'A': '[Underlined segment A in source]',
                 'B': '[Underlined segment B in source]',
                 'C': '[Underlined segment C in source]',
                 'D': '[Underlined segment D in source]'},
     'diagram_text': ''},
    {'number': 110,
     'subject': 'English',
     'question': 'The workers were raising much hue and cry when their demands were turned away.',
     'options': {'A': '[Underlined segment A in source]',
                 'B': '[Underlined segment B in source]',
                 'C': '[Underlined segment C in source]',
                 'D': '[Underlined segment D in source]'},
     'diagram_text': ''},
    {'number': 111,
     'subject': 'English',
     'question': 'The disease is uncurable without the judicious use of antibiotics.',
     'options': {'A': '[Underlined segment A in source]',
                 'B': '[Underlined segment B in source]',
                 'C': '[Underlined segment C in source]',
                 'D': '[Underlined segment D in source]'},
     'diagram_text': ''},
    {'number': 112,
     'subject': 'English',
     'question': 'The younger sister hopes to emulate her elder sister’s sporting achievement as she is putting up hectic '
                 'effort.',
     'options': {'A': '[Underlined segment A in source]',
                 'B': '[Underlined segment B in source]',
                 'C': '[Underlined segment C in source]',
                 'D': '[Underlined segment D in source]'},
     'diagram_text': ''},
    {'number': 113,
     'subject': 'English',
     'question': 'Choose the CORRECT sentence.',
     'options': {'A': 'The government should accrue taxes for strengthen the economy of the country.',
                 'B': 'The government should accrue taxes in strengthen the economy of the country.',
                 'C': 'The government should accrue taxes to strengthen the economy of the country.',
                 'D': 'The government should accrue taxes by strengthen the economy of the country.'},
     'diagram_text': ''},
    {'number': 114,
     'subject': 'English',
     'question': 'Choose the CORRECT sentence.',
     'options': {'A': 'Foreign trade have assumed greater importance in recent years.',
                 'B': 'Foreign trade is assumed greater importance in recent years.',
                 'C': 'Foreign trade has assumed greater importance in recent years.',
                 'D': 'Foreign trade shall assumed greater importance in recent years.'},
     'diagram_text': ''},
    {'number': 115,
     'subject': 'English',
     'question': 'Choose the CORRECT sentence.',
     'options': {'A': 'The space programme has been battered in bureaucratic wrangling.',
                 'B': 'The space programme has been battered into bureaucratic wrangling.',
                 'C': 'The space programme has been battered by bureaucratic wrangling.',
                 'D': 'The space programme has been battered to bureaucratic wrangling.'},
     'diagram_text': ''},
    {'number': 116,
     'subject': 'English',
     'question': 'Choose the CORRECT sentence.',
     'options': {'A': 'He will has to deal with the problem by showing adroitness.',
                 'B': 'He will have to deal with the problem by showing adroitness.',
                 'C': 'He will had to deal with the problem by showing adroitness.',
                 'D': 'He will having to deal with the problem by showing adroitness.'},
     'diagram_text': ''},
    {'number': 117,
     'subject': 'English',
     'question': 'Choose the CORRECT sentence.',
     'options': {'A': 'He does possesses altruistic behavior.',
                 'C': 'He does possessing altruistic behavior.',
                 'B': 'He does possess altruistic behavior.',
                 'D': 'He does possessed altruistic behavior.'},
     'diagram_text': ''},
    {'number': 118,
     'subject': 'English',
     'question': 'Choose the CORRECT sentence.',
     'options': {'A': 'He has great affinity in nature.',
                 'C': 'He has great affinity by nature.',
                 'B': 'He has great affinity with nature.',
                 'D': 'He has great affinity at nature.'},
     'diagram_text': ''},
    {'number': 119,
     'subject': 'English',
     'question': 'Choose the CORRECT sentence.',
     'options': {'A': 'He stands on arms akimbo.',
                 'C': 'He stands with arms akimbo.',
                 'B': 'He stands to arms akimbo.',
                 'D': 'He stands through arms akimbo.'},
     'diagram_text': ''},
    {'number': 120,
     'subject': 'English',
     'question': 'Choose the CORRECT sentence.',
     'options': {'A': 'An amorphous mass of cells are difficult to understand.',
                 'B': 'An amorphous mass of cells were difficult to understand.',
                 'C': 'An amorphous mass of cells had difficult to understand.',
                 'D': 'An amorphous mass of cells is difficult to understand.'},
     'diagram_text': ''},
    {'number': 121,
     'subject': 'English',
     'question': 'Choose the CORRECT sentence.',
     'options': {'A': 'He is suffering to anaphylactic shock.',
                 'C': 'He is suffering from anaphylactic shock.',
                 'B': 'He is suffering in anaphylactic shock.',
                 'D': 'He is suffering into anaphylactic shock.'},
     'diagram_text': ''},
    {'number': 122,
     'subject': 'English',
     'question': 'Choose the CORRECT sentence.',
     'options': {'A': 'If you had asked him, he would had accepted the offer with alacrity.',
                 'B': 'If you had asked him, he would have being accepted the offer with alacrity.',
                 'C': 'If you had asked him, he would have accepted the offer with alacrity.',
                 'D': 'If you had asked him, he would been accepted the offer with alacrity.'},
     'diagram_text': ''},
    {'number': 123,
     'subject': 'English',
     'question': 'Select the NEAREST CORRECT MEANING of the word: MUSE',
     'options': {'A': 'Wander', 'C': 'Robust', 'B': 'Fonder', 'D': 'Ponder'},
     'diagram_text': ''},
    {'number': 124,
     'subject': 'English',
     'question': 'Select the NEAREST CORRECT MEANING of the word: FECKLESS',
     'options': {'A': 'Useless', 'C': 'Dauntless', 'B': 'Careless', 'D': 'Fearless'},
     'diagram_text': ''},
    {'number': 125,
     'subject': 'English',
     'question': 'Select the NEAREST CORRECT MEANING of the word: MOSAIC',
     'options': {'A': 'Pattern', 'C': 'Ordinary', 'B': 'Mortal', 'D': 'Musical'},
     'diagram_text': ''},
    {'number': 126,
     'subject': 'English',
     'question': 'Select the NEAREST CORRECT MEANING of the word: INSCRUTABLE',
     'options': {'A': 'Immoral', 'C': 'Enigmatic', 'B': 'Unethical', 'D': 'Unaccountable'},
     'diagram_text': ''},
    {'number': 127,
     'subject': 'English',
     'question': 'Select the NEAREST CORRECT MEANING of the word: JUXTAPOSE',
     'options': {'A': 'Justify', 'C': 'Expose', 'B': 'Compare', 'D': 'Jettison'},
     'diagram_text': ''},
    {'number': 128,
     'subject': 'English',
     'question': 'Select the NEAREST CORRECT MEANING of the word: LACERATING',
     'options': {'A': 'Landing', 'C': 'Flagging', 'B': 'Tearing', 'D': 'Lactating'},
     'diagram_text': ''},
    {'number': 129,
     'subject': 'English',
     'question': 'Select the NEAREST CORRECT MEANING of the word: EMPATHY',
     'options': {'A': 'Fictitious', 'C': 'Ability', 'B': 'Facility', 'D': 'Felicity'},
     'diagram_text': ''},
    {'number': 130,
     'subject': 'English',
     'question': 'Select the NEAREST CORRECT MEANING of the word: EVANESCENT',
     'options': {'A': 'Evident', 'C': 'Event', 'B': 'Permanent', 'D': 'transitory'},
     'diagram_text': ''},
    {'number': 131,
     'subject': 'English',
     'question': 'Select the NEAREST CORRECT MEANING of the word: SIDLE',
     'options': {'A': 'Sneak', 'C': 'Sledge', 'B': 'Sift', 'D': 'Sieve'},
     'diagram_text': ''},
    {'number': 132,
     'subject': 'English',
     'question': 'Select the NEAREST CORRECT MEANING of the word: DISSONANCE',
     'options': {'A': 'Inconsistency', 'C': 'Perceptible', 'B': 'Expansion', 'D': 'WrapPart'},
     'diagram_text': ''},
    {'number': 133,
     'subject': 'Biology',
     'question': 'When chromosomes uncoil, the nucleoli are reformed and two nuclei are the two poles of the cell; stage '
                 'is known as',
     'options': {'A': 'Prophase', 'C': 'Telophase', 'B': 'Metaphase', 'D': 'Anaphase'},
     'diagram_text': ''},
    {'number': 134,
     'subject': 'Biology',
     'question': 'Mental retardation, short stature, broad face and squint eyes are the symptoms of',
     'options': {'A': 'Down’s syndrome', 'C': 'Turner’s syndrome', 'B': 'Klinefelter’s syndrome', 'D': 'XYZ syndrome'},
     'diagram_text': ''},
    {'number': 135,
     'subject': 'Biology',
     'question': 'Chiasmata formation takes place during the process which is known as',
     'options': {'A': 'Crossing Over', 'C': 'Pairing', 'B': 'Attachment', 'D': 'Leptotene'},
     'diagram_text': ''},
    {'number': 136,
     'subject': 'Biology',
     'question': 'Healing of a wound and repair is the phenomenon which takes place by the process of',
     'options': {'A': 'Mitosis', 'C': 'Cell Growth', 'B': 'Meiosis', 'D': 'Mitosis & Meiosis'},
     'diagram_text': ''},
    {'number': 137,
     'subject': 'Biology',
     'question': 'Which one of the following is the main cause of cancer?',
     'options': {'A': 'Mutation', 'C': 'Regulated Mitosis', 'B': 'Controlled Cell Division', 'D': 'Haploid Division'},
     'diagram_text': ''},
    {'number': 138,
     'subject': 'Biology',
     'question': 'The covalent bond formed between two monosaccharides is called',
     'options': {'A': 'Glycosidic Bond', 'C': 'Peptide Bond', 'B': 'Hydrogen Bond', 'D': 'Disulphide'},
     'diagram_text': ''},
    {'number': 139,
     'subject': 'Biology',
     'question': 'The bond formed between glucose and fructose form sucrose is',
     'options': {'A': '1,4 Glycosidic Linkage',
                 'C': '1,6 Glycosidic Linkage',
                 'B': '1,2 Glycosidic Linkage',
                 'D': '1,3 Glycosidic Linkage'},
     'diagram_text': ''},
    {'number': 140,
     'subject': 'Biology',
     'question': 'In an amino acid in which the R-group is H, its name will be',
     'options': {'A': 'Alanine', 'C': 'Leucine', 'B': 'Glycine', 'D': 'Valine'},
     'diagram_text': ''},
    {'number': 141,
     'subject': 'Biology',
     'question': 'Fatty acid are the organic compounds containing hydrogen, oxygen and one of the following are',
     'options': {'A': '–COOH', 'C': 'Acyl', 'B': '–NH2', 'D': 'Sucrose'},
     'diagram_text': ''},
    {'number': 142,
     'subject': 'Biology',
     'question': 'Posomes are used in gene therapy against',
     'options': {'A': 'Hypercholesterolemia',
                 'C': 'Cystic Fibrosis',
                 'B': 'Coronary Artery Angioplasty',
                 'D': 'Severe Combined Immunodeficiency Syndrome (SCID)'},
     'diagram_text': ''},
    {'number': 143,
     'subject': 'Biology',
     'question': 'Genetically engineered cells are introduced into bone marrow cells in the treatment of',
     'options': {'A': 'Hypercholesterolemia',
                 'C': 'Cystic Fibrosis',
                 'B': 'Severe Combined Immunodeficiency Syndrome',
                 'D': 'Coronary Artery Angioplasty (SCID)'},
     'diagram_text': ''},
    {'number': 144,
     'subject': 'Biology',
     'question': 'Which one of the following is depleting and causing thinning of ozone?',
     'options': {'A': 'Chlorine', 'C': 'Chlorofluorocarbon', 'B': 'Bromine', 'D': 'Carbon'},
     'diagram_text': ''},
    {'number': 145,
     'subject': 'Biology',
     'question': 'The typical environment of a particular organism population community is called',
     'options': {'A': 'Niche', 'C': 'Habitat', 'B': 'Ecosystem', 'D': 'Biosphere'},
     'diagram_text': ''},
    {'number': 146,
     'subject': 'Biology',
     'question': 'Excessive enrichment of water with nutrients by human activity by which large amount of living organic '
                 'matter grows is called',
     'options': {'A': 'Archeotrophication', 'C': 'Enrichment', 'B': 'Eutrophication', 'D': 'Low Trophication'},
     'diagram_text': ''},
    {'number': 147,
     'subject': 'Biology',
     'question': 'In an ecosystem, mycorrhizae is an example of',
     'options': {'A': 'Symbiosis', 'C': 'Commensalism', 'B': 'Predation', 'D': 'Parasitism'},
     'diagram_text': ''},
    {'number': 148,
     'subject': 'Biology',
     'question': 'Successive stages of eating and being eaten by which recycling of materials and flow of energy takes '
                 'place is called',
     'options': {'A': 'Food Chain', 'C': 'Trophic Level', 'B': 'Food Web', 'D': 'Food Link'},
     'diagram_text': ''},
    {'number': 149,
     'subject': 'Biology',
     'question': 'The sex of individuals of next generation always depends on one of the parents who is',
     'options': {'A': 'Heterogametic', 'C': 'Isogametic', 'B': 'Homogametic', 'D': 'Isomorphic'},
     'diagram_text': ''},
    {'number': 150,
     'subject': 'Biology',
     'question': 'Which of the following will be hemophilic?',
     'options': {'A': 'XHXh', 'C': 'XhY', 'B': 'XHXH', 'D': 'XHY'},
     'diagram_text': ''},
    {'number': 151,
     'subject': 'Biology',
     'question': 'Which of the following is an example of X-linked recessive trait in humans?',
     'options': {'A': 'Hypophospatemic Rickets', 'C': 'Baldness', 'B': 'Colour Blindness', 'D': 'Beard Growth'},
     'diagram_text': ''},
    {'number': 152,
     'subject': 'Biology',
     'question': 'Which trait in human in an example of multiple alleles?',
     'options': {'A': 'Eye Colour', 'C': 'ABO-Blood Group', 'B': 'Skin Colour', 'D': 'Rh-Blood Group'},
     'diagram_text': ''},
    {'number': 153,
     'subject': 'Biology',
     'question': 'When a gene pair at one locus interacts with another gene at another locus, the interaction is called',
     'options': {'A': 'Dominance', 'C': 'Pleiotropy', 'B': 'Multiple Alleles', 'D': 'Epistasis'},
     'diagram_text': ''},
    {'number': 154,
     'subject': 'Biology',
     'question': 'The combination of a pentose sugar with a base result in a compound is known as',
     'options': {'A': 'Nucleotide', 'C': 'Nucleic Acid', 'B': 'Nucleoside', 'D': 'Polynucleotide'},
     'diagram_text': ''},
    {'number': 155,
     'subject': 'Biology',
     'question': 'An enzyme and substrate reacts through a special feature or site present in enzyme:',
     'options': {'A': 'Building Site', 'C': 'Catalyst Site', 'B': 'Active Site', 'D': 'Inhibition Site'},
     'diagram_text': ''},
    {'number': 156,
     'subject': 'Biology',
     'question': 'The non-protein part of enzyme which is covalently and permanently bonded is called',
     'options': {'A': 'Prosthetic Group', 'C': 'Co-Enzyme', 'B': 'Co-Factor', 'D': 'Activator'},
     'diagram_text': ''},
    {'number': 157,
     'subject': 'Biology',
     'question': 'One of the pyrimidine bases is absent in DNA',
     'options': {'A': 'Uracil', 'C': 'Cytosine', 'B': 'Thymine', 'D': 'Adenine'},
     'diagram_text': ''},
    {'number': 158,
     'subject': 'Biology',
     'question': 'Enzymes increase the rate of reaction by',
     'options': {'A': 'Increasing Temperature',
                 'C': 'Decreasing Activation Energy',
                 'B': 'Decreasing pH',
                 'D': 'Increasing Activation Energy'},
     'diagram_text': ''},
    {'number': 159,
     'subject': 'Biology',
     'question': 'Which one of the following diseases caused by enveloped RNA virus and spread in epidemic form?',
     'options': {'A': 'Influenza', 'C': 'Polio', 'B': 'Herpes Simplex', 'D': 'Small Pox'},
     'diagram_text': ''},
    {'number': 160,
     'subject': 'Biology',
     'question': 'The structure which contains the gene for drug resistance bacteria are',
     'options': {'A': 'Nucleoids', 'C': 'Chromatin Bodies', 'B': 'Mesosomes', 'D': 'Plasmids'},
     'diagram_text': ''},
    {'number': 161,
     'subject': 'Biology',
     'question': 'Antibiotics that kill microbes immediately are called',
     'options': {'A': 'Microbistatic', 'C': 'Biostatic', 'B': 'Microbicidal', 'D': 'Chemotherapeutic'},
     'diagram_text': ''},
    {'number': 162,
     'subject': 'Biology',
     'question': 'Which one of the following fungi causes vaginal thrush?',
     'options': {'A': 'Candida', 'C': 'Tortula', 'B': 'Aspergillus', 'D': 'Penicillium'},
     'diagram_text': ''},
    {'number': 163,
     'subject': 'Biology',
     'question': 'Body cavity of round worms is called',
     'options': {'A': 'Pseudocoelom', 'C': 'Acoelom', 'B': 'Coelom', 'D': 'Enteron'},
     'diagram_text': ''},
    {'number': 164,
     'subject': 'Biology',
     'question': 'Fasciola is endoparasite of',
     'options': {'A': 'Colon', 'C': 'Small Intestine', 'B': 'Liver', 'D': 'Bile Duct'},
     'diagram_text': ''},
    {'number': 165,
     'subject': 'Biology',
     'question': 'Trypanosoma is transmitted in human beings by',
     'options': {'A': 'Plasmodium', 'C': 'House Fly', 'B': 'Anopheles', 'D': 'Tsetse Fly'},
     'diagram_text': ''},
    {'number': 166,
     'subject': 'Biology',
     'question': 'The nervous system develops from which of the following layer during embryonic development of animals',
     'options': {'A': 'Mesoderm', 'C': 'Endoderm', 'B': 'Ectoderm', 'D': 'Mesoderm and Endoderm'},
     'diagram_text': ''},
    {'number': 167,
     'subject': 'Biology',
     'question': 'Endosperm is formed as a result of',
     'options': {'A': 'Pollination', 'C': 'Double Fertilization', 'B': 'Self-Pollination', 'D': 'Cross Pollination'},
     'diagram_text': ''},
    {'number': 168,
     'subject': 'Biology',
     'question': 'Which of the following enzyme is released in an inactive form',
     'options': {'A': 'Amylase', 'C': 'Enterokinase', 'B': 'Lipase', 'D': 'Pepsin'},
     'diagram_text': ''},
    {'number': 169,
     'subject': 'Biology',
     'question': 'Which of the following hormones stimulate the secretion of pancreatic juice from pancreas in liver?',
     'options': {'A': 'Secretin', 'C': 'Gastrin', 'B': 'Pepsinogen', 'D': 'Both Gastrin and Secretin'},
     'diagram_text': ''},
    {'number': 170,
     'subject': 'Biology',
     'question': 'In large intestine, vitamin k is formed by the activity of',
     'options': {'A': 'Symbiotic Bacteria',
                 'C': 'Parasitic Bacteria',
                 'B': 'Obligate Bacteria',
                 'D': 'Facultative Bacteria'},
     'diagram_text': ''},
    {'number': 171,
     'subject': 'Biology',
     'question': 'During swallowing of food which structure close nasal opening?',
     'options': {'A': 'Hard Palate', 'C': 'Epiglottis', 'B': 'Soft Palate', 'D': 'Larynx'},
     'diagram_text': ''},
    {'number': 172,
     'subject': 'Biology',
     'question': 'The right atrium of the heart usually receives the',
     'options': {'A': 'Deoxygenated Blood', 'C': 'Filtered Blood', 'B': 'Oxygenated Blood', 'D': 'Non-Filtered Blood'},
     'diagram_text': ''},
    {'number': 173,
     'subject': 'Biology',
     'question': 'The largest lymph duct called thoracic lymph duct drains into',
     'options': {'A': 'Subclavian Vein', 'C': 'Pulmonary Vein', 'B': 'Renal Vein', 'D': 'Hepatic Portal Vein'},
     'diagram_text': ''},
    {'number': 174,
     'subject': 'Biology',
     'question': 'Which protein plays a major role in maintaining osmotic balance?',
     'options': {'A': 'Albumin', 'C': 'Fibrinogen', 'B': 'Globulin', 'D': 'Prothrombin'},
     'diagram_text': ''},
    {'number': 175,
     'subject': 'Biology',
     'question': 'The type of agranulocytes which stays in blood for a few hours and then enters tissues and become '
                 'macrophages are',
     'options': {'A': 'Lymphocytes', 'C': 'Eosinophils', 'B': 'Monocyte', 'D': 'Basophils'},
     'diagram_text': ''},
    {'number': 176,
     'subject': 'Biology',
     'question': 'Reabsorption of water by counter current multiplier mechanism takes place at',
     'options': {'A': 'Proximal Tubule', 'C': 'Collecting Duct', 'B': 'Distal Tubule', 'D': 'Loop of Henle'},
     'diagram_text': ''},
    {'number': 177,
     'subject': 'Biology',
     'question': 'Antiduretic hormone helps in reabsorption of water by changing permeability of',
     'options': {'A': 'Proximal Tubule', 'C': 'Collecting Duct', 'B': 'Distal Tubule', 'D': 'Loop of Henle'},
     'diagram_text': ''},
    {'number': 178,
     'subject': 'Biology',
     'question': 'During peritoneal dialysis, dialysis fluid is introduced into which part of human body?',
     'options': {'A': 'Liver', 'C': 'Kidney', 'B': 'Abdomen', 'D': 'Pancreas'},
     'diagram_text': ''},
    {'number': 179,
     'subject': 'Biology',
     'question': 'Aldosterone helps in conservation or active absorption of',
     'options': {'A': 'Sodium', 'C': 'Potassium', 'B': 'Calcium', 'D': 'Bicarbonate Ions'},
     'diagram_text': ''},
    {'number': 180,
     'subject': 'Biology',
     'question': 'Maximum reabsorption takes place in which part of the nephron?',
     'options': {'A': 'Distal Tubule', 'C': 'Cortical Tissue', 'B': 'Villi', 'D': 'Proximal Tubule'},
     'diagram_text': ''},
    {'number': 181,
     'subject': 'Biology',
     'question': 'Over-activity of sympathetic nervous system causes',
     'options': {'A': 'Disturbance of Vision',
                 'C': 'Decrease in Blood Pressure',
                 'B': 'Constipation',
                 'D': 'Increase in Heart Rate'},
     'diagram_text': ''},
    {'number': 182,
     'subject': 'Biology',
     'question': 'Which structures respond when they are stimulated by impulse coming through motor neuron?',
     'options': {'A': 'Receptors', 'C': 'Effectors', 'B': 'Responses', 'D': 'Transduction'},
     'diagram_text': ''},
    {'number': 183,
     'subject': 'Biology',
     'question': 'Respiratory center is located in',
     'options': {'A': 'Cerebrum', 'C': 'Medulla', 'B': 'Cerebellum', 'D': 'Hypothalamus'},
     'diagram_text': ''},
    {'number': 184,
     'subject': 'Biology',
     'question': 'A neurological condition characterized by involuntary tremors, diminished motor activity and rigidity is '
                 'called',
     'options': {'A': 'Epilepsy', 'C': 'Alzheimer’s Disease', 'B': 'Parkinson’s Disease', 'D': 'Cerebullar Tumours'},
     'diagram_text': ''},
    {'number': 185,
     'subject': 'Biology',
     'question': 'A type of cell in human testes which produces testosterone is called',
     'options': {'A': 'Interstitial Cells', 'C': 'Sertoli Cells', 'B': 'Germ Cells', 'D': 'Spermatocytes'},
     'diagram_text': ''},
    {'number': 186,
     'subject': 'Biology',
     'question': 'Breakdown of endometrium during menstruation is due to',
     'options': {'A': 'Increase in Level of LH',
                 'C': 'Increase in Level of Progesterone',
                 'B': 'Decrease in Level of Progesterone',
                 'D': 'Increase in Level of Oestrogen'},
     'diagram_text': ''},
    {'number': 187,
     'subject': 'Biology',
     'question': 'Oogonia are produced in the germ cells',
     'options': {'A': 'Both Uterus and Cervix', 'C': 'Uterus', 'B': 'Cervix', 'D': 'Ovary'},
     'diagram_text': ''},
    {'number': 188,
     'subject': 'Biology',
     'question': 'Which of the following diseases can be prevented through vaccination?',
     'options': {'A': 'AIDS and Cancer', 'C': 'Typhoid and Cancer', 'B': 'Malaria and AIDS', 'D': 'Measles and Mumps'},
     'diagram_text': ''},
    {'number': 189,
     'subject': 'Biology',
     'question': 'Newly produced cells/individuals which are identical in each other are known as',
     'options': {'A': 'Genetically Modified', 'C': 'Transgenic Bacteria', 'B': 'Transgenic Animals', 'D': 'Clones'},
     'diagram_text': ''},
    {'number': 190,
     'subject': 'Biology',
     'question': 'Which of the following is a blood borne disease?',
     'options': {'A': 'Hepatitis', 'C': 'Influenza', 'B': 'Cholera', 'D': 'Candidiasis'},
     'diagram_text': ''},
    {'number': 191,
     'subject': 'Biology',
     'question': 'The control of pest has traditionally meant regulation by natural enemies, predators, parasites and '
                 'pathogens. This type of control is known as',
     'options': {'A': 'Cultural Control',
                 'C': 'Pesticides Control',
                 'B': 'Biological Control',
                 'D': 'Insecticides Control'},
     'diagram_text': ''},
    {'number': 192,
     'subject': 'Biology',
     'question': 'Which of the following organelles is concerned with the cell secretion',
     'options': {'A': 'Ribosomes', 'C': 'Lysosomes', 'B': 'Golgi Apparatus', 'D': 'Mitochondria'},
     'diagram_text': ''},
    {'number': 193,
     'subject': 'Biology',
     'question': 'Which of the following contains peptidoglycan cell wall?',
     'options': {'A': 'Penicillium', 'C': 'Adiantum', 'B': 'Bacterium', 'D': 'Polytrichum'},
     'diagram_text': ''},
    {'number': 194,
     'subject': 'Biology',
     'question': 'The inner membrane of mitochondria is folded to form finger like structure called',
     'options': {'A': 'Cristae', 'C': 'Matrix', 'B': 'Vesicle', 'D': 'Cisternae'},
     'diagram_text': ''},
    {'number': 195,
     'subject': 'Biology',
     'question': 'Interior of chloroplast is divided into heterogeneous structure, embedded in the matrix known as',
     'options': {'A': 'Grana', 'C': 'Thylakoids', 'B': 'Stroma', 'D': 'Cisternae'},
     'diagram_text': ''},
    {'number': 196,
     'subject': 'Biology',
     'question': 'In which phase of the cell division the metabolic activity of the nucleus is high?',
     'options': {'A': 'Mitosis', 'C': 'Meiosis', 'B': 'Interphase', 'D': 'Cell Cycle'},
     'diagram_text': ''},
    {'number': 197,
     'subject': 'Biology',
     'question': 'Luteinizing hormone triggers',
     'options': {'A': 'Cessation of Oogenesis', 'C': 'Ovulation', 'B': 'Breakdown of Oocyte', 'D': 'Development of Zygote'},
     'diagram_text': ''},
    {'number': 198,
     'subject': 'Biology',
     'question': 'Syphilis is a sexually transmitted disease which is caused by',
     'options': {'A': 'HIV / AIDS', 'C': 'Treponema Pallidum', 'B': 'Pseudomonas Pyogenes', 'D': 'Neisseria'},
     'diagram_text': ''},
    {'number': 199,
     'subject': 'Biology',
     'question': 'Muscle is made up of many cells which are referred to as',
     'options': {'A': 'Myofilaments', 'C': 'Sarcolemma', 'B': 'Myofibrils', 'D': 'Muscles Fiber'},
     'diagram_text': ''},
    {'number': 200,
     'subject': 'Biology',
     'question': 'The length of myofibril from one Z-band to the next is known as',
     'options': {'A': 'Sarcomere', 'C': 'Sarcoplasm', 'B': 'Sarcolemma', 'D': 'Muscle Fiber'},
     'diagram_text': ''},
    {'number': 201,
     'subject': 'Biology',
     'question': 'Calcium ions released during a muscle fiber contraction attach with',
     'options': {'A': 'Myosin', 'C': 'Tropomyosin', 'B': 'Actin', 'D': 'Troponin'},
     'diagram_text': ''},
    {'number': 202,
     'subject': 'Biology',
     'question': 'A muscle condition resulting from the accumulation of lactic acid and ionic imbalance is:',
     'options': {'A': 'Tetany', 'C': 'Cramp', 'B': 'Muscle Fatigue', 'D': 'Tetanus'},
     'diagram_text': ''},
    {'number': 203,
     'subject': 'Biology',
     'question': 'The pigment which stores oxygen in muscles is',
     'options': {'A': 'Hemoglobin', 'C': 'Myosin', 'B': 'Myoglobin', 'D': 'Actinomyosin'},
     'diagram_text': ''},
    {'number': 204,
     'subject': 'Biology',
     'question': 'Neurosecretory cells are present in which part of brain',
     'options': {'A': 'Hypothalamus', 'C': 'Pons', 'B': 'Midbrain', 'D': 'Cerebellum'},
     'diagram_text': ''},
    {'number': 205,
     'subject': 'Biology',
     'question': 'Which of the following is the function of glucagon hormone?',
     'options': {'A': 'Glycogen to Glucose',
                 'C': 'Glucose to Lipids',
                 'B': 'Glucose to Glycogen',
                 'D': 'Glucose to Proteins'},
     'diagram_text': ''},
    {'number': 206,
     'subject': 'Biology',
     'question': 'Addison’s disease is caused due to destruction of',
     'options': {'A': 'Adrenal Cortex', 'C': 'Adrenal Medulla', 'B': 'Pituitary Adrenal Axis', 'D': 'Hypothalamus'},
     'diagram_text': ''},
    {'number': 207,
     'subject': 'Biology',
     'question': 'Which group of hormones is made up of amino acids and their derivatives?',
     'options': {'A': 'Vasopressin and ADH',
                 'C': 'Osterogen and Testosterone',
                 'B': 'Epinephrine and Non-Epinephrine',
                 'D': 'Insulin and Glucagon'},
     'diagram_text': ''},
    {'number': 208,
     'subject': 'Biology',
     'question': 'Thymus gland is involved in maturation of',
     'options': {'A': 'Platelets', 'C': 'Eosinophils', 'B': 'B-Lymphocytes', 'D': 'T-Lymphocytes'},
     'diagram_text': ''},
    {'number': 209,
     'subject': 'Biology',
     'question': 'In passive immunity which of the following component are injected into blood',
     'options': {'A': 'Antigens', 'C': 'Serum', 'B': 'Immunogens', 'D': 'Immunoglobulins'},
     'diagram_text': ''},
    {'number': 210,
     'subject': 'Biology',
     'question': 'Mucous membranes are part of body defense system and they offer',
     'options': {'A': 'Physical Barriers',
                 'C': 'Chemical Barriers',
                 'B': 'Mechanical Barriers',
                 'D': 'Biological Barriers'},
     'diagram_text': ''},
    {'number': 211,
     'subject': 'Biology',
     'question': 'Immediate protection is obtained from',
     'options': {'A': 'Passive Immunity', 'C': 'Vaccination', 'B': 'Active Immunity', 'D': 'Natural Activity Immunity'},
     'diagram_text': ''},
    {'number': 212,
     'subject': 'Biology',
     'question': 'The immunity in which T-cells recognize the antigens or micro-organisms is known as',
     'options': {'A': 'Tissue Grafting',
                 'C': 'Cell Mediated Immunity / Response',
                 'B': 'Phagocytosis',
                 'D': 'Hormonal Immunity / Response'},
     'diagram_text': ''},
    {'number': 213,
     'subject': 'Biology',
     'question': 'Oxidative phosphorylation, synthesis of ATP in the presence of oxygen occurs in:',
     'options': {'A': 'All Types of Cells',
                 'C': 'All Primitive Cells',
                 'B': 'All Anaerobic Cells',
                 'D': 'All Aerobic Cells'},
     'diagram_text': ''},
    {'number': 214,
     'subject': 'Biology',
     'question': 'Glycolysis is the breakdown of glucose into two molecules of',
     'options': {'A': 'Glycerate', 'C': 'Pyruvate', 'B': 'Lactic Acid', 'D': 'Succinic Acid'},
     'diagram_text': ''},
    {'number': 215,
     'subject': 'Biology',
     'question': 'Before entering Krebs’s cycle, the pyruvate is first decarboxylated and oxidized into',
     'options': {'A': 'Alpha Ketoglutaric Acid', 'C': 'Glyceric Acid', 'B': 'Citric Acid', 'D': 'Acetic Acid'},
     'diagram_text': ''},
    {'number': 216,
     'subject': 'Biology',
     'question': 'Some electron from the second primary acceptor may pass back to chlorophyll molecules by electron '
                 'carrier system, yielding ATP. This process is called',
     'options': {'A': 'Phosphorylation',
                 'C': 'Non-Cyclic Phosphorylation',
                 'B': 'Photophosphorylation',
                 'D': 'Cyclic Phosphorylation'},
     'diagram_text': ''},
    {'number': 217,
     'subject': 'Biology',
     'question': 'Z-scheme is used for',
     'options': {'A': 'Non-Cyclic Photophosphorylation',
                 'C': 'Both Cyclic and Non-Cyclic Photophosphorylation',
                 'B': 'Cyclic Photophosphorylation',
                 'D': 'Oxidative Phosphorylation'},
     'diagram_text': ''},
    {'number': 218,
     'subject': 'Biology',
     'question': 'The common vectors used in recombinant DNA technology are',
     'options': {'A': 'Probes', 'C': 'Plasmids', 'B': 'Palindromes', 'D': 'Prions'},
     'diagram_text': ''},
    {'number': 219,
     'subject': 'Biology',
     'question': 'The enzyme used to isolate gene from DNA is',
     'options': {'A': 'Helicase', 'C': 'Restriction Enzyme', 'B': 'Reverse Transcriptase', 'D': 'DNA Polymerase'},
     'diagram_text': ''},
    {'number': 220,
     'subject': 'Biology',
     'question': 'Which one of the following enzymes is temperature insensitive?',
     'options': {'A': 'DNA Polymerase I', 'C': 'DNA Polymerase III', 'B': 'Taq Polymerase', 'D': 'RNA Polymerase'},
     'diagram_text': ''},
]