"""
MDCAT Mock Test 19
==================
Full-length mock test: 180 MCQs
Weightage: Biology 81 | Chemistry 45 | Physics 36 | English 9 | Logical Reasoning 9
Difficulty mix (approx): 30% Easy / 50% Medium / 20% Hard, distributed throughout.

Includes 5 image/diagram-based questions (2 Biology, 1 Chemistry, 2 Physics).
Each such question has an "image" key giving a relative path to a PNG diagram
that must be viewed alongside the question (images/ subfolder, shipped alongside
this file). Diagrams: a labeled chloroplast cross-section, a labeled heart
cross-section identifying the aorta, a solubility-vs-temperature curve, a
parallel-then-series resistor circuit, and a concave-mirror ray diagram
(object placed between F and C).

Each question is a dict:
    id, subject, topic, difficulty, question, [image], options (A-D), answer (correct letter)

Run this file directly to print a summary / sanity-check the paper.
"""

QUESTIONS = [
{"id":1,"subject":"Biology","topic":"Biomolecules","difficulty":"Easy",
 "question":"Which of these compounds is classified as a monosaccharide?",
 "options":{"A":"Sucrose","B":"Glucose","C":"Starch","D":"Cellulose"},"answer":"B"},
{"id":2,"subject":"Biology","topic":"Biomolecules","difficulty":"Easy",
 "question":"Nucleic acids are polymers built from repeating units called:",
 "options":{"A":"Nucleotides","B":"Amino acids","C":"Fatty acids","D":"Monosaccharides"},"answer":"A"},
{"id":3,"subject":"Biology","topic":"Biomolecules","difficulty":"Medium",
 "question":"The tertiary structure of a protein is stabilized mainly by interactions among:",
 "options":{"A":"Nucleotide bases","B":"Adjacent DNA strands","C":"Only the polypeptide backbone atoms","D":"Side-chain (R group) interactions such as hydrogen bonds, ionic bonds, and hydrophobic interactions"},"answer":"D"},
{"id":4,"subject":"Biology","topic":"Biomolecules","difficulty":"Medium",
 "question":"Phospholipids form the main structural component of cell membranes because:",
 "options":{"A":"They dissolve freely in water","B":"They contain no fatty acid chains","C":"They arrange into a bilayer with hydrophilic heads facing outward and hydrophobic tails facing inward","D":"They are entirely hydrophobic"},"answer":"C"},
{"id":5,"subject":"Biology","topic":"Biomolecules","difficulty":"Hard",
 "question":"An enzyme's substrate specificity is determined mainly by:",
 "options":{"A":"The precise three-dimensional shape of the active site being complementary to the substrate","B":"The random collision of any molecule with the enzyme","C":"The enzyme's overall size alone","D":"The temperature of the surrounding solution alone"},"answer":"A"},
{"id":6,"subject":"Biology","topic":"Enzymes","difficulty":"Easy",
 "question":"The substance upon which an enzyme acts is called the:",
 "options":{"A":"Substrate","B":"Coenzyme","C":"Product","D":"Cofactor"},"answer":"A"},
{"id":7,"subject":"Biology","topic":"Enzymes","difficulty":"Medium",
 "question":"Increasing substrate concentration increases enzyme reaction rate until:",
 "options":{"A":"All enzyme active sites become saturated","B":"The enzyme is destroyed","C":"The reaction reverses","D":"The temperature decreases"},"answer":"A"},
{"id":8,"subject":"Biology","topic":"Enzymes","difficulty":"Medium",
 "question":"Enzymes that require a non-protein metal ion to function properly rely on a:",
 "options":{"A":"Zymogen","B":"Prosthetic sugar","C":"Coenzyme","D":"Cofactor"},"answer":"D"},
{"id":9,"subject":"Biology","topic":"Enzymes","difficulty":"Hard",
 "question":"Allosteric regulation of an enzyme involves a regulatory molecule binding:",
 "options":{"A":"A site other than the active site, causing a conformational change that affects catalytic activity","B":"The active site directly, mimicking the substrate","C":"Only irreversibly denaturing the enzyme","D":"The substrate itself, not the enzyme"},"answer":"A"},
{"id":10,"subject":"Biology","topic":"Cell Biology","difficulty":"Easy",
 "question":"The organelle responsible for breaking down worn-out cell components and foreign material using digestive enzymes is the:",
 "options":{"A":"Peroxisome","B":"Ribosome","C":"Centriole","D":"Lysosome"},"answer":"D"},
{"id":11,"subject":"Biology","topic":"Cell Biology","difficulty":"Easy",
 "question":"The rough endoplasmic reticulum is studded with ribosomes and functions mainly in:",
 "options":{"A":"Lipid synthesis","B":"Protein synthesis and processing for secretion","C":"ATP production","D":"Photosynthesis"},"answer":"B"},
{"id":12,"subject":"Biology","topic":"Cell Biology","difficulty":"Medium",
 "question":"The diagram shows a cross-section of a chloroplast with structures labeled P, Q, R, and S (the outer and inner membranes, the stacked thylakoid membranes forming a granum, and the fluid-filled stroma). Which labeled structure is the stack of membranes where the light-dependent reactions occur?",
 "image":"images/q_chloroplast_crosssection_diagram.png",
 "options":{"A":"Structure S (inner membrane)","B":"Structure P (outer membrane)","C":"Structure Q (granum / thylakoids)","D":"Structure R (stroma)"},"answer":"C"},
{"id":13,"subject":"Biology","topic":"Cell Biology","difficulty":"Medium",
 "question":"The cytoskeleton component made of actin filaments is primarily involved in:",
 "options":{"A":"ATP synthesis exclusively","B":"Muscle contraction and maintenance of cell shape","C":"Photosynthesis","D":"DNA replication"},"answer":"B"},
{"id":14,"subject":"Biology","topic":"Cell Biology","difficulty":"Hard",
 "question":"A cell that secretes large quantities of protein hormones would be expected to contain an unusually extensive:",
 "options":{"A":"Cytoskeleton with no organelles","B":"Smooth ER","C":"Rough ER and Golgi apparatus","D":"Peroxisome network only"},"answer":"C"},
{"id":15,"subject":"Biology","topic":"Cell Membrane & Transport","difficulty":"Easy",
 "question":"Diffusion refers to the net movement of particles:",
 "options":{"A":"Only in living cells","B":"From an area of low concentration to high concentration","C":"From an area of high concentration to low concentration, down their concentration gradient","D":"Only across membranes with carrier proteins"},"answer":"C"},
{"id":16,"subject":"Biology","topic":"Cell Membrane & Transport","difficulty":"Medium",
 "question":"Endocytosis is the process by which a cell:",
 "options":{"A":"Actively pumps ions using ATP","B":"Allows free diffusion of gases","C":"Releases materials to the outside via vesicle fusion with the membrane","D":"Takes in large particles or fluid by engulfing them within a vesicle formed from the membrane"},"answer":"D"},
{"id":17,"subject":"Biology","topic":"Cell Membrane & Transport","difficulty":"Medium",
 "question":"An animal cell placed in a hypotonic solution will most likely:",
 "options":{"A":"Remain completely unchanged","B":"Undergo plasmolysis","C":"Shrink and crenate","D":"Swell and potentially burst (lyse), since it lacks a rigid cell wall"},"answer":"D"},
{"id":18,"subject":"Biology","topic":"Cell Membrane & Transport","difficulty":"Hard",
 "question":"Facilitated diffusion differs from simple diffusion in that it:",
 "options":{"A":"Uses specific membrane channel or carrier proteins to move substances down their gradient","B":"Occurs only in prokaryotic cells","C":"Requires ATP hydrolysis","D":"Moves substances against their concentration gradient"},"answer":"A"},
{"id":19,"subject":"Biology","topic":"Cell Membrane & Transport","difficulty":"Easy",
 "question":"The fluid mosaic model describes the cell membrane as composed of:",
 "options":{"A":"A single layer of cholesterol molecules","B":"A rigid, unchanging layer of protein only","C":"A flexible phospholipid bilayer with embedded proteins that can move laterally","D":"A solid wall of cellulose"},"answer":"C"},
{"id":20,"subject":"Biology","topic":"Cell Cycle & Division","difficulty":"Easy",
 "question":"DNA replication occurs during which phase of the cell cycle?",
 "options":{"A":"Mitosis","B":"G1","C":"S phase","D":"G2"},"answer":"C"},
{"id":21,"subject":"Biology","topic":"Cell Cycle & Division","difficulty":"Easy",
 "question":"During which phase of mitosis do chromosomes align along the cell's equatorial plate?",
 "options":{"A":"Anaphase","B":"Telophase","C":"Prophase","D":"Metaphase"},"answer":"D"},
{"id":22,"subject":"Biology","topic":"Cell Cycle & Division","difficulty":"Medium",
 "question":"Crossing over, which increases genetic variation, occurs during:",
 "options":{"A":"Interphase of mitosis only","B":"Mitosis only","C":"Prophase I of meiosis, between homologous chromosomes","D":"Anaphase of mitosis"},"answer":"C"},
{"id":23,"subject":"Biology","topic":"Cell Cycle & Division","difficulty":"Medium",
 "question":"A diploid organism has 2n = 46. How many chromosomes are present in a cell that has just completed telophase of mitosis?",
 "options":{"A":"23","B":"46","C":"92","D":"12"},"answer":"B"},
{"id":24,"subject":"Biology","topic":"Cell Cycle & Division","difficulty":"Hard",
 "question":"Cancer can result from mutations in genes that normally regulate the cell cycle, particularly:",
 "options":{"A":"Genes with no role in the cell cycle","B":"Genes that only affect eye color","C":"Proto-oncogenes and tumor suppressor genes","D":"Genes coding exclusively for hemoglobin"},"answer":"C"},
{"id":25,"subject":"Biology","topic":"Cell Cycle & Division","difficulty":"Medium",
 "question":"Cytokinesis in animal cells occurs through the formation of a:",
 "options":{"A":"Cell plate","B":"Contractile ring that pinches the cell into two","C":"Cellulose wall between daughter cells","D":"Spindle fiber network only"},"answer":"B"},
{"id":26,"subject":"Biology","topic":"Genetics","difficulty":"Easy",
 "question":"In pea plants, if yellow seed color (Y) is dominant over green (y), a cross of YY x yy produces offspring that are:",
 "options":{"A":"All yellow","B":"All green","C":"1 yellow : 1 green","D":"3 yellow : 1 green"},"answer":"A"},
{"id":27,"subject":"Biology","topic":"Genetics","difficulty":"Medium",
 "question":"A test cross is used to determine:",
 "options":{"A":"The exact age of an organism","B":"The sex of offspring only","C":"The phenotype of a homozygous dominant organism","D":"Whether an organism showing the dominant phenotype is homozygous or heterozygous"},"answer":"D"},
{"id":28,"subject":"Biology","topic":"Genetics","difficulty":"Medium",
 "question":"Two parents, both carriers (Aa) for a recessive genetic disorder, have children. What is the probability that a given child will be unaffected (not showing the disorder)?",
 "options":{"A":"25%","B":"50%","C":"75%","D":"100%"},"answer":"C"},
{"id":29,"subject":"Biology","topic":"Genetics","difficulty":"Hard",
 "question":"In a dihybrid testcross AaBb x aabb, what fraction of offspring is expected to show both dominant traits?",
 "options":{"A":"3/4","B":"9/16","C":"1/4","D":"1/16"},"answer":"C"},
{"id":30,"subject":"Biology","topic":"Genetics","difficulty":"Medium",
 "question":"Color blindness is an X-linked recessive trait. A color-blind father and a homozygous normal mother have children. What proportion of their daughters will be color-blind?",
 "options":{"A":"50%","B":"100%","C":"0%","D":"25%"},"answer":"C"},
{"id":31,"subject":"Biology","topic":"Genetics","difficulty":"Hard",
 "question":"A trait that appears in every generation, in roughly half the offspring of an affected-by-unaffected cross, is most consistent with:",
 "options":{"A":"Codominant inheritance exclusively","B":"Autosomal recessive inheritance","C":"Autosomal dominant inheritance","D":"Y-linked inheritance only"},"answer":"C"},
{"id":32,"subject":"Biology","topic":"Genetics","difficulty":"Medium",
 "question":"In cattle, crossing a red-coated (RR) individual with a white-coated (WW) individual produces roan (RW) offspring with a mix of red and white hairs. This is an example of:",
 "options":{"A":"Codominance, since both alleles are fully and separately expressed","B":"Epistasis","C":"Complete dominance","D":"Incomplete dominance"},"answer":"A"},
{"id":33,"subject":"Biology","topic":"Genetics","difficulty":"Easy",
 "question":"The complete set of genetic instructions carried by an organism is called its:",
 "options":{"A":"Karyotype","B":"Phenotype","C":"Genome","D":"Allele"},"answer":"C"},
{"id":34,"subject":"Biology","topic":"Molecular Biology","difficulty":"Easy",
 "question":"In DNA, guanine always pairs with:",
 "options":{"A":"Thymine","B":"Cytosine","C":"Uracil","D":"Adenine"},"answer":"B"},
{"id":35,"subject":"Biology","topic":"Molecular Biology","difficulty":"Easy",
 "question":"The strand of DNA used as a template to synthesize a complementary mRNA strand is:",
 "options":{"A":"The antiparallel template strand","B":"The sense strand only","C":"Any random strand","D":"Only the newly synthesized strand"},"answer":"A"},
{"id":36,"subject":"Biology","topic":"Molecular Biology","difficulty":"Medium",
 "question":"Transcription is the process by which:",
 "options":{"A":"DNA is replicated into two identical DNA molecules","B":"mRNA is degraded in the cytoplasm","C":"Amino acids are joined to form a polypeptide","D":"A DNA sequence is copied into a complementary mRNA sequence"},"answer":"D"},
{"id":37,"subject":"Biology","topic":"Molecular Biology","difficulty":"Medium",
 "question":"A mutation that changes a codon for an amino acid into a stop codon is called a:",
 "options":{"A":"Missense mutation","B":"Nonsense mutation, which truncates the protein","C":"Frameshift mutation","D":"Silent mutation"},"answer":"B"},
{"id":38,"subject":"Biology","topic":"Molecular Biology","difficulty":"Medium",
 "question":"The process by which the primary mRNA transcript has its introns removed and exons joined together is called:",
 "options":{"A":"RNA splicing","B":"Replication","C":"Transcription initiation","D":"Translation"},"answer":"A"},
{"id":39,"subject":"Biology","topic":"Molecular Biology","difficulty":"Hard",
 "question":"Deletion of three consecutive nucleotides within a gene's coding region would most likely result in:",
 "options":{"A":"No change in the protein at all","B":"Complete loss of the start codon only","C":"A frameshift affecting all downstream codons","D":"The loss or gain of a single amino acid, without shifting the reading frame"},"answer":"D"},
{"id":40,"subject":"Biology","topic":"Molecular Biology","difficulty":"Hard",
 "question":"The enzyme responsible for unwinding the DNA double helix ahead of the replication fork is:",
 "options":{"A":"Helicase","B":"Ligase","C":"Primase","D":"DNA polymerase"},"answer":"A"},
{"id":41,"subject":"Biology","topic":"Molecular Biology","difficulty":"Medium",
 "question":"A promoter is a DNA sequence that functions to:",
 "options":{"A":"Serve as the binding site for RNA polymerase to initiate transcription","B":"Code for a specific protein","C":"Splice introns from mRNA","D":"Terminate transcription"},"answer":"A"},
{"id":42,"subject":"Biology","topic":"Molecular Biology","difficulty":"Easy",
 "question":"Which of the following is NOT one of the three stop codons in the standard genetic code?",
 "options":{"A":"AUG","B":"UAA","C":"UAG","D":"UGA"},"answer":"A"},
{"id":43,"subject":"Biology","topic":"Molecular Biology","difficulty":"Hard",
 "question":"In genetic engineering, restriction enzymes are used primarily to:",
 "options":{"A":"Join DNA fragments together permanently","B":"Cut DNA at specific recognition sequences, producing fragments with defined ends","C":"Synthesize new DNA strands from scratch","D":"Translate mRNA into protein"},"answer":"B"},
{"id":44,"subject":"Biology","topic":"Evolution","difficulty":"Easy",
 "question":"Evolution by natural selection requires which of the following?",
 "options":{"A":"Acquired traits being passed to offspring","B":"A constant environment with no selective pressures","C":"Heritable variation among individuals in a population","D":"Identical genotypes across all individuals"},"answer":"C"},
{"id":45,"subject":"Biology","topic":"Evolution","difficulty":"Medium",
 "question":"Directional selection tends to:",
 "options":{"A":"Favor the average phenotype","B":"Favor one phenotypic extreme over others, shifting the population's trait distribution over time","C":"Have no effect on allele frequency","D":"Always create two distinct extreme groups"},"answer":"B"},
{"id":46,"subject":"Biology","topic":"Evolution","difficulty":"Medium",
 "question":"Analogous structures, such as the wings of insects and birds, arise from:",
 "options":{"A":"Convergent evolution due to similar environmental pressures, not shared ancestry","B":"Identical genetic pathways","C":"Divergent evolution from a recent common ancestor","D":"Common ancestry"},"answer":"A"},
{"id":47,"subject":"Biology","topic":"Evolution","difficulty":"Hard",
 "question":"In a population at Hardy-Weinberg equilibrium, the frequency of the recessive allele (q) is 0.3. What percentage of the population is expected to be heterozygous (Aa)?",
 "options":{"A":"42%","B":"49%","C":"30%","D":"9%"},"answer":"A"},
{"id":48,"subject":"Biology","topic":"Classification & Diversity","difficulty":"Easy",
 "question":"The scientific naming system in which every species is given a two-part Latin name is called:",
 "options":{"A":"Cladistics","B":"Dichotomous keying","C":"Phylogenetics","D":"Binomial nomenclature"},"answer":"D"},
{"id":49,"subject":"Biology","topic":"Classification & Diversity","difficulty":"Easy",
 "question":"Members of kingdom Protista are best described as:",
 "options":{"A":"Exclusively parasitic organisms","B":"Multicellular and exclusively photosynthetic","C":"A diverse group of mostly unicellular eukaryotes","D":"Prokaryotic and lacking a nucleus"},"answer":"C"},
{"id":50,"subject":"Biology","topic":"Classification & Diversity","difficulty":"Medium",
 "question":"Domain Eukarya differs from Domains Bacteria and Archaea in that Eukarya organisms:",
 "options":{"A":"Are always unicellular","B":"Are always prokaryotic","C":"Lack a nucleus and membrane-bound organelles","D":"Possess a true nucleus and membrane-bound organelles"},"answer":"D"},
{"id":51,"subject":"Biology","topic":"Classification & Diversity","difficulty":"Medium",
 "question":"An organism with a soft body, a muscular foot, and often a calcium carbonate shell most likely belongs to phylum:",
 "options":{"A":"Arthropoda","B":"Annelida","C":"Cnidaria","D":"Mollusca"},"answer":"D"},
{"id":52,"subject":"Biology","topic":"Classification & Diversity","difficulty":"Easy",
 "question":"Which taxonomic rank is broader than Class but narrower than Kingdom?",
 "options":{"A":"Genus","B":"Phylum","C":"Order","D":"Family"},"answer":"B"},
{"id":53,"subject":"Biology","topic":"Classification & Diversity","difficulty":"Medium",
 "question":"Class Mammalia is characterized by:",
 "options":{"A":"Gills throughout life","B":"Feathers and egg-laying exclusively","C":"Hair or fur, mammary glands, and typically live birth","D":"Moist skin used for respiration"},"answer":"C"},
{"id":54,"subject":"Biology","topic":"Plant Biology","difficulty":"Easy",
 "question":"Sugars produced during photosynthesis are transported throughout the plant primarily through the:",
 "options":{"A":"Phloem","B":"Cortex","C":"Epidermis","D":"Xylem"},"answer":"A"},
{"id":55,"subject":"Biology","topic":"Plant Biology","difficulty":"Medium",
 "question":"The Calvin cycle (light-independent reactions) of photosynthesis takes place in the:",
 "options":{"A":"Nucleus","B":"Thylakoid membrane","C":"Stroma of the chloroplast","D":"Mitochondrial matrix"},"answer":"C"},
{"id":56,"subject":"Biology","topic":"Plant Biology","difficulty":"Medium",
 "question":"A plant root growing downward in response to gravity is an example of:",
 "options":{"A":"Positive gravitropism","B":"Negative phototropism","C":"Thigmotropism","D":"Positive phototropism"},"answer":"A"},
{"id":57,"subject":"Biology","topic":"Plant Biology","difficulty":"Hard",
 "question":"Nitrogen-fixing bacteria living in root nodules of legumes benefit the plant mainly by:",
 "options":{"A":"Breaking down the plant's cell walls","B":"Converting atmospheric nitrogen into a usable form (ammonia), which the plant can use to build proteins","C":"Producing sugars for the plant through photosynthesis","D":"Preventing water absorption"},"answer":"B"},
{"id":58,"subject":"Biology","topic":"Plant Biology","difficulty":"Medium",
 "question":"Gibberellins, a class of plant hormones, primarily promote:",
 "options":{"A":"Root formation exclusively","B":"Stomatal closure","C":"Leaf abscission only","D":"Stem elongation and seed germination"},"answer":"D"},
{"id":59,"subject":"Biology","topic":"Plant Biology","difficulty":"Easy",
 "question":"The part of a flower that receives pollen and is typically sticky is the:",
 "options":{"A":"Anther","B":"Stigma","C":"Filament","D":"Sepal"},"answer":"B"},
{"id":60,"subject":"Biology","topic":"Human Physiology - Digestion","difficulty":"Easy",
 "question":"Protein digestion begins in the:",
 "options":{"A":"Large intestine","B":"Stomach, through the action of pepsin","C":"Small intestine only","D":"Mouth"},"answer":"B"},
{"id":61,"subject":"Biology","topic":"Human Physiology - Digestion","difficulty":"Medium",
 "question":"Trypsin, secreted by the pancreas into the small intestine, functions to break down:",
 "options":{"A":"Proteins","B":"Lipids","C":"Nucleic acids exclusively","D":"Carbohydrates"},"answer":"A"},
{"id":62,"subject":"Biology","topic":"Human Physiology - Digestion","difficulty":"Medium",
 "question":"The small intestine's inner lining is folded into villi and microvilli mainly to:",
 "options":{"A":"Increase surface area for nutrient absorption","B":"Produce stomach acid","C":"Store undigested food","D":"Slow down digestion"},"answer":"A"},
{"id":63,"subject":"Biology","topic":"Human Physiology - Digestion","difficulty":"Hard",
 "question":"A person lacking sufficient lactase enzyme would have difficulty digesting:",
 "options":{"A":"Proteins exclusively","B":"Fats exclusively","C":"Starch","D":"Lactose (milk sugar), leading to lactose intolerance"},"answer":"D"},
{"id":64,"subject":"Biology","topic":"Human Physiology - Circulation","difficulty":"Easy",
 "question":"The chamber of the heart that receives deoxygenated blood returning from the body is the:",
 "options":{"A":"Right ventricle","B":"Left atrium","C":"Right atrium","D":"Left ventricle"},"answer":"C"},
{"id":65,"subject":"Biology","topic":"Human Physiology - Circulation","difficulty":"Medium",
 "question":"The diagram shows a simplified cross-section of the human heart with structures labeled 1-4 (the right atrium, the right ventricle, the left atrium, and the aorta arising from the left ventricle). Which labeled structure is the large artery that carries oxygenated blood to the rest of the body?",
 "image":"images/q_heart_crosssection_aorta_diagram.png",
 "options":{"A":"Structure 4 (aorta)","B":"Structure 1 (right atrium)","C":"Structure 2 (right ventricle)","D":"Structure 3 (left atrium)"},"answer":"A"},
{"id":66,"subject":"Biology","topic":"Human Physiology - Circulation","difficulty":"Medium",
 "question":"Systemic circulation carries oxygenated blood from the heart to:",
 "options":{"A":"The lungs for gas exchange","B":"The rest of the body's tissues, returning deoxygenated blood to the heart","C":"The kidneys exclusively","D":"Only the brain"},"answer":"B"},
{"id":67,"subject":"Biology","topic":"Human Physiology - Circulation","difficulty":"Hard",
 "question":"Red blood cells lack a nucleus in mammals, which primarily:",
 "options":{"A":"Has no functional significance","B":"Prevents them from carrying oxygen","C":"Maximizes internal space for hemoglobin, increasing oxygen-carrying capacity","D":"Allows them to divide rapidly"},"answer":"C"},
{"id":68,"subject":"Biology","topic":"Human Physiology - Respiration","difficulty":"Easy",
 "question":"The muscle primarily responsible for changing the volume of the thoracic cavity during breathing is the:",
 "options":{"A":"Bicep","B":"Diaphragm","C":"Cardiac muscle","D":"Tongue muscle"},"answer":"B"},
{"id":69,"subject":"Biology","topic":"Human Physiology - Respiration","difficulty":"Medium",
 "question":"Oxygen diffuses from the alveoli into the blood mainly because:",
 "options":{"A":"There is no concentration gradient involved","B":"Oxygen concentration is higher in the alveoli than in the blood, favoring diffusion down its gradient","C":"Oxygen concentration is lower in the alveoli than in the blood","D":"Active transport pumps oxygen into the blood"},"answer":"B"},
{"id":70,"subject":"Biology","topic":"Human Physiology - Respiration","difficulty":"Hard",
 "question":"Chronic obstructive pulmonary disease (COPD), which includes conditions like emphysema, primarily impairs breathing by:",
 "options":{"A":"Damaging alveoli and reducing the surface area available for gas exchange","B":"Increasing lung elasticity","C":"Having no impact on gas exchange","D":"Strengthening the alveolar walls"},"answer":"A"},
{"id":71,"subject":"Biology","topic":"Human Physiology - Excretion","difficulty":"Easy",
 "question":"The functional unit of the kidney, responsible for filtering blood and forming urine, is the:",
 "options":{"A":"Villus","B":"Nephron","C":"Neuron","D":"Alveolus"},"answer":"B"},
{"id":72,"subject":"Biology","topic":"Human Physiology - Excretion","difficulty":"Medium",
 "question":"Glucose that is filtered at the glomerulus is normally:",
 "options":{"A":"Converted directly into urea","B":"Entirely excreted in the urine","C":"Completely reabsorbed back into the blood at the proximal convoluted tubule under normal conditions","D":"Never filtered at all"},"answer":"C"},
{"id":73,"subject":"Biology","topic":"Human Physiology - Excretion","difficulty":"Hard",
 "question":"In cases of dehydration, the pituitary gland releases more ADH, which results in:",
 "options":{"A":"Complete cessation of urine formation","B":"No change in urine concentration","C":"More dilute urine and increased urine volume","D":"More concentrated urine and reduced urine volume, as more water is reabsorbed"},"answer":"D"},
{"id":74,"subject":"Biology","topic":"Human Physiology - Nervous & Endocrine","difficulty":"Easy",
 "question":"The gap between two neurons where neurotransmitters are released is called the:",
 "options":{"A":"Myelin sheath","B":"Axon terminal","C":"Synapse","D":"Dendrite"},"answer":"C"},
{"id":75,"subject":"Biology","topic":"Human Physiology - Nervous & Endocrine","difficulty":"Medium",
 "question":"During an action potential, the depolarization phase of a neuron's membrane occurs mainly due to:",
 "options":{"A":"Calcium ions leaving the cell","B":"No ion movement at all","C":"Potassium ions rushing out of the cell","D":"Sodium ions rushing into the cell through voltage-gated channels"},"answer":"D"},
{"id":76,"subject":"Biology","topic":"Human Physiology - Nervous & Endocrine","difficulty":"Medium",
 "question":"The pancreas secretes insulin, which functions to:",
 "options":{"A":"Trigger the fight-or-flight response","B":"Increase blood glucose levels","C":"Lower blood glucose levels by promoting cellular uptake and storage of glucose","D":"Regulate blood calcium exclusively"},"answer":"C"},
{"id":77,"subject":"Biology","topic":"Human Physiology - Nervous & Endocrine","difficulty":"Hard",
 "question":"In Type 1 diabetes, the pancreas fails to produce sufficient insulin because:",
 "options":{"A":"The person consumes too much salt","B":"The liver produces excess insulin","C":"Blood glucose levels are always too low","D":"The beta cells of the pancreas are destroyed, typically by an autoimmune process"},"answer":"D"},
{"id":78,"subject":"Biology","topic":"Human Physiology - Reproduction","difficulty":"Easy",
 "question":"In males, sperm cells are produced within the:",
 "options":{"A":"Seminiferous tubules of the testes","B":"Prostate gland","C":"Epididymis exclusively","D":"Urethra"},"answer":"A"},
{"id":79,"subject":"Biology","topic":"Human Physiology - Reproduction","difficulty":"Medium",
 "question":"A surge in luteinizing hormone (LH) at the midpoint of the menstrual cycle primarily triggers:",
 "options":{"A":"Implantation of the embryo","B":"Formation of the placenta","C":"Menstruation","D":"Ovulation, the release of a mature egg from the ovary"},"answer":"D"},
{"id":80,"subject":"Biology","topic":"Ecology","difficulty":"Easy",
 "question":"Organisms that manufacture their own organic molecules from inorganic sources, such as through photosynthesis, are called:",
 "options":{"A":"Decomposers only","B":"Consumers exclusively","C":"Heterotrophs","D":"Autotrophs"},"answer":"D"},
{"id":81,"subject":"Biology","topic":"Ecology","difficulty":"Medium",
 "question":"In an ecosystem, the total amount of biomass or energy typically decreases at each successive trophic level, a pattern often represented visually as a(n):",
 "options":{"A":"Nitrogen cycle","B":"Carbon cycle","C":"Ecological pyramid","D":"Food web only"},"answer":"C"},
{"id":82,"subject":"Chemistry","topic":"Atomic Structure","difficulty":"Easy",
 "question":"The nucleus of an atom contains:",
 "options":{"A":"Electrons only","B":"Protons and electrons","C":"Neutrons and electrons","D":"Protons and neutrons"},"answer":"D"},
{"id":83,"subject":"Chemistry","topic":"Atomic Structure","difficulty":"Medium",
 "question":"An atom of potassium-39 (atomic number 19) contains how many neutrons?",
 "options":{"A":"39","B":"20","C":"19","D":"58"},"answer":"B"},
{"id":84,"subject":"Chemistry","topic":"Atomic Structure","difficulty":"Medium",
 "question":"The electron configuration of a neutral sulfur atom (Z = 16) is:",
 "options":{"A":"1s2 2s2 2p6 3s2 3p4","B":"1s2 2s2 2p6 3s2 3p2","C":"1s2 2s2 2p6 3s2 3p6","D":"1s2 2s2 2p6 3s1 3p5"},"answer":"A"},
{"id":85,"subject":"Chemistry","topic":"Atomic Structure","difficulty":"Hard",
 "question":"An ion has 16 protons and 18 electrons. What is its charge?",
 "options":{"A":"-2","B":"+16","C":"-18","D":"+2"},"answer":"A"},
{"id":86,"subject":"Chemistry","topic":"Atomic Structure","difficulty":"Easy",
 "question":"The mass number of an atom is equal to the sum of its:",
 "options":{"A":"Protons only","B":"Protons and electrons","C":"Protons and neutrons","D":"Neutrons and electrons"},"answer":"C"},
{"id":87,"subject":"Chemistry","topic":"Periodic Table","difficulty":"Easy",
 "question":"The horizontal rows of the periodic table are called:",
 "options":{"A":"Blocks","B":"Periods","C":"Groups","D":"Families"},"answer":"B"},
{"id":88,"subject":"Chemistry","topic":"Periodic Table","difficulty":"Medium",
 "question":"Ionization energy generally changes across a period from left to right in that it:",
 "options":{"A":"Increases, as nuclear charge increases and atomic radius decreases","B":"Stays exactly constant","C":"Becomes negative","D":"Decreases steadily"},"answer":"A"},
{"id":89,"subject":"Chemistry","topic":"Periodic Table","difficulty":"Medium",
 "question":"An element with low ionization energy and a strong tendency to lose one electron would most likely be found:",
 "options":{"A":"Among the noble gases","B":"Among the halogens","C":"In Group 1, on the far left of the periodic table","D":"In Group 17"},"answer":"C"},
{"id":90,"subject":"Chemistry","topic":"Chemical Bonding","difficulty":"Easy",
 "question":"A bond formed by the complete transfer of electrons from one atom to another is a(n):",
 "options":{"A":"Metallic bond","B":"Hydrogen bond","C":"Covalent bond","D":"Ionic bond"},"answer":"D"},
{"id":91,"subject":"Chemistry","topic":"Chemical Bonding","difficulty":"Medium",
 "question":"According to VSEPR theory, a molecule with four bonding pairs and no lone pairs on the central atom (like CH4) has a molecular geometry of:",
 "options":{"A":"Bent","B":"Trigonal planar","C":"Tetrahedral","D":"Linear"},"answer":"C"},
{"id":92,"subject":"Chemistry","topic":"Chemical Bonding","difficulty":"Medium",
 "question":"Carbon dioxide (CO2) is nonpolar overall despite having polar C=O bonds mainly because:",
 "options":{"A":"Its linear geometry causes the bond dipoles to cancel out","B":"Carbon and oxygen have identical electronegativities","C":"It contains no polar bonds","D":"It has a bent molecular shape"},"answer":"A"},
{"id":93,"subject":"Chemistry","topic":"Chemical Bonding","difficulty":"Hard",
 "question":"Covalent network solids, such as diamond, are typically characterized by:",
 "options":{"A":"Low melting points and high electrical conductivity","B":"Very high melting points and hardness, due to a continuous network of strong covalent bonds","C":"Being liquid at room temperature","D":"Poor thermal stability"},"answer":"B"},
{"id":94,"subject":"Chemistry","topic":"Chemical Bonding","difficulty":"Easy",
 "question":"A hydrogen bond can form between a hydrogen atom covalently bonded to:",
 "options":{"A":"Another hydrogen atom only","B":"A noble gas atom","C":"Any carbon atom in a nonpolar molecule","D":"An electronegative atom like N, O, or F, and a lone pair on a nearby electronegative atom"},"answer":"D"},
{"id":95,"subject":"Chemistry","topic":"States of Matter","difficulty":"Easy",
 "question":"Which state of matter has a definite volume but takes the shape of its container?",
 "options":{"A":"Gas","B":"Plasma","C":"Solid","D":"Liquid"},"answer":"D"},
{"id":96,"subject":"Chemistry","topic":"States of Matter","difficulty":"Medium",
 "question":"A gas occupies 6.0 L at a pressure of 3.0 atm. What volume will it occupy at 2.0 atm, assuming constant temperature?",
 "options":{"A":"12 L","B":"2.0 L","C":"4.0 L","D":"9.0 L"},"answer":"D"},
{"id":97,"subject":"Chemistry","topic":"States of Matter","difficulty":"Hard",
 "question":"A gas has a volume of 4 L at 250 K and 2 atm. What volume will it occupy at 500 K and 1 atm?",
 "options":{"A":"4 L","B":"8 L","C":"16 L","D":"2 L"},"answer":"C"},
{"id":98,"subject":"Chemistry","topic":"Stoichiometry","difficulty":"Easy",
 "question":"The molar mass of sodium chloride (NaCl) is approximately:",
 "options":{"A":"78 g/mol","B":"58.5 g/mol","C":"35.5 g/mol","D":"23 g/mol"},"answer":"B"},
{"id":99,"subject":"Chemistry","topic":"Stoichiometry","difficulty":"Medium",
 "question":"How many moles of oxygen atoms are present in 2 moles of Ca(NO3)2?",
 "options":{"A":"4","B":"12","C":"2","D":"6"},"answer":"B"},
{"id":100,"subject":"Chemistry","topic":"Stoichiometry","difficulty":"Hard",
 "question":"A 250 mL solution contains 0.5 moles of HCl. What is the molarity of the solution?",
 "options":{"A":"1.0 M","B":"2.0 M","C":"0.25 M","D":"0.5 M"},"answer":"B"},
{"id":101,"subject":"Chemistry","topic":"Stoichiometry","difficulty":"Medium",
 "question":"In the reaction N2 + 3H2 -> 2NH3, how many moles of H2 are needed to react completely with 5 moles of N2?",
 "options":{"A":"10","B":"15","C":"20","D":"5"},"answer":"B"},
{"id":102,"subject":"Chemistry","topic":"Thermochemistry","difficulty":"Easy",
 "question":"In an exothermic reaction, the products have _____ energy than the reactants.",
 "options":{"A":"Zero","B":"Lower","C":"Higher","D":"The same"},"answer":"B"},
{"id":103,"subject":"Chemistry","topic":"Thermochemistry","difficulty":"Medium",
 "question":"According to Hess's law, if reaction A + B -> C releases 100 kJ and reaction C -> D releases 50 kJ, the overall enthalpy change for A + B -> D is:",
 "options":{"A":"+150 kJ","B":"-150 kJ","C":"-50 kJ","D":"+50 kJ"},"answer":"B"},
{"id":104,"subject":"Chemistry","topic":"Chemical Equilibrium","difficulty":"Medium",
 "question":"For the reaction 2SO2(g) + O2(g) <-> 2SO3(g), increasing the pressure by decreasing volume shifts the equilibrium toward:",
 "options":{"A":"Complete depletion of the reactants","B":"The reactants (3 moles of gas)","C":"The products (2 moles of gas), the side with fewer gas moles","D":"No shift at all"},"answer":"C"},
{"id":105,"subject":"Chemistry","topic":"Chemical Equilibrium","difficulty":"Hard",
 "question":"If the temperature is decreased for an exothermic reaction at equilibrium, the equilibrium will shift:",
 "options":{"A":"Toward the products, increasing yield","B":"Toward the reactants, decreasing yield","C":"Not at all","D":"To stop the reaction entirely"},"answer":"A"},
{"id":106,"subject":"Chemistry","topic":"Reaction Kinetics","difficulty":"Easy",
 "question":"Increasing the concentration of reactants generally increases reaction rate mainly because:",
 "options":{"A":"Molecules collide less frequently","B":"Molecules collide more frequently, increasing the chance of effective collisions","C":"Activation energy decreases automatically","D":"The reaction becomes non-spontaneous"},"answer":"B"},
{"id":107,"subject":"Chemistry","topic":"Reaction Kinetics","difficulty":"Medium",
 "question":"A catalyst added to a reaction at equilibrium will:",
 "options":{"A":"Have no effect on reaction rate","B":"Shift the equilibrium toward the products","C":"Speed up the rate at which equilibrium is reached, without shifting its position","D":"Shift the equilibrium toward the reactants"},"answer":"C"},
{"id":108,"subject":"Chemistry","topic":"Electrochemistry","difficulty":"Medium",
 "question":"In an electrochemical cell, reduction always occurs at the:",
 "options":{"A":"Salt bridge","B":"Cathode","C":"Anode","D":"External wire"},"answer":"B"},
{"id":109,"subject":"Chemistry","topic":"Electrochemistry","difficulty":"Hard",
 "question":"In the reaction Mg(s) + 2HCl(aq) -> MgCl2(aq) + H2(g), magnesium is:",
 "options":{"A":"Unchanged","B":"Acting as a catalyst","C":"Reduced","D":"Oxidized, losing electrons"},"answer":"D"},
{"id":110,"subject":"Chemistry","topic":"Acids & Bases","difficulty":"Easy",
 "question":"A solution with a pH of 12 is:",
 "options":{"A":"Weakly acidic","B":"Strongly basic","C":"Neutral","D":"Strongly acidic"},"answer":"B"},
{"id":111,"subject":"Chemistry","topic":"Acids & Bases","difficulty":"Medium",
 "question":"According to the Arrhenius theory, an acid is a substance that:",
 "options":{"A":"Increases the concentration of OH- ions in aqueous solution","B":"Accepts protons","C":"Donates electron pairs","D":"Increases the concentration of H+ ions in aqueous solution"},"answer":"D"},
{"id":112,"subject":"Chemistry","topic":"Acids & Bases","difficulty":"Medium",
 "question":"A buffer solution resists changes in pH mainly because it contains:",
 "options":{"A":"A weak acid and its conjugate base (or a weak base and its conjugate acid) in significant amounts","B":"Pure water only","C":"No dissociable ions","D":"Only a strong acid"},"answer":"A"},
{"id":113,"subject":"Chemistry","topic":"Acids & Bases","difficulty":"Hard",
 "question":"When a small amount of strong base is added to a buffer made of acetic acid and sodium acetate, the pH changes little because:",
 "options":{"A":"The buffer has no capacity to resist pH change","B":"The pH always rises sharply regardless","C":"The acetic acid component neutralizes the added base","D":"The sodium acetate reacts with the added base instead"},"answer":"C"},
{"id":114,"subject":"Chemistry","topic":"Organic Chemistry","difficulty":"Easy",
 "question":"The functional group -COOH characterizes which class of organic compounds?",
 "options":{"A":"Amines","B":"Aldehydes","C":"Carboxylic acids","D":"Alcohols"},"answer":"C"},
{"id":115,"subject":"Chemistry","topic":"Organic Chemistry","difficulty":"Medium",
 "question":"Alkenes primarily undergo which type of reaction, in which atoms are added across a double bond?",
 "options":{"A":"Substitution","B":"Addition","C":"Elimination","D":"Condensation"},"answer":"B"},
{"id":116,"subject":"Chemistry","topic":"Organic Chemistry","difficulty":"Medium",
 "question":"A tertiary alcohol has its -OH bearing carbon bonded to how many other carbon atoms?",
 "options":{"A":"One","B":"Two","C":"Three","D":"Zero"},"answer":"C"},
{"id":117,"subject":"Chemistry","topic":"Organic Chemistry","difficulty":"Hard",
 "question":"Which of the following best describes an SN2 reaction mechanism?",
 "options":{"A":"A two-step reaction through a stable carbocation intermediate","B":"A one-step concerted reaction in which the nucleophile attacks as the leaving group departs simultaneously","C":"A reaction that never involves a leaving group","D":"A reaction exclusive to aromatic rings"},"answer":"B"},
{"id":118,"subject":"Chemistry","topic":"Organic Chemistry","difficulty":"Medium",
 "question":"Amides are formed through condensation reactions between carboxylic acids and amines, releasing which byproduct?",
 "options":{"A":"Water","B":"Ammonia","C":"Hydrogen gas","D":"Carbon dioxide"},"answer":"A"},
{"id":119,"subject":"Chemistry","topic":"Organic Chemistry","difficulty":"Easy",
 "question":"A carbonyl group (C=O) located at the end of a carbon chain, bonded to at least one hydrogen, characterizes:",
 "options":{"A":"An aldehyde","B":"A carboxylic acid exclusively","C":"An ether","D":"A ketone"},"answer":"A"},
{"id":120,"subject":"Chemistry","topic":"Inorganic Chemistry","difficulty":"Medium",
 "question":"The general unreactivity of Group 18 elements (noble gases) can be attributed to:",
 "options":{"A":"Their tendency to form ionic bonds readily","B":"Their large atomic size","C":"A stable, complete valence electron configuration","D":"Very low nuclear charge"},"answer":"C"},
{"id":121,"subject":"Chemistry","topic":"Inorganic Chemistry","difficulty":"Medium",
 "question":"Alkaline earth metals (Group 2) are generally less reactive with water than alkali metals (Group 1) of the same period mainly because:",
 "options":{"A":"They have larger atomic radii","B":"They have a higher ionization energy, holding their valence electrons more tightly","C":"They have a lower ionization energy","D":"They do not react with water at all"},"answer":"B"},
{"id":122,"subject":"Chemistry","topic":"Inorganic Chemistry","difficulty":"Hard",
 "question":"In the reaction CuO + H2 -> Cu + H2O, copper's oxidation state changes from:",
 "options":{"A":"0 to +2","B":"+2 to 0 (reduction)","C":"+1 to +2","D":"No change occurs"},"answer":"B"},
{"id":123,"subject":"Chemistry","topic":"Physical Chemistry","difficulty":"Medium",
 "question":"Freezing point depression, a colligative property, occurs when a non-volatile solute is added to a solvent because the solute:",
 "options":{"A":"Has no effect on the freezing point","B":"Only affects the solvent's viscosity","C":"Disrupts the solvent's ability to form an ordered solid lattice, lowering the temperature needed to freeze","D":"Increases the freezing point of the solvent"},"answer":"C"},
{"id":124,"subject":"Chemistry","topic":"Physical Chemistry","difficulty":"Hard",
 "question":"The graph shows a solubility curve of a solid solute plotted against temperature, with solubility increasing steadily as temperature rises. According to the curve, if a saturated solution at a high temperature is cooled to a lower temperature at the same solute concentration, the solution becomes:",
 "image":"images/q_solubility_curve_saturation_diagram.png",
 "options":{"A":"Unsaturated","B":"Supersaturated, and excess solute will tend to precipitate out as it becomes saturated","C":"Diluted automatically","D":"Unaffected"},"answer":"B"},
{"id":125,"subject":"Chemistry","topic":"Environmental Chemistry","difficulty":"Easy",
 "question":"The buildup of greenhouse gases such as carbon dioxide and methane in the atmosphere primarily contributes to:",
 "options":{"A":"Decreased atmospheric pressure","B":"Ozone layer depletion exclusively","C":"Global warming through the enhanced greenhouse effect","D":"Acid rain formation exclusively"},"answer":"C"},
{"id":126,"subject":"Chemistry","topic":"Environmental Chemistry","difficulty":"Medium",
 "question":"Which of the following practices would most directly help reduce the buildup of atmospheric CO2?",
 "options":{"A":"Increasing deforestation","B":"Shifting toward renewable energy sources and reducing fossil fuel combustion","C":"Removing carbon capture technology","D":"Increasing fossil fuel subsidies"},"answer":"B"},
{"id":127,"subject":"Physics","topic":"Kinematics","difficulty":"Easy",
 "question":"A runner covers 100 m in 20 seconds at constant speed. What is the runner's speed?",
 "options":{"A":"5 m/s","B":"20 m/s","C":"2000 m/s","D":"0.2 m/s"},"answer":"A"},
{"id":128,"subject":"Physics","topic":"Kinematics","difficulty":"Medium",
 "question":"A car accelerates uniformly from 5 m/s to 20 m/s in 3 seconds. What is its acceleration?",
 "options":{"A":"5 m/s^2","B":"15 m/s^2","C":"25 m/s^2","D":"3 m/s^2"},"answer":"A"},
{"id":129,"subject":"Physics","topic":"Kinematics","difficulty":"Hard",
 "question":"A ball is dropped from rest and falls for 3 seconds before hitting the ground (g = 10 m/s^2, ignoring air resistance). What is its velocity just before impact?",
 "options":{"A":"10 m/s","B":"30 m/s","C":"15 m/s","D":"60 m/s"},"answer":"B"},
{"id":130,"subject":"Physics","topic":"Dynamics","difficulty":"Easy",
 "question":"An object moving at constant velocity experiences a net force that is:",
 "options":{"A":"Increasing","B":"Zero","C":"Decreasing","D":"Always positive"},"answer":"B"},
{"id":131,"subject":"Physics","topic":"Dynamics","difficulty":"Medium",
 "question":"A net force of 15 N produces an acceleration of 3 m/s^2 in an object. What is the mass of the object?",
 "options":{"A":"5 kg","B":"45 kg","C":"12 kg","D":"18 kg"},"answer":"A"},
{"id":132,"subject":"Physics","topic":"Dynamics","difficulty":"Medium",
 "question":"Which of the following correctly states Newton's third law?",
 "options":{"A":"Momentum is always conserved in an isolated system","B":"An object in motion stays in motion unless acted on by a force","C":"Force equals mass multiplied by acceleration","D":"For every action force, there is an equal and opposite reaction force"},"answer":"D"},
{"id":133,"subject":"Physics","topic":"Dynamics","difficulty":"Hard",
 "question":"A 5 kg object is pushed with a horizontal force of 25 N across a surface with a coefficient of kinetic friction of 0.2 (g = 10 m/s^2). What is the object's acceleration?",
 "options":{"A":"3 m/s^2","B":"5 m/s^2","C":"1 m/s^2","D":"2 m/s^2"},"answer":"A"},
{"id":134,"subject":"Physics","topic":"Work, Energy & Power","difficulty":"Easy",
 "question":"If a force acts perpendicular to an object's displacement, the work done by that force is:",
 "options":{"A":"Zero","B":"Always negative","C":"Undefined","D":"Maximum"},"answer":"A"},
{"id":135,"subject":"Physics","topic":"Work, Energy & Power","difficulty":"Medium",
 "question":"A 5 kg object is raised to a height of 4 m (g = 10 m/s^2). What is its gravitational potential energy?",
 "options":{"A":"40 J","B":"9 J","C":"20 J","D":"200 J"},"answer":"D"},
{"id":136,"subject":"Physics","topic":"Work, Energy & Power","difficulty":"Medium",
 "question":"A 6 kg object moving at 4 m/s has a kinetic energy of:",
 "options":{"A":"96 J","B":"48 J","C":"24 J","D":"12 J"},"answer":"B"},
{"id":137,"subject":"Physics","topic":"Work, Energy & Power","difficulty":"Hard",
 "question":"A motor produces 18000 J of energy in 30 seconds. What is its power output?",
 "options":{"A":"540000 W","B":"60 W","C":"6000 W","D":"600 W"},"answer":"D"},
{"id":138,"subject":"Physics","topic":"Circular Motion & Gravitation","difficulty":"Easy",
 "question":"In uniform circular motion, the centripetal acceleration always points:",
 "options":{"A":"Away from the center","B":"In the direction of velocity","C":"Tangent to the path","D":"Toward the center of the circle"},"answer":"D"},
{"id":139,"subject":"Physics","topic":"Circular Motion & Gravitation","difficulty":"Medium",
 "question":"If the distance between two masses is doubled while both masses remain unchanged, the gravitational force between them becomes:",
 "options":{"A":"1/4 of the original","B":"4 times the original","C":"2 times the original","D":"1/2 of the original"},"answer":"A"},
{"id":140,"subject":"Physics","topic":"Circular Motion & Gravitation","difficulty":"Hard",
 "question":"If a planet's mass were to double while its radius stayed the same, the acceleration due to gravity at its surface would:",
 "options":{"A":"Be reduced to half","B":"Quadruple","C":"Stay the same","D":"Double"},"answer":"D"},
{"id":141,"subject":"Physics","topic":"Fluid Mechanics","difficulty":"Easy",
 "question":"An object floats in a fluid when the buoyant force acting on it is:",
 "options":{"A":"Greater than or equal to its weight","B":"Less than its weight","C":"Always exactly zero","D":"Twice its weight"},"answer":"A"},
{"id":142,"subject":"Physics","topic":"Fluid Mechanics","difficulty":"Medium",
 "question":"Archimedes' principle states that the buoyant force on a submerged object is equal to:",
 "options":{"A":"The object's own weight, regardless of the fluid","B":"The weight of the fluid displaced by the object","C":"The density of the object alone","D":"The pressure at the surface of the fluid"},"answer":"B"},
{"id":143,"subject":"Physics","topic":"Fluid Mechanics","difficulty":"Hard",
 "question":"According to the continuity equation, as a fluid flows from a wide section of pipe into a narrower section, its speed:",
 "options":{"A":"Decreases","B":"Increases, since the flow rate must remain constant","C":"Stays exactly the same","D":"Becomes zero"},"answer":"B"},
{"id":144,"subject":"Physics","topic":"Oscillations & Waves","difficulty":"Easy",
 "question":"The highest point of a transverse wave is called the:",
 "options":{"A":"Crest","B":"Trough","C":"Node","D":"Wavelength"},"answer":"A"},
{"id":145,"subject":"Physics","topic":"Oscillations & Waves","difficulty":"Medium",
 "question":"A pendulum's period depends on its length such that a longer pendulum has:",
 "options":{"A":"No defined period","B":"A shorter period","C":"A longer period (lower frequency)","D":"The same period regardless of length"},"answer":"C"},
{"id":146,"subject":"Physics","topic":"Oscillations & Waves","difficulty":"Medium",
 "question":"A wave has a frequency of 25 Hz and a wavelength of 12 m. What is its speed?",
 "options":{"A":"300 m/s","B":"0.48 m/s","C":"37 m/s","D":"2.08 m/s"},"answer":"A"},
{"id":147,"subject":"Physics","topic":"Oscillations & Waves","difficulty":"Hard",
 "question":"Constructive interference occurs when two waves meet:",
 "options":{"A":"At a 90-degree angle only","B":"With no relationship between their phases","C":"Completely out of phase","D":"In phase, with crest meeting crest, amplifying the resulting amplitude"},"answer":"D"},
{"id":148,"subject":"Physics","topic":"Thermodynamics","difficulty":"Easy",
 "question":"Convection is a method of heat transfer that occurs primarily through:",
 "options":{"A":"The bulk movement of a heated fluid (liquid or gas)","B":"Direct particle-to-particle contact in solids","C":"Electromagnetic waves through a vacuum","D":"Only within solids"},"answer":"A"},
{"id":149,"subject":"Physics","topic":"Thermodynamics","difficulty":"Medium",
 "question":"An adiabatic process, by definition, involves:",
 "options":{"A":"Constant temperature throughout the process","B":"Constant volume","C":"Constant pressure","D":"No heat exchange with the surroundings"},"answer":"D"},
{"id":150,"subject":"Physics","topic":"Thermodynamics","difficulty":"Hard",
 "question":"A gas at constant pressure absorbs 800 J of heat and does 300 J of work on its surroundings. What is the change in internal energy of the gas?",
 "options":{"A":"500 J","B":"1100 J","C":"-500 J","D":"300 J"},"answer":"A"},
{"id":151,"subject":"Physics","topic":"Electrostatics","difficulty":"Easy",
 "question":"Two objects with opposite electric charges will:",
 "options":{"A":"Attract each other","B":"Repel each other","C":"Have no interaction","D":"Both become neutral instantly"},"answer":"A"},
{"id":152,"subject":"Physics","topic":"Electrostatics","difficulty":"Medium",
 "question":"According to Coulomb's law, the force between two point charges is inversely proportional to:",
 "options":{"A":"The product of the charges","B":"The square of the distance between them","C":"The medium's temperature","D":"The sum of the charges"},"answer":"B"},
{"id":153,"subject":"Physics","topic":"Current Electricity","difficulty":"Easy",
 "question":"Ohm's law states that voltage equals current multiplied by:",
 "options":{"A":"Time","B":"Energy","C":"Power","D":"Resistance"},"answer":"D"},
{"id":154,"subject":"Physics","topic":"Current Electricity","difficulty":"Medium",
 "question":"The diagram shows a circuit where resistors R1 (4 ohm) and R2 (4 ohm) are connected in parallel, and this parallel combination is connected in series with R3 (2 ohm). What is the total resistance of the circuit?",
 "image":"images/q_circuit_parallel_then_series.png",
 "options":{"A":"10 ohm","B":"6 ohm","C":"4 ohm","D":"2 ohm"},"answer":"C"},
{"id":155,"subject":"Physics","topic":"Current Electricity","difficulty":"Hard",
 "question":"Two resistors of 10 ohm and 15 ohm are connected in parallel. What is their equivalent resistance?",
 "options":{"A":"150 ohm","B":"25 ohm","C":"6 ohm","D":"5 ohm"},"answer":"C"},
{"id":156,"subject":"Physics","topic":"Current Electricity","difficulty":"Medium",
 "question":"A 1000 W appliance operates at 200 V. What current does it draw?",
 "options":{"A":"5 A","B":"0.2 A","C":"200000 A","D":"20 A"},"answer":"A"},
{"id":157,"subject":"Physics","topic":"Electromagnetism","difficulty":"Medium",
 "question":"The strength of the magnetic field inside a solenoid can be increased by:",
 "options":{"A":"Removing the iron core","B":"Decreasing the number of turns","C":"Decreasing the current through the coil","D":"Increasing the number of turns per unit length or the current"},"answer":"D"},
{"id":158,"subject":"Physics","topic":"Electromagnetism","difficulty":"Hard",
 "question":"According to Faraday's law of electromagnetic induction, the magnitude of an induced EMF depends on:",
 "options":{"A":"The color of the wire used","B":"The temperature of the magnet only","C":"Being independent of any change in flux","D":"The rate of change of magnetic flux through the circuit"},"answer":"D"},
{"id":159,"subject":"Physics","topic":"Modern Physics","difficulty":"Easy",
 "question":"The overall electric charge of a proton is:",
 "options":{"A":"Neutral (zero)","B":"Variable, depending on the atom","C":"Positive","D":"Negative"},"answer":"C"},
{"id":160,"subject":"Physics","topic":"Modern Physics","difficulty":"Medium",
 "question":"In beta-minus decay, an unstable nucleus emits:",
 "options":{"A":"A photon only","B":"Two protons","C":"A helium nucleus","D":"An electron and an antineutrino, as a neutron converts to a proton"},"answer":"D"},
{"id":161,"subject":"Physics","topic":"Modern Physics","difficulty":"Hard",
 "question":"A radioactive isotope has a half-life of 2 hours. Starting with 320 g, how much remains after 8 hours?",
 "options":{"A":"80 g","B":"20 g","C":"40 g","D":"10 g"},"answer":"B"},
{"id":162,"subject":"Physics","topic":"Optics","difficulty":"Medium",
 "question":"The ray diagram shows a concave mirror with an object placed between the focal point (F) and the center of curvature (C). Based on the diagram, the image formed is:",
 "image":"images/q_concave_mirror_object_between_f_and_c.png",
 "options":{"A":"Real, upright, and diminished","B":"Virtual, inverted, and diminished","C":"Real, inverted, and magnified, formed beyond C on the same side as the object","D":"Virtual, upright, and magnified"},"answer":"C"},
{"id":163,"subject":"English","topic":"Synonyms","difficulty":"Easy",
 "question":"Choose the word most nearly similar in meaning to 'CANDID':",
 "options":{"A":"Hostile","B":"Frank","C":"Secretive","D":"Deceptive"},"answer":"B"},
{"id":164,"subject":"English","topic":"Antonyms","difficulty":"Easy",
 "question":"Choose the word most nearly opposite in meaning to 'ABUNDANT':",
 "options":{"A":"Generous","B":"Wealthy","C":"Plentiful","D":"Scarce"},"answer":"D"},
{"id":165,"subject":"English","topic":"Grammar","difficulty":"Easy",
 "question":"Choose the grammatically correct sentence:",
 "options":{"A":"She not likes coffee.","B":"She doesn't likes coffee.","C":"She don't like coffee.","D":"She doesn't like coffee."},"answer":"D"},
{"id":166,"subject":"English","topic":"Grammar","difficulty":"Medium",
 "question":"Choose the correct sentence:",
 "options":{"A":"I suggest that he going to the doctor.","B":"I suggest he will go to the doctor.","C":"I suggest that he goes to the doctor.","D":"I suggest that he go to the doctor."},"answer":"D"},
{"id":167,"subject":"English","topic":"Sentence Correction","difficulty":"Medium",
 "question":"Choose the sentence that is grammatically correct:",
 "options":{"A":"Each of the student have submitted their assignment.","B":"Each of the students were submitted their assignment.","C":"Each of the students have submitted their assignment.","D":"Each of the students has submitted their assignment."},"answer":"D"},
{"id":168,"subject":"English","topic":"Vocabulary","difficulty":"Medium",
 "question":"Choose the word that best completes the sentence: 'Despite the heavy criticism, she remained ______ in her decision.'",
 "options":{"A":"Resolute","B":"Hesitant","C":"Indifferent","D":"Wavering"},"answer":"A"},
{"id":169,"subject":"English","topic":"Idioms","difficulty":"Medium",
 "question":"Choose the meaning closest to the idiom 'to let the cat out of the bag':",
 "options":{"A":"To accidentally reveal a secret","B":"To become very angry","C":"To ignore a problem","D":"To keep a secret carefully"},"answer":"A"},
{"id":170,"subject":"English","topic":"Sentence Correction","difficulty":"Hard",
 "question":"Choose the option that best corrects the sentence: 'Each of the boys have finished their homework on time.'",
 "options":{"A":"Each of the boy have finished their homework on time.","B":"Each of the boys have finished his homework on time.","C":"No correction needed.","D":"Each of the boys has finished his homework on time."},"answer":"D"},
{"id":171,"subject":"English","topic":"Prepositions","difficulty":"Hard",
 "question":"Choose the correct preposition: 'He is capable ______ solving this problem on his own.'",
 "options":{"A":"for","B":"in","C":"of","D":"at"},"answer":"C"},
{"id":172,"subject":"Logical Reasoning","topic":"Number Series","difficulty":"Easy",
 "question":"Find the next number in the series: 4, 8, 12, 16, ?",
 "options":{"A":"22","B":"24","C":"18","D":"20"},"answer":"D"},
{"id":173,"subject":"Logical Reasoning","topic":"Number Series","difficulty":"Easy",
 "question":"Find the missing number: 3, 6, 11, 18, ?",
 "options":{"A":"24","B":"25","C":"27","D":"29"},"answer":"C"},
{"id":174,"subject":"Logical Reasoning","topic":"Analogies","difficulty":"Easy",
 "question":"Fish is to Gills as Human is to:",
 "options":{"A":"Skin","B":"Blood","C":"Heart","D":"Lungs"},"answer":"D"},
{"id":175,"subject":"Logical Reasoning","topic":"Analogies","difficulty":"Medium",
 "question":"Author is to Book as Composer is to:",
 "options":{"A":"Orchestra","B":"Symphony","C":"Instrument","D":"Concert"},"answer":"B"},
{"id":176,"subject":"Logical Reasoning","topic":"Blood Relations","difficulty":"Medium",
 "question":"Pointing to a photograph, a woman said, 'He is the son of my mother's only daughter.' If the woman has no siblings, how is the boy related to her?",
 "options":{"A":"Cousin","B":"Brother","C":"Son","D":"Nephew"},"answer":"C"},
{"id":177,"subject":"Logical Reasoning","topic":"Coding-Decoding","difficulty":"Medium",
 "question":"If in a certain code, TABLE is written as UBCMF, how is CHAIR written in the same code?",
 "options":{"A":"CIBJS","B":"DHBJS","C":"DIBJS","D":"DIBJT"},"answer":"C"},
{"id":178,"subject":"Logical Reasoning","topic":"Syllogism","difficulty":"Hard",
 "question":"All scientists are logical. No logical people are superstitious. Which conclusion logically follows?",
 "options":{"A":"All superstitious people are scientists","B":"Some logical people are scientists","C":"No scientists are superstitious","D":"Some scientists are superstitious"},"answer":"C"},
{"id":179,"subject":"Logical Reasoning","topic":"Pattern Recognition","difficulty":"Hard",
 "question":"Find the next term in the series: 2, 5, 10, 17, 26, ?",
 "options":{"A":"39","B":"37","C":"33","D":"35"},"answer":"B"},
{"id":180,"subject":"Logical Reasoning","topic":"Direction Sense","difficulty":"Medium",
 "question":"A man walks 9 km north, then turns east and walks 12 km. How far is he from his starting point?",
 "options":{"A":"3 km","B":"108 km","C":"21 km","D":"15 km"},"answer":"D"},
]


# ------------------------------------------------------------
# Sanity-check / summary utility
# ------------------------------------------------------------
def summarize(questions):
    from collections import Counter
    subj = Counter(q["subject"] for q in questions)
    diff = Counter(q["difficulty"] for q in questions)
    ans = Counter(q["answer"] for q in questions)
    ids = [q["id"] for q in questions]
    dup_ids = [i for i in set(ids) if ids.count(i) > 1]
    dup_q = [q["question"] for q in questions]
    dup_questions = [t for t in set(dup_q) if dup_q.count(t) > 1]
    images = [q for q in questions if "image" in q]

    print(f"Total questions: {len(questions)}")
    print("\nBy subject:")
    for s, c in subj.items():
        print(f"  {s}: {c}")
    print("\nBy difficulty:")
    for d, c in diff.items():
        print(f"  {d}: {c}")
    print("\nBy correct-answer letter (should be roughly balanced):")
    for L in ["A", "B", "C", "D"]:
        print(f"  {L}: {ans[L]}")
    print(f"\nDuplicate IDs: {dup_ids if dup_ids else 'None'}")
    print(f"Duplicate question text: {dup_questions if dup_questions else 'None'}")
    print(f"\nImage-based questions ({len(images)}):")
    for q in images:
        print(f"  Q{q['id']} [{q['subject']}] -> {q['image']}")

    for q in questions:
        assert set(q["options"].keys()) == {"A", "B", "C", "D"}, f"Q{q['id']} missing an option"
        assert q["answer"] in q["options"], f"Q{q['id']} answer key invalid"
    print("\nAll questions have exactly 4 options (A-D) and a valid answer key. OK.")


def print_answer_key(questions):
    print("\nANSWER KEY")
    print("-" * 40)
    for q in questions:
        print(f"{q['id']:>3}. {q['answer']}", end="   ")
        if q["id"] % 10 == 0:
            print()
    print()


if __name__ == "__main__":
    summarize(QUESTIONS)
    print_answer_key(QUESTIONS)