"""
MDCAT Mock Test 1
==================
Full-length mock test: 180 MCQs
Weightage: Biology 81 | Chemistry 45 | Physics 36 | English 9 | Logical Reasoning 9
Difficulty mix (approx): 30% Easy / 50% Medium / 20% Hard, distributed throughout.
Answer letters (A-D) are balanced ~45 each so the paper cannot be gamed by guessing
a single letter.

Includes 5 image/diagram-based questions (2 Biology, 1 Chemistry, 2 Physics).
Each such question has an "image" key giving a relative path to a PNG diagram
that must be viewed alongside the question (images/ subfolder, shipped alongside
this file). Diagrams: labeled animal-cell structure, enzyme-activity vs
temperature graph, acid-base titration curve, a mixed series-parallel resistor
circuit, and a convex-lens ray diagram.

Each question is a dict:
    id, subject, topic, difficulty, question, [image], options (A-D), answer (correct letter)

Run this file directly to print a summary / sanity-check the paper
(counts per subject, counts per difficulty, duplicate check, answer-letter balance,
and which questions carry an image).
"""

QUESTIONS = [
# ============================================================
# BIOLOGY (81 questions) - id 1-81
# ============================================================

{"id":1,"subject":"Biology","topic":"Biomolecules","difficulty":"Easy",
 "question":"Which of the following is a monosaccharide?",
 "options":{"A":"Starch","B":"Cellulose","C":"Sucrose","D":"Glucose"},"answer":"D"},
{"id":2,"subject":"Biology","topic":"Biomolecules","difficulty":"Easy",
 "question":"The bond formed between two amino acids during protein synthesis is called a:",
 "options":{"A":"Ester bond","B":"Peptide bond","C":"Hydrogen bond","D":"Glycosidic bond"},"answer":"B"},
{"id":3,"subject":"Biology","topic":"Biomolecules","difficulty":"Medium",
 "question":"Which level of protein structure is primarily maintained by hydrogen bonds between backbone atoms, forming alpha helices and beta sheets?",
 "options":{"A":"Secondary","B":"Tertiary","C":"Quaternary","D":"Primary"},"answer":"A"},
{"id":4,"subject":"Biology","topic":"Biomolecules","difficulty":"Medium",
 "question":"Triglycerides are formed by the condensation of glycerol with three:",
 "options":{"A":"Fatty acids","B":"Nucleotides","C":"Monosaccharides","D":"Amino acids"},"answer":"A"},
{"id":5,"subject":"Biology","topic":"Biomolecules","difficulty":"Hard",
 "question":"A phospholipid molecule in a cell membrane is amphipathic mainly because:",
 "options":{"A":"Its fatty acid tails are hydrophobic while its phosphate head is hydrophilic","B":"It can rotate freely within the bilayer","C":"It contains both carbon and hydrogen atoms","D":"It is synthesized in the smooth endoplasmic reticulum"},"answer":"A"},
{"id":6,"subject":"Biology","topic":"Enzymes","difficulty":"Easy",
 "question":"Enzymes increase the rate of a reaction mainly by:",
 "options":{"A":"Lowering the activation energy","B":"Increasing the free energy of the products","C":"Increasing the temperature of the reaction","D":"Making the reaction exergonic"},"answer":"A"},
{"id":7,"subject":"Biology","topic":"Enzymes","difficulty":"Medium",
 "question":"A competitive inhibitor of an enzyme typically:",
 "options":{"A":"Increases the Vmax of the reaction","B":"Resembles the substrate and competes for the active site","C":"Binds only to the enzyme-substrate complex","D":"Binds to the allosteric site and changes enzyme shape permanently"},"answer":"B"},
{"id":8,"subject":"Biology","topic":"Enzymes","difficulty":"Medium",
 "question":"The graph shows the rate of an enzyme-catalyzed reaction against temperature. What is the most likely explanation for the sharp decline in rate above the optimum temperature shown on the graph?",
 "image":"images/q_enzyme_graph.png",
 "options":{"A":"Substrate concentration falls sharply","B":"The enzyme becomes denatured and loses its active site shape","C":"The reaction becomes reversible","D":"Product inhibition begins"},"answer":"B"},
{"id":9,"subject":"Biology","topic":"Enzymes","difficulty":"Hard",
 "question":"In an enzyme-catalyzed reaction, doubling the substrate concentration at a level already well above Km will:",
 "options":{"A":"Roughly double the reaction rate","B":"Have little effect since the enzyme is already saturated","C":"Stop the reaction completely","D":"Decrease the reaction rate due to substrate inhibition in all cases"},"answer":"B"},
{"id":10,"subject":"Biology","topic":"Cell Biology","difficulty":"Medium",
 "question":"The diagram shows an animal cell with four structures labeled A-D. Which labeled structure is the primary site of ATP production through aerobic respiration?",
 "image":"images/q_cell_diagram.png",
 "options":{"A":"Structure A","B":"Structure B","C":"Structure C","D":"Structure D"},"answer":"A"},
{"id":11,"subject":"Biology","topic":"Cell Biology","difficulty":"Easy",
 "question":"Ribosomes are the site of:",
 "options":{"A":"Lipid digestion","B":"Protein synthesis","C":"ATP hydrolysis for movement","D":"DNA replication"},"answer":"B"},
{"id":12,"subject":"Biology","topic":"Cell Biology","difficulty":"Easy",
 "question":"The cell organelle that packages and modifies proteins for secretion is the:",
 "options":{"A":"Golgi apparatus","B":"Peroxisome","C":"Centriole","D":"Nucleolus"},"answer":"A"},
{"id":13,"subject":"Biology","topic":"Cell Biology","difficulty":"Medium",
 "question":"Which of the following best explains why mitochondria are considered to have originated endosymbiotically?",
 "options":{"A":"They are surrounded by a single membrane","B":"They are found in both plant and animal cells","C":"They produce carbon dioxide as a waste product","D":"They contain their own circular DNA and ribosomes similar to bacteria"},"answer":"D"},
{"id":14,"subject":"Biology","topic":"Cell Biology","difficulty":"Medium",
 "question":"Lysosomes are formed by budding from which organelle?",
 "options":{"A":"Golgi apparatus","B":"Nuclear envelope","C":"Rough endoplasmic reticulum","D":"Mitochondria"},"answer":"A"},
{"id":15,"subject":"Biology","topic":"Cell Biology","difficulty":"Medium",
 "question":"Which statement correctly distinguishes rough ER from smooth ER?",
 "options":{"A":"Smooth ER is found only in plant cells","B":"Rough ER synthesizes lipids while smooth ER synthesizes proteins","C":"Rough ER is studded with ribosomes and processes proteins; smooth ER lacks ribosomes and is involved in lipid synthesis and detoxification","D":"Rough ER has no connection to the nuclear envelope"},"answer":"C"},
{"id":16,"subject":"Biology","topic":"Cell Biology","difficulty":"Hard",
 "question":"A cell treated with a drug that disrupts microtubule polymerization would most directly fail to complete:",
 "options":{"A":"Transcription of mRNA","B":"Glycolysis","C":"Chromosome segregation during mitosis","D":"DNA replication"},"answer":"C"},
{"id":17,"subject":"Biology","topic":"Cell Membrane & Transport","difficulty":"Easy",
 "question":"Movement of water across a selectively permeable membrane from a region of high water potential to low water potential is called:",
 "options":{"A":"Active transport","B":"Diffusion","C":"Osmosis","D":"Facilitated diffusion"},"answer":"C"},
{"id":18,"subject":"Biology","topic":"Cell Membrane & Transport","difficulty":"Medium",
 "question":"When a plant cell is placed in a hypertonic solution, the shrinking of the cytoplasm away from the cell wall is called:",
 "options":{"A":"Hemolysis","B":"Crenation","C":"Turgidity","D":"Plasmolysis"},"answer":"D"},
{"id":19,"subject":"Biology","topic":"Cell Membrane & Transport","difficulty":"Medium",
 "question":"The sodium-potassium pump moves ions against their concentration gradients using energy from:",
 "options":{"A":"Light energy","B":"A concentration gradient of glucose","C":"GTP hydrolysis","D":"ATP hydrolysis"},"answer":"D"},
{"id":20,"subject":"Biology","topic":"Cell Membrane & Transport","difficulty":"Hard",
 "question":"Facilitated diffusion differs from active transport in that facilitated diffusion:",
 "options":{"A":"Occurs only in plant cells","B":"Moves solutes down their concentration gradient through channel or carrier proteins without ATP","C":"Can move solutes in either direction regardless of concentration","D":"Requires ATP and moves solutes against their gradient"},"answer":"B"},
{"id":21,"subject":"Biology","topic":"Cell Membrane & Transport","difficulty":"Easy",
 "question":"According to the fluid mosaic model, the plasma membrane is mainly composed of:",
 "options":{"A":"Cellulose fibers embedded in protein","B":"Peptidoglycan cross-linked with sugars","C":"A phospholipid bilayer with embedded proteins","D":"A single layer of protein"},"answer":"C"},
{"id":22,"subject":"Biology","topic":"Cell Cycle & Division","difficulty":"Easy",
 "question":"DNA replication occurs during which phase of the cell cycle?",
 "options":{"A":"G2 phase","B":"M phase","C":"G1 phase","D":"S phase"},"answer":"D"},
{"id":23,"subject":"Biology","topic":"Cell Cycle & Division","difficulty":"Easy",
 "question":"Homologous chromosomes pair up (synapsis) during which stage of meiosis?",
 "options":{"A":"Prophase I","B":"Metaphase II","C":"Anaphase I","D":"Telophase II"},"answer":"A"},
{"id":24,"subject":"Biology","topic":"Cell Cycle & Division","difficulty":"Medium",
 "question":"Crossing over between non-sister chromatids during meiosis I results in:",
 "options":{"A":"Loss of one full set of chromosomes","B":"Formation of identical daughter cells","C":"Genetic recombination and increased variation in gametes","D":"A doubling of chromosome number"},"answer":"C"},
{"id":25,"subject":"Biology","topic":"Cell Cycle & Division","difficulty":"Medium",
 "question":"A human somatic cell has 46 chromosomes. How many chromosomes are present in each cell at the end of meiosis I?",
 "options":{"A":"12","B":"46","C":"23","D":"92"},"answer":"C"},
{"id":26,"subject":"Biology","topic":"Cell Cycle & Division","difficulty":"Hard",
 "question":"The G1/S checkpoint of the cell cycle mainly ensures that:",
 "options":{"A":"Cytokinesis has completed before the next G1","B":"Sister chromatids have separated equally","C":"Chromosomes are correctly attached to the spindle before anaphase","D":"The cell has adequate size, nutrients, and undamaged DNA before entering S phase"},"answer":"D"},
{"id":27,"subject":"Biology","topic":"Cell Cycle & Division","difficulty":"Medium",
 "question":"Uncontrolled cell division resulting from mutations in genes regulating the cell cycle (e.g., proto-oncogenes becoming oncogenes) can lead to:",
 "options":{"A":"Apoptosis","B":"Meiotic arrest","C":"Senescence only","D":"Cancer"},"answer":"D"},
{"id":28,"subject":"Biology","topic":"Genetics","difficulty":"Easy",
 "question":"In a monohybrid cross between two heterozygous (Aa) individuals, the expected phenotypic ratio in the offspring is:",
 "options":{"A":"1:1","B":"3:1","C":"1:2:1","D":"9:3:3:1"},"answer":"B"},
{"id":29,"subject":"Biology","topic":"Genetics","difficulty":"Medium",
 "question":"A cross between a heterozygous tall pea plant (Tt) and a homozygous recessive short plant (tt) gives what phenotypic ratio in offspring?",
 "options":{"A":"3 tall : 1 short","B":"All short","C":"All tall","D":"1 tall : 1 short"},"answer":"D"},
{"id":30,"subject":"Biology","topic":"Genetics","difficulty":"Medium",
 "question":"Red-green color blindness in humans is an X-linked recessive trait. A color-blind father and a homozygous normal-visioned mother have children. What is the expected outcome?",
 "options":{"A":"All daughters will be color-blind","B":"All sons will be color-blind","C":"Half of the sons will be color-blind","D":"All daughters will be carriers, no children will be color-blind"},"answer":"D"},
{"id":31,"subject":"Biology","topic":"Genetics","difficulty":"Hard",
 "question":"In a dihybrid cross AaBb x AaBb, assuming independent assortment, what fraction of offspring is expected to be homozygous recessive for both traits (aabb)?",
 "options":{"A":"1/16","B":"1/8","C":"1/4","D":"9/16"},"answer":"A"},
{"id":32,"subject":"Biology","topic":"Genetics","difficulty":"Medium",
 "question":"Which term describes a situation where both alleles at a locus are fully expressed in the heterozygote, as seen in the AB blood group?",
 "options":{"A":"Epistasis","B":"Codominance","C":"Incomplete dominance","D":"Complete dominance"},"answer":"B"},
{"id":33,"subject":"Biology","topic":"Genetics","difficulty":"Hard",
 "question":"A woman with blood group AB and a man with blood group O have children. Which blood groups are possible in their offspring?",
 "options":{"A":"Only AB","B":"O only","C":"A, B, AB, and O","D":"A and B only"},"answer":"D"},
{"id":34,"subject":"Biology","topic":"Genetics","difficulty":"Medium",
 "question":"Cystic fibrosis is an autosomal recessive disorder. Two carrier (heterozygous) parents have a child. What is the probability the child is affected?",
 "options":{"A":"50%","B":"100%","C":"25%","D":"0%"},"answer":"C"},
{"id":35,"subject":"Biology","topic":"Molecular Biology","difficulty":"Easy",
 "question":"The two strands of a DNA double helix are held together by:",
 "options":{"A":"Hydrogen bonds between complementary bases","B":"Covalent bonds between sugars","C":"Ionic bonds between phosphates","D":"Peptide bonds"},"answer":"A"},
{"id":36,"subject":"Biology","topic":"Molecular Biology","difficulty":"Easy",
 "question":"In DNA, adenine pairs with:",
 "options":{"A":"Guanine","B":"Cytosine","C":"Thymine","D":"Uracil"},"answer":"C"},
{"id":37,"subject":"Biology","topic":"Molecular Biology","difficulty":"Medium",
 "question":"DNA replication is described as semi-conservative because:",
 "options":{"A":"Only one of the two daughter cells receives replicated DNA","B":"Each new DNA molecule consists of one original (parental) strand and one newly synthesized strand","C":"DNA polymerase synthesizes both strands simultaneously in the same direction","D":"Only half of the DNA molecule is replicated at a time"},"answer":"B"},
{"id":38,"subject":"Biology","topic":"Molecular Biology","difficulty":"Medium",
 "question":"The enzyme responsible for synthesizing mRNA from a DNA template during transcription is:",
 "options":{"A":"Ligase","B":"RNA polymerase","C":"Helicase","D":"DNA polymerase"},"answer":"B"},
{"id":39,"subject":"Biology","topic":"Molecular Biology","difficulty":"Medium",
 "question":"During translation, tRNA molecules deliver amino acids to the ribosome by base-pairing their anticodon with the:",
 "options":{"A":"Ribosomal RNA exclusively","B":"Start codon only","C":"DNA template strand","D":"Corresponding codon on the mRNA"},"answer":"D"},
{"id":40,"subject":"Biology","topic":"Molecular Biology","difficulty":"Hard",
 "question":"A point mutation changes a single DNA base such that a codon coding for an amino acid becomes a stop codon. This type of mutation is called a:",
 "options":{"A":"Nonsense mutation","B":"Frameshift mutation","C":"Missense mutation","D":"Silent mutation"},"answer":"A"},
{"id":41,"subject":"Biology","topic":"Molecular Biology","difficulty":"Hard",
 "question":"Insertion of a single nucleotide into a gene's coding sequence (not in a multiple of three) most likely results in:",
 "options":{"A":"A silent mutation with no effect on the protein","B":"No change in the protein since introns absorb the change","C":"A frameshift mutation altering the entire downstream amino acid sequence","D":"Immediate cell death in all cases"},"answer":"C"},
{"id":42,"subject":"Biology","topic":"Molecular Biology","difficulty":"Medium",
 "question":"In eukaryotic gene expression, the removal of introns and joining of exons from pre-mRNA is called:",
 "options":{"A":"Splicing","B":"Translation","C":"Replication","D":"Transcription"},"answer":"A"},
{"id":43,"subject":"Biology","topic":"Molecular Biology","difficulty":"Medium",
 "question":"Which of these correctly pairs a nitrogenous base with its class?",
 "options":{"A":"Cytosine - purine","B":"Thymine - purine","C":"Adenine - pyrimidine","D":"Guanine - purine"},"answer":"D"},
{"id":44,"subject":"Biology","topic":"Molecular Biology","difficulty":"Easy",
 "question":"The genetic code is described as degenerate because:",
 "options":{"A":"Stop codons code for amino acids","B":"The code differs completely between species","C":"Some amino acids are coded for by more than one codon","D":"Each codon can code for more than one amino acid"},"answer":"C"},
{"id":45,"subject":"Biology","topic":"Evolution","difficulty":"Easy",
 "question":"Natural selection acts on:",
 "options":{"A":"The genotype directly, regardless of expression","B":"Traits acquired during an individual's lifetime","C":"Heritable variation in phenotype that affects survival and reproduction","D":"Only dominant alleles"},"answer":"C"},
{"id":46,"subject":"Biology","topic":"Evolution","difficulty":"Medium",
 "question":"Homologous structures, such as the forelimbs of humans, whales, and bats, provide evidence for evolution because they:",
 "options":{"A":"Are found only in extinct species","B":"Share a similar underlying structure inherited from a common ancestor despite different functions","C":"Evolved independently through convergent evolution","D":"Have identical functions in all species"},"answer":"B"},
{"id":47,"subject":"Biology","topic":"Evolution","difficulty":"Medium",
 "question":"A population is said to be in Hardy-Weinberg equilibrium when allele frequencies remain constant across generations. Which of the following would disrupt this equilibrium?",
 "options":{"A":"A very large population size","B":"Absence of mutation","C":"Random mating with no migration","D":"Natural selection favoring a particular allele"},"answer":"D"},
{"id":48,"subject":"Biology","topic":"Evolution","difficulty":"Hard",
 "question":"In a population, allele A has frequency p = 0.6 and allele a has frequency q = 0.4. Assuming Hardy-Weinberg equilibrium, what proportion of the population is expected to be heterozygous (Aa)?",
 "options":{"A":"0.36","B":"0.48","C":"0.16","D":"0.24"},"answer":"B"},
{"id":49,"subject":"Biology","topic":"Classification & Diversity","difficulty":"Easy",
 "question":"The five-kingdom classification system was proposed by:",
 "options":{"A":"R.H. Whittaker","B":"Carl Linnaeus","C":"Gregor Mendel","D":"Charles Darwin"},"answer":"A"},
{"id":50,"subject":"Biology","topic":"Classification & Diversity","difficulty":"Easy",
 "question":"Organisms belonging to kingdom Fungi are typically:",
 "options":{"A":"Photosynthetic autotrophs","B":"Prokaryotic and unicellular only","C":"Heterotrophs that absorb nutrients after extracellular digestion","D":"Chemosynthetic autotrophs"},"answer":"C"},
{"id":51,"subject":"Biology","topic":"Classification & Diversity","difficulty":"Medium",
 "question":"Bacteria are classified in a separate kingdom (Monera/Prokaryotae) mainly because they:",
 "options":{"A":"Lack a membrane-bound nucleus and other membrane-bound organelles","B":"Lack a cell wall","C":"Are always pathogenic","D":"Cannot reproduce"},"answer":"A"},
{"id":52,"subject":"Biology","topic":"Classification & Diversity","difficulty":"Medium",
 "question":"Viruses are generally not classified within the five-kingdom system because they:",
 "options":{"A":"Contain both DNA and RNA together","B":"Lack a cellular structure and cannot replicate outside a host cell","C":"Are exclusively plant pathogens","D":"Are too large to be classified"},"answer":"B"},
{"id":53,"subject":"Biology","topic":"Classification & Diversity","difficulty":"Easy",
 "question":"Which taxonomic rank lies directly between Kingdom and Class?",
 "options":{"A":"Genus","B":"Order","C":"Phylum","D":"Family"},"answer":"C"},
{"id":54,"subject":"Biology","topic":"Classification & Diversity","difficulty":"Medium",
 "question":"Members of phylum Arthropoda are characterized by:",
 "options":{"A":"Radial symmetry and a water vascular system","B":"A segmented body, jointed appendages, and an exoskeleton of chitin","C":"Notochord present throughout life","D":"A soft unsegmented body with a single shell"},"answer":"B"},
{"id":55,"subject":"Biology","topic":"Plant Biology","difficulty":"Easy",
 "question":"The main site of photosynthesis in a leaf cell is the:",
 "options":{"A":"Mitochondrion","B":"Nucleus","C":"Chloroplast","D":"Vacuole"},"answer":"C"},
{"id":56,"subject":"Biology","topic":"Plant Biology","difficulty":"Medium",
 "question":"During the light-dependent reactions of photosynthesis, water is split (photolysis) mainly to:",
 "options":{"A":"Provide glucose directly to the cell","B":"Regenerate RuBP","C":"Produce carbon dioxide for the Calvin cycle","D":"Replace electrons lost from photosystem II and release oxygen"},"answer":"D"},
{"id":57,"subject":"Biology","topic":"Plant Biology","difficulty":"Medium",
 "question":"In the Calvin cycle, the enzyme responsible for fixing atmospheric CO2 onto RuBP is:",
 "options":{"A":"ATP synthase","B":"Rubredoxin","C":"Carbonic anhydrase only","D":"RuBisCO"},"answer":"D"},
{"id":58,"subject":"Biology","topic":"Plant Biology","difficulty":"Hard",
 "question":"C4 plants such as maize show an adaptive advantage over C3 plants in hot, dry environments primarily because they:",
 "options":{"A":"Spatially separate initial CO2 fixation and the Calvin cycle, minimizing photorespiration","B":"Do not require light for photosynthesis","C":"Lack stomata entirely, preventing water loss","D":"Perform photosynthesis only at night"},"answer":"A"},
{"id":59,"subject":"Biology","topic":"Plant Biology","difficulty":"Medium",
 "question":"Xylem tissue in vascular plants is primarily responsible for:",
 "options":{"A":"Gas exchange in leaves","B":"Storage of starch","C":"Transport of sugars from source to sink","D":"Transport of water and minerals from roots to shoots"},"answer":"D"},
{"id":60,"subject":"Biology","topic":"Plant Biology","difficulty":"Easy",
 "question":"Stomata on a leaf surface primarily function in:",
 "options":{"A":"Gas exchange and transpiration","B":"Anchoring the plant","C":"Synthesizing chlorophyll","D":"Absorbing water from soil"},"answer":"A"},
{"id":61,"subject":"Biology","topic":"Human Physiology - Digestion","difficulty":"Easy",
 "question":"The enzyme pepsin, which begins protein digestion, is active in the:",
 "options":{"A":"Small intestine","B":"Mouth","C":"Stomach","D":"Large intestine"},"answer":"C"},
{"id":62,"subject":"Biology","topic":"Human Physiology - Digestion","difficulty":"Medium",
 "question":"Bile, produced by the liver and stored in the gallbladder, aids digestion mainly by:",
 "options":{"A":"Emulsifying fats into smaller droplets to increase surface area for lipase action","B":"Neutralizing intestinal alkalinity","C":"Directly digesting proteins into amino acids","D":"Digesting starch into maltose"},"answer":"A"},
{"id":63,"subject":"Biology","topic":"Human Physiology - Digestion","difficulty":"Medium",
 "question":"Most absorption of digested nutrients occurs in the:",
 "options":{"A":"Esophagus","B":"Small intestine","C":"Stomach","D":"Large intestine"},"answer":"B"},
{"id":64,"subject":"Biology","topic":"Human Physiology - Digestion","difficulty":"Hard",
 "question":"Villi and microvilli in the small intestine increase the efficiency of nutrient absorption primarily by:",
 "options":{"A":"Slowing down peristalsis","B":"Producing more digestive enzymes","C":"Vastly increasing the surface area available for absorption","D":"Neutralizing stomach acid"},"answer":"C"},
{"id":65,"subject":"Biology","topic":"Human Physiology - Circulation","difficulty":"Easy",
 "question":"Oxygenated blood from the lungs first enters which chamber of the heart?",
 "options":{"A":"Right ventricle","B":"Right atrium","C":"Left atrium","D":"Left ventricle"},"answer":"C"},
{"id":66,"subject":"Biology","topic":"Human Physiology - Circulation","difficulty":"Medium",
 "question":"The thick muscular wall of the left ventricle compared to the right ventricle is an adaptation for:",
 "options":{"A":"Storing more blood at rest","B":"Pumping blood a short distance to the lungs","C":"Producing red blood cells","D":"Generating higher pressure to pump blood throughout the entire systemic circulation"},"answer":"D"},
{"id":67,"subject":"Biology","topic":"Human Physiology - Circulation","difficulty":"Medium",
 "question":"Which blood vessel carries deoxygenated blood but is classified as an artery?",
 "options":{"A":"Pulmonary vein","B":"Pulmonary artery","C":"Vena cava","D":"Aorta"},"answer":"B"},
{"id":68,"subject":"Biology","topic":"Human Physiology - Circulation","difficulty":"Hard",
 "question":"The SA node is often called the natural pacemaker of the heart because it:",
 "options":{"A":"Is located in the left ventricle","B":"Receives blood first from the vena cava","C":"Produces the largest volume of contractile force","D":"Initiates the electrical impulse that sets the rhythm of the heartbeat"},"answer":"D"},
{"id":69,"subject":"Biology","topic":"Human Physiology - Respiration","difficulty":"Easy",
 "question":"Gas exchange in the lungs occurs across the walls of the:",
 "options":{"A":"Trachea","B":"Bronchi","C":"Alveoli","D":"Larynx"},"answer":"C"},
{"id":70,"subject":"Biology","topic":"Human Physiology - Respiration","difficulty":"Medium",
 "question":"During inhalation, contraction of the diaphragm causes it to flatten, which:",
 "options":{"A":"Directly forces oxygen into the blood","B":"Has no effect on lung volume","C":"Increases thoracic volume and decreases pressure, drawing air in","D":"Decreases thoracic volume and increases pressure, pushing air out"},"answer":"C"},
{"id":71,"subject":"Biology","topic":"Human Physiology - Respiration","difficulty":"Medium",
 "question":"Most carbon dioxide is transported in the blood in the form of:",
 "options":{"A":"Bicarbonate ions in plasma","B":"Carbonic acid crystals","C":"Dissolved CO2 gas","D":"Carbaminohemoglobin"},"answer":"A"},
{"id":72,"subject":"Biology","topic":"Human Physiology - Excretion","difficulty":"Easy",
 "question":"The functional unit of the human kidney is the:",
 "options":{"A":"Nephron","B":"Alveolus","C":"Neuron","D":"Villus"},"answer":"A"},
{"id":73,"subject":"Biology","topic":"Human Physiology - Excretion","difficulty":"Medium",
 "question":"Filtration of blood in the nephron occurs in the:",
 "options":{"A":"Loop of Henle","B":"Distal convoluted tubule","C":"Glomerulus and Bowman's capsule","D":"Collecting duct"},"answer":"C"},
{"id":74,"subject":"Biology","topic":"Human Physiology - Excretion","difficulty":"Hard",
 "question":"The hormone ADH (antidiuretic hormone) regulates water balance mainly by:",
 "options":{"A":"Increasing sodium excretion","B":"Stimulating red blood cell production","C":"Decreasing the glomerular filtration rate directly","D":"Increasing the permeability of the collecting duct to water, reducing urine volume"},"answer":"D"},
{"id":75,"subject":"Biology","topic":"Human Physiology - Nervous & Endocrine","difficulty":"Easy",
 "question":"The basic structural and functional unit of the nervous system is the:",
 "options":{"A":"Synapse","B":"Neuron","C":"Nephron","D":"Axon terminal only"},"answer":"B"},
{"id":76,"subject":"Biology","topic":"Human Physiology - Nervous & Endocrine","difficulty":"Medium",
 "question":"At a chemical synapse, an action potential arriving at the axon terminal causes:",
 "options":{"A":"Immediate destruction of the neuron","B":"Release of neurotransmitter from vesicles into the synaptic cleft","C":"Formation of a new axon","D":"Direct flow of electrical current into the next neuron"},"answer":"B"},
{"id":77,"subject":"Biology","topic":"Human Physiology - Nervous & Endocrine","difficulty":"Medium",
 "question":"Insulin, secreted by beta cells of the pancreas, lowers blood glucose mainly by:",
 "options":{"A":"Stimulating the liver to convert glycogen to glucose","B":"Increasing glucose reabsorption in the kidney","C":"Promoting uptake of glucose by cells and its conversion to glycogen","D":"Breaking down fats into glucose"},"answer":"C"},
{"id":78,"subject":"Biology","topic":"Human Physiology - Nervous & Endocrine","difficulty":"Hard",
 "question":"In a resting neuron, the inside of the membrane is negative relative to the outside mainly due to:",
 "options":{"A":"Absence of any ion channels","B":"The sodium-potassium pump and greater resting permeability to K+, which leaks out","C":"Continuous depolarization","D":"Higher permeability to Na+ than K+ at rest"},"answer":"B"},
{"id":79,"subject":"Biology","topic":"Human Physiology - Reproduction","difficulty":"Easy",
 "question":"In the human female reproductive cycle, ovulation refers to the:",
 "options":{"A":"Release of a mature egg from the ovary","B":"Implantation of the embryo","C":"Formation of the placenta","D":"Shedding of the uterine lining"},"answer":"A"},
{"id":80,"subject":"Biology","topic":"Human Physiology - Reproduction","difficulty":"Medium",
 "question":"Fertilization in humans normally occurs in the:",
 "options":{"A":"Uterus","B":"Vagina","C":"Ovary","D":"Fallopian tube (oviduct)"},"answer":"D"},
{"id":81,"subject":"Biology","topic":"Ecology","difficulty":"Medium",
 "question":"In a food chain, the trophic level that captures energy directly from the sun is occupied by:",
 "options":{"A":"Decomposers","B":"Secondary consumers","C":"Producers","D":"Primary consumers"},"answer":"C"},

# ============================================================
# CHEMISTRY (45 questions) - id 82-126
# ============================================================

{"id":82,"subject":"Chemistry","topic":"Atomic Structure","difficulty":"Easy",
 "question":"The number of protons in the nucleus of an atom determines its:",
 "options":{"A":"Mass number","B":"Atomic number","C":"Number of neutrons","D":"Isotope form"},"answer":"B"},
{"id":83,"subject":"Chemistry","topic":"Atomic Structure","difficulty":"Medium",
 "question":"An atom of chlorine-35 (atomic number 17) has how many neutrons?",
 "options":{"A":"35","B":"17","C":"52","D":"18"},"answer":"D"},
{"id":84,"subject":"Chemistry","topic":"Atomic Structure","difficulty":"Medium",
 "question":"According to the Aufbau principle, the electron configuration of a neutral potassium atom (Z=19) ends with:",
 "options":{"A":"4s^1","B":"3d^1","C":"4p^1","D":"3p^7"},"answer":"A"},
{"id":85,"subject":"Chemistry","topic":"Atomic Structure","difficulty":"Hard",
 "question":"Two isotopes of an element differ in:",
 "options":{"A":"Number of electrons only, with different protons","B":"Number of protons only","C":"Number of neutrons, while having the same number of protons","D":"Atomic number"},"answer":"C"},
{"id":86,"subject":"Chemistry","topic":"Periodic Table","difficulty":"Easy",
 "question":"Elements in the same group of the periodic table have similar chemical properties mainly because they have the same:",
 "options":{"A":"Number of energy shells","B":"Number of neutrons","C":"Atomic mass","D":"Number of valence electrons"},"answer":"D"},
{"id":87,"subject":"Chemistry","topic":"Periodic Table","difficulty":"Medium",
 "question":"Across a period from left to right, atomic radius generally:",
 "options":{"A":"Decreases due to increasing effective nuclear charge pulling electrons closer","B":"Remains constant","C":"Increases due to added electron shells","D":"Increases due to increasing nuclear charge"},"answer":"A"},
{"id":88,"subject":"Chemistry","topic":"Periodic Table","difficulty":"Medium",
 "question":"Ionization energy generally increases across a period because:",
 "options":{"A":"Shielding effect increases dramatically","B":"Atomic size increases, making electrons easier to remove","C":"Increasing nuclear charge holds valence electrons more tightly","D":"Electrons are added to a new outer shell"},"answer":"C"},
{"id":89,"subject":"Chemistry","topic":"Chemical Bonding","difficulty":"Easy",
 "question":"An ionic bond is formed by:",
 "options":{"A":"Sharing of electron pairs between atoms","B":"Weak attraction between molecules","C":"Overlap of atomic orbitals only","D":"Transfer of electrons from one atom to another, forming oppositely charged ions"},"answer":"D"},
{"id":90,"subject":"Chemistry","topic":"Chemical Bonding","difficulty":"Medium",
 "question":"The shape of a methane (CH4) molecule, according to VSEPR theory, is:",
 "options":{"A":"Linear","B":"Trigonal planar","C":"Bent","D":"Tetrahedral"},"answer":"D"},
{"id":91,"subject":"Chemistry","topic":"Chemical Bonding","difficulty":"Medium",
 "question":"Water (H2O) is a bent molecule with a bond angle of approximately 104.5 degrees mainly because:",
 "options":{"A":"Oxygen forms two double bonds with hydrogen","B":"Hydrogen atoms repel each other strongly","C":"Water has no lone pairs on oxygen","D":"Two lone pairs on oxygen repel the bonding pairs, compressing the bond angle"},"answer":"D"},
{"id":92,"subject":"Chemistry","topic":"Chemical Bonding","difficulty":"Hard",
 "question":"Hydrogen bonding in water molecules is responsible for which of the following properties?",
 "options":{"A":"Water's low specific heat capacity","B":"Water's inability to dissolve ionic compounds","C":"Water's unusually high boiling point and surface tension compared to similarly sized molecules","D":"Water's low boiling point compared to H2S"},"answer":"C"},
{"id":93,"subject":"Chemistry","topic":"States of Matter","difficulty":"Easy",
 "question":"According to the kinetic molecular theory, increasing the temperature of a gas at constant volume:",
 "options":{"A":"Decreases the average kinetic energy of particles","B":"Has no effect on particle motion","C":"Increases the average kinetic energy and pressure of the gas","D":"Converts the gas into a liquid"},"answer":"C"},
{"id":94,"subject":"Chemistry","topic":"States of Matter","difficulty":"Medium",
 "question":"A gas occupies 2.0 L at 1 atm pressure. At constant temperature, what volume will it occupy at 4 atm pressure (Boyle's Law)?",
 "options":{"A":"4.0 L","B":"8.0 L","C":"2.0 L","D":"0.5 L"},"answer":"D"},
{"id":95,"subject":"Chemistry","topic":"States of Matter","difficulty":"Hard",
 "question":"A fixed mass of gas at 300 K occupies 6 L. If the temperature is raised to 450 K at constant pressure, the new volume (Charles's Law) is:",
 "options":{"A":"12 L","B":"6 L","C":"4 L","D":"9 L"},"answer":"D"},
{"id":96,"subject":"Chemistry","topic":"Stoichiometry","difficulty":"Easy",
 "question":"One mole of any gas at STP occupies approximately:",
 "options":{"A":"44.8 L","B":"1 L","C":"22.4 L","D":"11.2 L"},"answer":"C"},
{"id":97,"subject":"Chemistry","topic":"Stoichiometry","difficulty":"Medium",
 "question":"How many moles of oxygen molecules (O2) are needed to completely combust 2 moles of methane (CH4) according to CH4 + 2O2 -> CO2 + 2H2O?",
 "options":{"A":"6 moles","B":"2 moles","C":"4 moles","D":"1 mole"},"answer":"C"},
{"id":98,"subject":"Chemistry","topic":"Stoichiometry","difficulty":"Hard",
 "question":"5.85 g of NaCl (molar mass 58.5 g/mol) is dissolved in water to make 500 mL of solution. What is the molarity of the solution?",
 "options":{"A":"1.0 M","B":"0.5 M","C":"0.2 M","D":"0.1 M"},"answer":"C"},
{"id":99,"subject":"Chemistry","topic":"Stoichiometry","difficulty":"Medium",
 "question":"In the reaction N2 + 3H2 -> 2NH3, if 1 mole of N2 reacts completely with excess H2, how many moles of NH3 are produced?",
 "options":{"A":"4","B":"2","C":"3","D":"1"},"answer":"B"},
{"id":100,"subject":"Chemistry","topic":"Thermochemistry","difficulty":"Easy",
 "question":"A reaction that releases heat to the surroundings is called:",
 "options":{"A":"Exothermic","B":"Endothermic","C":"Isothermic","D":"Adiabatic"},"answer":"A"},
{"id":101,"subject":"Chemistry","topic":"Thermochemistry","difficulty":"Medium",
 "question":"In an endothermic reaction, the enthalpy of the products compared to the reactants is:",
 "options":{"A":"Exactly equal","B":"Lower, with negative delta H","C":"Undefined","D":"Higher, with positive delta H"},"answer":"D"},
{"id":102,"subject":"Chemistry","topic":"Chemical Equilibrium","difficulty":"Medium",
 "question":"According to Le Chatelier's principle, increasing the pressure on a gaseous equilibrium system will shift the equilibrium toward the side with:",
 "options":{"A":"No change since pressure does not affect equilibrium","B":"Fewer moles of gas","C":"Equal moles on both sides always","D":"More moles of gas"},"answer":"B"},
{"id":103,"subject":"Chemistry","topic":"Chemical Equilibrium","difficulty":"Hard",
 "question":"For an exothermic reaction at equilibrium, increasing the temperature will shift the equilibrium position:",
 "options":{"A":"Toward the reactants, decreasing product yield","B":"Have no effect on the position of equilibrium","C":"Toward the products, increasing yield","D":"Completely stop the reaction"},"answer":"A"},
{"id":104,"subject":"Chemistry","topic":"Reaction Kinetics","difficulty":"Easy",
 "question":"Increasing the concentration of reactants generally increases the rate of a reaction because:",
 "options":{"A":"It decreases the temperature of the system","B":"It increases the frequency of effective collisions between particles","C":"It lowers the activation energy","D":"It changes the reaction mechanism entirely"},"answer":"B"},
{"id":105,"subject":"Chemistry","topic":"Reaction Kinetics","difficulty":"Medium",
 "question":"A catalyst increases the rate of a reaction by:",
 "options":{"A":"Shifting the equilibrium position toward products","B":"Increasing the concentration of reactants","C":"Increasing the temperature of the reaction mixture","D":"Providing an alternative pathway with lower activation energy"},"answer":"D"},
{"id":106,"subject":"Chemistry","topic":"Electrochemistry","difficulty":"Medium",
 "question":"In an electrochemical (galvanic) cell, oxidation occurs at the:",
 "options":{"A":"External circuit only","B":"Anode","C":"Cathode","D":"Salt bridge"},"answer":"B"},
{"id":107,"subject":"Chemistry","topic":"Electrochemistry","difficulty":"Hard",
 "question":"In the reaction Zn(s) + Cu2+(aq) -> Zn2+(aq) + Cu(s), zinc is:",
 "options":{"A":"Oxidized, acting as the reducing agent","B":"Reduced, acting as the reducing agent","C":"Neither oxidized nor reduced","D":"Reduced, acting as the oxidizing agent"},"answer":"A"},
{"id":108,"subject":"Chemistry","topic":"Acids & Bases","difficulty":"Easy",
 "question":"A solution with pH = 3 is:",
 "options":{"A":"Weakly basic","B":"Acidic","C":"Strongly basic","D":"Neutral"},"answer":"B"},
{"id":109,"subject":"Chemistry","topic":"Acids & Bases","difficulty":"Medium",
 "question":"A solution has a hydrogen ion concentration [H+] of 1x10^-5 M. What is its pH?",
 "options":{"A":"14","B":"9","C":"1x10^-5","D":"5"},"answer":"D"},
{"id":110,"subject":"Chemistry","topic":"Acids & Bases","difficulty":"Medium",
 "question":"The graph shows the titration curve obtained when NaOH solution is added to 25 mL of HCl solution. Based on the graph, what is the approximate volume of NaOH required to reach the equivalence point?",
 "image":"images/q_titration_curve.png",
 "options":{"A":"10 mL","B":"25 mL","C":"40 mL","D":"50 mL"},"answer":"B"},
{"id":111,"subject":"Chemistry","topic":"Acids & Bases","difficulty":"Hard",
 "question":"A buffer solution resists changes in pH mainly because it contains:",
 "options":{"A":"Only pure water","B":"A weak acid (or base) and its conjugate base (or acid), which can neutralize added H+ or OH-","C":"A strong acid and a strong base in equal amounts","D":"A concentrated strong acid alone"},"answer":"B"},
{"id":112,"subject":"Chemistry","topic":"Organic Chemistry","difficulty":"Easy",
 "question":"The general formula for an alkane is:",
 "options":{"A":"CnH2n","B":"CnHn","C":"CnH2n+2","D":"CnH2n-2"},"answer":"C"},
{"id":113,"subject":"Chemistry","topic":"Organic Chemistry","difficulty":"Medium",
 "question":"Alkenes are more reactive than alkanes mainly because:",
 "options":{"A":"They lack hydrogen atoms","B":"The pi bond in the C=C double bond is relatively weak and reactive toward addition reactions","C":"They contain only single bonds, which are weak","D":"They are ionic compounds"},"answer":"B"},
{"id":114,"subject":"Chemistry","topic":"Organic Chemistry","difficulty":"Medium",
 "question":"The functional group -OH, when attached to a carbon chain, characterizes which class of organic compounds?",
 "options":{"A":"Carboxylic acids","B":"Ethers","C":"Alcohols","D":"Aldehydes"},"answer":"C"},
{"id":115,"subject":"Chemistry","topic":"Organic Chemistry","difficulty":"Hard",
 "question":"In a nucleophilic substitution reaction (SN2) on a primary haloalkane, the reaction proceeds via:",
 "options":{"A":"Elimination of a proton without nucleophile involvement","B":"A single concerted step where the nucleophile attacks as the leaving group departs, with inversion of configuration","C":"Radical chain propagation","D":"Formation of a stable carbocation intermediate followed by nucleophilic attack"},"answer":"B"},
{"id":116,"subject":"Chemistry","topic":"Organic Chemistry","difficulty":"Medium",
 "question":"Ethanol (C2H5OH) reacting with ethanoic acid (CH3COOH) in the presence of an acid catalyst produces an ester and:",
 "options":{"A":"Hydrogen gas","B":"Water","C":"Ammonia","D":"Carbon dioxide"},"answer":"B"},
{"id":117,"subject":"Chemistry","topic":"Organic Chemistry","difficulty":"Easy",
 "question":"The functional group -COOH characterizes:",
 "options":{"A":"Alcohols","B":"Aldehydes","C":"Ketones","D":"Carboxylic acids"},"answer":"D"},
{"id":118,"subject":"Chemistry","topic":"Inorganic Chemistry","difficulty":"Medium",
 "question":"Transition metals commonly form colored compounds mainly due to:",
 "options":{"A":"Formation of only ionic bonds","B":"Electronic transitions between partially filled d-orbitals","C":"Their large atomic radius","D":"Their high melting points"},"answer":"B"},
{"id":119,"subject":"Chemistry","topic":"Inorganic Chemistry","difficulty":"Medium",
 "question":"Noble gases are chemically unreactive mainly because they have:",
 "options":{"A":"A complete outer electron shell","B":"Only two electrons total","C":"A single valence electron","D":"High atomic mass"},"answer":"A"},
{"id":120,"subject":"Chemistry","topic":"Inorganic Chemistry","difficulty":"Hard",
 "question":"In the reaction 2KMnO4 + 16HCl -> 2KCl + 2MnCl2 + 5Cl2 + 8H2O, manganese undergoes a change in oxidation state from:",
 "options":{"A":"+4 to +2","B":"+2 to +7 (oxidation)","C":"+7 to +2 (reduction)","D":"No change in oxidation state"},"answer":"C"},
{"id":121,"subject":"Chemistry","topic":"Physical Chemistry","difficulty":"Medium",
 "question":"The molarity of a solution is defined as:",
 "options":{"A":"Moles of solute per mole of solvent","B":"Moles of solute per kilogram of solvent","C":"Moles of solute per liter of solution","D":"Grams of solute per liter of solution"},"answer":"C"},
{"id":122,"subject":"Chemistry","topic":"Physical Chemistry","difficulty":"Hard",
 "question":"If 20 mL of 0.5 M HCl is required to exactly neutralize 25 mL of NaOH solution, the molarity of the NaOH solution is:",
 "options":{"A":"0.625 M","B":"0.2 M","C":"0.4 M","D":"0.5 M"},"answer":"C"},
{"id":123,"subject":"Chemistry","topic":"Environmental Chemistry","difficulty":"Easy",
 "question":"The layer of the atmosphere that absorbs most harmful UV radiation from the sun is composed mainly of:",
 "options":{"A":"Ozone (O3)","B":"Carbon dioxide (CO2)","C":"Nitrogen (N2)","D":"Oxygen (O2)"},"answer":"A"},
{"id":124,"subject":"Chemistry","topic":"Environmental Chemistry","difficulty":"Medium",
 "question":"Acid rain is primarily caused by atmospheric pollutants such as:",
 "options":{"A":"Sulfur dioxide and nitrogen oxides reacting with water vapor","B":"Oxygen and nitrogen","C":"Water vapor alone","D":"Carbon dioxide only"},"answer":"A"},
{"id":125,"subject":"Chemistry","topic":"Chemical Bonding","difficulty":"Easy",
 "question":"A covalent bond is formed by:",
 "options":{"A":"Attraction between oppositely charged ions","B":"Loss of electrons from a metal atom only","C":"Sharing of a pair of electrons between two atoms","D":"Complete transfer of electrons between atoms"},"answer":"C"},
{"id":126,"subject":"Chemistry","topic":"Atomic Structure","difficulty":"Easy",
 "question":"Which subatomic particle has a negligible mass compared to protons and neutrons and carries a negative charge?",
 "options":{"A":"Electron","B":"Neutron","C":"Positron","D":"Proton"},"answer":"A"},

# ============================================================
# PHYSICS (36 questions) - id 127-162
# ============================================================

{"id":127,"subject":"Physics","topic":"Kinematics","difficulty":"Easy",
 "question":"A car accelerates uniformly from rest to 20 m/s in 5 seconds. What is its acceleration?",
 "options":{"A":"2 m/s^2","B":"4 m/s^2","C":"100 m/s^2","D":"5 m/s^2"},"answer":"B"},
{"id":128,"subject":"Physics","topic":"Kinematics","difficulty":"Medium",
 "question":"An object is dropped from rest and falls freely under gravity (g = 10 m/s^2). How far does it fall in 3 seconds?",
 "options":{"A":"90 m","B":"30 m","C":"60 m","D":"45 m"},"answer":"D"},
{"id":129,"subject":"Physics","topic":"Kinematics","difficulty":"Hard",
 "question":"A ball is thrown vertically upward with an initial speed of 20 m/s (g = 10 m/s^2, ignoring air resistance). How long does it take to return to its starting point?",
 "options":{"A":"4 s","B":"1 s","C":"20 s","D":"2 s"},"answer":"A"},
{"id":130,"subject":"Physics","topic":"Dynamics","difficulty":"Easy",
 "question":"Newton's second law of motion states that force equals:",
 "options":{"A":"Mass divided by acceleration","B":"Mass times acceleration","C":"Mass times velocity","D":"Mass divided by velocity"},"answer":"B"},
{"id":131,"subject":"Physics","topic":"Dynamics","difficulty":"Medium",
 "question":"A net force of 20 N acts on a 4 kg object initially at rest. What is its acceleration?",
 "options":{"A":"2 m/s^2","B":"10 m/s^2","C":"5 m/s^2","D":"80 m/s^2"},"answer":"C"},
{"id":132,"subject":"Physics","topic":"Dynamics","difficulty":"Medium",
 "question":"According to Newton's third law, when object A exerts a force on object B, object B:",
 "options":{"A":"Exerts a smaller force in the same direction","B":"Exerts an equal and opposite force on A","C":"Accelerates only if A is stationary","D":"Exerts no force on A"},"answer":"B"},
{"id":133,"subject":"Physics","topic":"Dynamics","difficulty":"Hard",
 "question":"A block of mass 5 kg rests on a horizontal surface with a coefficient of friction of 0.2. Taking g = 10 m/s^2, what is the minimum horizontal force needed to just start moving the block?",
 "options":{"A":"10 N","B":"50 N","C":"1 N","D":"5 N"},"answer":"A"},
{"id":134,"subject":"Physics","topic":"Work, Energy & Power","difficulty":"Easy",
 "question":"Work done is defined as:",
 "options":{"A":"Force divided by displacement","B":"Mass times velocity","C":"Force multiplied by displacement in the direction of the force","D":"Force multiplied by time"},"answer":"C"},
{"id":135,"subject":"Physics","topic":"Work, Energy & Power","difficulty":"Medium",
 "question":"A 2 kg object moving at 3 m/s has kinetic energy of:",
 "options":{"A":"9 J","B":"6 J","C":"18 J","D":"3 J"},"answer":"A"},
{"id":136,"subject":"Physics","topic":"Work, Energy & Power","difficulty":"Medium",
 "question":"By the work-energy theorem, the net work done on an object equals its:",
 "options":{"A":"Change in momentum","B":"Total potential energy","C":"Change in kinetic energy","D":"Change in mass"},"answer":"C"},
{"id":137,"subject":"Physics","topic":"Work, Energy & Power","difficulty":"Hard",
 "question":"A machine does 500 J of work in 5 seconds. What is its power output?",
 "options":{"A":"100 W","B":"50 W","C":"2500 W","D":"250 W"},"answer":"A"},
{"id":138,"subject":"Physics","topic":"Circular Motion & Gravitation","difficulty":"Easy",
 "question":"The force that keeps an object moving in a circular path directed toward the center is called:",
 "options":{"A":"Normal force","B":"Centripetal force","C":"Centrifugal force","D":"Frictional force"},"answer":"B"},
{"id":139,"subject":"Physics","topic":"Circular Motion & Gravitation","difficulty":"Medium",
 "question":"According to Newton's law of universal gravitation, if the distance between two masses is doubled, the gravitational force between them becomes:",
 "options":{"A":"Four times","B":"One quarter","C":"Half","D":"Double"},"answer":"B"},
{"id":140,"subject":"Physics","topic":"Circular Motion & Gravitation","difficulty":"Hard",
 "question":"A satellite orbits Earth in a circular orbit. As its orbital radius increases, its orbital speed:",
 "options":{"A":"Becomes zero","B":"Increases","C":"Decreases","D":"Remains the same regardless of radius"},"answer":"C"},
{"id":141,"subject":"Physics","topic":"Fluid Mechanics","difficulty":"Easy",
 "question":"Pressure is defined as:",
 "options":{"A":"Force per unit area","B":"Force per unit volume","C":"Mass per unit volume","D":"Force per unit time"},"answer":"A"},
{"id":142,"subject":"Physics","topic":"Fluid Mechanics","difficulty":"Medium",
 "question":"According to Archimedes' principle, the buoyant force on a submerged object equals:",
 "options":{"A":"The volume of the object","B":"The density of the fluid alone","C":"The weight of the fluid displaced by the object","D":"The weight of the object itself"},"answer":"C"},
{"id":143,"subject":"Physics","topic":"Fluid Mechanics","difficulty":"Hard",
 "question":"According to Bernoulli's principle, as the speed of a flowing fluid increases in a horizontal pipe, its pressure:",
 "options":{"A":"Increases","B":"Becomes zero","C":"Stays the same","D":"Decreases"},"answer":"D"},
{"id":144,"subject":"Physics","topic":"Oscillations & Waves","difficulty":"Easy",
 "question":"The time taken to complete one full oscillation of a simple pendulum is called its:",
 "options":{"A":"Wavelength","B":"Amplitude","C":"Frequency","D":"Period"},"answer":"D"},
{"id":145,"subject":"Physics","topic":"Oscillations & Waves","difficulty":"Medium",
 "question":"If the length of a simple pendulum is quadrupled, its period of oscillation becomes:",
 "options":{"A":"Half as long","B":"Twice as long","C":"Four times as long","D":"Unchanged"},"answer":"B"},
{"id":146,"subject":"Physics","topic":"Oscillations & Waves","difficulty":"Medium",
 "question":"A wave has a frequency of 5 Hz and a wavelength of 2 m. What is its speed?",
 "options":{"A":"7 m/s","B":"2.5 m/s","C":"20 m/s","D":"10 m/s"},"answer":"D"},
{"id":147,"subject":"Physics","topic":"Oscillations & Waves","difficulty":"Hard",
 "question":"Sound waves cannot travel through a vacuum because they are:",
 "options":{"A":"Mechanical waves that require a material medium to propagate","B":"Electromagnetic waves that need charged particles","C":"Transverse waves that need a solid medium only","D":"Too weak to travel any distance"},"answer":"A"},
{"id":148,"subject":"Physics","topic":"Thermodynamics","difficulty":"Easy",
 "question":"Heat naturally flows from:",
 "options":{"A":"A colder body to a hotter body spontaneously","B":"Bodies at the same temperature only","C":"Nowhere, heat does not flow","D":"A hotter body to a colder body"},"answer":"D"},
{"id":149,"subject":"Physics","topic":"Thermodynamics","difficulty":"Medium",
 "question":"The first law of thermodynamics is fundamentally a statement of:",
 "options":{"A":"Conservation of momentum","B":"Conservation of energy","C":"Increase of entropy","D":"Conservation of mass only"},"answer":"B"},
{"id":150,"subject":"Physics","topic":"Thermodynamics","difficulty":"Hard",
 "question":"An amount of 500 J of heat is supplied to a gas, and the gas does 200 J of work on its surroundings. According to the first law of thermodynamics, the change in internal energy of the gas is:",
 "options":{"A":"200 J","B":"700 J","C":"500 J","D":"300 J"},"answer":"D"},
{"id":151,"subject":"Physics","topic":"Electrostatics","difficulty":"Easy",
 "question":"Like electric charges:",
 "options":{"A":"Repel each other","B":"Attract each other","C":"Have no interaction","D":"Always cancel out"},"answer":"A"},
{"id":152,"subject":"Physics","topic":"Electrostatics","difficulty":"Medium",
 "question":"According to Coulomb's law, if the distance between two point charges is tripled, the electrostatic force between them becomes:",
 "options":{"A":"One ninth","B":"Three times","C":"One third","D":"Nine times"},"answer":"A"},
{"id":153,"subject":"Physics","topic":"Current Electricity","difficulty":"Easy",
 "question":"According to Ohm's law, the current through a conductor is directly proportional to the voltage across it, provided:",
 "options":{"A":"Current flows in alternating direction only","B":"Temperature and other physical conditions remain constant","C":"The conductor is a semiconductor","D":"The resistance changes proportionally with voltage"},"answer":"B"},
{"id":154,"subject":"Physics","topic":"Current Electricity","difficulty":"Medium",
 "question":"In the circuit shown, R2 and R3 are connected in parallel with each other, and this combination is connected in series with R1. What is the total resistance of the circuit?",
 "image":"images/q_circuit_diagram.png",
 "options":{"A":"3 Ω","B":"7 Ω","C":"10 Ω","D":"16 Ω"},"answer":"B"},
{"id":155,"subject":"Physics","topic":"Current Electricity","difficulty":"Hard",
 "question":"Two resistors of 4 ohm and 4 ohm are connected in parallel. What is the equivalent resistance?",
 "options":{"A":"4 ohm","B":"8 ohm","C":"2 ohm","D":"1 ohm"},"answer":"C"},
{"id":156,"subject":"Physics","topic":"Current Electricity","difficulty":"Medium",
 "question":"A device operating at 220 V draws a current of 2 A. What is its power consumption?",
 "options":{"A":"110 W","B":"440 W","C":"220 W","D":"880 W"},"answer":"B"},
{"id":157,"subject":"Physics","topic":"Electromagnetism","difficulty":"Medium",
 "question":"A current-carrying conductor placed in a magnetic field experiences a force whose direction is given by:",
 "options":{"A":"Ohm's law","B":"Lenz's law only","C":"Fleming's left-hand rule","D":"Fleming's right-hand rule"},"answer":"C"},
{"id":158,"subject":"Physics","topic":"Electromagnetism","difficulty":"Hard",
 "question":"According to Lenz's law, the direction of an induced current in a coil due to a changing magnetic flux is such that it:",
 "options":{"A":"Aids the change in flux that produced it","B":"Is always in the same direction regardless of flux change","C":"Has no relation to the change in flux","D":"Opposes the change in flux that produced it"},"answer":"D"},
{"id":159,"subject":"Physics","topic":"Modern Physics","difficulty":"Easy",
 "question":"The nucleus of an atom is composed of:",
 "options":{"A":"Electrons only","B":"Protons and neutrons","C":"Neutrons and electrons","D":"Protons and electrons"},"answer":"B"},
{"id":160,"subject":"Physics","topic":"Modern Physics","difficulty":"Medium",
 "question":"In radioactive alpha decay, the emitted alpha particle consists of:",
 "options":{"A":"A single electron","B":"A photon of high energy","C":"A single neutron","D":"2 protons and 2 neutrons (equivalent to a helium nucleus)"},"answer":"D"},
{"id":161,"subject":"Physics","topic":"Modern Physics","difficulty":"Hard",
 "question":"A radioactive sample has a half-life of 4 days. What fraction of the original sample remains after 12 days?",
 "options":{"A":"1/2","B":"1/16","C":"1/4","D":"1/8"},"answer":"D"},
{"id":162,"subject":"Physics","topic":"Optics","difficulty":"Medium",
 "question":"The ray diagram shows an object placed at 2F in front of a convex lens. Based on the diagram, what are the characteristics of the image formed?",
 "image":"images/q_lens_diagram.png",
 "options":{"A":"Virtual, upright, and magnified","B":"Real, inverted, same size as the object, formed at 2F on the other side","C":"Real, upright, and diminished","D":"Virtual, inverted, and same size as the object"},"answer":"B"},

# ============================================================
# ENGLISH (9 questions) - id 163-171
# ============================================================

{"id":163,"subject":"English","topic":"Synonyms","difficulty":"Easy",
 "question":"Choose the word most nearly similar in meaning to 'ABUNDANT':",
 "options":{"A":"Scarce","B":"Fragile","C":"Plentiful","D":"Hidden"},"answer":"C"},
{"id":164,"subject":"English","topic":"Antonyms","difficulty":"Easy",
 "question":"Choose the word most nearly opposite in meaning to 'BENEVOLENT':",
 "options":{"A":"Generous","B":"Malevolent","C":"Kind","D":"Cheerful"},"answer":"B"},
{"id":165,"subject":"English","topic":"Grammar","difficulty":"Easy",
 "question":"Choose the correctly punctuated/grammatical sentence:",
 "options":{"A":"Neither of the boys are present.","B":"Neither of the boys was present.","C":"Neither of the boys were present.","D":"Neither of the boy was present."},"answer":"B"},
{"id":166,"subject":"English","topic":"Grammar","difficulty":"Medium",
 "question":"Identify the correct sentence:",
 "options":{"A":"She has been working here for five years.","B":"She has been working here since five years.","C":"She works here since five years.","D":"She is working here since five years."},"answer":"A"},
{"id":167,"subject":"English","topic":"Sentence Correction","difficulty":"Medium",
 "question":"Choose the sentence that is grammatically correct:",
 "options":{"A":"Each of the students has submitted his or her assignment.","B":"Each of the student have submitted their assignment.","C":"Each of the students submit their assignment yesterday.","D":"Each of the students have submitted their assignment."},"answer":"A"},
{"id":168,"subject":"English","topic":"Vocabulary","difficulty":"Medium",
 "question":"Choose the word that best completes the sentence: 'The scientist's theory was so ______ that few could understand it.'",
 "options":{"A":"Esoteric","B":"Simple","C":"Trivial","D":"Obvious"},"answer":"A"},
{"id":169,"subject":"English","topic":"Idioms","difficulty":"Medium",
 "question":"Choose the meaning closest to the idiom 'to turn a blind eye to something':",
 "options":{"A":"To lose one's eyesight suddenly","B":"To become extremely angry","C":"To deliberately ignore or overlook something","D":"To examine something very carefully"},"answer":"C"},
{"id":170,"subject":"English","topic":"Sentence Correction","difficulty":"Hard",
 "question":"Choose the option that best corrects the underlined error: 'Not only he is intelligent but also hardworking.'",
 "options":{"A":"He is not only intelligent but also hardworking he is.","B":"Not only intelligent he is but also hardworking.","C":"Not only he is intelligent but also he is hardworking.","D":"Not only is he intelligent but also hardworking."},"answer":"D"},
{"id":171,"subject":"English","topic":"Prepositions","difficulty":"Hard",
 "question":"Choose the correct preposition to complete the sentence: 'The committee is comprised ______ ten members from different departments.'",
 "options":{"A":"of","B":"in","C":"with","D":"by"},"answer":"A"},

# ============================================================
# LOGICAL REASONING (9 questions) - id 172-180
# ============================================================

{"id":172,"subject":"Logical Reasoning","topic":"Number Series","difficulty":"Easy",
 "question":"Find the next number in the series: 2, 4, 8, 16, ?",
 "options":{"A":"36","B":"24","C":"30","D":"32"},"answer":"D"},
{"id":173,"subject":"Logical Reasoning","topic":"Number Series","difficulty":"Easy",
 "question":"Find the missing number: 5, 10, 15, 20, ?",
 "options":{"A":"25","B":"22","C":"30","D":"24"},"answer":"A"},
{"id":174,"subject":"Logical Reasoning","topic":"Analogies","difficulty":"Easy",
 "question":"Doctor is to Hospital as Teacher is to:",
 "options":{"A":"School","B":"Student","C":"Book","D":"Chalk"},"answer":"A"},
{"id":175,"subject":"Logical Reasoning","topic":"Analogies","difficulty":"Medium",
 "question":"Pen is to Write as Knife is to:",
 "options":{"A":"Sharp","B":"Cut","C":"Kitchen","D":"Metal"},"answer":"B"},
{"id":176,"subject":"Logical Reasoning","topic":"Blood Relations","difficulty":"Medium",
 "question":"Pointing to a photograph, Ali says, 'She is the daughter of my grandfather's only son.' How is the girl in the photograph related to Ali?",
 "options":{"A":"Cousin","B":"Sister","C":"Niece","D":"Daughter"},"answer":"B"},
{"id":177,"subject":"Logical Reasoning","topic":"Coding-Decoding","difficulty":"Medium",
 "question":"If in a certain code, CAT is written as DBU, how is DOG written in the same code?",
 "options":{"A":"CPH","B":"EPH","C":"EPI","D":"EOG"},"answer":"B"},
{"id":178,"subject":"Logical Reasoning","topic":"Syllogism","difficulty":"Hard",
 "question":"All roses are flowers. Some flowers fade quickly. Which conclusion logically follows?",
 "options":{"A":"No definite conclusion can be drawn about roses fading quickly","B":"Some roses fade quickly","C":"All roses fade quickly","D":"No flowers are roses"},"answer":"A"},
{"id":179,"subject":"Logical Reasoning","topic":"Pattern Recognition","difficulty":"Hard",
 "question":"Find the next term in the series: 1, 4, 9, 16, 25, ?",
 "options":{"A":"36","B":"49","C":"32","D":"30"},"answer":"A"},
{"id":180,"subject":"Logical Reasoning","topic":"Direction Sense","difficulty":"Medium",
 "question":"A man walks 5 km north, then turns right and walks 3 km, then turns right again and walks 5 km. How far is he from his starting point?",
 "options":{"A":"8 km","B":"13 km","C":"5 km","D":"3 km"},"answer":"D"},
]


# ------------------------------------------------------------
# Sanity-check / summary utility
# ------------------------------------------------------------
def summarize(questions):
    from collections import Counter
    subj = Counter(q["subject"] for q in questions)
    diff = Counter(q["difficulty"] for q in questions)
    ans = Counter(q["answer"] for q in questions)
    ids = [q["id"] for q in questions]
    dup_ids = [i for i in set(ids) if ids.count(i) > 1]
    dup_q = [q["question"] for q in questions]
    dup_questions = [t for t in set(dup_q) if dup_q.count(t) > 1]
    images = [q for q in questions if "image" in q]

    print(f"Total questions: {len(questions)}")
    print("\nBy subject:")
    for s, c in subj.items():
        print(f"  {s}: {c}")
    print("\nBy difficulty:")
    for d, c in diff.items():
        print(f"  {d}: {c}")
    print("\nBy correct-answer letter (should be balanced, ~45 each):")
    for L in ["A", "B", "C", "D"]:
        print(f"  {L}: {ans[L]}")
    print(f"\nDuplicate IDs: {dup_ids if dup_ids else 'None'}")
    print(f"Duplicate question text: {dup_questions if dup_questions else 'None'}")
    print(f"\nImage-based questions ({len(images)}):")
    for q in images:
        print(f"  Q{q['id']} [{q['subject']}] -> {q['image']}")

    for q in questions:
        assert set(q["options"].keys()) == {"A", "B", "C", "D"}, f"Q{q['id']} missing an option"
        assert q["answer"] in q["options"], f"Q{q['id']} answer key invalid"
    print("\nAll questions have exactly 4 options (A-D) and a valid answer key. OK.")


def print_answer_key(questions):
    print("\nANSWER KEY")
    print("-" * 40)
    for q in questions:
        print(f"{q['id']:>3}. {q['answer']}", end="   ")
        if q["id"] % 10 == 0:
            print()
    print()


if __name__ == "__main__":
    summarize(QUESTIONS)
    print_answer_key(QUESTIONS)