"""
MDCAT Mock Test 6
==================
Full-length mock test: 180 MCQs
Weightage: Biology 81 | Chemistry 45 | Physics 36 | English 9 | Logical Reasoning 9
Difficulty mix (approx): 30% Easy / 50% Medium / 20% Hard, distributed throughout.

Includes 5 image/diagram-based questions (2 Biology, 1 Chemistry, 2 Physics).
Each such question has an "image" key giving a relative path to a PNG diagram
that must be viewed alongside the question (images/ subfolder, shipped alongside
this file). Diagrams: Michaelis-Menten enzyme-kinetics curve, an X-linked
recessive pedigree chart, a weak-acid/strong-base titration curve, a
series-parallel resistor circuit, and a concave-mirror ray diagram (object
beyond C).

Each question is a dict:
    id, subject, topic, difficulty, question, [image], options (A-D), answer (correct letter)

Run this file directly to print a summary / sanity-check the paper.
"""

QUESTIONS = [
# ============================================================
# BIOLOGY (81 questions) - id 1-81
# ============================================================
{"id":1,"subject":'Biology',"topic":'Biomolecules',"difficulty":'Easy',
 "question":'Which of the following is an example of a monosaccharide?',
 "options":{"A":'Lactose', "B":'Galactose', "C":'Maltose', "D":'Cellulose'},"answer":'B'},
{"id":2,"subject":'Biology',"topic":'Biomolecules',"difficulty":'Easy',
 "question":'The condensation of two monosaccharides with the loss of a water molecule forms a:',
 "options":{"A":'Peptide bond', "B":'Ester bond', "C":'Phosphodiester bond', "D":'Glycosidic bond'},"answer":'D'},
{"id":3,"subject":'Biology',"topic":'Biomolecules',"difficulty":'Medium',
 "question":'Denaturation of a protein primarily disrupts its:',
 "options":{"A":'Secondary, tertiary, and quaternary structure, while the primary structure remains intact', "B":'Primary structure (the amino acid sequence)', "C":'Only the peptide bonds between amino acids', "D":'Nothing; denaturation has no structural effect on proteins'},"answer":'A'},
{"id":4,"subject":'Biology',"topic":'Biomolecules',"difficulty":'Medium',
 "question":'Saturated fatty acids differ from unsaturated fatty acids mainly in that saturated fatty acids:',
 "options":{"A":'Contain one or more C=C double bonds', "B":'Contain no C=C double bonds, allowing tighter packing and a solid state at room temperature', "C":'Are always liquid at room temperature', "D":'Cannot be used for energy storage'},"answer":'B'},
{"id":5,"subject":'Biology',"topic":'Biomolecules',"difficulty":'Hard',
 "question":'RNA differs chemically from DNA in that RNA:',
 "options":{"A":'Contains ribose sugar and uracil instead of thymine', "B":'Contains deoxyribose sugar and thymine', "C":'Is always double-stranded', "D":'Lacks a sugar-phosphate backbone'},"answer":'A'},
{"id":6,"subject":'Biology',"topic":'Enzymes',"difficulty":'Easy',
 "question":'A molecule that binds to an enzyme and increases its catalytic activity is called a(n):',
 "options":{"A":'Inhibitor', "B":'Activator', "C":'Substrate', "D":'Product'},"answer":'B'},
{"id":7,"subject":'Biology',"topic":'Enzymes',"difficulty":'Medium',
 "question":'Allosteric regulation of an enzyme occurs when a regulatory molecule binds:',
 "options":{"A":'Directly at the active site, competing with the substrate', "B":'Only to already-denatured enzymes', "C":'To the substrate itself, not the enzyme', "D":"At a site other than the active site, changing the enzyme's overall shape and activity"},"answer":'D'},
{"id":8,"subject":'Biology',"topic":'Enzymes',"difficulty":'Medium',
 "question":'Feedback inhibition in a metabolic pathway occurs when:',
 "options":{"A":'The initial substrate activates the first enzyme in the pathway', "B":'Intermediate products have no regulatory effect on the pathway', "C":'Enzymes are irreversibly destroyed after a single reaction', "D":'The final product of a pathway inhibits an earlier enzyme in that same pathway'},"answer":'D'},
{"id":9,"subject":'Biology',"topic":'Enzymes',"difficulty":'Hard',
 "question":'The graph shows reaction velocity (v) plotted against substrate concentration [S] for an enzyme-catalyzed reaction, with Vmax marked by a dashed line. Based on the graph, the substrate concentration at which the reaction reaches half of Vmax corresponds to:',
 "image":'images/q_enzyme_km_curve.png',
 "options":{"A":'Km', "B":'Vmax', "C":'kcat', "D":'The saturation point'},"answer":'A'},
{"id":10,"subject":'Biology',"topic":'Cell Biology',"difficulty":'Easy',
 "question":'The organelle responsible for breaking down macromolecules using hydrolytic enzymes in an acidic interior is the:',
 "options":{"A":'Peroxisome', "B":'Ribosome', "C":'Mitochondrion', "D":'Lysosome'},"answer":'D'},
{"id":11,"subject":'Biology',"topic":'Cell Biology',"difficulty":'Easy',
 "question":'Cell walls of fungi are composed mainly of:',
 "options":{"A":'Cellulose', "B":'Peptidoglycan', "C":'Keratin', "D":'Chitin'},"answer":'D'},
{"id":12,"subject":'Biology',"topic":'Cell Biology',"difficulty":'Medium',
 "question":'The cytoskeleton in eukaryotic cells is composed of three main types of protein filaments: microfilaments, intermediate filaments, and:',
 "options":{"A":'Cristae', "B":'Ribosomes', "C":'Microtubules', "D":'Centrioles'},"answer":'C'},
{"id":13,"subject":'Biology',"topic":'Cell Biology',"difficulty":'Medium',
 "question":'Which of the following best distinguishes prokaryotic ribosomes from eukaryotic cytoplasmic ribosomes?',
 "options":{"A":'Only eukaryotic cells contain ribosomes', "B":'Prokaryotic ribosomes are 70S, while eukaryotic cytoplasmic ribosomes are 80S', "C":'Prokaryotic ribosomes lack rRNA entirely', "D":'Eukaryotic ribosomes are always membrane-bound'},"answer":'B'},
{"id":14,"subject":'Biology',"topic":'Cell Biology',"difficulty":'Medium',
 "question":'A cell biologist observes that the nuclear envelope breaks down and later reforms during division. This is most characteristic of:',
 "options":{"A":'Mitosis in eukaryotic cells (open mitosis)', "B":'Prokaryotic cell division', "C":'Binary fission', "D":'Interphase alone'},"answer":'A'},
{"id":15,"subject":'Biology',"topic":'Cell Biology',"difficulty":'Medium',
 "question":'Which structure connects adjacent plant cells and allows direct cytoplasmic communication between them?',
 "options":{"A":'Desmosomes', "B":'Tight junctions', "C":'Gap junctions', "D":'Plasmodesmata'},"answer":'D'},
{"id":16,"subject":'Biology',"topic":'Cell Biology',"difficulty":'Hard',
 "question":'A cell exposed to a drug that inhibits ATP synthase would most directly show a reduction in:',
 "options":{"A":'The rate of DNA replication only', "B":'The rate of transcription', "C":'ATP production via oxidative phosphorylation', "D":'Cell wall synthesis'},"answer":'C'},
{"id":17,"subject":'Biology',"topic":'Cell Membrane & Transport',"difficulty":'Easy',
 "question":'Movement of ions across a membrane through a channel protein, down their electrochemical gradient, is an example of:',
 "options":{"A":'Active transport', "B":'Facilitated diffusion', "C":'Osmosis', "D":'Pinocytosis'},"answer":'B'},
{"id":18,"subject":'Biology',"topic":'Cell Membrane & Transport',"difficulty":'Medium',
 "question":'A plant cell placed in a solution with the same solute concentration as its cytoplasm (isotonic) will show:',
 "options":{"A":'No net movement of water and no change in turgor', "B":'Plasmolysis', "C":'Rapid bursting of the cell', "D":'Complete dehydration of the cytoplasm'},"answer":'A'},
{"id":19,"subject":'Biology',"topic":'Cell Membrane & Transport',"difficulty":'Medium',
 "question":'Pinocytosis differs from phagocytosis in that pinocytosis involves the uptake of:',
 "options":{"A":'Dissolved substances and small droplets of extracellular fluid', "B":'Solid particles or whole cells', "C":'Only gases', "D":'Large amounts of solid cellular waste'},"answer":'A'},
{"id":20,"subject":'Biology',"topic":'Cell Membrane & Transport',"difficulty":'Hard',
 "question":'Primary active transport, such as the sodium-potassium pump, differs from secondary active transport mainly in that primary active transport:',
 "options":{"A":'Directly uses ATP hydrolysis to move ions against their gradient', "B":'Uses energy stored in an ion gradient established by another pump', "C":'Never requires any energy input', "D":'Always moves substances down their concentration gradient'},"answer":'A'},
{"id":21,"subject":'Biology',"topic":'Cell Membrane & Transport',"difficulty":'Easy',
 "question":'Cholesterol embedded within the phospholipid bilayer of animal cell membranes primarily functions to:',
 "options":{"A":'Increase membrane rigidity permanently at all temperatures', "B":'Help regulate membrane fluidity across a range of temperatures', "C":'Transport glucose directly across the membrane', "D":'Synthesize new phospholipid molecules'},"answer":'B'},
{"id":22,"subject":'Biology',"topic":'Cell Cycle & Division',"difficulty":'Easy',
 "question":'The phase of the cell cycle during which the physical division of the cytoplasm occurs is:',
 "options":{"A":'Cytokinesis', "B":'Interphase', "C":'Prophase', "D":'G1 phase'},"answer":'A'},
{"id":23,"subject":'Biology',"topic":'Cell Cycle & Division',"difficulty":'Easy',
 "question":'The stage of mitosis during which the nuclear envelope re-forms around each set of separated chromosomes is:',
 "options":{"A":'Prophase', "B":'Metaphase', "C":'Anaphase', "D":'Telophase'},"answer":'D'},
{"id":24,"subject":'Biology',"topic":'Cell Cycle & Division',"difficulty":'Medium',
 "question":'The main purpose of the G2 checkpoint in the cell cycle is to verify that:',
 "options":{"A":'The cell has reached an appropriate size to begin S phase', "B":'Chromosomes are aligned at the metaphase plate', "C":'DNA replication is complete and free of damage before mitosis begins', "D":'Cytokinesis has occurred correctly'},"answer":'C'},
{"id":25,"subject":'Biology',"topic":'Cell Cycle & Division',"difficulty":'Medium',
 "question":'In humans, how many chromosomes are present in a secondary oocyte immediately after meiosis I is completed?',
 "options":{"A":'46', "B":'23 (each still consisting of two sister chromatids)', "C":'92', "D":'12'},"answer":'B'},
{"id":26,"subject":'Biology',"topic":'Cell Cycle & Division',"difficulty":'Hard',
 "question":'Telomerase activity is typically high in germ cells and many cancer cells mainly because it:',
 "options":{"A":'Adds repetitive sequences to chromosome ends, preventing telomere shortening and allowing continued division', "B":'Shortens telomeres with each division, promoting cell death', "C":'Is required only for DNA repair in somatic cells', "D":'Has no relation to the ends of chromosomes'},"answer":'A'},
{"id":27,"subject":'Biology',"topic":'Cell Cycle & Division',"difficulty":'Medium',
 "question":'Binary fission, the method of reproduction in bacteria, differs from mitosis in eukaryotes mainly because binary fission:',
 "options":{"A":'Produces four genetically distinct daughter cells', "B":'Requires the nuclear envelope to break down first', "C":'Involves division of a single circular chromosome without forming a mitotic spindle', "D":'Always involves meiosis beforehand'},"answer":'C'},
{"id":28,"subject":'Biology',"topic":'Genetics',"difficulty":'Easy',
 "question":'In guinea pigs, black coat color (B) is dominant over white (b). A cross between a heterozygous black (Bb) and a white (bb) guinea pig produces offspring in what phenotypic ratio?',
 "options":{"A":'All black', "B":'3 black : 1 white', "C":'All white', "D":'1 black : 1 white'},"answer":'D'},
{"id":29,"subject":'Biology',"topic":'Genetics',"difficulty":'Medium',
 "question":'A cross between two heterozygous black guinea pigs (Bb x Bb) is expected to yield what genotypic ratio in the offspring?',
 "options":{"A":'All Bb', "B":'3 BB : 1 bb', "C":'1 BB : 2 Bb : 1 bb', "D":'1 BB : 1 bb'},"answer":'C'},
{"id":30,"subject":'Biology',"topic":'Genetics',"difficulty":'Medium',
 "question":'Red-green color blindness in humans is X-linked recessive. A color-blind man and a homozygous normal-visioned woman have a daughter. What is expected regarding the daughter?',
 "options":{"A":'She will be color-blind', "B":'She has a 50% chance of being color-blind', "C":'She will be an unaffected, obligate carrier', "D":'Her genotype cannot be determined'},"answer":'C'},
{"id":31,"subject":'Biology',"topic":'Genetics',"difficulty":'Hard',
 "question":'In a dihybrid cross between two heterozygotes (AaBb x AaBb), what fraction of the offspring is expected to be homozygous dominant for both traits (AABB)?',
 "options":{"A":'1/4', "B":'1/16', "C":'1/8', "D":'9/16'},"answer":'B'},
{"id":32,"subject":'Biology',"topic":'Genetics',"difficulty":'Medium',
 "question":'A father with blood type A (genotype IAi) and a mother with blood type B (genotype IBi) could have a child with which blood type?',
 "options":{"A":'Only A or B', "B":'A, B, AB, or O', "C":'Only AB', "D":'Only O'},"answer":'B'},
{"id":33,"subject":'Biology',"topic":'Genetics',"difficulty":'Hard',
 "question":'The pedigree chart shows the inheritance of an X-linked recessive disorder across three generations. Based on the pattern shown, an unaffected daughter of an affected father and an unaffected (non-carrier) mother must be:',
 "image":'images/q_pedigree_xlinked.png',
 "options":{"A":'Affected herself', "B":'Completely free of the recessive allele', "C":'An obligate carrier (heterozygous) for the disorder', "D":'Impossible to determine from the pedigree'},"answer":'C'},
{"id":34,"subject":'Biology',"topic":'Genetics',"difficulty":'Medium',
 "question":'When neither allele in a heterozygote is completely dominant, and the resulting phenotype is an intermediate blend of both, this pattern is called:',
 "options":{"A":'Codominance', "B":'Epistasis', "C":'Polygenic inheritance', "D":'Incomplete dominance'},"answer":'D'},
{"id":35,"subject":'Biology',"topic":'Molecular Biology',"difficulty":'Easy',
 "question":'In the DNA double helix, the nitrogenous bases point:',
 "options":{"A":'Outward, away from the helix axis', "B":'Inward, toward the center of the helix, pairing with bases on the opposite strand', "C":'In random directions along the strand', "D":'Only along one of the two strands'},"answer":'B'},
{"id":36,"subject":'Biology',"topic":'Molecular Biology',"difficulty":'Easy',
 "question":'During transcription, the RNA base uracil pairs with which DNA base?',
 "options":{"A":'Adenine', "B":'Cytosine', "C":'Guanine', "D":'Thymine'},"answer":'A'},
{"id":37,"subject":'Biology',"topic":'Molecular Biology',"difficulty":'Medium',
 "question":'The enzyme primase is required during DNA replication mainly to:',
 "options":{"A":'Unwind the DNA double helix', "B":'Seal nicks in the sugar-phosphate backbone', "C":"Synthesize a short RNA primer, providing a free 3'-OH group for DNA polymerase to extend", "D":'Proofread newly synthesized DNA'},"answer":'C'},
{"id":38,"subject":'Biology',"topic":'Molecular Biology',"difficulty":'Medium',
 "question":'The three-nucleotide sequence on mRNA that specifies a particular amino acid is called a:',
 "options":{"A":'Codon', "B":'Anticodon', "C":'Intron', "D":'Exon'},"answer":'A'},
{"id":39,"subject":'Biology',"topic":'Molecular Biology',"difficulty":'Medium',
 "question":'A silent mutation has minimal effect on the resulting protein mainly because:',
 "options":{"A":'The changed codon still specifies the same amino acid, due to the degeneracy of the genetic code', "B":'It always occurs in non-coding DNA', "C":'It always creates a premature stop codon', "D":'It shifts the reading frame of translation'},"answer":'A'},
{"id":40,"subject":'Biology',"topic":'Molecular Biology',"difficulty":'Hard',
 "question":'A single nucleotide substitution changes a codon that specified an amino acid into a stop codon. This type of mutation is called a:',
 "options":{"A":'Silent mutation', "B":'Missense mutation', "C":'Nonsense mutation', "D":'Frameshift mutation'},"answer":'C'},
{"id":41,"subject":'Biology',"topic":'Molecular Biology',"difficulty":'Hard',
 "question":'In eukaryotic cells, the enzyme primarily responsible for synthesizing messenger RNA (mRNA) is:',
 "options":{"A":'RNA polymerase I', "B":'RNA polymerase III', "C":'RNA polymerase II', "D":'DNA polymerase I'},"answer":'C'},
{"id":42,"subject":'Biology',"topic":'Molecular Biology',"difficulty":'Medium',
 "question":'Which of the following is true regarding the genetic code?',
 "options":{"A":'It is overlapping, with adjacent codons sharing nucleotides', "B":'It is non-overlapping and read in triplets (codons) without gaps', "C":'It varies completely and unpredictably between species', "D":'Each amino acid has only one possible codon'},"answer":'B'},
{"id":43,"subject":'Biology',"topic":'Molecular Biology',"difficulty":'Medium',
 "question":'A terminator sequence located at the end of a gene functions to:',
 "options":{"A":'Initiate transcription at that gene', "B":'Code for the first amino acid of the protein', "C":'Mark the beginning of translation', "D":'Signal RNA polymerase to stop transcription and release the newly synthesized RNA'},"answer":'D'},
{"id":44,"subject":'Biology',"topic":'Molecular Biology',"difficulty":'Easy',
 "question":'The start codon that signals the beginning of translation, and also codes for methionine, is:',
 "options":{"A":'AUG', "B":'UAA', "C":'UGA', "D":'UAG'},"answer":'A'},
{"id":45,"subject":'Biology',"topic":'Evolution',"difficulty":'Easy',
 "question":'Individuals within a population best suited to their environment tend to survive and reproduce more successfully than others. This is the basic principle of:',
 "options":{"A":'Genetic drift', "B":'Gene flow', "C":'Natural selection', "D":'Mutation alone'},"answer":'C'},
{"id":46,"subject":'Biology',"topic":'Evolution',"difficulty":'Medium',
 "question":'Structures that are similar in different species due to inheritance from a common ancestor, even if they now serve different functions, are called:',
 "options":{"A":'Analogous structures', "B":'Vestigial structures', "C":'Homologous structures', "D":'Convergent structures'},"answer":'C'},
{"id":47,"subject":'Biology',"topic":'Evolution',"difficulty":'Medium',
 "question":'Genetic drift is expected to have the greatest effect on allele frequencies in:',
 "options":{"A":'A very large, randomly mating population', "B":'A population undergoing no reproduction at all', "C":'A small, isolated population', "D":'A population experiencing no random events whatsoever'},"answer":'C'},
{"id":48,"subject":'Biology',"topic":'Evolution',"difficulty":'Hard',
 "question":'In a population of 500 individuals at Hardy-Weinberg equilibrium, the frequency of allele A is 0.8 and allele a is 0.2. What is the expected number of heterozygous (Aa) individuals?',
 "options":{"A":'160', "B":'320', "C":'80', "D":'20'},"answer":'A'},
{"id":49,"subject":'Biology',"topic":'Classification & Diversity',"difficulty":'Easy',
 "question":'The scientific naming system in which each species is given a two-part Latin name (genus + species) is called:',
 "options":{"A":'Cladistics', "B":'Phylogenetics', "C":'General taxonomy', "D":'Binomial nomenclature'},"answer":'D'},
{"id":50,"subject":'Biology',"topic":'Classification & Diversity',"difficulty":'Easy',
 "question":'Kingdom Animalia is distinguished from the other kingdoms mainly by organisms that are:',
 "options":{"A":'Autotrophic and photosynthetic', "B":'Prokaryotic and unicellular', "C":'Multicellular, heterotrophic, and generally capable of movement', "D":'Decomposers possessing rigid cell walls'},"answer":'C'},
{"id":51,"subject":'Biology',"topic":'Classification & Diversity',"difficulty":'Medium',
 "question":'A dichotomous key is a tool used by biologists mainly to:',
 "options":{"A":'Determine the exact age of a fossil', "B":'Identify an organism by working through a series of paired, contrasting statements', "C":"Sequence an organism's entire genome", "D":'Measure the size of a population directly'},"answer":'B'},
{"id":52,"subject":'Biology',"topic":'Classification & Diversity',"difficulty":'Medium',
 "question":'Which of the following is a key diagnostic feature separating phylum Mollusca from phylum Arthropoda?',
 "options":{"A":'Both phyla share an identical body plan', "B":'Mollusks always possess jointed legs', "C":'Arthropods lack any type of external covering', "D":'Mollusks typically have a soft body often protected by a calcium carbonate shell, while arthropods have a jointed exoskeleton of chitin'},"answer":'D'},
{"id":53,"subject":'Biology',"topic":'Classification & Diversity',"difficulty":'Easy',
 "question":'Which taxonomic category groups together organisms that can potentially interbreed and produce fertile offspring?',
 "options":{"A":'Genus', "B":'Species', "C":'Family', "D":'Order'},"answer":'B'},
{"id":54,"subject":'Biology',"topic":'Classification & Diversity',"difficulty":'Medium',
 "question":'Members of phylum Echinodermata, such as starfish, are characterized by:',
 "options":{"A":'Bilateral symmetry as adults and a jointed exoskeleton', "B":'Radial symmetry (as adults) and a unique water vascular system', "C":'A segmented body with a true coelom only', "D":'A notochord present throughout their entire life'},"answer":'B'},
{"id":55,"subject":'Biology',"topic":'Plant Biology',"difficulty":'Easy',
 "question":'The primary pigment responsible for capturing light energy in most plants is:',
 "options":{"A":'Carotenoid', "B":'Chlorophyll', "C":'Anthocyanin', "D":'Xanthophyll'},"answer":'B'},
{"id":56,"subject":'Biology',"topic":'Plant Biology',"difficulty":'Medium',
 "question":'The electron transport chain in the thylakoid membrane, during the light-dependent reactions, ultimately generates a proton gradient used to produce:',
 "options":{"A":'Glucose directly', "B":'Carbon dioxide', "C":'Water only', "D":'ATP, via ATP synthase'},"answer":'D'},
{"id":57,"subject":'Biology',"topic":'Plant Biology',"difficulty":'Medium',
 "question":'In the Calvin cycle, the three-carbon compound produced immediately after CO2 fixation and reduction, from which glucose can eventually be formed, is:',
 "options":{"A":'Pyruvate', "B":'Oxaloacetate', "C":'RuBP', "D":'G3P (glyceraldehyde-3-phosphate)'},"answer":'D'},
{"id":58,"subject":'Biology',"topic":'Plant Biology',"difficulty":'Hard',
 "question":'Compared to C3 and C4 plants, CAM plants such as pineapple and many cacti conserve water mainly by:',
 "options":{"A":'Opening their stomata only during the day', "B":'Never carrying out the Calvin cycle', "C":'Lacking chlorophyll entirely', "D":'Fixing CO2 into organic acids at night when stomata are open, then using it in the Calvin cycle during the day with stomata closed'},"answer":'D'},
{"id":59,"subject":'Biology',"topic":'Plant Biology',"difficulty":'Medium',
 "question":'The movement of sugars from a leaf (source) to a growing fruit (sink) through the phloem is best explained by the:',
 "options":{"A":'Cohesion-tension theory', "B":'Pressure-flow (mass flow) hypothesis', "C":'Root pressure theory', "D":'Transpiration pull theory'},"answer":'B'},
{"id":60,"subject":'Biology',"topic":'Plant Biology',"difficulty":'Easy',
 "question":"A flower's male reproductive structure, which produces pollen, is called the:",
 "options":{"A":'Pistil', "B":'Sepal', "C":'Petal', "D":'Stamen'},"answer":'D'},
{"id":61,"subject":'Biology',"topic":'Human Physiology - Digestion',"difficulty":'Easy',
 "question":'The wave-like muscular contractions that push food through the esophagus toward the stomach are called:',
 "options":{"A":'Segmentation', "B":'Churning', "C":'Peristalsis', "D":'Emulsification'},"answer":'C'},
{"id":62,"subject":'Biology',"topic":'Human Physiology - Digestion',"difficulty":'Medium',
 "question":'Which of the following enzymes begins the digestion of proteins specifically within the stomach?',
 "options":{"A":'Trypsin', "B":'Salivary amylase', "C":'Pepsin', "D":'Lipase'},"answer":'C'},
{"id":63,"subject":'Biology',"topic":'Human Physiology - Digestion',"difficulty":'Medium',
 "question":"The primary role of the small intestine's brush-border enzymes (such as maltase and lactase) is to:",
 "options":{"A":'Begin the digestion of proteins', "B":'Emulsify dietary fats', "C":'Break down disaccharides into monosaccharides ready for absorption', "D":'Neutralize stomach acid'},"answer":'C'},
{"id":64,"subject":'Biology',"topic":'Human Physiology - Digestion',"difficulty":'Hard',
 "question":'Following removal of the gallbladder, a person may have difficulty digesting fatty foods mainly because:',
 "options":{"A":'The liver stops producing bile entirely', "B":'Bile is no longer stored and concentrated before release, reducing the efficiency of fat emulsification', "C":'The pancreas stops producing lipase', "D":'The stomach can no longer produce hydrochloric acid'},"answer":'B'},
{"id":65,"subject":'Biology',"topic":'Human Physiology - Circulation',"difficulty":'Easy',
 "question":'Blood returning to the heart from the lungs enters through the:',
 "options":{"A":'Vena cava', "B":'Pulmonary artery', "C":'Pulmonary veins', "D":'Aorta'},"answer":'C'},
{"id":66,"subject":'Biology',"topic":'Human Physiology - Circulation',"difficulty":'Medium',
 "question":'The septum separating the left and right sides of the heart primarily functions to:',
 "options":{"A":'Generate the heartbeat', "B":'Prevent oxygenated and deoxygenated blood from mixing', "C":'Produce red blood cells', "D":'Directly regulate blood pressure'},"answer":'B'},
{"id":67,"subject":'Biology',"topic":'Human Physiology - Circulation',"difficulty":'Medium',
 "question":'Platelets play their primary physiological role in:',
 "options":{"A":'Carrying oxygen throughout the body', "B":'Blood clotting at sites of vessel injury', "C":'Fighting bacterial infections', "D":'Producing antibodies'},"answer":'B'},
{"id":68,"subject":'Biology',"topic":'Human Physiology - Circulation',"difficulty":'Hard',
 "question":'An electrocardiogram (ECG) records:',
 "options":{"A":'The mechanical pumping force of the heart directly', "B":'Blood oxygen saturation', "C":"The electrical activity associated with the heart's contraction and relaxation", "D":'Blood pressure directly'},"answer":'C'},
{"id":69,"subject":'Biology',"topic":'Human Physiology - Respiration',"difficulty":'Easy',
 "question":'Air entering the nose is warmed, moistened, and filtered before passing through the:',
 "options":{"A":'Alveoli', "B":'Bronchioles only', "C":'Diaphragm', "D":'Pharynx and trachea'},"answer":'D'},
{"id":70,"subject":'Biology',"topic":'Human Physiology - Respiration',"difficulty":'Medium',
 "question":'The partial pressure gradient of oxygen between alveolar air and pulmonary capillary blood causes oxygen to:',
 "options":{"A":'Diffuse from the blood into the alveolar air', "B":'Diffuse from the alveolar air into the blood', "C":'Remain unchanged between the two compartments', "D":'Be actively transported into the blood using ATP'},"answer":'B'},
{"id":71,"subject":'Biology',"topic":'Human Physiology - Respiration',"difficulty":'Medium',
 "question":'The respiratory control center located in the medulla oblongata primarily adjusts breathing rate mainly in response to:',
 "options":{"A":'Blood glucose levels', "B":'Blood cell count', "C":'Blood CO2 (and pH) levels', "D":'Body temperature alone'},"answer":'C'},
{"id":72,"subject":'Biology',"topic":'Human Physiology - Excretion',"difficulty":'Easy',
 "question":"Blood is filtered under pressure into the Bowman's capsule at a structure called the:",
 "options":{"A":'Loop of Henle', "B":'Glomerulus', "C":'Collecting duct', "D":'Ureter'},"answer":'B'},
{"id":73,"subject":'Biology',"topic":'Human Physiology - Excretion',"difficulty":'Medium',
 "question":'Substances such as excess H+ ions and certain drugs are added to the filtrate from the blood in the nephron mainly during:',
 "options":{"A":'Tubular secretion', "B":'Filtration', "C":'Reabsorption', "D":'Micturition'},"answer":'A'},
{"id":74,"subject":'Biology',"topic":'Human Physiology - Excretion',"difficulty":'Hard',
 "question":'A person with uncontrolled diabetes mellitus may excrete glucose in their urine mainly because:',
 "options":{"A":'Blood glucose levels exceed the renal threshold, exceeding the capacity of transporters to reabsorb all filtered glucose', "B":'The kidneys deliberately secrete glucose into the filtrate', "C":'Insulin directly causes glucose excretion', "D":'The glomerulus stops filtering glucose entirely'},"answer":'A'},
{"id":75,"subject":'Biology',"topic":'Human Physiology - Nervous & Endocrine',"difficulty":'Easy',
 "question":'The gap between two neurons across which a nerve impulse is transmitted chemically is called the:',
 "options":{"A":'Axon', "B":'Dendrite', "C":'Nucleus', "D":'Synapse'},"answer":'D'},
{"id":76,"subject":'Biology',"topic":'Human Physiology - Nervous & Endocrine',"difficulty":'Medium',
 "question":'The parasympathetic division of the autonomic nervous system generally:',
 "options":{"A":"Prepares the body for 'fight or flight'", "B":'Has no effect on internal organs', "C":'Controls skeletal muscle exclusively', "D":"Promotes 'rest and digest' functions, such as slowing the heart rate"},"answer":'D'},
{"id":77,"subject":'Biology',"topic":'Human Physiology - Nervous & Endocrine',"difficulty":'Medium',
 "question":'Thyroid hormone (T3/T4) primarily functions to:',
 "options":{"A":'Regulate blood calcium levels only', "B":'Control blood glucose levels directly', "C":'Stimulate ovulation', "D":"Regulate the body's basal metabolic rate"},"answer":'D'},
{"id":78,"subject":'Biology',"topic":'Human Physiology - Nervous & Endocrine',"difficulty":'Hard',
 "question":'In negative feedback control of hormone secretion, a rising level of a hormone typically:',
 "options":{"A":'Further stimulates its own release', "B":'Inhibits further release of that hormone (or its releasing factors), helping maintain homeostasis', "C":'Has no effect on the endocrine gland producing it', "D":'Always triggers release of a completely unrelated hormone'},"answer":'B'},
{"id":79,"subject":'Biology',"topic":'Human Physiology - Reproduction',"difficulty":'Easy',
 "question":'In the human menstrual cycle, thickening of the uterine lining in preparation for a possible pregnancy is primarily driven by:',
 "options":{"A":'FSH alone', "B":'LH alone', "C":'Oxytocin', "D":'Estrogen and progesterone'},"answer":'D'},
{"id":80,"subject":'Biology',"topic":'Human Physiology - Reproduction',"difficulty":'Medium',
 "question":'If fertilization does not occur, the corpus luteum degenerates, causing a drop in progesterone that leads to:',
 "options":{"A":'Shedding of the uterine lining (menstruation)', "B":'Ovulation', "C":'Implantation of an embryo', "D":'A surge in LH'},"answer":'A'},
{"id":81,"subject":'Biology',"topic":'Ecology',"difficulty":'Medium',
 "question":'In an ecological pyramid, energy transfer between trophic levels is typically only about 10% efficient mainly because:',
 "options":{"A":'Producers absorb all available sunlight, leaving none for consumers', "B":'Consumers refuse to eat all of the food available to them', "C":'Energy cannot move between trophic levels at all', "D":'Most energy is lost as heat through cellular respiration and other metabolic processes at each level'},"answer":'D'},

# ============================================================
# CHEMISTRY (45 questions) - id 82-126
# ============================================================
{"id":82,"subject":'Chemistry',"topic":'Atomic Structure',"difficulty":'Easy',
 "question":'The number of neutrons in an atom can be calculated by subtracting the atomic number from the:',
 "options":{"A":'Number of electrons', "B":'Group number', "C":'Period number', "D":'Mass number'},"answer":'D'},
{"id":83,"subject":'Chemistry',"topic":'Atomic Structure',"difficulty":'Medium',
 "question":'An atom of oxygen-18 (atomic number 8) contains how many neutrons?',
 "options":{"A":'8', "B":'18', "C":'10', "D":'26'},"answer":'C'},
{"id":84,"subject":'Chemistry',"topic":'Atomic Structure',"difficulty":'Medium',
 "question":"According to Hund's rule, electrons filling degenerate (equal-energy) orbitals will:",
 "options":{"A":'Pair up in the same orbital before occupying any other orbital', "B":'Always pair immediately upon entering a subshell', "C":'Skip empty orbitals entirely', "D":'Occupy separate orbitals singly, with parallel spins, before any pairing occurs'},"answer":'D'},
{"id":85,"subject":'Chemistry',"topic":'Atomic Structure',"difficulty":'Hard',
 "question":'Two atoms with electron configurations [Ar]4s2 and [Ar]4s1 belong to which groups of the periodic table, respectively?',
 "options":{"A":'Group 1 and Group 2', "B":'Group 17 and Group 18', "C":'Group 2 and Group 1', "D":'Group 18 and Group 1'},"answer":'C'},
{"id":86,"subject":'Chemistry',"topic":'Periodic Table',"difficulty":'Easy',
 "question":'Elements are arranged in the periodic table in horizontal rows called:',
 "options":{"A":'Groups', "B":'Series', "C":'Blocks', "D":'Periods'},"answer":'D'},
{"id":87,"subject":'Chemistry',"topic":'Periodic Table',"difficulty":'Medium',
 "question":'Ionization energy generally decreases down a group mainly because:',
 "options":{"A":'Nuclear charge decreases going down a group', "B":'Valence electrons are farther from the nucleus and more shielded, so less energy is needed to remove them', "C":'Atoms become progressively smaller going down a group', "D":'Electronegativity increases going down a group'},"answer":'B'},
{"id":88,"subject":'Chemistry',"topic":'Periodic Table',"difficulty":'Medium',
 "question":'An element with high electronegativity and a strong tendency to gain electrons, located near the top-right of the periodic table (excluding noble gases), would most likely be:',
 "options":{"A":'A halogen, such as fluorine or chlorine', "B":'A highly reactive metal', "C":'A noble gas', "D":'An alkaline earth metal'},"answer":'A'},
{"id":89,"subject":'Chemistry',"topic":'Chemical Bonding',"difficulty":'Easy',
 "question":'A polar covalent bond forms when two bonded atoms:',
 "options":{"A":'Share electrons completely and equally', "B":'Transfer electrons completely from one atom to the other', "C":'Do not share any electrons at all', "D":'Share electrons unequally due to a difference in electronegativity'},"answer":'D'},
{"id":90,"subject":'Chemistry',"topic":'Chemical Bonding',"difficulty":'Medium',
 "question":'According to VSEPR theory, a molecule with four bonding pairs and no lone pairs on the central atom (e.g., CCl4) has a molecular shape described as:',
 "options":{"A":'Trigonal pyramidal', "B":'Bent', "C":'Tetrahedral', "D":'Square planar'},"answer":'C'},
{"id":91,"subject":'Chemistry',"topic":'Chemical Bonding',"difficulty":'Medium',
 "question":'Hydrogen bonding can occur between molecules when a hydrogen atom is directly bonded to:',
 "options":{"A":'Carbon only', "B":'A highly electronegative atom such as nitrogen, oxygen, or fluorine', "C":'Any nonmetal element', "D":'Sulfur only'},"answer":'B'},
{"id":92,"subject":'Chemistry',"topic":'Chemical Bonding',"difficulty":'Hard',
 "question":'Graphite conducts electricity, unlike diamond, mainly because graphite:',
 "options":{"A":'Contains ionic bonds between carbon atoms', "B":'Has delocalized electrons that can move freely between its layered sheets of carbon atoms', "C":'Consists of a network of individual, isolated molecules', "D":'Contains no covalent bonds whatsoever'},"answer":'B'},
{"id":93,"subject":'Chemistry',"topic":'States of Matter',"difficulty":'Easy',
 "question":'The process by which a gas changes directly into a solid, without passing through the liquid state, is called:',
 "options":{"A":'Sublimation', "B":'Condensation', "C":'Deposition', "D":'Fusion'},"answer":'C'},
{"id":94,"subject":'Chemistry',"topic":'States of Matter',"difficulty":'Medium',
 "question":"A sample of gas occupies 6.0 L at 2.0 atm. What pressure would be required to compress it to 1.5 L at constant temperature (Boyle's Law)?",
 "options":{"A":'8.0 atm', "B":'4.5 atm', "C":'2.0 atm', "D":'1.5 atm'},"answer":'A'},
{"id":95,"subject":'Chemistry',"topic":'States of Matter',"difficulty":'Hard',
 "question":"A gas has a volume of 4 L at 250 K. At constant pressure, what volume will it occupy at 500 K (Charles's Law)?",
 "options":{"A":'2 L', "B":'4 L', "C":'8 L', "D":'1000 L'},"answer":'C'},
{"id":96,"subject":'Chemistry',"topic":'Stoichiometry',"difficulty":'Easy',
 "question":'The molar mass of carbon dioxide (CO2) is approximately:',
 "options":{"A":'28 g/mol', "B":'44 g/mol', "C":'32 g/mol', "D":'16 g/mol'},"answer":'B'},
{"id":97,"subject":'Chemistry',"topic":'Stoichiometry',"difficulty":'Medium',
 "question":'How many grams of NaCl (molar mass 58.5 g/mol) are needed to prepare 2 moles of NaCl?',
 "options":{"A":'29.25 g', "B":'58.5 g', "C":'117 g', "D":'234 g'},"answer":'C'},
{"id":98,"subject":'Chemistry',"topic":'Stoichiometry',"difficulty":'Hard',
 "question":'A 500 mL solution is prepared by dissolving 0.25 mole of glucose. What is the molarity of the solution?',
 "options":{"A":'0.5 M', "B":'0.125 M', "C":'1.25 M', "D":'2.0 M'},"answer":'A'},
{"id":99,"subject":'Chemistry',"topic":'Stoichiometry',"difficulty":'Medium',
 "question":'In the reaction C3H8 + 5O2 -> 3CO2 + 4H2O, how many moles of CO2 are produced when 2 moles of propane (C3H8) react completely with excess O2?',
 "options":{"A":'6', "B":'2', "C":'3', "D":'5'},"answer":'A'},
{"id":100,"subject":'Chemistry',"topic":'Thermochemistry',"difficulty":'Easy',
 "question":'A reaction that absorbs heat from its surroundings, causing the surroundings to feel colder, is called:',
 "options":{"A":'Exothermic', "B":'Isothermal', "C":'Adiabatic', "D":'Endothermic'},"answer":'D'},
{"id":101,"subject":'Chemistry',"topic":'Thermochemistry',"difficulty":'Medium',
 "question":"Hess's law states that the total enthalpy change for a reaction is:",
 "options":{"A":'Dependent on the specific pathway taken to reach the products', "B":'Always equal to zero', "C":'The same regardless of the pathway taken, as long as the initial and final states are the same', "D":'Impossible to calculate indirectly'},"answer":'C'},
{"id":102,"subject":'Chemistry',"topic":'Chemical Equilibrium',"difficulty":'Medium',
 "question":'For the reversible reaction CaCO3(s) <-> CaO(s) + CO2(g), increasing the pressure by decreasing the container volume will shift the equilibrium:',
 "options":{"A":'Toward the products, since a gas is formed', "B":'Not at all, since solids are excluded from the equilibrium expression', "C":'Toward the reactant CaCO3(s), the side with fewer moles of gas', "D":'Completely, stopping the reaction entirely'},"answer":'C'},
{"id":103,"subject":'Chemistry',"topic":'Chemical Equilibrium',"difficulty":'Hard',
 "question":'If a chemist doubles the initial concentration of a reactant in a reaction at equilibrium, the value of the equilibrium constant, Keq, at that same temperature will:',
 "options":{"A":'Double as well', "B":'Be halved', "C":'Remain unchanged, since Keq depends only on temperature', "D":'Become undefined'},"answer":'C'},
{"id":104,"subject":'Chemistry',"topic":'Reaction Kinetics',"difficulty":'Easy',
 "question":'A rise in the frequency of collisions between reactant particles generally leads to:',
 "options":{"A":'A faster reaction rate', "B":'A slower reaction rate', "C":'No change in reaction rate', "D":'A decrease in activation energy'},"answer":'A'},
{"id":105,"subject":'Chemistry',"topic":'Reaction Kinetics',"difficulty":'Medium',
 "question":'The rate-determining step of a multi-step reaction mechanism is:',
 "options":{"A":'The fastest step in the sequence', "B":'Always the first step of the mechanism', "C":'Always the final step of the mechanism', "D":'The slowest step, which limits the overall rate of the reaction'},"answer":'D'},
{"id":106,"subject":'Chemistry',"topic":'Electrochemistry',"difficulty":'Medium',
 "question":'The salt bridge in a galvanic cell primarily functions to:',
 "options":{"A":'Maintain electrical neutrality by allowing ion flow between the two half-cells', "B":'Generate the electric current directly', "C":'Prevent any current from flowing in the circuit', "D":'Oxidize the electrodes directly'},"answer":'A'},
{"id":107,"subject":'Chemistry',"topic":'Electrochemistry',"difficulty":'Hard',
 "question":'In the reaction 2Al + 3Cu2+ -> 2Al3+ + 3Cu, aluminum is:',
 "options":{"A":'Reduced, acting as the oxidizing agent', "B":'Oxidized, acting as the reducing agent', "C":'Neither oxidized nor reduced', "D":'Acting purely as a catalyst'},"answer":'B'},
{"id":108,"subject":'Chemistry',"topic":'Acids & Bases',"difficulty":'Easy',
 "question":'A solution with a pH of 2 is:',
 "options":{"A":'Strongly basic', "B":'Neutral', "C":'Strongly acidic', "D":'Not chemically possible'},"answer":'C'},
{"id":109,"subject":'Chemistry',"topic":'Acids & Bases',"difficulty":'Medium',
 "question":'A solution has [OH-] = 1x10^-3 M. What is its pH (Kw = 1x10^-14)?',
 "options":{"A":'3', "B":'14', "C":'11', "D":'0'},"answer":'C'},
{"id":110,"subject":'Chemistry',"topic":'Acids & Bases',"difficulty":'Medium',
 "question":'According to the Lewis theory of acids and bases, a Lewis acid is a species that:',
 "options":{"A":'Accepts a pair of electrons to form a new covalent bond', "B":'Donates a pair of electrons', "C":'Donates a proton only', "D":'Always contains oxygen'},"answer":'A'},
{"id":111,"subject":'Chemistry',"topic":'Acids & Bases',"difficulty":'Hard',
 "question":'The titration curve shows a weak acid (CH3COOH) being titrated with a strong base (NaOH). Based on the shape of the curve, the pH at the equivalence point is expected to be:',
 "image":'images/q_titration_weak_acid_strong_base.png',
 "options":{"A":'Exactly 7 (neutral)', "B":'Less than 7 (acidic)', "C":'Undefined, since weak acids have no equivalence point', "D":'Greater than 7 (basic), because the conjugate base formed undergoes hydrolysis'},"answer":'D'},
{"id":112,"subject":'Chemistry',"topic":'Organic Chemistry',"difficulty":'Easy',
 "question":'The general formula for an alkene is:',
 "options":{"A":'CnH2n+2', "B":'CnH2n-2', "C":'CnH2n', "D":'CnHn'},"answer":'C'},
{"id":113,"subject":'Chemistry',"topic":'Organic Chemistry',"difficulty":'Medium',
 "question":'Substitution reactions are more typical of alkanes than addition reactions mainly because alkanes:',
 "options":{"A":'Contain reactive carbon-carbon double bonds', "B":'Are ionic compounds', "C":'Have no hydrogen atoms at all', "D":'Contain only strong, relatively unreactive single (sigma) bonds'},"answer":'D'},
{"id":114,"subject":'Chemistry',"topic":'Organic Chemistry',"difficulty":'Medium',
 "question":'The functional group present in a carboxylic acid is:',
 "options":{"A":'-COOH', "B":'-OH', "C":'-CHO', "D":'-C-O-C-'},"answer":'A'},
{"id":115,"subject":'Chemistry',"topic":'Organic Chemistry',"difficulty":'Hard',
 "question":"In an addition reaction of HBr with an unsymmetrical alkene, Markovnikov's rule predicts that the hydrogen atom preferentially bonds to the carbon that:",
 "options":{"A":'Has the fewest hydrogen atoms attached', "B":'Already has the most hydrogen atoms attached, so H+ forms the more stable carbocation on the other carbon', "C":'Is part of the most substituted end of the double bond', "D":'Is always the terminal carbon of the chain'},"answer":'B'},
{"id":116,"subject":'Chemistry',"topic":'Organic Chemistry',"difficulty":'Medium',
 "question":'Esters are typically formed by the reaction between a carboxylic acid and an:',
 "options":{"A":'Amine', "B":'Alkene', "C":'Alcohol, releasing water (esterification)', "D":'Alkane'},"answer":'C'},
{"id":117,"subject":'Chemistry',"topic":'Organic Chemistry',"difficulty":'Easy',
 "question":'A compound containing only carbon and hydrogen atoms is classified as a:',
 "options":{"A":'Hydrocarbon', "B":'Carbohydrate', "C":'Alcohol', "D":'Halide'},"answer":'A'},
{"id":118,"subject":'Chemistry',"topic":'Inorganic Chemistry',"difficulty":'Medium',
 "question":'The reactivity of alkali metals (Group 1) increases down the group mainly because:',
 "options":{"A":'The outermost electron is held less tightly, as atomic radius and shielding both increase', "B":'Nuclear charge increases faster than shielding down the group', "C":'Atomic radius decreases going down the group', "D":'Ionization energy increases sharply down the group'},"answer":'A'},
{"id":119,"subject":'Chemistry',"topic":'Inorganic Chemistry',"difficulty":'Medium',
 "question":'Transition metals commonly exhibit multiple oxidation states mainly because:',
 "options":{"A":'Their d-electrons and s-electrons are relatively close in energy, allowing a variable number to be lost', "B":'They have only one valence electron', "C":'They never form ions of any kind', "D":'They always have completely filled d-orbitals'},"answer":'A'},
{"id":120,"subject":'Chemistry',"topic":'Inorganic Chemistry',"difficulty":'Hard',
 "question":"In the reaction Zn + 2HCl -> ZnCl2 + H2, hydrogen's oxidation state changes from:",
 "options":{"A":'0 to +1 (oxidation)', "B":'-1 to +1', "C":'No change occurs', "D":'+1 to 0 (reduction)'},"answer":'D'},
{"id":121,"subject":'Chemistry',"topic":'Physical Chemistry',"difficulty":'Medium',
 "question":'The mole fraction of a component in a solution is defined as:',
 "options":{"A":'Moles of component divided by the total moles of all components in the solution', "B":'Moles of component divided by the total mass of the solution', "C":'Grams of component divided by total volume of solution', "D":'Moles of component per liter of solvent'},"answer":'A'},
{"id":122,"subject":'Chemistry',"topic":'Physical Chemistry',"difficulty":'Hard',
 "question":'40 mL of 0.25 M HNO3 is required to completely neutralize 20 mL of NaOH solution (HNO3 + NaOH -> NaNO3 + H2O). What is the molarity of the NaOH solution?',
 "options":{"A":'0.5 M', "B":'0.25 M', "C":'1.0 M', "D":'0.125 M'},"answer":'A'},
{"id":123,"subject":'Chemistry',"topic":'Environmental Chemistry',"difficulty":'Easy',
 "question":'Chlorofluorocarbons (CFCs), once widely used as refrigerants, are of environmental concern mainly because they:',
 "options":{"A":'Deplete the stratospheric ozone layer', "B":'Increase soil acidity', "C":'Increase the salinity of ocean water', "D":'Have no significant environmental effects'},"answer":'A'},
{"id":124,"subject":'Chemistry',"topic":'Environmental Chemistry',"difficulty":'Medium',
 "question":'Photochemical smog forms mainly when:',
 "options":{"A":'Sulfur dioxide reacts directly with rainwater', "B":'Nitrogen oxides and volatile organic compounds react in sunlight, producing ozone and other pollutants near ground level', "C":'Carbon dioxide accumulates in the upper atmosphere', "D":'Methane is released from wetlands'},"answer":'B'},
{"id":125,"subject":'Chemistry',"topic":'Chemical Bonding',"difficulty":'Easy',
 "question":'A single covalent bond between two atoms consists of the sharing of:',
 "options":{"A":'Two pairs of electrons', "B":'Three pairs of electrons', "C":'No electrons at all', "D":'One pair of electrons'},"answer":'D'},
{"id":126,"subject":'Chemistry',"topic":'Atomic Structure',"difficulty":'Easy',
 "question":'The overall charge of a neutral atom is zero because it contains:',
 "options":{"A":'Equal numbers of protons and neutrons', "B":'Equal numbers of protons and electrons', "C":'Only neutrons and no charged particles', "D":'More electrons than protons'},"answer":'B'},

# ============================================================
# PHYSICS (36 questions) - id 127-162
# ============================================================
{"id":127,"subject":'Physics',"topic":'Kinematics',"difficulty":'Easy',
 "question":"A runner covers 400 m in 50 seconds at constant speed. What is the runner's speed?",
 "options":{"A":'6 m/s', "B":'10 m/s', "C":'20000 m/s', "D":'8 m/s'},"answer":'D'},
{"id":128,"subject":'Physics',"topic":'Kinematics',"difficulty":'Medium',
 "question":'A car accelerates uniformly from 10 m/s to 30 m/s over 4 seconds. What is its acceleration?',
 "options":{"A":'10 m/s^2', "B":'2.5 m/s^2', "C":'40 m/s^2', "D":'5 m/s^2'},"answer":'D'},
{"id":129,"subject":'Physics',"topic":'Kinematics',"difficulty":'Hard',
 "question":'A stone is thrown vertically upward with an initial velocity of 30 m/s (g = 10 m/s^2, ignoring air resistance). What maximum height does it reach?',
 "options":{"A":'30 m', "B":'60 m', "C":'90 m', "D":'45 m'},"answer":'D'},
{"id":130,"subject":'Physics',"topic":'Dynamics',"difficulty":'Easy',
 "question":'An object continues moving at constant velocity in a straight line unless acted upon by a net external force. This is a statement of:',
 "options":{"A":"Newton's second law", "B":"Newton's first law (the law of inertia)", "C":"Newton's third law", "D":'The law of conservation of energy'},"answer":'B'},
{"id":131,"subject":'Physics',"topic":'Dynamics',"difficulty":'Medium',
 "question":"A net force of 24 N produces an acceleration of 3 m/s^2 in an object. What is the object's mass?",
 "options":{"A":'72 kg', "B":'3 kg', "C":'8 kg', "D":'0.125 kg'},"answer":'C'},
{"id":132,"subject":'Physics',"topic":'Dynamics',"difficulty":'Medium',
 "question":'When a swimmer pushes backward against the water, the water pushes the swimmer forward with an equal and opposite force. This illustrates:',
 "options":{"A":"Newton's first law", "B":"Newton's second law", "C":'The law of inertia alone', "D":"Newton's third law"},"answer":'D'},
{"id":133,"subject":'Physics',"topic":'Dynamics',"difficulty":'Hard',
 "question":'A 2 kg object is pulled horizontally by a 15 N force across a surface with a coefficient of kinetic friction of 0.3 (g = 10 m/s^2). What is its acceleration?',
 "options":{"A":'4.5 m/s^2', "B":'7.5 m/s^2', "C":'1.5 m/s^2', "D":'3 m/s^2'},"answer":'A'},
{"id":134,"subject":'Physics',"topic":'Work, Energy & Power',"difficulty":'Easy',
 "question":'The kinetic energy of a moving object depends on its:',
 "options":{"A":'Mass and acceleration', "B":'Weight and time', "C":'Mass and velocity', "D":'Volume and speed'},"answer":'C'},
{"id":135,"subject":'Physics',"topic":'Work, Energy & Power',"difficulty":'Medium',
 "question":'How much work is done in lifting a 10 kg object to a height of 3 m (g = 10 m/s^2)?',
 "options":{"A":'30 J', "B":'3 J', "C":'100 J', "D":'300 J'},"answer":'D'},
{"id":136,"subject":'Physics',"topic":'Work, Energy & Power',"difficulty":'Medium',
 "question":'A spring stores elastic potential energy when it is:',
 "options":{"A":'Compressed or stretched away from its natural length', "B":'At its natural, unstretched length', "C":'Moving at constant velocity', "D":'Heated to a higher temperature'},"answer":'A'},
{"id":137,"subject":'Physics',"topic":'Work, Energy & Power',"difficulty":'Hard',
 "question":'An electric motor does 1200 J of work in 15 seconds. What is its power output?',
 "options":{"A":'18000 W', "B":'80 W', "C":'800 W', "D":'8 W'},"answer":'B'},
{"id":138,"subject":'Physics',"topic":'Circular Motion & Gravitation',"difficulty":'Easy',
 "question":"The SI unit of gravitational field strength (g) at Earth's surface is:",
 "options":{"A":'kg', "B":'m/s^2', "C":'N', "D":'J'},"answer":'B'},
{"id":139,"subject":'Physics',"topic":'Circular Motion & Gravitation',"difficulty":'Medium',
 "question":"According to Newton's law of universal gravitation, if the mass of one object is tripled while distance and the other mass remain constant, the gravitational force becomes:",
 "options":{"A":'Three times the original', "B":'One third of the original', "C":'Nine times the original', "D":'Unchanged'},"answer":'A'},
{"id":140,"subject":'Physics',"topic":'Circular Motion & Gravitation',"difficulty":'Hard',
 "question":"A planet has twice the mass of Earth and twice Earth's radius. Compared to Earth's surface gravity, the surface gravity of this planet is:",
 "options":{"A":"Half of Earth's", "B":"The same as Earth's", "C":"Twice Earth's", "D":"Four times Earth's"},"answer":'A'},
{"id":141,"subject":'Physics',"topic":'Fluid Mechanics',"difficulty":'Easy',
 "question":'Density is defined as:',
 "options":{"A":'Mass per unit volume', "B":'Volume per unit mass', "C":'Force per unit area', "D":'Mass per unit area'},"answer":'A'},
{"id":142,"subject":'Physics',"topic":'Fluid Mechanics',"difficulty":'Medium',
 "question":'A hydraulic lift uses a small input force applied over a small piston area to generate a much larger output force over a larger piston area. This works based on:',
 "options":{"A":"Bernoulli's principle", "B":"Pascal's principle", "C":"Archimedes' principle", "D":"Newton's third law alone"},"answer":'B'},
{"id":143,"subject":'Physics',"topic":'Fluid Mechanics',"difficulty":'Hard',
 "question":'A boat floats higher in salt water than in fresh water mainly because:',
 "options":{"A":'Salt water has a lower density than fresh water', "B":'Salt water exerts no buoyant force', "C":'Fresh water is more viscous than salt water', "D":"Salt water has a higher density than fresh water, so less volume needs to be displaced to equal the boat's weight"},"answer":'D'},
{"id":144,"subject":'Physics',"topic":'Oscillations & Waves',"difficulty":'Easy',
 "question":'The distance between two successive crests of a wave is called its:',
 "options":{"A":'Wavelength', "B":'Amplitude', "C":'Frequency', "D":'Period'},"answer":'A'},
{"id":145,"subject":'Physics',"topic":'Oscillations & Waves',"difficulty":'Medium',
 "question":'A mass-spring system oscillates with a certain period. If the mass is increased while the spring constant stays the same, the period will:',
 "options":{"A":'Decrease', "B":'Remain exactly the same', "C":'Become zero', "D":'Increase'},"answer":'D'},
{"id":146,"subject":'Physics',"topic":'Oscillations & Waves',"difficulty":'Medium',
 "question":'A wave has a wavelength of 4 m and travels at 20 m/s. What is its frequency?',
 "options":{"A":'80 Hz', "B":'5 Hz', "C":'0.2 Hz', "D":'24 Hz'},"answer":'B'},
{"id":147,"subject":'Physics',"topic":'Oscillations & Waves',"difficulty":'Hard',
 "question":'The Doppler effect describes how the observed frequency of a wave changes when:',
 "options":{"A":"The wave's amplitude changes", "B":'The medium is completely still', "C":'There is relative motion between the source and the observer', "D":"The wave's speed changes with no motion involved"},"answer":'C'},
{"id":148,"subject":'Physics',"topic":'Thermodynamics',"difficulty":'Easy',
 "question":'The specific heat capacity of a substance is defined as the amount of heat required to:',
 "options":{"A":'Raise the temperature of one kilogram of the substance by one degree', "B":'Melt one kilogram of the substance', "C":'Boil one kilogram of the substance', "D":'Freeze one kilogram of the substance'},"answer":'A'},
{"id":149,"subject":'Physics',"topic":'Thermodynamics',"difficulty":'Medium',
 "question":'An isothermal process is one in which:',
 "options":{"A":'No heat is exchanged with the surroundings', "B":'The temperature of the system remains constant throughout', "C":'The volume of the system remains constant', "D":'The pressure of the system remains constant'},"answer":'B'},
{"id":150,"subject":'Physics',"topic":'Thermodynamics',"difficulty":'Hard',
 "question":'A 2 kg block of ice at 0 degrees C absorbs 672,000 J of heat to completely melt (latent heat of fusion of ice is approximately 336,000 J/kg). Based on this, how much heat would be needed to melt 1 kg of ice?',
 "options":{"A":'336,000 J', "B":'168,000 J', "C":'672,000 J', "D":'1,008,000 J'},"answer":'A'},
{"id":151,"subject":'Physics',"topic":'Electrostatics',"difficulty":'Easy',
 "question":'The SI unit of electric charge is the:',
 "options":{"A":'Ampere', "B":'Volt', "C":'Coulomb', "D":'Ohm'},"answer":'C'},
{"id":152,"subject":'Physics',"topic":'Electrostatics',"difficulty":'Medium',
 "question":'Two point charges separated by a certain distance experience a force F. If the distance between them is doubled, the new force becomes:',
 "options":{"A":'F/2', "B":'2F', "C":'4F', "D":'F/4'},"answer":'D'},
{"id":153,"subject":'Physics',"topic":'Current Electricity',"difficulty":'Easy',
 "question":'An ammeter is used to measure:',
 "options":{"A":'Electric current', "B":'Voltage', "C":'Resistance', "D":'Power'},"answer":'A'},
{"id":154,"subject":'Physics',"topic":'Current Electricity',"difficulty":'Medium',
 "question":'In the circuit shown, R1 (5 ohm) and R2 (5 ohm) are connected in parallel with each other, and this combination is connected in series with R3 (3 ohm). What is the total resistance of the circuit?',
 "image":'images/q_circuit_r1_r2_parallel_r3_series.png',
 "options":{"A":'2.5 ohm', "B":'5.5 ohm', "C":'8 ohm', "D":'13 ohm'},"answer":'B'},
{"id":155,"subject":'Physics',"topic":'Current Electricity',"difficulty":'Hard',
 "question":'A 12 V battery is connected across a 4 ohm resistor in series with a 2 ohm resistor. What current flows through the circuit?',
 "options":{"A":'6 A', "B":'3 A', "C":'2 A', "D":'8 A'},"answer":'C'},
{"id":156,"subject":'Physics',"topic":'Current Electricity',"difficulty":'Medium',
 "question":'A 100 W bulb operates at 220 V. What current does it draw?',
 "options":{"A":'2.2 A', "B":'22000 A', "C":'0.45 A', "D":'100 A'},"answer":'C'},
{"id":157,"subject":'Physics',"topic":'Electromagnetism',"difficulty":'Medium',
 "question":'A changing magnetic field through a coil induces an EMF in that coil. This phenomenon is called:',
 "options":{"A":'Electrolysis', "B":'Electromagnetic induction', "C":'Static discharge', "D":'Magnetic saturation'},"answer":'B'},
{"id":158,"subject":'Physics',"topic":'Electromagnetism',"difficulty":'Hard',
 "question":'A DC motor operates by converting:',
 "options":{"A":'Mechanical energy into electrical energy', "B":'Electrical energy into mechanical energy, using the force on a current-carrying coil in a magnetic field', "C":'Chemical energy directly into heat', "D":'Sound energy into electrical energy'},"answer":'B'},
{"id":159,"subject":'Physics',"topic":'Modern Physics',"difficulty":'Easy',
 "question":'The atomic number of an element is equal to the number of ______ in its nucleus.',
 "options":{"A":'Neutrons', "B":'Electrons in the outer shell', "C":'Protons', "D":'Isotopes'},"answer":'C'},
{"id":160,"subject":'Physics',"topic":'Modern Physics',"difficulty":'Medium',
 "question":'In alpha decay, the mass number of the daughter nucleus compared to the parent nucleus:',
 "options":{"A":'Increases by 4', "B":'Stays exactly the same', "C":'Decreases by 2', "D":'Decreases by 4'},"answer":'D'},
{"id":161,"subject":'Physics',"topic":'Modern Physics',"difficulty":'Hard',
 "question":'A radioactive isotope decays such that only 1/8 of the original sample remains after 24 hours. What is the half-life of this isotope?',
 "options":{"A":'3 hours', "B":'6 hours', "C":'12 hours', "D":'8 hours'},"answer":'D'},
{"id":162,"subject":'Physics',"topic":'Optics',"difficulty":'Medium',
 "question":'The ray diagram shows an object placed beyond the center of curvature (C) of a concave mirror. Based on the diagram, the image formed is:',
 "image":'images/q_concave_mirror_beyond_c.png',
 "options":{"A":'Real, inverted, and diminished, formed between F and C', "B":'Virtual, upright, and magnified', "C":'Real, upright, and the same size as the object', "D":'Virtual, inverted, and enlarged'},"answer":'A'},

# ============================================================
# ENGLISH (9 questions) - id 163-171
# ============================================================
{"id":163,"subject":'English',"topic":'Synonyms',"difficulty":'Easy',
 "question":"Choose the word most nearly similar in meaning to 'INNOVATIVE':",
 "options":{"A":'Conventional', "B":'Outdated', "C":'Original', "D":'Rigid'},"answer":'C'},
{"id":164,"subject":'English',"topic":'Antonyms',"difficulty":'Easy',
 "question":"Choose the word most nearly opposite in meaning to 'DILIGENT':",
 "options":{"A":'Hardworking', "B":'Lazy', "C":'Careful', "D":'Attentive'},"answer":'B'},
{"id":165,"subject":'English',"topic":'Grammar',"difficulty":'Easy',
 "question":'Choose the grammatically correct sentence:',
 "options":{"A":"She don't know the answer.", "B":"She doesn't know the answer.", "C":"She doesn't knows the answer.", "D":'She not knows the answer.'},"answer":'B'},
{"id":166,"subject":'English',"topic":'Grammar',"difficulty":'Medium',
 "question":'Choose the correct sentence:',
 "options":{"A":'If it rains, we will cancel the picnic.', "B":'If it will rain, we cancel the picnic.', "C":'If it rains, we would cancel the picnic.', "D":'If it rain, we will cancel the picnic.'},"answer":'A'},
{"id":167,"subject":'English',"topic":'Sentence Correction',"difficulty":'Medium',
 "question":'Identify the sentence that follows correct subject-verb agreement:',
 "options":{"A":'Everyone have submitted their assignments.', "B":'Everyone has submitted his or her assignment.', "C":'Everyone have submitted his assignment.', "D":'Everyone has submit their assignment.'},"answer":'B'},
{"id":168,"subject":'English',"topic":'Vocabulary',"difficulty":'Medium',
 "question":"Choose the word that best completes the sentence: 'Despite years of research, the exact cause of the disease remains ______.'",
 "options":{"A":'Obvious', "B":'Confirmed', "C":'Simple', "D":'Elusive'},"answer":'D'},
{"id":169,"subject":'English',"topic":'Idioms',"difficulty":'Medium',
 "question":"Choose the meaning closest to the idiom 'to hit the nail on the head':",
 "options":{"A":'To make a careless mistake', "B":'To argue without making any real point', "C":'To say or do something exactly right', "D":'To finish a task very quickly'},"answer":'C'},
{"id":170,"subject":'English',"topic":'Sentence Correction',"difficulty":'Hard',
 "question":"Choose the option that best corrects the sentence: 'Being a rainy day, we decided to stay home.'",
 "options":{"A":'It being a rainy day, we decided to stay home.', "B":'Both A and C are acceptable corrections.', "C":'Being a rainy day, we decide to stay home.', "D":'Because it was a rainy day, we decided to stay home.'},"answer":'B'},
{"id":171,"subject":'English',"topic":'Prepositions',"difficulty":'Hard',
 "question":"Choose the correct preposition: 'The company was accused ______ violating environmental regulations.'",
 "options":{"A":'for', "B":'with', "C":'about', "D":'of'},"answer":'D'},

# ============================================================
# LOGICAL REASONING (9 questions) - id 172-180
# ============================================================
{"id":172,"subject":'Logical Reasoning',"topic":'Number Series',"difficulty":'Easy',
 "question":'Find the next number in the series: 7, 14, 21, 28, ?',
 "options":{"A":'30', "B":'35', "C":'42', "D":'32'},"answer":'B'},
{"id":173,"subject":'Logical Reasoning',"topic":'Number Series',"difficulty":'Easy',
 "question":'Find the missing number: 81, 27, 9, 3, ?',
 "options":{"A":'1', "B":'0', "C":'2', "D":'-3'},"answer":'A'},
{"id":174,"subject":'Logical Reasoning',"topic":'Analogies',"difficulty":'Easy',
 "question":'Chef is to Kitchen as Pilot is to:',
 "options":{"A":'Airport', "B":'Sky', "C":'Cockpit', "D":'Airplane'},"answer":'C'},
{"id":175,"subject":'Logical Reasoning',"topic":'Analogies',"difficulty":'Medium',
 "question":'Pen is to Author as Brush is to:',
 "options":{"A":'Canvas', "B":'Painter', "C":'Paint', "D":'Palette'},"answer":'B'},
{"id":176,"subject":'Logical Reasoning',"topic":'Blood Relations',"difficulty":'Medium',
 "question":"Introducing a boy, a woman said, 'He is the son of my mother's only daughter.' How is the boy related to the woman?",
 "options":{"A":'Son', "B":'Nephew', "C":'Brother', "D":'Cousin'},"answer":'A'},
{"id":177,"subject":'Logical Reasoning',"topic":'Coding-Decoding',"difficulty":'Medium',
 "question":'If in a certain code, APPLE is written as BQQMF, how is MANGO written in the same code?',
 "options":{"A":'NBOHO', "B":'LBOHP', "C":'NBPHP', "D":'NBOHP'},"answer":'D'},
{"id":178,"subject":'Logical Reasoning',"topic":'Syllogism',"difficulty":'Hard',
 "question":'All doctors are educated. Some educated people are wealthy. Which conclusion logically follows?',
 "options":{"A":'All doctors are wealthy', "B":'Some doctors are definitely wealthy', "C":'No definite conclusion can be drawn about doctors being wealthy', "D":'No doctors are wealthy'},"answer":'C'},
{"id":179,"subject":'Logical Reasoning',"topic":'Pattern Recognition',"difficulty":'Hard',
 "question":'Find the next term in the series: 3, 6, 11, 18, 27, ?',
 "options":{"A":'38', "B":'36', "C":'40', "D":'34'},"answer":'A'},
{"id":180,"subject":'Logical Reasoning',"topic":'Direction Sense',"difficulty":'Medium',
 "question":'A man walks 7 km west, then turns right and walks 4 km, then turns right again and walks 7 km. How far is he from his starting point?',
 "options":{"A":'18 km', "B":'14 km', "C":'4 km', "D":'7 km'},"answer":'C'},
]


# ------------------------------------------------------------
# Sanity-check / summary utility
# ------------------------------------------------------------
def summarize(questions):
    from collections import Counter
    subj = Counter(q["subject"] for q in questions)
    diff = Counter(q["difficulty"] for q in questions)
    ans = Counter(q["answer"] for q in questions)
    ids = [q["id"] for q in questions]
    dup_ids = [i for i in set(ids) if ids.count(i) > 1]
    dup_q = [q["question"] for q in questions]
    dup_questions = [t for t in set(dup_q) if dup_q.count(t) > 1]
    images = [q for q in questions if "image" in q]

    print(f"Total questions: {len(questions)}")
    print("\nBy subject:")
    for s, c in subj.items():
        print(f"  {s}: {c}")
    print("\nBy difficulty:")
    for d, c in diff.items():
        print(f"  {d}: {c}")
    print("\nBy correct-answer letter (should be roughly balanced):")
    for L in ["A", "B", "C", "D"]:
        print(f"  {L}: {ans[L]}")
    print(f"\nDuplicate IDs: {dup_ids if dup_ids else 'None'}")
    print(f"Duplicate question text: {dup_questions if dup_questions else 'None'}")
    print(f"\nImage-based questions ({len(images)}):")
    for q in images:
        print(f"  Q{q['id']} [{q['subject']}] -> {q['image']}")

    for q in questions:
        assert set(q["options"].keys()) == {"A", "B", "C", "D"}, f"Q{q['id']} missing an option"
        assert q["answer"] in q["options"], f"Q{q['id']} answer key invalid"
    print("\nAll questions have exactly 4 options (A-D) and a valid answer key. OK.")


def print_answer_key(questions):
    print("\nANSWER KEY")
    print("-" * 40)
    for q in questions:
        print(f"{q['id']:>3}. {q['answer']}", end="   ")
        if q["id"] % 10 == 0:
            print()
    print()


if __name__ == "__main__":
    summarize(QUESTIONS)
    print_answer_key(QUESTIONS)