# -*- coding: utf-8 -*-
# Transcribed from UHS MDCAT 2022 paper (Q1-190) + official key (Q1-200)

SUBJECTS = [
    ("BIOLOGY", 1, 68),
    ("CHEMISTRY", 69, 122),
    ("PHYSICS", 123, 176),
    ("ENGLISH", 177, 190),
]

QUESTIONS = {
1: ("What does the term bacteriophage refer to?", ["A virus that infects bacteria","A bacterium that infects virus","A virus which behaves as bacteria","Combination of Bacterium & Virion"]),
2: ("What of the following virus contains single stranded DNA?", ["Adeno virus","Herpes virus","Parvo virus","Pox virus"]),
3: ("How may tail fibrils are attached to the end plate of a bacteriophage?", ["2","4","6","8"]),
4: ("The enzymes integrase, protease and reverse transcriptase are found in which virus?", ["Hepatitis A virus","Herpes virus","Influenza virus","Human immunodeficiency virus"]),
5: ("What is the end product of glucose by yeast in anaerobic respiration?", ["Ethanol and oxygen","Ethanol and water","Ethanol and CO2","Lactic acid and CO2"]),
6: ("Each carrier in Electron Transport Chain is first _______ and then _______.", ["Broken-down, Regenerate","Generated, Broken-down","Oxidized, Reduced","Reduced, Oxidized"]),
7: ("Electron transport chain explains:", ["Photophosphorylation","Z-Scheme","Photolysis","Mechanism of ATP synthesis"]),
8: ("What is the colour of Chlorophyll-b molecule?", ["Blueish green","Yellowish green","Dark Green","Reddish green"]),
9: ("Upon initial hydrolysis starch yields:", ["Maltose","Glucose","Sucrose","Mannose"]),
10: ("Human Bone cells contain..........% of water?", ["20","40","85","90"]),
11: ("Unique three-dimensional shape of the fully folded polypeptide, constitutes:", ["Primary structure of protein","Secondary structure of protein","Tertiary structure of protein","Quaternary structure of protein"]),
12: ("Butyric acid is a _______ carbon fatty acid.", ["6","2","4","8"]),
13: ("Which of the following is a conjugated molecule?", ["Protein","Lipid","Glycoproteins","Vitamins"]),
14: ("Hydrolysis process is a reverse of ------------------- process.", ["Photolysis","Condensation","Deduction","Convection"]),
15: ("Proteins are the main ------------ of the cell?", ["Physiological components","Functional components","Structural components","Biological components"]),
16: ("Cell wall may be absent in which of the following?", ["Plant & Algae","Algae & Fungi","Fungi & Archaea","Bacteria & Archaea"]),
17: ("Structure formed by invagination of plasma membrane and involved in cell division and DNA replication of prokaryotic cell:", ["Lysosomes","Mesosomes","Golgi bodies","Phragmoplasts"]),
18: ("Which of the following are single membranous organelles?", ["Mitochondria and ribosomes","Cytosol, mitochondria and ribosomes","Golgi bodies, Lysosome and ER","Golgi bodies, lysosome and mitochondria"]),
19: ("Movement of molecules against the concentration gradient is?", ["Passive transport","Active transport","Facilitated diffusion","Filtration"]),
20: ("The digestive vacuoles and autophagosomes are also known as?", ["Phagocytosis","Primary lysosome and autophagy","Secondary lysosome","Peroxisome"]),
21: ("The cell wall of Bacteria is made up of:", ["Chitin","Murein","Cellulose","Hemicellulose"]),
22: ("Which one is common in both prokaryotic and eukaryotic cells?", ["Cytoplasmic streaming movement","Ribosome","Binary fission","Nuclear envelope"]),
23: ("There is no clear difference between dendrites and axons in sensory neurons, except:", ["Thickness","Length","Terminal portions","None of the above"]),
24: ("The neurotransmitter active outside the CNS (Central Nervous System) is:", ["Acetylcholine","Dopamine","Glutamate","Serotonin"]),
25: ("A hormone that plays a major role in social bonding, childbirth, milk ejection and sexual reproduction is:", ["Estrogen","Oxytocin","Prolactin","Secretin"]),
26: ("Hormone produced by placenta is:", ["Follicle-Stimulating Hormone (FSH)","Luteinizing Hormone (LH)","Progesterone","Testosterone"]),
27: ("The middle layer of meninges is:", ["Arachnoid mater","Pia mater","Dura mater","Cranium"]),
28: ("The part of brain which guides smooth and accurate motions and maintains body position is:", ["Cerebrum","Cerebellum","Pons","Medulla"]),
29: ("Water vascular system or ambulacral system is a unique and complex system specially present in?", ["Sponges","Arthropods","Echinoderms","Fishes"]),
30: ("Round worms belong to which phylum?", ["Annelida","Coelenterata","Nematoda","Platyhelminthes"]),
31: ("Silver fish is a/an?", ["Insect","Mollusc","Jawless fish","Cartilaginous fish"]),
32: ("Tissue are not found in the following animal?", ["Flat worms","Sponges","Cnidarians","Round worms"]),
33: ("Enzymes lower the activation energy by stabilizing the transition state of a metabolic reaction due to?", ["Changing conditions within the active site","Changing conditions within the protein framework","Rearranging the fatty acids in active site","Distorting the molecules in the allosteric site"]),
34: ("Competitive inhibitors compete with?", ["Enzyme","Substrate","Product","Coenzyme"]),
35: ("Non-competitive inhibitor molecules have:", ["A similar structure to the normal substrate molecule","A quite different structure from the substrate molecule","A different conformation but fit into the active site","A similar conformation but does not fit into the active site"]),
36: ("Zinc ion is attached at the active site of the enzyme carboxypeptidase. The zinc ion functions as:", ["A coenzyme molecule","An activator","An inhibitor molecule","Controller of Allosteric site"]),
37: ("What is the best physiological pH for optimum functioning for most of the cellular enzymes of human?", ["2-3 pH","3-5 pH","6-8 pH","8-10 pH"]),
38: ("Adaptations that an organism acquires by its own actions during its life span without modifying its genome are:", ["Heritable","Non-heritable","Can be made heritable through some modification","Sometimes heritable and other times non-heritable"]),
39: ("For evolutionary process to occur, which of the following is NOT a geographical barrier?", ["Ocean","River","Mountains","Atmosphere"]),
40: ("According to the Biogenetic Law of Ernst Haeckel:", ["There is survival of the fittest","There is use and disuse of organs","Phylogeny recapitulates ontogeny","Ontogeny recapitulates phylogeny"]),
41: ("The animal species on Galapagos resemble species living on the:", ["Northern Europe","Great Britain","North American mainland","South American mainland"]),
42: ("Digested food from intestine is carried to the liver by?", ["Hepatic artery","Hepatic vein","Hepatic portal vein","Hepatic portal artery"]),
43: ("------------ proteins are produced by WBCs in response to --------- and provide immunity?", ["Antibiotics, antigen","Antibodies, RBC","Globulin, histamine","Antibodies, antigen"]),
44: ("The lymphatic vessels of the body empty the lymph into blood stream at?", ["Abdominal vein","Jugular vein","Subclavian vein","Bile duct"]),
45: ("Flow of blood in the capillaries is adjusted by?", ["Heart directly","Pre-capillary sphincters","Meta-arteriole","Valves"]),
46: ("The pressure exerted by a solution separated by a semipermeable membrane from pure water is_________?", ["Osmotic Pressure","Soil potential","Solute Potential","Solvent potential"]),
47: ("Which of the following is NOT a consequence of anaerobic respiration in humans muscles cells?", ["Cramps","High consumption of energy","Pain","Tiredness"]),
48: ("The respiratory surfaces exhibit following characteristic?", ["It must be permeable","It must be thick for low diffusion","It should be non-vascularized","It should have low ventilation mechanism"]),
49: ("Which of the following is a prokaryote?", ["Protista","E.coli","Amoeba","Fungi"]),
50: ("Number of layers present in Gram-negative bacterial cell wall:", ["one","two","three","four"]),
51: ("The division of cocci in three planes form Sarcina, which is a cube of ------------- Cocci?", ["02","04","08","16"]),
52: ("Which of the following statement is correct?", ["Tuberculosis and Pneumonia are caused by Gram Positive Bacteria","Tuberculosis and Pneumonia are caused by Gram Negative Bacteria","Pneumonia is a lung disease caused by Gram Negative Bacteria","Tuberculosis is a lung disease caused by Gram Negative Bacteria"]),
53: ("Nitrifying bacteria are the examples of:", ["Heterotrophic bacteria","Chemosynthetic bacteria","Saprophytic bacteria","Parasitic bacteria"]),
54: ("Each human testis is divided into:", ["50-100 lobules","150-200 lobules","200-300 lobules","250-300 lobules"]),
55: ("Which cells in the human males are responsible for the release of testosterone?", ["Pituitary Gland","Hypothalamus","Sertoli cells","Leydig cells or interstitial cells"]),
56: ("Fertilized ovum is implanted and undergoes further development in the:", ["Ovary","Uterus","Oviduct","Cervix"]),
57: ("Level of luteinizing hormone (LH) is maximum in blood during which stage of menstrual cycle?", ["Menstrual stage","Proliferative stage","Ovulation stage","Secretory stage"]),
58: ("Major source of transmission of syphilis is:", ["Blood transfusion","Insect bite","Contaminated water","Sexual contact"]),
59: ("What is FALSE about cartilage?", ["There are many blood vessels in cartilage","It is a form of connective tissue","It covers ends of the bones at joints","It is much softer than bone"]),
60: ("Which of the following is a muscle component that act as store for energy?", ["ATP","Creatine-PO4","Myoglobin","Creatinine-PO4"]),
61: ("Which of the following is NOT found in skeletal muscle fibers in human?", ["Multiple nuclei","Multiple mitochondria","Large amount of myoglobin","Large amount of hemoglobin"]),
62: ("Hinge joint is present between which of the following bones?", ["Humerus and radio-ulna","Femur and pectoral girdle","Femur and acetabulum","Humerus and pectoral girdle"]),
63: ("Test cross is made to check the genotype of a trait. Which of the following crosses is a test cross?", ["Unknown x At","Unknown x tt","Unknown x AB","Unknown x TT"]),
64: ("What happens when a Rh -ve woman, married to a Rh +ve man conceives a child who is Rh +ve?", ["Maternal-foetal incompatibility","Paternal-foetal incompatibility","Cancer of fetus","Death of mother"]),
65: ("DNA stores biological information in discrete units termed as:", ["Genes","Phenotypes","Karyotypes","Cells"]),
66: ("To study sex linkages in Drosophila, Morgan mated white eyed males with wild type red eyed females. What will be the phenotype of offspring?", ["All red eyed males and females","Red eyed females and white eyed males","White eyed females and red eyed males","All white eyed females and males"]),
67: ("Which one of the following is X Linked Dominant disorder?", ["Haemophilia","Color blindness","Hypophosphatemic rickets","Hypertrichosis"]),
68: ("Mode of inheritance in humans can be traced through:", ["Experimental Mating","Chi Square Chart","Pedigree Analysis","Probability Analysis"]),

69: ("One a. m .u stands for", ["An atom of C - 12","1/12th of a carbon","1/12th of H","1 atom of all the elements"]),
70: ("A compound of sodium oxide has 74.2 % sodium and 25.8% of Oxygen. The empirical formula of the compound is?", ["NaO","NaO2","Na2O","Na2O2"]),
71: ("30 grams of 2-propanol were mixed with excess acidified K2Cr2O7 and boiled under reflux for 20 minutes. The organic product was then collected by distillation. The yield of product was 75.0%. What is the mass of product produced?", ["1.74g","21.75g","2.74g","29 g"]),
72: ("According to which scientist, the probability of finding an electron at a certain position is possible?", ["Bohr's","De-Broglie","Hund's","Schrodinger"]),
73: ("Which gas in the discharge tube produces lightest canal ray particles?", ["Ar","He","H2","Ne"]),
74: ("Which element has the ground state electronic configuration of 1s2, 2s2, 2p6, 3s2, 3p6?", ["Ar","Cl","Na","S"]),
75: ("What is the proton (atomic number) of an element that has four unpaired electrons in its ground state?", ["6","14","22","26"]),
76: ("A gaseous mixture contains 9.6% NH3, 22.6% N2 and 67.8% H2 gases. If the total pressure is 50 atm, then the partial pressure of H2 is", ["67.8 x100 / 50","50 x 100 / 100","67.8 x 50 / 100","67.8 + 50 / 100"]),
77: ("If we want to raise the temperature of one mole of an ideal gas by one kelvin, we have to provide how much amount of energy?", ["0.0821 joules","8.314 dm3-atm","0.0821 kJ","0.0821 dm3-atm"]),
78: ("The process of heat flow between hotter and colder gases remains continued until all the molecules have equal", ["Average translational kinetic energy","Average rotational kinetic energy","Average translational potential energy","Average vibrational kinetic energy"]),
79: ("In liquid, with the change in dipole-dipole forces, there is a change in some physical properties. Select the property which is not affected by the strength of dipole-dipole forces?", ["boiling point","heat of vaporization","heat of sublimation","moles"]),
80: ("Which of the following factor does not affect the magnitude of vapor pressure?", ["amount of liquid","size of molecule","temperature of liquid","intermolecular forces"]),
81: ("A small building block which belongs to whole information about crystal structure is called?", ["Cell","Unit Cell","Crystal lattice","Crystal unit"]),
82: ("Which type of solid is called as atomic solid?", ["Covalent solids","Ionic solids","Metallic solids","Molecular solids"]),
83: ("The decrease in solubility of the salt in a solution that already contains an ion common to that salt is known as:", ["Le Chatelier's principle","Solubility Product","Common ion effect","Ksp"]),
84: ("The precipitation occurs if the ionic concentration is:", ["Less than ksp","More than ksp","Equal to ksp","Present in any amount"]),
85: ("One can estimate the direction in which equilibrium will shift with the help of:", ["Le Chatelier's principle","Law of mass action","Mess's law","Law of heat of formation"]),
86: ("What is the overall order of this rate equation? Rate =k[H2][NO2]^2", ["1","2","3","4"]),
87: ("The catalysis in which the catalyst and the reactants are in the same phase is known?", ["Heterogeneous catalyst","Homogeneous catalyst","Slow","Fast"]),
88: ("Born-Haber cycle is used to determine the Lattice energy of ionic compounds. It is the application of", ["Henry's law","Le - Chatlier's Principle","Hess's law","Common ion effect"]),
89: ("Which of the following term is state function?", ["freezing","decomposition","sublimation","enthalpy"]),
90: ("An electrochemical cell is based upon which reaction?", ["Acid-base reaction","Redox reaction","Nuclear reaction","Neutralization reaction"]),
91: ("In which of the following, oxygen shows fractional oxidation number?", ["OF2","Na2O2","KO2","Cl2O7"]),
92: ("Which of the following element has smaller size?", ["Na","K","Al","Li"]),
93: ("Among LiCl, BeCl2, NaCl, CsCl, the compounds with the greatest and the least ionic character respectively are:", ["LiCl and CsCl","NaCl and LiCl","CsCl and NaCl","CsCl and BeCl2"]),
94: ("Which statement describes the conversion of magnesium atoms to magnesium ions for ionic bond formation with chlorine?", ["The change is reduction, because there has been a gain of electrons","The change is oxidation, because there has been a loss of electrons","The change is reduction, because there has been a loss of electrons","The change is oxidation, because there has been a gain of electrons"]),
95: ("AB4 Type with no Lone Pairs geometry enables to form which shape of molecule?", ["Trigonal","Regular tetrahedron","Regular octahedron","Regular pyramidal"]),
96: ("Why dimer of Aluminum chloride is formed", ["Aluminum is electron rich","Aluminum is having lone pair of electron","Aluminum donates lone pair to form bridge","Aluminum forms coordinate bonds with chlorine to complete its octet"]),
97: ("Which group of the periodic table contain non-metals, metalloids and metals.", ["I B","VII A","IV A","VI A"]),
98: ("Which of the following sulfate compound is insoluble in water ?", ["BeSO4","BaSO4","MgSO4","CaSO4"]),
99: ("Which of the following complex show a tetrahedral geometry?", ["[Fe(CO)5]","[Cu(CN)4]-2","[Au(Cl)4]-","[Pt(NH3)4]+2"]),
100: ("In which pair one has all Unpaired d orbitals while other have all paired d orbitals ?", ["Cu and Zn","Cr and Fe","Cr and Zn","Mn and Co"]),
101: ("In which of the following functional groups, the carbon atom is sp hybridized?", ["-CHO","-COOH","-CN","-COOR"]),
102: ("The compounds containing R-SH functional group are known as:", ["Alcohols","Thio-alcohols","Thio-ether","Nitrile"]),
103: ("What is the number of isomers of a hydrocarbon having a molecular formula, C4H8?", ["2","3","4","5"]),
104: ("Alkylbenzene is formed when benzene is treated with an alkyl halide in the presence of anhydrous aluminum chloride. Identify the type of reaction.", ["Halogenation","Friedel-Crafts acylation reaction","Friedel-Crafts alkylation reaction","Sulphonation"]),
105: ("Three alternate single and double bonds in benzene are called?", ["Conjugate bonds","Coordinate covalent bonds","Fixed bonds","Ionic bonds"]),
106: ("Which of the following compound is more acidic?", ["Alkane","Alkene","Alkyne","Cycloalkane"]),
107: ("Consider the chlorination of methane, the attack of chlorine free radical on methane form methyl free radical occurs in ?", ["Initiation step","Propagation step","Termination step","Last step"]),
108: ("The ratio of sigma to pi electrons in benzene is?", ["1:3","3:1","4:1","1:4"]),
109: ("When halogen is removed from an alkyl halide a carbocation is formed, identify the most reactive carbocation", ["Primary carbocation","Secondary carbocation","Tertiary carbocation","Methyl carbocation"]),
110: ("Freon is commonly known as ?", ["Refrigerant","A solvent","Insecticides","A fire extinguisher"]),
111: ("Neopentylchloride belongs to which class of alkyl halides?", ["Primary alkyl halides","Secondary alkyl halides","Tertiary alkyl halides","Quaternary alkyl halides"]),
112: ("What is the common name of 1,2,3-propanetriol?", ["Butyl alcohol","Glycol","Glycerol","Propyl alcohol"]),
113: ("Benzene is formed when Na reacts with which of the following?", ["Alcohol","Butyl alcohol","Propanol","Phenol"]),
114: ("When Phenol reacts with formaldehyde, which of the following product is produced?", ["Adduct","Hydronium ion","Oxonium ion","Phenoxide ion"]),
115: ("Which of the following is the correct name of CH3CH2CH2COCH2CHO?", ["3-oxo hexanal","3-one hexanal","3-oxo hexanol","3 keto hexanol"]),
116: ("Which is the most suitable reagent for the conversion of R-CH2OH -> RCHO?", ["KMnO4/NaOH","K2Cr2O7/H2SO4 (Conc.)","CrO3","Cr2O4/H2SO4 (Conc.)"]),
117: ("Which of the following is also called silver mirror test?", ["Benedict's solution test","Fehling's solution test","Iodoform test","Tollen's reagent test"]),
118: ("Which among the following have least pH?", ["CH3CH2COOH","CH2ClCH2COOH","CH3CHCl2 COOH","CH3CH2CH2COOH"]),
119: ("If carboxylic acid and ketone groups C=O are present in a chain then final name will be given as", ["oxo, oic acid","one, oic acid","Both 1 and 2","None of these"]),
120: ("When carboxylic acids and dicarboxylic acids have similar molecular weights, how do their melting points compare?", ["Carboxylic acids have greater melting points","Dicarboxylic acids have greater melting points","Both acids have similar melting points","No any consistent trends exits"]),
121: ("When food reaches stomach, the action of which of the following come to an end due to acidic PH?", ["Lipases","Amylase","Maltase","Hydrolases"]),
122: ("Which of the following proteins acts as carrier of copper in blood plasma?", ["Hemoglobin","Glycoprotein","Ceruloplasmin","Histone"]),

123: ("What is the shape of velocity-time graph for constant acceleration?", ["Parabola line","Straight line","Incline curve","Decline curve"]),
124: ("Which of the following is the correct definition of variable velocity?", ["Unequal distances are covered in equal intervals of time","Equal displacements are made in unequal intervals of time","Unequal displacements are made in equal intervals of time","Equal displacements are made in equal intervals of time"]),
125: ("A stone thrown horizontally from the top of a tall building follows a path that is:", ["Circular","Made of two straight line segments","Hyperbolic","Parabolic"]),
126: ("Which of the following is incorrect?", ["Reaction force on a body is always balanced by the action force","Reaction and action forces are always equal","Action and reaction forces never act on the same body","Newton's Third Law is always valid in all situations"]),
127: ("A fireman wants to slide down a rope. The breaking load of the rope is 3/4 th of the weight of the man. With what acceleration should the fire man slide down? ( Acceleration due to gravity is 'g')", ["g","g/4","3g/4","0"]),
128: ("When a heavy coin falls a short distance towards the ground it does not reach terminal velocity. Why is this so?", ["The coin has not hit the ground","The weight of coin is equal to air resistance","The weight of coin increases as air resistance increases","The weight of coin is more than air resistance"]),
129: ("The consumption of energy by a 60 W bulb in 2 s is:", ["120 J","60 J","30 J","0.02 J"]),
130: ("A long spring, when stretched by a distance x, has potential energy V. On increasing the stretching to nx, the potential energy of the spring will be:", ["nV","V/n","n^2 V","V/n^2"]),
131: ("Ignoring details associated with friction, extra forces exerted by arm and leg muscles, and other factors, we can consider a pole vault as the conversion of an athlete's running kinetic energy to gravitational potential energy. If an athlete is to lift his body 5 m during a vault, what speed must he have when he plants his pole?", ["5 m/s","10 m/s","15 m/s","20 m/s"]),
132: ("A particle of mass m at rest is acted upon by a force P for time t. Its kinetic energy after time t is:", ["(P^2 t^2)/m","(P^2 t^2)/2m","(P^2 t^2)/3m","(P^2 t^2)/4m"]),
133: ("The number of revolutions in 3(pi) radians is:", ["1/60","3/2","2","6"]),
134: ("If a flywheel is rotating at 3.0 rad/s, the time it takes to complete one revolution is about", ["0.67 s","1.0 s","1.3 s","2.1 s"]),
135: ("A fighter plane is moving in a vertical circle of radius r. Its minimum velocity at the highest point of the circle will be ?", ["sqrt(3gr)","sqrt(2gr)","sqrt(gr)","sqrt(gr/2)"]),
136: ("Which of the following increase by increasing amplitude?", ["Wavelength","Frequently","Zero","Loudness"]),
137: ("An airplane travels at a speed of 0.5v where v is the speed of sound. The airplane approaches a stationary observer. The frequency of sound emitted by the aircraft is 200 Hz. Which frequency does the observer hear?", ["400 HZ","100 Hz","120 Hz","180 Hz"]),
138: ("If the wavelength of light coming from a galaxy shifts towards the red end of spectrum, then galaxy is:", ["Approaching Earth","Receding the Earth","Stationary","Approaching Earth or is stationary"]),
139: ("The shortest distance between any two points in phase on a wave is called:", ["Displacement","Amplitude","Wavelength","Frequency"]),
140: ("When will the oscillations stop in the absence of resistive forces?", ["Never","After 10 minutes","In 10 minutes","Immediately"]),
141: ("The mechanical waves are not generated by:", ["Electric and magnetic fields","Coil of springs","Ropes","Water"]),
142: ("Reducing mass M of a suspending body to one fourth will change the frequency of oscillation to:", ["One fourth","Double","Quardruple","Half"]),
143: ("A distant star is receding from the Earth with a speed of 1.40 x 10^7 m/s. It emits light of frequency 4.57 x 10^14 Hz. The speed of light is 3.0 x 10^8 m/s. The Doppler effect formula can be used with light waves. What will be the frequency of this light when detected on Earth?", ["2.04 x 10^13 Hz","4.37 x 10^14 Hz","4.57 x 10^14 Hz","4.79 x 10^14 Hz"]),
144: ("Thermodynamics is that branch of Physics in which we study", ["relations between heat and mechanical energies","relations between heat and ionization energies","relations between chemical and mechanical energies","relations between kinetic and potential energies"]),
145: ("When a gas is compressed isothermally, the product of its pressure and volume during the process is:", ["not constant","constant","zero","proportional to entropy"]),
146: ("Temperature of given mass of a gas is changed from 150 C to 300 C during an isobaric process, volume of the gas will become:", ["Half","Double","Remain same","Less than double"]),
147: ("A capacitor is charged with a battery and energy stored is U. After disconnecting battery another capacitor of same capacity is connected in parallel to the first capacitor. Then energy stored in each capacitor is", ["U/2","U/4","4U","2U"]),
148: ("What is the potential difference between two points in an electric field if it takes 600 J of energy to move a charge of 2 C between these two points?", ["1200 J","800 J","300 J","0 J"]),
149: ("Gauss law cannot be used to find which of the following quantity?", ["Electric field intensity","Electric flux density","Charge","Permittivity"]),
150: ("Which one of the following statements is true?", ["electrostatic force obeys inverse square law while gravitational force does not","both gravitational force and electrostatic force are repulsive in nature","gravitational force is much weaker than electrostatic force","Both electrostatic force and gravitational force don't obey inverse square law"]),
151: ("The Coulomb's constant k depends upon:", ["nature of medium","system of units","types of charge","nature of medium and system of units"]),
152: ("A charged particle is moving in a uniform electric field. For the motion of the particle due to the field, which quantity has a constant non-zero value?", ["acceleration","displacement","rate of change of acceleration","velocity"]),
153: ("A capacitor of capacitance 'C' has a charge 'Q' and stored energy is 'w'. If the charge is increases to '2Q'. The stored energy will be:", ["2W","4W","W/4","W/2"]),
154: ("How much potential drop exist across closed switch?", ["0 V","1V","2V","3V"]),
155: ("A 3 V battery is connected in series with ammeter and 2 ohm resistance after short circuiting. What will be the reading of ammeter?", ["1 A","1.5 A","5 A","6 A"]),
156: ("The resistance of a conductor does not depend on which of the following?", ["area","resistivity","length","mass"]),
157: ("Which of the following statement is NOT CORRECT about Kirchhoff's rule?", ["Kirchhoff's current rule based upon the law of conservation of charge","Wheatstone bridge is an application of Kirchhoff's rule","Kirchhoff's rules are more suitable in AC circuits","Kirchhoff's voltage rule based upon the law of conservation of energy"]),
158: ("What do the substances whose resistance decreases with increase in temperature have?", ["high temperature coefficient","negative temperature coefficient","positive temperature coefficient","zero temperature coefficient"]),
159: ("A low voltage supply with an e.m.f. of 20 V and an internal resistance of 1.5 ohms is used to supply power to a heater of resistance 6.5 ohms in a fish tank. What is the power supplied to the water in the fish tank?", ["41 W","50 W","53 W","62 W"]),
160: ("Electric forces change the magnitude and direction of velocity while magnetic forces change_________ of velocity", ["Only Magnitude","Only direction","Magnitude and direction","Neither magnitude nor direction"]),
161: ("Which surface has greater magnetic flux in same magnetic field, each has an area 1 m^2.", ["Circular","Rectangular","Square","Flux is independent of shape"]),
162: ("The source of magnetic field is:", ["An isolated magnetic pole","Static electric charge","Nonmagnetic substance","Current loop"]),
163: ("One meter long copper rod is moving with speed 20 m/sec in the magnetic field of strength 0.6 tesla. What is the value of induced emf ?", ["10 v","12 v","14 v","16 v"]),
164: ("The unit of change in flux / change in time can be written as ?", ["NmA-2s-1","NmAs-1","NmA-1s-1","NmA-2s1"]),
165: ("Working principal of magnetic levitation train is according to ?", ["Faraday law","Max planks law","Ohm law","Lenz law"]),
166: ("A copper hoop is held in a vertical east-west plane in a uniform magnetic field whose field lines run along the north-south direction. The largest induced emf is produced when the hoop is ?", ["Rotated about a north-south axis","Rotated about an east-west axis","Moved rapidly, without rotation, toward the east","Moved rapidly, without rotation, toward the south"]),
167: ("In transformer, there is no _______ connection between the two coils but they are ______ linked ?", ["Magnetic, electrically","Electrical, magnetically","Magnetic, magnetically","Electrical, optically"]),
168: ("When the temperature of semiconductor suddenly drops to zero kelvin, then a semiconductor acts as:", ["Conductor","Semi-conductor","Super conductor","Insulator"]),
169: ("If electron, proton, neutron, and alpha particle have same velocity, which of them has the shortest wavelength?", ["Electron","Proton","Neutron","Alpha particle"]),
170: ("The process of ejection of loosely bound electrons from a certain photo sensitive surface by absorption of photon is called:", ["Compton effect","Photoelectric effect","Pair production","Black body radiation"]),
171: ("In a photoelectric effect experiment, the stopping potential is:", ["The kinetic energy of the most energetic electron ejected","The potential energy of the most energetic electron ejected","The photon energy","The electric potential that causes the electron current to vanish"]),
172: ("The line spectrum of hydrogen atom contains the spectral lines in the region of:", ["ultraviolet","infrared","visible","all of these"]),
173: ("The speed of electron in the first Bohr orbit is:", ["2.19 x 10^6 m/s","2.19 x 10^-6 m/s","2.19 x 10^4 m/s","2.19 x 10^-4 m/s"]),
174: ("A low energy neutron has RBE factor of 10. How much energy is absorbed by a man of mass 80 Kg if the value of equivalent dose is 400 rem?", ["16 J","32 J","48 J","64 J"]),
175: ("It has been observed that Thorium (Z=90, mass 234) is transformed into Protactinium (Z=91, mass 234) after the emission of ..................... particle:", ["Alpha","Beta","Gamma","Alpha, Beta, Gamma"]),
176: ("The half-life of Strontium (Sr) is 8.70 hours. Its decay constant is:", ["0.000022 s","45000 /s","0.000022 /s","0.000032 /s"]),

177: ("Synonym of the word \"Capricious\" is:", ["Fickle","Predictable","Uniform","Invariable"]),
178: ("Diseases like diabetes are supposed to be taken seriously or they can be ............. Which of the following words will fill in the blank most appropriately?", ["Cursing","Healthy","Fatal","Impersonating"]),
179: ("Choose the most appropriate antonym for \"abandonment\":", ["cessation","stoppage","halt","extension"]),
180: ("Fill in the blank with the correct word. The shepherd ploughed this mountain with cattle the first time it ....... ever ploughed.", ["was","was been","had","had been"]),
181: ("To give one some idea of Rabies' horrors, one ......... only read such descriptions as the following: spasms, restlessness, shudders at the least breath of air, an ardent thirst, convulsive movements, and fits of furious age.", ["needs","need","needed","has needed"]),
182: ("By 2030, people ................... been reading the works of Charles Dickens for more than 190 years.", ["had","will","have","will have"]),
183: ("Choose the most suitable/appropriate sentence out of the following:", ["Penny did not let me to get my book.","Penny was not leaving me to get my book.","Penny did not let me get my book.","Penny had not left me get my book."]),
184: ("Which one of the following is correct?", ["We visited, Istanbul, Turkey, and Kowloon, Hong Kong last summer.","We visited: Istanbul, Turkey, and Kowloon, Hong Kong last summer.","We visited Istanbul, Turkey, Kowloon, Hong Kong last summer.","We visited Istanbul, Turkey, and Kowloon, Hong Kong last summer."]),
185: ("Which of the following sentences is correct?", ["How could Sarah perswad her mum to stay out later?","How could Sarah persuade her mum to stay out later?","How could Sarah persuad her mum to stay out later?","How could Sarah parsuade her mum to stay out later?"]),
186: ("Choose the sentence with the correct use of article.", ["Natasha can play a piano and a violin.","Natasha can play the piano and the violin.","Natasha can play the piano and a violin.","Natasha can play piano and violin."]),
187: ("Distribute the handouts _________ the candidates. The correct preposition to be filled in is:", ["into","among","in","on"]),
188: ("Choose the correct sentence:", ["These scissors are very sharp","This scissors is very sharp","This scissor is very sharp","These scissor are very sharp"]),
189: ("Identify the sentence, out of the following, that is error free:", ["I do not enjoy being laughed at by other people","I did not enjoy laughing by other people","I am not enjoying laughing by other people","I do not enjoying being laughed at by other people"]),
190: ("Choose the sentence that is grammatically correct.", ["We agreed that the play was rather boring so we felt bored","We agreed that the play was rather bored so we felt boring","We agreed that the play was rather boring so we felt bore","We agreed that the play was rather bores so we felt bored"]),
}

# Raw answer key text as printed (columns of "Q Ans"), transcribed from the official UHS key
KEY_RAW = """
1 a 31 a 61 d 91 c 121 b 151 d 181 b
2 c 32 b 62 a 92 d 122 c 152 a 182 d
3 c 33 a 63 b 93 d 123 b 153 a 183 c
4 d 34 b 64 a 94 b 124 c 154 a 184 d
5 c 35 b 65 a 95 b 125 d 155 b 185 b
6 d 36 b 66 a 96 d 126 a 156 d 186 b
7 d 37 c 67 c 97 c 127 b 157 c 187 b
8 b 38 b 68 c 98 b 128 d 158 b 188 a
9 a 39 d 69 b 99 b 129 a 159 a 189 a
10 a 40 d 70 c 100 c 130 c 160 b 190 a
11 c 41 d 71 b 101 c 131 b 161 d 191 b
12 c 42 c 72 d 102 b 132 b 162 d 192 b
13 c 43 d 73 c 103 d 133 b 163 b 193 a
14 b 44 c 74 a 104 c 134 d 164 c 194 d
15 c 45 b 75 d 105 a 135 c 165 d 195 c
16 d 46 a 76 c 106 c 136 d 166 b 196 b
17 b 47 b 77 d 107 b 137 a 167 b 197 c
18 c 48 a 78 a 108 c 138 b 168 d 198 c
19 b 49 b 79 d 109 d 139 c 169 d 199 a
20 c 50 b 80 a 110 a 140 a 170 b 200 b
21 b 51 c 81 b 111 a 141 a 171 d
22 b 52 a 82 a 112 c 142 b 172 d
23 c 53 b 83 c 113 d 143 b 173 a
24 a 54 d 84 b 114 a 144 a 174 b
25 b 55 d 85 a 115 a 145 b 175 b
26 c 56 b 86 c 116 d 146 d 176 c
27 a 57 c 87 b 117 d 147 b 177 a
28 b 58 d 88 c 118 c 148 c 178 c
29 c 59 a 89 d 119 a 149 d 179 d
30 c 60 b 90 b 120 b 150 c 180 a
"""