"""
MDCAT Mock Test 10
==================
Full-length mock test: 180 MCQs
Weightage: Biology 81 | Chemistry 45 | Physics 36 | English 9 | Logical Reasoning 9
Difficulty mix (approx): 30% Easy / 50% Medium / 20% Hard, distributed throughout.

Includes 5 image/diagram-based questions (2 Biology, 1 Chemistry, 2 Physics).
Each such question has an "image" key giving a relative path to a PNG diagram
that must be viewed alongside the question (images/ subfolder, shipped alongside
this file). Diagrams: a maternal (mitochondrial) inheritance pedigree chart, a
labeled leaf cross-section, a reactant-concentration-vs-time kinetics graph, a
three-resistor series circuit, and a concave (diverging) lens ray diagram.

Each question is a dict:
    id, subject, topic, difficulty, question, [image], options (A-D), answer (correct letter)

Run this file directly to print a summary / sanity-check the paper.
"""

QUESTIONS = [
# ============================================================
# BIOLOGY (81 questions) - id 1-81
# ============================================================
{"id":1,"subject":'Biology',"topic":'Biomolecules',"difficulty":'Easy',
 "question":'Which of the following is a pentose sugar found in RNA?',
 "options":{"A":'Glucose', "B":'Fructose', "C":'Galactose', "D":'Ribose'},"answer":'D'},
{"id":2,"subject":'Biology',"topic":'Biomolecules',"difficulty":'Easy',
 "question":'The primary structural component of plant cell walls, made of repeating glucose units linked by beta-glycosidic bonds, is:',
 "options":{"A":'Starch', "B":'Glycogen', "C":'Cellulose', "D":'Chitin'},"answer":'C'},
{"id":3,"subject":'Biology',"topic":'Biomolecules',"difficulty":'Medium',
 "question":'A dipeptide is formed when two amino acids join via a peptide bond, releasing a molecule of:',
 "options":{"A":'Carbon dioxide', "B":'Water', "C":'Ammonia', "D":'Oxygen'},"answer":'B'},
{"id":4,"subject":'Biology',"topic":'Biomolecules',"difficulty":'Medium',
 "question":'Steroid hormones, such as testosterone and estrogen, are derived from which type of lipid?',
 "options":{"A":'Triglycerides', "B":'Phospholipids', "C":'Cholesterol', "D":'Waxes'},"answer":'C'},
{"id":5,"subject":'Biology',"topic":'Biomolecules',"difficulty":'Hard',
 "question":'Which of the following best describes the difference between fibrous and globular proteins?',
 "options":{"A":'Fibrous proteins are generally soluble and function as enzymes, while globular proteins are insoluble structural molecules', "B":'Fibrous proteins are typically elongated, insoluble, and structural (e.g., collagen), while globular proteins are compact, soluble, and often functional (e.g., enzymes)', "C":'There is no meaningful difference between the two categories', "D":'Globular proteins never possess a tertiary structure'},"answer":'B'},
{"id":6,"subject":'Biology',"topic":'Enzymes',"difficulty":'Easy',
 "question":'The optimum temperature of most human enzymes is approximately:',
 "options":{"A":'0 degrees C', "B":'100 degrees C', "C":'37 degrees C', "D":'60 degrees C'},"answer":'C'},
{"id":7,"subject":'Biology',"topic":'Enzymes',"difficulty":'Medium',
 "question":"A competitive inhibitor's effect on an enzyme reaction can typically be overcome by:",
 "options":{"A":'Increasing the substrate concentration', "B":'Lowering the temperature', "C":'Removing the enzyme entirely', "D":'Adding more inhibitor'},"answer":'A'},
{"id":8,"subject":'Biology',"topic":'Enzymes',"difficulty":'Medium',
 "question":'Zymogens (proenzymes), such as pepsinogen and trypsinogen, are secreted in an inactive form mainly to:',
 "options":{"A":'Increase reaction rate immediately upon secretion', "B":'Allow the enzyme to work at very high temperatures', "C":'Make the enzyme insoluble in water', "D":'Prevent the enzyme from digesting the tissues that produce it until it reaches its target location'},"answer":'D'},
{"id":9,"subject":'Biology',"topic":'Enzymes',"difficulty":'Hard',
 "question":'In a graph of enzyme activity versus pH for a mixed solution, two distinct activity peaks appear at different pH values. This most likely suggests:',
 "options":{"A":'A single enzyme with a very broad pH optimum', "B":'Enzyme denaturation occurring at both peaks', "C":'An experimental error, since enzymes can only have one peak', "D":'The presence of two different enzymes, each with its own distinct pH optimum'},"answer":'D'},
{"id":10,"subject":'Biology',"topic":'Cell Biology',"difficulty":'Easy',
 "question":'The rigid outer layer surrounding a plant cell, providing structural support, is the:',
 "options":{"A":'Plasma membrane', "B":'Nuclear envelope', "C":'Cell wall', "D":'Cytoskeleton'},"answer":'C'},
{"id":11,"subject":'Biology',"topic":'Cell Biology',"difficulty":'Easy',
 "question":"The organelle sometimes called the 'powerhouse of the cell' due to its role in ATP production is the:",
 "options":{"A":'Nucleus', "B":'Golgi apparatus', "C":'Ribosome', "D":'Mitochondrion'},"answer":'D'},
{"id":12,"subject":'Biology',"topic":'Cell Biology',"difficulty":'Medium',
 "question":'Which structure is responsible for organizing the genetic material into a compact form within the nucleus during cell division?',
 "options":{"A":'Nucleolus', "B":'Nuclear pore', "C":'Ribosome', "D":'Chromatin condensing into chromosomes'},"answer":'D'},
{"id":13,"subject":'Biology',"topic":'Cell Biology',"difficulty":'Medium',
 "question":'The main function of the smooth endoplasmic reticulum in a muscle cell is to:',
 "options":{"A":'Synthesize proteins destined for secretion', "B":'Store and release calcium ions, important for muscle contraction', "C":'Package proteins into vesicles', "D":"Replicate the cell's DNA"},"answer":'B'},
{"id":14,"subject":'Biology',"topic":'Cell Biology',"difficulty":'Medium',
 "question":'Which of the following best describes the role of the cell wall in bacteria?',
 "options":{"A":'It has no functional role in the cell', "B":'It replaces the need for a plasma membrane', "C":'It provides structural support and protection against osmotic lysis', "D":'It synthesizes ATP for the cell'},"answer":'C'},
{"id":15,"subject":'Biology',"topic":'Cell Biology',"difficulty":'Medium',
 "question":'A cell that actively secretes large amounts of protein (such as a pancreatic cell producing digestive enzymes) would be expected to have an especially well-developed:',
 "options":{"A":'Rough endoplasmic reticulum and Golgi apparatus', "B":'Cell wall', "C":'Chloroplast', "D":'Large central vacuole'},"answer":'A'},
{"id":16,"subject":'Biology',"topic":'Cell Biology',"difficulty":'Hard',
 "question":"Which of the following would most directly impair a cell's ability to correctly sort and target newly synthesized proteins to their proper destinations?",
 "options":{"A":'A defect in the cell wall', "B":'A defect in the vacuole of an animal cell', "C":'A defect in the centriole', "D":'A defect in the Golgi apparatus'},"answer":'D'},
{"id":17,"subject":'Biology',"topic":'Cell Membrane & Transport',"difficulty":'Easy',
 "question":'Water molecules move rapidly across a cell membrane primarily through channel proteins called:',
 "options":{"A":'Ion channels', "B":'Glucose carrier proteins', "C":'Sodium channels', "D":'Aquaporins'},"answer":'D'},
{"id":18,"subject":'Biology',"topic":'Cell Membrane & Transport',"difficulty":'Medium',
 "question":'A solution that causes a cell to lose water and shrink is described as:',
 "options":{"A":'Isotonic to the cell', "B":'Hypotonic to the cell', "C":'Hypertonic to the cell', "D":'Neutral to the cell'},"answer":'C'},
{"id":19,"subject":'Biology',"topic":'Cell Membrane & Transport',"difficulty":'Medium',
 "question":'Receptor-mediated endocytosis differs from general (bulk-phase) endocytosis mainly in that receptor-mediated endocytosis:',
 "options":{"A":'Involves specific receptor proteins binding target molecules before the membrane forms a vesicle around them', "B":'Requires no receptor proteins at all', "C":'Never forms a vesicle', "D":'Only removes water from the cell'},"answer":'A'},
{"id":20,"subject":'Biology',"topic":'Cell Membrane & Transport',"difficulty":'Hard',
 "question":"A cell membrane's permeability to a substance generally decreases as the substance's molecular size and polarity increase, mainly because:",
 "options":{"A":'All molecules pass through the membrane with equal ease', "B":"The phospholipid bilayer's hydrophobic interior resists the passage of large, polar molecules", "C":'The membrane has no lipid component at all', "D":'Polar molecules are always smaller than nonpolar ones'},"answer":'B'},
{"id":21,"subject":'Biology',"topic":'Cell Membrane & Transport',"difficulty":'Easy',
 "question":'Tight junctions between adjacent epithelial cells mainly function to:',
 "options":{"A":'Allow free movement of ions and molecules between the cells', "B":'Transport glucose into the cell', "C":'Prevent leakage of substances through the spaces between cells, creating a sealed barrier', "D":'Synthesize new membrane proteins'},"answer":'C'},
{"id":22,"subject":'Biology',"topic":'Cell Cycle & Division',"difficulty":'Easy',
 "question":'The longest phase of the cell cycle, during which the cell spends most of its time, is:',
 "options":{"A":'Mitosis', "B":'Cytokinesis', "C":'Telophase', "D":'Interphase'},"answer":'D'},
{"id":23,"subject":'Biology',"topic":'Cell Cycle & Division',"difficulty":'Easy',
 "question":'During which phase of mitosis do sister chromatids separate and begin moving to opposite poles of the cell?',
 "options":{"A":'Prophase', "B":'Metaphase', "C":'Anaphase', "D":'Telophase'},"answer":'C'},
{"id":24,"subject":'Biology',"topic":'Cell Cycle & Division',"difficulty":'Medium',
 "question":'The main biological purpose of meiosis, as opposed to mitosis, is to:',
 "options":{"A":'Produce haploid gametes with genetic variation for sexual reproduction', "B":'Produce genetically identical somatic cells for growth', "C":'Repair damaged tissue', "D":'Increase the total chromosome number of a cell'},"answer":'A'},
{"id":25,"subject":'Biology',"topic":'Cell Cycle & Division',"difficulty":'Medium',
 "question":'A diploid cell with 2n = 8 chromosomes undergoes meiosis. How many chromosomes will be present in each resulting gamete?',
 "options":{"A":'8', "B":'16', "C":'2', "D":'4'},"answer":'D'},
{"id":26,"subject":'Biology',"topic":'Cell Cycle & Division',"difficulty":'Hard',
 "question":'Apoptosis (programmed cell death) differs from necrosis mainly in that apoptosis:',
 "options":{"A":'Is an uncontrolled, traumatic form of cell death that damages surrounding tissue', "B":'Is a controlled, orderly process in which the cell is broken down and its contents are neatly removed without damaging neighboring cells', "C":'Never occurs in healthy organisms', "D":'Always results from an external physical injury'},"answer":'B'},
{"id":27,"subject":'Biology',"topic":'Cell Cycle & Division',"difficulty":'Medium',
 "question":'Errors during mitosis that result in daughter cells with an abnormal number of chromosomes are referred to as:',
 "options":{"A":'Aneuploidy, often caused by nondisjunction', "B":'Simple point mutation only', "C":'Polyploidy exclusively', "D":'Crossing over'},"answer":'A'},
{"id":28,"subject":'Biology',"topic":'Genetics',"difficulty":'Easy',
 "question":'A cross between two individuals heterozygous for a single trait (Aa x Aa) is expected to yield offspring with a phenotypic ratio of:',
 "options":{"A":'1:1', "B":'1:2:1', "C":'3:1', "D":'9:3:3:1'},"answer":'C'},
{"id":29,"subject":'Biology',"topic":'Genetics',"difficulty":'Medium',
 "question":'A father is heterozygous (Aa) for a trait, and the mother is homozygous recessive (aa). What fraction of their children is expected to show the dominant phenotype?',
 "options":{"A":'1/4', "B":'3/4', "C":'All of them', "D":'1/2'},"answer":'D'},
{"id":30,"subject":'Biology',"topic":'Genetics',"difficulty":'Medium',
 "question":'Cystic fibrosis is an autosomal recessive disorder. Two unaffected, carrier parents have several children. Based on Mendelian expectations, what proportion of their children is expected to be affected?',
 "options":{"A":'All of the children', "B":'None of the children', "C":'On average, about 1 in 4 children (25%)', "D":'Exactly half of the children'},"answer":'C'},
{"id":31,"subject":'Biology',"topic":'Genetics',"difficulty":'Hard',
 "question":'In a trihybrid cross AaBbCc x AaBbCc, assuming independent assortment, what fraction of the offspring is expected to be homozygous recessive for all three traits (aabbcc)?',
 "options":{"A":'1/16', "B":'1/64', "C":'1/32', "D":'1/8'},"answer":'B'},
{"id":32,"subject":'Biology',"topic":'Genetics',"difficulty":'Medium',
 "question":'A man with blood type B and a woman with blood type O have a child. Which blood type(s) could this child NOT have?',
 "options":{"A":'B or O', "B":'A or AB', "C":'O only', "D":'B only'},"answer":'B'},
{"id":33,"subject":'Biology',"topic":'Genetics',"difficulty":'Hard',
 "question":'The pedigree chart shows a trait passed from an affected mother to all of her children, both sons and daughters, in every generation, while affected fathers never pass on the trait. This pattern is most consistent with:',
 "image":'images/q_pedigree_mitochondrial.png',
 "options":{"A":'Autosomal dominant inheritance', "B":'X-linked recessive inheritance', "C":'Mitochondrial (maternal) inheritance', "D":'Y-linked inheritance'},"answer":'C'},
{"id":34,"subject":'Biology',"topic":'Genetics',"difficulty":'Medium',
 "question":"A rooster's comb shape is determined by one gene masking or altering the expression of a different gene at another locus. This phenomenon is called:",
 "options":{"A":'Epistasis', "B":'Codominance', "C":'Incomplete dominance', "D":'Pleiotropy'},"answer":'A'},
{"id":35,"subject":'Biology',"topic":'Molecular Biology',"difficulty":'Easy',
 "question":"Chargaff's rule states that in DNA, the amount of adenine equals the amount of:",
 "options":{"A":'Guanine', "B":'Cytosine', "C":'Uracil', "D":'Thymine'},"answer":'D'},
{"id":36,"subject":'Biology',"topic":'Molecular Biology',"difficulty":'Easy',
 "question":'The process of copying the information from a DNA template strand into a complementary mRNA strand is:',
 "options":{"A":'Translation', "B":'Transcription', "C":'Replication', "D":'Reverse transcription'},"answer":'B'},
{"id":37,"subject":'Biology',"topic":'Molecular Biology',"difficulty":'Medium',
 "question":'DNA polymerase proofreads newly synthesized DNA mainly to:',
 "options":{"A":'Remove incorrectly paired nucleotides, reducing the mutation rate', "B":'Speed up the overall rate of replication', "C":'Unwind the DNA double helix', "D":'Add RNA primers to the template'},"answer":'A'},
{"id":38,"subject":'Biology',"topic":'Molecular Biology',"difficulty":'Medium',
 "question":'A ribosome is composed of:',
 "options":{"A":'Only protein', "B":'A large and small subunit made of rRNA and protein', "C":'Only rRNA', "D":'Only DNA'},"answer":'B'},
{"id":39,"subject":'Biology',"topic":'Molecular Biology',"difficulty":'Medium',
 "question":'Which of the following mutations is generally considered most likely to have a severe effect on protein function?',
 "options":{"A":'A silent mutation', "B":'A mutation located in a non-coding intron', "C":'A synonymous codon change', "D":'A frameshift mutation caused by insertion or deletion of a non-multiple-of-three number of nucleotides'},"answer":'D'},
{"id":40,"subject":'Biology',"topic":'Molecular Biology',"difficulty":'Hard',
 "question":'A gene contains both exons and introns. During mRNA processing, which of these are removed before the mature mRNA leaves the nucleus?',
 "options":{"A":'Exons', "B":'Introns', "C":'Both exons and introns', "D":'Neither is removed'},"answer":'B'},
{"id":41,"subject":'Biology',"topic":'Molecular Biology',"difficulty":'Hard',
 "question":'The Shine-Dalgarno sequence in prokaryotic mRNA functions to:',
 "options":{"A":'Terminate translation at the ribosome', "B":'Code for the final amino acid of the protein', "C":'Signal the end of transcription', "D":'Help position the ribosome correctly at the start codon for translation initiation'},"answer":'D'},
{"id":42,"subject":'Biology',"topic":'Molecular Biology',"difficulty":'Medium',
 "question":'Which of the following correctly describes codon degeneracy in the genetic code?',
 "options":{"A":'Every amino acid is coded for by exactly one unique codon', "B":'The genetic code has no redundancy at all', "C":'Only start and stop codons show any redundancy', "D":'Most amino acids can be coded for by more than one codon, due to redundancy in the genetic code'},"answer":'D'},
{"id":43,"subject":'Biology',"topic":'Molecular Biology',"difficulty":'Medium',
 "question":'A gene mutation occurring in a somatic (body) cell rather than a germ (reproductive) cell:',
 "options":{"A":'Will always be passed on to offspring', "B":'Always causes cancer', "C":'Generally will not be passed on to offspring, since it does not affect the gametes', "D":'Has the same inheritance pattern as a germline mutation'},"answer":'C'},
{"id":44,"subject":'Biology',"topic":'Molecular Biology',"difficulty":'Easy',
 "question":'The mRNA synthesized from a DNA template strand is:',
 "options":{"A":'Identical in sequence to the coding (sense) DNA strand, with uracil replacing thymine', "B":'Identical in sequence to the template strand', "C":'Unrelated to either DNA strand', "D":'Always shorter than the gene that codes for it, with no exceptions'},"answer":'A'},
{"id":45,"subject":'Biology',"topic":'Evolution',"difficulty":'Easy',
 "question":'Fossils provide evidence for evolution mainly by showing:',
 "options":{"A":'That species have never changed over time', "B":'That all organisms appeared simultaneously', "C":'That only extinct species existed in the past', "D":'A chronological record of how species have changed and diversified over time'},"answer":'D'},
{"id":46,"subject":'Biology',"topic":'Evolution',"difficulty":'Medium',
 "question":'Artificial selection, as practiced by breeders of domesticated animals and crops, differs from natural selection mainly in that artificial selection:',
 "options":{"A":'Occurs entirely without any human involvement', "B":'Involves humans intentionally choosing which individuals reproduce, based on desired traits', "C":'Always results in a worse-adapted organism', "D":'Cannot produce any observable change in a population'},"answer":'B'},
{"id":47,"subject":'Biology',"topic":'Evolution',"difficulty":'Medium',
 "question":'Which of the following is the best example of stabilizing selection acting on a population?',
 "options":{"A":'Both extreme phenotypes are favored over the intermediate phenotype', "B":'The intermediate (average) phenotype is favored, reducing variation, such as stabilizing human birth weight near an optimal average', "C":'Only one extreme phenotype is consistently favored, shifting the population average', "D":'All phenotypes are equally favored regardless of how extreme they are'},"answer":'B'},
{"id":48,"subject":'Biology',"topic":'Evolution',"difficulty":'Hard',
 "question":'In a population at Hardy-Weinberg equilibrium, the frequency of the homozygous recessive genotype is 0.09. What is the expected frequency of the heterozygous genotype?',
 "options":{"A":'0.09', "B":'0.49', "C":'0.42', "D":'0.30'},"answer":'C'},
{"id":49,"subject":'Biology',"topic":'Classification & Diversity',"difficulty":'Easy',
 "question":'The scientific study of naming, describing, and classifying organisms is called:',
 "options":{"A":'Ecology', "B":'Taxonomy', "C":'Genetics', "D":'Physiology'},"answer":'B'},
{"id":50,"subject":'Biology',"topic":'Classification & Diversity',"difficulty":'Easy',
 "question":'Members of kingdom Protista are most accurately described as:',
 "options":{"A":'Exclusively multicellular, complex organisms', "B":'Prokaryotic cells without a nucleus', "C":'A diverse group of mostly unicellular eukaryotes that do not fit neatly into the plant, animal, or fungal kingdoms', "D":'Non-living infectious particles'},"answer":'C'},
{"id":51,"subject":'Biology',"topic":'Classification & Diversity',"difficulty":'Medium',
 "question":'A virus is generally not considered a living organism by most biologists mainly because it:',
 "options":{"A":'Contains genetic material', "B":'Can infect other organisms', "C":'Cannot carry out independent metabolism or reproduce without a host cell', "D":'Has a protein coat surrounding it'},"answer":'C'},
{"id":52,"subject":'Biology',"topic":'Classification & Diversity',"difficulty":'Medium',
 "question":'Which characteristic is used to place an organism into phylum Porifera (sponges)?',
 "options":{"A":'A segmented body with jointed appendages', "B":'Radial symmetry with stinging cells', "C":'A notochord present at some stage of life', "D":'A body composed of a loose aggregation of cells around water-filled pores and chambers, lacking true tissues'},"answer":'D'},
{"id":53,"subject":'Biology',"topic":'Classification & Diversity',"difficulty":'Easy',
 "question":'Which taxonomic rank is the most specific, representing a group of organisms capable of interbreeding?',
 "options":{"A":'Genus', "B":'Species', "C":'Family', "D":'Order'},"answer":'B'},
{"id":54,"subject":'Biology',"topic":'Classification & Diversity',"difficulty":'Medium',
 "question":'Members of class Insecta (phylum Arthropoda) are characterized by having:',
 "options":{"A":'Eight legs and two body segments', "B":'A soft, completely unsegmented body', "C":'Six legs and typically three body segments (head, thorax, abdomen)', "D":'A water vascular system'},"answer":'C'},
{"id":55,"subject":'Biology',"topic":'Plant Biology',"difficulty":'Easy',
 "question":'The tissue in plants responsible for primary growth in length, found at root and shoot tips, is:',
 "options":{"A":'Vascular cambium', "B":'Cork cambium', "C":'Ground tissue', "D":'Apical meristem'},"answer":'D'},
{"id":56,"subject":'Biology',"topic":'Plant Biology',"difficulty":'Medium',
 "question":'The diagram shows a cross-section of a leaf with four structures labeled 1-4: upper epidermis, palisade mesophyll, spongy mesophyll, and lower epidermis with stomata. Which labeled structure is the primary site of photosynthesis, due to its high density of tightly packed chloroplasts?',
 "image":'images/q_leaf_crosssection_diagram.png',
 "options":{"A":'Structure 1 (upper epidermis)', "B":'Structure 3 (spongy mesophyll)', "C":'Structure 4 (lower epidermis)', "D":'Structure 2 (palisade mesophyll)'},"answer":'D'},
{"id":57,"subject":'Biology',"topic":'Plant Biology',"difficulty":'Medium',
 "question":'Which pigment, in addition to chlorophyll, helps capture light energy and gives autumn leaves their orange and yellow colors as chlorophyll breaks down?',
 "options":{"A":'Carotenoid', "B":'Anthocyanin', "C":'Melanin', "D":'Hemoglobin'},"answer":'A'},
{"id":58,"subject":'Biology',"topic":'Plant Biology',"difficulty":'Hard',
 "question":'A key difference between primary growth and secondary growth in plants is that secondary growth:',
 "options":{"A":'Occurs only at root and shoot tips, increasing length', "B":'Occurs only in monocot plants', "C":'Has no relation to the vascular cambium', "D":'Increases the girth (thickness) of stems and roots via the vascular cambium and cork cambium'},"answer":'D'},
{"id":59,"subject":'Biology',"topic":'Plant Biology',"difficulty":'Medium',
 "question":'Which plant hormone is primarily responsible for promoting fruit ripening?',
 "options":{"A":'Ethylene', "B":'Auxin', "C":'Gibberellin', "D":'Cytokinin'},"answer":'A'},
{"id":60,"subject":'Biology',"topic":'Plant Biology',"difficulty":'Easy',
 "question":'The transfer of pollen from the anther to the stigma of a flower is called:',
 "options":{"A":'Germination', "B":'Fertilization', "C":'Pollination', "D":'Dispersal'},"answer":'C'},
{"id":61,"subject":'Biology',"topic":'Human Physiology - Digestion',"difficulty":'Easy',
 "question":'The first organ where mechanical digestion of food occurs through chewing is the:',
 "options":{"A":'Mouth', "B":'Stomach', "C":'Esophagus', "D":'Small intestine'},"answer":'A'},
{"id":62,"subject":'Biology',"topic":'Human Physiology - Digestion',"difficulty":'Medium',
 "question":'The primary role of the liver in digestion is to:',
 "options":{"A":'Secrete digestive enzymes directly into the stomach', "B":'Produce bile, which emulsifies fats for easier digestion', "C":'Absorb nutrients directly into the bloodstream', "D":'Store undigested food'},"answer":'B'},
{"id":63,"subject":'Biology',"topic":'Human Physiology - Digestion',"difficulty":'Medium',
 "question":'Nutrient absorption in the small intestine is greatly enhanced by finger-like projections called:',
 "options":{"A":'Villi', "B":'Rugae', "C":'Alveoli', "D":'Cilia alone'},"answer":'A'},
{"id":64,"subject":'Biology',"topic":'Human Physiology - Digestion',"difficulty":'Hard',
 "question":'A person who has had a large portion of their small intestine surgically removed would most likely experience:',
 "options":{"A":'Improved nutrient absorption', "B":'Reduced nutrient absorption, due to loss of absorptive surface area', "C":'No change in digestion at all', "D":'Increased production of bile'},"answer":'B'},
{"id":65,"subject":'Biology',"topic":'Human Physiology - Circulation',"difficulty":'Easy',
 "question":'The largest artery in the human body, which carries oxygenated blood away from the left ventricle, is the:',
 "options":{"A":'Vena cava', "B":'Pulmonary artery', "C":'Aorta', "D":'Coronary artery'},"answer":'C'},
{"id":66,"subject":'Biology',"topic":'Human Physiology - Circulation',"difficulty":'Medium',
 "question":'Coronary arteries primarily function to:',
 "options":{"A":'Carry blood from the heart to the lungs', "B":'Supply oxygenated blood to the heart muscle itself', "C":'Carry deoxygenated blood to the body', "D":'Drain blood from the brain'},"answer":'B'},
{"id":67,"subject":'Biology',"topic":'Human Physiology - Circulation',"difficulty":'Medium',
 "question":'Which blood component is primarily responsible for carrying oxygen throughout the body?',
 "options":{"A":'Plasma', "B":'Red blood cells (via hemoglobin)', "C":'White blood cells', "D":'Platelets'},"answer":'B'},
{"id":68,"subject":'Biology',"topic":'Human Physiology - Circulation',"difficulty":'Hard',
 "question":'Varicose veins commonly develop mainly due to:',
 "options":{"A":'Overly strong valves that prevent any blood flow', "B":'Excessive arterial pressure', "C":'Weakened or damaged valves in veins, allowing blood to pool and vessels to become enlarged', "D":'A lack of red blood cells'},"answer":'C'},
{"id":69,"subject":'Biology',"topic":'Human Physiology - Respiration',"difficulty":'Easy',
 "question":'The windpipe, which carries air from the throat to the bronchi, is called the:',
 "options":{"A":'Esophagus', "B":'Larynx', "C":'Trachea', "D":'Pharynx'},"answer":'C'},
{"id":70,"subject":'Biology',"topic":'Human Physiology - Respiration',"difficulty":'Medium',
 "question":'Tidal volume refers to:',
 "options":{"A":'The maximum volume of air the lungs can hold', "B":'The volume of air inhaled or exhaled during a normal, quiet breath', "C":'The volume of air that can never be expelled from the lungs', "D":'The rate of breathing'},"answer":'B'},
{"id":71,"subject":'Biology',"topic":'Human Physiology - Respiration',"difficulty":'Medium',
 "question":'Which of the following best explains why the lungs do not collapse under normal circumstances despite their natural elastic recoil?',
 "options":{"A":'Negative pressure in the pleural cavity holds the lungs against the chest wall', "B":'The lungs are filled entirely with muscle tissue', "C":'The diaphragm physically holds the lungs open', "D":'The trachea prevents the lungs from collapsing'},"answer":'A'},
{"id":72,"subject":'Biology',"topic":'Human Physiology - Excretion',"difficulty":'Easy',
 "question":'The outer, protective layer of the kidney is called the:',
 "options":{"A":'Renal medulla', "B":'Renal pelvis', "C":'Ureter', "D":'Renal cortex'},"answer":'D'},
{"id":73,"subject":'Biology',"topic":'Human Physiology - Excretion',"difficulty":'Medium',
 "question":'Filtration in the nephron is driven mainly by:',
 "options":{"A":"Blood pressure forcing fluid out of the glomerular capillaries into Bowman's capsule", "B":'Active transport requiring ATP', "C":'Osmosis alone', "D":'Muscular contraction of the nephron itself'},"answer":'A'},
{"id":74,"subject":'Biology',"topic":'Human Physiology - Excretion',"difficulty":'Hard',
 "question":'Dialysis is used to treat kidney failure mainly by:',
 "options":{"A":'Surgically repairing damaged nephrons', "B":'Stimulating the kidneys to regenerate instantly', "C":'Artificially filtering waste products and excess fluid from the blood, mimicking kidney function', "D":'Replacing the need for the liver'},"answer":'C'},
{"id":75,"subject":'Biology',"topic":'Human Physiology - Nervous & Endocrine',"difficulty":'Easy',
 "question":'The part of the neuron that carries electrical impulses away from the cell body toward other neurons is the:',
 "options":{"A":'Dendrite', "B":'Axon', "C":'Cell body (soma)', "D":'Synapse'},"answer":'B'},
{"id":76,"subject":'Biology',"topic":'Human Physiology - Nervous & Endocrine',"difficulty":'Medium',
 "question":'The knee-jerk reflex is an example of a:',
 "options":{"A":'Voluntary, learned response', "B":'Response requiring extensive brain processing', "C":'Simple reflex arc, mediated by the spinal cord without requiring conscious brain involvement', "D":'Hormonal response'},"answer":'C'},
{"id":77,"subject":'Biology',"topic":'Human Physiology - Nervous & Endocrine',"difficulty":'Medium',
 "question":'Growth hormone (GH), secreted by the anterior pituitary, primarily stimulates:',
 "options":{"A":'Blood glucose regulation directly', "B":'Water reabsorption in the kidney', "C":'Milk production in the mammary glands', "D":'Growth of bones and tissues throughout the body, especially during childhood'},"answer":'D'},
{"id":78,"subject":'Biology',"topic":'Human Physiology - Nervous & Endocrine',"difficulty":'Hard',
 "question":'A person with damage to their hypothalamus might experience disruptions in:',
 "options":{"A":'Vision only', "B":'Hearing only', "C":'Regulation of body temperature, hunger, thirst, and hormone release via the pituitary', "D":'Skeletal muscle contraction exclusively'},"answer":'C'},
{"id":79,"subject":'Biology',"topic":'Human Physiology - Reproduction',"difficulty":'Easy',
 "question":'The hormone primarily responsible for stimulating uterine contractions during childbirth is:',
 "options":{"A":'Estrogen', "B":'Oxytocin', "C":'Progesterone', "D":'FSH'},"answer":'B'},
{"id":80,"subject":'Biology',"topic":'Human Physiology - Reproduction',"difficulty":'Medium',
 "question":'Menopause in women is primarily characterized by:',
 "options":{"A":'An increase in fertility', "B":'An increase in estrogen production', "C":'The cessation of ovulation and menstrual cycles due to declining ovarian function', "D":'The onset of puberty'},"answer":'C'},
{"id":81,"subject":'Biology',"topic":'Ecology',"difficulty":'Medium',
 "question":'A symbiotic relationship in which one organism benefits and the other is neither helped nor harmed is called:',
 "options":{"A":'Commensalism', "B":'Mutualism', "C":'Parasitism', "D":'Competition'},"answer":'A'},

# ============================================================
# CHEMISTRY (45 questions) - id 82-126
# ============================================================
{"id":82,"subject":'Chemistry',"topic":'Atomic Structure',"difficulty":'Easy',
 "question":"An atom's mass number is the sum of its number of protons and:",
 "options":{"A":'Electrons', "B":'Neutrons', "C":'Isotopes', "D":'Ions'},"answer":'B'},
{"id":83,"subject":'Chemistry',"topic":'Atomic Structure',"difficulty":'Medium',
 "question":'An atom of nitrogen-14 (atomic number 7) contains how many neutrons?',
 "options":{"A":'14', "B":'21', "C":'2', "D":'7'},"answer":'D'},
{"id":84,"subject":'Chemistry',"topic":'Atomic Structure',"difficulty":'Medium',
 "question":'The electron configuration of a neutral chlorine atom (Z = 17) is:',
 "options":{"A":'1s2 2s2 2p5 3s2 3p6', "B":'1s2 2s2 2p6 3s2 3p5', "C":'1s2 2s2 2p6 3s2 3p6', "D":'1s2 2s2 2p6 3s1 3p6'},"answer":'B'},
{"id":85,"subject":'Chemistry',"topic":'Atomic Structure',"difficulty":'Hard',
 "question":'An ion has 20 protons and 18 electrons. What is its charge?',
 "options":{"A":'-2', "B":'+2', "C":'+18', "D":'-18'},"answer":'B'},
{"id":86,"subject":'Chemistry',"topic":'Periodic Table',"difficulty":'Easy',
 "question":'The modern periodic table arranges elements primarily by increasing:',
 "options":{"A":'Atomic mass', "B":'Number of neutrons', "C":'Melting point', "D":'Atomic number'},"answer":'D'},
{"id":87,"subject":'Chemistry',"topic":'Periodic Table',"difficulty":'Medium',
 "question":'Which trend correctly describes the change in metallic character within the periodic table?',
 "options":{"A":'Decreases across a period and increases down a group', "B":'Increases across a period and decreases down a group', "C":'Remains constant throughout the periodic table', "D":'Decreases in both directions'},"answer":'A'},
{"id":88,"subject":'Chemistry',"topic":'Periodic Table',"difficulty":'Medium',
 "question":'Which of the following elements is expected to have the largest atomic radius?',
 "options":{"A":'Potassium', "B":'Lithium', "C":'Sodium', "D":'Hydrogen'},"answer":'A'},
{"id":89,"subject":'Chemistry',"topic":'Chemical Bonding',"difficulty":'Easy',
 "question":'A nonpolar covalent bond forms when two atoms:',
 "options":{"A":'Share electrons equally, typically between identical or very similar atoms', "B":'Have very different electronegativities', "C":'Transfer electrons completely from one atom to another', "D":'Form an ionic crystal lattice'},"answer":'A'},
{"id":90,"subject":'Chemistry',"topic":'Chemical Bonding',"difficulty":'Medium',
 "question":'According to VSEPR theory, a molecule with five bonding pairs and no lone pairs on the central atom (e.g., PCl5) has a molecular shape described as:',
 "options":{"A":'Octahedral', "B":'Square pyramidal', "C":'Trigonal bipyramidal', "D":'Tetrahedral'},"answer":'C'},
{"id":91,"subject":'Chemistry',"topic":'Chemical Bonding',"difficulty":'Medium',
 "question":'Which of the following best explains why ice floats on liquid water?',
 "options":{"A":'Hydrogen bonding in ice creates an open, less dense crystalline structure compared to liquid water', "B":'Ice is denser than liquid water', "C":'Ice contains trapped air bubbles that make it float', "D":'Water becomes lighter as it freezes due to loss of mass'},"answer":'A'},
{"id":92,"subject":'Chemistry',"topic":'Chemical Bonding',"difficulty":'Hard',
 "question":'Metals are good conductors of electricity mainly because they contain:',
 "options":{"A":'Fixed, immobile electrons', "B":"A 'sea' of delocalized electrons that can move freely throughout the metal lattice", "C":'No free electrons whatsoever', "D":'Only covalent bonds between atoms'},"answer":'B'},
{"id":93,"subject":'Chemistry',"topic":'States of Matter',"difficulty":'Easy',
 "question":'The process by which a solid changes directly into a gas is called:',
 "options":{"A":'Melting', "B":'Condensation', "C":'Deposition', "D":'Sublimation'},"answer":'D'},
{"id":94,"subject":'Chemistry',"topic":'States of Matter',"difficulty":'Medium',
 "question":'A gas occupies 8.0 L at a pressure of 1.5 atm. What volume will it occupy at 3.0 atm, assuming constant temperature?',
 "options":{"A":'16.0 L', "B":'12.0 L', "C":'4.0 L', "D":'2.0 L'},"answer":'C'},
{"id":95,"subject":'Chemistry',"topic":'States of Matter',"difficulty":'Hard',
 "question":'A sample of gas at 2 atm and 400 K has a volume of 5 L. What would be its volume at 1 atm and 200 K?',
 "options":{"A":'5 L', "B":'10 L', "C":'2.5 L', "D":'20 L'},"answer":'A'},
{"id":96,"subject":'Chemistry',"topic":'Stoichiometry',"difficulty":'Easy',
 "question":'The volume occupied by one mole of any ideal gas at STP is approximately:',
 "options":{"A":'22.4 L', "B":'1 L', "C":'44.8 L', "D":'6.02 L'},"answer":'A'},
{"id":97,"subject":'Chemistry',"topic":'Stoichiometry',"difficulty":'Medium',
 "question":'How many moles of oxygen atoms are present in 1 mole of Al2O3?',
 "options":{"A":'1', "B":'2', "C":'5', "D":'3'},"answer":'D'},
{"id":98,"subject":'Chemistry',"topic":'Stoichiometry',"difficulty":'Hard',
 "question":'A 400 mL solution contains 0.2 mole of sucrose. What is the molarity of the solution?',
 "options":{"A":'0.2 M', "B":'0.8 M', "C":'0.5 M', "D":'2.0 M'},"answer":'C'},
{"id":99,"subject":'Chemistry',"topic":'Stoichiometry',"difficulty":'Medium',
 "question":'In the reaction 2C4H10 + 13O2 -> 8CO2 + 10H2O, how many moles of CO2 are produced from 1 mole of butane (C4H10) reacting completely with excess O2?',
 "options":{"A":'2', "B":'8', "C":'13', "D":'4'},"answer":'D'},
{"id":100,"subject":'Chemistry',"topic":'Thermochemistry',"difficulty":'Easy',
 "question":'The energy stored within the chemical bonds of a substance is referred to as its:',
 "options":{"A":'Kinetic energy', "B":'Thermal energy alone', "C":'Chemical potential energy', "D":'Nuclear energy'},"answer":'C'},
{"id":101,"subject":'Chemistry',"topic":'Thermochemistry',"difficulty":'Medium',
 "question":'If the enthalpy of the products of a reaction is lower than that of the reactants, the reaction is:',
 "options":{"A":'Endothermic', "B":'At equilibrium by definition', "C":'Exothermic', "D":'Necessarily non-spontaneous'},"answer":'C'},
{"id":102,"subject":'Chemistry',"topic":'Chemical Equilibrium',"difficulty":'Medium',
 "question":'For the reaction 2NO(g) + O2(g) <-> 2NO2(g), adding more O2 gas to the system at equilibrium will shift the equilibrium:',
 "options":{"A":'Toward the product, NO2, consuming some of the added O2', "B":'Toward the reactants', "C":'Not at all, since gas addition has no effect', "D":'Completely to the reactant side'},"answer":'A'},
{"id":103,"subject":'Chemistry',"topic":'Chemical Equilibrium',"difficulty":'Hard',
 "question":'A large value of the equilibrium constant, Keq, for a reaction indicates that at equilibrium:',
 "options":{"A":'The reaction strongly favors the reactants', "B":'The reaction strongly favors the products', "C":'The reaction has not yet started', "D":'No reaction occurs at all'},"answer":'B'},
{"id":104,"subject":'Chemistry',"topic":'Reaction Kinetics',"difficulty":'Easy',
 "question":'Which of the following factors does NOT generally affect the rate of a chemical reaction?',
 "options":{"A":'The color of the reaction vessel', "B":'Temperature', "C":'Concentration of reactants', "D":'Presence of a catalyst'},"answer":'A'},
{"id":105,"subject":'Chemistry',"topic":'Reaction Kinetics',"difficulty":'Medium',
 "question":'The graph shows reactant concentration plotted against time for a chemical reaction. Based on the graph, the initial rate of reaction (early in the reaction) is best represented by:',
 "image":'images/q_concentration_vs_time_graph.png',
 "options":{"A":'The slope (steepness) of the curve at the start, which is steepest early in the reaction', "B":'The y-intercept of the graph', "C":'The x-intercept of the graph', "D":'The total area under the entire curve'},"answer":'A'},
{"id":106,"subject":'Chemistry',"topic":'Electrochemistry',"difficulty":'Medium',
 "question":'The standard hydrogen electrode is assigned a standard reduction potential of exactly:',
 "options":{"A":'+1.00 V', "B":'0.00 V', "C":'-1.00 V', "D":'+2.00 V'},"answer":'B'},
{"id":107,"subject":'Chemistry',"topic":'Electrochemistry',"difficulty":'Hard',
 "question":'In the reaction Ni(s) + Pb2+(aq) -> Ni2+(aq) + Pb(s), which species is reduced?',
 "options":{"A":'Ni(s)', "B":'Ni2+(aq)', "C":'Neither species is reduced', "D":'Pb2+(aq)'},"answer":'D'},
{"id":108,"subject":'Chemistry',"topic":'Acids & Bases',"difficulty":'Easy',
 "question":'A substance that releases hydroxide ions (OH-) when dissolved in water is classified, according to Arrhenius, as a(n):',
 "options":{"A":'Base', "B":'Acid', "C":'Salt', "D":'Neutral compound'},"answer":'A'},
{"id":109,"subject":'Chemistry',"topic":'Acids & Bases',"difficulty":'Medium',
 "question":'A solution has a pH of 4. What is its hydrogen ion concentration [H+]?',
 "options":{"A":'1x10^-4 M', "B":'4 M', "C":'1x10^4 M', "D":'0.4 M'},"answer":'A'},
{"id":110,"subject":'Chemistry',"topic":'Acids & Bases',"difficulty":'Medium',
 "question":'Amphoteric substances, such as water, can act as:',
 "options":{"A":'Either an acid or a base, depending on the reaction', "B":'Only an acid', "C":'Only a base', "D":'Neither an acid nor a base'},"answer":'A'},
{"id":111,"subject":'Chemistry',"topic":'Acids & Bases',"difficulty":'Hard',
 "question":'A weak base, such as ammonia (NH3), reacts with water to form only a small amount of hydroxide ions at equilibrium. Compared to a strong base of the same molar concentration, this weak base solution will have:',
 "options":{"A":'A higher pH', "B":'A lower pH, since it only partially ionizes', "C":'Exactly the same pH', "D":'A pH below 7'},"answer":'B'},
{"id":112,"subject":'Chemistry',"topic":'Organic Chemistry',"difficulty":'Easy',
 "question":'The general formula for a saturated cyclic hydrocarbon (cycloalkane) is:',
 "options":{"A":'CnH2n', "B":'CnH2n+2', "C":'CnH2n-2', "D":'CnHn'},"answer":'A'},
{"id":113,"subject":'Chemistry',"topic":'Organic Chemistry',"difficulty":'Medium',
 "question":'Which type of isomerism occurs when two compounds have the same molecular formula but the atoms are connected in a different order?',
 "options":{"A":'Geometric (cis-trans) isomerism', "B":'Optical isomerism only', "C":'No such isomerism exists in organic chemistry', "D":'Structural (constitutional) isomerism'},"answer":'D'},
{"id":114,"subject":'Chemistry',"topic":'Organic Chemistry',"difficulty":'Medium',
 "question":'The functional group present in a ketone is:',
 "options":{"A":'-CHO at the end of the carbon chain', "B":'A carbonyl group (C=O) located within the carbon chain, not at the end', "C":'-COOH', "D":'-OH'},"answer":'B'},
{"id":115,"subject":'Chemistry',"topic":'Organic Chemistry',"difficulty":'Hard',
 "question":'In a free-radical substitution reaction, such as the chlorination of methane, the initiation step typically involves:',
 "options":{"A":'A carbocation forming spontaneously', "B":'Direct substitution without any intermediate', "C":'Homolytic cleavage of the Cl-Cl bond by light or heat, producing two chlorine radicals', "D":'Formation of an ionic bond between reactants'},"answer":'C'},
{"id":116,"subject":'Chemistry',"topic":'Organic Chemistry',"difficulty":'Medium',
 "question":'The reaction between an alcohol and a carboxylic acid, catalyzed by an acid, to form an ester and water is called:',
 "options":{"A":'Hydrolysis', "B":'Saponification', "C":'Oxidation', "D":'Esterification'},"answer":'D'},
{"id":117,"subject":'Chemistry',"topic":'Organic Chemistry',"difficulty":'Easy',
 "question":'A compound with the general formula R-CHO, where the carbonyl group is located at the end of the carbon chain, is classified as a(n):',
 "options":{"A":'Ketone', "B":'Aldehyde', "C":'Ether', "D":'Amine'},"answer":'B'},
{"id":118,"subject":'Chemistry',"topic":'Inorganic Chemistry',"difficulty":'Medium',
 "question":'Transition metals typically form colored complexes and compounds mainly due to:',
 "options":{"A":'Their large atomic size alone', "B":'Their high melting points', "C":'Their complete lack of valence electrons', "D":'d-d electron transitions that absorb specific wavelengths of visible light'},"answer":'D'},
{"id":119,"subject":'Chemistry',"topic":'Inorganic Chemistry',"difficulty":'Medium',
 "question":'Metalloids, such as silicon and germanium, are useful in the electronics industry mainly because they:',
 "options":{"A":'Have intermediate electrical conductivity (semiconductor properties) between metals and nonmetals', "B":'Are perfect electrical insulators', "C":'Are highly reactive with water', "D":'Cannot conduct electricity under any conditions'},"answer":'A'},
{"id":120,"subject":'Chemistry',"topic":'Inorganic Chemistry',"difficulty":'Hard',
 "question":"In the reaction MnO2 + 4HCl -> MnCl2 + Cl2 + 2H2O, manganese's oxidation state changes from:",
 "options":{"A":'+2 to +4 (oxidation)', "B":'+4 to +2 (reduction)', "C":'0 to +4', "D":'No change occurs'},"answer":'B'},
{"id":121,"subject":'Chemistry',"topic":'Physical Chemistry',"difficulty":'Medium',
 "question":'The percentage composition by mass of a compound is calculated by:',
 "options":{"A":'Dividing the total molar mass by the mass of one element', "B":'Adding the atomic masses of all elements without dividing by anything', "C":'Dividing the mass of an element in the compound by the total molar mass of the compound, then multiplying by 100', "D":'Multiplying the number of atoms present by 100 directly'},"answer":'C'},
{"id":122,"subject":'Chemistry',"topic":'Physical Chemistry',"difficulty":'Hard',
 "question":'15 mL of 0.4 M HCl is needed to neutralize 20 mL of Ca(OH)2 solution (2HCl + Ca(OH)2 -> CaCl2 + 2H2O). What is the molarity of the Ca(OH)2 solution?',
 "options":{"A":'0.3 M', "B":'0.6 M', "C":'0.075 M', "D":'0.15 M'},"answer":'D'},
{"id":123,"subject":'Chemistry',"topic":'Environmental Chemistry',"difficulty":'Easy',
 "question":'Which of the following gases is primarily responsible for the depletion of the ozone layer?',
 "options":{"A":'Carbon dioxide', "B":'Nitrogen', "C":'Oxygen', "D":'Chlorofluorocarbons (CFCs)'},"answer":'D'},
{"id":124,"subject":'Chemistry',"topic":'Environmental Chemistry',"difficulty":'Medium',
 "question":'Eutrophication in lakes and rivers, often caused by agricultural runoff, leads to:',
 "options":{"A":'A decrease in algae and plant growth', "B":'An increase in dissolved oxygen levels', "C":'Excessive algal growth that depletes dissolved oxygen as it decomposes, harming aquatic life', "D":'No significant ecological effect on the water body'},"answer":'C'},
{"id":125,"subject":'Chemistry',"topic":'Chemical Bonding',"difficulty":'Easy',
 "question":'A polar molecule has:',
 "options":{"A":'An even distribution of electron density throughout', "B":'An uneven distribution of electron density, creating regions of partial positive and negative charge', "C":'No electrons at all', "D":'Only nonpolar bonds within it'},"answer":'B'},
{"id":126,"subject":'Chemistry',"topic":'Atomic Structure',"difficulty":'Easy',
 "question":'Isotopes of carbon, such as carbon-12 and carbon-14, have the same number of protons but different numbers of:',
 "options":{"A":'Electrons', "B":'Neutrons', "C":'Valence shells', "D":'Isotopes'},"answer":'B'},

# ============================================================
# PHYSICS (36 questions) - id 127-162
# ============================================================
{"id":127,"subject":'Physics',"topic":'Kinematics',"difficulty":'Easy',
 "question":'A car travels 180 km in 3 hours at constant speed. What is its speed?',
 "options":{"A":'40 km/h', "B":'540 km/h', "C":'6 km/h', "D":'60 km/h'},"answer":'D'},
{"id":128,"subject":'Physics',"topic":'Kinematics',"difficulty":'Medium',
 "question":'An object decelerates uniformly from 40 m/s to 10 m/s over 5 seconds. What is the magnitude of its deceleration?',
 "options":{"A":'6 m/s^2', "B":'5 m/s^2', "C":'8 m/s^2', "D":'2 m/s^2'},"answer":'A'},
{"id":129,"subject":'Physics',"topic":'Kinematics',"difficulty":'Hard',
 "question":'A ball is thrown vertically upward and returns to its starting point after 6 seconds (g = 10 m/s^2, ignoring air resistance). What was its initial velocity?',
 "options":{"A":'30 m/s', "B":'20 m/s', "C":'60 m/s', "D":'15 m/s'},"answer":'A'},
{"id":130,"subject":'Physics',"topic":'Dynamics',"difficulty":'Easy',
 "question":"According to Newton's third law of motion, for every action there is:",
 "options":{"A":'An equal and opposite reaction', "B":'No reaction at all', "C":'A smaller, unrelated reaction', "D":'A reaction only if the object is stationary'},"answer":'A'},
{"id":131,"subject":'Physics',"topic":'Dynamics',"difficulty":'Medium',
 "question":'A 4 kg object, initially at rest, experiences a net force of 20 N for 3 seconds. What is its final velocity?',
 "options":{"A":'5 m/s', "B":'15 m/s', "C":'60 m/s', "D":'12 m/s'},"answer":'B'},
{"id":132,"subject":'Physics',"topic":'Dynamics',"difficulty":'Medium',
 "question":'The momentum of a moving object is calculated as the product of its:',
 "options":{"A":'Mass and acceleration', "B":'Mass and velocity', "C":'Force and time', "D":'Weight and height'},"answer":'B'},
{"id":133,"subject":'Physics',"topic":'Dynamics',"difficulty":'Hard',
 "question":'A 2 kg object moving at 6 m/s collides with a stationary 4 kg object, and they stick together (perfectly inelastic collision). What is their combined velocity immediately after the collision?',
 "options":{"A":'1 m/s', "B":'3 m/s', "C":'2 m/s', "D":'4 m/s'},"answer":'C'},
{"id":134,"subject":'Physics',"topic":'Work, Energy & Power',"difficulty":'Easy',
 "question":'The unit of power, the watt, is equivalent to:',
 "options":{"A":'One newton per second', "B":'One newton-meter per hour', "C":'One joule per second', "D":'One kilogram per second'},"answer":'C'},
{"id":135,"subject":'Physics',"topic":'Work, Energy & Power',"difficulty":'Medium',
 "question":'How much kinetic energy does a 4 kg object have when moving at 5 m/s?',
 "options":{"A":'20 J', "B":'100 J', "C":'50 J', "D":'10 J'},"answer":'C'},
{"id":136,"subject":'Physics',"topic":'Work, Energy & Power',"difficulty":'Medium',
 "question":'A roller coaster car sits momentarily at rest at the very top of a tall hill. At this instant, it has maximum:',
 "options":{"A":'Potential energy and minimum kinetic energy', "B":'Kinetic energy and minimum potential energy', "C":'Both kinetic and potential energy equal to zero', "D":'Only thermal energy'},"answer":'A'},
{"id":137,"subject":'Physics',"topic":'Work, Energy & Power',"difficulty":'Hard',
 "question":'An engine performs 6000 J of work in 20 seconds. What is its power output?',
 "options":{"A":'120 W', "B":'300 W', "C":'30000 W', "D":'3000 W'},"answer":'B'},
{"id":138,"subject":'Physics',"topic":'Circular Motion & Gravitation',"difficulty":'Easy',
 "question":'The force required to keep an object moving along a circular path is directed:',
 "options":{"A":'Away from the center', "B":'Toward the center of the circular path', "C":'Tangent to the circle', "D":'In the direction of motion'},"answer":'B'},
{"id":139,"subject":'Physics',"topic":'Circular Motion & Gravitation',"difficulty":'Medium',
 "question":'If the distance between two objects is tripled, while their masses remain unchanged, the gravitational force between them becomes:',
 "options":{"A":'One ninth of the original', "B":'One third of the original', "C":'Three times the original', "D":'Nine times the original'},"answer":'A'},
{"id":140,"subject":'Physics',"topic":'Circular Motion & Gravitation',"difficulty":'Hard',
 "question":'Two satellites orbit Earth; Satellite A has a larger orbital radius than Satellite B. Compared to Satellite B, Satellite A has:',
 "options":{"A":'A shorter orbital period', "B":'Exactly the same orbital period', "C":'Zero orbital period', "D":'A longer orbital period'},"answer":'D'},
{"id":141,"subject":'Physics',"topic":'Fluid Mechanics',"difficulty":'Easy',
 "question":"The pressure exerted by a fluid at a given point depends on the fluid's density and its:",
 "options":{"A":'Depth (height) of the fluid column above that point', "B":'Volume', "C":'Color', "D":'Temperature alone'},"answer":'A'},
{"id":142,"subject":'Physics',"topic":'Fluid Mechanics',"difficulty":'Medium',
 "question":'A solid object with a density less than that of a liquid, when placed in the liquid, will:',
 "options":{"A":'Sink completely to the bottom', "B":'Dissolve entirely into the liquid', "C":'Remain suspended exactly at the surface with no part above it', "D":'Float, with only part of it submerged'},"answer":'D'},
{"id":143,"subject":'Physics',"topic":'Fluid Mechanics',"difficulty":'Hard',
 "question":"Air flowing over the curved upper surface of an airplane wing moves faster than air flowing beneath the flatter lower surface. According to Bernoulli's principle, this creates:",
 "options":{"A":'Higher pressure above the wing, pushing it down', "B":'Equal pressure above and below, generating no lift', "C":'Lower pressure above the wing than below, generating an upward lift force', "D":"No relationship at all between air speed and the wing's lift"},"answer":'C'},
{"id":144,"subject":'Physics',"topic":'Oscillations & Waves',"difficulty":'Easy',
 "question":'The lowest point of a transverse wave is called its:',
 "options":{"A":'Trough', "B":'Crest', "C":'Node', "D":'Antinode'},"answer":'A'},
{"id":145,"subject":'Physics',"topic":'Oscillations & Waves',"difficulty":'Medium',
 "question":'For a mass-spring system, if the spring constant (k) is increased while the mass stays the same, the period of oscillation will:',
 "options":{"A":'Increase', "B":'Remain unchanged', "C":'Decrease', "D":'Become infinite'},"answer":'C'},
{"id":146,"subject":'Physics',"topic":'Oscillations & Waves',"difficulty":'Medium',
 "question":'A wave has a speed of 15 m/s and a wavelength of 3 m. What is its period?',
 "options":{"A":'0.2 s', "B":'5 s', "C":'45 s', "D":'0.6 s'},"answer":'A'},
{"id":147,"subject":'Physics',"topic":'Oscillations & Waves',"difficulty":'Hard',
 "question":'When two waves of the same frequency and amplitude meet exactly out of phase (180 degrees apart), the result is:',
 "options":{"A":'Constructive interference, doubling the amplitude', "B":'Destructive interference, canceling out to produce zero (or reduced) amplitude', "C":'No interference occurs at all', "D":'The waves simply pass through each other, completely unaffected'},"answer":'B'},
{"id":148,"subject":'Physics',"topic":'Thermodynamics',"difficulty":'Easy',
 "question":'The transfer of heat through the bulk movement of a fluid (liquid or gas) is called:',
 "options":{"A":'Conduction', "B":'Radiation', "C":'Convection', "D":'Insulation'},"answer":'C'},
{"id":149,"subject":'Physics',"topic":'Thermodynamics',"difficulty":'Medium',
 "question":'The third law of thermodynamics states that as temperature approaches absolute zero, the entropy of a perfect crystal approaches:',
 "options":{"A":'A minimum, approaching zero', "B":'Infinity', "C":'A maximum value', "D":'An undefined value'},"answer":'A'},
{"id":150,"subject":'Physics',"topic":'Thermodynamics',"difficulty":'Hard',
 "question":'A gas at constant volume absorbs 600 J of heat, and no work is done on or by the gas, since the volume is constant. What is the change in internal energy of the gas?',
 "options":{"A":'0 J', "B":'600 J', "C":'-600 J', "D":'1200 J'},"answer":'B'},
{"id":151,"subject":'Physics',"topic":'Electrostatics',"difficulty":'Easy',
 "question":'A material through which electric charge flows easily is called a(n):',
 "options":{"A":'Insulator', "B":'Conductor', "C":'Semiconductor', "D":'Superconductor only'},"answer":'B'},
{"id":152,"subject":'Physics',"topic":'Electrostatics',"difficulty":'Medium',
 "question":"According to Coulomb's law, the electrostatic force between two point charges is:",
 "options":{"A":'Inversely proportional to the product of the charges', "B":'Completely independent of the distance between them', "C":'Directly proportional to the distance between them', "D":'Directly proportional to the product of the charges and inversely proportional to the square of the distance between them'},"answer":'D'},
{"id":153,"subject":'Physics',"topic":'Current Electricity',"difficulty":'Easy',
 "question":'The rate of flow of electric charge through a conductor is called:',
 "options":{"A":'Voltage', "B":'Resistance', "C":'Power', "D":'Current'},"answer":'D'},
{"id":154,"subject":'Physics',"topic":'Current Electricity',"difficulty":'Medium',
 "question":'In the circuit shown, three resistors R1 (2 ohm), R2 (3 ohm), and R3 (5 ohm) are all connected in series. What is the total resistance of the circuit?',
 "image":'images/q_circuit_series_r1r2r3.png',
 "options":{"A":'30 ohm', "B":'0.97 ohm', "C":'5 ohm', "D":'10 ohm'},"answer":'D'},
{"id":155,"subject":'Physics',"topic":'Current Electricity',"difficulty":'Hard',
 "question":'A circuit has a 6 V battery connected to a single 3 ohm resistor. What is the current flowing through the circuit?',
 "options":{"A":'0.5 A', "B":'18 A', "C":'3 A', "D":'2 A'},"answer":'D'},
{"id":156,"subject":'Physics',"topic":'Current Electricity',"difficulty":'Medium',
 "question":'A 60 W bulb is used for 5 hours. How much electrical energy (in watt-hours) does it consume?',
 "options":{"A":'300 Wh', "B":'12 Wh', "C":'65 Wh', "D":'55 Wh'},"answer":'A'},
{"id":157,"subject":'Physics',"topic":'Electromagnetism',"difficulty":'Medium',
 "question":'A transformer that decreases voltage from the primary coil to the secondary coil (a step-down transformer) has:',
 "options":{"A":'More turns in the secondary coil than the primary coil', "B":'An equal number of turns in both coils', "C":'Fewer turns in the secondary coil than the primary coil', "D":'No coils at all'},"answer":'C'},
{"id":158,"subject":'Physics',"topic":'Electromagnetism',"difficulty":'Hard',
 "question":'When the current through a coil is suddenly switched off, a spark may sometimes be observed due to:',
 "options":{"A":'Static electricity unrelated to the coil', "B":'The coil suddenly gaining mass', "C":'A self-induced EMF, caused by the rapidly collapsing magnetic field within the coil', "D":'A chemical reaction occurring inside the coil'},"answer":'C'},
{"id":159,"subject":'Physics',"topic":'Modern Physics',"difficulty":'Easy',
 "question":'The atomic number of hydrogen is 1, meaning a neutral hydrogen atom has:',
 "options":{"A":'One neutron only', "B":'Two protons', "C":'One proton and one electron', "D":'No electrons'},"answer":'C'},
{"id":160,"subject":'Physics',"topic":'Modern Physics',"difficulty":'Medium',
 "question":'Alpha particles emitted during radioactive decay are:',
 "options":{"A":'Helium nuclei, consisting of 2 protons and 2 neutrons', "B":'High-energy electrons', "C":'Massless photons', "D":'Single protons only'},"answer":'A'},
{"id":161,"subject":'Physics',"topic":'Modern Physics',"difficulty":'Hard',
 "question":'A radioactive substance has an activity that decreases to 1/4 of its original value after 20 minutes. What is the half-life of this substance?',
 "options":{"A":'5 minutes', "B":'10 minutes', "C":'20 minutes', "D":'40 minutes'},"answer":'B'},
{"id":162,"subject":'Physics',"topic":'Optics',"difficulty":'Medium',
 "question":'The ray diagram shows a diverging (concave) lens with an object placed in front of it. Based on the diagram, the image formed by a concave lens is always:',
 "image":'images/q_concave_lens_diverging.png',
 "options":{"A":'Real, inverted, and magnified', "B":'Real, upright, and the same size as the object', "C":'Virtual, inverted, and magnified', "D":'Virtual, upright, and diminished'},"answer":'D'},

# ============================================================
# ENGLISH (9 questions) - id 163-171
# ============================================================
{"id":163,"subject":'English',"topic":'Synonyms',"difficulty":'Easy',
 "question":"Choose the word most nearly similar in meaning to 'AUDACIOUS':",
 "options":{"A":'Bold', "B":'Timid', "C":'Cautious', "D":'Modest'},"answer":'A'},
{"id":164,"subject":'English',"topic":'Antonyms',"difficulty":'Easy',
 "question":"Choose the word most nearly opposite in meaning to 'GENUINE':",
 "options":{"A":'Sincere', "B":'Authentic', "C":'True', "D":'Fake'},"answer":'D'},
{"id":165,"subject":'English',"topic":'Grammar',"difficulty":'Easy',
 "question":'Choose the grammatically correct sentence:',
 "options":{"A":'He is one of the students who was late.', "B":'He is one of the students who were late.', "C":'He is one of the student who were late.', "D":'He are one of the students who were late.'},"answer":'B'},
{"id":166,"subject":'English',"topic":'Grammar',"difficulty":'Medium',
 "question":'Choose the correct sentence:',
 "options":{"A":'By the time we arrived, the movie had already started.', "B":'By the time we arrived, the movie has already started.', "C":'By the time we arrive, the movie had already started.', "D":'By the time we arrived, the movie already starts.'},"answer":'A'},
{"id":167,"subject":'English',"topic":'Sentence Correction',"difficulty":'Medium',
 "question":'Identify the sentence with correct subject-verb agreement:',
 "options":{"A":'Either the manager or the employees is responsible.', "B":'Either the manager or the employees was responsible.', "C":'Either the manager or the employees are responsible.', "D":'Either the manager and the employees are responsible.'},"answer":'C'},
{"id":168,"subject":'English',"topic":'Vocabulary',"difficulty":'Medium',
 "question":"Choose the word that best completes the sentence: 'Even under intense pressure, the surgeon remained remarkably ______ throughout the operation.'",
 "options":{"A":'Frantic', "B":'Distracted', "C":'Nervous', "D":'Composed'},"answer":'D'},
{"id":169,"subject":'English',"topic":'Idioms',"difficulty":'Medium',
 "question":"Choose the meaning closest to the idiom 'to see eye to eye with someone':",
 "options":{"A":'To be in complete agreement with someone', "B":'To argue constantly with someone', "C":'To avoid making eye contact with someone', "D":'To meet someone in person for the first time'},"answer":'A'},
{"id":170,"subject":'English',"topic":'Sentence Correction',"difficulty":'Hard',
 "question":"Choose the option that best corrects the sentence: 'The report, along with the supporting documents, were submitted late.'",
 "options":{"A":'The report, along with the supporting documents, are submitted late.', "B":'The report, along with the supporting documents, was submitted late.', "C":'The reports, along with the supporting document, were submitted late.', "D":'No correction is needed.'},"answer":'B'},
{"id":171,"subject":'English',"topic":'Prepositions',"difficulty":'Hard',
 "question":"Choose the correct preposition: 'The students were divided ______ four separate groups for the project.'",
 "options":{"A":'into', "B":'in', "C":'among', "D":'with'},"answer":'A'},

# ============================================================
# LOGICAL REASONING (9 questions) - id 172-180
# ============================================================
{"id":172,"subject":'Logical Reasoning',"topic":'Number Series',"difficulty":'Easy',
 "question":'Find the next number in the series: 6, 12, 18, 24, ?',
 "options":{"A":'26', "B":'28', "C":'30', "D":'32'},"answer":'C'},
{"id":173,"subject":'Logical Reasoning',"topic":'Number Series',"difficulty":'Easy',
 "question":'Find the missing number: 64, 32, 16, 8, ?',
 "options":{"A":'6', "B":'2', "C":'4', "D":'0'},"answer":'C'},
{"id":174,"subject":'Logical Reasoning',"topic":'Analogies',"difficulty":'Easy',
 "question":'Thermometer is to Temperature as Clock is to:',
 "options":{"A":'Numbers', "B":'Hands', "C":'Alarm', "D":'Time'},"answer":'D'},
{"id":175,"subject":'Logical Reasoning',"topic":'Analogies',"difficulty":'Medium',
 "question":'Novelist is to Novel as Sculptor is to:',
 "options":{"A":'Chisel', "B":'Statue', "C":'Marble', "D":'Museum'},"answer":'B'},
{"id":176,"subject":'Logical Reasoning',"topic":'Blood Relations',"difficulty":'Medium',
 "question":"Pointing to a photograph, a man says, 'This lady is my mother's mother's only son's wife.' How is the lady related to the man?",
 "options":{"A":'Mother', "B":'Aunt', "C":'Grandmother', "D":'Sister'},"answer":'B'},
{"id":177,"subject":'Logical Reasoning',"topic":'Coding-Decoding',"difficulty":'Medium',
 "question":'If in a certain code, RIVER is written as SJWFS, how is OCEAN written in the same code?',
 "options":{"A":'PDFBO', "B":'PDFBP', "C":'NBDZM', "D":'PDGBO'},"answer":'A'},
{"id":178,"subject":'Logical Reasoning',"topic":'Syllogism',"difficulty":'Hard',
 "question":'All squares are quadrilaterals. Some quadrilaterals are not rectangles. Which conclusion logically follows?',
 "options":{"A":'Some squares are not rectangles', "B":'All quadrilaterals are squares', "C":'All squares are rectangles', "D":'No definite conclusion can be drawn about squares and rectangles'},"answer":'D'},
{"id":179,"subject":'Logical Reasoning',"topic":'Pattern Recognition',"difficulty":'Hard',
 "question":'Find the next term in the series: 2, 3, 5, 8, 13, ?',
 "options":{"A":'18', "B":'20', "C":'21', "D":'16'},"answer":'C'},
{"id":180,"subject":'Logical Reasoning',"topic":'Direction Sense',"difficulty":'Medium',
 "question":'A cyclist rides 10 km east, then turns south and rides 10 km, then turns west and rides 10 km. How far and in what direction is she from her starting point?',
 "options":{"A":'20 km east', "B":'10 km north', "C":'0 km, back at the start', "D":'10 km south'},"answer":'D'},
]


# ------------------------------------------------------------
# Sanity-check / summary utility
# ------------------------------------------------------------
def summarize(questions):
    from collections import Counter
    subj = Counter(q["subject"] for q in questions)
    diff = Counter(q["difficulty"] for q in questions)
    ans = Counter(q["answer"] for q in questions)
    ids = [q["id"] for q in questions]
    dup_ids = [i for i in set(ids) if ids.count(i) > 1]
    dup_q = [q["question"] for q in questions]
    dup_questions = [t for t in set(dup_q) if dup_q.count(t) > 1]
    images = [q for q in questions if "image" in q]

    print(f"Total questions: {len(questions)}")
    print("\nBy subject:")
    for s, c in subj.items():
        print(f"  {s}: {c}")
    print("\nBy difficulty:")
    for d, c in diff.items():
        print(f"  {d}: {c}")
    print("\nBy correct-answer letter (should be roughly balanced):")
    for L in ["A", "B", "C", "D"]:
        print(f"  {L}: {ans[L]}")
    print(f"\nDuplicate IDs: {dup_ids if dup_ids else 'None'}")
    print(f"Duplicate question text: {dup_questions if dup_questions else 'None'}")
    print(f"\nImage-based questions ({len(images)}):")
    for q in images:
        print(f"  Q{q['id']} [{q['subject']}] -> {q['image']}")

    for q in questions:
        assert set(q["options"].keys()) == {"A", "B", "C", "D"}, f"Q{q['id']} missing an option"
        assert q["answer"] in q["options"], f"Q{q['id']} answer key invalid"
    print("\nAll questions have exactly 4 options (A-D) and a valid answer key. OK.")


def print_answer_key(questions):
    print("\nANSWER KEY")
    print("-" * 40)
    for q in questions:
        print(f"{q['id']:>3}. {q['answer']}", end="   ")
        if q["id"] % 10 == 0:
            print()
    print()


if __name__ == "__main__":
    summarize(QUESTIONS)
    print_answer_key(QUESTIONS)