"""
MDCAT Mock Test 4
==================
Full-length mock test: 180 MCQs
Weightage: Biology 81 | Chemistry 45 | Physics 36 | English 9 | Logical Reasoning 9
Difficulty mix (approx): 30% Easy / 50% Medium / 20% Hard, distributed throughout.

Includes 5 image/diagram-based questions (2 Biology, 1 Chemistry, 2 Physics).
Each such question has an "image" key giving a relative path to a PNG diagram
that must be viewed alongside the question (images/ subfolder, shipped alongside
this file). Diagrams: enzyme-activity vs temperature graph, labeled animal-cell
structure (mitochondrion), acid-base titration curve, a series-parallel resistor
circuit, and a convex-lens ray diagram (object beyond 2F).

Each question is a dict:
    id, subject, topic, difficulty, question, [image], options (A-D), answer (correct letter)

Run this file directly to print a summary / sanity-check the paper.
"""

QUESTIONS = [
# ============================================================
# BIOLOGY (81 questions) - id 1-81
# ============================================================
{"id":1,"subject":'Biology',"topic":'Biomolecules',"difficulty":'Easy',
 "question":'Which of the following is a monosaccharide?',
 "options":{"A":'Cellulose', "B":'Starch', "C":'Glucose', "D":'Glycogen'},"answer":'C'},
{"id":2,"subject":'Biology',"topic":'Biomolecules',"difficulty":'Easy',
 "question":'The bond that joins two amino acids together in a protein chain is called a:',
 "options":{"A":'Glycosidic bond', "B":'Hydrogen bond', "C":'Ester bond', "D":'Peptide bond'},"answer":'D'},
{"id":3,"subject":'Biology',"topic":'Biomolecules',"difficulty":'Medium',
 "question":'The secondary structure of a protein, such as an alpha helix, is stabilized mainly by:',
 "options":{"A":'Hydrogen bonds along the polypeptide backbone', "B":'Peptide bonds between adjacent chains', "C":'Ionic bonds between side chains', "D":'Disulfide bridges only'},"answer":'A'},
{"id":4,"subject":'Biology',"topic":'Biomolecules',"difficulty":'Medium',
 "question":'Cellulose cannot be digested by humans, unlike starch, mainly because cellulose contains:',
 "options":{"A":'Beta-1,4 glycosidic linkages that human digestive enzymes cannot break', "B":'Alpha-1,4 glycosidic linkages, like starch', "C":'Only monosaccharide units', "D":'No glycosidic linkages at all'},"answer":'A'},
{"id":5,"subject":'Biology',"topic":'Biomolecules',"difficulty":'Hard',
 "question":'Which of the following distinguishes RNA nucleotides from DNA nucleotides?',
 "options":{"A":'RNA nucleotides lack a phosphate group', "B":'RNA nucleotides contain deoxyribose sugar', "C":'RNA nucleotides contain ribose sugar and typically uracil instead of thymine', "D":'RNA nucleotides cannot form hydrogen bonds'},"answer":'C'},
{"id":6,"subject":'Biology',"topic":'Enzymes',"difficulty":'Easy',
 "question":'A substance that increases the rate of a biochemical reaction without being consumed is called a/an:',
 "options":{"A":'Substrate', "B":'Cofactor', "C":'Enzyme', "D":'Product'},"answer":'C'},
{"id":7,"subject":'Biology',"topic":'Enzymes',"difficulty":'Medium',
 "question":'A competitive inhibitor reduces enzyme activity by:',
 "options":{"A":'Binding at the active site and blocking substrate access', "B":'Binding permanently to the enzyme and destroying it', "C":'Binding only to the product', "D":"Increasing the enzyme's affinity for substrate"},"answer":'A'},
{"id":8,"subject":'Biology',"topic":'Enzymes',"difficulty":'Medium',
 "question":'The graph shows the activity of a human digestive enzyme across a range of temperatures, with a peak near 37°C followed by a sharp decline at higher temperatures. The decline in activity above the optimum is best explained by:',
 "image":'images/q4_enzyme_temp_graph.png',
 "options":{"A":"Denaturation of the enzyme's tertiary structure, disrupting the active site", "B":'The enzyme being washed away', "C":'An increase in substrate concentration', "D":'The reaction reaching equilibrium'},"answer":'A'},
{"id":9,"subject":'Biology',"topic":'Enzymes',"difficulty":'Hard',
 "question":'On a Lineweaver-Burk (double reciprocal) plot of 1/v against 1/[S], the x-intercept of the line represents:',
 "options":{"A":'1/Vmax', "B":'Vmax', "C":'Km/Vmax', "D":'-1/Km'},"answer":'D'},
{"id":10,"subject":'Biology',"topic":'Cell Biology',"difficulty":'Easy',
 "question":'Which organelle is the primary site of ATP production through aerobic respiration?',
 "options":{"A":'Golgi apparatus', "B":'Lysosome', "C":'Ribosome', "D":'Mitochondrion'},"answer":'D'},
{"id":11,"subject":'Biology',"topic":'Cell Biology',"difficulty":'Easy',
 "question":'Ribosomes attached to the rough endoplasmic reticulum mainly synthesize proteins destined for:',
 "options":{"A":'Storage in the nucleus', "B":'Secretion or insertion into membranes', "C":'Breakdown in lysosomes only', "D":'Immediate destruction'},"answer":'B'},
{"id":12,"subject":'Biology',"topic":'Cell Biology',"difficulty":'Medium',
 "question":'The cytoskeleton in eukaryotic cells provides structural support and also functions in:',
 "options":{"A":'Photosynthesis', "B":'Intracellular transport and cell movement', "C":'DNA replication only', "D":'Protein glycosylation'},"answer":'B'},
{"id":13,"subject":'Biology',"topic":'Cell Biology',"difficulty":'Medium',
 "question":'Which feature distinguishes prokaryotic cells from eukaryotic cells?',
 "options":{"A":'Absence of a membrane-bound nucleus', "B":'Presence of ribosomes', "C":'Presence of a cell membrane', "D":'Presence of DNA'},"answer":'A'},
{"id":14,"subject":'Biology',"topic":'Cell Biology',"difficulty":'Medium',
 "question":'The diagram shows an animal cell with structures labeled P, Q, R, and S. Structure Q has a double membrane, with the inner membrane folded into cristae to increase surface area for ATP synthesis. Which structure is Q?',
 "image":'images/q4_cell_diagram_pqrs.png',
 "options":{"A":'Structure P (nucleus)', "B":'Structure R (Golgi apparatus)', "C":'Structure Q (mitochondrion)', "D":'Structure S (lysosome)'},"answer":'C'},
{"id":15,"subject":'Biology',"topic":'Cell Biology',"difficulty":'Medium',
 "question":'The nucleolus within the nucleus is primarily responsible for:',
 "options":{"A":'DNA replication', "B":'Protein folding', "C":'Synthesis of rRNA and assembly of ribosomal subunits', "D":'Lipid synthesis'},"answer":'C'},
{"id":16,"subject":'Biology',"topic":'Cell Biology',"difficulty":'Hard',
 "question":'A cell exposed to a drug that disrupts microtubule formation would most directly experience difficulty with:',
 "options":{"A":'DNA transcription', "B":'Glycolysis', "C":'Fatty acid synthesis', "D":'Formation of the mitotic spindle during cell division'},"answer":'D'},
{"id":17,"subject":'Biology',"topic":'Cell Membrane & Transport',"difficulty":'Easy',
 "question":'Osmosis refers specifically to the diffusion of:',
 "options":{"A":'Proteins across a membrane', "B":'Ions using ATP', "C":'Water across a selectively permeable membrane', "D":'Glucose using carrier proteins'},"answer":'C'},
{"id":18,"subject":'Biology',"topic":'Cell Membrane & Transport',"difficulty":'Medium',
 "question":'A plant cell placed in a hypotonic solution will typically:',
 "options":{"A":'Undergo plasmolysis', "B":'Become turgid as water enters, with the cell wall preventing bursting', "C":'Shrink and lose turgor', "D":'Remain completely unchanged'},"answer":'B'},
{"id":19,"subject":'Biology',"topic":'Cell Membrane & Transport',"difficulty":'Medium',
 "question":'Active transport differs from facilitated diffusion in that active transport:',
 "options":{"A":'Requires no membrane proteins', "B":'Always moves substances down their concentration gradient', "C":'Moves substances against their concentration gradient using ATP', "D":'Occurs only in plant cells'},"answer":'C'},
{"id":20,"subject":'Biology',"topic":'Cell Membrane & Transport',"difficulty":'Hard',
 "question":'The sodium-potassium pump moves ions across the membrane in which pattern per cycle?',
 "options":{"A":'2 Na+ out, 3 K+ in', "B":'3 Na+ out, 2 K+ in', "C":'3 Na+ in, 2 K+ out', "D":'Equal numbers of Na+ and K+ in both directions'},"answer":'B'},
{"id":21,"subject":'Biology',"topic":'Cell Membrane & Transport',"difficulty":'Easy',
 "question":'Phospholipids in the plasma membrane arrange themselves into a bilayer mainly because they are:',
 "options":{"A":'Fully hydrophobic', "B":'Fully hydrophilic', "C":'Positively charged throughout', "D":'Amphipathic, with hydrophilic heads and hydrophobic tails'},"answer":'D'},
{"id":22,"subject":'Biology',"topic":'Cell Cycle & Division',"difficulty":'Easy',
 "question":'DNA replication occurs during which phase of the cell cycle?',
 "options":{"A":'G1 phase', "B":'G2 phase', "C":'M phase', "D":'S phase'},"answer":'D'},
{"id":23,"subject":'Biology',"topic":'Cell Cycle & Division',"difficulty":'Easy',
 "question":'Sister chromatids separate and move to opposite poles during:',
 "options":{"A":'Prophase', "B":'Anaphase', "C":'Metaphase', "D":'Telophase'},"answer":'B'},
{"id":24,"subject":'Biology',"topic":'Cell Cycle & Division',"difficulty":'Medium',
 "question":'Meiosis differs fundamentally from mitosis in that meiosis:',
 "options":{"A":'Produces two genetically identical diploid cells', "B":'Involves two rounds of division producing four genetically varied haploid cells', "C":'Occurs only in somatic cells', "D":'Does not involve DNA replication'},"answer":'B'},
{"id":25,"subject":'Biology',"topic":'Cell Cycle & Division',"difficulty":'Medium',
 "question":'A cell with a diploid number of 46 chromosomes enters meiosis. How many chromosomes will each resulting gamete contain?',
 "options":{"A":'23', "B":'46', "C":'92', "D":'12'},"answer":'A'},
{"id":26,"subject":'Biology',"topic":'Cell Cycle & Division',"difficulty":'Medium',
 "question":'Crossing over between homologous chromosomes during prophase I of meiosis primarily results in:',
 "options":{"A":'Identical daughter cells', "B":'Doubling of chromosome number', "C":'Prevention of gamete formation', "D":'Increased genetic variation among gametes'},"answer":'D'},
{"id":27,"subject":'Biology',"topic":'Cell Cycle & Division',"difficulty":'Hard',
 "question":'A checkpoint late in G1, sometimes called the restriction point, primarily determines whether:',
 "options":{"A":'Cytokinesis will occur', "B":'Anaphase can begin', "C":'The cell is committed to proceeding through the rest of the cell cycle', "D":'Spindle fibers have attached properly'},"answer":'C'},
{"id":28,"subject":'Biology',"topic":'Genetics',"difficulty":'Easy',
 "question":'In humans, brown eyes (B) are dominant over blue eyes (b). A cross between a homozygous brown-eyed parent and a blue-eyed parent produces offspring with genotype:',
 "options":{"A":'All BB', "B":'All Bb', "C":'1 BB : 1 bb', "D":'All bb'},"answer":'B'},
{"id":29,"subject":'Biology',"topic":'Genetics',"difficulty":'Medium',
 "question":'A cross between two heterozygous brown-eyed individuals (Bb x Bb) is expected to give what phenotypic ratio?',
 "options":{"A":'1 brown : 1 blue', "B":'1 brown : 2 intermediate : 1 blue', "C":'3 brown : 1 blue', "D":'9 : 3 : 3 : 1'},"answer":'C'},
{"id":30,"subject":'Biology',"topic":'Genetics',"difficulty":'Medium',
 "question":'Hemophilia is an X-linked recessive disorder. If a carrier mother and an unaffected father have children, what proportion of their sons is expected to be affected?',
 "options":{"A":'0%', "B":'50%', "C":'25%', "D":'100%'},"answer":'B'},
{"id":31,"subject":'Biology',"topic":'Genetics',"difficulty":'Hard',
 "question":'In a dihybrid cross AaBb x AaBb, assuming independent assortment, what fraction of offspring is expected to be homozygous recessive for both traits?',
 "options":{"A":'1/4', "B":'9/16', "C":'1/16', "D":'1/2'},"answer":'C'},
{"id":32,"subject":'Biology',"topic":'Genetics',"difficulty":'Medium',
 "question":'A woman with blood group A (heterozygous, IAi) and a man with blood group B (heterozygous, IBi) have children. Which blood groups could NOT appear among their offspring?',
 "options":{"A":'A and B', "B":'AB and O', "C":'None; all are possible', "D":'A, B, AB, and O'},"answer":'C'},
{"id":33,"subject":'Biology',"topic":'Genetics',"difficulty":'Hard',
 "question":'A trait that appears in every generation, affects roughly half the offspring of an affected heterozygous parent, and is passed regardless of the sex of the affected parent, is most consistent with:',
 "options":{"A":'Autosomal recessive inheritance', "B":'Autosomal dominant inheritance', "C":'X-linked recessive inheritance', "D":'Y-linked inheritance'},"answer":'B'},
{"id":34,"subject":'Biology',"topic":'Genetics',"difficulty":'Medium',
 "question":'In humans, the ABO blood group system, where alleles IA and IB are both expressed in a heterozygote (as in blood type AB), illustrates:',
 "options":{"A":'Codominance', "B":'Incomplete dominance', "C":'Epistasis', "D":'Complete dominance'},"answer":'A'},
{"id":35,"subject":'Biology',"topic":'Molecular Biology',"difficulty":'Easy',
 "question":'In RNA, adenine pairs with:',
 "options":{"A":'Guanine', "B":'Uracil', "C":'Cytosine', "D":'Thymine'},"answer":'B'},
{"id":36,"subject":'Biology',"topic":'Molecular Biology',"difficulty":'Easy',
 "question":'The process by which a polypeptide chain is synthesized from an mRNA template at the ribosome is called:',
 "options":{"A":'Translation', "B":'Transcription', "C":'Replication', "D":'Splicing'},"answer":'A'},
{"id":37,"subject":'Biology',"topic":'Molecular Biology',"difficulty":'Medium',
 "question":'DNA replication is described as semiconservative because each new DNA molecule contains:',
 "options":{"A":'Two entirely new strands', "B":'One original (parental) strand and one newly synthesized strand', "C":'Two entirely original strands', "D":'A mixture of DNA and RNA strands'},"answer":'B'},
{"id":38,"subject":'Biology',"topic":'Molecular Biology',"difficulty":'Medium',
 "question":'The enzyme responsible for unwinding the DNA double helix at the replication fork is:',
 "options":{"A":'DNA polymerase', "B":'DNA ligase', "C":'RNA primase', "D":'DNA helicase'},"answer":'D'},
{"id":39,"subject":'Biology',"topic":'Molecular Biology',"difficulty":'Medium',
 "question":'A point mutation that changes a codon to specify a different amino acid is called a:',
 "options":{"A":'Silent mutation', "B":'Nonsense mutation', "C":'Frameshift mutation', "D":'Missense mutation'},"answer":'D'},
{"id":40,"subject":'Biology',"topic":'Molecular Biology',"difficulty":'Hard',
 "question":"Insertion of a single nucleotide into the middle of a gene's coding sequence would most likely cause:",
 "options":{"A":'No change to the protein', "B":'A single silent substitution only', "C":'Only a change at the very last codon', "D":'A frameshift, altering every downstream codon'},"answer":'D'},
{"id":41,"subject":'Biology',"topic":'Molecular Biology',"difficulty":'Hard',
 "question":'In the lac operon, when glucose is abundant and lactose is absent, transcription of the lac genes is:',
 "options":{"A":'Maximally activated', "B":'Always on regardless of the repressor', "C":'Kept off, as the repressor binds the operator and blocks RNA polymerase', "D":'Controlled only by the CAP protein'},"answer":'C'},
{"id":42,"subject":'Biology',"topic":'Molecular Biology',"difficulty":'Medium',
 "question":'Which of the following correctly describes the direction of mRNA synthesis relative to its DNA template?',
 "options":{"A":"RNA polymerase reads the template 5' to 3' and synthesizes mRNA 3' to 5'", "B":"RNA polymerase reads the template strand 3' to 5' and synthesizes mRNA 5' to 3'", "C":'mRNA synthesis has no fixed direction', "D":'RNA polymerase synthesizes both strands simultaneously'},"answer":'B'},
{"id":43,"subject":'Biology',"topic":'Molecular Biology',"difficulty":'Medium',
 "question":'Introns differ from exons in that introns:',
 "options":{"A":'Code for functional protein', "B":'Are found only in prokaryotic genes', "C":'Are removed from pre-mRNA before translation', "D":'Are translated into amino acids'},"answer":'C'},
{"id":44,"subject":'Biology',"topic":'Molecular Biology',"difficulty":'Easy',
 "question":'The start codon that initiates translation and codes for methionine is:',
 "options":{"A":'UAA', "B":'UGA', "C":'UAG', "D":'AUG'},"answer":'D'},
{"id":45,"subject":'Biology',"topic":'Evolution',"difficulty":'Easy',
 "question":'The process by which individuals with favorable heritable traits survive and reproduce more successfully than others is called:',
 "options":{"A":'Genetic drift', "B":'Gene flow', "C":'Mutation', "D":'Natural selection'},"answer":'D'},
{"id":46,"subject":'Biology',"topic":'Evolution',"difficulty":'Medium',
 "question":'Homologous structures, such as the forelimbs of humans, whales, and bats, provide evidence for evolution because they:',
 "options":{"A":'Share a similar underlying structure inherited from a common ancestor, despite different functions', "B":'Have completely different underlying bone structure', "C":'Are found only in unrelated species', "D":'Always perform identical functions'},"answer":'A'},
{"id":47,"subject":'Biology',"topic":'Evolution',"difficulty":'Medium',
 "question":'Genetic drift is expected to have the greatest effect on allele frequencies in:',
 "options":{"A":'A very large population', "B":'A population with no reproduction', "C":'A small population', "D":'A population in Hardy-Weinberg equilibrium'},"answer":'C'},
{"id":48,"subject":'Biology',"topic":'Evolution',"difficulty":'Hard',
 "question":'In a population in Hardy-Weinberg equilibrium, the frequency of the dominant allele (p) is 0.6. What percentage of the population is expected to be heterozygous?',
 "options":{"A":'36%', "B":'16%', "C":'24%', "D":'48%'},"answer":'D'},
{"id":49,"subject":'Biology',"topic":'Classification & Diversity',"difficulty":'Easy',
 "question":'The two-part naming system that gives every species a genus name and a species name is called:',
 "options":{"A":'Taxonomic hierarchy', "B":'Cladistics', "C":'Binomial nomenclature', "D":'Phylogeny'},"answer":'C'},
{"id":50,"subject":'Biology',"topic":'Classification & Diversity',"difficulty":'Easy',
 "question":'Organisms in kingdom Fungi obtain nutrition mainly by:',
 "options":{"A":'Photosynthesis', "B":'Absorbing nutrients from organic matter through extracellular digestion', "C":'Ingesting prey through a mouth', "D":'Chemosynthesis alone'},"answer":'B'},
{"id":51,"subject":'Biology',"topic":'Classification & Diversity',"difficulty":'Medium',
 "question":'Which feature is used to place an organism in domain Eukarya rather than Bacteria or Archaea?',
 "options":{"A":'Presence of a cell wall', "B":'Presence of a membrane-bound nucleus and organelles', "C":'Ability to survive extreme environments', "D":'Peptidoglycan in the cell wall'},"answer":'B'},
{"id":52,"subject":'Biology',"topic":'Classification & Diversity',"difficulty":'Medium',
 "question":'A student observes a unicellular organism with a membrane-bound nucleus and chloroplasts, capable of both photosynthesis and locomotion via a flagellum. This organism most likely belongs to:',
 "options":{"A":'Kingdom Monera', "B":'Kingdom Fungi', "C":'Kingdom Animalia', "D":'Kingdom Protista'},"answer":'D'},
{"id":53,"subject":'Biology',"topic":'Classification & Diversity',"difficulty":'Easy',
 "question":'Which taxonomic rank is broader than Class but narrower than Kingdom?',
 "options":{"A":'Order', "B":'Family', "C":'Genus', "D":'Phylum'},"answer":'D'},
{"id":54,"subject":'Biology',"topic":'Classification & Diversity',"difficulty":'Medium',
 "question":'Members of phylum Arthropoda are characterized mainly by:',
 "options":{"A":'A soft body with no appendages', "B":'A segmented body, jointed appendages, and a chitinous exoskeleton', "C":'Radial symmetry only', "D":'An internal skeleton made of bone'},"answer":'B'},
{"id":55,"subject":'Biology',"topic":'Plant Biology',"difficulty":'Easy',
 "question":'Water and dissolved minerals are transported upward from roots to leaves mainly through the:',
 "options":{"A":'Xylem', "B":'Phloem', "C":'Cambium', "D":'Cortex'},"answer":'A'},
{"id":56,"subject":'Biology',"topic":'Plant Biology',"difficulty":'Medium',
 "question":'The light-dependent reactions of photosynthesis take place in the:',
 "options":{"A":'Stroma', "B":'Thylakoid membrane', "C":'Mitochondrial matrix', "D":'Cytoplasm'},"answer":'B'},
{"id":57,"subject":'Biology',"topic":'Plant Biology',"difficulty":'Medium',
 "question":'During the light-dependent reactions, the splitting of water (photolysis) primarily provides:',
 "options":{"A":'Glucose for the Calvin cycle', "B":'Electrons to replace those lost by photosystem II, along with oxygen as a byproduct', "C":'Carbon dioxide for carbon fixation', "D":'ATP directly without electron transport'},"answer":'B'},
{"id":58,"subject":'Biology',"topic":'Plant Biology',"difficulty":'Hard',
 "question":'CAM (Crassulacean Acid Metabolism) plants, common in arid environments, reduce water loss mainly by:',
 "options":{"A":'Opening stomata during the day and closing them at night', "B":'Lacking stomata entirely', "C":'Performing photosynthesis without light entirely', "D":'Closing stomata during the day and fixing CO2 at night, storing it as an organic acid'},"answer":'D'},
{"id":59,"subject":'Biology',"topic":'Plant Biology',"difficulty":'Medium',
 "question":'Transpiration, the loss of water vapor from leaves, helps drive water movement through the xylem mainly through:',
 "options":{"A":'Root pressure alone', "B":'Active transport of water molecules', "C":'Cohesion-tension, as evaporation creates a pull that draws water upward through connected water columns', "D":'Osmosis at the stomata'},"answer":'C'},
{"id":60,"subject":'Biology',"topic":'Plant Biology',"difficulty":'Easy',
 "question":"The fusion of a pollen grain's sperm nucleus with the egg cell in a flower is called:",
 "options":{"A":'Germination', "B":'Fertilization', "C":'Pollination', "D":'Transpiration'},"answer":'B'},
{"id":61,"subject":'Biology',"topic":'Human Physiology - Digestion',"difficulty":'Easy',
 "question":'Protein digestion begins in the stomach due to the enzyme:',
 "options":{"A":'Pepsin', "B":'Salivary amylase', "C":'Trypsin', "D":'Lipase'},"answer":'A'},
{"id":62,"subject":'Biology',"topic":'Human Physiology - Digestion',"difficulty":'Medium',
 "question":'Bile, produced by the liver, aids fat digestion mainly by:',
 "options":{"A":'Chemically breaking fats into fatty acids', "B":'Neutralizing stomach acid only', "C":'Emulsifying large fat globules into smaller droplets, increasing surface area for lipase', "D":'Directly absorbing fats into the bloodstream'},"answer":'C'},
{"id":63,"subject":'Biology',"topic":'Human Physiology - Digestion',"difficulty":'Medium',
 "question":'Most nutrient absorption in the digestive tract occurs in the:',
 "options":{"A":'Small intestine', "B":'Stomach', "C":'Large intestine', "D":'Esophagus'},"answer":'A'},
{"id":64,"subject":'Biology',"topic":'Human Physiology - Digestion',"difficulty":'Hard',
 "question":'Villi and microvilli lining the small intestine primarily function to:',
 "options":{"A":'Produce digestive enzymes exclusively', "B":'Store undigested food', "C":'Greatly increase surface area for nutrient absorption', "D":'Secrete bile'},"answer":'C'},
{"id":65,"subject":'Biology',"topic":'Human Physiology - Circulation',"difficulty":'Easy',
 "question":'Oxygenated blood returning from the lungs first enters which chamber of the heart?',
 "options":{"A":'Right atrium', "B":'Right ventricle', "C":'Left ventricle', "D":'Left atrium'},"answer":'D'},
{"id":66,"subject":'Biology',"topic":'Human Physiology - Circulation',"difficulty":'Medium',
 "question":'Arteries generally have thicker, more muscular walls than veins mainly because arteries must:',
 "options":{"A":'Carry blood at low pressure', "B":'Contain valves to prevent backflow', "C":'Withstand the high pressure of blood pumped directly from the heart', "D":'Allow diffusion of nutrients'},"answer":'C'},
{"id":67,"subject":'Biology',"topic":'Human Physiology - Circulation',"difficulty":'Medium',
 "question":'Veins rely mainly on which mechanism, besides heart pressure, to return blood to the heart against gravity?',
 "options":{"A":'Peristalsis of the vein walls', "B":'Active transport of blood cells', "C":'Skeletal muscle contraction combined with one-way valves', "D":'Diffusion'},"answer":'C'},
{"id":68,"subject":'Biology',"topic":'Human Physiology - Circulation',"difficulty":'Hard',
 "question":"The SA node is often called the heart's natural pacemaker because it:",
 "options":{"A":'Receives all sensory input from the brain', "B":'Initiates the electrical impulse that sets the rhythm of each heartbeat', "C":'Pumps blood directly into the aorta', "D":'Is located in the left ventricle'},"answer":'B'},
{"id":69,"subject":'Biology',"topic":'Human Physiology - Respiration',"difficulty":'Easy',
 "question":'Air is warmed, filtered, and humidified as it passes through the:',
 "options":{"A":'Alveoli', "B":'Bronchioles', "C":'Nasal cavity', "D":'Diaphragm'},"answer":'C'},
{"id":70,"subject":'Biology',"topic":'Human Physiology - Respiration',"difficulty":'Medium',
 "question":'During inhalation, the diaphragm:',
 "options":{"A":'Relaxes and domes upward', "B":'Contracts and flattens, increasing thoracic volume', "C":'Remains motionless', "D":'Contracts to decrease thoracic volume'},"answer":'B'},
{"id":71,"subject":'Biology',"topic":'Human Physiology - Respiration',"difficulty":'Medium',
 "question":'Most carbon dioxide is transported in the blood in the form of:',
 "options":{"A":'Dissolved gas in plasma', "B":'Bound directly to hemoglobin as carbaminohemoglobin', "C":'Bicarbonate ions in the plasma', "D":'Carbonic acid crystals'},"answer":'C'},
{"id":72,"subject":'Biology',"topic":'Human Physiology - Excretion',"difficulty":'Easy',
 "question":'Blood is filtered to form urine primarily within the:',
 "options":{"A":'Ureter', "B":'Urinary bladder', "C":'Nephron', "D":'Urethra'},"answer":'C'},
{"id":73,"subject":'Biology',"topic":'Human Physiology - Excretion',"difficulty":'Medium',
 "question":"Filtration in the nephron, where blood plasma is forced out of the glomerulus into Bowman's capsule, is driven mainly by:",
 "options":{"A":'Active transport', "B":'Hydrostatic (blood) pressure', "C":'Osmosis alone', "D":'Facilitated diffusion'},"answer":'B'},
{"id":74,"subject":'Biology',"topic":'Human Physiology - Excretion',"difficulty":'Hard',
 "question":'Increased secretion of ADH (antidiuretic hormone) results in:',
 "options":{"A":'Increased urine volume, as the collecting duct becomes more permeable to water', "B":'No effect on water reabsorption', "C":'Complete cessation of filtration', "D":'Decreased urine volume and more concentrated urine, as more water is reabsorbed'},"answer":'D'},
{"id":75,"subject":'Biology',"topic":'Human Physiology - Nervous & Endocrine',"difficulty":'Easy',
 "question":"The long, single projection that carries nerve impulses away from a neuron's cell body is called the:",
 "options":{"A":'Axon', "B":'Dendrite', "C":'Synapse', "D":'Soma'},"answer":'A'},
{"id":76,"subject":'Biology',"topic":'Human Physiology - Nervous & Endocrine',"difficulty":'Medium',
 "question":'At a chemical synapse, an action potential arriving at the axon terminal triggers:',
 "options":{"A":'Release of neurotransmitter from vesicles into the synaptic cleft', "B":'Direct electrical flow to the next neuron', "C":'Immediate destruction of the neuron', "D":'Reversal of the resting potential permanently'},"answer":'A'},
{"id":77,"subject":'Biology',"topic":'Human Physiology - Nervous & Endocrine',"difficulty":'Medium',
 "question":'Insulin, released by the pancreas, primarily functions to:',
 "options":{"A":'Raise blood glucose levels', "B":'Stimulate glycogen breakdown', "C":'Increase blood pressure', "D":'Lower blood glucose levels by promoting its uptake and storage in cells'},"answer":'D'},
{"id":78,"subject":'Biology',"topic":'Human Physiology - Nervous & Endocrine',"difficulty":'Hard',
 "question":'During the depolarization phase of an action potential, the membrane potential becomes more positive mainly because:',
 "options":{"A":'K+ channels open, allowing K+ efflux', "B":'The sodium-potassium pump reverses direction', "C":'Cl- ions rush into the cell', "D":'Voltage-gated Na+ channels open, allowing Na+ influx'},"answer":'D'},
{"id":79,"subject":'Biology',"topic":'Human Physiology - Reproduction',"difficulty":'Easy',
 "question":'In females, the egg cell is released from the ovary during a process called:',
 "options":{"A":'Menstruation', "B":'Ovulation', "C":'Fertilization', "D":'Implantation'},"answer":'B'},
{"id":80,"subject":'Biology',"topic":'Human Physiology - Reproduction',"difficulty":'Medium',
 "question":'Following fertilization, the developing embryo normally implants in the:',
 "options":{"A":'Ovary', "B":'Endometrium (uterine lining)', "C":'Fallopian tube', "D":'Cervix'},"answer":'B'},
{"id":81,"subject":'Biology',"topic":'Ecology',"difficulty":'Medium',
 "question":'An organism that obtains energy by breaking down dead organic matter and returning nutrients to the ecosystem is best classified as a:',
 "options":{"A":'Primary consumer', "B":'Producer', "C":'Decomposer', "D":'Secondary consumer'},"answer":'C'},

# ============================================================
# CHEMISTRY (45 questions) - id 82-126
# ============================================================
{"id":82,"subject":'Chemistry',"topic":'Atomic Structure',"difficulty":'Easy',
 "question":'The number of protons in the nucleus of an atom is also known as its:',
 "options":{"A":'Mass number', "B":'Atomic number', "C":'Isotope number', "D":'Valency'},"answer":'B'},
{"id":83,"subject":'Chemistry',"topic":'Atomic Structure',"difficulty":'Medium',
 "question":'An atom of chlorine-37 (atomic number 17) contains how many neutrons?',
 "options":{"A":'20', "B":'17', "C":'37', "D":'54'},"answer":'A'},
{"id":84,"subject":'Chemistry',"topic":'Atomic Structure',"difficulty":'Medium',
 "question":'The electron configuration of a neutral sodium atom (Z = 11) is:',
 "options":{"A":'1s2 2s2 2p5', "B":'1s2 2s2 2p6 3s2', "C":'1s2 2s2 2p6', "D":'1s2 2s2 2p6 3s1'},"answer":'D'},
{"id":85,"subject":'Chemistry',"topic":'Atomic Structure',"difficulty":'Hard',
 "question":'An ion formed from a neutral atom with 13 protons that has lost 3 electrons carries a charge of:',
 "options":{"A":'-3', "B":'+1', "C":'-1', "D":'+3'},"answer":'D'},
{"id":86,"subject":'Chemistry',"topic":'Periodic Table',"difficulty":'Easy',
 "question":'Elements in Group 1 of the periodic table, which are highly reactive metals, are called:',
 "options":{"A":'Halogens', "B":'Noble gases', "C":'Alkali metals', "D":'Alkaline earth metals'},"answer":'C'},
{"id":87,"subject":'Chemistry',"topic":'Periodic Table',"difficulty":'Medium',
 "question":'Atomic radius generally increases:',
 "options":{"A":'Down a group, and from right to left across a period', "B":'Across a period left to right, and up a group', "C":'Down a group, and left to right across a period', "D":'Up a group only'},"answer":'A'},
{"id":88,"subject":'Chemistry',"topic":'Periodic Table',"difficulty":'Medium',
 "question":'An element with electron configuration [Ar]4s1 would most likely:',
 "options":{"A":'Lose one electron to form a +1 ion', "B":'Gain one electron to form a -1 ion', "C":'Be chemically inert', "D":'Form only covalent bonds'},"answer":'A'},
{"id":89,"subject":'Chemistry',"topic":'Chemical Bonding',"difficulty":'Easy',
 "question":'An ionic bond is formed primarily through:',
 "options":{"A":'Sharing of electron pairs between atoms', "B":'Overlap of atomic orbitals only', "C":'Weak van der Waals attraction', "D":'Complete transfer of electrons from one atom to another'},"answer":'D'},
{"id":90,"subject":'Chemistry',"topic":'Chemical Bonding',"difficulty":'Medium',
 "question":'According to VSEPR theory, a molecule such as ammonia (NH3), with three bonding pairs and one lone pair on the central atom, has a molecular shape described as:',
 "options":{"A":'Tetrahedral', "B":'Trigonal pyramidal', "C":'Trigonal planar', "D":'Linear'},"answer":'B'},
{"id":91,"subject":'Chemistry',"topic":'Chemical Bonding',"difficulty":'Medium',
 "question":'CO2 is a nonpolar molecule overall, despite having polar C=O bonds, because:',
 "options":{"A":'Its linear geometry causes the two bond dipoles to cancel', "B":'Carbon has no valence electrons', "C":'Oxygen atoms are themselves nonpolar', "D":'Carbon carries a lone pair balancing the dipoles'},"answer":'A'},
{"id":92,"subject":'Chemistry',"topic":'Chemical Bonding',"difficulty":'Hard',
 "question":'Graphite conducts electricity, unlike diamond, mainly because graphite:',
 "options":{"A":'Has delocalized electrons free to move within its layered sheet structure', "B":'Is an ionic compound', "C":'Has no covalent bonds at all', "D":'Contains metal ions'},"answer":'A'},
{"id":93,"subject":'Chemistry',"topic":'States of Matter',"difficulty":'Easy',
 "question":'The change of state directly from a solid to a gas, without passing through the liquid phase, is called:',
 "options":{"A":'Sublimation', "B":'Evaporation', "C":'Condensation', "D":'Melting'},"answer":'A'},
{"id":94,"subject":'Chemistry',"topic":'States of Matter',"difficulty":'Medium',
 "question":"A gas occupies 6.0 L at 2.0 atm. What volume will it occupy at 4.0 atm, assuming constant temperature (Boyle's Law)?",
 "options":{"A":'12.0 L', "B":'8.0 L', "C":'1.5 L', "D":'3.0 L'},"answer":'D'},
{"id":95,"subject":'Chemistry',"topic":'States of Matter',"difficulty":'Hard',
 "question":"A fixed mass of gas occupies 4 L at 300 K at constant pressure. What volume will it occupy at 600 K (Charles's Law)?",
 "options":{"A":'8 L', "B":'2 L', "C":'4 L', "D":'16 L'},"answer":'A'},
{"id":96,"subject":'Chemistry',"topic":'Stoichiometry',"difficulty":'Easy',
 "question":'The molar mass of carbon dioxide (CO2) is approximately:',
 "options":{"A":'44 g/mol', "B":'28 g/mol', "C":'32 g/mol', "D":'12 g/mol'},"answer":'A'},
{"id":97,"subject":'Chemistry',"topic":'Stoichiometry',"difficulty":'Medium',
 "question":'How many moles are present in 36 g of water (molar mass 18 g/mol)?',
 "options":{"A":'1 mol', "B":'2 mol', "C":'0.5 mol', "D":'4 mol'},"answer":'B'},
{"id":98,"subject":'Chemistry',"topic":'Stoichiometry',"difficulty":'Hard',
 "question":'A 500 mL solution contains 0.25 mole of NaCl. What is the molarity of this solution?',
 "options":{"A":'0.25 M', "B":'0.125 M', "C":'2 M', "D":'0.5 M'},"answer":'D'},
{"id":99,"subject":'Chemistry',"topic":'Stoichiometry',"difficulty":'Medium',
 "question":'In the balanced equation N2 + 3H2 -> 2NH3, how many moles of NH3 are formed when 3 moles of N2 react completely with excess H2?',
 "options":{"A":'6', "B":'3', "C":'9', "D":'1.5'},"answer":'A'},
{"id":100,"subject":'Chemistry',"topic":'Thermochemistry',"difficulty":'Easy',
 "question":'A reaction that releases heat to its surroundings is classified as:',
 "options":{"A":'Endothermic', "B":'Exothermic', "C":'Isothermal', "D":'Adiabatic'},"answer":'B'},
{"id":101,"subject":'Chemistry',"topic":'Thermochemistry',"difficulty":'Medium',
 "question":'If the energy released when new bonds form in the products exceeds the energy required to break bonds in the reactants, the reaction is:',
 "options":{"A":'Exothermic', "B":'Endothermic', "C":'Always non-spontaneous', "D":'At equilibrium'},"answer":'A'},
{"id":102,"subject":'Chemistry',"topic":'Chemical Equilibrium',"difficulty":'Medium',
 "question":'For the equilibrium N2(g) + 3H2(g) <-> 2NH3(g), increasing the pressure by decreasing volume will shift the equilibrium:',
 "options":{"A":'Toward the reactants', "B":'Not at all', "C":'Completely to the reactant side', "D":'Toward the products, the side with fewer moles of gas'},"answer":'D'},
{"id":103,"subject":'Chemistry',"topic":'Chemical Equilibrium',"difficulty":'Hard',
 "question":'Adding a catalyst to a reversible reaction at equilibrium will:',
 "options":{"A":'Shift the equilibrium toward the reactants', "B":'Shift the equilibrium toward the products', "C":'Change the value of Keq', "D":'Speed up both forward and reverse reactions equally, without shifting the equilibrium position'},"answer":'D'},
{"id":104,"subject":'Chemistry',"topic":'Reaction Kinetics',"difficulty":'Easy',
 "question":'A catalyst increases the rate of a chemical reaction mainly by:',
 "options":{"A":'Providing an alternative pathway with lower activation energy', "B":'Increasing the temperature of the reactants', "C":'Increasing the concentration of reactants', "D":'Being consumed in the reaction'},"answer":'A'},
{"id":105,"subject":'Chemistry',"topic":'Reaction Kinetics',"difficulty":'Medium',
 "question":'A reaction is second order overall with respect to a single reactant. Doubling the concentration of that reactant will:',
 "options":{"A":'Quadruple the rate', "B":'Double the rate', "C":'Have no effect on rate', "D":'Halve the rate'},"answer":'A'},
{"id":106,"subject":'Chemistry',"topic":'Electrochemistry',"difficulty":'Medium',
 "question":'In a galvanic (voltaic) cell, oxidation occurs at the:',
 "options":{"A":'Cathode', "B":'Anode', "C":'Salt bridge', "D":'Voltmeter'},"answer":'B'},
{"id":107,"subject":'Chemistry',"topic":'Electrochemistry',"difficulty":'Hard',
 "question":'In the reaction Zn(s) + CuSO4(aq) -> ZnSO4(aq) + Cu(s), zinc metal acts as the:',
 "options":{"A":'Oxidizing agent', "B":'Catalyst', "C":'Reducing agent', "D":'Neither oxidized nor reduced'},"answer":'C'},
{"id":108,"subject":'Chemistry',"topic":'Acids & Bases',"difficulty":'Easy',
 "question":'A solution with pH = 3 is:',
 "options":{"A":'Strongly basic', "B":'Acidic', "C":'Neutral', "D":'Not chemically possible'},"answer":'B'},
{"id":109,"subject":'Chemistry',"topic":'Acids & Bases',"difficulty":'Medium',
 "question":'A solution has a hydroxide ion concentration [OH-] = 1x10^-5 M. What is its pH (at 25°C)?',
 "options":{"A":'5', "B":'14', "C":'9', "D":'7'},"answer":'C'},
{"id":110,"subject":'Chemistry',"topic":'Acids & Bases',"difficulty":'Medium',
 "question":'The graph shows the change in pH as NaOH solution is gradually added to 25 mL of HCl solution. Based on the curve, what is the approximate volume of NaOH required to reach the equivalence point?',
 "image":'images/q4_titration_curve_naoh_hcl.png',
 "options":{"A":'15 mL', "B":'35 mL', "C":'50 mL', "D":'25 mL'},"answer":'D'},
{"id":111,"subject":'Chemistry',"topic":'Acids & Bases',"difficulty":'Hard',
 "question":'A buffer made of ammonia (NH3) and ammonium chloride (NH4Cl) resists changes in pH mainly because:',
 "options":{"A":'It contains only a strong base', "B":'Added H+ reacts with NH3, and added OH- reacts with NH4+, minimizing pH change', "C":'NH4Cl behaves as a strong acid only', "D":'The solution has no chemical equilibrium'},"answer":'B'},
{"id":112,"subject":'Chemistry',"topic":'Organic Chemistry',"difficulty":'Easy',
 "question":'The general formula CnH2n+2 most directly corresponds to the:',
 "options":{"A":'Alkene series', "B":'Alkane series', "C":'Alkyne series', "D":'Aromatic series'},"answer":'B'},
{"id":113,"subject":'Chemistry',"topic":'Organic Chemistry',"difficulty":'Medium',
 "question":'Carboxylic acids and esters both contain a carbonyl group; they differ mainly in that:',
 "options":{"A":'Esters contain an -OH directly bonded to the carbonyl carbon, while carboxylic acids do not', "B":'Esters are never derived from carboxylic acids', "C":'Carboxylic acids contain no oxygen atoms', "D":'Carboxylic acids have an -OH group bonded to the carbonyl carbon, while esters have an -O-R group instead'},"answer":'D'},
{"id":114,"subject":'Chemistry',"topic":'Organic Chemistry',"difficulty":'Medium',
 "question":'The functional group -COOH attached to a carbon chain characterizes a class of compounds called:',
 "options":{"A":'Carboxylic acids', "B":'Alcohols', "C":'Aldehydes', "D":'Ethers'},"answer":'A'},
{"id":115,"subject":'Chemistry',"topic":'Organic Chemistry',"difficulty":'Hard',
 "question":'In an SN2 reaction, the nucleophile attacks the substrate:',
 "options":{"A":'From the side opposite the leaving group, in a single concerted step', "B":'After the leaving group has already departed, forming a carbocation', "C":'From the same side as the leaving group', "D":'Only after the substrate has fully ionized'},"answer":'A'},
{"id":116,"subject":'Chemistry',"topic":'Organic Chemistry',"difficulty":'Medium',
 "question":'The reaction of an alcohol with a carboxylic acid to form an ester and water is called:',
 "options":{"A":'Esterification', "B":'Hydrolysis', "C":'Saponification', "D":'Polymerization'},"answer":'A'},
{"id":117,"subject":'Chemistry',"topic":'Organic Chemistry',"difficulty":'Easy',
 "question":'Geometric (cis-trans) isomers arise due to restricted rotation around a:',
 "options":{"A":'Double bond', "B":'Single bond', "C":'Ionic bond', "D":'Hydrogen bond'},"answer":'A'},
{"id":118,"subject":'Chemistry',"topic":'Inorganic Chemistry',"difficulty":'Medium',
 "question":'Transition metals commonly form colored compounds mainly because of:',
 "options":{"A":'Complete absence of d electrons', "B":'Their large atomic radius', "C":'Electron transitions between partially filled d orbitals, which absorb specific wavelengths of visible light', "D":'Their low melting points'},"answer":'C'},
{"id":119,"subject":'Chemistry',"topic":'Inorganic Chemistry',"difficulty":'Medium',
 "question":'Among the halogens, reactivity generally decreases going down the group mainly because:',
 "options":{"A":'Electronegativity increases down the group', "B":'Atomic radius increases, weakening the attraction for an additional electron', "C":'Atomic radius decreases down the group', "D":'Halogens become more metallic'},"answer":'B'},
{"id":120,"subject":'Chemistry',"topic":'Inorganic Chemistry',"difficulty":'Hard',
 "question":"In the reaction Zn + 2HCl -> ZnCl2 + H2, zinc's oxidation state changes from:",
 "options":{"A":'+2 to 0 (reduction)', "B":'0 to -2', "C":'No change occurs', "D":'0 to +2 (oxidation)'},"answer":'D'},
{"id":121,"subject":'Chemistry',"topic":'Physical Chemistry',"difficulty":'Medium',
 "question":'Molality of a solution is defined as:',
 "options":{"A":'Moles of solute per liter of solution', "B":'Equivalents of solute per liter of solution', "C":'Grams of solute per liter of solution', "D":'Moles of solute per kilogram of solvent'},"answer":'D'},
{"id":122,"subject":'Chemistry',"topic":'Physical Chemistry',"difficulty":'Hard',
 "question":'20 mL of 0.5 M HCl is required to exactly neutralize 40 mL of NaOH solution (HCl + NaOH -> NaCl + H2O). What is the molarity of the NaOH solution?',
 "options":{"A":'0.1 M', "B":'0.25 M', "C":'0.5 M', "D":'1.0 M'},"answer":'B'},
{"id":123,"subject":'Chemistry',"topic":'Environmental Chemistry',"difficulty":'Easy',
 "question":'Which gas in the upper atmosphere absorbs harmful ultraviolet radiation from the sun?',
 "options":{"A":'Carbon dioxide', "B":'Ozone', "C":'Nitrogen', "D":'Methane'},"answer":'B'},
{"id":124,"subject":'Chemistry',"topic":'Environmental Chemistry',"difficulty":'Medium',
 "question":'Acid rain is primarily caused by atmospheric pollutants such as sulfur dioxide and nitrogen oxides reacting with:',
 "options":{"A":'Oxygen to form ozone', "B":'Carbon dioxide to form carbonic acid only', "C":'Water vapor to form sulfuric and nitric acids', "D":'Nitrogen to form ammonia'},"answer":'C'},
{"id":125,"subject":'Chemistry',"topic":'Chemical Bonding',"difficulty":'Easy',
 "question":'A double covalent bond between two atoms involves the sharing of:',
 "options":{"A":'One pair of electrons', "B":'Three pairs of electrons', "C":'Four pairs of electrons', "D":'Two pairs of electrons'},"answer":'D'},
{"id":126,"subject":'Chemistry',"topic":'Atomic Structure',"difficulty":'Easy',
 "question":'Isotopes of the same element differ in their number of:',
 "options":{"A":'Neutrons', "B":'Protons', "C":'Electrons', "D":'Valence electrons'},"answer":'A'},

# ============================================================
# PHYSICS (36 questions) - id 127-162
# ============================================================
{"id":127,"subject":'Physics',"topic":'Kinematics',"difficulty":'Easy',
 "question":"A runner covers 400 m in 50 seconds at constant velocity. What is the runner's speed?",
 "options":{"A":'4 m/s', "B":'20 m/s', "C":'8 m/s', "D":'450 m/s'},"answer":'C'},
{"id":128,"subject":'Physics',"topic":'Kinematics',"difficulty":'Medium',
 "question":'A car accelerates uniformly from rest to 20 m/s in 4 seconds. What is its acceleration?',
 "options":{"A":'80 m/s^2', "B":'4 m/s^2', "C":'0.2 m/s^2', "D":'5 m/s^2'},"answer":'D'},
{"id":129,"subject":'Physics',"topic":'Kinematics',"difficulty":'Hard',
 "question":'A ball is dropped from rest from a height of 80 m (g = 10 m/s^2, ignoring air resistance). How long does it take to hit the ground?',
 "options":{"A":'8 s', "B":'16 s', "C":'4 s', "D":'2 s'},"answer":'C'},
{"id":130,"subject":'Physics',"topic":'Dynamics',"difficulty":'Easy',
 "question":"According to Newton's first law, an object in motion will continue at constant velocity unless acted upon by:",
 "options":{"A":'Its own mass', "B":'Time alone', "C":'A net external force', "D":'Its own inertia'},"answer":'C'},
{"id":131,"subject":'Physics',"topic":'Dynamics',"difficulty":'Medium',
 "question":'A 5 kg object accelerates at 3 m/s^2 due to an applied net force. What is the magnitude of this force?',
 "options":{"A":'1.67 N', "B":'8 N', "C":'2 N', "D":'15 N'},"answer":'D'},
{"id":132,"subject":'Physics',"topic":'Dynamics',"difficulty":'Medium',
 "question":"Newton's third law states that when object A exerts a force on object B, object B:",
 "options":{"A":'Exerts an equal and opposite force on A', "B":'Exerts no force on A', "C":'Exerts a force twice as large on A', "D":'Remains completely stationary'},"answer":'A'},
{"id":133,"subject":'Physics',"topic":'Dynamics',"difficulty":'Hard',
 "question":"A 5 kg block is pushed horizontally with a 40 N force across a surface with a coefficient of kinetic friction of 0.2 (g = 10 m/s^2). What is the block's acceleration?",
 "options":{"A":'8 m/s^2', "B":'4 m/s^2', "C":'6 m/s^2', "D":'2 m/s^2'},"answer":'C'},
{"id":134,"subject":'Physics',"topic":'Work, Energy & Power',"difficulty":'Easy',
 "question":'The SI unit of work and energy is the:',
 "options":{"A":'Watt', "B":'Joule', "C":'Newton', "D":'Pascal'},"answer":'B'},
{"id":135,"subject":'Physics',"topic":'Work, Energy & Power',"difficulty":'Medium',
 "question":'A 4 kg object is raised to a height of 5 m (g = 10 m/s^2). What is its gravitational potential energy at that height?',
 "options":{"A":'20 J', "B":'50 J', "C":'400 J', "D":'200 J'},"answer":'D'},
{"id":136,"subject":'Physics',"topic":'Work, Energy & Power',"difficulty":'Medium',
 "question":'A 2 kg object moving at 5 m/s has a kinetic energy of:',
 "options":{"A":'10 J', "B":'25 J', "C":'50 J', "D":'5 J'},"answer":'B'},
{"id":137,"subject":'Physics',"topic":'Work, Energy & Power',"difficulty":'Hard',
 "question":'A motor lifts a 200 kg load to a height of 6 m in 4 seconds (g = 10 m/s^2). What is the power output of the motor?',
 "options":{"A":'300 W', "B":'1200 W', "C":'12000 W', "D":'3000 W'},"answer":'D'},
{"id":138,"subject":'Physics',"topic":'Circular Motion & Gravitation',"difficulty":'Easy',
 "question":'For an object moving in a circle at constant speed, the direction of its velocity is:',
 "options":{"A":'Continuously changing, always tangent to the circle', "B":'Constant throughout the motion', "C":'Always toward the center', "D":'Always away from the center'},"answer":'A'},
{"id":139,"subject":'Physics',"topic":'Circular Motion & Gravitation',"difficulty":'Medium',
 "question":'If the distance between two masses is tripled while both masses stay the same, the gravitational force between them becomes:',
 "options":{"A":'Three times as large', "B":'One third as large', "C":'Nine times as large', "D":'One ninth as large'},"answer":'D'},
{"id":140,"subject":'Physics',"topic":'Circular Motion & Gravitation',"difficulty":'Hard',
 "question":'An astronaut experiences apparent weightlessness while orbiting Earth in the International Space Station mainly because:',
 "options":{"A":'There is no gravity at that altitude', "B":'The station blocks all gravitational force', "C":'The astronaut and the station are both in continuous free fall around Earth', "D":'The astronaut has zero mass in orbit'},"answer":'C'},
{"id":141,"subject":'Physics',"topic":'Fluid Mechanics',"difficulty":'Easy',
 "question":'Atmospheric pressure is typically measured using a:',
 "options":{"A":'Thermometer', "B":'Voltmeter', "C":'Ammeter', "D":'Barometer'},"answer":'D'},
{"id":142,"subject":'Physics',"topic":'Fluid Mechanics',"difficulty":'Medium',
 "question":'A ship made of steel floats on water mainly because:',
 "options":{"A":'Steel is less dense than water', "B":'It has no weight', "C":'Its overall shape displaces enough water that the buoyant force equals its weight', "D":'Water has no buoyant force'},"answer":'C'},
{"id":143,"subject":'Physics',"topic":'Fluid Mechanics',"difficulty":'Hard',
 "question":"According to Bernoulli's principle, as the speed of a flowing fluid increases, the pressure within the fluid:",
 "options":{"A":'Decreases', "B":'Increases', "C":'Remains unchanged', "D":'Becomes negative'},"answer":'A'},
{"id":144,"subject":'Physics',"topic":'Oscillations & Waves',"difficulty":'Easy',
 "question":"The number of complete oscillations or wave cycles occurring per second is called the wave's:",
 "options":{"A":'Wavelength', "B":'Frequency', "C":'Amplitude', "D":'Period'},"answer":'B'},
{"id":145,"subject":'Physics',"topic":'Oscillations & Waves',"difficulty":'Medium',
 "question":"A simple pendulum's period depends on its length and:",
 "options":{"A":'The mass of the bob', "B":'The amplitude of swing only', "C":'The local acceleration due to gravity', "D":'The material of the string'},"answer":'C'},
{"id":146,"subject":'Physics',"topic":'Oscillations & Waves',"difficulty":'Medium',
 "question":'A wave has a frequency of 25 Hz. What is its period?',
 "options":{"A":'25 s', "B":'4 s', "C":'0.25 s', "D":'0.04 s'},"answer":'D'},
{"id":147,"subject":'Physics',"topic":'Oscillations & Waves',"difficulty":'Hard',
 "question":'In a transverse wave, particles of the medium vibrate:',
 "options":{"A":'Perpendicular to the direction of wave travel', "B":'Parallel to the direction of wave travel', "C":'They do not vibrate at all', "D":'In circles around a fixed point'},"answer":'A'},
{"id":148,"subject":'Physics',"topic":'Thermodynamics',"difficulty":'Easy',
 "question":'Temperature is best described as a measure of:',
 "options":{"A":'The total heat energy in an object', "B":'The total mass of a substance', "C":'The pressure exerted by a substance', "D":'The average kinetic energy of the particles in a substance'},"answer":'D'},
{"id":149,"subject":'Physics',"topic":'Thermodynamics',"difficulty":'Medium',
 "question":'According to the first law of thermodynamics, the change in internal energy of a system equals:',
 "options":{"A":'Heat added plus work done by the system only', "B":'Work done alone, regardless of heat', "C":'Heat added minus work done by the system', "D":'Zero for any closed system'},"answer":'C'},
{"id":150,"subject":'Physics',"topic":'Thermodynamics',"difficulty":'Hard',
 "question":'A gas is compressed, and 200 J of work is done on it, while it releases 150 J of heat to its surroundings. What is the change in internal energy of the gas?',
 "options":{"A":'350 J', "B":'50 J', "C":'-50 J', "D":'-350 J'},"answer":'B'},
{"id":151,"subject":'Physics',"topic":'Electrostatics',"difficulty":'Easy',
 "question":'An object that has lost electrons becomes:',
 "options":{"A":'Negatively charged', "B":'Electrically neutral', "C":'Positively charged', "D":'Non-conductive'},"answer":'C'},
{"id":152,"subject":'Physics',"topic":'Electrostatics',"difficulty":'Medium',
 "question":"According to Coulomb's law, if the distance between two point charges is doubled, the electrostatic force between them becomes:",
 "options":{"A":'Twice as large', "B":'One quarter as large', "C":'Four times as large', "D":'One half as large'},"answer":'B'},
{"id":153,"subject":'Physics',"topic":'Current Electricity',"difficulty":'Easy',
 "question":'Electric current is measured in units of:',
 "options":{"A":'Amperes', "B":'Volts', "C":'Ohms', "D":'Watts'},"answer":'A'},
{"id":154,"subject":'Physics',"topic":'Current Electricity',"difficulty":'Medium',
 "question":'In the circuit shown, R1 (3 ohm) and R2 (3 ohm) are connected in parallel, and this parallel combination is connected in series with R3 (2 ohm). What is the total resistance of the circuit?',
 "image":'images/q4_circuit_diagram_r1r2r3.png',
 "options":{"A":'8 ohm', "B":'1.5 ohm', "C":'3.5 ohm', "D":'6 ohm'},"answer":'C'},
{"id":155,"subject":'Physics',"topic":'Current Electricity',"difficulty":'Hard',
 "question":'Two resistors of 8 ohm each are connected in parallel. What is their equivalent resistance?',
 "options":{"A":'16 ohm', "B":'8 ohm', "C":'4 ohm', "D":'2 ohm'},"answer":'C'},
{"id":156,"subject":'Physics',"topic":'Current Electricity',"difficulty":'Medium',
 "question":'A device operates at 220 V and draws a current of 2 A. What is its power consumption?',
 "options":{"A":'110 W', "B":'222 W', "C":'440 W', "D":'880 W'},"answer":'C'},
{"id":157,"subject":'Physics',"topic":'Electromagnetism',"difficulty":'Medium',
 "question":'According to the right-hand rule, if current flows upward through a straight wire, the magnetic field lines around the wire form:',
 "options":{"A":'Circles in a plane perpendicular to the wire, following the curl of the right hand', "B":'Straight lines pointing upward', "C":'No field at all', "D":'A field pointing directly opposite to the current'},"answer":'A'},
{"id":158,"subject":'Physics',"topic":'Electromagnetism',"difficulty":'Hard',
 "question":'Increasing the current through a solenoid, while keeping the number of turns constant, will:',
 "options":{"A":'Increase the magnetic field strength produced', "B":'Decrease the magnetic field strength produced', "C":'Have no effect on the field', "D":"Reverse the field's direction without changing strength"},"answer":'A'},
{"id":159,"subject":'Physics',"topic":'Modern Physics',"difficulty":'Easy',
 "question":'The mass number of an atom represents the total number of:',
 "options":{"A":'Protons only', "B":'Neutrons only', "C":'Electrons only', "D":'Protons and neutrons combined'},"answer":'D'},
{"id":160,"subject":'Physics',"topic":'Modern Physics',"difficulty":'Medium',
 "question":'During beta decay, a nucleus emits:',
 "options":{"A":'A helium nucleus', "B":'High-energy electromagnetic radiation only', "C":'An electron, as a neutron converts to a proton', "D":'A proton'},"answer":'C'},
{"id":161,"subject":'Physics',"topic":'Modern Physics',"difficulty":'Hard',
 "question":'A radioactive sample has a half-life of 4 hours. Starting with 200 g, how much remains after 12 hours?',
 "options":{"A":'25 g', "B":'100 g', "C":'50 g', "D":'12.5 g'},"answer":'A'},
{"id":162,"subject":'Physics',"topic":'Optics',"difficulty":'Medium',
 "question":'The ray diagram shows an object placed beyond twice the focal length (2F) of a converging (convex) lens. Based on the diagram, the image formed on the opposite side of the lens is:',
 "image":'images/q4_lens_diagram_object_beyond_2f.png',
 "options":{"A":'Real, upright, and magnified', "B":'Real, inverted, and diminished', "C":'Virtual, upright, and magnified', "D":'Virtual, inverted, and diminished'},"answer":'B'},

# ============================================================
# ENGLISH (9 questions) - id 163-171
# ============================================================
{"id":163,"subject":'English',"topic":'Synonyms',"difficulty":'Easy',
 "question":"Choose the word most nearly similar in meaning to 'BENEVOLENT':",
 "options":{"A":'Cruel', "B":'Kind', "C":'Indifferent', "D":'Greedy'},"answer":'B'},
{"id":164,"subject":'English',"topic":'Antonyms',"difficulty":'Easy',
 "question":"Choose the word most nearly opposite in meaning to 'ABUNDANT':",
 "options":{"A":'Plentiful', "B":'Numerous', "C":'Scarce', "D":'Generous'},"answer":'C'},
{"id":165,"subject":'English',"topic":'Grammar',"difficulty":'Easy',
 "question":'Choose the grammatically correct sentence:',
 "options":{"A":'Neither of the boys has finished his homework.', "B":'Neither of the boys have finished their homework.', "C":'Neither of the boy has finished his homework.', "D":'Neither of the boys have finished his homework.'},"answer":'A'},
{"id":166,"subject":'English',"topic":'Grammar',"difficulty":'Medium',
 "question":'Choose the correct sentence:',
 "options":{"A":'By the time we arrive, the movie will start.', "B":'By the time we arrive, the movie starts.', "C":'By the time we arrive, the movie will have started.', "D":'By the time we arrive, the movie is starting.'},"answer":'C'},
{"id":167,"subject":'English',"topic":'Sentence Correction',"difficulty":'Medium',
 "question":'Identify the sentence that follows correct subject-verb agreement:',
 "options":{"A":'Neither the manager nor the employees was informed.', "B":'Neither the managers nor the employee were informed.', "C":'Neither the manager nor the employees were informed.', "D":'Neither the manager nor employees was informed.'},"answer":'C'},
{"id":168,"subject":'English',"topic":'Vocabulary',"difficulty":'Medium',
 "question":"Choose the word that best completes the sentence: 'Despite the heavy rain, the team remained ______ and completed the project on time.'",
 "options":{"A":'Reluctant', "B":'Careless', "C":'Indifferent', "D":'Diligent'},"answer":'D'},
{"id":169,"subject":'English',"topic":'Idioms',"difficulty":'Medium',
 "question":"Choose the meaning closest to the idiom 'to bite the bullet':",
 "options":{"A":'To avoid a problem entirely', "B":'To face a difficult situation with courage', "C":'To celebrate a victory', "D":'To break a promise'},"answer":'B'},
{"id":170,"subject":'English',"topic":'Sentence Correction',"difficulty":'Hard',
 "question":"Choose the option that best corrects the sentence: 'Neither of the students were prepared for their exam.'",
 "options":{"A":'Neither of the students were prepared for their exam.', "B":'Neither of the student were prepared for his exam.', "C":'Neither of the students were prepared for his or her exam.', "D":'Neither of the students was prepared for his or her exam.'},"answer":'D'},
{"id":171,"subject":'English',"topic":'Prepositions',"difficulty":'Hard',
 "question":"Choose the correct preposition to complete the sentence: 'The committee is responsible ______ reviewing all applications.'",
 "options":{"A":'on', "B":'at', "C":'with', "D":'for'},"answer":'D'},

# ============================================================
# LOGICAL REASONING (9 questions) - id 172-180
# ============================================================
{"id":172,"subject":'Logical Reasoning',"topic":'Number Series',"difficulty":'Easy',
 "question":'Find the next number in the series: 3, 6, 12, 24, ?',
 "options":{"A":'30', "B":'48', "C":'36', "D":'42'},"answer":'B'},
{"id":173,"subject":'Logical Reasoning',"topic":'Number Series',"difficulty":'Easy',
 "question":'Find the missing number: 4, 9, 14, 19, ?',
 "options":{"A":'24', "B":'22', "C":'23', "D":'25'},"answer":'A'},
{"id":174,"subject":'Logical Reasoning',"topic":'Analogies',"difficulty":'Easy',
 "question":'Painter is to Canvas as Sculptor is to:',
 "options":{"A":'Marble', "B":'Brush', "C":'Chisel', "D":'Museum'},"answer":'A'},
{"id":175,"subject":'Logical Reasoning',"topic":'Analogies',"difficulty":'Medium',
 "question":'Doctor is to Hospital as Teacher is to:',
 "options":{"A":'Classroom', "B":'Student', "C":'Book', "D":'Exam'},"answer":'A'},
{"id":176,"subject":'Logical Reasoning',"topic":'Blood Relations',"difficulty":'Medium',
 "question":"Pointing to a woman, Ahmed said, 'She is the daughter of my mother's only son.' If Ahmed has no brothers, how is the woman related to Ahmed?",
 "options":{"A":'Sister', "B":'Daughter', "C":'Niece', "D":'Cousin'},"answer":'B'},
{"id":177,"subject":'Logical Reasoning',"topic":'Coding-Decoding',"difficulty":'Medium',
 "question":'If in a certain code, BOOK is written as CPPL, how is DOOR written in the same code?',
 "options":{"A":'EPPS', "B":'EQQS', "C":'DPPS', "D":'EPQS'},"answer":'A'},
{"id":178,"subject":'Logical Reasoning',"topic":'Syllogism',"difficulty":'Hard',
 "question":'All doctors are graduates. All graduates have studied for years. Which conclusion logically follows?',
 "options":{"A":'All graduates are doctors', "B":'All doctors have studied for years', "C":'No doctors have studied for years', "D":'Some graduates are not doctors'},"answer":'B'},
{"id":179,"subject":'Logical Reasoning',"topic":'Pattern Recognition',"difficulty":'Hard',
 "question":'Find the next term in the series: 2, 3, 5, 8, 12, ?',
 "options":{"A":'17', "B":'15', "C":'16', "D":'18'},"answer":'A'},
{"id":180,"subject":'Logical Reasoning',"topic":'Direction Sense',"difficulty":'Medium',
 "question":'A girl walks 5 km north, then turns right and walks 12 km. How far is she from her starting point?',
 "options":{"A":'17 km', "B":'7 km', "C":'5 km', "D":'13 km'},"answer":'D'},

]


# ------------------------------------------------------------
# Sanity-check / summary utility
# ------------------------------------------------------------
def summarize(questions):
    from collections import Counter
    subj = Counter(q["subject"] for q in questions)
    diff = Counter(q["difficulty"] for q in questions)
    ans = Counter(q["answer"] for q in questions)
    ids = [q["id"] for q in questions]
    dup_ids = [i for i in set(ids) if ids.count(i) > 1]
    dup_q = [q["question"] for q in questions]
    dup_questions = [t for t in set(dup_q) if dup_q.count(t) > 1]
    images = [q for q in questions if "image" in q]

    print(f"Total questions: {len(questions)}")
    print("\nBy subject:")
    for s, c in subj.items():
        print(f"  {s}: {c}")
    print("\nBy difficulty:")
    for d, c in diff.items():
        print(f"  {d}: {c}")
    print("\nBy correct-answer letter (should be roughly balanced):")
    for L in ["A", "B", "C", "D"]:
        print(f"  {L}: {ans[L]}")
    print(f"\nDuplicate IDs: {dup_ids if dup_ids else 'None'}")
    print(f"Duplicate question text: {dup_questions if dup_questions else 'None'}")
    print(f"\nImage-based questions ({len(images)}):")
    for q in images:
        print(f"  Q{q['id']} [{q['subject']}] -> {q['image']}")

    for q in questions:
        assert set(q["options"].keys()) == {"A", "B", "C", "D"}, f"Q{q['id']} missing an option"
        assert q["answer"] in q["options"], f"Q{q['id']} answer key invalid"
    print("\nAll questions have exactly 4 options (A-D) and a valid answer key. OK.")


def print_answer_key(questions):
    print("\nANSWER KEY")
    print("-" * 40)
    for q in questions:
        print(f"{q['id']:>3}. {q['answer']}", end="   ")
        if q["id"] % 10 == 0:
            print()
    print()


if __name__ == "__main__":
    summarize(QUESTIONS)
    print_answer_key(QUESTIONS)