"""
MDCAT Mock Test 13
===================
Full-length mock test: 180 MCQs
Weightage: Biology 81 | Chemistry 45 | Physics 36 | English 9 | Logical Reasoning 9
Difficulty mix (approx): 30% Easy / 50% Medium / 20% Hard, distributed throughout.

Includes 5 image/diagram-based questions (2 Biology, 1 Chemistry, 2 Physics).
Each such question has an "image" key giving a relative path to a PNG diagram
that must be viewed alongside the question (images/ subfolder, shipped alongside
this file). Diagrams: a bar graph of enzyme activity with different metal-ion
cofactors, labeled plant-cell structure (chloroplast), a weak-base/strong-acid
titration curve, a series-then-parallel resistor circuit, and a plane-mirror
ray diagram.

Each question is a dict:
    id, subject, topic, difficulty, question, [image], options (A-D), answer (correct letter)

Run this file directly to print a summary / sanity-check the paper.
"""

QUESTIONS = [
# ============================================================
# BIOLOGY (81 questions) - id 1-81
# ============================================================
{"id":1,"subject":'Biology',"topic":'Biomolecules',"difficulty":'Easy',
 "question":'Which of the following biomolecules is primarily responsible for catalyzing biochemical reactions in cells?',
 "options":{"A":'Carbohydrates', "B":'Lipids', "C":'Proteins (enzymes)', "D":'Nucleic acids'},"answer":'C'},
{"id":2,"subject":'Biology',"topic":'Biomolecules',"difficulty":'Easy',
 "question":'Cellulose, a structural polysaccharide found in plant cell walls, is composed of repeating units of:',
 "options":{"A":'Glucose', "B":'Fructose', "C":'Galactose', "D":'Ribose'},"answer":'A'},
{"id":3,"subject":'Biology',"topic":'Biomolecules',"difficulty":'Medium',
 "question":'Which level of protein structure specifically refers to local folding patterns such as alpha helices and beta pleated sheets?',
 "options":{"A":'Secondary structure', "B":'Primary structure', "C":'Tertiary structure', "D":'Quaternary structure'},"answer":'A'},
{"id":4,"subject":'Biology',"topic":'Biomolecules',"difficulty":'Medium',
 "question":'Phospholipids differ from triglycerides mainly in that phospholipids:',
 "options":{"A":'Contain no fatty acids at all', "B":'Are entirely hydrophobic', "C":'Contain only glycerol and no other components', "D":'Have a phosphate group replacing one fatty acid, giving the molecule both hydrophilic and hydrophobic regions'},"answer":'D'},
{"id":5,"subject":'Biology',"topic":'Biomolecules',"difficulty":'Hard',
 "question":'Which of the following best explains why enzymes generally lose function when exposed to extreme pH?',
 "options":{"A":"Changes in pH disrupt ionic and hydrogen bonds maintaining the protein's three-dimensional shape, denaturing the enzyme", "B":'Extreme pH has no effect on protein structure', "C":'Extreme pH always increases enzyme activity', "D":'pH only affects carbohydrates, not proteins'},"answer":'A'},
{"id":6,"subject":'Biology',"topic":'Enzymes',"difficulty":'Easy',
 "question":'The specific region of an enzyme that binds to a cofactor or coenzyme, distinct from the active site, is called the:',
 "options":{"A":'Allosteric site', "B":'Substrate site', "C":'Product site', "D":'Regulatory (or binding) site'},"answer":'D'},
{"id":7,"subject":'Biology',"topic":'Enzymes',"difficulty":'Medium',
 "question":'Increasing substrate concentration while keeping enzyme concentration constant will increase reaction rate until:',
 "options":{"A":'All enzyme active sites become saturated with substrate, after which the rate plateaus', "B":'The enzyme is completely destroyed', "C":'The temperature drops to zero', "D":'The pH becomes neutral'},"answer":'A'},
{"id":8,"subject":'Biology',"topic":'Enzymes',"difficulty":'Medium',
 "question":'The bar graph shows the relative activity of an enzyme in three test tubes, each supplied with a different metal ion as a potential cofactor. Tube 2 (with Mg2+) shows significantly higher activity than Tubes 1 and 3. This result suggests that:',
 "image":'images/q13_enzyme_cofactor_bar_graph.png',
 "options":{"A":'All metal ions equally activate the enzyme', "B":'The enzyme requires Mg2+ specifically as a cofactor for optimal activity', "C":'The enzyme does not require any cofactor', "D":'Metal ions always inhibit enzyme activity'},"answer":'B'},
{"id":9,"subject":'Biology',"topic":'Enzymes',"difficulty":'Hard',
 "question":'Irreversible enzyme inhibitors typically act by:',
 "options":{"A":'Binding temporarily and being easily displaced by substrate', "B":'Forming a stable, often covalent bond with the enzyme, permanently inactivating it', "C":"Increasing the enzyme's affinity for substrate", "D":'Only functioning at high temperatures'},"answer":'B'},
{"id":10,"subject":'Biology',"topic":'Cell Biology',"difficulty":'Easy',
 "question":'Which structure is responsible for regulating what enters and exits the nucleus?',
 "options":{"A":'Nucleolus', "B":'Chromatin', "C":'Nuclear pores', "D":'Nuclear membrane lipids alone'},"answer":'C'},
{"id":11,"subject":'Biology',"topic":'Cell Biology',"difficulty":'Easy',
 "question":'The cytoskeleton is composed of three main types of protein filaments: microtubules, microfilaments, and:',
 "options":{"A":'Ribosomal filaments', "B":'Intermediate filaments', "C":'Nuclear filaments', "D":'Golgi filaments'},"answer":'B'},
{"id":12,"subject":'Biology',"topic":'Cell Biology',"difficulty":'Medium',
 "question":'Which organelle would be present in the greatest abundance in a highly active muscle cell, given its high energy demand?',
 "options":{"A":'Mitochondrion', "B":'Lysosome', "C":'Golgi apparatus', "D":'Peroxisome'},"answer":'A'},
{"id":13,"subject":'Biology',"topic":'Cell Biology',"difficulty":'Medium',
 "question":'Cilia and flagella share a common internal structure known as the:',
 "options":{"A":'Actin filament bundle only', "B":'Nuclear lamina', "C":'9+2 arrangement of microtubules', "D":'Intermediate filament network'},"answer":'C'},
{"id":14,"subject":'Biology',"topic":'Cell Biology',"difficulty":'Medium',
 "question":'The diagram shows a plant cell with structures labeled A, B, C, and D. Structure C is a double-membraned organelle containing stacked membranous structures (grana) where light-dependent reactions occur. Which structure is C?',
 "image":'images/q13_plant_cell_diagram_abcd.png',
 "options":{"A":'Structure C (chloroplast)', "B":'Structure A (mitochondrion)', "C":'Structure B (nucleus)', "D":'Structure D (vacuole)'},"answer":'A'},
{"id":15,"subject":'Biology',"topic":'Cell Biology',"difficulty":'Medium',
 "question":'The endoplasmic reticulum is continuous with which other cellular structure?',
 "options":{"A":'The outer nuclear membrane', "B":'The cell wall', "C":'The plasma membrane exclusively', "D":'The mitochondrial membrane'},"answer":'A'},
{"id":16,"subject":'Biology',"topic":'Cell Biology',"difficulty":'Hard',
 "question":'A cell that has lost the ability to form microtubules would experience the greatest difficulty with:',
 "options":{"A":'Chromosome segregation during cell division and intracellular transport', "B":'DNA transcription', "C":'Ribosomal protein synthesis', "D":'Fatty acid synthesis'},"answer":'A'},
{"id":17,"subject":'Biology',"topic":'Cell Membrane & Transport',"difficulty":'Easy',
 "question":"The plasma membrane is described as 'selectively permeable' because it:",
 "options":{"A":'Allows all substances to pass through freely', "B":'Blocks all substances completely', "C":'Allows some substances to pass through more easily than others', "D":'Is permeable only to water'},"answer":'C'},
{"id":18,"subject":'Biology',"topic":'Cell Membrane & Transport',"difficulty":'Medium',
 "question":'A solution that causes a cell to neither gain nor lose water is described as:',
 "options":{"A":'Hypertonic', "B":'Hypotonic', "C":'Non-polar', "D":'Isotonic'},"answer":'D'},
{"id":19,"subject":'Biology',"topic":'Cell Membrane & Transport',"difficulty":'Medium',
 "question":'Receptor-mediated endocytosis differs from simple endocytosis in that it:',
 "options":{"A":'Involves specific receptor proteins on the membrane surface that bind particular molecules before internalization', "B":'Involves no membrane proteins', "C":'Only occurs in prokaryotic cells', "D":'Requires no energy at all'},"answer":'A'},
{"id":20,"subject":'Biology',"topic":'Cell Membrane & Transport',"difficulty":'Hard',
 "question":'The sodium-potassium pump is classified as a primary active transport mechanism because it:',
 "options":{"A":'Directly uses the energy from ATP hydrolysis to move ions against their concentration gradients', "B":'Uses only the concentration gradient of another ion for energy', "C":'Moves ions down their concentration gradient', "D":'Requires no energy input at all'},"answer":'A'},
{"id":21,"subject":'Biology',"topic":'Cell Membrane & Transport',"difficulty":'Easy',
 "question":'Which of the following molecules can typically cross the plasma membrane by simple diffusion without the help of a transport protein?',
 "options":{"A":'Glucose', "B":'Small nonpolar molecules like oxygen and carbon dioxide', "C":'Sodium ions', "D":'Large proteins'},"answer":'B'},
{"id":22,"subject":'Biology',"topic":'Cell Cycle & Division',"difficulty":'Easy',
 "question":'The process by which the cytoplasm divides to form two separate daughter cells following mitosis is called:',
 "options":{"A":'Prophase', "B":'Interphase', "C":'Cytokinesis', "D":'Karyokinesis only'},"answer":'C'},
{"id":23,"subject":'Biology',"topic":'Cell Cycle & Division',"difficulty":'Easy',
 "question":'During anaphase of mitosis, the centromeres split and:',
 "options":{"A":'Chromosomes align at the metaphase plate', "B":'Sister chromatids separate and move toward opposite poles', "C":'The nuclear envelope reforms', "D":'Chromatin begins to condense'},"answer":'B'},
{"id":24,"subject":'Biology',"topic":'Cell Cycle & Division',"difficulty":'Medium',
 "question":'Which statement correctly compares the number of divisions in mitosis versus meiosis?',
 "options":{"A":'Mitosis involves two divisions, meiosis involves one', "B":'Both involve exactly two divisions', "C":'Mitosis involves one division, meiosis involves two divisions', "D":'Neither involves cell division'},"answer":'C'},
{"id":25,"subject":'Biology',"topic":'Cell Cycle & Division',"difficulty":'Medium',
 "question":'A cell with a diploid number of 12 undergoes mitosis. How many chromosomes will be present in each daughter cell?',
 "options":{"A":'6', "B":'12', "C":'24', "D":'3'},"answer":'B'},
{"id":26,"subject":'Biology',"topic":'Cell Cycle & Division',"difficulty":'Medium',
 "question":'Random orientation of homologous chromosome pairs at the metaphase I plate, followed by their separation, is a key source of genetic variation known as:',
 "options":{"A":'Crossing over', "B":'Non-disjunction', "C":'Independent assortment', "D":'Mutation'},"answer":'C'},
{"id":27,"subject":'Biology',"topic":'Cell Cycle & Division',"difficulty":'Hard',
 "question":'The G1/S checkpoint of the cell cycle primarily ensures that:',
 "options":{"A":"The cell's DNA is undamaged and conditions are favorable before committing to DNA replication", "B":'Cytokinesis has been completed successfully', "C":'Chromosomes have properly attached to spindle fibers', "D":'The cell has already finished mitosis'},"answer":'A'},
{"id":28,"subject":'Biology',"topic":'Genetics',"difficulty":'Easy',
 "question":'In pea plants, purple flower color (P) is dominant over white (p). A cross between a homozygous purple plant and a homozygous white plant produces offspring that are:',
 "options":{"A":'All white', "B":'All purple (Pp)', "C":'1 purple : 1 white', "D":'All homozygous purple (PP)'},"answer":'B'},
{"id":29,"subject":'Biology',"topic":'Genetics',"difficulty":'Medium',
 "question":'A cross between two heterozygous purple-flowered plants (Pp x Pp) is expected to produce what phenotypic ratio in the offspring?',
 "options":{"A":'1 purple : 1 white', "B":'3 purple : 1 white', "C":'1 purple : 2 intermediate : 1 white', "D":'All purple'},"answer":'B'},
{"id":30,"subject":'Biology',"topic":'Genetics',"difficulty":'Medium',
 "question":'Hemophilia is X-linked recessive. If both parents are unaffected but the mother is a carrier, what proportion of their sons is expected to be affected?',
 "options":{"A":'0%', "B":'25%', "C":'50%', "D":'100%'},"answer":'C'},
{"id":31,"subject":'Biology',"topic":'Genetics',"difficulty":'Hard',
 "question":'In a cross between two individuals heterozygous for a single gene (Aa x Aa), what fraction of offspring is expected to be homozygous (either AA or aa)?',
 "options":{"A":'1/4', "B":'3/4', "C":'1/8', "D":'1/2'},"answer":'D'},
{"id":32,"subject":'Biology',"topic":'Genetics',"difficulty":'Medium',
 "question":'A man with blood type B (heterozygous, IBi) and a woman with blood type A (heterozygous, IAi) have children. Which blood types are possible among their offspring?',
 "options":{"A":'A, B, AB, and O', "B":'Only A and B', "C":'Only AB and O', "D":'Only O'},"answer":'A'},
{"id":33,"subject":'Biology',"topic":'Genetics',"difficulty":'Hard',
 "question":'A pedigree shows an X-linked recessive trait. An affected father and a homozygous unaffected mother will have daughters who are:',
 "options":{"A":'All carriers (unaffected but heterozygous)', "B":'All affected', "C":'All unaffected and non-carriers', "D":'Half affected, half unaffected'},"answer":'A'},
{"id":34,"subject":'Biology',"topic":'Genetics',"difficulty":'Medium',
 "question":'In certain chicken breeds, crossing a black-feathered chicken with a white-feathered chicken produces offspring with a mixture of black and white feathers (not gray), a pattern where both alleles are fully and simultaneously expressed. This is an example of:',
 "options":{"A":'Codominance', "B":'Incomplete dominance', "C":'Epistasis', "D":'Polygenic inheritance'},"answer":'A'},
{"id":35,"subject":'Biology',"topic":'Molecular Biology',"difficulty":'Easy',
 "question":'In the genetic code, each amino acid is specified by a sequence of how many nucleotides?',
 "options":{"A":'Three', "B":'One', "C":'Two', "D":'Four'},"answer":'A'},
{"id":36,"subject":'Biology',"topic":'Molecular Biology',"difficulty":'Easy',
 "question":'The enzyme primarily responsible for synthesizing a new mRNA strand from a DNA template during transcription is:',
 "options":{"A":'DNA polymerase', "B":'Helicase', "C":'RNA polymerase', "D":'Ligase'},"answer":'C'},
{"id":37,"subject":'Biology',"topic":'Molecular Biology',"difficulty":'Medium',
 "question":'Telomerase is an enzyme that helps to:',
 "options":{"A":'Break down damaged DNA', "B":'Splice introns from pre-mRNA', "C":'Unwind the double helix during transcription', "D":'Extend the telomeres at the ends of chromosomes, counteracting their shortening during replication'},"answer":'D'},
{"id":38,"subject":'Biology',"topic":'Molecular Biology',"difficulty":'Medium',
 "question":'During translation, the process of the ribosome moving from one codon to the next along the mRNA is known as:',
 "options":{"A":'Initiation', "B":'Elongation', "C":'Termination', "D":'Splicing'},"answer":'B'},
{"id":39,"subject":'Biology',"topic":'Molecular Biology',"difficulty":'Medium',
 "question":'A mutation that results in the substitution of one amino acid for a different one in the resulting protein is classified as a:',
 "options":{"A":'Silent mutation', "B":'Missense mutation', "C":'Nonsense mutation', "D":'Neutral mutation only'},"answer":'B'},
{"id":40,"subject":'Biology',"topic":'Molecular Biology',"difficulty":'Hard',
 "question":'Which of the following mutations would most likely have the least impact on protein function?',
 "options":{"A":'A frameshift mutation near the beginning of the gene', "B":'A nonsense mutation near the beginning of the gene', "C":'A large deletion spanning most of the gene', "D":'A missense mutation that substitutes a chemically similar amino acid in a non-critical region'},"answer":'D'},
{"id":41,"subject":'Biology',"topic":'Molecular Biology',"difficulty":'Hard',
 "question":'In the lac operon model, the operator sequence functions as the site where:',
 "options":{"A":'RNA polymerase initially binds to begin transcription', "B":'The repressor protein binds, physically blocking RNA polymerase from transcribing the structural genes', "C":'Ribosomes attach to begin translation', "D":'CAP protein always binds regardless of glucose levels'},"answer":'B'},
{"id":42,"subject":'Biology',"topic":'Molecular Biology',"difficulty":'Medium',
 "question":'Which of the following is true regarding the genetic code?',
 "options":{"A":'It is degenerate, meaning most amino acids are specified by more than one codon', "B":'It is highly ambiguous, with each codon specifying multiple different amino acids', "C":'It varies completely and unpredictably between all species', "D":'Each amino acid has exactly one possible codon'},"answer":'A'},
{"id":43,"subject":'Biology',"topic":'Molecular Biology',"difficulty":'Medium',
 "question":'Which of the following occurs during RNA processing in eukaryotes, but not typically in prokaryotes?',
 "options":{"A":'Transcription', "B":'Translation', "C":'DNA replication', "D":"Addition of a 5' cap and a poly-A tail, and splicing out of introns"},"answer":'D'},
{"id":44,"subject":'Biology',"topic":'Molecular Biology',"difficulty":'Easy',
 "question":'Which nitrogenous base is unique to RNA and not found in DNA?',
 "options":{"A":'Adenine', "B":'Guanine', "C":'Cytosine', "D":'Uracil'},"answer":'D'},
{"id":45,"subject":'Biology',"topic":'Evolution',"difficulty":'Easy',
 "question":'Fossils found in progressively younger rock layers that show a gradual change in form over time provide evidence for:',
 "options":{"A":'Evolution through descent with modification', "B":'Genetic drift only', "C":'Spontaneous generation', "D":'The stability of species over time'},"answer":'A'},
{"id":46,"subject":'Biology',"topic":'Evolution',"difficulty":'Medium',
 "question":"The beaks of Darwin's finches on the Galapagos Islands vary in shape and size according to available food sources on each island. This is best explained by:",
 "options":{"A":'Random genetic drift with no adaptive significance', "B":'Natural selection favoring beak shapes suited to the local food supply', "C":'Identical selective pressures on all islands', "D":'Direct modification of beaks by the environment within a single generation'},"answer":'B'},
{"id":47,"subject":'Biology',"topic":'Evolution',"difficulty":'Medium',
 "question":'Gene flow between two previously isolated populations tends to:',
 "options":{"A":'Increase genetic differences between the populations', "B":'Have no effect on allele frequencies', "C":'Decrease genetic differences between the populations by introducing new alleles into each', "D":'Cause immediate speciation'},"answer":'C'},
{"id":48,"subject":'Biology',"topic":'Evolution',"difficulty":'Hard',
 "question":'In a population in Hardy-Weinberg equilibrium, the frequency of the recessive allele (q) is 0.1. What percentage of the population is expected to be homozygous dominant?',
 "options":{"A":'1%', "B":'18%', "C":'99%', "D":'81%'},"answer":'D'},
{"id":49,"subject":'Biology',"topic":'Classification & Diversity',"difficulty":'Easy',
 "question":'The scientific (binomial) name of an organism typically consists of its:',
 "options":{"A":'Kingdom and phylum', "B":'Genus and species', "C":'Family and order', "D":'Domain and kingdom'},"answer":'B'},
{"id":50,"subject":'Biology',"topic":'Classification & Diversity',"difficulty":'Easy',
 "question":'Organisms in kingdom Monera (or the domains Bacteria and Archaea) are characterized primarily by:',
 "options":{"A":'Being multicellular eukaryotes', "B":'Having chloroplasts exclusively', "C":'Being obligate parasites only', "D":'Being unicellular prokaryotes lacking a membrane-bound nucleus'},"answer":'D'},
{"id":51,"subject":'Biology',"topic":'Classification & Diversity',"difficulty":'Medium',
 "question":'Cladistics, a method of classification based on shared derived characteristics, primarily aims to group organisms according to:',
 "options":{"A":'Superficial physical similarity only', "B":'Habitat and geographic location', "C":'Alphabetical order of their names', "D":'Evolutionary relationships and common ancestry'},"answer":'D'},
{"id":52,"subject":'Biology',"topic":'Classification & Diversity',"difficulty":'Medium',
 "question":'An organism is multicellular, heterotrophic, absorbs nutrients through a network of thread-like structures, and reproduces via spores. It most likely belongs to:',
 "options":{"A":'Kingdom Fungi', "B":'Kingdom Plantae', "C":'Kingdom Animalia', "D":'Kingdom Protista'},"answer":'A'},
{"id":53,"subject":'Biology',"topic":'Classification & Diversity',"difficulty":'Easy',
 "question":'Which of the following taxonomic ranks is broader than Order but narrower than Phylum?',
 "options":{"A":'Family', "B":'Genus', "C":'Class', "D":'Species'},"answer":'C'},
{"id":54,"subject":'Biology',"topic":'Classification & Diversity',"difficulty":'Medium',
 "question":'Members of phylum Nematoda (roundworms) are characterized by having:',
 "options":{"A":'A segmented body with jointed legs', "B":'Radial symmetry with no true body cavity', "C":'A rigid exoskeleton made of chitin', "D":'A cylindrical, unsegmented body with a complete digestive tract'},"answer":'D'},
{"id":55,"subject":'Biology',"topic":'Plant Biology',"difficulty":'Easy',
 "question":'The tissue responsible for producing new cells through cell division, enabling plant growth, is called:',
 "options":{"A":'Xylem tissue', "B":'Epidermal tissue', "C":'Meristematic tissue', "D":'Phloem tissue'},"answer":'C'},
{"id":56,"subject":'Biology',"topic":'Plant Biology',"difficulty":'Medium',
 "question":'In photosynthesis, the light-dependent reactions occur in the thylakoid membrane, while the Calvin cycle (light-independent reactions) occurs in the:',
 "options":{"A":'Thylakoid lumen', "B":'Outer chloroplast membrane', "C":'Stroma', "D":'Mitochondrial matrix'},"answer":'C'},
{"id":57,"subject":'Biology',"topic":'Plant Biology',"difficulty":'Medium',
 "question":'Which pigment is primarily responsible for absorbing light energy to initiate photosynthesis, though accessory pigments also contribute?',
 "options":{"A":'Carotenoid', "B":'Anthocyanin', "C":'Chlorophyll a', "D":'Xanthophyll'},"answer":'C'},
{"id":58,"subject":'Biology',"topic":'Plant Biology',"difficulty":'Hard',
 "question":'CAM plants differ from C4 plants in that CAM plants separate carbon fixation and the Calvin cycle by:',
 "options":{"A":'Temporal separation, fixing CO2 at night and running the Calvin cycle during the day using stored organic acids', "B":'Spatial separation between mesophyll and bundle-sheath cells', "C":'Performing both processes simultaneously in the same cell at the same time', "D":'Lacking the Calvin cycle entirely'},"answer":'A'},
{"id":59,"subject":'Biology',"topic":'Plant Biology',"difficulty":'Medium',
 "question":'Abscisic acid (ABA), a plant hormone, is primarily associated with:',
 "options":{"A":'Promoting rapid cell division', "B":'Inducing stomatal closure and seed dormancy in response to stress', "C":'Promoting stem elongation', "D":'Triggering flowering'},"answer":'B'},
{"id":60,"subject":'Biology',"topic":'Plant Biology',"difficulty":'Easy',
 "question":"A seed's protective outer covering, which develops from the ovule's outer layers, is called the:",
 "options":{"A":'Cotyledon', "B":'Seed coat (testa)', "C":'Endosperm', "D":'Radicle'},"answer":'B'},
{"id":61,"subject":'Biology',"topic":'Human Physiology - Digestion',"difficulty":'Easy',
 "question":'The enzyme pepsin, active in the acidic environment of the stomach, primarily digests:',
 "options":{"A":'Carbohydrates', "B":'Proteins', "C":'Fats', "D":'Nucleic acids'},"answer":'B'},
{"id":62,"subject":'Biology',"topic":'Human Physiology - Digestion',"difficulty":'Medium',
 "question":'Which of the following best describes the role of the pyloric sphincter?',
 "options":{"A":'It controls swallowing at the top of the esophagus', "B":'It regulates the release of chyme from the stomach into the duodenum', "C":'It regulates bile release from the gallbladder', "D":'It controls the passage of food from the mouth to the esophagus'},"answer":'B'},
{"id":63,"subject":'Biology',"topic":'Human Physiology - Digestion',"difficulty":'Medium',
 "question":'Segmentation, a type of intestinal muscular contraction, primarily functions to:',
 "options":{"A":'Propel food rapidly in one direction only', "B":'Mix chyme with digestive juices and increase contact with the absorptive surface', "C":'Prevent any movement of food', "D":'Absorb nutrients directly'},"answer":'B'},
{"id":64,"subject":'Biology',"topic":'Human Physiology - Digestion',"difficulty":'Hard',
 "question":'A person with a damaged pancreas, unable to secrete bicarbonate into the small intestine, would most likely experience:',
 "options":{"A":'Enhanced fat digestion', "B":'No digestive consequences', "C":'Impaired digestion, as pancreatic enzymes function poorly in the acidic environment left unneutralized', "D":'Excess absorption of nutrients'},"answer":'C'},
{"id":65,"subject":'Biology',"topic":'Human Physiology - Circulation',"difficulty":'Easy',
 "question":'Which chamber of the heart pumps oxygenated blood into the aorta to supply the entire body?',
 "options":{"A":'Right atrium', "B":'Right ventricle', "C":'Left atrium', "D":'Left ventricle'},"answer":'D'},
{"id":66,"subject":'Biology',"topic":'Human Physiology - Circulation',"difficulty":'Medium',
 "question":'Which of the following best describes the role of valves within veins?',
 "options":{"A":'They prevent the backflow of blood, assisting its return to the heart against gravity', "B":'They generate the pressure needed to pump blood', "C":'They regulate heart rate', "D":'They filter blood cells'},"answer":'A'},
{"id":67,"subject":'Biology',"topic":'Human Physiology - Circulation',"difficulty":'Medium',
 "question":'White blood cells (leukocytes) primarily function in the body to:',
 "options":{"A":'Carry oxygen throughout the body', "B":'Defend the body against infection and foreign invaders', "C":'Clot blood at wound sites', "D":'Transport nutrients to tissues'},"answer":'B'},
{"id":68,"subject":'Biology',"topic":'Human Physiology - Circulation',"difficulty":'Hard',
 "question":'During exercise, blood flow to skeletal muscles increases significantly mainly due to:',
 "options":{"A":'Vasoconstriction of arterioles supplying the muscles', "B":'Vasodilation of arterioles supplying the muscles, in response to increased metabolic demand', "C":'A decrease in heart rate', "D":'Closure of capillary beds in the muscles'},"answer":'B'},
{"id":69,"subject":'Biology',"topic":'Human Physiology - Respiration',"difficulty":'Easy',
 "question":'The thin, dome-shaped muscle that separates the thoracic and abdominal cavities and plays a key role in breathing is the:',
 "options":{"A":'Larynx', "B":'Trachea', "C":'Pleura', "D":'Diaphragm'},"answer":'D'},
{"id":70,"subject":'Biology',"topic":'Human Physiology - Respiration',"difficulty":'Medium',
 "question":'The pleural membranes surrounding the lungs primarily function to:',
 "options":{"A":'Reduce friction during lung expansion and contraction, and help maintain lung inflation', "B":'Produce mucus to trap particles', "C":'Filter incoming air', "D":'Regulate blood pH'},"answer":'A'},
{"id":71,"subject":'Biology',"topic":'Human Physiology - Respiration',"difficulty":'Medium',
 "question":'An increase in blood carbon dioxide concentration causes blood pH to:',
 "options":{"A":'Increase (become more basic)', "B":'Decrease (become more acidic), as CO2 forms carbonic acid in the blood', "C":'Remain completely unchanged', "D":'Become exactly neutral'},"answer":'B'},
{"id":72,"subject":'Biology',"topic":'Human Physiology - Excretion',"difficulty":'Easy',
 "question":"The outer, reddish-brown region of the kidney, containing most of the nephrons' filtering structures, is called the:",
 "options":{"A":'Renal medulla', "B":'Renal pelvis', "C":'Renal cortex', "D":'Ureter'},"answer":'C'},
{"id":73,"subject":'Biology',"topic":'Human Physiology - Excretion',"difficulty":'Medium',
 "question":'Which of the following substances is normally almost completely reabsorbed from the filtrate back into the blood under healthy conditions?',
 "options":{"A":'Urea', "B":'Creatinine', "C":'Excess water during dehydration only', "D":'Glucose'},"answer":'D'},
{"id":74,"subject":'Biology',"topic":'Human Physiology - Excretion',"difficulty":'Hard',
 "question":'A person with untreated diabetes mellitus often has glucose present in their urine (glucosuria) mainly because:',
 "options":{"A":'Blood glucose levels exceed the renal threshold, so not all filtered glucose can be reabsorbed by the limited number of transporters', "B":'The kidneys deliberately excrete glucose to maintain blood levels', "C":'Glucose is never reabsorbed under any circumstances', "D":'Insulin directly causes glucose excretion'},"answer":'A'},
{"id":75,"subject":'Biology',"topic":'Human Physiology - Nervous & Endocrine',"difficulty":'Easy',
 "question":'The part of the neuron that transmits electrical impulses away from the cell body toward the synapse is the:',
 "options":{"A":'Dendrite', "B":'Nucleus', "C":'Axon', "D":'Cell body (soma)'},"answer":'C'},
{"id":76,"subject":'Biology',"topic":'Human Physiology - Nervous & Endocrine',"difficulty":'Medium',
 "question":'The hypothalamus plays a central role in the endocrine system mainly by:',
 "options":{"A":'Directly secreting all body hormones', "B":'Having no connection to hormone regulation', "C":'Producing only digestive enzymes', "D":'Regulating the pituitary gland, which in turn controls many other endocrine glands'},"answer":'D'},
{"id":77,"subject":'Biology',"topic":'Human Physiology - Nervous & Endocrine',"difficulty":'Medium',
 "question":'Antidiuretic hormone (ADH), released by the posterior pituitary, primarily acts on the kidneys to:',
 "options":{"A":'Increase urine volume', "B":'Increase sodium excretion', "C":'Increase water reabsorption, reducing urine volume', "D":'Have no effect on water balance'},"answer":'C'},
{"id":78,"subject":'Biology',"topic":'Human Physiology - Nervous & Endocrine',"difficulty":'Hard',
 "question":'The all-or-none principle of action potentials means that:',
 "options":{"A":'Stronger stimuli always produce proportionally larger action potentials', "B":'Action potentials vary continuously in size depending on stimulus strength', "C":'A stimulus of any strength always produces the same size action potential once threshold is reached', "D":'No action potential ever reaches the same amplitude twice'},"answer":'C'},
{"id":79,"subject":'Biology',"topic":'Human Physiology - Reproduction',"difficulty":'Easy',
 "question":'The structure that connects a developing fetus to the placenta, allowing nutrient and gas exchange, is the:',
 "options":{"A":'Amniotic sac', "B":'Cervix', "C":'Umbilical cord', "D":'Fallopian tube'},"answer":'C'},
{"id":80,"subject":'Biology',"topic":'Human Physiology - Reproduction',"difficulty":'Medium',
 "question":'Progesterone, secreted mainly by the corpus luteum and later the placenta, primarily functions to:',
 "options":{"A":'Trigger ovulation', "B":'Maintain the uterine lining to support pregnancy', "C":'Stimulate sperm production', "D":'Trigger menstruation'},"answer":'B'},
{"id":81,"subject":'Biology',"topic":'Ecology',"difficulty":'Medium',
 "question":'Primary succession occurs when an ecological community develops in an area:',
 "options":{"A":'That previously supported a thriving community, now disturbed', "B":'That has never previously supported life, such as newly formed volcanic rock', "C":'With abundant established soil and vegetation', "D":'That is fully aquatic only'},"answer":'B'},

# ============================================================
# CHEMISTRY (45 questions) - id 82-126
# ============================================================
{"id":82,"subject":'Chemistry',"topic":'Atomic Structure',"difficulty":'Easy',
 "question":'The maximum number of electrons that can occupy the first electron shell (n=1) is:',
 "options":{"A":'8', "B":'2', "C":'18', "D":'32'},"answer":'B'},
{"id":83,"subject":'Chemistry',"topic":'Atomic Structure',"difficulty":'Medium',
 "question":'An atom of nitrogen-15 (atomic number 7) contains how many neutrons?',
 "options":{"A":'8', "B":'7', "C":'15', "D":'22'},"answer":'A'},
{"id":84,"subject":'Chemistry',"topic":'Atomic Structure',"difficulty":'Medium',
 "question":'The electron configuration of a neutral fluorine atom (Z = 9) is:',
 "options":{"A":'1s2 2s2 2p5', "B":'1s2 2s2 2p6', "C":'1s2 2s2 2p4', "D":'1s2 2s1 2p6'},"answer":'A'},
{"id":85,"subject":'Chemistry',"topic":'Atomic Structure',"difficulty":'Hard',
 "question":'An ion formed from a neutral atom with 19 protons that has lost 1 electron carries a charge of:',
 "options":{"A":'+1', "B":'-1', "C":'+2', "D":'-2'},"answer":'A'},
{"id":86,"subject":'Chemistry',"topic":'Periodic Table',"difficulty":'Easy',
 "question":'Which of the following groups contains elements that are generally the least reactive?',
 "options":{"A":'Group 1', "B":'Group 18', "C":'Group 17', "D":'Group 2'},"answer":'B'},
{"id":87,"subject":'Chemistry',"topic":'Periodic Table',"difficulty":'Medium',
 "question":'Atomic radius generally decreases across a period from left to right mainly because:',
 "options":{"A":'The number of electron shells increases significantly', "B":'Shielding effect increases dramatically', "C":'Nuclear charge increases while electrons are added to the same shell, pulling electrons closer', "D":'Atomic mass decreases across the period'},"answer":'C'},
{"id":88,"subject":'Chemistry',"topic":'Periodic Table',"difficulty":'Medium',
 "question":'An element with electron configuration 1s2 2s2 2p6 3s2 3p4 would most likely:',
 "options":{"A":'Lose 6 electrons to form a +6 ion', "B":'Be chemically inert', "C":'Gain 2 electrons to form a -2 ion', "D":'Lose 4 electrons only, never gaining any'},"answer":'C'},
{"id":89,"subject":'Chemistry',"topic":'Chemical Bonding',"difficulty":'Easy',
 "question":'Which type of bond forms when electrons are transferred completely from one atom to another, typically between a metal and a nonmetal?',
 "options":{"A":'Ionic bond', "B":'Covalent bond', "C":'Metallic bond', "D":'Hydrogen bond'},"answer":'A'},
{"id":90,"subject":'Chemistry',"topic":'Chemical Bonding',"difficulty":'Medium',
 "question":'According to VSEPR theory, a molecule such as SF6, with six bonding pairs and no lone pairs on the central atom, has a molecular shape described as:',
 "options":{"A":'Trigonal bipyramidal', "B":'Tetrahedral', "C":'Octahedral', "D":'Square planar'},"answer":'C'},
{"id":91,"subject":'Chemistry',"topic":'Chemical Bonding',"difficulty":'Medium',
 "question":'NH3 is a polar molecule mainly because:',
 "options":{"A":'Its shape is perfectly symmetrical', "B":'Nitrogen and hydrogen have identical electronegativities', "C":'It has no lone pairs', "D":'Its trigonal pyramidal shape, due to the lone pair on nitrogen, prevents the bond dipoles from canceling'},"answer":'D'},
{"id":92,"subject":'Chemistry',"topic":'Chemical Bonding',"difficulty":'Hard',
 "question":'Which of the following best explains why molecular substances like iodine (I2) generally have much lower melting points than ionic compounds like NaCl?',
 "options":{"A":'Molecular substances have stronger covalent bonds than ionic bonds', "B":'Ionic compounds have no charged particles', "C":'Molecular substances always contain metals', "D":'Molecular substances are held together by weak intermolecular forces between molecules, while ionic compounds have strong electrostatic forces throughout the lattice'},"answer":'D'},
{"id":93,"subject":'Chemistry',"topic":'States of Matter',"difficulty":'Easy',
 "question":'Brownian motion, the random movement of small particles suspended in a fluid, provides evidence for:',
 "options":{"A":'The existence of a vacuum', "B":'The constant, random motion of molecules in a fluid', "C":'The stationary nature of liquid molecules', "D":'The absence of intermolecular forces'},"answer":'B'},
{"id":94,"subject":'Chemistry',"topic":'States of Matter',"difficulty":'Medium',
 "question":"A gas occupies 5.0 L at 4.0 atm. What volume will it occupy at 2.0 atm, assuming constant temperature (Boyle's Law)?",
 "options":{"A":'20.0 L', "B":'2.5 L', "C":'10.0 L', "D":'1.0 L'},"answer":'C'},
{"id":95,"subject":'Chemistry',"topic":'States of Matter',"difficulty":'Hard',
 "question":"A fixed mass of gas occupies 6 L at 600 K at constant pressure. What volume will it occupy at 200 K (Charles's Law)?",
 "options":{"A":'18 L', "B":'2 L', "C":'200 L', "D":'12 L'},"answer":'B'},
{"id":96,"subject":'Chemistry',"topic":'Stoichiometry',"difficulty":'Easy',
 "question":'The molar mass of methane (CH4) is approximately:',
 "options":{"A":'12 g/mol', "B":'20 g/mol', "C":'28 g/mol', "D":'16 g/mol'},"answer":'D'},
{"id":97,"subject":'Chemistry',"topic":'Stoichiometry',"difficulty":'Medium',
 "question":'How many moles are present in 6.4 g of sulfur (molar mass 32 g/mol)?',
 "options":{"A":'0.1 mol', "B":'2 mol', "C":'5 mol', "D":'0.2 mol'},"answer":'D'},
{"id":98,"subject":'Chemistry',"topic":'Stoichiometry',"difficulty":'Hard',
 "question":'A 400 mL solution contains 0.1 mole of KOH. What is the molarity of this solution?',
 "options":{"A":'0.1 M', "B":'0.25 M', "C":'0.4 M', "D":'0.025 M'},"answer":'B'},
{"id":99,"subject":'Chemistry',"topic":'Stoichiometry',"difficulty":'Medium',
 "question":'In the balanced equation N2 + 3H2 -> 2NH3, how many moles of H2 are needed to react completely with 5 moles of N2?',
 "options":{"A":'5', "B":'10', "C":'15', "D":'3'},"answer":'C'},
{"id":100,"subject":'Chemistry',"topic":'Thermochemistry',"difficulty":'Easy',
 "question":'A reaction in which the enthalpy of the products is lower than that of the reactants is classified as:',
 "options":{"A":'Endothermic', "B":'Exothermic', "C":'Isothermal', "D":'Adiabatic'},"answer":'B'},
{"id":101,"subject":'Chemistry',"topic":'Thermochemistry',"difficulty":'Medium',
 "question":'Bond dissociation energy refers to the energy required to:',
 "options":{"A":'Form a bond between two atoms', "B":'Break a specific chemical bond, separating the bonded atoms', "C":'Ionize an entire molecule', "D":"Change a substance's phase"},"answer":'B'},
{"id":102,"subject":'Chemistry',"topic":'Chemical Equilibrium',"difficulty":'Medium',
 "question":'For the exothermic equilibrium N2(g) + 3H2(g) <-> 2NH3(g) + heat, increasing the temperature will shift the equilibrium:',
 "options":{"A":'Toward the products (NH3)', "B":'Not at all', "C":'Completely to the product side', "D":'Toward the reactants (N2 and H2), since heat is treated as a product being added'},"answer":'D'},
{"id":103,"subject":'Chemistry',"topic":'Chemical Equilibrium',"difficulty":'Hard',
 "question":'If Keq for a reaction is much less than 1 (Keq << 1), this indicates that at equilibrium:',
 "options":{"A":'The products are strongly favored', "B":'The reaction is at a 1:1 ratio', "C":'The reaction has not started', "D":'The reactants are strongly favored'},"answer":'D'},
{"id":104,"subject":'Chemistry',"topic":'Reaction Kinetics',"difficulty":'Easy',
 "question":'A catalyst increases reaction rate without being permanently consumed because it:',
 "options":{"A":'Becomes part of the final product', "B":'Increases the temperature of the system permanently', "C":'Reacts completely with the reactants', "D":'Provides an alternate reaction pathway with lower activation energy, and is regenerated at the end'},"answer":'D'},
{"id":105,"subject":'Chemistry',"topic":'Reaction Kinetics',"difficulty":'Medium',
 "question":'A reaction has a rate law of rate = k[A][B]^2. If the concentration of B is tripled while A remains constant, the rate will:',
 "options":{"A":'Triple', "B":'Increase ninefold', "C":'Remain unchanged', "D":'Increase sixfold'},"answer":'B'},
{"id":106,"subject":'Chemistry',"topic":'Electrochemistry',"difficulty":'Medium',
 "question":'In an electrochemical cell, the cathode is defined as the electrode where:',
 "options":{"A":'Reduction occurs', "B":'Oxidation occurs', "C":'No reaction occurs', "D":'Only metal ions are produced'},"answer":'A'},
{"id":107,"subject":'Chemistry',"topic":'Electrochemistry',"difficulty":'Hard',
 "question":'In the reaction Zn + Pb(NO3)2 -> Zn(NO3)2 + Pb, zinc metal is oxidized while lead ion (Pb2+) is:',
 "options":{"A":'Reduced, gaining electrons to form solid lead', "B":'Oxidized', "C":'Unchanged', "D":'Acting as a catalyst'},"answer":'A'},
{"id":108,"subject":'Chemistry',"topic":'Acids & Bases',"difficulty":'Easy',
 "question":'A substance that can act as both an acid and a base, depending on the reaction, is called:',
 "options":{"A":'Neutral', "B":'Amphoteric (or amphiprotic)', "C":'Inert', "D":'Ionic only'},"answer":'B'},
{"id":109,"subject":'Chemistry',"topic":'Acids & Bases',"difficulty":'Medium',
 "question":'A solution has a pH of 2. What is its hydrogen ion concentration [H+]?',
 "options":{"A":'2 M', "B":'1x10^2 M', "C":'1x10^-2 M', "D":'1x10^-12 M'},"answer":'C'},
{"id":110,"subject":'Chemistry',"topic":'Acids & Bases',"difficulty":'Medium',
 "question":'The graph shows the pH curve as HCl is added to a weak base (ammonia) solution. Based on the shape of the curve, the pH at the equivalence point is expected to be:',
 "image":'images/q13_titration_weak_base_strong_acid.png',
 "options":{"A":'Exactly 7.0', "B":'Less than 7, because the resulting salt solution is weakly acidic', "C":'Greater than 7', "D":'Extremely high, near pH 13'},"answer":'B'},
{"id":111,"subject":'Chemistry',"topic":'Acids & Bases',"difficulty":'Hard',
 "question":'The conjugate base of a weak acid, HA, is:',
 "options":{"A":'HA itself', "B":'A-', "C":'H+', "D":'H2A+'},"answer":'B'},
{"id":112,"subject":'Chemistry',"topic":'Organic Chemistry',"difficulty":'Easy',
 "question":'Which functional group is characteristic of an aldehyde?',
 "options":{"A":'A carbonyl group within the chain, bonded to two carbons', "B":'-COOH', "C":'A carbonyl group at the end of a carbon chain, bonded to at least one hydrogen (-CHO)', "D":'-OH'},"answer":'C'},
{"id":113,"subject":'Chemistry',"topic":'Organic Chemistry',"difficulty":'Medium',
 "question":'Which of the following correctly describes a substitution reaction in organic chemistry?',
 "options":{"A":'A double bond is converted into a single bond by adding atoms', "B":'One atom or group is replaced by another atom or group', "C":'Two molecules combine to release water', "D":'A molecule is broken into two smaller molecules by heat alone'},"answer":'B'},
{"id":114,"subject":'Chemistry',"topic":'Organic Chemistry',"difficulty":'Medium',
 "question":'Which functional group is present in amino acids, in addition to the carboxyl group, that allows them to link via peptide bonds?',
 "options":{"A":'Hydroxyl group (-OH)', "B":'Aldehyde group (-CHO)', "C":'Amino group (-NH2)', "D":'Ether linkage'},"answer":'C'},
{"id":115,"subject":'Chemistry',"topic":'Organic Chemistry',"difficulty":'Hard',
 "question":"Which of the following best describes a Grignard reagent's general reactivity in organic synthesis?",
 "options":{"A":'It behaves as a strong electrophile that avoids carbon-carbon bond formation', "B":'It has no reactivity toward carbonyl compounds', "C":'It acts as a strong nucleophile and base, commonly used to form new carbon-carbon bonds by attacking carbonyl carbons', "D":'It only reacts with alkanes'},"answer":'C'},
{"id":116,"subject":'Chemistry',"topic":'Organic Chemistry',"difficulty":'Medium',
 "question":'Vulcanization, the process of heating natural rubber with sulfur, primarily functions to:',
 "options":{"A":'Remove all carbon-carbon bonds', "B":'Break down the polymer into monomers', "C":"Introduce cross-links between polymer chains, increasing the rubber's strength and elasticity", "D":"Decrease the material's durability"},"answer":'C'},
{"id":117,"subject":'Chemistry',"topic":'Organic Chemistry',"difficulty":'Easy',
 "question":'Cis and trans isomers, a type of geometric isomerism, arise specifically due to restricted rotation around a:',
 "options":{"A":'Single (sigma) bond', "B":'Carbon-carbon double bond', "C":'Ionic bond', "D":'Hydrogen bond'},"answer":'B'},
{"id":118,"subject":'Chemistry',"topic":'Inorganic Chemistry',"difficulty":'Medium',
 "question":'Which of the following best explains why potassium (K) is more reactive than lithium (Li), both being Group 1 metals?',
 "options":{"A":'Potassium has a larger atomic radius, so its single valence electron is held less tightly and is easier to remove', "B":'Potassium has a smaller atomic radius, making its valence electron easier to remove', "C":'Lithium has more valence electrons than potassium', "D":'Potassium is a nonmetal'},"answer":'A'},
{"id":119,"subject":'Chemistry',"topic":'Inorganic Chemistry',"difficulty":'Medium',
 "question":'Which of the following elements would you expect to have properties most similar to oxygen, based on periodic trends?',
 "options":{"A":'Nitrogen', "B":'Fluorine', "C":'Sulfur', "D":'Carbon'},"answer":'C'},
{"id":120,"subject":'Chemistry',"topic":'Inorganic Chemistry',"difficulty":'Hard',
 "question":'In the reaction 2KI + Cl2 -> 2KCl + I2, iodide ion (I-) is oxidized while chlorine is:',
 "options":{"A":'Reduced, gaining electrons', "B":'Oxidized', "C":'Unchanged', "D":'Acting as a catalyst'},"answer":'A'},
{"id":121,"subject":'Chemistry',"topic":'Physical Chemistry',"difficulty":'Medium',
 "question":'Which of the following best describes osmotic pressure?',
 "options":{"A":'The pressure required to prevent the net flow of solvent across a semipermeable membrane by osmosis', "B":'The pressure exerted by a gas in a closed container', "C":'The pressure of the atmosphere at sea level', "D":'The pressure inside a solid crystal lattice'},"answer":'A'},
{"id":122,"subject":'Chemistry',"topic":'Physical Chemistry',"difficulty":'Hard',
 "question":'8 mL of 0.5 M NaOH is required to exactly neutralize 20 mL of HCl solution (NaOH + HCl -> NaCl + H2O). What is the molarity of the HCl solution?',
 "options":{"A":'0.2 M', "B":'0.1 M', "C":'0.4 M', "D":'0.05 M'},"answer":'A'},
{"id":123,"subject":'Chemistry',"topic":'Environmental Chemistry',"difficulty":'Easy',
 "question":'Which of the following human activities is a major contributor to global increases in atmospheric carbon dioxide?',
 "options":{"A":'Photosynthesis by plants', "B":'Combustion of fossil fuels', "C":'Evaporation of ocean water', "D":'Volcanic ash deposition'},"answer":'B'},
{"id":124,"subject":'Chemistry',"topic":'Environmental Chemistry',"difficulty":'Medium',
 "question":'Bioaccumulation refers to the process by which:',
 "options":{"A":"Certain substances, such as heavy metals or pesticides, build up in an organism's tissues over time, often increasing in concentration at higher trophic levels", "B":'Pollutants are rapidly broken down and eliminated from an organism', "C":'Nutrients cycle rapidly through an ecosystem', "D":'Organisms adapt genetically to pollution within one generation'},"answer":'A'},
{"id":125,"subject":'Chemistry',"topic":'Chemical Bonding',"difficulty":'Easy',
 "question":'The strength of a covalent bond generally increases with:',
 "options":{"A":'A decrease in the number of shared electron pairs', "B":'The bond having no shared electrons', "C":'An increase in the number of shared electron pairs (e.g., triple bonds are stronger than single bonds)', "D":'Increasing atomic size only'},"answer":'C'},
{"id":126,"subject":'Chemistry',"topic":'Atomic Structure',"difficulty":'Easy',
 "question":"Which of the following correctly describes an isotope's relationship to the standard atom of the same element?",
 "options":{"A":'Different number of protons', "B":'Different number of electrons only', "C":'Identical in every respect', "D":'Different number of neutrons, but the same number of protons'},"answer":'D'},

# ============================================================
# PHYSICS (36 questions) - id 127-162
# ============================================================
{"id":127,"subject":'Physics',"topic":'Kinematics',"difficulty":'Easy',
 "question":"A bus travels 280 km in 5 hours at constant velocity. What is the bus's average speed?",
 "options":{"A":'1400 km/h', "B":'56 km/h', "C":'40 km/h', "D":'5.6 km/h'},"answer":'B'},
{"id":128,"subject":'Physics',"topic":'Kinematics',"difficulty":'Medium',
 "question":'A skateboarder accelerates uniformly from 2 m/s to 14 m/s over 3 seconds. What is the acceleration?',
 "options":{"A":'6 m/s^2', "B":'12 m/s^2', "C":'3 m/s^2', "D":'4 m/s^2'},"answer":'D'},
{"id":129,"subject":'Physics',"topic":'Kinematics',"difficulty":'Hard',
 "question":'A rock is thrown vertically upward with an initial velocity of 25 m/s (g = 10 m/s^2). What is its velocity after 4 seconds (taking upward as positive)?',
 "options":{"A":'25 m/s', "B":'15 m/s', "C":'-15 m/s', "D":'-25 m/s'},"answer":'C'},
{"id":130,"subject":'Physics',"topic":'Dynamics',"difficulty":'Easy',
 "question":"According to Newton's first law, an object at rest will remain at rest unless acted upon by:",
 "options":{"A":'A balanced force', "B":'Gravity alone, regardless of other forces', "C":'An unbalanced (net) external force', "D":'Time passing'},"answer":'C'},
{"id":131,"subject":'Physics',"topic":'Dynamics',"difficulty":'Medium',
 "question":'A 7 kg object accelerates at 2 m/s^2 due to an applied net force. What is the magnitude of this force?',
 "options":{"A":'14 N', "B":'3.5 N', "C":'9 N', "D":'5 N'},"answer":'A'},
{"id":132,"subject":'Physics',"topic":'Dynamics',"difficulty":'Medium',
 "question":'The weight of an object is best defined as:',
 "options":{"A":'The amount of matter it contains', "B":'The gravitational force acting on its mass', "C":'Its resistance to acceleration', "D":'Its momentum'},"answer":'B'},
{"id":133,"subject":'Physics',"topic":'Dynamics',"difficulty":'Hard',
 "question":"A 12 kg block is pushed horizontally with a 60 N force across a surface with a coefficient of kinetic friction of 0.25 (g = 10 m/s^2). What is the block's acceleration?",
 "options":{"A":'5 m/s^2', "B":'1 m/s^2', "C":'3 m/s^2', "D":'2.5 m/s^2'},"answer":'D'},
{"id":134,"subject":'Physics',"topic":'Work, Energy & Power',"difficulty":'Easy',
 "question":'If the work done on an object is negative, this indicates that the force and displacement are:',
 "options":{"A":'In opposite directions', "B":'In the same direction', "C":'Perpendicular to each other', "D":'Both zero'},"answer":'A'},
{"id":135,"subject":'Physics',"topic":'Work, Energy & Power',"difficulty":'Medium',
 "question":'A 7 kg object is raised to a height of 6 m (g = 10 m/s^2). What is its gravitational potential energy at that height?',
 "options":{"A":'42 J', "B":'70 J', "C":'420 J', "D":'60 J'},"answer":'C'},
{"id":136,"subject":'Physics',"topic":'Work, Energy & Power',"difficulty":'Medium',
 "question":'An 8 kg object moving at 5 m/s has a kinetic energy of:',
 "options":{"A":'100 J', "B":'40 J', "C":'200 J', "D":'20 J'},"answer":'A'},
{"id":137,"subject":'Physics',"topic":'Work, Energy & Power',"difficulty":'Hard',
 "question":'A machine does 24000 J of work in 30 seconds. What is its power output?',
 "options":{"A":'720000 W', "B":'800 W', "C":'80 W', "D":'8000 W'},"answer":'B'},
{"id":138,"subject":'Physics',"topic":'Circular Motion & Gravitation',"difficulty":'Easy',
 "question":"The unit of gravitational field strength (g) near Earth's surface is typically expressed as:",
 "options":{"A":'m/s', "B":'m/s^2', "C":'kg/m^3', "D":'N·m'},"answer":'B'},
{"id":139,"subject":'Physics',"topic":'Circular Motion & Gravitation',"difficulty":'Medium',
 "question":'If the distance between two masses is increased fourfold, the gravitational force between them becomes:',
 "options":{"A":'Four times as large', "B":'One quarter as large', "C":'Sixteen times as large', "D":'One sixteenth as large'},"answer":'D'},
{"id":140,"subject":'Physics',"topic":'Circular Motion & Gravitation',"difficulty":'Hard',
 "question":'A satellite in a stable circular orbit experiences a net force that is:',
 "options":{"A":'Equal to the gravitational force, providing the centripetal force needed for circular motion', "B":'Zero, since it moves at constant speed', "C":'Directed away from the planet', "D":'Provided entirely by its own engines'},"answer":'A'},
{"id":141,"subject":'Physics',"topic":'Fluid Mechanics',"difficulty":'Easy',
 "question":"Archimedes' principle states that the buoyant force on a submerged or floating object is equal to:",
 "options":{"A":'The weight of the fluid displaced by the object', "B":"The object's own weight always", "C":'The volume of the object', "D":'The density of the fluid alone'},"answer":'A'},
{"id":142,"subject":'Physics',"topic":'Fluid Mechanics',"difficulty":'Medium',
 "question":'A submarine can control its depth in water mainly by:',
 "options":{"A":'Changing its own mass by absorbing water', "B":'Increasing its speed only', "C":'Adjusting the amount of water in its ballast tanks to change its overall density', "D":'Changing the salinity of the surrounding water'},"answer":'C'},
{"id":143,"subject":'Physics',"topic":'Fluid Mechanics',"difficulty":'Hard',
 "question":"In a venturi tube, where the fluid passage narrows, the fluid's velocity increases and, according to Bernoulli's principle, its pressure:",
 "options":{"A":'Increases', "B":'Remains the same', "C":'Becomes zero', "D":'Decreases'},"answer":'D'},
{"id":144,"subject":'Physics',"topic":'Oscillations & Waves',"difficulty":'Easy',
 "question":"The number of wave cycles that pass a given point per unit time is called the wave's:",
 "options":{"A":'Wavelength', "B":'Amplitude', "C":'Speed', "D":'Frequency'},"answer":'D'},
{"id":145,"subject":'Physics',"topic":'Oscillations & Waves',"difficulty":'Medium',
 "question":'For a simple pendulum, which of the following factors does NOT affect its period of oscillation (for small angles)?',
 "options":{"A":'The length of the pendulum', "B":'The local gravitational acceleration', "C":'None of these factors matter', "D":'The mass of the bob'},"answer":'D'},
{"id":146,"subject":'Physics',"topic":'Oscillations & Waves',"difficulty":'Medium',
 "question":'A wave has a speed of 15 m/s and a frequency of 3 Hz. What is its wavelength?',
 "options":{"A":'45 m', "B":'0.2 m', "C":'18 m', "D":'5 m'},"answer":'D'},
{"id":147,"subject":'Physics',"topic":'Oscillations & Waves',"difficulty":'Hard',
 "question":'Constructive interference between two waves occurs when the waves meet:',
 "options":{"A":'Completely out of phase, cancelling each other', "B":'In phase, with crests aligning with crests, resulting in a wave of increased amplitude', "C":'At a 90-degree phase difference', "D":'Only when traveling in the same medium at different speeds'},"answer":'B'},
{"id":148,"subject":'Physics',"topic":'Thermodynamics',"difficulty":'Easy',
 "question":'Which temperature scale is based on absolute zero, the point at which molecular motion theoretically ceases?',
 "options":{"A":'Celsius', "B":'Kelvin', "C":'Fahrenheit', "D":'Rankine only in some contexts'},"answer":'B'},
{"id":149,"subject":'Physics',"topic":'Thermodynamics',"difficulty":'Medium',
 "question":'According to the third law of thermodynamics, the entropy of a perfect crystal at absolute zero is:',
 "options":{"A":'Infinite', "B":'Negative', "C":'Undefined', "D":'Zero'},"answer":'D'},
{"id":150,"subject":'Physics',"topic":'Thermodynamics',"difficulty":'Hard',
 "question":"In a cyclic process, a gas returns to its original state after completing one full cycle. Over one complete cycle, the net change in the gas's internal energy is:",
 "options":{"A":'Positive', "B":'Negative', "C":'Zero', "D":'Dependent on the path taken'},"answer":'C'},
{"id":151,"subject":'Physics',"topic":'Electrostatics',"difficulty":'Easy',
 "question":'The process by which an object becomes charged without direct contact, due to the presence of a nearby charged object, is called charging by:',
 "options":{"A":'Conduction', "B":'Friction', "C":'Grounding', "D":'Induction'},"answer":'D'},
{"id":152,"subject":'Physics',"topic":'Electrostatics',"difficulty":'Medium',
 "question":'Two point charges exert a force of 10 N on each other. If the distance between them is doubled, the new force will be:',
 "options":{"A":'20 N', "B":'2.5 N', "C":'5 N', "D":'40 N'},"answer":'B'},
{"id":153,"subject":'Physics',"topic":'Current Electricity',"difficulty":'Easy',
 "question":'In a parallel circuit, the voltage across each branch is:',
 "options":{"A":'Different for each branch', "B":'Always zero', "C":'The same across all branches, equal to the total voltage', "D":'Dependent only on resistance'},"answer":'C'},
{"id":154,"subject":'Physics',"topic":'Current Electricity',"difficulty":'Medium',
 "question":'In the circuit shown, R1 (8 ohm) and R2 (8 ohm) are connected in series, and this series combination is connected in parallel with R3 (16 ohm). What is the total resistance of the circuit?',
 "image":'images/q13_circuit_diagram_r1r2r3.png',
 "options":{"A":'16 ohm', "B":'4 ohm', "C":'8 ohm', "D":'32 ohm'},"answer":'C'},
{"id":155,"subject":'Physics',"topic":'Current Electricity',"difficulty":'Hard',
 "question":'Two identical resistors of 12 ohm each are connected first in series, then in parallel. What is the ratio of the series resistance to the parallel resistance?',
 "options":{"A":'1:1', "B":'2:1', "C":'8:1', "D":'4:1'},"answer":'D'},
{"id":156,"subject":'Physics',"topic":'Current Electricity',"difficulty":'Medium',
 "question":'A circuit carries a current of 3 A when connected to a 90 V supply. What is its resistance?',
 "options":{"A":'270 ohm', "B":'0.033 ohm', "C":'30 ohm', "D":'93 ohm'},"answer":'C'},
{"id":157,"subject":'Physics',"topic":'Electromagnetism',"difficulty":'Medium',
 "question":'The strength of the magnetic field produced by a current-carrying solenoid can be increased by inserting which type of core into the coil?',
 "options":{"A":'A plastic core', "B":'A wooden core', "C":'A glass core', "D":'A soft iron core'},"answer":'D'},
{"id":158,"subject":'Physics',"topic":'Electromagnetism',"difficulty":'Hard',
 "question":'According to the motor effect, a current-carrying conductor placed in a magnetic field experiences a force. This force is used practically in:',
 "options":{"A":'Generators only', "B":'Transformers exclusively', "C":'Batteries', "D":'Electric motors, converting electrical energy into mechanical motion'},"answer":'D'},
{"id":159,"subject":'Physics',"topic":'Modern Physics',"difficulty":'Easy',
 "question":'Which type of radioactive emission has the greatest penetrating power, able to pass through several centimeters of lead?',
 "options":{"A":'Gamma rays', "B":'Alpha particles', "C":'Beta particles', "D":'None of these penetrate matter'},"answer":'A'},
{"id":160,"subject":'Physics',"topic":'Modern Physics',"difficulty":'Medium',
 "question":'In beta-minus decay, a neutron in the nucleus transforms into a proton, an electron, and a(n):',
 "options":{"A":'Alpha particle', "B":'Positron', "C":'Gamma ray only', "D":'Antineutrino'},"answer":'D'},
{"id":161,"subject":'Physics',"topic":'Modern Physics',"difficulty":'Hard',
 "question":'A radioactive isotope has a half-life of 8 days. Approximately what percentage of the original sample remains after 24 days?',
 "options":{"A":'50%', "B":'25%', "C":'6.25%', "D":'12.5%'},"answer":'D'},
{"id":162,"subject":'Physics',"topic":'Optics',"difficulty":'Medium',
 "question":'The ray diagram shows an object placed in front of a plane mirror. Based on the diagram, the image formed is:',
 "image":'images/q13_plane_mirror_diagram.png',
 "options":{"A":'Virtual, upright, the same size as the object, and laterally inverted', "B":'Real, inverted, and magnified', "C":'Real, upright, and diminished', "D":'Virtual, inverted, and diminished'},"answer":'A'},

# ============================================================
# ENGLISH (9 questions) - id 163-171
# ============================================================
{"id":163,"subject":'English',"topic":'Synonyms',"difficulty":'Easy',
 "question":"Choose the word most nearly similar in meaning to 'DILIGENT':",
 "options":{"A":'Lazy', "B":'Careless', "C":'Hardworking', "D":'Indifferent'},"answer":'C'},
{"id":164,"subject":'English',"topic":'Antonyms',"difficulty":'Easy',
 "question":"Choose the word most nearly opposite in meaning to 'EXPAND':",
 "options":{"A":'Contract', "B":'Enlarge', "C":'Grow', "D":'Extend'},"answer":'A'},
{"id":165,"subject":'English',"topic":'Grammar',"difficulty":'Easy',
 "question":'Choose the grammatically correct sentence:',
 "options":{"A":'Neither the teacher nor the students was ready.', "B":'Neither the teacher nor the student were ready.', "C":'Neither teacher nor students was ready.', "D":'Neither the teacher nor the students were ready.'},"answer":'D'},
{"id":166,"subject":'English',"topic":'Grammar',"difficulty":'Medium',
 "question":'Choose the correct sentence:',
 "options":{"A":'By the time the guests arrive, we finish cooking.', "B":'By the time the guests arrive, we will finish cooking already.', "C":'By the time the guests arrived, we will have finished cooking.', "D":'By the time the guests arrive, we will have finished cooking.'},"answer":'D'},
{"id":167,"subject":'English',"topic":'Sentence Correction',"difficulty":'Medium',
 "question":'Identify the sentence that follows correct subject-verb agreement:',
 "options":{"A":'The committee have reached a decision.', "B":'The committees has reached a decision.', "C":"The committee were reaching a decision, weren't they.", "D":'The committee has reached a decision.'},"answer":'D'},
{"id":168,"subject":'English',"topic":'Vocabulary',"difficulty":'Medium',
 "question":"Choose the word that best completes the sentence: 'Despite the CEO's ______ promises of transparency, several financial irregularities were later uncovered.'",
 "options":{"A":'Genuine', "B":'Sincere', "C":'Honest', "D":'Hollow'},"answer":'D'},
{"id":169,"subject":'English',"topic":'Idioms',"difficulty":'Medium',
 "question":"Choose the meaning closest to the idiom 'to break the ice':",
 "options":{"A":'To initiate conversation in an awkward or unfamiliar situation', "B":'To cause a conflict', "C":'To end a relationship abruptly', "D":'To postpone an event'},"answer":'A'},
{"id":170,"subject":'English',"topic":'Sentence Correction',"difficulty":'Hard',
 "question":"Choose the option that best corrects the sentence: 'Everybody should submit their application before the deadline.'",
 "options":{"A":'Everybody should submit his or her application before the deadline.', "B":'Everybody should submit their applications before the deadline.', "C":'Everybody should submit his application before the deadlines.', "D":'Everyone should submit their application before deadlines.'},"answer":'A'},
{"id":171,"subject":'English',"topic":'Prepositions',"difficulty":'Hard',
 "question":"Choose the correct preposition to complete the sentence: 'The professor is highly regarded ______ her contributions to the field.'",
 "options":{"A":'on', "B":'at', "C":'with', "D":'for'},"answer":'D'},

# ============================================================
# LOGICAL REASONING (9 questions) - id 172-180
# ============================================================
{"id":172,"subject":'Logical Reasoning',"topic":'Number Series',"difficulty":'Easy',
 "question":'Find the next number in the series: 6, 12, 24, 48, ?',
 "options":{"A":'60', "B":'72', "C":'96', "D":'84'},"answer":'C'},
{"id":173,"subject":'Logical Reasoning',"topic":'Number Series',"difficulty":'Easy',
 "question":'Find the missing number: 7, 12, 17, 22, ?',
 "options":{"A":'27', "B":'25', "C":'26', "D":'24'},"answer":'A'},
{"id":174,"subject":'Logical Reasoning',"topic":'Analogies',"difficulty":'Easy',
 "question":'Teacher is to Classroom as Surgeon is to:',
 "options":{"A":'Hospital', "B":'Patient', "C":'Scalpel', "D":'Operating room'},"answer":'D'},
{"id":175,"subject":'Logical Reasoning',"topic":'Analogies',"difficulty":'Medium',
 "question":'Bee is to Hive as Ant is to:',
 "options":{"A":'Nest', "B":'Anthill', "C":'Colony', "D":'Queen'},"answer":'B'},
{"id":176,"subject":'Logical Reasoning',"topic":'Blood Relations',"difficulty":'Medium',
 "question":"Faisal said, 'This woman is the mother of my son's only sister.' How is the woman related to Faisal?",
 "options":{"A":'Mother', "B":'Sister', "C":'Wife', "D":'Daughter'},"answer":'C'},
{"id":177,"subject":'Logical Reasoning',"topic":'Coding-Decoding',"difficulty":'Medium',
 "question":'If in a certain code, PENCIL is written as QFODJM, how is PAPER written in the same code?',
 "options":{"A":'QAQFS', "B":'QBQES', "C":'QBQFS', "D":'RBQFS'},"answer":'C'},
{"id":178,"subject":'Logical Reasoning',"topic":'Syllogism',"difficulty":'Hard',
 "question":'All doctors are educated. Some educated people are wealthy. Which conclusion logically follows?',
 "options":{"A":'Some doctors are wealthy', "B":'All doctors are wealthy', "C":'None of the given conclusions logically follows', "D":'No doctors are wealthy'},"answer":'C'},
{"id":179,"subject":'Logical Reasoning',"topic":'Pattern Recognition',"difficulty":'Hard',
 "question":'Find the next term in the series: 2, 5, 10, 17, 26, ?',
 "options":{"A":'37', "B":'35', "C":'39', "D":'33'},"answer":'A'},
{"id":180,"subject":'Logical Reasoning',"topic":'Direction Sense',"difficulty":'Medium',
 "question":'A cyclist rides 7 km south, then turns west and rides 24 km. How far is he from his starting point?',
 "options":{"A":'31 km', "B":'17 km', "C":'29 km', "D":'25 km'},"answer":'D'},

]


# ------------------------------------------------------------
# Sanity-check / summary utility
# ------------------------------------------------------------
def summarize(questions):
    from collections import Counter
    subj = Counter(q["subject"] for q in questions)
    diff = Counter(q["difficulty"] for q in questions)
    ans = Counter(q["answer"] for q in questions)
    ids = [q["id"] for q in questions]
    dup_ids = [i for i in set(ids) if ids.count(i) > 1]
    dup_q = [q["question"] for q in questions]
    dup_questions = [t for t in set(dup_q) if dup_q.count(t) > 1]
    images = [q for q in questions if "image" in q]

    print(f"Total questions: {len(questions)}")
    print("\nBy subject:")
    for s, c in subj.items():
        print(f"  {s}: {c}")
    print("\nBy difficulty:")
    for d, c in diff.items():
        print(f"  {d}: {c}")
    print("\nBy correct-answer letter (should be roughly balanced):")
    for L in ["A", "B", "C", "D"]:
        print(f"  {L}: {ans[L]}")
    print(f"\nDuplicate IDs: {dup_ids if dup_ids else 'None'}")
    print(f"Duplicate question text: {dup_questions if dup_questions else 'None'}")
    print(f"\nImage-based questions ({len(images)}):")
    for q in images:
        print(f"  Q{q['id']} [{q['subject']}] -> {q['image']}")

    for q in questions:
        assert set(q["options"].keys()) == {"A", "B", "C", "D"}, f"Q{q['id']} missing an option"
        assert q["answer"] in q["options"], f"Q{q['id']} answer key invalid"
    print("\nAll questions have exactly 4 options (A-D) and a valid answer key. OK.")


def print_answer_key(questions):
    print("\nANSWER KEY")
    print("-" * 40)
    for q in questions:
        print(f"{q['id']:>3}. {q['answer']}", end="   ")
        if q["id"] % 10 == 0:
            print()
    print()


if __name__ == "__main__":
    summarize(QUESTIONS)
    print_answer_key(QUESTIONS)