# -*- coding: utf-8 -*-
# Clean text extraction of UHS Entrance Test 2010 from the uploaded PDF.
# Source: MDCAT Past Papers (2008-2016) Solved.pdf, Entrance Test – 2010, pages 1-17 of the 2010 paper.
# Total questions: 220. No answer key included.
# Diagram/figure content is represented by text only; no images are embedded.

QUESTIONS = [{'number': 1,
  'subject': 'Physics',
  'question': 'Which one is the highest power multiple?',
  'options': {'A': 'Giga', 'C': 'Mega', 'B': 'Tera', 'D': 'Deca'},
  'diagram_text': ''},
 {'number': 2,
  'subject': 'Physics',
  'question': 'SI unit of charge is _______.',
  'options': {'A': 'Ampere', 'C': 'Coulomb', 'B': 'Volt', 'D': 'Calorie'},
  'diagram_text': ''},
 {'number': 3,
  'subject': 'Physics',
  'question': 'The electrical analog of mass is electricity is _________.',
  'options': {'A': 'Capacitance', 'C': 'Charge', 'B': 'Inductance', 'D': 'Resistance'},
  'diagram_text': ''},
 {'number': 4,
  'subject': 'Physics',
  'question': 'Which one of the following relations is correct?',
  'options': {'A': '1 wb m-2 = N m-1 A-1', 'C': '1 wb m-2 = 1 Tesla', 'B': '1 Tesla = 10⁴ Gausses', 'D': 'All of these'},
  'diagram_text': ''},
 {'number': 5,
  'subject': 'Physics',
  'question': 'Life time of electron in metastable state is about _________.',
  'options': {'A': '10⁻⁵ sec', 'C': '10⁻⁸ sec', 'B': '10⁻³ sec', 'D': '10⁻² sec'},
  'diagram_text': ''},
 {'number': 6,
  'subject': 'Physics',
  'question': 'The torque acting on a current carrying coil is given by _____________.',
  'options': {'A': 'τ = NIAB cos α', 'C': 'τ = NIAB sin α', 'B': 'τ = BIL sin α', 'D': 'τ = BIL cos α'},
  'diagram_text': ''},
 {'number': 7,
  'subject': 'Physics',
  'question': 'The grid in the cathode ray oscilloscope _____________.',
  'options': {'A': 'Controls number of waves',
              'C': 'Accelerates electrons',
              'B': 'Controls the brightness of spot formed',
              'D': 'Has positive potential with respect to cathode A B C D ID 1 2 3 4'},
  'diagram_text': ''},
 {'number': 8,
  'subject': 'Physics',
  'question': 'The horizontal range of a projectile, at a certain place, is completely determined by',
  'options': {'A': 'The angle of projection',
              'C': 'The mass of the projectile',
              'B': 'The initial velocity of projection',
              'D': 'Speed and mass of the projectile'},
  'diagram_text': ''},
 {'number': 9,
  'subject': 'Physics',
  'question': 'If velocity is double, then.',
  'options': {'A': 'Momentum increase 4 times and K.E increases 2 times',
              'B': 'Momentum and K.E remain same',
              'C': 'Momentum increases 2 times and K.E increase constant',
              'D': 'Momentum increases 2 times and K.E increases 4 times'},
  'diagram_text': ''},
 {'number': 10,
  'subject': 'Physics',
  'question': 'The consumption of energy by 60-watt bulb in 2 seconds is:',
  'options': {'A': '20 J', 'C': '30 J', 'B': '120 J', 'D': '0.02 J'},
  'diagram_text': ''},
 {'number': 11,
  'subject': 'Physics',
  'question': 'In transistors, the base region is very thin, of the order of',
  'options': {'A': '10⁻⁵ cm', 'C': '10⁻⁶ mm', 'B': '10⁻⁶ m', 'D': '10⁻⁶ µm'},
  'diagram_text': ''},
 {'number': 12,
  'subject': 'Physics',
  'question': 'The closed loop gain of OP-AMP depends on',
  'options': {'A': 'Internal structure of OP-AMP',
              'C': 'Voltage of power supplies',
              'B': 'Externally connected resistances',
              'D': 'Input resistance'},
  'diagram_text': ''},
 {'number': 13,
  'subject': 'Physics',
  'question': 'The net charge on an N-type substance is',
  'options': {'A': '0.7 volts', 'C': '0.25 volts', 'B': '0.3 volts', 'D': '0.07 volts'},
  'diagram_text': ''},
 {'number': 14,
  'subject': 'Physics',
  'question': 'The value of Wien’s constant is',
  'options': {'A': '2.90 x 10⁻³ mK', 'C': '4.22 x 10⁻⁷ mK', 'B': '3.34 x 10⁻⁴ mK', 'D': '3.42 x 10⁻⁸ mK'},
  'diagram_text': ''},
 {'number': 15,
  'subject': 'Physics',
  'question': 'The minimum frequency below which no electron is emitted from the metal surface is called',
  'options': {'A': 'High frequency', 'C': 'Threshold frequency', 'B': 'Low frequency', 'D': 'Resonance frequency'},
  'diagram_text': ''},
 {'number': 16,
  'subject': 'Physics',
  'question': 'In pair production, the type of photon used',
  'options': {'A': 'α-particle', 'C': 'X-rays', 'B': 'β-particle', 'D': 'γ-radiations'},
  'diagram_text': ''},
 {'number': 17,
  'subject': 'Physics',
  'question': 'The life time of an electron in an excited state is about 10⁻⁸ s. What is its uncertainty in energy during this time?',
  'options': {'A': '1.05 x 10⁻⁴¹ J', 'C': '1.15 x 10¹⁰ J', 'B': '1.05 x 10⁻²6 J', 'D': '2.19 x 10⁻⁴⁰ J'},
  'diagram_text': ''},
 {'number': 18,
  'subject': 'Physics',
  'question': 'Velocity of electron moving in first orbit of hydrogen is',
  'options': {'A': '2.19 x 10⁷ m/sec', 'C': '2.2 x 10⁸ m/sec', 'B': '2.18 x 10⁷ m/sec', 'D': '2.19 x 106 m/sec'},
  'diagram_text': ''},
 {'number': 19,
  'subject': 'Physics',
  'question': 'LASER is a potential energy source for inducing which type of reaction?',
  'options': {'A': 'Radioactive', 'C': 'Ionization', 'B': 'Fission', 'D': 'Fusion'},
  'diagram_text': ''},
 {'number': 20,
  'subject': 'Physics',
  'question': 'In the half-life of an element, the equation for the number of decaying atoms is given by',
  'options': {'A': 'ΔN ∝ -NΔt', 'C': 'ΔN ∝ -nΔt', 'B': 'ΔN = KNΔt', 'D': 'ΔN = -ΔNΔt'},
  'diagram_text': ''},
 {'number': 21,
  'subject': 'Physics',
  'question': 'Decay constant ‘λ’ is given as',
  'options': {'A': '- ∆N/N ∆t', 'C': '- N ∆t', 'B': '- ∆N ∆t', 'D': '∆N/N ∆t'},
  'diagram_text': ''},
 {'number': 22,
  'subject': 'Physics',
  'question': 'The SI unit of absorbed dose ‘D’ i.e. radiation effect is Gray and one Gray is equal to',
  'options': {'A': 'kJ / mol', 'C': 'kg / J', 'B': 'J / mol', 'D': 'J / kg'},
  'diagram_text': ''},
 {'number': 23,
  'subject': 'Physics',
  'question': 'The principle of homogeneity of dimensions determines',
  'options': {'A': 'Only variable in the equation',
              'C': 'Correctness of an equation',
              'B': 'Only constant in the equation',
              'D': 'Constant and variable in the equation'},
  'diagram_text': ''},
 {'number': 24,
  'subject': 'Physics',
  'question': 'For a body to be in complete equilibrium',
  'options': {'A': 'Linear acceleration is zero',
              'B': 'Angular acceleration is zero',
              'C': 'Linear acceleration is zero but angular acceleration is not zero',
              'D': 'Linear acceleration and angular acceleration both should be zero'},
  'diagram_text': ''},
 {'number': 25,
  'subject': 'Physics',
  'question': 'If length of a spanner is ‘I’ and a force ‘F’ is applied on it to tighten a nut such that it passes through the pivot '
              'point, then torque is',
  'options': {'A': 'Zero', 'C': 'Fl sin θ', 'B': 'Ff', 'D': 'Fl sin θλ'},
  'diagram_text': ''},
 {'number': 26,
  'subject': 'Physics',
  'question': 'If a force of magnitude 8 N acts on a body in direction making an angle 30, its x and y components will be',
  'options': {'A': 'Fx = 4√3 and Fy = 8', 'C': 'Fx = 4√3 and Fy = 4', 'B': 'Fx = 8 and Fy = 4√3', 'D': 'Fx = 8√3 and Fy = 4'},
  'diagram_text': ''},
 {'number': 27,
  'subject': 'Physics',
  'question': 'The difference of a vector B\x04\x04⃗ and its negative vector – \x07\x04⃗ is',
  'options': {'A': 'A null vector',
              'C': 'Twice the magnitude of vector B\x04⃗',
              'B': 'Equal to magnitude of vector B\x04⃗',
              'D': 'Smaller than magnitude of vector B\x04⃗'},
  'diagram_text': ''},
 {'number': 28,
  'subject': 'Physics',
  'question': 'Time of projectile’s flight is',
  'options': {'A': 'vi² sin2 θ g', 'C': 'vi² sin θ g', 'B': '2vi sin θ g', 'D': 'vi² g sin 2θ'},
  'diagram_text': ''},
 {'number': 29,
  'subject': 'Physics',
  'question': 'If the velocity of the body changes by equal amount in equal intervals of time, the body is said to have:',
  'options': {'A': 'variable acceleration', 'C': 'uniform velocity', 'B': 'uniform acceleration', 'D': 'negative acceleration'},
  'diagram_text': ''},
 {'number': 30,
  'subject': 'Physics',
  'question': 'In order to determine the maximum height of the projectile, the equation of motion used is',
  'options': {'A': 'aS = vf 2 - vi²', 'C': '2S = a vf 2 - vi²', 'B': '2aS = vf 2 - vi²', 'D': 'aS = 2 vf 2 - vi²'},
  'diagram_text': ''},
 {'number': 31,
  'subject': 'Physics',
  'question': 'If a force of 12 N acts on a car and changes its momentum from 36 kgm/sec to 60 kgm/sec, the time during which this change '
              'occurs will be',
  'options': {'A': '24 sec', 'C': '12 sec', 'B': '2 sec', 'D': '8 sec'},
  'diagram_text': ''},
 {'number': 32,
  'subject': 'Physics',
  'question': 'Which one of the following is a non-conservative force?',
  'options': {'A': 'Electric force', 'C': 'Gravitational force', 'B': 'Elastic spring force', 'D': 'Frictional force'},
  'diagram_text': ''},
 {'number': 33,
  'subject': 'Physics',
  'question': 'Value of escape velocity for the surface of the earth is 11 km/sec. Its value for surface of the moon is',
  'options': {'A': '11 km/sec', 'C': '2.4 km/sec', 'B': '10.4 km/sec', 'D': '4.3 km/sec'},
  'diagram_text': ''},
 {'number': 34,
  'subject': 'Physics',
  'question': 'On a clear day at noon, the intensity of solar energy reaching the earth’s surface is about',
  'options': {'A': '1.0 kWm-2', 'C': '1.0 Wm-2', 'B': '1.4 kWm-2', 'D': '1.4 Wm-2'},
  'diagram_text': ''},
 {'number': 35,
  'subject': 'Physics',
  'question': 'When a lift is accelerated upward, the apparent weight of an object in it will be',
  'options': {'A': 'Equal to its real weight', 'C': 'Zero', 'B': 'Less than its real weight', 'D': 'Greater than its real weight'},
  'diagram_text': ''},
 {'number': 36,
  'subject': 'Physics',
  'question': 'The moment of inertial of a thin rod is',
  'options': {'A': '1 2 mL2', 'C': '1 12 mL', 'B': '1 4 m3L', 'D': '1 12 mL2'},
  'diagram_text': ''},
 {'number': 37,
  'subject': 'Physics',
  'question': 'A wheel of radius 1 m covers an angular displacement of 180. Its linear displacement is',
  'options': {'A': '3.14 m', 'C': '6.28 m', 'B': 'π rad', 'D': '0.157 m'},
  'diagram_text': ''},
 {'number': 38,
  'subject': 'Physics',
  'question': 'Conservation of mass of fluid flow leads to',
  'options': {'A': 'Bernoulli’s equation', 'C': 'Equation of motion', 'B': 'Venturi meter', 'D': 'Equation of continuity'},
  'diagram_text': ''},
 {'number': 39,
  'subject': 'Physics',
  'question': 'The blood vessels collapse when',
  'options': {'A': 'External pressure applied becomes greater than the systolic pressure',
              'B': 'External pressure applied is equal to systolic pressure',
              'C': 'External pressure applied is less than the systolic pressure',
              'D': 'External pressure applied is zero'},
  'diagram_text': ''},
 {'number': 40,
  'subject': 'Physics',
  'question': 'An oscillating body is at mean position at t = 0. At t = T/4 it will be at',
  'options': {'A': 'Extreme position', 'C': 'Between extreme and mean position', 'B': 'Mean position', 'D': 'Beyond extreme position'},
  'diagram_text': ''},
 {'number': 41,
  'subject': 'Physics',
  'question': 'In a simple pendulum, the tension of the string is',
  'options': {'A': 'g cos θ', 'C': 'mg cos θ', 'B': 'mg sin θ', 'D': 'mg'},
  'diagram_text': ''},
 {'number': 42,
  'subject': 'Physics',
  'question': 'Two sound waves having the same amplitudes are moving in the same direction are out of phase. The amplitude of the '
              'resultant wave is',
  'options': {'A': 'Zero amplitude',
              'C': 'Difference of the amplitudes of the two waves',
              'B': 'The sum of amplitude of the two waves',
              'D': 'Double the amplitude of either wave'},
  'diagram_text': ''},
 {'number': 43,
  'subject': 'Physics',
  'question': 'A source ‘Y’ of unknown frequency produces 4 beats with a source of 240 Hz and 8 beats with a sound of 252 Hz. Frequency of '
              'the source ‘Y’ is',
  'options': {'A': '244 Hz', 'C': '248 Hz', 'B': '236 Hz', 'D': '246 Hz'},
  'diagram_text': ''},
 {'number': 44,
  'subject': 'Physics',
  'question': 'An organ pipe closed at one end has a length of 25 cm. Wavelength of the fundamental note is',
  'options': {'A': '25 cm', 'C': '100 cm', 'B': '50 cm', 'D': '75 cm'},
  'diagram_text': ''},
 {'number': 45,
  'subject': 'Physics',
  'question': 'In Newton ring apparatus, at the point of contact of the lens and glass plate, the additional path difference introduced is',
  'options': {'A': 'λ/4', 'C': 'λ', 'B': 'λ/2', 'D': 'λ/3'},
  'diagram_text': ''},
 {'number': 46,
  'subject': 'Physics',
  'question': 'The path difference ‘BD’ for destructive interference is',
  'options': {'A': '(m + ½) λ', 'C': 'd sin θ', 'B': 'mλ', 'D': '3λ'},
  'diagram_text': ''},
 {'number': 47,
  'subject': 'Physics',
  'question': 'In the case of a grafting spectrometer, the resolving power ‘R’ of the grating is defined as',
  'options': {'A': 'λ / Δλ', 'C': 'λ / λ1', 'B': 'λ / D', 'D': 'N x m'},
  'diagram_text': ''},
 {'number': 48,
  'subject': 'Physics',
  'question': 'Which one of the following lights travels fastest in optical fibers?',
  'options': {'A': 'Visible light', 'C': 'Ordinary light', 'B': 'Ultraviolet light', 'D': 'Invisible infrared light'},
  'diagram_text': ''},
 {'number': 49,
  'subject': 'Physics',
  'question': 'The value of universal gas constant is',
  'options': {'A': '8.314 Jmol-1K-1', 'C': '7.23 Jmol-1K-1', 'B': '8.324 Jmol-1K-1', 'D': '1.00 Jmol-1K-1'},
  'diagram_text': ''},
 {'number': 50,
  'subject': 'Physics',
  'question': 'The turbine in a steam power plant takes steam from a boiler at 427 °C and exhausts into a low temperature reservoir at 77 '
              '°C. What is the maximum possible efficiency?',
  'options': {'A': '50%', 'C': '60%', 'B': '40%', 'D': '70%'},
  'diagram_text': ''},
 {'number': 51,
  'subject': 'Physics',
  'question': 'Which one of the following is a postulate of kinetic theory of gases?',
  'options': {'A': 'Molecules do not exert force on each other',
              'B': 'The size of molecules is much larger than separation between the molecules',
              'C': 'A finite volume of gas consists of a very small number of molecules',
              'D': 'The gas molecules are not in random motion'},
  'diagram_text': ''},
 {'number': 52,
  'subject': 'Physics',
  'question': 'Which one is not an irreversible process?',
  'options': {'A': 'Slow compression of a gas into a cylinder',
              'C': 'Explosion',
              'B': 'Changes due to friction',
              'D': 'Dissipation of energy'},
  'diagram_text': ''},
 {'number': 53,
  'subject': 'Physics',
  'question': 'Electric intensity is a vector quantity and its direction is',
  'options': {'A': 'Perpendicular to the direction of field',
              'C': 'At a certain angle',
              'B': 'Opposite to the direction of force',
              'D': 'Along the direction of force'},
  'diagram_text': ''},
 {'number': 54,
  'subject': 'Physics',
  'question': 'The magnitude of an electric field between two separated plates can be calculated by the relation',
  'options': {'A': 'ΔV = Ed', 'C': 'ΔV = E qo', 'B': 'ΔV = E/d', 'D': 'E = d ΔV'},
  'diagram_text': ''},
 {'number': 55,
  'subject': 'Physics',
  'question': 'SI unit of electric flux is',
  'options': {'A': 'NmC-1', 'C': 'Nm2C-2', 'B': 'Nm-2C-2', 'D': 'Nm2C-2'},
  'diagram_text': ''},
 {'number': 56,
  'subject': 'Physics',
  'question': 'The equivalent current which passes from a point at higher potential to a point at a lower potential as if it represented a '
              'movement of positive charges is',
  'options': {'A': 'Electronic current', 'C': 'Magnetic lines', 'B': 'Electric current', 'D': 'Conventional current'},
  'diagram_text': ''},
 {'number': 57,
  'subject': 'Physics',
  'question': 'If ‘V’ is applied potential difference across a resistance ‘R’, then loss in potential energy per unit time is',
  'options': {'A': 'VI', 'C': 'V2 R', 'B': 'I2R', 'D': 'All of the above'},
  'diagram_text': ''},
 {'number': 58,
  'subject': 'Physics',
  'question': 'The substances like germanium and silicon have',
  'options': {'A': 'Negative temperature coefficients',
              'C': 'Both A and B',
              'B': 'Positive temperature coefficients',
              'D': 'None of the above'},
  'diagram_text': ''},
 {'number': 59,
  'subject': 'Physics',
  'question': 'The sensitivity of a galvanometer can be decreased by',
  'options': {'A': 'Increasing magnetic field',
              'C': 'Increasing c BAN Ration',
              'B': 'Increasing number of turns of the coil',
              'D': 'Decreasing length of couple ‘c’'},
  'diagram_text': ''},
 {'number': 60,
  'subject': 'Physics',
  'question': 'Force on a current carrying conductor in a uniform magnetic field is',
  'options': {'A': 'F = NIA cos α', 'C': 'F = ILB sin α', 'B': 'F = μnI', 'D': 'F = ILA cos α'},
  'diagram_text': ''},
 {'number': 61,
  'subject': 'Chemistry',
  'question': 'In an electrochemical series, standard electrode potentials are arranged on the basis of:',
  'options': {'A': 'pH scale', 'C': 'Hydrogen Scale', 'B': 'pOH scale', 'D': 'pKa scale'},
  'diagram_text': ''},
 {'number': 62,
  'subject': 'Chemistry',
  'question': 'The reaction which is responsible for the production of electricity in the Voltaic cell is:',
  'options': {'A': 'Hydrolysis reaction', 'C': 'Redox reaction', 'B': 'Oxidation reaction', 'D': 'Reduction reaction'},
  'diagram_text': ''},
 {'number': 63,
  'subject': 'Chemistry',
  'question': 'Glucose is converted into ethanol by the enzyme _______ present in yeast:',
  'options': {'A': 'Urease', 'C': 'Sucrase', 'B': 'Invertase', 'D': 'Zymase'},
  'diagram_text': ''},
 {'number': 64,
  'subject': 'Chemistry',
  'question': 'The rate of reaction involving ions can be studied by __________ method',
  'options': {'A': 'Dilatometric', 'C': 'Optical rotation', 'B': 'Refractometric', 'D': 'Electrical conductivity'},
  'diagram_text': ''},
 {'number': 65,
  'subject': 'Chemistry',
  'question': 'When one mole of gaseous hydrogen ions are dissolved in water to form an infinitely dilute solution, the amount of heat '
              'liberated is',
  'options': {'A': '-1891 kJmol-1', 'C': '-499 kJmol-1', 'B': '-10⁷5 kJmol-1', 'D': '-1562 kJmol-1'},
  'diagram_text': ''},
 {'number': 66,
  'subject': 'Chemistry',
  'question': 'Energy required to remove an electron from the outermost shell of its isolated gaseous atom in the ground state is',
  'options': {'A': 'Electron affinity', 'C': 'Ionization energy', 'B': 'Lattice energy', 'D': 'Crystal energy'},
  'diagram_text': ''},
 {'number': 67,
  'subject': 'Chemistry',
  'question': 'Which of the following carbonates of alkali metals is not stable towards heat and is decomposed on heating to its oxide '
              'along with liberation of CO2?',
  'options': {'A': 'Li2CO3', 'C': 'K2CO3', 'B': 'Mg2CO3', 'D': 'Na2CO3'},
  'diagram_text': ''},
 {'number': 68,
  'subject': 'Chemistry',
  'question': 'The presence of calcium is essential for the normal development of plants. An adequate supply of calcium appears to '
              'stimulate the development of which part of the plants?',
  'options': {'A': 'Leaves', 'C': 'Root hairs', 'B': 'Fruits', 'D': 'Branches'},
  'diagram_text': ''},
 {'number': 69,
  'subject': 'Chemistry',
  'question': 'Which of the following sulphates is not soluble in water?',
  'options': {'A': 'Sodium Sulphate', 'C': 'Potassium Sulphate', 'B': 'Barium Sulphate', 'D': 'Zinc Sulphate'},
  'diagram_text': ''},
 {'number': 70,
  'subject': 'Chemistry',
  'question': 'The trend in the densities of elements of Group III-A of the Periodic Table is',
  'options': {'A': 'A gradual increase',
              'C': 'First decrease then increase',
              'B': 'A gradual decrease',
              'D': 'First increase then decrease'},
  'diagram_text': ''},
 {'number': 71,
  'subject': 'Chemistry',
  'question': 'White lead has one of the following properties',
  'options': {'A': 'Acidic', 'C': 'Amorphous', 'B': 'Crystalline', 'D': 'Neutral'},
  'diagram_text': ''},
 {'number': 72,
  'subject': 'Chemistry',
  'question': 'The strongest acid among the following is',
  'options': {'A': 'HF', 'C': 'HCl', 'B': 'HI', 'D': 'HBr'},
  'diagram_text': ''},
 {'number': 73,
  'subject': 'Chemistry',
  'question': 'The noble gas which is used in radiotherapy of cancer is',
  'options': {'A': 'Radon', 'C': 'Krypton', 'B': 'Xenon', 'D': 'Argon'},
  'diagram_text': ''},
 {'number': 74,
  'subject': 'Chemistry',
  'question': 'Paramagnetic behavior of an atom, ion or molecule is due to presence of',
  'options': {'A': 'Unpaired electrons', 'C': 'Protons', 'B': 'Paired electrons', 'D': 'Neutrons'},
  'diagram_text': ''},
 {'number': 75,
  'subject': 'Chemistry',
  'question': 'The geometry of the complexes depends upon the type of ________ taking place in the valence shell of the central metal atom',
  'options': {'A': 'Hybridization', 'C': 'Deprotonation', 'B': 'Protonation', 'D': 'Dissociation'},
  'diagram_text': ''},
 {'number': 76,
  'subject': 'Chemistry',
  'question': 'KMnO4 acts as a',
  'options': {'A': 'Reducing agent', 'C': 'Germicide', 'B': 'Excellent precipitating reagent', 'D': 'Oxidizing agent'},
  'diagram_text': ''},
 {'number': 77,
  'subject': 'Chemistry',
  'question': 'A gasoline of higher octane number can be obtained by',
  'options': {'A': 'Oxidative cleavage', 'C': 'Catalytic cracking', 'B': 'Thermal cracking', 'D': 'Steam cracking'},
  'diagram_text': ''},
 {'number': 78,
  'subject': 'Chemistry',
  'question': 'Ethyne molecule is formed when two carbon atoms joined together to form a sigma bond by',
  'options': {'A': 'sp-s overlap', 'C': '2py-2py overlap', 'B': 'sp3-sp3 overlap', 'D': 'sp-sp overlap'},
  'diagram_text': ''},
 {'number': 79,
  'subject': 'Chemistry',
  'question': 'Symmetrical alkanes can be produced by',
  'options': {'A': 'Sabatier Sender’s Reaction',
              'C': 'Reduction Reaction',
              'B': 'Hydrogenolysis Reaction',
              'D': 'Kolbe’s Electrolytic Reaction'},
  'diagram_text': ''},
 {'number': 80,
  'subject': 'Chemistry',
  'question': 'The catalyst used for the preparation of acrylonitrile is',
  'options': {'A': 'Cu2Cl2 and NH4Cl', 'C': 'Cu2Cl2 and NH4OH', 'B': 'Al2O3 and NH4Cl', 'D': 'Cu2Cl2 and Al2O3'},
  'diagram_text': ''},
 {'number': 81,
  'subject': 'Chemistry',
  'question': 'When a hydrogen atom is removed from benzene, the group left behind is called',
  'options': {'A': 'Alkyl group', 'C': 'Benzyl group', 'B': 'Phenyl group', 'D': 'Methyl group'},
  'diagram_text': ''},
 {'number': 82,
  'subject': 'Chemistry',
  'question': 'The introduction of NO2 group in benzene ring is called ‘Nitration’. The nitration of benzene takes place when it is heated '
              'with a 1:1 mixture of _________ at 50 oC-55 oC.',
  'options': {'A': 'Conc. HNO3 and conc. HCl',
              'C': 'Conc. HNO3 and H3PO4',
              'B': 'Conc. HNO3 and conc. Acetic acid',
              'D': 'Conc. HNO3 and conc. H2SO4'},
  'diagram_text': ''},
 {'number': 83,
  'subject': 'Chemistry',
  'question': 'During SN2 reactions, configuration of the alkyl halide molecule:',
  'options': {'A': 'Gets inverted',
              'C': 'Depends upon the carbon atom',
              'B': 'Remains same',
              'D': 'Depends upon the electronegativity of halide'},
  'diagram_text': ''},
 {'number': 84,
  'subject': 'Chemistry',
  'question': 'Grignard reagents are prepared by the reaction of magnesium metal with alkyl halides in the presence of',
  'options': {'A': 'Dry Ether', 'C': 'Alcohol', 'B': 'Sodium Lead Alloy', 'D': 'Water'},
  'diagram_text': ''},
 {'number': 85,
  'subject': 'Chemistry',
  'question': 'Methanol is prepared from carbon monoxide and hydrogen. The catalyst used for this reaction is',
  'options': {'A': 'ZnO + CoO2', 'C': 'ZnO + Ag2O', 'B': 'ZnO + CuO', 'D': 'Cr2O3 + ZnO'},
  'diagram_text': ''},
 {'number': 86,
  'subject': 'Chemistry',
  'question': 'Ethanol reacts with Ammonia to produce ethyl amine, the catalyst is',
  'options': {'A': 'ZnCl2', 'C': 'C6H5N', 'B': 'ThO2', 'D': 'Cr2O3'},
  'diagram_text': ''},
 {'number': 87,
  'subject': 'Chemistry',
  'question': 'Dissociation constant of phenol is',
  'options': {'A': '1.2 x 10-10', 'C': '1.3 x 10¹⁰', 'B': '1.2 x 10¹⁰', 'D': '1.3 x 10-10'},
  'diagram_text': ''},
 {'number': 88,
  'subject': 'Chemistry',
  'question': 'Dry distillation of a mixture of calcium salts of formic acid and acetic acid results into the formation of',
  'options': {'A': 'Formaldehyde', 'C': 'Calcium acetate', 'B': 'Acetaldehyde', 'D': 'Sodium acetate'},
  'diagram_text': ''},
 {'number': 89,
  'subject': 'Chemistry',
  'question': 'Hydrolysis of cyano group by an aqueous acid results into',
  'options': {'A': 'Carboxylic Acid', 'C': 'Cyanohydride', 'B': 'Acid Amide', 'D': 'Formaldehyde'},
  'diagram_text': ''},
 {'number': 90,
  'subject': 'Chemistry',
  'question': 'Brick red precipitates are formed when aldehydes react with',
  'options': {'A': 'Sodium borohydride', 'C': 'Sodium nitroprusside', 'B': 'Sodium bisulphite', 'D': 'Fehling’s solution'},
  'diagram_text': ''},
 {'number': 91,
  'subject': 'Chemistry',
  'question': 'The nature of the amino acid ‘lysine’ is',
  'options': {'A': 'Neutral', 'C': 'Amphoteric', 'B': 'Acidic', 'D': 'Basic'},
  'diagram_text': ''},
 {'number': 92,
  'subject': 'Chemistry',
  'question': 'Which of the following compounds, in the form of aqueous solution, on reaction with sodium carbonate will produce carbon '
              'dioxide gas?',
  'options': {'A': 'H3C-COO-C2H5', 'C': 'H3C2-CO-OH', 'B': 'H3C2-COO-CH3', 'D': 'H3C2-COO-C2H5'},
  'diagram_text': ''},
 {'number': 93,
  'subject': 'Chemistry',
  'question': 'Collagen and albumin are',
  'options': {'A': 'Simple proteins', 'C': 'Polyamides', 'B': 'Derived proteins', 'D': 'Polysaccharides'},
  'diagram_text': ''},
 {'number': 94,
  'subject': 'Chemistry',
  'question': 'Urea is produced by the reaction of liquid ammonia with',
  'options': {'A': 'CO2', 'C': 'CaO', 'B': 'CO', 'D': 'C'},
  'diagram_text': ''},
 {'number': 95,
  'subject': 'Chemistry',
  'question': 'The calcium sulpho-aluminate is',
  'options': {'A': 'Co.Al2O3.3CaSO4.6H2O', 'C': '3Ca.Al2O3.3CaSO4.2H2O', 'B': '3Ca.Al2O3.CaSO4.2H2O', 'D': '3Ca.Al2O3.3CaSO4.6H2O'},
  'diagram_text': ''},
 {'number': 96,
  'subject': 'Chemistry',
  'question': 'The coagulant used in raw water to precipitate suspended impurities is',
  'options': {'A': 'Caustic soda', 'C': 'Alum', 'B': 'Lime water', 'D': 'Soda ash'},
  'diagram_text': ''},
 {'number': 97,
  'subject': 'Chemistry',
  'question': 'The whiteness of the recycled newspaper is improved by treating it with:',
  'options': {'A': 'Sodium hydroxide', 'C': 'Super oxides', 'B': 'Per oxides', 'D': 'Normal oxides'},
  'diagram_text': ''},
 {'number': 98,
  'subject': 'Chemistry',
  'question': 'One mole of any gas at standard temperature and pressure (STP) occupies a volume of',
  'options': {'A': '20.414 dm3', 'C': '22.414 cm3', 'B': '22.414 dm3', 'D': '23.414 dm3'},
  'diagram_text': ''},
 {'number': 99,
  'subject': 'Chemistry',
  'question': 'The relative abundance of the isotopes of the elements can be determined by:',
  'options': {'A': 'Mass Spectrometry', 'C': 'Chromatography', 'B': 'X-rays', 'D': 'Solvent Extraction'},
  'diagram_text': ''},
 {'number': 100,
  'subject': 'Chemistry',
  'question': 'If we are given the mass of one substance, we can calculate volume of other substances and vice a versa with the help of '
              'balanced chemical equation. This is called',
  'options': {'A': 'Mass-mass relationship',
              'C': 'Mole-volume relationship',
              'B': 'Mass-mole relationship',
              'D': 'Mass-volume relationship'},
  'diagram_text': ''},
 {'number': 101,
  'subject': 'Chemistry',
  'question': 'Sublimation is used to purify',
  'options': {'A': 'Ammonium sulphate', 'C': 'Benzoic acid', 'B': 'Sodium chloride', 'D': 'Lead carbonate'},
  'diagram_text': ''},
 {'number': 102,
  'subject': 'Chemistry',
  'question': 'The purity of a substance can be identified by',
  'options': {'A': 'Sublimation', 'C': 'Chromatography', 'B': 'Filtration', 'D': 'Solvent extraction'},
  'diagram_text': ''},
 {'number': 103,
  'subject': 'Chemistry',
  'question': 'Which one of the following mathematical expressions represents the Avogadro’s law?',
  'options': {'A': 'V= R nT P (when ‘T’ and ‘n’ are constant)',
              'C': 'V= R P nT (when ‘P’ and ‘n’ are constant)',
              'B': 'V= R nT P (when ‘P’, ‘T’ and ‘n’ are constant)',
              'D': 'V= R nT P (when ‘P’ and ‘T’ are constant)'},
  'diagram_text': ''},
 {'number': 104,
  'subject': 'Chemistry',
  'question': 'The root mean square velocity of gases is inversely proportional to the square root of their:',
  'options': {'A': 'Molar mass', 'C': 'Pressure', 'B': 'Temperature', 'D': 'Volume'},
  'diagram_text': ''},
 {'number': 105,
  'subject': 'Chemistry',
  'question': 'Plasma is the ionized gas mixture which consists of',
  'options': {'A': 'Ions and electrons',
              'C': 'Electrons, ions and neutral atoms',
              'B': 'Electrons and neutral atoms',
              'D': 'Ions and neutral atoms'},
  'diagram_text': ''},
 {'number': 106,
  'subject': 'Chemistry',
  'question': 'Which type of force is present in gasoline?',
  'options': {'A': 'Dipole-dipole forces', 'C': 'London dispersion forces', 'B': 'Dipole-induced dipole forces', 'D': 'hydrogen bonding'},
  'diagram_text': ''},
 {'number': 107,
  'subject': 'Chemistry',
  'question': 'In the structure of NaCl, each Na+ is surrounded by _____ Cl- ions.',
  'options': {'A': 'Four', 'C': 'Five', 'B': 'Eight', 'D': 'Six'},
  'diagram_text': ''},
 {'number': 108,
  'subject': 'Chemistry',
  'question': 'The charge of one gram of electron is',
  'options': {'A': '1.7588 x 10-11', 'C': '1.602 x 10⁻¹⁹', 'B': '1.7588 x 10¹¹', 'D': '1.7588 x 10⁸'},
  'diagram_text': ''},
 {'number': 109,
  'subject': 'Chemistry',
  'question': 'The ionization energy of hydrogen atom is',
  'options': {'A': 'Zero', 'C': '1313.31 kJmol-1', 'B': '13.13 kJmol-1', 'D': '1313.31 k2Jmol'},
  'diagram_text': ''},
 {'number': 110,
  'subject': 'Chemistry',
  'question': 'Which quantum number helps to study the orientation of an orbital in space?',
  'options': {'A': 'Principal Quantum Number', 'C': 'Magnetic Quantum Number', 'B': 'Spin Quantum Number', 'D': 'Azimuthal Quantum Number'},
  'diagram_text': ''},
 {'number': 111,
  'subject': 'Chemistry',
  'question': 'The inter-ionic distance in a crystal lattice of KCl is',
  'options': {'A': '314 pm', 'C': '95 pm', 'B': '181 pm', 'D': '300 pm'},
  'diagram_text': ''},
 {'number': 112,
  'subject': 'Chemistry',
  'question': 'The number of bonds in nitrogen molecule is',
  'options': {'A': 'One σ and two π', 'B': 'One σ and one π', 'C': 'Three σ only', 'D': 'Two σ and one π'},
  'diagram_text': ''},
 {'number': 113,
  'subject': 'Chemistry',
  'question': 'Which one of the following molecules has zero dipole moment?',
  'options': {'A': 'NH3', 'C': 'BF3', 'B': 'CHCl3', 'D': 'H2O'},
  'diagram_text': ''},
 {'number': 114,
  'subject': 'Chemistry',
  'question': 'A spontaneous process is',
  'options': {'A': 'Unidirectional and irreversible',
              'C': 'Unidirectional and a real process',
              'B': 'Irreversible and a real process',
              'D': 'All of the above'},
  'diagram_text': ''},
 {'number': 115,
  'subject': 'Chemistry',
  'question': 'The standard enthalpy of solution of NH4Cl is ____________ kJmol-1.',
  'options': {'A': '+16.2', 'C': '+4.98', 'B': '-25.0', 'D': '+26.0'},
  'diagram_text': ''},
 {'number': 116,
  'subject': 'Chemistry',
  'question': 'The Kc has following units for the reaction H2(g) + I2(g) ⇋ 2HI (g)',
  'options': {'A': 'mol3dm-6', 'C': 'mol-3dm6', 'B': 'moldm-3', 'D': 'No unit'},
  'diagram_text': ''},
 {'number': 117,
  'subject': 'Chemistry',
  'question': '0.1 mole of acetic acid has been dissolved per dm3 of the solution, the percentage ionization of acetic acid will be',
  'options': {'A': '13', 'C': '1.3', 'B': '15', 'D': '0.1'},
  'diagram_text': ''},
 {'number': 118,
  'subject': 'Chemistry',
  'question': 'Solubility of Ce2(SO4)3',
  'options': {'A': 'Increases with temperature',
              'C': 'Shows exceptional behavior',
              'B': 'Decreases with temperature',
              'D': 'Remains constant'},
  'diagram_text': ''},
 {'number': 119,
  'subject': 'Chemistry',
  'question': 'Seawater has 5.65 x 10⁻³ g of dissolved oxygen in one kilogram of water. Concentration of O2 in parts per million is',
  'options': {'A': '5.65', 'C': '5.20', 'B': '7.69', 'D': '4.11'},
  'diagram_text': ''},
 {'number': 120,
  'subject': 'Chemistry',
  'question': 'Metallic conduction involves the relatively free movement of their _________ throughout the metallic lattice',
  'options': {'A': 'Atoms', 'C': 'Electrons', 'B': 'Molecules', 'D': 'Ions'},
  'diagram_text': ''},
 {'number': 121,
  'subject': 'English',
  'question': 'My advice had no ______________ on him.',
  'options': {'A': 'Effect', 'C': 'Influence', 'B': 'Affect', 'D': 'Impression'},
  'diagram_text': ''},
 {'number': 122,
  'subject': 'English',
  'question': 'Do not lose heart, it is just a __________ in the tea cup',
  'options': {'A': 'Wind', 'C': 'Blast', 'B': 'Cyclone', 'D': 'Storm'},
  'diagram_text': ''},
 {'number': 123,
  'subject': 'English',
  'question': 'Pakistan __________ from voting against Iran in the United Nations',
  'options': {'A': 'Prevented', 'C': 'Abstained', 'B': 'Detained', 'D': 'Refused'},
  'diagram_text': ''},
 {'number': 124,
  'subject': 'English',
  'question': 'Please ____________ the door after you.',
  'options': {'A': 'Close',
              'C': 'Leave',
              'B': 'Shut',
              'D': 'Knock SPOT THE ERROR: In the following sentences, some segments of each sentence are underlined. Your task is to '
                   'identify that underlined segment of the sentence, which contains the mistake that needs to be corrected. Fill the '
                   'Circle corresponding to that letter under the segment in the MCQ Response From.'},
  'diagram_text': ''},
 {'number': 125,
  'subject': 'English',
  'question': 'Suddenly he stopped at the edge of the meadow, taking his pocket knife from his pocket, and cut a wisp of alfalfa.',
  'options': {'A': 'Underlined segment A in the original sentence',
              'B': 'Underlined segment B in the original sentence',
              'C': 'Underlined segment C in the original sentence',
              'D': 'Underlined segment D in the original sentence'},
  'diagram_text': ''},
 {'number': 126,
  'subject': 'English',
  'question': 'The study of population growth indicates one of the greatest paradox of our time.',
  'options': {'A': 'Underlined segment A in the original sentence',
              'B': 'Underlined segment B in the original sentence',
              'C': 'Underlined segment C in the original sentence',
              'D': 'Underlined segment D in the original sentence'},
  'diagram_text': ''},
 {'number': 127,
  'subject': 'English',
  'question': 'Among the Western nations, the decline in the death rate is followed after an interval by the reduction in the birth rate, '
              'so that the population is not now growing so fast.',
  'options': {'A': 'Underlined segment A in the original sentence',
              'B': 'Underlined segment B in the original sentence',
              'C': 'Underlined segment C in the original sentence',
              'D': 'Underlined segment D in the original sentence'},
  'diagram_text': ''},
 {'number': 128,
  'subject': 'English',
  'question': 'In view of increasing hazards with our national security it is the duty of every citizen to keep a watch on his '
              'surroundings.',
  'options': {'A': 'Underlined segment A in the original sentence',
              'B': 'Underlined segment B in the original sentence',
              'C': 'Underlined segment C in the original sentence',
              'D': 'Underlined segment D in the original sentence'},
  'diagram_text': ''},
 {'number': 129,
  'subject': 'English',
  'question': 'Thrifty housewives preserved their homegrown vegetables and fruits in canning, pickling or drying them for use during the '
              'cold weather.',
  'options': {'A': 'Underlined segment A in the original sentence',
              'B': 'Underlined segment B in the original sentence',
              'C': 'Underlined segment C in the original sentence',
              'D': 'Underlined segment D in the original sentence'},
  'diagram_text': ''},
 {'number': 130,
  'subject': 'English',
  'question': 'When a low-wage category worker finds he has to maintain a large family, his expenses may exceeds his income. In each of '
              'the following question, four alternative sentences are given. Choose the CORRECT one and fill the Circle corresponding to '
              'that letter in the MCQ Response Form.',
  'options': {'A': 'Underlined segment A in the original sentence',
              'B': 'Underlined segment B in the original sentence',
              'C': 'Underlined segment C in the original sentence',
              'D': 'Underlined segment D in the original sentence'},
  'diagram_text': ''},
 {'number': 131,
  'subject': 'English',
  'question': '',
  'options': {'A': 'This is different to what had been expected.',
              'C': 'This is different from what had been expected.',
              'B': 'This is different what had been expected.',
              'D': 'This is different to what would be expected.'},
  'diagram_text': ''},
 {'number': 132,
  'subject': 'English',
  'question': '',
  'options': {'A': 'He suddenly remembered that he has left his house unlocked.',
              'B': 'He suddenly remembered that he may have left his house unlocked.',
              'C': 'He suddenly remembered that he had left his house unlocked.',
              'D': 'He suddenly remembered that he will have left his house unlocked.'},
  'diagram_text': ''},
 {'number': 133,
  'subject': 'English',
  'question': '',
  'options': {'A': 'He asked us would we care to go.',
              'C': 'He asked us we would care to go.',
              'B': 'He asked us if we would care to go.',
              'D': 'He asked us we will care to go.'},
  'diagram_text': ''},
 {'number': 134,
  'subject': 'English',
  'question': '',
  'options': {'A': 'When this war is over, no nation will either be isolated in war or peace.',
              'B': 'When this war is over, no nation will be either isolated in war or peace.',
              'C': 'When this war is over, no nation will neither be isolated in war nor peace.',
              'D': 'When this war is over, no nation will be isolated either in war or in peace.'},
  'diagram_text': ''},
 {'number': 135,
  'subject': 'English',
  'question': '',
  'options': {'A': 'When the fact failed him, he questions his senses.',
              'B': 'When the fact failed him, he questioned from his senses.',
              'C': 'When the fact fails him, he questions his senses.',
              'D': 'He will question his senses, when the fact will fail him.'},
  'diagram_text': ''},
 {'number': 136,
  'subject': 'English',
  'question': '',
  'options': {'A': 'He said there has been no need to do it.',
              'C': 'He said there had been not any need doing it.',
              'B': 'He said there wasn’t no need to do it.',
              'D': 'He said there was no need to do it.'},
  'diagram_text': ''},
 {'number': 137,
  'subject': 'English',
  'question': '',
  'options': {'A': 'I could barely make of the traffic sings through the rain.',
              'B': 'I could barely make out the traffic signs because of the rain.',
              'C': 'I could barely make up the traffic sings through the rain.',
              'D': 'I could barely make with the traffic signs through the rain.'},
  'diagram_text': ''},
 {'number': 138,
  'subject': 'English',
  'question': '',
  'options': {'A': 'He walked as though he is lame.',
              'C': 'He walked as though he were lame.',
              'B': 'He walked as though he was lame.',
              'D': 'He walked as though he may have been lame.'},
  'diagram_text': ''},
 {'number': 139,
  'subject': 'English',
  'question': '',
  'options': {'A': 'E-mail is a relatively new means of communication.',
              'C': 'E-mail is a relatively new mean to communication.',
              'B': 'E-mail is a relatively new mean of communication.',
              'D': 'E-mail is a relatively new means to communication.'},
  'diagram_text': ''},
 {'number': 140,
  'subject': 'English',
  'question': '',
  'options': {'A': 'The remain of the body was thrown into the sea.',
              'C': 'The remains of the body were thrown to the sea.',
              'B': 'The remains of the body were thrown into the sea.',
              'D': 'The remains of the body was thrown into the sea. In each of the following question, four alternative meanings of a '
                   'word are given. You have to select the NEAREST CORRECT MEANING of the given word and fill the appropriate Circle on '
                   'the MCQ Response Form.'},
  'diagram_text': ''},
 {'number': 141,
  'subject': 'English',
  'question': 'WALLOW',
  'options': {'A': 'Roll about', 'C': 'Protest', 'B': 'Mock', 'D': 'Borrow'},
  'diagram_text': ''},
 {'number': 142,
  'subject': 'English',
  'question': 'CONNOISSEUR',
  'options': {'A': 'Guide', 'C': 'Expert critic of art', 'B': 'Artist', 'D': 'Teacher'},
  'diagram_text': ''},
 {'number': 143,
  'subject': 'English',
  'question': 'ECCENTRIC',
  'options': {'A': 'Lunatic', 'C': 'Upset', 'B': 'Stern', 'D': 'Odd'},
  'diagram_text': ''},
 {'number': 144,
  'subject': 'English',
  'question': 'BOULDER',
  'options': {'A': 'Rounded stone / hill', 'C': 'Magnanimity', 'B': 'Builder', 'D': 'Magnitude'},
  'diagram_text': ''},
 {'number': 145,
  'subject': 'English',
  'question': 'SLUMBER',
  'options': {'A': 'Heap', 'C': 'Knee', 'B': 'Humble', 'D': 'Sleep'},
  'diagram_text': ''},
 {'number': 146,
  'subject': 'English',
  'question': 'EXCREMENT',
  'options': {'A': 'Increment', 'C': 'Excitement', 'B': 'Waste matter expelled from body', 'D': 'Disagreement'},
  'diagram_text': ''},
 {'number': 147,
  'subject': 'English',
  'question': 'VISAGE',
  'options': {'A': 'Vision', 'C': 'Trunk less', 'B': 'Illusion', 'D': 'A person’s face'},
  'diagram_text': ''},
 {'number': 148,
  'subject': 'English',
  'question': 'FELICITY',
  'options': {'A': 'Intense Happiness', 'C': 'Inspire', 'B': 'Respite', 'D': 'Sensational'},
  'diagram_text': ''},
 {'number': 149,
  'subject': 'English',
  'question': 'ENMESHED',
  'options': {'A': 'Sojourn', 'C': 'Gallows', 'B': 'Entangled', 'D': 'Cascade'},
  'diagram_text': ''},
 {'number': 150,
  'subject': 'English',
  'question': 'CAPTIVATE',
  'options': {'A': 'Hesitate', 'C': 'Hate', 'B': 'Concentrate', 'D': 'Fascinate'},
  'diagram_text': ''},
 {'number': 151,
  'subject': 'Biology',
  'question': 'Book lungs are present in arthropods for exchange of gases in class:',
  'options': {'A': 'Crustacea', 'C': 'Myriapoda', 'B': 'Insecta', 'D': 'Arachnida'},
  'diagram_text': ''},
 {'number': 152,
  'subject': 'Biology',
  'question': 'Larvae of which group are similar to chordates?',
  'options': {'A': 'Echinodermata', 'C': 'Arthropoda', 'B': 'Annelida', 'D': 'Nematoda'},
  'diagram_text': ''},
 {'number': 153,
  'subject': 'Biology',
  'question': 'Type of respiration which involves step by step breakdown of carbon chain molecules in the cell is called:',
  'options': {'A': 'External respiration', 'C': 'Pulmonary respiration', 'B': 'Cellular respiration', 'D': 'Cutaneous respiration'},
  'diagram_text': ''},
 {'number': 154,
  'subject': 'Biology',
  'question': 'Instrument which is used to measure relative abilities of different pigments to absorb different wavelengths of light is '
              'called:',
  'options': {'A': 'Spectrometer', 'C': 'Barometer', 'B': 'Photometer', 'D': 'Spectrophotometer'},
  'diagram_text': ''},
 {'number': 155,
  'subject': 'Biology',
  'question': 'End products of yeast fermentation, bacterial fermentation and anaerobic respiration are',
  'options': {'A': 'Citric acid, lactic acid, carbon dioxide and water',
              'C': 'Ethyl alcohol, lactic acid, carbon dioxide and water',
              'B': 'Ethyl alcohol, citric acid and carbon dioxide',
              'D': 'Methanol, lactic acid and citric acid'},
  'diagram_text': ''},
 {'number': 156,
  'subject': 'Biology',
  'question': 'In human beings, what is the function of amylase in digestion?',
  'options': {'A': 'Digestion of triglycerides',
              'C': 'Digestion of all types of food',
              'B': 'Digestion of lipids',
              'D': 'Digestion of carbohydrates'},
  'diagram_text': ''},
 {'number': 157,
  'subject': 'Biology',
  'question': 'Where is the ileocolic sphincter located in your body?',
  'options': {'A': 'At the junction of esophagus and stomach',
              'C': 'At the junction of ileum and large intestine',
              'B': 'At the junction of stomach and small intestine',
              'D': 'At the junction of small intestine and large intestine'},
  'diagram_text': ''},
 {'number': 158,
  'subject': 'Biology',
  'question': 'The term which is employed to the loss of appetite due to fear of becoming obese is',
  'options': {'A': 'Obesity', 'C': 'Dyspepsia', 'B': 'Anorexia nervosa', 'D': 'Bulimia nervosa'},
  'diagram_text': ''},
 {'number': 159,
  'subject': 'Biology',
  'question': 'Which one of the following acts as functional unit of lungs in man?',
  'options': {'A': 'Air sac', 'C': 'Trachea', 'B': 'Larynx', 'D': 'Bronchioles'},
  'diagram_text': ''},
 {'number': 160,
  'subject': 'Biology',
  'question': 'Which one of following factors is directly proportional to oxygen carrying capacity of haemoglobin?',
  'options': {'A': 'Carbon dioxide', 'C': 'pH', 'B': 'Temperature', 'D': 'Light'},
  'diagram_text': ''},
 {'number': 161,
  'subject': 'Biology',
  'question': 'Expiration in human beings is carried out by',
  'options': {'A': 'Contraction of lungs',
              'C': 'Relaxation of intercostal and diaphragm muscles',
              'B': 'Contraction of intercostal membrane',
              'D': 'Contraction of diaphragm muscles'},
  'diagram_text': ''},
 {'number': 162,
  'subject': 'Biology',
  'question': 'Which one of the following is a precursor of steroid hormones?',
  'options': {'A': 'Glycerol', 'C': 'Amino acids', 'B': 'Sterol', 'D': 'Cholesterol'},
  'diagram_text': ''},
 {'number': 163,
  'subject': 'Biology',
  'question': 'Granulocytes or white blood cells are produced in',
  'options': {'A': 'Lymph nodes', 'C': 'Tonsils', 'B': 'Red bone marrow', 'D': 'Spleen'},
  'diagram_text': ''},
 {'number': 164,
  'subject': 'Biology',
  'question': 'Which one of the following statements best describes the function of sinoatrial node?',
  'options': {'A': 'It sends out electrical impulses to atrial muscles causing both atria to contract.',
              'B': 'It consists of small number of diffusely oriented cardiac fibres',
              'C': 'It sends out electrical impulses to ventricular muscles causing both ventricles to contract',
              'D': 'It is present at upper end of left atrium.'},
  'diagram_text': ''},
 {'number': 165,
  'subject': 'Biology',
  'question': 'The flow of lymph in lymphatic vessels is maintained by:',
  'options': {'A': 'Heart, activity of smooth muscles and valves',
              'B': 'Activity of skeletal muscles, heart and breathing movements',
              'C': 'Breathing movements, activity of skeletal muscles and valves',
              'D': 'Exercise, breathing movements and heart'},
  'diagram_text': ''},
 {'number': 166,
  'subject': 'Biology',
  'question': 'Metabolic waste from metabolism of nucleic acid is',
  'options': {'A': 'Uric acid', 'C': 'Urea', 'B': 'Creatine', 'D': 'Creatinine'},
  'diagram_text': ''},
 {'number': 167,
  'subject': 'Biology',
  'question': 'The central metabolic station and clearing house of a body is',
  'options': {'A': 'Liver', 'C': 'Nephron', 'B': 'Kidney', 'D': 'Glomerulus'},
  'diagram_text': ''},
 {'number': 168,
  'subject': 'Biology',
  'question': 'The muscles that control urine in bladder are known as',
  'options': {'A': 'Striated muscles', 'C': 'Sphincter muscles', 'B': 'Smooth muscles', 'D': 'Circular muscles'},
  'diagram_text': ''},
 {'number': 169,
  'subject': 'Biology',
  'question': 'The living cells of cartilage are called',
  'options': {'A': 'Chrondrocytes', 'C': 'Ostecytes', 'B': 'Osteoblasts', 'D': 'Osteoclasts'},
  'diagram_text': ''},
 {'number': 170,
  'subject': 'Biology',
  'question': 'The disease which causes immobility and fusion of vertebral joints is',
  'options': {'A': 'Osteomalacia (soft bones)', 'C': 'Arthritis', 'B': 'Disc slip', 'D': 'Spondylosis'},
  'diagram_text': ''},
 {'number': 171,
  'subject': 'Biology',
  'question': 'During muscle contraction',
  'options': {'A': 'I-band shortens', 'C': 'Actin filaments shorten', 'B': 'Myosin filaments shorten', 'D': 'Z-line disappears'},
  'diagram_text': ''},
 {'number': 172,
  'subject': 'Biology',
  'question': 'Hormones are the organic compounds of varying structural complexity. Which of the following is not a function or property '
              'of these compounds?',
  'options': {'A': 'They initiate new biochemical reactions',
              'C': 'They may be proteins',
              'B': 'They are poured directly into blood',
              'D': 'They affect target cells'},
  'diagram_text': ''},
 {'number': 173,
  'subject': 'Biology',
  'question': 'Reflexes and instincts type of behaviours respond to which combination /s?',
  'options': {'A': 'Biological rhythms, territorial, courtship and development',
              'B': 'The responses that do produce same result in different conditions',
              'C': 'Aggression, mating and altruism',
              'D': 'The responses that are predetermined like differentiation.'},
  'diagram_text': ''},
 {'number': 174,
  'subject': 'Biology',
  'question': 'A typical neuron at rest',
  'options': {'A': 'Is more positive outside than inside',
              'C': 'Has no charge on either side',
              'B': 'Is more negative outside than inside',
              'D': 'has an equal charge on either side'},
  'diagram_text': ''},
 {'number': 175,
  'subject': 'Biology',
  'question': 'The first cells produced by the repeated cell division of germinal epithelium of testis are',
  'options': {'A': 'Interstitial cells', 'C': 'Secondary spermatocytes', 'B': 'Spermatogonia', 'D': 'Spermatids'},
  'diagram_text': ''},
 {'number': 176,
  'subject': 'Biology',
  'question': 'Which of the following sequence is correct?',
  'options': {'A': 'LH \uf022 FSH \uf022 Estrogen \uf022 Progesterone',
              'C': 'FSH \uf022 Estrogen \uf022 Progesterone \uf022 LH',
              'B': 'FSH \uf022 LH \uf022 Progesterone \uf022 Estrogen',
              'D': 'FSH \uf022 Estrogen \uf022 LH \uf022 Progesterone'},
  'diagram_text': ''},
 {'number': 177,
  'subject': 'Biology',
  'question': 'Which chromosomal abnormality in humans causes aggressive and antisocial behavior?',
  'options': {'A': 'XO', 'C': 'XYY', 'B': 'XXY', 'D': 'XXX'},
  'diagram_text': ''},
 {'number': 178,
  'subject': 'Biology',
  'question': 'Grey equatorial cytoplasm produces',
  'options': {'A': 'Muscle cells', 'C': 'Notochord and neural tube', 'B': 'Gut', 'D': 'Larval epidermis'},
  'diagram_text': ''},
 {'number': 179,
  'subject': 'Biology',
  'question': 'Sickle cell Anaemia is an example of which type of chromosomal defect?',
  'options': {'A': 'Chromosomal rearrangement', 'C': 'Chromosomal aberration', 'B': 'Transposition of gene', 'D': 'Point mutation'},
  'diagram_text': ''},
 {'number': 180,
  'subject': 'Biology',
  'question': 'The karyotype of an individual is ________ of chromosomes.',
  'options': {'A': 'Number', 'C': 'Number, types and chemical composition', 'B': 'Types', 'D': 'Number and types'},
  'diagram_text': ''},
 {'number': 181,
  'subject': 'Biology',
  'question': 'The process of replication of DNA begins at',
  'options': {'A': 'One place only without any specific sequence of DNA',
              'B': 'One or more places without any specific sequence of DNA',
              'C': 'Any place with the uncoiling of two strands of DNA',
              'D': 'One or more places where there is a specific sequence of nucleotides'},
  'diagram_text': ''},
 {'number': 182,
  'subject': 'Biology',
  'question': 'Amino acid attaches at which site of RNA',
  'options': {'A': 'Anticodon site',
              'C': '3’-site with terminal OH',
              'B': 'Ribosomes recognition site',
              'D': 'Activation enzyme recognition site'},
  'diagram_text': ''},
 {'number': 183,
  'subject': 'Biology',
  'question': 'Microtubules of spindle fibres are composed of a protein called',
  'options': {'A': 'Tubulin', 'C': 'Myosin', 'B': 'Actin', 'D': 'Troponin'},
  'diagram_text': ''},
 {'number': 184,
  'subject': 'Biology',
  'question': 'The kinetochore fibres contract and spindle or pole fibres elongate during',
  'options': {'A': 'Prophase I', 'C': 'Telophase I', 'B': 'Metaphase I', 'D': 'Anaphase I'},
  'diagram_text': ''},
 {'number': 185,
  'subject': 'Biology',
  'question': 'Cell death due to tissue damage is called',
  'options': {'A': 'Necrosis', 'C': 'Apoptosis', 'B': 'Metastasis', 'D': 'Epistasis'},
  'diagram_text': ''},
 {'number': 186,
  'subject': 'Biology',
  'question': 'When a disease is transmitted directly from an affected father to his son, it is called:',
  'options': {'A': 'X-linked', 'C': 'Y-linked', 'B': 'Autosomal', 'D': 'X and Y-linked'},
  'diagram_text': ''},
 {'number': 187,
  'subject': 'Biology',
  'question': 'Epistasis is a relationship between:',
  'options': {'A': 'Alleles of a gene',
              'C': 'Two contrasting traits',
              'B': 'Two different genes at the same locus',
              'D': 'Two different genes at different loci'},
  'diagram_text': ''},
 {'number': 188,
  'subject': 'Biology',
  'question': 'Gene for albinism in man is present on chromosome number:',
  'options': {'A': '11', 'C': '21', 'B': '22', 'D': '12'},
  'diagram_text': ''},
 {'number': 189,
  'subject': 'Biology',
  'question': 'Gene can be synthesized in laboratory from messenger RNA by using:',
  'options': {'A': 'Restriction enzymes', 'C': 'Vector', 'B': 'cDNA (complementary DN', 'D': 'Reverse transcriptase'},
  'diagram_text': ''},
 {'number': 190,
  'subject': 'Biology',
  'question': 'Antibiotic resistance gene for tetracycline and ampicillin are present in the plasmid',
  'options': {'A': 'pSC 101', 'C': 'pBR 322', 'B': 'pCR 101', 'D': 'pBR 233'},
  'diagram_text': ''},
 {'number': 191,
  'subject': 'Biology',
  'question': 'Cloning is a form of',
  'options': {'A': 'Sexual Reproduction', 'C': 'Vegetative Propagation', 'B': 'Asexual Reproduction', 'D': 'Genetic Recombination'},
  'diagram_text': ''},
 {'number': 192,
  'subject': 'Biology',
  'question': 'Group of interbreeding individuals of particular species, sharing common geographical area is called:',
  'options': {'A': 'Population', 'C': 'Community', 'B': 'Community ecology', 'D': 'Autecology'},
  'diagram_text': ''},
 {'number': 193,
  'subject': 'Biology',
  'question': 'Which of the following proteins is common in man and aerobic bacteria?',
  'options': {'A': 'Haemoglobin', 'C': 'Cytochrome c', 'B': 'Myoglobin', 'D': 'Pilin'},
  'diagram_text': ''},
 {'number': 194,
  'subject': 'Biology',
  'question': 'Ozone filters ultraviolet radiations from the sun in the upper',
  'options': {'A': 'Biosphere', 'C': 'Lithosphere', 'B': 'Atmosphere', 'D': 'Hydrosphere'},
  'diagram_text': ''},
 {'number': 195,
  'subject': 'Biology',
  'question': 'A parasite living inside body of the host is called',
  'options': {'A': 'Ectoparasite', 'C': 'Facultative parasite', 'B': 'Obligate parasite', 'D': 'Endoparasite'},
  'diagram_text': ''},
 {'number': 196,
  'subject': 'Biology',
  'question': 'An association between two organisms benefiting both is called',
  'options': {'A': 'Commensalism', 'C': 'Predation', 'B': 'Parasitism', 'D': 'Symbiosis'},
  'diagram_text': ''},
 {'number': 197,
  'subject': 'Biology',
  'question': 'In aquatic ecosystem, human activities may accelerate the process of',
  'options': {'A': 'Eutrophication', 'C': 'Decomposition', 'B': 'Photosynthesis', 'D': 'Recycling'},
  'diagram_text': ''},
 {'number': 198,
  'subject': 'Biology',
  'question': 'Beri Beri is due to',
  'options': {'A': 'Metabolic disorder', 'C': 'Nutritional deficiency', 'B': 'Chemical causes', 'D': 'Mental Illness'},
  'diagram_text': ''},
 {'number': 199,
  'subject': 'Biology',
  'question': 'The natural heat energy trapped underground is',
  'options': {'A': 'Geothermal energy', 'C': 'Electric energy', 'B': 'Thermal energy', 'D': 'Solar energy'},
  'diagram_text': ''},
 {'number': 200,
  'subject': 'Biology',
  'question': 'Which of the following is the lowest level of biological organization with respect to others?',
  'options': {'A': 'Multicellular organisms', 'C': 'Species', 'B': 'Biosphere', 'D': 'Population'},
  'diagram_text': ''},
 {'number': 201,
  'subject': 'Biology',
  'question': 'When an electron pair is shared between two atoms',
  'options': {'A': 'Two covalent bonds are formed',
              'C': 'Single covalent bond is formed',
              'B': 'Hydrogen bond is formed',
              'D': 'Ionic bond is formed'},
  'diagram_text': ''},
 {'number': 202,
  'subject': 'Biology',
  'question': 'The first microbe to have the genome completely sequenced and was published on July 28th, 1995 was',
  'options': {'A': 'Hyphomicrobium', 'C': 'Haemophillus malariae', 'B': 'Haemophilus aquaticus', 'D': 'Haemophillus infulenzae'},
  'diagram_text': ''},
 {'number': 203,
  'subject': 'Biology',
  'question': 'An activated enzyme consisting of polypeptide and a cofactor is known as',
  'options': {'A': 'Amylase', 'C': 'Haloenzyme', 'B': 'Apoenzyme', 'D': 'Coenzyme'},
  'diagram_text': ''},
 {'number': 204,
  'subject': 'Biology',
  'question': '__________ forms weak linkages with enzymes and their effect can be neutralized completely or partly by an increase in the '
              'concentration of the substrate.',
  'options': {'A': 'Only competitive Inhibitors',
              'C': 'Irreversible inhibitors',
              'B': 'Reversible inhibitors',
              'D': 'Both reversible and irreversible inhibitors'},
  'diagram_text': ''},
 {'number': 205,
  'subject': 'Biology',
  'question': 'In prokaryotic cell, wall strengthening material is',
  'options': {'A': 'Cellulose', 'C': 'Chitin', 'B': 'Silica', 'D': 'Peptidoglycan'},
  'diagram_text': ''},
 {'number': 206,
  'subject': 'Biology',
  'question': 'The entire cell wall of bacteria is often regarded as a single huge molecule or molecular complex called',
  'options': {'A': 'Capsule', 'C': 'Slime capsule', 'B': 'Secondary wall', 'D': 'Sacculus'},
  'diagram_text': ''},
 {'number': 207,
  'subject': 'Biology',
  'question': 'Krebs’s cycle takes place in',
  'options': {'A': 'Ribosomes', 'C': 'Mitochondria', 'B': 'Golgi apparatus', 'D': 'Endoplasmic Reticulum'},
  'diagram_text': ''},
 {'number': 208,
  'subject': 'Biology',
  'question': 'Chemically, viruses are made up of',
  'options': {'A': 'Nucleic acid only', 'C': 'Nucleic acid and protein', 'B': 'Protein only', 'D': 'Core and coat'},
  'diagram_text': ''},
 {'number': 209,
  'subject': 'Biology',
  'question': 'Widespread epidemic disease, influenza is caused by',
  'options': {'A': 'DNA virus', 'C': 'DNA enveloped virus', 'B': 'RNA enveloped virus', 'D': 'RNA virus'},
  'diagram_text': ''},
 {'number': 210,
  'subject': 'Biology',
  'question': 'When the division of cells is in three planes, the arrangement is known as',
  'options': {'A': 'Diplococcus', 'C': 'Streptococcus', 'B': 'Sarcina', 'D': 'Staphylococcus'},
  'diagram_text': ''},
 {'number': 211,
  'subject': 'Biology',
  'question': 'Bacterial ‘death rate’ is equal to ‘birth rate; in',
  'options': {'A': 'Lag phase', 'C': 'Death phase', 'B': 'Log phase', 'D': 'Stationary phase'},
  'diagram_text': ''},
 {'number': 212,
  'subject': 'Biology',
  'question': 'Trypanosoma is a human parasite causing',
  'options': {'A': 'African sleeping sickness',
              'C': 'Indonesian sleeping sickness',
              'B': 'European sleeping sickness',
              'D': 'American sleeping sickness'},
  'diagram_text': ''},
 {'number': 213,
  'subject': 'Biology',
  'question': 'The feeding stage of slime mold is a',
  'options': {'A': 'Gastrozoid', 'C': 'Plasmodium', 'B': 'Sporozoite', 'D': 'Merozote'},
  'diagram_text': ''},
 {'number': 214,
  'subject': 'Biology',
  'question': 'Drug obtained from fungus used for lowing blood cholesterol is',
  'options': {'A': 'Lovastatin', 'C': 'Ergotin', 'B': 'Cyclosporin', 'D': 'Griseofulvin'},
  'diagram_text': ''},
 {'number': 215,
  'subject': 'Biology',
  'question': 'Fungi store surplus food in the form of',
  'options': {'A': 'Cellulose', 'C': 'Starch', 'B': 'Glycogen', 'D': 'Both B and C'},
  'diagram_text': ''},
 {'number': 216,
  'subject': 'Biology',
  'question': 'The ecological role of fungi as decomposers is paralleled only by',
  'options': {'A': 'Prions', 'C': 'Bacteria', 'B': 'Algae', 'D': 'Viruses'},
  'diagram_text': ''},
 {'number': 217,
  'subject': 'Biology',
  'question': '“Vascular System absent; gametophyte dominant, sporophyte attached to gametophyte; homosporous” are distinguishing '
              'characters of',
  'options': {'A': 'Psiolpsida', 'C': 'Angiosperms', 'B': 'Pteropsida', 'D': 'Bryophyta'},
  'diagram_text': ''},
 {'number': 218,
  'subject': 'Biology',
  'question': 'Which of the following features differentiate angiosperms from gymnosperms?',
  'options': {'A': 'Pollens disperse by air', 'C': 'Ovaries', 'B': 'Haploid microspores', 'D': 'Pollen tubes'},
  'diagram_text': ''},
 {'number': 219,
  'subject': 'Biology',
  'question': 'In Pakistan, the furniture wood is mainly obtained from the members of family:',
  'options': {'A': 'Rosaceae', 'C': 'Minosaceae', 'B': 'Solanaceae', 'D': 'Fabaceae'},
  'diagram_text': ''},
 {'number': 220,
  'subject': 'Biology',
  'question': 'Which of the following is exclusive character of mammals?',
  'options': {'A': 'Homeothermic', 'C': 'Poikliothermic', 'B': 'Hair', 'D': 'Four chambered heart'},
  'diagram_text': ''}]

# Remove section/instruction text that appears immediately after the final option in the PDF layout.
for _q in QUESTIONS:
    _q['question'] = _q['question'].replace(' In each of the following question, four alternative sentences are given. Choose the CORRECT one and fill the Circle corresponding to that letter in the MCQ Response Form.', '')
    _q['question'] = _q['question'].replace(' In each of the following question, four alternative meanings of a word are given. You have to select the NEAREST CORRECT MEANING of the given word and fill the appropriate Circle on the MCQ Response Form.', '')

# Normalize English section prompts that are shared across several questions in the source.
for _q in QUESTIONS:
    if 125 <= _q['number'] <= 130:
        _q['question'] = 'Identify the underlined segment containing the error: ' + _q['question']
    elif 131 <= _q['number'] <= 140:
        _q['question'] = 'Choose the CORRECT sentence.'
    elif 141 <= _q['number'] <= 150:
        _q['question'] = 'Select the NEAREST CORRECT MEANING of the word: ' + _q['question']

SUBJECT_RANGES = {
    "Physics": (1, 60),
    "Chemistry": (61, 120),
    "English": (121, 150),
    "Biology": (151, 220),
}