"""
MDCAT Mock Test 3
==================
Full-length mock test: 180 MCQs
Weightage: Biology 81 | Chemistry 45 | Physics 36 | English 9 | Logical Reasoning 9
Difficulty mix (approx): 30% Easy / 50% Medium / 20% Hard, distributed throughout.

Includes 5 image/diagram-based questions (2 Biology, 1 Chemistry, 2 Physics).
Each such question has an "image" key giving a relative path to a PNG diagram
that must be viewed alongside the question (images/ subfolder, shipped alongside
this file). Diagrams: enzyme-activity vs pH graph, labeled animal-cell structure,
acid-base titration curve, a series-parallel resistor circuit, and a convex-lens
ray diagram (object between F and the lens).

Each question is a dict:
    id, subject, topic, difficulty, question, [image], options (A-D), answer (correct letter)

Run this file directly to print a summary / sanity-check the paper.
"""

QUESTIONS = [
# ============================================================
# BIOLOGY (81 questions) - id 1-81
# ============================================================
{"id":1,"subject":'Biology',"topic":'Biomolecules',"difficulty":'Easy',
 "question":'Which of the following is a polysaccharide?',
 "options":{"A":'Glucose', "B":'Glycogen', "C":'Sucrose', "D":'Fructose'},"answer":'B'},
{"id":2,"subject":'Biology',"topic":'Biomolecules',"difficulty":'Easy',
 "question":'Which type of bond links a fatty acid to glycerol in a triglyceride?',
 "options":{"A":'Peptide bond', "B":'Ester bond', "C":'Glycosidic bond', "D":'Hydrogen bond'},"answer":'B'},
{"id":3,"subject":'Biology',"topic":'Biomolecules',"difficulty":'Medium',
 "question":'The primary structure of a protein refers to:',
 "options":{"A":'Its folding into alpha helices and beta sheets', "B":'Its overall three-dimensional globular shape', "C":'The association of multiple polypeptide subunits', "D":'The linear sequence of amino acids joined by peptide bonds'},"answer":'D'},
{"id":4,"subject":'Biology',"topic":'Biomolecules',"difficulty":'Medium',
 "question":'Glycogen differs from starch mainly in that glycogen:',
 "options":{"A":'Is a monosaccharide rather than a polymer', "B":'Contains beta-glycosidic linkages', "C":'Is more highly branched, allowing faster mobilization of glucose', "D":'Is not found in animal cells'},"answer":'C'},
{"id":5,"subject":'Biology',"topic":'Biomolecules',"difficulty":'Hard',
 "question":'The sugar-phosphate backbone of a DNA strand is formed by phosphodiester bonds between:',
 "options":{"A":'Adjacent nitrogenous bases', "B":'The phosphate group of one nucleotide and the sugar of the next', "C":'Two pentose sugars directly', "D":'Amino acids attached to the sugar-phosphate chain'},"answer":'B'},
{"id":6,"subject":'Biology',"topic":'Enzymes',"difficulty":'Easy',
 "question":'The region of an enzyme where the substrate binds and the reaction is catalyzed is called the:',
 "options":{"A":'Active site', "B":'Allosteric site', "C":'Regulatory site', "D":'Cofactor site'},"answer":'A'},
{"id":7,"subject":'Biology',"topic":'Enzymes',"difficulty":'Medium',
 "question":'If enzyme concentration is increased while substrate remains in constant excess, the initial reaction rate will:',
 "options":{"A":'Increase proportionally, up to a limit set by available substrate', "B":'Decrease', "C":'Remain completely unchanged', "D":'Cause the enzyme to denature'},"answer":'A'},
{"id":8,"subject":'Biology',"topic":'Enzymes',"difficulty":'Medium',
 "question":'The graph shows the activity of a digestive enzyme measured across a range of pH values, with a sharp activity peak near pH 2. Based on the graph, this enzyme most likely functions in the:',
 "image":'images/q_enzyme_ph_graph.png',
 "options":{"A":'Small intestine', "B":'Mouth', "C":'Large intestine', "D":'Stomach'},"answer":'D'},
{"id":9,"subject":'Biology',"topic":'Enzymes',"difficulty":'Hard',
 "question":'On a Lineweaver-Burk (double reciprocal) plot of 1/v against 1/[S], the y-intercept of the line represents:',
 "options":{"A":'-1/Km', "B":'1/Vmax', "C":'Km/Vmax', "D":'Vmax'},"answer":'B'},
{"id":10,"subject":'Biology',"topic":'Cell Biology',"difficulty":'Easy',
 "question":'Which organelle is chiefly responsible for detoxifying drugs and synthesizing lipids in liver cells?',
 "options":{"A":'Rough endoplasmic reticulum', "B":'Golgi apparatus', "C":'Lysosome', "D":'Smooth endoplasmic reticulum'},"answer":'D'},
{"id":11,"subject":'Biology',"topic":'Cell Biology',"difficulty":'Easy',
 "question":'Ribosomal RNA is synthesized and ribosomal subunits are assembled within the:',
 "options":{"A":'Nuclear pore', "B":'Nucleolus', "C":'Chromatin', "D":'Nuclear envelope'},"answer":'B'},
{"id":12,"subject":'Biology',"topic":'Cell Biology',"difficulty":'Medium',
 "question":'Centrioles in animal cells play a key role mainly by:',
 "options":{"A":'Folding newly synthesized proteins', "B":'Synthesizing membrane lipids', "C":'Organizing the mitotic spindle during cell division', "D":'Producing ATP through respiration'},"answer":'C'},
{"id":13,"subject":'Biology',"topic":'Cell Biology',"difficulty":'Medium',
 "question":'Which feature is shared by both mitochondria and chloroplasts, supporting the endosymbiotic theory of their origin?',
 "options":{"A":'They both contain chlorophyll', "B":'They both have a double membrane and their own circular DNA and ribosomes', "C":'They are both found exclusively in plant cells', "D":'Neither has an internal membrane system'},"answer":'B'},
{"id":14,"subject":'Biology',"topic":'Cell Biology',"difficulty":'Medium',
 "question":'The diagram shows an animal cell with four structures labeled W, X, Y, and Z. Structure X is a stack of flattened, membrane-bound sacs that receives proteins from the rough ER, then modifies, sorts, and packages them for secretion. Which structure is X?',
 "image":'images/q_cell_diagram_wxyz.png',
 "options":{"A":'Structure W (mitochondrion)', "B":'Structure Y (nucleus)', "C":'Structure X (Golgi apparatus)', "D":'Structure Z (lysosome)'},"answer":'C'},
{"id":15,"subject":'Biology',"topic":'Cell Biology',"difficulty":'Medium',
 "question":'Nuclear pores in the nuclear envelope primarily function to:',
 "options":{"A":'Manufacture ribosomes directly', "B":'Allow only water molecules to cross', "C":'Regulate the passage of large molecules such as proteins and RNA between nucleus and cytoplasm', "D":'Anchor chromosomes during mitosis'},"answer":'C'},
{"id":16,"subject":'Biology',"topic":'Cell Biology',"difficulty":'Hard',
 "question":'A cell that lacks functional lysosomes would primarily have difficulty with:',
 "options":{"A":'Replicating its DNA', "B":'Producing ATP via the electron transport chain', "C":'Splicing pre-mRNA', "D":'Breaking down worn-out organelles and cellular debris'},"answer":'D'},
{"id":17,"subject":'Biology',"topic":'Cell Membrane & Transport',"difficulty":'Easy',
 "question":'Simple diffusion of small nonpolar molecules such as O2 across a membrane occurs:',
 "options":{"A":'Against the concentration gradient, using ATP', "B":'Only through specific channel proteins', "C":'Only during endocytosis', "D":'Down the concentration gradient without any transport protein'},"answer":'D'},
{"id":18,"subject":'Biology',"topic":'Cell Membrane & Transport',"difficulty":'Medium',
 "question":'A red blood cell placed in a hypertonic solution will most likely:',
 "options":{"A":'Shrink as water leaves the cell (crenation)', "B":'Swell and eventually burst', "C":'Remain completely unchanged', "D":'Immediately undergo mitosis'},"answer":'A'},
{"id":19,"subject":'Biology',"topic":'Cell Membrane & Transport',"difficulty":'Medium',
 "question":'Exocytosis is the process by which a cell:',
 "options":{"A":'Engulfs large particles from outside the cell', "B":'Transports ions against their concentration gradient', "C":'Releases materials, such as hormones or enzymes, by fusing vesicles with the plasma membrane', "D":'Exchanges gases passively across the membrane'},"answer":'C'},
{"id":20,"subject":'Biology',"topic":'Cell Membrane & Transport',"difficulty":'Hard',
 "question":'Glucose uptake into most body cells via GLUT carrier proteins is best classified as:',
 "options":{"A":'Active transport requiring ATP hydrolysis', "B":'Simple diffusion directly through the lipid bilayer', "C":'Facilitated diffusion, moving glucose down its concentration gradient via a carrier protein', "D":'Osmosis'},"answer":'C'},
{"id":21,"subject":'Biology',"topic":'Cell Membrane & Transport',"difficulty":'Easy',
 "question":'According to the fluid mosaic model of the plasma membrane, membrane proteins:',
 "options":{"A":'Are fixed rigidly in one position', "B":'Are found only on the outer surface of the membrane', "C":'Never span the entire width of the membrane', "D":'Can move laterally within the phospholipid bilayer'},"answer":'D'},
{"id":22,"subject":'Biology',"topic":'Cell Cycle & Division',"difficulty":'Easy',
 "question":'The phase of the cell cycle in which the cell grows and carries out normal metabolic activity before replicating its DNA is:',
 "options":{"A":'S phase', "B":'G2 phase', "C":'G1 phase', "D":'M phase'},"answer":'C'},
{"id":23,"subject":'Biology',"topic":'Cell Cycle & Division',"difficulty":'Easy',
 "question":"Chromosomes align individually at the cell's equator during:",
 "options":{"A":'Anaphase', "B":'Metaphase', "C":'Prophase', "D":'Telophase'},"answer":'B'},
{"id":24,"subject":'Biology',"topic":'Cell Cycle & Division',"difficulty":'Medium',
 "question":'Nondisjunction occurring during meiosis I most directly results in:',
 "options":{"A":'Gametes with a normal chromosome number', "B":'Genetically identical daughter cells', "C":'Gametes with an abnormal (too many or too few) number of chromosomes', "D":'Complete failure of gamete formation in every case'},"answer":'C'},
{"id":25,"subject":'Biology',"topic":'Cell Cycle & Division',"difficulty":'Medium',
 "question":'A cell with a diploid chromosome number of 20 undergoes mitosis. How many chromosomes will each resulting daughter cell contain?',
 "options":{"A":'10', "B":'20', "C":'40', "D":'5'},"answer":'B'},
{"id":26,"subject":'Biology',"topic":'Cell Cycle & Division',"difficulty":'Hard',
 "question":'The spindle-assembly checkpoint during mitosis primarily ensures that:',
 "options":{"A":'All chromosomes are properly attached to spindle fibers before anaphase begins', "B":'DNA replication has finished in S phase', "C":'The cell has reached an adequate size before dividing', "D":'Cytokinesis has already been completed'},"answer":'A'},
{"id":27,"subject":'Biology',"topic":'Cell Cycle & Division',"difficulty":'Medium',
 "question":'Cytokinesis in animal cells typically occurs by:',
 "options":{"A":'Formation of a rigid cell plate that splits the cell in two', "B":'Division of the nucleus alone, without cytoplasmic division', "C":'Formation of a new cell wall around each daughter cell', "D":'Pinching of the plasma membrane inward via a contractile ring, forming two daughter cells'},"answer":'D'},
{"id":28,"subject":'Biology',"topic":'Genetics',"difficulty":'Easy',
 "question":'In pea plants, tall (T) is dominant over short (t). Crossing a homozygous tall plant (TT) with a homozygous short plant (tt) produces offspring with genotype:',
 "options":{"A":'All TT', "B":'1 TT : 1 tt', "C":'All Tt', "D":'All tt'},"answer":'C'},
{"id":29,"subject":'Biology',"topic":'Genetics',"difficulty":'Medium',
 "question":'A cross between two heterozygous tall pea plants (Tt x Tt) gives what expected phenotypic ratio in the offspring?',
 "options":{"A":'1 tall : 1 short', "B":'1 tall : 2 intermediate : 1 short', "C":'3 tall : 1 short', "D":'9 tall : 3 : 3 : 1 short'},"answer":'C'},
{"id":30,"subject":'Biology',"topic":'Genetics',"difficulty":'Medium',
 "question":'Duchenne muscular dystrophy is an X-linked recessive disorder. If a carrier mother and an unaffected father have children, what proportion of their daughters is expected to be carriers?',
 "options":{"A":'0%', "B":'25%', "C":'50%', "D":'100%'},"answer":'C'},
{"id":31,"subject":'Biology',"topic":'Genetics',"difficulty":'Hard',
 "question":'In a test cross AaBb x aabb, assuming independent assortment, what fraction of offspring is expected to show the dominant phenotype for both traits?',
 "options":{"A":'1/2', "B":'1/8', "C":'1/4', "D":'1/16'},"answer":'C'},
{"id":32,"subject":'Biology',"topic":'Genetics',"difficulty":'Medium',
 "question":'A man with blood group O and a woman with blood group AB have children. Which blood groups are possible among their offspring?',
 "options":{"A":'A and B only', "B":'Only O', "C":'Only AB', "D":'A, B, AB, and O'},"answer":'A'},
{"id":33,"subject":'Biology',"topic":'Genetics',"difficulty":'Hard',
 "question":'A trait that appears only in children of two unaffected, carrier parents, tends to skip generations, and affects males and females in roughly equal numbers is most consistent with:',
 "options":{"A":'Autosomal dominant inheritance', "B":'X-linked dominant inheritance', "C":'Autosomal recessive inheritance', "D":'Y-linked inheritance'},"answer":'C'},
{"id":34,"subject":'Biology',"topic":'Genetics',"difficulty":'Medium',
 "question":'Sickle-cell trait, in which heterozygous carriers produce both normal and sickle hemoglobin, is an example of:',
 "options":{"A":'Epistasis', "B":'Codominance', "C":'Incomplete dominance', "D":'Complete dominance'},"answer":'B'},
{"id":35,"subject":'Biology',"topic":'Molecular Biology',"difficulty":'Easy',
 "question":'In DNA, adenine pairs with thymine, while guanine pairs with:',
 "options":{"A":'Cytosine', "B":'Adenine', "C":'Uracil', "D":'Thymine'},"answer":'A'},
{"id":36,"subject":'Biology',"topic":'Molecular Biology',"difficulty":'Easy',
 "question":'The process by which mRNA is synthesized from a DNA template is called:',
 "options":{"A":'Translation', "B":'Replication', "C":'Splicing', "D":'Transcription'},"answer":'D'},
{"id":37,"subject":'Biology',"topic":'Molecular Biology',"difficulty":'Medium',
 "question":'DNA polymerase can only add new nucleotides to a growing strand in which direction?',
 "options":{"A":"3' to 5'", "B":"5' to 3'", "C":'Either direction, depending on the strand', "D":'In a random direction'},"answer":'B'},
{"id":38,"subject":'Biology',"topic":'Molecular Biology',"difficulty":'Medium',
 "question":'The primary role of tRNA during translation is to:',
 "options":{"A":'Bring specific amino acids to the ribosome according to the mRNA codon being read', "B":'Carry the genetic code from the nucleus to the cytoplasm', "C":'Catalyze peptide bond formation independently of the ribosome', "D":'Unwind the DNA double helix'},"answer":'A'},
{"id":39,"subject":'Biology',"topic":'Molecular Biology',"difficulty":'Medium',
 "question":'A mutation that changes a codon but, due to the degeneracy of the genetic code, still specifies the same amino acid is called a:',
 "options":{"A":'Missense mutation', "B":'Nonsense mutation', "C":'Frameshift mutation', "D":'Silent mutation'},"answer":'D'},
{"id":40,"subject":'Biology',"topic":'Molecular Biology',"difficulty":'Hard',
 "question":"Deletion of two nucleotides from the middle of a gene's coding sequence would most likely cause:",
 "options":{"A":'A frameshift, altering every downstream codon', "B":'No change to the resulting protein', "C":'A single amino acid substitution only, with the rest unaffected', "D":'Premature termination only, with no other change'},"answer":'A'},
{"id":41,"subject":'Biology',"topic":'Molecular Biology',"difficulty":'Hard',
 "question":'The lac operon in E. coli is transcribed (switched on) mainly when:',
 "options":{"A":'Lactose is present, binding the repressor protein and preventing it from blocking transcription', "B":'Glucose is abundant and lactose is absent', "C":'The repressor protein permanently binds the operator regardless of lactose', "D":'RNA polymerase is degraded by the cell'},"answer":'A'},
{"id":42,"subject":'Biology',"topic":'Molecular Biology',"difficulty":'Medium',
 "question":'Which of the following correctly describes base pairing in DNA?',
 "options":{"A":'G-C pairs form three hydrogen bonds', "B":'A-T pairs form three hydrogen bonds', "C":'A-T pairs are joined by covalent bonds', "D":'G-C pairs form only one hydrogen bond'},"answer":'A'},
{"id":43,"subject":'Biology',"topic":'Molecular Biology',"difficulty":'Medium',
 "question":'A promoter sequence within a gene functions mainly to:',
 "options":{"A":'Code for the first amino acid of the resulting protein', "B":'Provide a binding site for RNA polymerase to initiate transcription', "C":'Terminate translation at the ribosome', "D":'Splice introns out of the pre-mRNA'},"answer":'B'},
{"id":44,"subject":'Biology',"topic":'Molecular Biology',"difficulty":'Easy',
 "question":'Which of the following is NOT one of the three stop codons?',
 "options":{"A":'UAA', "B":'UAG', "C":'AUG', "D":'UGA'},"answer":'C'},
{"id":45,"subject":'Biology',"topic":'Evolution',"difficulty":'Easy',
 "question":'The process by which a new species arises as populations become reproductively isolated from one another is called:',
 "options":{"A":'Adaptation', "B":'Speciation', "C":'Mutation', "D":'Selection'},"answer":'B'},
{"id":46,"subject":'Biology',"topic":'Evolution',"difficulty":'Medium',
 "question":'Vestigial structures, such as the human coccyx (tailbone), provide evidence for evolution because they:',
 "options":{"A":'Are remnants of structures that were functional in ancestral species', "B":'Currently perform vital, essential functions', "C":'Are found only in modern humans and no other species', "D":'Evolved independently in completely unrelated lineages'},"answer":'A'},
{"id":47,"subject":'Biology',"topic":'Evolution',"difficulty":'Medium',
 "question":'Which scenario would most likely disrupt Hardy-Weinberg equilibrium in a population?',
 "options":{"A":'A very small population size subject to genetic drift', "B":'An extremely large population with random mating', "C":'No mutation or migration occurring', "D":'No natural selection acting on any allele'},"answer":'A'},
{"id":48,"subject":'Biology',"topic":'Evolution',"difficulty":'Hard',
 "question":'In a population, the frequency of the recessive allele (q) is 0.2. Assuming Hardy-Weinberg equilibrium, what percentage of the population is expected to be homozygous recessive?',
 "options":{"A":'20%', "B":'64%', "C":'40%', "D":'4%'},"answer":'D'},
{"id":49,"subject":'Biology',"topic":'Classification & Diversity',"difficulty":'Easy',
 "question":'In the taxonomic hierarchy, moving from broadest to most specific, the rank that comes immediately after Domain is:',
 "options":{"A":'Species', "B":'Phylum', "C":'Kingdom', "D":'Genus'},"answer":'C'},
{"id":50,"subject":'Biology',"topic":'Classification & Diversity',"difficulty":'Easy',
 "question":'Organisms in kingdom Plantae are characterized as:',
 "options":{"A":'Heterotrophic organisms lacking cell walls', "B":'Prokaryotic, unicellular organisms', "C":'Decomposers that absorb nutrients from dead matter', "D":'Multicellular, photosynthetic autotrophs with cellulose cell walls'},"answer":'D'},
{"id":51,"subject":'Biology',"topic":'Classification & Diversity',"difficulty":'Medium',
 "question":'Archaea are classified in a domain separate from Bacteria mainly because they:',
 "options":{"A":'Always cause disease in humans', "B":'Are the only prokaryotes that possess a true nucleus', "C":'Lack ribosomes entirely', "D":'Differ significantly in cell membrane lipids, cell wall composition, and genetics, often surviving extreme environments'},"answer":'D'},
{"id":52,"subject":'Biology',"topic":'Classification & Diversity',"difficulty":'Medium',
 "question":'A student observes an organism that is unicellular, lacks a membrane-bound nucleus, and has a cell wall made of peptidoglycan. This organism most likely belongs to:',
 "options":{"A":'Kingdom Protista', "B":'Kingdom Monera (Bacteria)', "C":'Kingdom Fungi', "D":'Kingdom Plantae'},"answer":'B'},
{"id":53,"subject":'Biology',"topic":'Classification & Diversity',"difficulty":'Easy',
 "question":'Which taxonomic rank is more specific (narrower) than Family but broader than Species?',
 "options":{"A":'Order', "B":'Class', "C":'Genus', "D":'Phylum'},"answer":'C'},
{"id":54,"subject":'Biology',"topic":'Classification & Diversity',"difficulty":'Medium',
 "question":'Members of phylum Annelida are characterized mainly by:',
 "options":{"A":'A segmented body plan with a true coelom', "B":'Radial symmetry and no true tissues', "C":'A rigid exoskeleton made of chitin', "D":'A notochord present throughout their entire life'},"answer":'A'},
{"id":55,"subject":'Biology',"topic":'Plant Biology',"difficulty":'Easy',
 "question":'Gas exchange in a leaf occurs mainly through small pores called:',
 "options":{"A":'Lenticels', "B":'Trichomes', "C":'Stomata', "D":'Xylem vessels'},"answer":'C'},
{"id":56,"subject":'Biology',"topic":'Plant Biology',"difficulty":'Medium',
 "question":'The light-independent reactions (Calvin cycle) of photosynthesis take place in the:',
 "options":{"A":'Stroma of the chloroplast', "B":'Thylakoid membrane', "C":'Cristae of the mitochondrion', "D":'Cytoplasm'},"answer":'A'},
{"id":57,"subject":'Biology',"topic":'Plant Biology',"difficulty":'Medium',
 "question":'Besides ATP, which product of the light-dependent reactions is used to reduce fixed carbon in the Calvin cycle?',
 "options":{"A":'Oxygen', "B":'NADPH', "C":'Glucose', "D":'Pyruvate'},"answer":'B'},
{"id":58,"subject":'Biology',"topic":'Plant Biology',"difficulty":'Hard',
 "question":'A key adaptation of C4 plants that reduces photorespiration compared to C3 plants is:',
 "options":{"A":'The complete absence of the enzyme RuBisCO', "B":'Carrying out all photosynthetic reactions only at night', "C":'A complete lack of stomata on the leaf surface', "D":'Initial CO2 fixation by PEP carboxylase in mesophyll cells, followed by transfer of the fixed carbon to bundle-sheath cells for the Calvin cycle'},"answer":'D'},
{"id":59,"subject":'Biology',"topic":'Plant Biology',"difficulty":'Medium',
 "question":'Root hairs increase the efficiency of water and mineral absorption mainly by:',
 "options":{"A":'Producing additional chlorophyll', "B":'Increasing the surface area of the root in contact with soil', "C":'Secreting digestive enzymes into the soil', "D":'Storing starch for later use'},"answer":'B'},
{"id":60,"subject":'Biology',"topic":'Plant Biology',"difficulty":'Easy',
 "question":'The process by which a seed begins to develop into a seedling is called:',
 "options":{"A":'Pollination', "B":'Germination', "C":'Fertilization', "D":'Transpiration'},"answer":'B'},
{"id":61,"subject":'Biology',"topic":'Human Physiology - Digestion',"difficulty":'Easy',
 "question":'Chemical digestion of starch begins in the mouth due to the enzyme:',
 "options":{"A":'Salivary amylase', "B":'Pepsin', "C":'Trypsin', "D":'Lipase'},"answer":'A'},
{"id":62,"subject":'Biology',"topic":'Human Physiology - Digestion',"difficulty":'Medium',
 "question":'The primary function of the gallbladder is to:',
 "options":{"A":'Store and concentrate bile produced by the liver', "B":'Produce bile', "C":'Secrete pancreatic digestive enzymes', "D":'Absorb digested nutrients into the blood'},"answer":'A'},
{"id":63,"subject":'Biology',"topic":'Human Physiology - Digestion',"difficulty":'Medium',
 "question":'Which pancreatic enzyme digests dietary fats into fatty acids and glycerol?',
 "options":{"A":'Trypsin', "B":'Amylase', "C":'Pepsin', "D":'Lipase'},"answer":'D'},
{"id":64,"subject":'Biology',"topic":'Human Physiology - Digestion',"difficulty":'Hard',
 "question":'Peristalsis in the digestive tract refers to:',
 "options":{"A":'The chemical breakdown of food by enzymes', "B":'The absorption of nutrients into the bloodstream', "C":'Rhythmic, wave-like muscular contractions that propel food along the digestive tract', "D":'The secretion of hydrochloric acid by the stomach'},"answer":'C'},
{"id":65,"subject":'Biology',"topic":'Human Physiology - Circulation',"difficulty":'Easy',
 "question":'Deoxygenated blood returning from the body first enters which chamber of the heart?',
 "options":{"A":'Right atrium', "B":'Left atrium', "C":'Left ventricle', "D":'Right ventricle'},"answer":'A'},
{"id":66,"subject":'Biology',"topic":'Human Physiology - Circulation',"difficulty":'Medium',
 "question":'Capillaries are ideally suited for the exchange of gases and nutrients mainly because they:',
 "options":{"A":'Have thick, muscular walls', "B":'Have walls only one cell thick, allowing easy diffusion', "C":'Carry blood at very high pressure', "D":'Contain one-way valves'},"answer":'B'},
{"id":67,"subject":'Biology',"topic":'Human Physiology - Circulation',"difficulty":'Medium',
 "question":'The pulmonary circuit differs from the systemic circuit in that the pulmonary circuit:',
 "options":{"A":'Carries blood exclusively to and from the brain', "B":'Never contains deoxygenated blood', "C":'Carries blood between the heart and the lungs for gas exchange', "D":'Contains no capillary beds'},"answer":'C'},
{"id":68,"subject":'Biology',"topic":'Human Physiology - Circulation',"difficulty":'Hard',
 "question":'An increase in heart rate during exercise is primarily triggered by:',
 "options":{"A":'Sympathetic stimulation of the SA node, increasing its firing rate', "B":'Parasympathetic stimulation of the SA node', "C":'Direct contraction of the AV node without any nervous input', "D":'A decrease in blood carbon dioxide levels'},"answer":'A'},
{"id":69,"subject":'Biology',"topic":'Human Physiology - Respiration',"difficulty":'Easy',
 "question":'The exchange of oxygen and carbon dioxide between air and blood occurs across the walls of the:',
 "options":{"A":'Bronchioles', "B":'Alveoli', "C":'Trachea', "D":'Larynx'},"answer":'B'},
{"id":70,"subject":'Biology',"topic":'Human Physiology - Respiration',"difficulty":'Medium',
 "question":'During quiet exhalation, the diaphragm:',
 "options":{"A":'Relaxes and domes upward, decreasing thoracic volume', "B":'Contracts and flattens', "C":'Remains completely motionless', "D":'Contracts to increase thoracic volume'},"answer":'A'},
{"id":71,"subject":'Biology',"topic":'Human Physiology - Respiration',"difficulty":'Medium',
 "question":'Oxygen is transported in the blood mainly:',
 "options":{"A":'Dissolved freely in the plasma', "B":'Bound to hemoglobin within red blood cells', "C":'As bicarbonate ions', "D":'Bound to white blood cells'},"answer":'B'},
{"id":72,"subject":'Biology',"topic":'Human Physiology - Excretion',"difficulty":'Easy',
 "question":'Urine is temporarily stored before being excreted in the:',
 "options":{"A":'Kidney', "B":'Ureter', "C":'Urinary bladder', "D":'Urethra'},"answer":'C'},
{"id":73,"subject":'Biology',"topic":'Human Physiology - Excretion',"difficulty":'Medium',
 "question":'The process by which useful substances such as glucose and amino acids are returned from the filtrate back into the blood is called:',
 "options":{"A":'Filtration', "B":'Secretion', "C":'Excretion', "D":'Reabsorption'},"answer":'D'},
{"id":74,"subject":'Biology',"topic":'Human Physiology - Excretion',"difficulty":'Hard',
 "question":'A drug that inhibits the release of ADH (antidiuretic hormone) would most likely result in:',
 "options":{"A":'Decreased urine volume and highly concentrated urine', "B":'Complete cessation of urine production', "C":'Increased urine volume as the collecting duct becomes less permeable to water', "D":'Increased blood pressure only, with no effect on urine'},"answer":'C'},
{"id":75,"subject":'Biology',"topic":'Human Physiology - Nervous & Endocrine',"difficulty":'Easy',
 "question":'The part of a neuron that receives signals from other neurons is the:',
 "options":{"A":'Axon', "B":'Synapse', "C":'Myelin sheath', "D":'Dendrite'},"answer":'D'},
{"id":76,"subject":'Biology',"topic":'Human Physiology - Nervous & Endocrine',"difficulty":'Medium',
 "question":'After binding its receptor at a synapse, a neurotransmitter is typically cleared from the synaptic cleft by:',
 "options":{"A":"Permanent incorporation into the postsynaptic neuron's membrane", "B":'Permanent binding to its receptor', "C":'Reuptake by the presynaptic neuron or enzymatic breakdown', "D":'Conversion into DNA'},"answer":'C'},
{"id":77,"subject":'Biology',"topic":'Human Physiology - Nervous & Endocrine',"difficulty":'Medium',
 "question":'The hormone cortisol, released by the adrenal cortex in response to stress, primarily functions to:',
 "options":{"A":'Lower blood glucose levels', "B":'Stimulate insulin release from the pancreas', "C":'Decrease heart rate', "D":'Raise blood glucose levels and suppress non-essential functions during stress'},"answer":'D'},
{"id":78,"subject":'Biology',"topic":'Human Physiology - Nervous & Endocrine',"difficulty":'Hard',
 "question":'During the repolarization phase of an action potential, the membrane potential returns toward resting levels mainly because:',
 "options":{"A":'K+ channels open, allowing K+ to flow out of the neuron', "B":'Na+ channels open further, allowing more Na+ influx', "C":'Ca2+ ions rush into the neuron', "D":'The sodium-potassium pump instantly reverses direction'},"answer":'A'},
{"id":79,"subject":'Biology',"topic":'Human Physiology - Reproduction',"difficulty":'Easy',
 "question":'Sperm cells are produced within the testes in structures called:',
 "options":{"A":'Epididymis', "B":'Vas deferens', "C":'Prostate gland', "D":'Seminiferous tubules'},"answer":'D'},
{"id":80,"subject":'Biology',"topic":'Human Physiology - Reproduction',"difficulty":'Medium',
 "question":'The corpus luteum, formed in the ovary after ovulation, mainly functions to:',
 "options":{"A":'Release the mature egg from the ovary', "B":'Produce sperm cells', "C":'Transport the egg toward the uterus', "D":'Secrete progesterone to help maintain the uterine lining'},"answer":'D'},
{"id":81,"subject":'Biology',"topic":'Ecology',"difficulty":'Medium',
 "question":'In a food web, an organism that regularly consumes both producers and other consumers is best classified as:',
 "options":{"A":'A strict herbivore', "B":'A decomposer', "C":'An omnivore', "D":'A primary producer'},"answer":'C'},

# ============================================================
# CHEMISTRY (45 questions) - id 82-126
# ============================================================
{"id":82,"subject":'Chemistry',"topic":'Atomic Structure',"difficulty":'Easy',
 "question":'The number of electrons in a neutral atom is equal to its number of:',
 "options":{"A":'Neutrons', "B":'Isotopes', "C":'Energy levels', "D":'Protons'},"answer":'D'},
{"id":83,"subject":'Chemistry',"topic":'Atomic Structure',"difficulty":'Medium',
 "question":'An atom of potassium-39 (atomic number 19) contains how many neutrons?',
 "options":{"A":'19', "B":'20', "C":'39', "D":'58'},"answer":'B'},
{"id":84,"subject":'Chemistry',"topic":'Atomic Structure',"difficulty":'Medium',
 "question":'The electron configuration of a neutral calcium atom (Z = 20) ends with:',
 "options":{"A":'4s^2', "B":'3d^2', "C":'4s^1 3d^1', "D":'4p^2'},"answer":'A'},
{"id":85,"subject":'Chemistry',"topic":'Atomic Structure',"difficulty":'Hard',
 "question":'An ion formed from an atom with 16 protons that has gained 2 electrons carries a charge of:',
 "options":{"A":'-2', "B":'+2', "C":'+1', "D":'-1'},"answer":'A'},
{"id":86,"subject":'Chemistry',"topic":'Periodic Table',"difficulty":'Easy',
 "question":'Elements in Group 18 of the periodic table are known as:',
 "options":{"A":'Alkali metals', "B":'Halogens', "C":'Noble gases', "D":'Transition metals'},"answer":'C'},
{"id":87,"subject":'Chemistry',"topic":'Periodic Table',"difficulty":'Medium',
 "question":'Metallic character in the periodic table generally increases:',
 "options":{"A":'Across a period from left to right, and up a group', "B":'Down a group, and from right to left across a period', "C":'Down a group, and from left to right across a period', "D":'Up a group, and from left to right across a period'},"answer":'B'},
{"id":88,"subject":'Chemistry',"topic":'Periodic Table',"difficulty":'Medium',
 "question":'An element with the electron configuration [Ne]3s2 3p5 would most likely:',
 "options":{"A":'Gain one electron to form a -1 ion, achieving a stable noble gas configuration', "B":'Lose one electron to form a +1 ion', "C":'Be chemically inert like a noble gas', "D":'Form covalent bonds only with other metals'},"answer":'A'},
{"id":89,"subject":'Chemistry',"topic":'Chemical Bonding',"difficulty":'Easy',
 "question":'A coordinate (dative) covalent bond differs from an ordinary covalent bond in that:',
 "options":{"A":'It involves complete transfer of electrons between atoms', "B":'It forms only between two metal atoms', "C":'Both shared electrons are contributed by only one of the two atoms', "D":'No electrons are actually shared'},"answer":'C'},
{"id":90,"subject":'Chemistry',"topic":'Chemical Bonding',"difficulty":'Medium',
 "question":'According to VSEPR theory, a molecule such as water, with two bonding pairs and two lone pairs on the central atom, has a molecular shape described as:',
 "options":{"A":'Linear', "B":'Tetrahedral', "C":'Trigonal pyramidal', "D":'Bent'},"answer":'D'},
{"id":91,"subject":'Chemistry',"topic":'Chemical Bonding',"difficulty":'Medium',
 "question":'BF3 is a nonpolar molecule overall, despite having polar B-F bonds, because:',
 "options":{"A":'Boron has no valence electrons available for bonding', "B":'Fluorine atoms are themselves nonpolar', "C":'Its trigonal planar geometry causes the three bond dipoles to cancel symmetrically', "D":'Boron carries a lone pair that balances the dipoles'},"answer":'C'},
{"id":92,"subject":'Chemistry',"topic":'Chemical Bonding',"difficulty":'Hard',
 "question":'Diamond has an extremely high melting point mainly because:',
 "options":{"A":'Each carbon atom is covalently bonded to four others in a rigid three-dimensional network', "B":'It consists of individual, weakly bonded molecules', "C":'It is held together only by weak van der Waals forces', "D":'It forms an ionic crystal lattice'},"answer":'A'},
{"id":93,"subject":'Chemistry',"topic":'States of Matter',"difficulty":'Easy',
 "question":'The change of state from liquid to gas occurring at the surface of a liquid, below its boiling point, is called:',
 "options":{"A":'Boiling', "B":'Evaporation', "C":'Condensation', "D":'Sublimation'},"answer":'B'},
{"id":94,"subject":'Chemistry',"topic":'States of Matter',"difficulty":'Medium',
 "question":"A gas occupies 4.0 L at 3.0 atm. What volume will it occupy at 6.0 atm, assuming constant temperature (Boyle's Law)?",
 "options":{"A":'8.0 L', "B":'12.0 L', "C":'4.0 L', "D":'2.0 L'},"answer":'D'},
{"id":95,"subject":'Chemistry',"topic":'States of Matter',"difficulty":'Hard',
 "question":"A fixed mass of gas at 2 atm and 300 K is heated at constant volume until its temperature reaches 600 K. What is the new pressure (Gay-Lussac's Law)?",
 "options":{"A":'1 atm', "B":'2 atm', "C":'8 atm', "D":'4 atm'},"answer":'D'},
{"id":96,"subject":'Chemistry',"topic":'Stoichiometry',"difficulty":'Easy',
 "question":'The molar mass of water (H2O) is approximately:',
 "options":{"A":'16 g/mol', "B":'20 g/mol', "C":'34 g/mol', "D":'18 g/mol'},"answer":'D'},
{"id":97,"subject":'Chemistry',"topic":'Stoichiometry',"difficulty":'Medium',
 "question":'How many moles are present in 88 g of CO2 (molar mass 44 g/mol)?',
 "options":{"A":'0.5 mol', "B":'1 mol', "C":'2 mol', "D":'4 mol'},"answer":'C'},
{"id":98,"subject":'Chemistry',"topic":'Stoichiometry',"difficulty":'Hard',
 "question":'A 250 mL solution contains 0.1 mole of KCl. What is the molarity of this solution?',
 "options":{"A":'0.1 M', "B":'0.4 M', "C":'0.25 M', "D":'0.025 M'},"answer":'B'},
{"id":99,"subject":'Chemistry',"topic":'Stoichiometry',"difficulty":'Medium',
 "question":'In the balanced equation 2Mg + O2 -> 2MgO, how many moles of MgO are formed when 5 moles of Mg react completely with excess O2?',
 "options":{"A":'5', "B":'2.5', "C":'10', "D":'1'},"answer":'A'},
{"id":100,"subject":'Chemistry',"topic":'Thermochemistry',"difficulty":'Easy',
 "question":'The heat content of a system measured at constant pressure is called its:',
 "options":{"A":'Entropy', "B":'Enthalpy', "C":'Free energy', "D":'Activation energy'},"answer":'B'},
{"id":101,"subject":'Chemistry',"topic":'Thermochemistry',"difficulty":'Medium',
 "question":'If breaking the bonds in the reactants requires more energy than is released when new bonds form in the products, the reaction is:',
 "options":{"A":'Exothermic', "B":'Endothermic', "C":'Always at equilibrium', "D":'Necessarily non-spontaneous'},"answer":'B'},
{"id":102,"subject":'Chemistry',"topic":'Chemical Equilibrium',"difficulty":'Medium',
 "question":'For the equilibrium 2SO2(g) + O2(g) <-> 2SO3(g), decreasing the container volume (increasing pressure) will shift the equilibrium:',
 "options":{"A":'Toward the reactants', "B":'Toward the side with fewer moles of gas (the products)', "C":'Not at all, since pressure has no effect', "D":'Completely to the reactant side'},"answer":'B'},
{"id":103,"subject":'Chemistry',"topic":'Chemical Equilibrium',"difficulty":'Hard',
 "question":'The equilibrium constant, Keq, for a given reaction changes only when:',
 "options":{"A":'A catalyst is added to the system', "B":'The temperature of the system is changed', "C":'The concentration of a reactant is increased', "D":'The pressure is changed at constant temperature'},"answer":'B'},
{"id":104,"subject":'Chemistry',"topic":'Reaction Kinetics',"difficulty":'Easy',
 "question":'Raising the temperature of a reaction generally increases its rate mainly because:',
 "options":{"A":'It decreases the activation energy needed', "B":'It decreases the frequency of particle collisions', "C":'More particles collide with sufficient energy to react', "D":'It lowers the average kinetic energy of particles'},"answer":'C'},
{"id":105,"subject":'Chemistry',"topic":'Reaction Kinetics',"difficulty":'Medium',
 "question":'A reaction is found to be first order with respect to reactant A. Doubling the concentration of A will:',
 "options":{"A":'Double the reaction rate', "B":'Have no effect on the reaction rate', "C":'Quadruple the reaction rate', "D":'Halve the reaction rate'},"answer":'A'},
{"id":106,"subject":'Chemistry',"topic":'Electrochemistry',"difficulty":'Medium',
 "question":'In a galvanic (voltaic) cell, reduction occurs at the:',
 "options":{"A":'Anode', "B":'Cathode', "C":'Salt bridge', "D":'External wire'},"answer":'B'},
{"id":107,"subject":'Chemistry',"topic":'Electrochemistry',"difficulty":'Hard',
 "question":'In the reaction Mg(s) + 2AgNO3(aq) -> Mg(NO3)2(aq) + 2Ag(s), the silver ion (Ag+) acts as the:',
 "options":{"A":'Reducing agent', "B":'Neither oxidized nor reduced', "C":'Oxidizing agent', "D":'Catalyst'},"answer":'C'},
{"id":108,"subject":'Chemistry',"topic":'Acids & Bases',"difficulty":'Easy',
 "question":'A solution with pH = 7 at 25 degrees C is:',
 "options":{"A":'Acidic', "B":'Neutral', "C":'Basic', "D":'Not chemically possible'},"answer":'B'},
{"id":109,"subject":'Chemistry',"topic":'Acids & Bases',"difficulty":'Medium',
 "question":'A solution has a hydrogen ion concentration [H+] = 1x10^-9 M. What is its pH?',
 "options":{"A":'5', "B":'0.9', "C":'-9', "D":'9'},"answer":'D'},
{"id":110,"subject":'Chemistry',"topic":'Acids & Bases',"difficulty":'Medium',
 "question":'The graph shows the change in pH as HCl solution is gradually added to 20 mL of NaOH solution. Based on the curve, what is the approximate volume of HCl required to reach the equivalence point?',
 "image":'images/q_titration_curve_hcl_naoh.png',
 "options":{"A":'10 mL', "B":'20 mL', "C":'30 mL', "D":'40 mL'},"answer":'B'},
{"id":111,"subject":'Chemistry',"topic":'Acids & Bases',"difficulty":'Hard',
 "question":'A buffer solution made of acetic acid and sodium acetate maintains a relatively stable pH mainly because:',
 "options":{"A":'It contains only a strong acid', "B":'The solution has no chemical equilibrium', "C":'Sodium acetate behaves as a strong base', "D":'Added H+ reacts with the acetate ions, and added OH- reacts with the acetic acid, minimizing the pH change'},"answer":'D'},
{"id":112,"subject":'Chemistry',"topic":'Organic Chemistry',"difficulty":'Easy',
 "question":'The general formula CnH2n-2 (with one triple bond, or a ring plus a double bond) most directly corresponds to the:',
 "options":{"A":'Alkyne series', "B":'Alkane series', "C":'Alkene series', "D":'Cycloalkane series'},"answer":'A'},
{"id":113,"subject":'Chemistry',"topic":'Organic Chemistry',"difficulty":'Medium',
 "question":'Aldehydes and ketones both contain a carbonyl (C=O) group; they differ mainly in that:',
 "options":{"A":'Ketones are never found in naturally occurring compounds', "B":'Aldehydes contain no oxygen atom', "C":'Aldehydes have the carbonyl group at the end of the carbon chain, while ketones have it within the chain', "D":'Ketones always contain an -OH group'},"answer":'C'},
{"id":114,"subject":'Chemistry',"topic":'Organic Chemistry',"difficulty":'Medium',
 "question":'The functional group -NH2 attached to a carbon chain characterizes a class of compounds called:',
 "options":{"A":'Amides', "B":'Esters', "C":'Amines', "D":'Nitriles'},"answer":'C'},
{"id":115,"subject":'Chemistry',"topic":'Organic Chemistry',"difficulty":'Hard',
 "question":'In an SN1 reaction of a tertiary haloalkane, the rate-determining step involves:',
 "options":{"A":'Simultaneous bond breaking and bond forming in a single concerted step', "B":'Formation of a relatively stable carbocation intermediate after the leaving group departs', "C":'Direct attack of the nucleophile on the halide ion itself', "D":'Formation of a covalent network solid'},"answer":'B'},
{"id":116,"subject":'Chemistry',"topic":'Organic Chemistry',"difficulty":'Medium',
 "question":'Polymerization of ethene (CH2=CH2) under high pressure to form polyethylene is an example of:',
 "options":{"A":'Condensation polymerization', "B":'Hydrolysis', "C":'Addition polymerization', "D":'Esterification'},"answer":'C'},
{"id":117,"subject":'Chemistry',"topic":'Organic Chemistry',"difficulty":'Easy',
 "question":'Structural isomers have the same molecular formula but differ in:',
 "options":{"A":'Their overall molecular mass', "B":'The connectivity or arrangement of their atoms', "C":'The number of atoms present', "D":'The elements present in the molecule'},"answer":'B'},
{"id":118,"subject":'Chemistry',"topic":'Inorganic Chemistry',"difficulty":'Medium',
 "question":'Alkaline earth metals (Group 2) are generally less reactive than alkali metals (Group 1) mainly because they:',
 "options":{"A":'Have two valence electrons, requiring more energy to remove both', "B":'Have a larger atomic radius than Group 1 metals', "C":'Have a completely full outer electron shell', "D":'Behave as non-metals'},"answer":'A'},
{"id":119,"subject":'Chemistry',"topic":'Inorganic Chemistry',"difficulty":'Medium',
 "question":'Fluorine is the most reactive of the halogens mainly because it:',
 "options":{"A":'Has the smallest atomic radius and highest electronegativity, strongly attracting an additional electron', "B":'Has the largest atomic radius among the halogens', "C":'Has the fewest valence electrons of any halogen', "D":'Cannot form ionic bonds'},"answer":'A'},
{"id":120,"subject":'Chemistry',"topic":'Inorganic Chemistry',"difficulty":'Hard',
 "question":"In the reaction Cu + 2AgNO3 -> Cu(NO3)2 + 2Ag, copper's oxidation state changes from:",
 "options":{"A":'+2 to 0 (reduction)', "B":'0 to -2', "C":'0 to +2 (oxidation)', "D":'No change in oxidation state occurs'},"answer":'C'},
{"id":121,"subject":'Chemistry',"topic":'Physical Chemistry',"difficulty":'Medium',
 "question":'The normality of a solution is defined as:',
 "options":{"A":'Moles of solute per liter of solution', "B":'Equivalents of solute per liter of solution', "C":'Moles of solute per kilogram of solvent', "D":'Grams of solute per liter of solution'},"answer":'B'},
{"id":122,"subject":'Chemistry',"topic":'Physical Chemistry',"difficulty":'Hard',
 "question":'25 mL of 0.2 M H2SO4 is required to exactly neutralize 50 mL of KOH solution (H2SO4 + 2KOH -> K2SO4 + 2H2O). What is the molarity of the KOH solution?',
 "options":{"A":'0.1 M', "B":'0.2 M', "C":'0.4 M', "D":'0.05 M'},"answer":'B'},
{"id":123,"subject":'Chemistry',"topic":'Environmental Chemistry',"difficulty":'Easy',
 "question":'The primary greenhouse gas released into the atmosphere by burning fossil fuels is:',
 "options":{"A":'Nitrogen', "B":'Argon', "C":'Carbon dioxide', "D":'Helium'},"answer":'C'},
{"id":124,"subject":'Chemistry',"topic":'Environmental Chemistry',"difficulty":'Medium',
 "question":'Biochemical Oxygen Demand (BOD) is used as a measure of:',
 "options":{"A":'The salinity of a water body', "B":'The amount of oxygen required by microorganisms to decompose organic matter in water, indicating pollution level', "C":'The acidity of rainwater specifically', "D":'The temperature of a water body'},"answer":'B'},
{"id":125,"subject":'Chemistry',"topic":'Chemical Bonding',"difficulty":'Easy',
 "question":'A triple covalent bond between two atoms involves the sharing of:',
 "options":{"A":'One pair of electrons', "B":'Two pairs of electrons', "C":'Three pairs of electrons', "D":'Four pairs of electrons'},"answer":'C'},
{"id":126,"subject":'Chemistry',"topic":'Atomic Structure',"difficulty":'Easy',
 "question":'Which subatomic particle is located in the nucleus, has approximately the same mass as a proton, but carries no electric charge?',
 "options":{"A":'Electron', "B":'Neutron', "C":'Positron', "D":'Photon'},"answer":'B'},

# ============================================================
# PHYSICS (36 questions) - id 127-162
# ============================================================
{"id":127,"subject":'Physics',"topic":'Kinematics',"difficulty":'Easy',
 "question":"A cyclist travels 240 m in 20 seconds at constant velocity. What is the cyclist's speed?",
 "options":{"A":'12 m/s', "B":'8 m/s', "C":'20 m/s', "D":'4800 m/s'},"answer":'A'},
{"id":128,"subject":'Physics',"topic":'Kinematics',"difficulty":'Medium',
 "question":'A car moving at 25 m/s decelerates uniformly to rest over 5 seconds. What is the magnitude of its deceleration?',
 "options":{"A":'5 m/s^2', "B":'125 m/s^2', "C":'2 m/s^2', "D":'0.2 m/s^2'},"answer":'A'},
{"id":129,"subject":'Physics',"topic":'Kinematics',"difficulty":'Hard',
 "question":'A ball is dropped from rest from a height of 45 m (g = 10 m/s^2, ignoring air resistance). How long does it take to hit the ground?',
 "options":{"A":'4.5 s', "B":'3 s', "C":'9 s', "D":'2 s'},"answer":'B'},
{"id":130,"subject":'Physics',"topic":'Dynamics',"difficulty":'Easy',
 "question":'A net force acting on an object at rest will cause it to:',
 "options":{"A":'Remain at constant velocity always', "B":'Accelerate in the direction of the net force', "C":'Lose mass', "D":'Stop moving instantly'},"answer":'B'},
{"id":131,"subject":'Physics',"topic":'Dynamics',"difficulty":'Medium',
 "question":'A 3 kg object accelerates at 4 m/s^2 due to an applied net force. What is the magnitude of this force?',
 "options":{"A":'12 N', "B":'0.75 N', "C":'7 N', "D":'1 N'},"answer":'A'},
{"id":132,"subject":'Physics',"topic":'Dynamics',"difficulty":'Medium',
 "question":'A book resting on a table remains stationary mainly because:',
 "options":{"A":'No forces act on the book at all', "B":"Gravity is absent at the table's surface", "C":'Friction alone holds the book upward', "D":"The normal force from the table balances the book's weight, giving zero net force"},"answer":'D'},
{"id":133,"subject":'Physics',"topic":'Dynamics',"difficulty":'Hard',
 "question":"A 4 kg block is pushed horizontally with a 30 N force across a surface with a coefficient of kinetic friction of 0.25 (g = 10 m/s^2). What is the block's acceleration?",
 "options":{"A":'5 m/s^2', "B":'2.5 m/s^2', "C":'7.5 m/s^2', "D":'10 m/s^2'},"answer":'A'},
{"id":134,"subject":'Physics',"topic":'Work, Energy & Power',"difficulty":'Easy',
 "question":'If a force is applied to an object but the object does not move at all, the work done by that force is:',
 "options":{"A":'Zero', "B":'Maximum', "C":'Negative', "D":'Equal to the applied force'},"answer":'A'},
{"id":135,"subject":'Physics',"topic":'Work, Energy & Power',"difficulty":'Medium',
 "question":'A 5 kg object is raised to a height of 4 m (g = 10 m/s^2). What is its gravitational potential energy at that height?',
 "options":{"A":'20 J', "B":'50 J', "C":'400 J', "D":'200 J'},"answer":'D'},
{"id":136,"subject":'Physics',"topic":'Work, Energy & Power',"difficulty":'Medium',
 "question":'A 3 kg object moving at 4 m/s has a kinetic energy of:',
 "options":{"A":'12 J', "B":'24 J', "C":'48 J', "D":'6 J'},"answer":'B'},
{"id":137,"subject":'Physics',"topic":'Work, Energy & Power',"difficulty":'Hard',
 "question":'A crane lifts a 500 kg load to a height of 8 m in 10 seconds (g = 10 m/s^2). What is the power output of the crane?',
 "options":{"A":'400 W', "B":'40000 W', "C":'500 W', "D":'4000 W'},"answer":'D'},
{"id":138,"subject":'Physics',"topic":'Circular Motion & Gravitation',"difficulty":'Easy',
 "question":'The centripetal acceleration of an object in uniform circular motion is always directed:',
 "options":{"A":'Tangent to the circular path', "B":'Away from the center of the circle', "C":"In the same direction as the object's velocity", "D":'Toward the center of the circle'},"answer":'D'},
{"id":139,"subject":'Physics',"topic":'Circular Motion & Gravitation',"difficulty":'Medium',
 "question":"If the distance between two masses is halved while both masses stay the same, the gravitational force between them (per Newton's law of gravitation) becomes:",
 "options":{"A":'Four times', "B":'Half', "C":'Double', "D":'One quarter'},"answer":'A'},
{"id":140,"subject":'Physics',"topic":'Circular Motion & Gravitation',"difficulty":'Hard',
 "question":"A geostationary satellite maintains a fixed position relative to a point on Earth's surface because its orbital period equals:",
 "options":{"A":"The Moon's orbital period around Earth", "B":'One Earth year', "C":'Zero', "D":'Exactly one Earth day (about 24 hours)'},"answer":'D'},
{"id":141,"subject":'Physics',"topic":'Fluid Mechanics',"difficulty":'Easy',
 "question":'The SI unit of pressure is the:',
 "options":{"A":'Pascal', "B":'Newton', "C":'Joule', "D":'Watt'},"answer":'A'},
{"id":142,"subject":'Physics',"topic":'Fluid Mechanics',"difficulty":'Medium',
 "question":'A solid metal object sinks when placed in water mainly because:',
 "options":{"A":'It has zero volume', "B":'Its density is greater than that of water, so its weight exceeds the buoyant force on it', "C":'The buoyant force on it is greater than its weight', "D":'Water has no density'},"answer":'B'},
{"id":143,"subject":'Physics',"topic":'Fluid Mechanics',"difficulty":'Hard',
 "question":"Water flows steadily through a horizontal pipe that narrows at one section. According to the continuity equation and Bernoulli's principle, at the narrower section the water's speed and pressure are, respectively:",
 "options":{"A":'Higher speed, higher pressure', "B":'Higher speed, lower pressure', "C":'Lower speed, lower pressure', "D":'Lower speed, higher pressure'},"answer":'B'},
{"id":144,"subject":'Physics',"topic":'Oscillations & Waves',"difficulty":'Easy',
 "question":'The maximum displacement of a particle from its equilibrium position in a wave is called its:',
 "options":{"A":'Amplitude', "B":'Wavelength', "C":'Frequency', "D":'Period'},"answer":'A'},
{"id":145,"subject":'Physics',"topic":'Oscillations & Waves',"difficulty":'Medium',
 "question":'A simple pendulum has a length L on Earth. If its length is doubled to 2L, its period of oscillation will:',
 "options":{"A":'Double', "B":'Decrease by a factor of the square root of 2', "C":'Increase by a factor of the square root of 2', "D":'Remain exactly the same'},"answer":'C'},
{"id":146,"subject":'Physics',"topic":'Oscillations & Waves',"difficulty":'Medium',
 "question":'A wave has a period of 0.02 seconds. What is its frequency?',
 "options":{"A":'50 Hz', "B":'0.02 Hz', "C":'2 Hz', "D":'500 Hz'},"answer":'A'},
{"id":147,"subject":'Physics',"topic":'Oscillations & Waves',"difficulty":'Hard',
 "question":'In a longitudinal wave, such as a sound wave, particles of the medium vibrate:',
 "options":{"A":'Perpendicular to the direction of wave travel', "B":'In small circles around a fixed point', "C":'They do not vibrate at all', "D":'Parallel to the direction of wave travel, creating compressions and rarefactions'},"answer":'D'},
{"id":148,"subject":'Physics',"topic":'Thermodynamics',"difficulty":'Easy',
 "question":'Heat is best described as:',
 "options":{"A":'Energy transferred between objects due to a temperature difference', "B":'The total kinetic energy contained within a substance', "C":'The average speed of particles in a substance', "D":'A distinct form of matter'},"answer":'A'},
{"id":149,"subject":'Physics',"topic":'Thermodynamics',"difficulty":'Medium',
 "question":'According to the zeroth law of thermodynamics, if object A is in thermal equilibrium with object B, and object B is in thermal equilibrium with object C, then:',
 "options":{"A":'A and C are always at different temperatures', "B":'Heat necessarily flows from A to C', "C":'A and B must always differ in temperature', "D":'A is in thermal equilibrium with C'},"answer":'D'},
{"id":150,"subject":'Physics',"topic":'Thermodynamics',"difficulty":'Hard',
 "question":'A gas expands and does 300 J of work on its surroundings while absorbing 450 J of heat. What is the change in internal energy of the gas?',
 "options":{"A":'150 J', "B":'750 J', "C":'300 J', "D":'-150 J'},"answer":'A'},
{"id":151,"subject":'Physics',"topic":'Electrostatics',"difficulty":'Easy',
 "question":'An object that has gained extra electrons becomes:',
 "options":{"A":'Negatively charged', "B":'Positively charged', "C":'Electrically neutral', "D":'Non-conductive'},"answer":'A'},
{"id":152,"subject":'Physics',"topic":'Electrostatics',"difficulty":'Medium',
 "question":"According to Coulomb's law, if one of two point charges is tripled while the distance between them stays constant, the electrostatic force between them becomes:",
 "options":{"A":'One third as large', "B":'Three times as large', "C":'Nine times as large', "D":'Unchanged'},"answer":'B'},
{"id":153,"subject":'Physics',"topic":'Current Electricity',"difficulty":'Easy',
 "question":'Electrical resistance is measured in units of:',
 "options":{"A":'Amperes', "B":'Volts', "C":'Watts', "D":'Ohms'},"answer":'D'},
{"id":154,"subject":'Physics',"topic":'Current Electricity',"difficulty":'Medium',
 "question":'In the circuit shown, R1 (4 ohm) and R2 (2 ohm) are connected in series, and this series combination is connected in parallel with R3 (6 ohm). What is the total resistance of the circuit?',
 "image":'images/q_circuit_diagram_r1r2r3.png',
 "options":{"A":'6 ohm', "B":'12 ohm', "C":'3 ohm', "D":'2 ohm'},"answer":'C'},
{"id":155,"subject":'Physics',"topic":'Current Electricity',"difficulty":'Hard',
 "question":'Three resistors of 6 ohm each are connected in parallel. What is their equivalent resistance?',
 "options":{"A":'18 ohm', "B":'6 ohm', "C":'2 ohm', "D":'3 ohm'},"answer":'C'},
{"id":156,"subject":'Physics',"topic":'Current Electricity',"difficulty":'Medium',
 "question":'A device operates at 110 V and draws a current of 4 A. What is its power consumption?',
 "options":{"A":'440 W', "B":'27.5 W', "C":'220 W', "D":'880 W'},"answer":'A'},
{"id":157,"subject":'Physics',"topic":'Electromagnetism',"difficulty":'Medium',
 "question":'The magnetic field lines produced around a long, straight current-carrying wire form:',
 "options":{"A":'Straight lines running parallel to the wire', "B":'A uniform field pointing in one fixed direction only', "C":'No magnetic field is produced at all', "D":'Concentric circles centered on the wire'},"answer":'D'},
{"id":158,"subject":'Physics',"topic":'Electromagnetism',"difficulty":'Hard',
 "question":'Increasing the number of turns in a solenoid, while keeping the current constant, will:',
 "options":{"A":'Decrease the strength of the magnetic field produced', "B":'Have no effect on the magnetic field strength', "C":'Reverse the direction of the magnetic field', "D":'Increase the strength of the magnetic field produced'},"answer":'D'},
{"id":159,"subject":'Physics',"topic":'Modern Physics',"difficulty":'Easy',
 "question":"The number of neutrons in an atom's nucleus can be found by:",
 "options":{"A":'Adding the atomic number to the mass number', "B":'The atomic number alone', "C":'Subtracting the atomic number from the mass number', "D":'The mass number alone'},"answer":'C'},
{"id":160,"subject":'Physics',"topic":'Modern Physics',"difficulty":'Medium',
 "question":'During gamma decay, a nucleus emits:',
 "options":{"A":'An electron', "B":'A helium nucleus', "C":'A proton', "D":'High-energy electromagnetic radiation, with no change in atomic or mass number'},"answer":'D'},
{"id":161,"subject":'Physics',"topic":'Modern Physics',"difficulty":'Hard',
 "question":'A radioactive sample has a half-life of 3 hours. Starting with 160 g of the sample, how much remains after 12 hours?',
 "options":{"A":'40 g', "B":'10 g', "C":'20 g', "D":'5 g'},"answer":'B'},
{"id":162,"subject":'Physics',"topic":'Optics',"difficulty":'Medium',
 "question":'The ray diagram shows an object placed between the focal point (F) and a converging (convex) lens. Based on the diagram, the image formed on the same side as the object is:',
 "image":'images/q_lens_diagram_object_inside_f.png',
 "options":{"A":'Real, inverted, and diminished', "B":'Real, upright, and the same size as the object', "C":'Virtual, upright, and magnified', "D":'Virtual, inverted, and diminished'},"answer":'C'},

# ============================================================
# ENGLISH (9 questions) - id 163-171
# ============================================================
{"id":163,"subject":'English',"topic":'Synonyms',"difficulty":'Easy',
 "question":"Choose the word most nearly similar in meaning to 'METICULOUS':",
 "options":{"A":'Careless', "B":'Painstaking', "C":'Hasty', "D":'Indifferent'},"answer":'B'},
{"id":164,"subject":'English',"topic":'Antonyms',"difficulty":'Easy',
 "question":"Choose the word most nearly opposite in meaning to 'TRANSPARENT':",
 "options":{"A":'Clear', "B":'Obvious', "C":'Visible', "D":'Opaque'},"answer":'D'},
{"id":165,"subject":'English',"topic":'Grammar',"difficulty":'Easy',
 "question":'Choose the grammatically correct sentence:',
 "options":{"A":'Each of the girls have her own book.', "B":'Each of the girls has their own book.', "C":'Each of the girl has her own book.', "D":'Each of the girls has her own book.'},"answer":'D'},
{"id":166,"subject":'English',"topic":'Grammar',"difficulty":'Medium',
 "question":'Choose the correct sentence:',
 "options":{"A":'By next year, she will complete her degree.', "B":'By next year, she completes her degree.', "C":'By next year, she is completing her degree.', "D":'By next year, she will have completed her degree.'},"answer":'D'},
{"id":167,"subject":'English',"topic":'Sentence Correction',"difficulty":'Medium',
 "question":'Identify the sentence that follows correct subject-verb agreement:',
 "options":{"A":'The number of students have increased this year.', "B":'A number of students has increased this year.', "C":'The numbers of student has increased this year.', "D":'The number of students has increased this year.'},"answer":'D'},
{"id":168,"subject":'English',"topic":'Vocabulary',"difficulty":'Medium',
 "question":"Choose the word that best completes the sentence: 'The politician's speech was full of ______ promises that were never intended to be kept.'",
 "options":{"A":'Hollow', "B":'Sincere', "C":'Genuine', "D":'Reliable'},"answer":'A'},
{"id":169,"subject":'English',"topic":'Idioms',"difficulty":'Medium',
 "question":"Choose the meaning closest to the idiom 'to let the cat out of the bag':",
 "options":{"A":'To reveal a secret accidentally', "B":'To adopt a pet unexpectedly', "C":'To escape from a difficult situation', "D":'To become very angry'},"answer":'A'},
{"id":170,"subject":'English',"topic":'Sentence Correction',"difficulty":'Hard',
 "question":"Choose the option that best corrects the sentence: 'Each of the members were asked to submit their report by Friday.'",
 "options":{"A":'Each of the members were asked to submit his report by Friday.', "B":'Each of the member was asked to submit their reports by Friday.', "C":'Each of the members was asked to submit their reports by Friday.', "D":'Each of the members was asked to submit his or her report by Friday.'},"answer":'D'},
{"id":171,"subject":'English',"topic":'Prepositions',"difficulty":'Hard',
 "question":"Choose the correct preposition to complete the sentence: 'The teacher insisted ______ punctuality from all her students.'",
 "options":{"A":'at', "B":'with', "C":'on', "D":'for'},"answer":'C'},

# ============================================================
# LOGICAL REASONING (9 questions) - id 172-180
# ============================================================
{"id":172,"subject":'Logical Reasoning',"topic":'Number Series',"difficulty":'Easy',
 "question":'Find the next number in the series: 5, 10, 20, 40, ?',
 "options":{"A":'60', "B":'70', "C":'50', "D":'80'},"answer":'D'},
{"id":173,"subject":'Logical Reasoning',"topic":'Number Series',"difficulty":'Easy',
 "question":'Find the missing number: 2, 5, 8, 11, ?',
 "options":{"A":'13', "B":'15', "C":'14', "D":'12'},"answer":'C'},
{"id":174,"subject":'Logical Reasoning',"topic":'Analogies',"difficulty":'Easy',
 "question":'Author is to Book as Composer is to:',
 "options":{"A":'Instrument', "B":'Orchestra', "C":'Concert', "D":'Symphony'},"answer":'D'},
{"id":175,"subject":'Logical Reasoning',"topic":'Analogies',"difficulty":'Medium',
 "question":'Key is to Lock as Password is to:',
 "options":{"A":'Computer', "B":'Account', "C":'Security', "D":'Login screen'},"answer":'B'},
{"id":176,"subject":'Logical Reasoning',"topic":'Blood Relations',"difficulty":'Medium',
 "question":"Pointing to a man in a photograph, Aisha said, 'He is the only son of my father's only daughter.' How is the man related to Aisha?",
 "options":{"A":'Brother', "B":'Nephew', "C":'Son', "D":'Father'},"answer":'C'},
{"id":177,"subject":'Logical Reasoning',"topic":'Coding-Decoding',"difficulty":'Medium',
 "question":'If in a certain code, LION is written as MJPO, how is TIGER written in the same code?',
 "options":{"A":'UJHFT', "B":'SJHFS', "C":'UJHFS', "D":'UIHFS'},"answer":'C'},
{"id":178,"subject":'Logical Reasoning',"topic":'Syllogism',"difficulty":'Hard',
 "question":'All squares are rectangles. All rectangles have four sides. Which conclusion logically follows?',
 "options":{"A":'All four-sided figures are squares', "B":'No squares have four sides', "C":'All squares have four sides', "D":'Some rectangles are not squares'},"answer":'C'},
{"id":179,"subject":'Logical Reasoning',"topic":'Pattern Recognition',"difficulty":'Hard',
 "question":'Find the next term in the series: 1, 2, 4, 7, 11, ?',
 "options":{"A":'16', "B":'14', "C":'15', "D":'18'},"answer":'A'},
{"id":180,"subject":'Logical Reasoning',"topic":'Direction Sense',"difficulty":'Medium',
 "question":'A boy walks 6 km south, then turns left and walks 8 km, then turns left again and walks 6 km. How far is he from his starting point?',
 "options":{"A":'20 km', "B":'14 km', "C":'6 km', "D":'8 km'},"answer":'D'},
]


# ------------------------------------------------------------
# Sanity-check / summary utility
# ------------------------------------------------------------
def summarize(questions):
    from collections import Counter
    subj = Counter(q["subject"] for q in questions)
    diff = Counter(q["difficulty"] for q in questions)
    ans = Counter(q["answer"] for q in questions)
    ids = [q["id"] for q in questions]
    dup_ids = [i for i in set(ids) if ids.count(i) > 1]
    dup_q = [q["question"] for q in questions]
    dup_questions = [t for t in set(dup_q) if dup_q.count(t) > 1]
    images = [q for q in questions if "image" in q]

    print(f"Total questions: {len(questions)}")
    print("\nBy subject:")
    for s, c in subj.items():
        print(f"  {s}: {c}")
    print("\nBy difficulty:")
    for d, c in diff.items():
        print(f"  {d}: {c}")
    print("\nBy correct-answer letter (should be roughly balanced):")
    for L in ["A", "B", "C", "D"]:
        print(f"  {L}: {ans[L]}")
    print(f"\nDuplicate IDs: {dup_ids if dup_ids else 'None'}")
    print(f"Duplicate question text: {dup_questions if dup_questions else 'None'}")
    print(f"\nImage-based questions ({len(images)}):")
    for q in images:
        print(f"  Q{q['id']} [{q['subject']}] -> {q['image']}")

    for q in questions:
        assert set(q["options"].keys()) == {"A", "B", "C", "D"}, f"Q{q['id']} missing an option"
        assert q["answer"] in q["options"], f"Q{q['id']} answer key invalid"
    print("\nAll questions have exactly 4 options (A-D) and a valid answer key. OK.")


def print_answer_key(questions):
    print("\nANSWER KEY")
    print("-" * 40)
    for q in questions:
        print(f"{q['id']:>3}. {q['answer']}", end="   ")
        if q["id"] % 10 == 0:
            print()
    print()


if __name__ == "__main__":
    summarize(QUESTIONS)
    print_answer_key(QUESTIONS)