"""
MDCAT Mock Test 7
==================
Full-length mock test: 180 MCQs
Weightage: Biology 81 | Chemistry 45 | Physics 36 | English 9 | Logical Reasoning 9
Difficulty mix (approx): 30% Easy / 50% Medium / 20% Hard, distributed throughout.

Includes 5 image/diagram-based questions (2 Biology, 1 Chemistry, 2 Physics).
Each such question has an "image" key giving a relative path to a PNG diagram
that must be viewed alongside the question (images/ subfolder, shipped alongside
this file). Diagrams: comparative enzyme-activity-vs-pH graph, labeled animal-cell
structure (rough ER), a weak-acid/strong-base titration curve showing the buffering
region, a series-then-parallel resistor circuit, and a concave-mirror ray diagram
(object beyond the center of curvature).

Each question is a dict:
    id, subject, topic, difficulty, question, [image], options (A-D), answer (correct letter)

Run this file directly to print a summary / sanity-check the paper.
"""

QUESTIONS = [
# ============================================================
# BIOLOGY (81 questions) - id 1-81
# ============================================================
{"id":1,"subject":'Biology',"topic":'Biomolecules',"difficulty":'Easy',
 "question":'Which class of biomolecule serves as the primary long-term energy storage molecule in animals?',
 "options":{"A":'Proteins', "B":'Fats (lipids)', "C":'Nucleic acids', "D":'Vitamins'},"answer":'B'},
{"id":2,"subject":'Biology',"topic":'Biomolecules',"difficulty":'Easy',
 "question":'The monomer unit of a nucleic acid is called a:',
 "options":{"A":'Amino acid', "B":'Monosaccharide', "C":'Fatty acid', "D":'Nucleotide'},"answer":'D'},
{"id":3,"subject":'Biology',"topic":'Biomolecules',"difficulty":'Medium',
 "question":'Quaternary structure in a protein refers to:',
 "options":{"A":'The linear amino acid sequence', "B":'Folding of a single chain into a helix', "C":'The arrangement and interaction of two or more separate polypeptide subunits into a functional complex', "D":'The bonding of a single amino acid to a coenzyme'},"answer":'C'},
{"id":4,"subject":'Biology',"topic":'Biomolecules',"difficulty":'Medium',
 "question":'Which of the following best explains why enzymes are proteins with highly specific three-dimensional shapes?',
 "options":{"A":'Their shape creates an active site that binds only a specific substrate or class of substrates', "B":'Their shape is irrelevant to function', "C":'All proteins are enzymes', "D":'Shape only matters for structural proteins'},"answer":'A'},
{"id":5,"subject":'Biology',"topic":'Biomolecules',"difficulty":'Hard',
 "question":'Nucleotides are joined together in a nucleic acid strand by:',
 "options":{"A":'Peptide bonds between bases', "B":'Glycosidic bonds between phosphate groups', "C":'Phosphodiester bonds between the sugar of one nucleotide and the phosphate of the next', "D":'Hydrogen bonds along the backbone'},"answer":'C'},
{"id":6,"subject":'Biology',"topic":'Enzymes',"difficulty":'Easy',
 "question":'Molecules that must bind to certain enzymes before they can function are called:',
 "options":{"A":'Substrates', "B":'Products', "C":'Cofactors', "D":'Inhibitors'},"answer":'C'},
{"id":7,"subject":'Biology',"topic":'Enzymes',"difficulty":'Medium',
 "question":'Which factor, if increased far beyond the optimum, typically causes an enzyme to lose activity due to denaturation?',
 "options":{"A":'Temperature', "B":'Substrate concentration', "C":'Enzyme concentration', "D":'Presence of a cofactor'},"answer":'A'},
{"id":8,"subject":'Biology',"topic":'Enzymes',"difficulty":'Medium',
 "question":'The graph compares the activity of two digestive enzymes, X and Y, across a range of pH values. Enzyme X shows peak activity around pH 2, while enzyme Y shows peak activity around pH 8. Based on this, enzyme Y most likely functions in the:',
 "image":'images/q7_enzyme_ph_comparison_graph.png',
 "options":{"A":'Stomach', "B":'Mouth', "C":'Small intestine', "D":'Esophagus'},"answer":'C'},
{"id":9,"subject":'Biology',"topic":'Enzymes',"difficulty":'Hard',
 "question":'The Michaelis constant (Km) of an enzyme represents the substrate concentration at which:',
 "options":{"A":'The reaction rate is at its absolute maximum (Vmax)', "B":'No product is formed', "C":'The reaction rate is exactly half of Vmax', "D":'The enzyme is fully saturated'},"answer":'C'},
{"id":10,"subject":'Biology',"topic":'Cell Biology',"difficulty":'Easy',
 "question":'Which structure provides shape and rigidity to plant cells and is composed mainly of cellulose?',
 "options":{"A":'Cell wall', "B":'Plasma membrane', "C":'Nuclear envelope', "D":'Cytoskeleton'},"answer":'A'},
{"id":11,"subject":'Biology',"topic":'Cell Biology',"difficulty":'Easy',
 "question":'The site within the cell where lipids are synthesized and calcium ions are stored (especially in muscle cells) is the:',
 "options":{"A":'Rough endoplasmic reticulum', "B":'Smooth endoplasmic reticulum', "C":'Golgi apparatus', "D":'Lysosome'},"answer":'B'},
{"id":12,"subject":'Biology',"topic":'Cell Biology',"difficulty":'Medium',
 "question":'Which of the following best distinguishes a eukaryotic cell from a prokaryotic cell?',
 "options":{"A":'Presence of a cell membrane', "B":'Presence of membrane-bound organelles, including a nucleus', "C":'Presence of ribosomes', "D":'Ability to carry out metabolism'},"answer":'B'},
{"id":13,"subject":'Biology',"topic":'Cell Biology',"difficulty":'Medium',
 "question":'Vacuoles in mature plant cells primarily function to:',
 "options":{"A":'Synthesize proteins', "B":'Maintain turgor pressure and store water, ions, and pigments', "C":'Produce ATP', "D":'Package and modify proteins'},"answer":'B'},
{"id":14,"subject":'Biology',"topic":'Cell Biology',"difficulty":'Medium',
 "question":'The diagram shows an animal cell with structures labeled J, K, L, and M. Structure J is a network of membranes studded with ribosomes on its outer surface, involved in synthesizing proteins destined for secretion. Which structure is J?',
 "image":'images/q7_cell_diagram_jklm.png',
 "options":{"A":'Structure K (smooth endoplasmic reticulum)', "B":'Structure L (Golgi apparatus)', "C":'Structure M (lysosome)', "D":'Structure J (rough endoplasmic reticulum)'},"answer":'D'},
{"id":15,"subject":'Biology',"topic":'Cell Biology',"difficulty":'Medium',
 "question":'The nuclear envelope is composed of:',
 "options":{"A":'A single membrane with no pores', "B":'A single layer of protein only', "C":'No membrane at all, just a boundary of chromatin', "D":'A double membrane with nuclear pores regulating molecular traffic'},"answer":'D'},
{"id":16,"subject":'Biology',"topic":'Cell Biology',"difficulty":'Hard',
 "question":'A cell exposed to a toxin that specifically destroys ribosomes would experience the most immediate difficulty with:',
 "options":{"A":'DNA replication', "B":'Protein synthesis', "C":'Lipid digestion', "D":'Waste excretion'},"answer":'B'},
{"id":17,"subject":'Biology',"topic":'Cell Membrane & Transport',"difficulty":'Easy',
 "question":'The tendency of water to move from a region of lower solute concentration to a region of higher solute concentration across a selectively permeable membrane is called:',
 "options":{"A":'Active transport', "B":'Osmosis', "C":'Facilitated diffusion', "D":'Exocytosis'},"answer":'B'},
{"id":18,"subject":'Biology',"topic":'Cell Membrane & Transport',"difficulty":'Medium',
 "question":'A cell placed in an isotonic solution will:',
 "options":{"A":'Swell and burst', "B":'Shrink and shrivel', "C":'Immediately divide', "D":'Experience no net change in water movement, as solute concentrations are equal inside and out'},"answer":'D'},
{"id":19,"subject":'Biology',"topic":'Cell Membrane & Transport',"difficulty":'Medium',
 "question":'Phagocytosis is a specific type of endocytosis in which a cell:',
 "options":{"A":'Takes in dissolved molecules in small vesicles', "B":'Releases waste products', "C":'Engulfs large solid particles, such as bacteria or debris', "D":'Exchanges gases across the membrane'},"answer":'C'},
{"id":20,"subject":'Biology',"topic":'Cell Membrane & Transport',"difficulty":'Hard',
 "question":'Secondary active transport, such as the sodium-glucose cotransporter, differs from primary active transport in that it:',
 "options":{"A":'Directly uses ATP to move the solute of interest', "B":'Moves substances only down their concentration gradient without any energy source', "C":'Uses the potential energy stored in an ion gradient (itself established by primary active transport) to move another substance', "D":'Occurs only in plant cells'},"answer":'C'},
{"id":21,"subject":'Biology',"topic":'Cell Membrane & Transport',"difficulty":'Easy',
 "question":'Integral membrane proteins differ from peripheral membrane proteins in that integral proteins:',
 "options":{"A":'Are loosely attached to the membrane surface only', "B":'Never interact with the membrane', "C":'Are embedded within, and often span, the phospholipid bilayer', "D":'Are found only outside the cell'},"answer":'C'},
{"id":22,"subject":'Biology',"topic":'Cell Cycle & Division',"difficulty":'Easy',
 "question":'The stage of the cell cycle during which a cell is not actively dividing, but is growing and carrying out normal functions, is broadly called:',
 "options":{"A":'Mitosis', "B":'Cytokinesis', "C":'Interphase', "D":'Anaphase'},"answer":'C'},
{"id":23,"subject":'Biology',"topic":'Cell Cycle & Division',"difficulty":'Easy',
 "question":'During prophase of mitosis, which of the following events occurs?',
 "options":{"A":'Chromosomes align at the metaphase plate', "B":'Sister chromatids separate', "C":'The cell physically divides into two', "D":'Chromatin condenses into visible chromosomes and the nuclear envelope begins to break down'},"answer":'D'},
{"id":24,"subject":'Biology',"topic":'Cell Cycle & Division',"difficulty":'Medium',
 "question":'Meiosis produces gametes with half the chromosome number of the parent cell mainly because it involves:',
 "options":{"A":'Two rounds of DNA replication and one round of division', "B":'No DNA replication at all', "C":'One round of DNA replication followed by two rounds of cell division', "D":'The complete loss of half the DNA'},"answer":'C'},
{"id":25,"subject":'Biology',"topic":'Cell Cycle & Division',"difficulty":'Medium',
 "question":'A cell with a diploid number of 24 undergoes meiosis. How many chromosomes will be present in each of the four resulting gametes?',
 "options":{"A":'24', "B":'6', "C":'12', "D":'48'},"answer":'C'},
{"id":26,"subject":'Biology',"topic":'Cell Cycle & Division',"difficulty":'Medium',
 "question":'Which of the following contributes to genetic variation among offspring produced by sexual reproduction?',
 "options":{"A":'Mitosis alone', "B":'DNA replication during S phase', "C":'Cytokinesis', "D":'Crossing over and independent assortment during meiosis'},"answer":'D'},
{"id":27,"subject":'Biology',"topic":'Cell Cycle & Division',"difficulty":'Hard',
 "question":'Cancer cells often result from mutations that disable cell cycle checkpoints, primarily leading to:',
 "options":{"A":'Controlled, regulated cell division', "B":'Immediate cell death', "C":'Complete cessation of the cell cycle', "D":'Uncontrolled cell division, since damaged cells are no longer halted before dividing'},"answer":'D'},
{"id":28,"subject":'Biology',"topic":'Genetics',"difficulty":'Easy',
 "question":'In guinea pigs, black fur (B) is dominant over white fur (b). Crossing two heterozygous black guinea pigs (Bb x Bb) produces offspring in what genotypic ratio?',
 "options":{"A":'All Bb', "B":'1 BB : 2 Bb : 1 bb', "C":'3 BB : 1 bb', "D":'1 BB : 1 bb'},"answer":'B'},
{"id":29,"subject":'Biology',"topic":'Genetics',"difficulty":'Medium',
 "question":'In a dihybrid cross used as a test cross (AaBb x aabb), what phenotypic ratio is expected among the offspring, assuming independent assortment?',
 "options":{"A":'9:3:3:1', "B":'3:1', "C":'1:1:1:1', "D":'1:2:1'},"answer":'C'},
{"id":30,"subject":'Biology',"topic":'Genetics',"difficulty":'Medium',
 "question":'Red-green color blindness is X-linked recessive. A color-blind man and a woman who is homozygous normal have children. What proportion of their sons is expected to be color-blind?',
 "options":{"A":'50%', "B":'100%', "C":'0%', "D":'25%'},"answer":'C'},
{"id":31,"subject":'Biology',"topic":'Genetics',"difficulty":'Hard',
 "question":'In a trihybrid cross AaBbCc x AaBbCc, assuming independent assortment, what fraction of offspring is expected to be homozygous recessive for all three traits?',
 "options":{"A":'1/16', "B":'1/4', "C":'1/64', "D":'1/8'},"answer":'C'},
{"id":32,"subject":'Biology',"topic":'Genetics',"difficulty":'Medium',
 "question":'A woman with blood type O and a man who is heterozygous for blood type A (IAi) have children. Which blood types are possible among their offspring?',
 "options":{"A":'A and O only', "B":'Only A', "C":'A, B, and O', "D":'Only O'},"answer":'A'},
{"id":33,"subject":'Biology',"topic":'Genetics',"difficulty":'Hard',
 "question":'A trait that appears only when inherited from an affected mother, and never from an affected father, and is passed to all her children, is most consistent with:',
 "options":{"A":'Autosomal dominant inheritance', "B":'X-linked recessive inheritance', "C":'Y-linked inheritance', "D":'Mitochondrial (maternal) inheritance'},"answer":'D'},
{"id":34,"subject":'Biology',"topic":'Genetics',"difficulty":'Medium',
 "question":"In a certain plant species, flower color is controlled by two genes, with specific gene combinations producing several distinct color phenotypes not explained by a simple 3:1 ratio. This pattern of one gene's expression affecting or masking another gene's phenotype is called:",
 "options":{"A":'Codominance', "B":'Epistasis', "C":'Incomplete dominance', "D":'Polygenic inheritance'},"answer":'B'},
{"id":35,"subject":'Biology',"topic":'Molecular Biology',"difficulty":'Easy',
 "question":'The sugar found in DNA nucleotides is:',
 "options":{"A":'Deoxyribose', "B":'Ribose', "C":'Glucose', "D":'Fructose'},"answer":'A'},
{"id":36,"subject":'Biology',"topic":'Molecular Biology',"difficulty":'Easy',
 "question":'The process by which a cell copies its DNA before division is called:',
 "options":{"A":'Transcription', "B":'Replication', "C":'Translation', "D":'Splicing'},"answer":'B'},
{"id":37,"subject":'Biology',"topic":'Molecular Biology',"difficulty":'Medium',
 "question":'The leading strand during DNA replication is synthesized:',
 "options":{"A":'Discontinuously, in short fragments', "B":'Only after the lagging strand is complete', "C":'Continuously, in the same direction as the replication fork movement', "D":"In the 3' to 5' direction"},"answer":'C'},
{"id":38,"subject":'Biology',"topic":'Molecular Biology',"difficulty":'Medium',
 "question":'During translation, the ribosome moves along the mRNA in which direction, reading codons sequentially?',
 "options":{"A":"3' to 5'", "B":'Randomly in either direction', "C":"5' to 3'", "D":'It does not move at all'},"answer":'C'},
{"id":39,"subject":'Biology',"topic":'Molecular Biology',"difficulty":'Medium',
 "question":'A mutation in which a single nucleotide is replaced by a different one, but the resulting amino acid remains the same due to codon degeneracy, is a:',
 "options":{"A":'Missense mutation', "B":'Silent mutation', "C":'Nonsense mutation', "D":'Frameshift mutation'},"answer":'B'},
{"id":40,"subject":'Biology',"topic":'Molecular Biology',"difficulty":'Hard',
 "question":"Which type of mutation is generally expected to have the most severe effect on a protein's function?",
 "options":{"A":'A silent mutation', "B":'A missense mutation that substitutes a chemically very similar amino acid', "C":'A frameshift mutation caused by insertion or deletion of a single nucleotide', "D":'None of these affect protein function'},"answer":'C'},
{"id":41,"subject":'Biology',"topic":'Molecular Biology',"difficulty":'Hard',
 "question":'The CAP (catabolite activator protein), when bound to cAMP, enhances transcription of the lac operon mainly by:',
 "options":{"A":'Directly destroying the lac repressor', "B":'Binding near the promoter and helping RNA polymerase bind more efficiently when glucose is scarce', "C":'Blocking RNA polymerase entirely', "D":'Converting lactose into glucose'},"answer":'B'},
{"id":42,"subject":'Biology',"topic":'Molecular Biology',"difficulty":'Medium',
 "question":"A gene's exons are best described as the sequences that:",
 "options":{"A":'Are retained in the mature mRNA and code for the protein', "B":'Are removed from the pre-mRNA before translation', "C":'Never appear in the final mRNA', "D":'Only exist in prokaryotic genes'},"answer":'A'},
{"id":43,"subject":'Biology',"topic":'Molecular Biology',"difficulty":'Medium',
 "question":'The process of removing introns and joining exons together in a pre-mRNA transcript is called:',
 "options":{"A":'Transcription', "B":'Translation', "C":'RNA splicing', "D":'Replication'},"answer":'C'},
{"id":44,"subject":'Biology',"topic":'Molecular Biology',"difficulty":'Easy',
 "question":'Which molecule physically carries a specific amino acid to the ribosome during translation?',
 "options":{"A":'mRNA', "B":'tRNA', "C":'rRNA', "D":'DNA'},"answer":'B'},
{"id":45,"subject":'Biology',"topic":'Evolution',"difficulty":'Easy',
 "question":"Charles Darwin's theory of evolution proposes that species change over time mainly through the mechanism of:",
 "options":{"A":'Use and disuse of organs', "B":'Direct transformation by the environment', "C":'Random extinction events only', "D":'Natural selection acting on heritable variation'},"answer":'D'},
{"id":46,"subject":'Biology',"topic":'Evolution',"difficulty":'Medium',
 "question":'Which of the following is considered direct evidence for evolution, observable within a human lifetime?',
 "options":{"A":'Antibiotic resistance evolving in bacterial populations under selective pressure', "B":'Fossil records alone', "C":'Comparative anatomy of ancient species', "D":'Geological rock strata'},"answer":'A'},
{"id":47,"subject":'Biology',"topic":'Evolution',"difficulty":'Medium',
 "question":'A population bottleneck, such as a natural disaster drastically reducing population size, primarily affects genetic diversity by:',
 "options":{"A":'Increasing it substantially', "B":'Having no effect on allele frequencies', "C":'Randomly eliminating much of the genetic variation that existed before the event', "D":'Guaranteeing survival of only the fittest alleles'},"answer":'C'},
{"id":48,"subject":'Biology',"topic":'Evolution',"difficulty":'Hard',
 "question":'In a population in Hardy-Weinberg equilibrium, the frequency of a recessive allele (q) is 0.3. What percentage of the population is expected to be homozygous dominant?',
 "options":{"A":'9%', "B":'42%', "C":'91%', "D":'49%'},"answer":'D'},
{"id":49,"subject":'Biology',"topic":'Classification & Diversity',"difficulty":'Easy',
 "question":'Carl Linnaeus is best known for developing the:',
 "options":{"A":'Theory of natural selection', "B":'Cell theory', "C":'Germ theory of disease', "D":'System of binomial nomenclature and hierarchical classification'},"answer":'D'},
{"id":50,"subject":'Biology',"topic":'Classification & Diversity',"difficulty":'Easy',
 "question":'Bacteria are classified in domain:',
 "options":{"A":'Eukarya', "B":'Archaea', "C":'Protista', "D":'Bacteria'},"answer":'D'},
{"id":51,"subject":'Biology',"topic":'Classification & Diversity',"difficulty":'Medium',
 "question":'Viruses are generally NOT classified within any of the three domains of life mainly because they:',
 "options":{"A":'Lack an independent metabolism and cannot reproduce without a host cell', "B":'Have a nucleus', "C":'Are exclusively harmful', "D":'Are too large to classify'},"answer":'A'},
{"id":52,"subject":'Biology',"topic":'Classification & Diversity',"difficulty":'Medium',
 "question":'An organism is unicellular, has a rigid cell wall made of chitin, and absorbs nutrients rather than ingesting them, though it is not photosynthetic. It most likely belongs to:',
 "options":{"A":'Kingdom Plantae', "B":'Kingdom Fungi', "C":'Kingdom Animalia', "D":'Kingdom Monera'},"answer":'B'},
{"id":53,"subject":'Biology',"topic":'Classification & Diversity',"difficulty":'Easy',
 "question":'Which of the following taxonomic ranks is the most specific and narrow?',
 "options":{"A":'Species', "B":'Genus', "C":'Family', "D":'Order'},"answer":'A'},
{"id":54,"subject":'Biology',"topic":'Classification & Diversity',"difficulty":'Medium',
 "question":'Members of phylum Mollusca, such as snails and octopuses, are characterized primarily by:',
 "options":{"A":'A soft body, often protected by a calcium carbonate shell, with a muscular foot', "B":'A segmented body with jointed appendages', "C":'Radial symmetry with no true organs', "D":'A notochord present throughout life'},"answer":'A'},
{"id":55,"subject":'Biology',"topic":'Plant Biology',"difficulty":'Easy',
 "question":'The vascular tissue responsible for transporting sugars produced during photosynthesis to other parts of a plant is the:',
 "options":{"A":'Phloem', "B":'Xylem', "C":'Cortex', "D":'Epidermis'},"answer":'A'},
{"id":56,"subject":'Biology',"topic":'Plant Biology',"difficulty":'Medium',
 "question":'In the Calvin cycle, the enzyme RuBisCO is responsible for:',
 "options":{"A":'Producing ATP directly from light', "B":'Splitting water into oxygen and hydrogen', "C":'Catalyzing the fixation of atmospheric CO2 onto a five-carbon sugar', "D":'Transporting electrons in the thylakoid membrane'},"answer":'C'},
{"id":57,"subject":'Biology',"topic":'Plant Biology',"difficulty":'Medium',
 "question":'The products of the Calvin cycle, used to regenerate its starting material and to synthesize glucose, are ultimately derived from:',
 "options":{"A":'Only oxygen from photolysis', "B":'ATP and NADPH generated during the light-dependent reactions', "C":'Nitrogen absorbed from soil', "D":'Carbon dioxide alone, without other inputs'},"answer":'B'},
{"id":58,"subject":'Biology',"topic":'Plant Biology',"difficulty":'Hard',
 "question":'Compared to C3 plants, C4 plants tend to be more efficient photosynthesizers in hot, sunny climates mainly because C4 plants:',
 "options":{"A":'Lack chlorophyll entirely', "B":'Minimize photorespiration by spatially separating initial CO2 fixation from the Calvin cycle', "C":'Perform photosynthesis exclusively at night', "D":'Have no stomata'},"answer":'B'},
{"id":59,"subject":'Biology',"topic":'Plant Biology',"difficulty":'Medium',
 "question":'Auxin, a plant hormone, is primarily responsible for:',
 "options":{"A":'Promoting cell elongation and influencing phototropism (bending toward light)', "B":'Promoting leaf senescence', "C":'Triggering seed dormancy exclusively', "D":'Closing stomata during drought'},"answer":'A'},
{"id":60,"subject":'Biology',"topic":'Plant Biology',"difficulty":'Easy',
 "question":'The process by which excess water evaporates from the surface of leaves, mainly through stomata, is called:',
 "options":{"A":'Germination', "B":'Transpiration', "C":'Pollination', "D":'Respiration'},"answer":'B'},
{"id":61,"subject":'Biology',"topic":'Human Physiology - Digestion',"difficulty":'Easy',
 "question":'Which organ produces bile, although it is stored elsewhere?',
 "options":{"A":'Gallbladder', "B":'Liver', "C":'Pancreas', "D":'Stomach'},"answer":'B'},
{"id":62,"subject":'Biology',"topic":'Human Physiology - Digestion',"difficulty":'Medium',
 "question":"The stomach's highly acidic environment (pH around 2) serves mainly to:",
 "options":{"A":'Complete digestion of all nutrients', "B":'Activate pepsinogen into pepsin and help kill ingested pathogens', "C":'Neutralize bile', "D":'Absorb the majority of nutrients'},"answer":'B'},
{"id":63,"subject":'Biology',"topic":'Human Physiology - Digestion',"difficulty":'Medium',
 "question":'Which of the following is NOT a function of the pancreas in digestion?',
 "options":{"A":'Secreting digestive enzymes into the small intestine', "B":'Secreting bicarbonate to neutralize stomach acid entering the duodenum', "C":'Storing and concentrating bile', "D":'Producing insulin and glucagon'},"answer":'C'},
{"id":64,"subject":'Biology',"topic":'Human Physiology - Digestion',"difficulty":'Hard',
 "question":'A person whose pancreas fails to secrete adequate lipase would most likely experience:',
 "options":{"A":'Complete inability to digest carbohydrates', "B":'No digestive symptoms at all', "C":'Poor digestion and absorption of dietary fats', "D":'Excess absorption of fats'},"answer":'C'},
{"id":65,"subject":'Biology',"topic":'Human Physiology - Circulation',"difficulty":'Easy',
 "question":'The heart valve located between the left atrium and left ventricle is the:',
 "options":{"A":'Tricuspid valve', "B":'Pulmonary valve', "C":'Mitral (bicuspid) valve', "D":'Aortic valve'},"answer":'C'},
{"id":66,"subject":'Biology',"topic":'Human Physiology - Circulation',"difficulty":'Medium',
 "question":'Which blood vessel carries deoxygenated blood, unlike most arteries?',
 "options":{"A":'Aorta', "B":'Pulmonary artery', "C":'Renal artery', "D":'Coronary artery'},"answer":'B'},
{"id":67,"subject":'Biology',"topic":'Human Physiology - Circulation',"difficulty":'Medium',
 "question":'Red blood cells lack a nucleus in mature form, which mainly allows them to:',
 "options":{"A":'Carry more hemoglobin and thus more oxygen due to extra internal space', "B":'Reproduce more quickly', "C":'Fight infections more effectively', "D":'Live indefinitely'},"answer":'A'},
{"id":68,"subject":'Biology',"topic":'Human Physiology - Circulation',"difficulty":'Hard',
 "question":'Atherosclerosis, the buildup of fatty plaques within arterial walls, primarily increases the risk of heart attack and stroke by:',
 "options":{"A":'Increasing the diameter of the artery', "B":'Narrowing arteries and potentially triggering clot formation, restricting or blocking blood flow', "C":"Directly weakening the heart's valves", "D":'Lowering blood pressure permanently'},"answer":'B'},
{"id":69,"subject":'Biology',"topic":'Human Physiology - Respiration',"difficulty":'Easy',
 "question":'The windpipe, which carries air from the throat toward the lungs, is called the:',
 "options":{"A":'Trachea', "B":'Bronchus', "C":'Larynx', "D":'Pharynx'},"answer":'A'},
{"id":70,"subject":'Biology',"topic":'Human Physiology - Respiration',"difficulty":'Medium',
 "question":'Surfactant, a substance produced by cells lining the alveoli, primarily functions to:',
 "options":{"A":'Increase surface tension, causing alveoli to collapse', "B":'Reduce surface tension within the alveoli, preventing their collapse', "C":'Filter incoming air', "D":'Warm incoming air'},"answer":'B'},
{"id":71,"subject":'Biology',"topic":'Human Physiology - Respiration',"difficulty":'Medium',
 "question":'The partial pressure gradient of oxygen between the alveoli and the pulmonary capillaries drives oxygen to move:',
 "options":{"A":'From the blood into the alveoli', "B":'In both directions equally', "C":'From the alveoli into the blood', "D":'Not at all, since active transport is required'},"answer":'C'},
{"id":72,"subject":'Biology',"topic":'Human Physiology - Excretion',"difficulty":'Easy',
 "question":'Which part of the nephron is primarily responsible for the initial filtration of blood plasma?',
 "options":{"A":'Loop of Henle', "B":'Collecting duct', "C":"Glomerulus and Bowman's capsule", "D":'Distal convoluted tubule'},"answer":'C'},
{"id":73,"subject":'Biology',"topic":'Human Physiology - Excretion',"difficulty":'Medium',
 "question":'The loop of Henle plays a key role in the kidney mainly by:',
 "options":{"A":'Filtering blood plasma initially', "B":"Producing urine's yellow color", "C":'Establishing a concentration gradient in the medulla that allows the kidney to produce concentrated urine', "D":'Storing urine before excretion'},"answer":'C'},
{"id":74,"subject":'Biology',"topic":'Human Physiology - Excretion',"difficulty":'Hard',
 "question":'A substance that is freely filtered at the glomerulus but neither reabsorbed nor secreted along the nephron would have a urine concentration relative to plasma that:',
 "options":{"A":'Is always identical to the plasma concentration', "B":'Reflects exactly how much water was reabsorbed from the filtrate', "C":'Is always zero', "D":'Cannot be determined by filtration alone'},"answer":'B'},
{"id":75,"subject":'Biology',"topic":'Human Physiology - Nervous & Endocrine',"difficulty":'Easy',
 "question":'The basic functional and structural unit of the nervous system is the:',
 "options":{"A":'Nephron', "B":'Neuron', "C":'Axon', "D":'Synapse'},"answer":'B'},
{"id":76,"subject":'Biology',"topic":'Human Physiology - Nervous & Endocrine',"difficulty":'Medium',
 "question":"The autonomic nervous system's sympathetic division is primarily responsible for:",
 "options":{"A":"Preparing the body for 'fight or flight' responses during stress", "B":"Promoting 'rest and digest' functions", "C":'Controlling voluntary skeletal muscle movement', "D":'Regulating only digestive secretions'},"answer":'A'},
{"id":77,"subject":'Biology',"topic":'Human Physiology - Nervous & Endocrine',"difficulty":'Medium',
 "question":'Which hormone, released by the pancreas, raises blood glucose levels by stimulating the breakdown of glycogen in the liver?',
 "options":{"A":'Glucagon', "B":'Insulin', "C":'Cortisol', "D":'Thyroxine'},"answer":'A'},
{"id":78,"subject":'Biology',"topic":'Human Physiology - Nervous & Endocrine',"difficulty":'Hard',
 "question":'The refractory period following an action potential mainly ensures that:',
 "options":{"A":'The neuron can immediately generate another action potential in the same location', "B":'Nerve impulses travel in one direction only, without backward propagation', "C":'The neuron permanently stops functioning', "D":'No neurotransmitter is ever released again'},"answer":'B'},
{"id":79,"subject":'Biology',"topic":'Human Physiology - Reproduction',"difficulty":'Easy',
 "question":'The site of fertilization in the human female reproductive system is normally the:',
 "options":{"A":'Uterus', "B":'Ovary', "C":'Cervix', "D":'Fallopian tube (oviduct)'},"answer":'D'},
{"id":80,"subject":'Biology',"topic":'Human Physiology - Reproduction',"difficulty":'Medium',
 "question":'FSH (follicle-stimulating hormone) in females primarily functions to:',
 "options":{"A":'Trigger ovulation directly', "B":'Maintain the uterine lining after implantation', "C":'Stimulate the growth and maturation of ovarian follicles', "D":'Stimulate milk production'},"answer":'C'},
{"id":81,"subject":'Biology',"topic":'Ecology',"difficulty":'Medium',
 "question":'A symbiotic relationship in which one organism benefits while the other is neither helped nor harmed is called:',
 "options":{"A":'Mutualism', "B":'Commensalism', "C":'Parasitism', "D":'Competition'},"answer":'B'},

# ============================================================
# CHEMISTRY (45 questions) - id 82-126
# ============================================================
{"id":82,"subject":'Chemistry',"topic":'Atomic Structure',"difficulty":'Easy',
 "question":'Protons and neutrons are collectively referred to as:',
 "options":{"A":'Electrons', "B":'Nucleons', "C":'Ions', "D":'Isotopes'},"answer":'B'},
{"id":83,"subject":'Chemistry',"topic":'Atomic Structure',"difficulty":'Medium',
 "question":'An atom of sodium-23 (atomic number 11) contains how many neutrons?',
 "options":{"A":'11', "B":'12', "C":'23', "D":'34'},"answer":'B'},
{"id":84,"subject":'Chemistry',"topic":'Atomic Structure',"difficulty":'Medium',
 "question":'The electron configuration of a neutral magnesium atom (Z = 12) is:',
 "options":{"A":'1s2 2s2 2p6 3s1', "B":'1s2 2s2 2p6 3s2', "C":'1s2 2s2 2p5', "D":'1s2 2s2 2p6 3s2 3p1'},"answer":'B'},
{"id":85,"subject":'Chemistry',"topic":'Atomic Structure',"difficulty":'Hard',
 "question":'An ion formed from a neutral atom with 15 protons that has gained 3 electrons carries a charge of:',
 "options":{"A":'-3', "B":'+3', "C":'-2', "D":'+2'},"answer":'A'},
{"id":86,"subject":'Chemistry',"topic":'Periodic Table',"difficulty":'Easy',
 "question":'Elements in Group 2 of the periodic table are known as:',
 "options":{"A":'Alkali metals', "B":'Halogens', "C":'Transition metals', "D":'Alkaline earth metals'},"answer":'D'},
{"id":87,"subject":'Chemistry',"topic":'Periodic Table',"difficulty":'Medium',
 "question":'Electronegativity generally increases:',
 "options":{"A":'Down a group, and from left to right across a period', "B":'Down a group only, with no periodic trend', "C":'Up a group and left to right, but only for metals', "D":'Across a period from left to right, and up a group'},"answer":'D'},
{"id":88,"subject":'Chemistry',"topic":'Periodic Table',"difficulty":'Medium',
 "question":'An element with electron configuration [Kr]5s1 would most likely:',
 "options":{"A":'Gain seven electrons to form a -7 ion', "B":'Lose one electron to form a +1 ion', "C":'Be chemically inert', "D":'Share electrons covalently only'},"answer":'B'},
{"id":89,"subject":'Chemistry',"topic":'Chemical Bonding',"difficulty":'Easy',
 "question":'A hydrogen bond is best described as:',
 "options":{"A":'A strong covalent bond within a single molecule', "B":'An ionic bond formed by electron transfer', "C":'A bond found only in metals', "D":'A relatively weak attraction between a hydrogen atom bonded to an electronegative atom and a nearby electronegative atom'},"answer":'D'},
{"id":90,"subject":'Chemistry',"topic":'Chemical Bonding',"difficulty":'Medium',
 "question":'According to VSEPR theory, a molecule such as BeCl2, with two bonding pairs and no lone pairs on the central atom, has a molecular shape described as:',
 "options":{"A":'Bent', "B":'Trigonal planar', "C":'Linear', "D":'Tetrahedral'},"answer":'C'},
{"id":91,"subject":'Chemistry',"topic":'Chemical Bonding',"difficulty":'Medium',
 "question":'Water (H2O) is a polar molecule mainly because:',
 "options":{"A":'Its linear shape causes the dipoles to cancel', "B":'Oxygen and hydrogen have identical electronegativities', "C":'It contains no covalent bonds', "D":'Its bent shape prevents the O-H bond dipoles from canceling'},"answer":'D'},
{"id":92,"subject":'Chemistry',"topic":'Chemical Bonding',"difficulty":'Hard',
 "question":'Metals are good conductors of electricity mainly because they contain:',
 "options":{"A":'Delocalized electrons that are free to move throughout the metallic lattice', "B":'Fixed, localized electrons that cannot move', "C":'No electrons available for conduction', "D":'Only covalent bonds'},"answer":'A'},
{"id":93,"subject":'Chemistry',"topic":'States of Matter',"difficulty":'Easy',
 "question":'The process by which a gas changes directly into a liquid is called:',
 "options":{"A":'Evaporation', "B":'Sublimation', "C":'Deposition', "D":'Condensation'},"answer":'D'},
{"id":94,"subject":'Chemistry',"topic":'States of Matter',"difficulty":'Medium',
 "question":"A gas occupies 8.0 L at 2.5 atm. What volume will it occupy at 5.0 atm, assuming constant temperature (Boyle's Law)?",
 "options":{"A":'16.0 L', "B":'20.0 L', "C":'2.0 L', "D":'4.0 L'},"answer":'D'},
{"id":95,"subject":'Chemistry',"topic":'States of Matter',"difficulty":'Hard',
 "question":"A fixed mass of gas occupies 3 L at 250 K at constant pressure. What volume will it occupy at 500 K (Charles's Law)?",
 "options":{"A":'1.5 L', "B":'3 L', "C":'750 L', "D":'6 L'},"answer":'D'},
{"id":96,"subject":'Chemistry',"topic":'Stoichiometry',"difficulty":'Easy',
 "question":'The molar mass of sodium hydroxide (NaOH) is approximately:',
 "options":{"A":'23 g/mol', "B":'17 g/mol', "C":'58 g/mol', "D":'40 g/mol'},"answer":'D'},
{"id":97,"subject":'Chemistry',"topic":'Stoichiometry',"difficulty":'Medium',
 "question":'How many moles are present in 11 g of CO2 (molar mass 44 g/mol)?',
 "options":{"A":'0.5 mol', "B":'4 mol', "C":'2.5 mol', "D":'0.25 mol'},"answer":'D'},
{"id":98,"subject":'Chemistry',"topic":'Stoichiometry',"difficulty":'Hard',
 "question":'A 100 mL solution contains 0.02 mole of H2SO4. What is the molarity of this solution?',
 "options":{"A":'0.2 M', "B":'0.02 M', "C":'2 M', "D":'0.002 M'},"answer":'A'},
{"id":99,"subject":'Chemistry',"topic":'Stoichiometry',"difficulty":'Medium',
 "question":'In the balanced equation 2H2 + O2 -> 2H2O, how many moles of water are formed from the complete reaction of 6 moles of H2 with excess O2?',
 "options":{"A":'6', "B":'3', "C":'12', "D":'2'},"answer":'A'},
{"id":100,"subject":'Chemistry',"topic":'Thermochemistry',"difficulty":'Easy',
 "question":"The heat energy released or absorbed by a reaction at constant pressure is called the reaction's:",
 "options":{"A":'Entropy change', "B":'Free energy change', "C":'Enthalpy change', "D":'Activation energy'},"answer":'C'},
{"id":101,"subject":'Chemistry',"topic":'Thermochemistry',"difficulty":'Medium',
 "question":"Hess's law states that the total enthalpy change for a reaction is:",
 "options":{"A":'The same regardless of the pathway taken, as long as initial and final states are identical', "B":'Dependent on the specific reaction pathway taken', "C":'Always positive', "D":'Impossible to calculate for multi-step reactions'},"answer":'A'},
{"id":102,"subject":'Chemistry',"topic":'Chemical Equilibrium',"difficulty":'Medium',
 "question":'For the equilibrium PCl5(g) <-> PCl3(g) + Cl2(g), increasing the volume of the container (decreasing pressure) will shift the equilibrium:',
 "options":{"A":'Toward the reactant (PCl5), the side with fewer moles of gas', "B":'Toward the products (PCl3 + Cl2), the side with more moles of gas', "C":'Not at all', "D":'Completely to the reactant side'},"answer":'B'},
{"id":103,"subject":'Chemistry',"topic":'Chemical Equilibrium',"difficulty":'Hard',
 "question":'If Keq for a reaction is much greater than 1, this indicates that at equilibrium:',
 "options":{"A":'The reaction strongly favors the reactants', "B":'The reaction has not yet started', "C":'The reaction strongly favors the products', "D":'The reaction is exactly balanced 1:1'},"answer":'C'},
{"id":104,"subject":'Chemistry',"topic":'Reaction Kinetics',"difficulty":'Easy',
 "question":'Increasing the concentration of reactants generally increases reaction rate mainly because it:',
 "options":{"A":'Decreases the frequency of collisions between particles', "B":'Lowers the activation energy required', "C":'Increases the frequency of collisions between reacting particles', "D":'Decreases the average kinetic energy'},"answer":'C'},
{"id":105,"subject":'Chemistry',"topic":'Reaction Kinetics',"difficulty":'Medium',
 "question":'A reaction is first order in reactant A and first order in reactant B (second order overall). If the concentration of A is doubled while B remains constant, the rate will:',
 "options":{"A":'Double', "B":'Quadruple', "C":'Remain unchanged', "D":'Halve'},"answer":'A'},
{"id":106,"subject":'Chemistry',"topic":'Electrochemistry',"difficulty":'Medium',
 "question":'In a standard galvanic cell, electrons flow through the external circuit from the:',
 "options":{"A":'Anode to the cathode', "B":'Cathode to the anode', "C":'Salt bridge to the cathode', "D":'Cathode to the salt bridge'},"answer":'A'},
{"id":107,"subject":'Chemistry',"topic":'Electrochemistry',"difficulty":'Hard',
 "question":'In the reaction Mg + 2HCl -> MgCl2 + H2, hydrogen ions (H+) are:',
 "options":{"A":'Oxidized', "B":'Unchanged in oxidation state', "C":'Reduced, gaining electrons to form H2 gas', "D":'Acting as a catalyst'},"answer":'C'},
{"id":108,"subject":'Chemistry',"topic":'Acids & Bases',"difficulty":'Easy',
 "question":'A strong acid is one that:',
 "options":{"A":'Partially ionizes in water', "B":'Completely ionizes in water, releasing all its available H+ ions', "C":'Does not ionize at all', "D":'Is always concentrated'},"answer":'B'},
{"id":109,"subject":'Chemistry',"topic":'Acids & Bases',"difficulty":'Medium',
 "question":'A solution has a pOH of 3. What is its pH (at 25°C)?',
 "options":{"A":'3', "B":'11', "C":'7', "D":'10'},"answer":'B'},
{"id":110,"subject":'Chemistry',"topic":'Acids & Bases',"difficulty":'Medium',
 "question":'The graph shows the pH change as NaOH is added to a weak acid solution. The relatively flat region of the curve before the steep jump near the equivalence point is best explained by:',
 "image":'images/q7_titration_buffer_region_graph.png',
 "options":{"A":'The solution having no buffering capacity', "B":'Complete neutralization having already occurred', "C":'The buffering region, where the weak acid and its conjugate base resist large pH changes', "D":'An error in the experiment'},"answer":'C'},
{"id":111,"subject":'Chemistry',"topic":'Acids & Bases',"difficulty":'Hard',
 "question":'The pH of a buffer solution can be estimated using the Henderson-Hasselbalch equation, which relates pH to:',
 "options":{"A":'Only the concentration of the weak acid', "B":'Temperature alone', "C":'The pKa of the weak acid and the ratio of conjugate base to weak acid concentrations', "D":'The strength of the solvent'},"answer":'C'},
{"id":112,"subject":'Chemistry',"topic":'Organic Chemistry',"difficulty":'Easy',
 "question":'A ketone functional group consists of a carbonyl group bonded to:',
 "options":{"A":'Two carbon atoms (within the carbon chain)', "B":'One hydrogen and one carbon', "C":'Two hydrogen atoms only', "D":'A nitrogen atom'},"answer":'A'},
{"id":113,"subject":'Chemistry',"topic":'Organic Chemistry',"difficulty":'Medium',
 "question":'Benzene and other aromatic compounds are characterized by:',
 "options":{"A":'A single double bond only', "B":'Complete absence of carbon-carbon bonds', "C":'A ring of alternating single and double bonds with delocalized pi electrons, giving unusual stability', "D":'A straight-chain structure with no ring'},"answer":'C'},
{"id":114,"subject":'Chemistry',"topic":'Organic Chemistry',"difficulty":'Medium',
 "question":'Amide functional groups, found in proteins as peptide bonds, are formed by the reaction between:',
 "options":{"A":'A carboxylic acid and an amine, releasing water', "B":'An alcohol and an aldehyde', "C":'Two alcohols', "D":'An ether and an ester'},"answer":'A'},
{"id":115,"subject":'Chemistry',"topic":'Organic Chemistry',"difficulty":'Hard',
 "question":"Markovnikov's rule predicts that when HX adds across an unsymmetrical alkene, the hydrogen atom preferentially bonds to:",
 "options":{"A":'The carbon bearing fewer hydrogen atoms', "B":'Neither carbon; it bonds to the halogen instead', "C":'Whichever carbon is closer to a functional group', "D":'The carbon already bearing more hydrogen atoms'},"answer":'D'},
{"id":116,"subject":'Chemistry',"topic":'Organic Chemistry',"difficulty":'Medium',
 "question":'Condensation polymerization, unlike addition polymerization, typically involves:',
 "options":{"A":'The release of a small molecule, such as water, at each linkage between monomers', "B":'No loss of any atoms during polymer formation', "C":'Only monomers containing a double bond', "D":'A process that cannot form long polymer chains'},"answer":'A'},
{"id":117,"subject":'Chemistry',"topic":'Organic Chemistry',"difficulty":'Easy',
 "question":'Which of the following pairs is best described as functional isomers (constitutional isomers with different functional groups)?',
 "options":{"A":'Ethanol and dimethyl ether, both C2H6O', "B":'Two enantiomers of the same molecule', "C":'Cis and trans isomers of a compound', "D":'Two identical molecules'},"answer":'A'},
{"id":118,"subject":'Chemistry',"topic":'Inorganic Chemistry',"difficulty":'Medium',
 "question":'Transition metals typically exhibit multiple oxidation states mainly because:',
 "options":{"A":'They have no d electrons', "B":'They only ever form +1 ions', "C":'Electrons from both the outer s subshell and the underlying d subshell can be involved in bonding', "D":'They lack valence electrons entirely'},"answer":'C'},
{"id":119,"subject":'Chemistry',"topic":'Inorganic Chemistry',"difficulty":'Medium',
 "question":'Which of the following best explains why sodium (Group 1) is much more reactive than magnesium (Group 2)?',
 "options":{"A":'Sodium has a smaller atomic radius than magnesium', "B":"Sodium needs to lose only one electron to achieve a stable configuration, requiring less energy than magnesium's two-electron loss", "C":'Magnesium has more valence electrons available for bonding', "D":'Sodium is a nonmetal'},"answer":'B'},
{"id":120,"subject":'Chemistry',"topic":'Inorganic Chemistry',"difficulty":'Hard',
 "question":"In the reaction 2Al + 3CuSO4 -> Al2(SO4)3 + 3Cu, aluminum's oxidation state changes from:",
 "options":{"A":'0 to +2', "B":'+3 to 0', "C":'0 to +3 (oxidation)', "D":'No change occurs'},"answer":'C'},
{"id":121,"subject":'Chemistry',"topic":'Physical Chemistry',"difficulty":'Medium',
 "question":'Which colligative property depends only on the number of solute particles present, not their identity?',
 "options":{"A":'Boiling point elevation', "B":'Color of the solution', "C":'Density', "D":'Viscosity'},"answer":'A'},
{"id":122,"subject":'Chemistry',"topic":'Physical Chemistry',"difficulty":'Hard',
 "question":'10 mL of 1.0 M HCl is required to exactly neutralize 25 mL of Ca(OH)2 solution (2HCl + Ca(OH)2 -> CaCl2 + 2H2O). What is the molarity of the Ca(OH)2 solution?',
 "options":{"A":'0.1 M', "B":'0.4 M', "C":'0.05 M', "D":'0.2 M'},"answer":'D'},
{"id":123,"subject":'Chemistry',"topic":'Environmental Chemistry',"difficulty":'Easy',
 "question":'Which of the following gases is most closely associated with the depletion of the ozone layer?',
 "options":{"A":'Carbon dioxide', "B":'Nitrogen', "C":'Water vapor', "D":'Chlorofluorocarbons (CFCs)'},"answer":'D'},
{"id":124,"subject":'Chemistry',"topic":'Environmental Chemistry',"difficulty":'Medium',
 "question":'The pH of unpolluted rainwater is typically slightly acidic (around 5.6) mainly due to:',
 "options":{"A":'Sulfuric acid from industrial pollution', "B":'Nitric acid from vehicle emissions', "C":'Dissolved ozone', "D":'Dissolved atmospheric carbon dioxide forming weak carbonic acid'},"answer":'D'},
{"id":125,"subject":'Chemistry',"topic":'Chemical Bonding',"difficulty":'Easy',
 "question":'In a polar covalent bond, shared electrons are:',
 "options":{"A":'Distributed equally between the two atoms', "B":'Completely transferred to one atom', "C":'Not shared at all', "D":'Distributed unequally, spending more time near the more electronegative atom'},"answer":'D'},
{"id":126,"subject":'Chemistry',"topic":'Atomic Structure',"difficulty":'Easy',
 "question":'The atomic number of an element is defined as the number of:',
 "options":{"A":'Neutrons in the nucleus', "B":'Total nucleons', "C":'Protons in the nucleus', "D":'Electrons in the outermost shell only'},"answer":'C'},

# ============================================================
# PHYSICS (36 questions) - id 127-162
# ============================================================
{"id":127,"subject":'Physics',"topic":'Kinematics',"difficulty":'Easy',
 "question":'A train covers 360 km in 4 hours at constant velocity. What is its speed?',
 "options":{"A":'1440 km/h', "B":'40 km/h', "C":'9 km/h', "D":'90 km/h'},"answer":'D'},
{"id":128,"subject":'Physics',"topic":'Kinematics',"difficulty":'Medium',
 "question":'A car decelerates uniformly from 24 m/s to 0 m/s over 6 seconds. What is the magnitude of its deceleration?',
 "options":{"A":'4 m/s^2', "B":'144 m/s^2', "C":'6 m/s^2', "D":'0.25 m/s^2'},"answer":'A'},
{"id":129,"subject":'Physics',"topic":'Kinematics',"difficulty":'Hard',
 "question":'A ball is thrown horizontally from a height of 20 m with an initial horizontal speed of 15 m/s (g = 10 m/s^2, ignoring air resistance). How long does it take to hit the ground?',
 "options":{"A":'2 s', "B":'4 s', "C":'1.5 s', "D":'20 s'},"answer":'A'},
{"id":130,"subject":'Physics',"topic":'Dynamics',"difficulty":'Easy',
 "question":"Newton's second law of motion states that the acceleration of an object is:",
 "options":{"A":'Inversely proportional to net force and directly proportional to mass', "B":'Independent of both force and mass', "C":'Always equal to zero for any moving object', "D":'Directly proportional to net force and inversely proportional to mass'},"answer":'D'},
{"id":131,"subject":'Physics',"topic":'Dynamics',"difficulty":'Medium',
 "question":'An 8 kg object accelerates at 1.5 m/s^2 due to an applied net force. What is the magnitude of this force?',
 "options":{"A":'5.3 N', "B":'12 N', "C":'9.5 N', "D":'6.5 N'},"answer":'B'},
{"id":132,"subject":'Physics',"topic":'Dynamics',"difficulty":'Medium',
 "question":'A rocket accelerates upward by expelling exhaust gases downward; this is best explained by:',
 "options":{"A":"Newton's first law", "B":'The law of conservation of mass alone', "C":'Air resistance alone', "D":"Newton's third law, as the rocket exerts a force on the gases and the gases exert an equal, opposite force on the rocket"},"answer":'D'},
{"id":133,"subject":'Physics',"topic":'Dynamics',"difficulty":'Hard',
 "question":"A 10 kg block is pushed horizontally with a 50 N force across a surface with a coefficient of kinetic friction of 0.2 (g = 10 m/s^2). What is the block's acceleration?",
 "options":{"A":'5 m/s^2', "B":'3 m/s^2', "C":'2 m/s^2', "D":'1 m/s^2'},"answer":'B'},
{"id":134,"subject":'Physics',"topic":'Work, Energy & Power',"difficulty":'Easy',
 "question":'According to the work-energy theorem, the net work done on an object equals its:',
 "options":{"A":'Change in momentum', "B":'Change in potential energy only', "C":'Total mechanical energy', "D":'Change in kinetic energy'},"answer":'D'},
{"id":135,"subject":'Physics',"topic":'Work, Energy & Power',"difficulty":'Medium',
 "question":'An 8 kg object is raised to a height of 2.5 m (g = 10 m/s^2). What is its gravitational potential energy at that height?',
 "options":{"A":'20 J', "B":'100 J', "C":'25 J', "D":'200 J'},"answer":'D'},
{"id":136,"subject":'Physics',"topic":'Work, Energy & Power',"difficulty":'Medium',
 "question":'A 6 kg object moving at 4 m/s has a kinetic energy of:',
 "options":{"A":'24 J', "B":'96 J', "C":'12 J', "D":'48 J'},"answer":'D'},
{"id":137,"subject":'Physics',"topic":'Work, Energy & Power',"difficulty":'Hard',
 "question":'A pump lifts 1000 kg of water to a height of 5 m in 25 seconds (g = 10 m/s^2). What is the power output of the pump?',
 "options":{"A":'200 W', "B":'5000 W', "C":'50000 W', "D":'2000 W'},"answer":'D'},
{"id":138,"subject":'Physics',"topic":'Circular Motion & Gravitation',"difficulty":'Easy',
 "question":'The formula for centripetal force acting on an object moving in a circle is:',
 "options":{"A":'F = ma', "B":'F = mgh', "C":'F = mg', "D":'F = mv^2/r'},"answer":'D'},
{"id":139,"subject":'Physics',"topic":'Circular Motion & Gravitation',"difficulty":'Medium',
 "question":'If both masses in a gravitational interaction are doubled while the distance remains the same, the gravitational force between them becomes:',
 "options":{"A":'Four times as large', "B":'Twice as large', "C":'Half as large', "D":'Unchanged'},"answer":'A'},
{"id":140,"subject":'Physics',"topic":'Circular Motion & Gravitation',"difficulty":'Hard',
 "question":"As a satellite's orbital radius around Earth increases, its orbital speed:",
 "options":{"A":'Increases', "B":'Remains exactly the same', "C":'Becomes infinite', "D":'Decreases, since gravitational pull weakens with distance'},"answer":'D'},
{"id":141,"subject":'Physics',"topic":'Fluid Mechanics',"difficulty":'Easy',
 "question":'Pressure is defined as force applied per unit:',
 "options":{"A":'Volume', "B":'Mass', "C":'Area', "D":'Length'},"answer":'C'},
{"id":142,"subject":'Physics',"topic":'Fluid Mechanics',"difficulty":'Medium',
 "question":'A helium balloon rises in air mainly because:',
 "options":{"A":'Helium is negatively charged', "B":'Helium has no mass', "C":'Air has no buoyant force', "D":"Helium gas is less dense than the surrounding air, so the buoyant force exceeds the balloon's weight"},"answer":'D'},
{"id":143,"subject":'Physics',"topic":'Fluid Mechanics',"difficulty":'Hard',
 "question":"An airplane wing generates lift partly due to Bernoulli's principle because air flows faster over the curved upper surface than the flatter lower surface, resulting in:",
 "options":{"A":'Lower pressure above the wing than below it, creating a net upward force', "B":'Higher pressure above the wing than below it', "C":'Equal pressure above and below the wing', "D":'No pressure difference at all'},"answer":'A'},
{"id":144,"subject":'Physics',"topic":'Oscillations & Waves',"difficulty":'Easy',
 "question":'The time taken to complete one full oscillation or wave cycle is called the:',
 "options":{"A":'Period', "B":'Frequency', "C":'Amplitude', "D":'Wavelength'},"answer":'A'},
{"id":145,"subject":'Physics',"topic":'Oscillations & Waves',"difficulty":'Medium',
 "question":"Doubling the amplitude of a sound wave, while keeping frequency constant, primarily affects the sound's:",
 "options":{"A":'Pitch', "B":'Loudness (intensity)', "C":'Wavelength only', "D":'Speed of travel'},"answer":'B'},
{"id":146,"subject":'Physics',"topic":'Oscillations & Waves',"difficulty":'Medium',
 "question":'A wave has a wavelength of 2 m and travels at 340 m/s. What is its frequency?',
 "options":{"A":'680 Hz', "B":'342 Hz', "C":'170 Hz', "D":'338 Hz'},"answer":'C'},
{"id":147,"subject":'Physics',"topic":'Oscillations & Waves',"difficulty":'Hard',
 "question":'The Doppler effect describes the apparent change in frequency of a wave observed when:',
 "options":{"A":'The source and observer are both stationary', "B":'There is relative motion between the wave source and the observer', "C":'The wave has zero amplitude', "D":'The medium has no density'},"answer":'B'},
{"id":148,"subject":'Physics',"topic":'Thermodynamics',"difficulty":'Easy',
 "question":'Heat naturally flows from a region of:',
 "options":{"A":'Lower temperature to higher temperature spontaneously', "B":'Equal temperature to unequal temperature', "C":'Higher temperature to lower temperature', "D":'High pressure to low pressure only'},"answer":'C'},
{"id":149,"subject":'Physics',"topic":'Thermodynamics',"difficulty":'Medium',
 "question":'An isothermal process is one in which:',
 "options":{"A":'Temperature remains constant throughout the process', "B":'No heat is exchanged with the surroundings', "C":'Volume remains constant throughout', "D":'Pressure remains constant throughout'},"answer":'A'},
{"id":150,"subject":'Physics',"topic":'Thermodynamics',"difficulty":'Hard',
 "question":'A gas absorbs 500 J of heat while doing 200 J of work on its surroundings. What is the change in internal energy of the gas?',
 "options":{"A":'700 J', "B":'-300 J', "C":'-700 J', "D":'300 J'},"answer":'D'},
{"id":151,"subject":'Physics',"topic":'Electrostatics',"difficulty":'Easy',
 "question":'Like electric charges when brought close together will:',
 "options":{"A":'Attract each other', "B":'Have no interaction', "C":'Cancel each other out completely', "D":'Repel each other'},"answer":'D'},
{"id":152,"subject":'Physics',"topic":'Electrostatics',"difficulty":'Medium',
 "question":'The electric field around a point charge is defined as the force experienced per unit:',
 "options":{"A":'Positive test charge placed at that point', "B":'Mass', "C":'Distance', "D":'Area'},"answer":'A'},
{"id":153,"subject":'Physics',"topic":'Current Electricity',"difficulty":'Easy',
 "question":'Which of the following materials is generally the best electrical conductor?',
 "options":{"A":'Rubber', "B":'Glass', "C":'Wood', "D":'Copper'},"answer":'D'},
{"id":154,"subject":'Physics',"topic":'Current Electricity',"difficulty":'Medium',
 "question":'In the circuit shown, R1 (6 ohm) and R2 (3 ohm) are connected in series, and this series combination is connected in parallel with R3 (9 ohm). What is the total resistance of the circuit?',
 "image":'images/q7_circuit_diagram_r1r2r3.png',
 "options":{"A":'4.5 ohm', "B":'18 ohm', "C":'3 ohm', "D":'9 ohm'},"answer":'A'},
{"id":155,"subject":'Physics',"topic":'Current Electricity',"difficulty":'Hard',
 "question":'Two resistors, 4 ohm and 12 ohm, are connected in parallel. What is their equivalent resistance?',
 "options":{"A":'16 ohm', "B":'8 ohm', "C":'3 ohm', "D":'48 ohm'},"answer":'C'},
{"id":156,"subject":'Physics',"topic":'Current Electricity',"difficulty":'Medium',
 "question":'A device has a resistance of 50 ohm and operates at 200 V. What current does it draw?',
 "options":{"A":'0.25 A', "B":'10000 A', "C":'250 A', "D":'4 A'},"answer":'D'},
{"id":157,"subject":'Physics',"topic":'Electromagnetism',"difficulty":'Medium',
 "question":'An electric generator converts:',
 "options":{"A":'Electrical energy into mechanical energy', "B":'Mechanical energy into electrical energy, using electromagnetic induction', "C":'Chemical energy directly into light', "D":'Heat energy into sound'},"answer":'B'},
{"id":158,"subject":'Physics',"topic":'Electromagnetism',"difficulty":'Hard',
 "question":"According to Lenz's law, the direction of an induced current is such that it:",
 "options":{"A":'Opposes the change in magnetic flux that caused it', "B":'Reinforces the change in magnetic flux that caused it', "C":'Has no relationship to the change in flux', "D":'Always flows clockwise regardless of circumstances'},"answer":'A'},
{"id":159,"subject":'Physics',"topic":'Modern Physics',"difficulty":'Easy',
 "question":'Radioactive decay in which the atomic number and mass number of a nucleus remain unchanged, but the nucleus loses excess energy, is called:',
 "options":{"A":'Alpha decay', "B":'Gamma decay', "C":'Beta decay', "D":'Fission'},"answer":'B'},
{"id":160,"subject":'Physics',"topic":'Modern Physics',"difficulty":'Medium',
 "question":'Nuclear fission involves:',
 "options":{"A":'The fusion of two light nuclei into a heavier one', "B":'The emission of a single electron from the nucleus', "C":'No change to the nucleus at all', "D":'The splitting of a heavy nucleus into two lighter nuclei, releasing energy'},"answer":'D'},
{"id":161,"subject":'Physics',"topic":'Modern Physics',"difficulty":'Hard',
 "question":'A radioactive sample decays such that only 1/8 of the original amount remains after 15 hours. What is the half-life of this substance?',
 "options":{"A":'5 hours', "B":'3 hours', "C":'7.5 hours', "D":'15 hours'},"answer":'A'},
{"id":162,"subject":'Physics',"topic":'Optics',"difficulty":'Medium',
 "question":'The ray diagram shows an object placed beyond the center of curvature (C) of a concave mirror. Based on the diagram, the image formed between F and C is:',
 "image":'images/q7_concave_mirror_diagram_beyond_c.png',
 "options":{"A":'Virtual, upright, and magnified', "B":'Real, inverted, and diminished', "C":'Real, upright, and magnified', "D":'Virtual, inverted, and diminished'},"answer":'B'},

# ============================================================
# ENGLISH (9 questions) - id 163-171
# ============================================================
{"id":163,"subject":'English',"topic":'Synonyms',"difficulty":'Easy',
 "question":"Choose the word most nearly similar in meaning to 'AUDACIOUS':",
 "options":{"A":'Timid', "B":'Bold', "C":'Cautious', "D":'Modest'},"answer":'B'},
{"id":164,"subject":'English',"topic":'Antonyms',"difficulty":'Easy',
 "question":"Choose the word most nearly opposite in meaning to 'CONCISE':",
 "options":{"A":'Verbose', "B":'Brief', "C":'Succinct', "D":'Clear'},"answer":'A'},
{"id":165,"subject":'English',"topic":'Grammar',"difficulty":'Easy',
 "question":'Choose the grammatically correct sentence:',
 "options":{"A":"He don't know the answer.", "B":"He doesn't know the answer.", "C":'He not knows the answer.', "D":"He didn't knew the answer."},"answer":'B'},
{"id":166,"subject":'English',"topic":'Grammar',"difficulty":'Medium',
 "question":'Choose the correct sentence:',
 "options":{"A":'I have been living here since five years.', "B":'I have been living here for five years.', "C":'I am living here since five years.', "D":'I live here for five years ago.'},"answer":'B'},
{"id":167,"subject":'English',"topic":'Sentence Correction',"difficulty":'Medium',
 "question":'Identify the sentence that follows correct subject-verb agreement:',
 "options":{"A":'Either of the two answers are correct.', "B":'Either of the two answer are correct.', "C":'Either the two answers is correct.', "D":'Either of the two answers is correct.'},"answer":'D'},
{"id":168,"subject":'English',"topic":'Vocabulary',"difficulty":'Medium',
 "question":"Choose the word that best completes the sentence: 'The lengthy negotiations finally reached an ______ that satisfied both parties.'",
 "options":{"A":'Impasse', "B":'Accord', "C":'Dispute', "D":'Ultimatum'},"answer":'B'},
{"id":169,"subject":'English',"topic":'Idioms',"difficulty":'Medium',
 "question":"Choose the meaning closest to the idiom 'to burn the midnight oil':",
 "options":{"A":'To work or study late into the night', "B":'To waste time carelessly', "C":'To start a fire accidentally', "D":'To finish a task early'},"answer":'A'},
{"id":170,"subject":'English',"topic":'Sentence Correction',"difficulty":'Hard',
 "question":"Choose the option that best corrects the sentence: 'Each student have submitted their assignment on time.'",
 "options":{"A":'Each student has submitted their assignments on time.', "B":'Each student has submitted his or her assignment on time.', "C":'Each student have submitted his assignment on time.', "D":'Each students has submitted their assignment on time.'},"answer":'B'},
{"id":171,"subject":'English',"topic":'Prepositions',"difficulty":'Hard',
 "question":"Choose the correct preposition to complete the sentence: 'The company has decided to invest heavily ______ renewable energy.'",
 "options":{"A":'in', "B":'on', "C":'at', "D":'with'},"answer":'A'},

# ============================================================
# LOGICAL REASONING (9 questions) - id 172-180
# ============================================================
{"id":172,"subject":'Logical Reasoning',"topic":'Number Series',"difficulty":'Easy',
 "question":'Find the next number in the series: 2, 6, 18, 54, ?',
 "options":{"A":'162', "B":'108', "C":'216', "D":'72'},"answer":'A'},
{"id":173,"subject":'Logical Reasoning',"topic":'Number Series',"difficulty":'Easy',
 "question":'Find the missing number: 50, 44, 38, 32, ?',
 "options":{"A":'28', "B":'24', "C":'26', "D":'30'},"answer":'C'},
{"id":174,"subject":'Logical Reasoning',"topic":'Analogies',"difficulty":'Easy',
 "question":'Thermometer is to Temperature as Speedometer is to:',
 "options":{"A":'Speed', "B":'Distance', "C":'Time', "D":'Direction'},"answer":'A'},
{"id":175,"subject":'Logical Reasoning',"topic":'Analogies',"difficulty":'Medium',
 "question":'Puppy is to Dog as Kitten is to:',
 "options":{"A":'Cat', "B":'Cub', "C":'Foal', "D":'Lamb'},"answer":'A'},
{"id":176,"subject":'Logical Reasoning',"topic":'Blood Relations',"difficulty":'Medium',
 "question":"Bilal said, 'This girl is the wife of my father's only son.' If Bilal has no brothers, how is the girl related to Bilal?",
 "options":{"A":'Sister', "B":'Mother', "C":'Daughter', "D":'Wife'},"answer":'D'},
{"id":177,"subject":'Logical Reasoning',"topic":'Coding-Decoding',"difficulty":'Medium',
 "question":'If in a certain code, MOUSE is written as NPVTF, how is HORSE written in the same code?',
 "options":{"A":'ISPTF', "B":'IPTSF', "C":'IPSTF', "D":'JPSTF'},"answer":'C'},
{"id":178,"subject":'Logical Reasoning',"topic":'Syllogism',"difficulty":'Hard',
 "question":'All squares are quadrilaterals. Some quadrilaterals are not rectangles. Which conclusion logically follows?',
 "options":{"A":'No squares are rectangles', "B":'Some squares are not rectangles', "C":'All quadrilaterals are squares', "D":'None of the given conclusions logically follows'},"answer":'D'},
{"id":179,"subject":'Logical Reasoning',"topic":'Pattern Recognition',"difficulty":'Hard',
 "question":'Find the next term in the series: 1, 4, 9, 16, 25, ?',
 "options":{"A":'30', "B":'32', "C":'36', "D":'49'},"answer":'C'},
{"id":180,"subject":'Logical Reasoning',"topic":'Direction Sense',"difficulty":'Medium',
 "question":'A woman walks 9 km west, then turns left and walks 12 km. How far is she from her starting point?',
 "options":{"A":'15 km', "B":'21 km', "C":'3 km', "D":'18 km'},"answer":'A'},

]


# ------------------------------------------------------------
# Sanity-check / summary utility
# ------------------------------------------------------------
def summarize(questions):
    from collections import Counter
    subj = Counter(q["subject"] for q in questions)
    diff = Counter(q["difficulty"] for q in questions)
    ans = Counter(q["answer"] for q in questions)
    ids = [q["id"] for q in questions]
    dup_ids = [i for i in set(ids) if ids.count(i) > 1]
    dup_q = [q["question"] for q in questions]
    dup_questions = [t for t in set(dup_q) if dup_q.count(t) > 1]
    images = [q for q in questions if "image" in q]

    print(f"Total questions: {len(questions)}")
    print("\nBy subject:")
    for s, c in subj.items():
        print(f"  {s}: {c}")
    print("\nBy difficulty:")
    for d, c in diff.items():
        print(f"  {d}: {c}")
    print("\nBy correct-answer letter (should be roughly balanced):")
    for L in ["A", "B", "C", "D"]:
        print(f"  {L}: {ans[L]}")
    print(f"\nDuplicate IDs: {dup_ids if dup_ids else 'None'}")
    print(f"Duplicate question text: {dup_questions if dup_questions else 'None'}")
    print(f"\nImage-based questions ({len(images)}):")
    for q in images:
        print(f"  Q{q['id']} [{q['subject']}] -> {q['image']}")

    for q in questions:
        assert set(q["options"].keys()) == {"A", "B", "C", "D"}, f"Q{q['id']} missing an option"
        assert q["answer"] in q["options"], f"Q{q['id']} answer key invalid"
    print("\nAll questions have exactly 4 options (A-D) and a valid answer key. OK.")


def print_answer_key(questions):
    print("\nANSWER KEY")
    print("-" * 40)
    for q in questions:
        print(f"{q['id']:>3}. {q['answer']}", end="   ")
        if q["id"] % 10 == 0:
            print()
    print()


if __name__ == "__main__":
    summarize(QUESTIONS)
    print_answer_key(QUESTIONS)