"""
MDCAT Mock Test 12
==================
Full-length mock test: 180 MCQs
Weightage: Biology 81 | Chemistry 45 | Physics 36 | English 9 | Logical Reasoning 9
Difficulty mix (approx): 30% Easy / 50% Medium / 20% Hard, distributed throughout.

Includes 5 image/diagram-based questions (2 Biology, 1 Chemistry, 2 Physics).
Each such question has an "image" key giving a relative path to a PNG diagram
that must be viewed alongside the question (images/ subfolder, shipped alongside
this file). Diagrams: a labeled cell nucleus, a labeled cross-section of the
heart showing its four valves, a solid-substance heating curve, a
parallel-then-series resistor circuit, and a concave-mirror ray diagram
(object between the pole and F).

Each question is a dict:
    id, subject, topic, difficulty, question, [image], options (A-D), answer (correct letter)

Run this file directly to print a summary / sanity-check the paper.
"""

QUESTIONS = [
# ============================================================
# BIOLOGY (81 questions) - id 1-81
# ============================================================
{"id":1,"subject":'Biology',"topic":'Biomolecules',"difficulty":'Easy',
 "question":'Which of the following is a lipid rather than a carbohydrate or protein?',
 "options":{"A":'Cellulose', "B":'Collagen', "C":'Glycogen', "D":'Cholesterol'},"answer":'D'},
{"id":2,"subject":'Biology',"topic":'Biomolecules',"difficulty":'Easy',
 "question":'The bond that links a phosphate group to a sugar in a nucleotide chain is called a:',
 "options":{"A":'Peptide bond', "B":'Glycosidic bond', "C":'Hydrogen bond', "D":'Phosphodiester bond'},"answer":'D'},
{"id":3,"subject":'Biology',"topic":'Biomolecules',"difficulty":'Medium',
 "question":'Which of the following best describes a globular protein such as hemoglobin?',
 "options":{"A":'Compact, roughly spherical, and generally soluble in water', "B":'Long, fibrous, and insoluble in water', "C":'Composed only of a primary structure with no further folding', "D":'Unable to fold into a three-dimensional shape'},"answer":'A'},
{"id":4,"subject":'Biology',"topic":'Biomolecules',"difficulty":'Medium',
 "question":'Enzymatic hydrolysis of a triglyceride yields glycerol and:',
 "options":{"A":'Amino acids', "B":'Glucose molecules', "C":'Nucleotides', "D":'Three fatty acid molecules'},"answer":'D'},
{"id":5,"subject":'Biology',"topic":'Biomolecules',"difficulty":'Hard',
 "question":'The double bonds present in unsaturated fatty acids typically occur in which configuration in most naturally occurring fats, causing a kink in the hydrocarbon chain?',
 "options":{"A":'Cis configuration', "B":'Trans configuration', "C":'Both configurations are equally common in nature', "D":'Neither configuration is possible in fatty acids'},"answer":'A'},
{"id":6,"subject":'Biology',"topic":'Enzymes',"difficulty":'Easy',
 "question":'The molecule an enzyme converts into product(s) is known as the:',
 "options":{"A":'Substrate', "B":'Cofactor', "C":'Coenzyme', "D":'Catalyst'},"answer":'A'},
{"id":7,"subject":'Biology',"topic":'Enzymes',"difficulty":'Medium',
 "question":"An enzyme's rate of reaction generally increases with rising temperature up to a certain point, after which it:",
 "options":{"A":'Continues increasing indefinitely', "B":'Remains exactly constant regardless of temperature', "C":'Becomes unaffected by any further temperature change', "D":"Sharply decreases due to denaturation of the enzyme's structure"},"answer":'D'},
{"id":8,"subject":'Biology',"topic":'Enzymes',"difficulty":'Medium',
 "question":'A metal ion, such as Zn2+ or Mg2+, required by certain enzymes for proper function is called a(n):',
 "options":{"A":'Inorganic cofactor', "B":'Coenzyme', "C":'Apoenzyme', "D":'Substrate'},"answer":'A'},
{"id":9,"subject":'Biology',"topic":'Enzymes',"difficulty":'Hard',
 "question":'In an enzyme reaction following Michaelis-Menten kinetics, at substrate concentrations far below Km, the reaction rate is approximately:',
 "options":{"A":'Directly proportional to substrate concentration (first-order behavior)', "B":'Independent of substrate concentration', "C":'Always equal to Vmax', "D":'Zero, regardless of substrate present'},"answer":'A'},
{"id":10,"subject":'Biology',"topic":'Cell Biology',"difficulty":'Easy',
 "question":'The structure that controls which substances enter and exit an animal cell is the:',
 "options":{"A":'Cell wall', "B":'Plasma membrane', "C":'Nucleolus', "D":'Cytoskeleton'},"answer":'B'},
{"id":11,"subject":'Biology',"topic":'Cell Biology',"difficulty":'Easy',
 "question":'Which organelle contains digestive enzymes used to break down waste materials and worn-out cell parts?',
 "options":{"A":'Lysosome', "B":'Peroxisome', "C":'Ribosome', "D":'Golgi apparatus'},"answer":'A'},
{"id":12,"subject":'Biology',"topic":'Cell Biology',"difficulty":'Medium',
 "question":'The diagram shows a cell nucleus with four structures labeled 1-4. Which labeled structure is responsible for producing ribosomal subunits?',
 "image":'images/q_nucleus_diagram.png',
 "options":{"A":'Structure 1 (nuclear envelope)', "B":'Structure 3 (nuclear pore)', "C":'Structure 4 (chromatin)', "D":'Structure 2 (nucleolus)'},"answer":'D'},
{"id":13,"subject":'Biology',"topic":'Cell Biology',"difficulty":'Medium',
 "question":'Which structure provides shape, internal support, and enables movement of organelles within a eukaryotic cell?',
 "options":{"A":'Cell wall', "B":'Nuclear envelope', "C":'Cytoskeleton', "D":'Cristae'},"answer":'C'},
{"id":14,"subject":'Biology',"topic":'Cell Biology',"difficulty":'Medium',
 "question":'Peroxisomes are important in breaking down fatty acids and detoxifying harmful substances mainly using:',
 "options":{"A":'Anaerobic fermentation', "B":'Oxidative reactions that produce and then break down hydrogen peroxide', "C":'DNA repair enzymes', "D":'Photosynthetic pigments'},"answer":'B'},
{"id":15,"subject":'Biology',"topic":'Cell Biology',"difficulty":'Medium',
 "question":'In a eukaryotic cell, most cellular ATP is produced through aerobic respiration primarily within the:',
 "options":{"A":'Nucleus', "B":'Ribosome', "C":'Golgi apparatus', "D":'Mitochondrion'},"answer":'D'},
{"id":16,"subject":'Biology',"topic":'Cell Biology',"difficulty":'Hard',
 "question":'A cell exposed to a toxin that disrupts microtubule assembly would most likely have difficulty with:',
 "options":{"A":'DNA base pairing', "B":'Glycolysis', "C":'Intracellular transport and organization of the mitotic spindle', "D":'mRNA splicing'},"answer":'C'},
{"id":17,"subject":'Biology',"topic":'Cell Membrane & Transport',"difficulty":'Easy',
 "question":'Movement of a substance across a membrane from an area of high concentration to low concentration, without energy input, is called:',
 "options":{"A":'Active transport', "B":'Phagocytosis', "C":'Exocytosis', "D":'Diffusion'},"answer":'D'},
{"id":18,"subject":'Biology',"topic":'Cell Membrane & Transport',"difficulty":'Medium',
 "question":'A cell placed in distilled water (essentially pure water) would experience:',
 "options":{"A":'No net water movement', "B":'A net outward movement of water', "C":'Immediate cell death, with no other observable effect', "D":'A net inward movement of water, since the surrounding solution is hypotonic to the cell'},"answer":'D'},
{"id":19,"subject":'Biology',"topic":'Cell Membrane & Transport',"difficulty":'Medium',
 "question":'Phagocytosis is a specific type of endocytosis involving the engulfment of:',
 "options":{"A":'Large particles, such as bacteria or cellular debris', "B":'Dissolved ions only', "C":'Only gases', "D":'Water molecules exclusively'},"answer":'A'},
{"id":20,"subject":'Biology',"topic":'Cell Membrane & Transport',"difficulty":'Hard',
 "question":'The steepness of a concentration gradient across a membrane primarily affects:',
 "options":{"A":'The rate of diffusion, with steeper gradients generally producing faster net movement', "B":'Only the direction of diffusion', "C":'Nothing related to diffusion', "D":'Only active transport rates, not diffusion at all'},"answer":'A'},
{"id":21,"subject":'Biology',"topic":'Cell Membrane & Transport',"difficulty":'Easy',
 "question":'Carrier proteins involved in facilitated diffusion differ from channel proteins mainly in that carrier proteins:',
 "options":{"A":'Bind the specific substance and undergo a conformational change to move it across the membrane', "B":'Form open pores that substances pass through freely', "C":'Never interact with any substrate', "D":'Always require ATP to function'},"answer":'A'},
{"id":22,"subject":'Biology',"topic":'Cell Cycle & Division',"difficulty":'Easy',
 "question":'DNA is duplicated during which stage of the cell cycle?',
 "options":{"A":'G1 phase', "B":'G2 phase', "C":'S phase', "D":'M phase'},"answer":'C'},
{"id":23,"subject":'Biology',"topic":'Cell Cycle & Division',"difficulty":'Easy',
 "question":'The stage of mitosis in which the nuclear envelope breaks down and chromosomes fully condense is:',
 "options":{"A":'Metaphase', "B":'Anaphase', "C":'Telophase', "D":'Prophase'},"answer":'D'},
{"id":24,"subject":'Biology',"topic":'Cell Cycle & Division',"difficulty":'Medium',
 "question":'The process by which the cytoplasm divides to form two separate daughter cells following mitosis is called:',
 "options":{"A":'Interphase', "B":'Cytokinesis', "C":'Synapsis', "D":'Crossing over'},"answer":'B'},
{"id":25,"subject":'Biology',"topic":'Cell Cycle & Division',"difficulty":'Medium',
 "question":'A somatic cell in a certain organism has 2n = 40 chromosomes. How many chromosomes will each of its gametes contain after meiosis?',
 "options":{"A":'40', "B":'80', "C":'20', "D":'10'},"answer":'C'},
{"id":26,"subject":'Biology',"topic":'Cell Cycle & Division',"difficulty":'Hard',
 "question":'The M checkpoint (spindle checkpoint) during mitosis prevents anaphase from beginning until:',
 "options":{"A":'DNA replication is complete', "B":'The cell has reached an adequate size', "C":'Cytokinesis has already occurred', "D":'All chromosomes are properly attached to spindle fibers from both poles'},"answer":'D'},
{"id":27,"subject":'Biology',"topic":'Cell Cycle & Division',"difficulty":'Medium',
 "question":'Mutations in genes that normally regulate the cell cycle, allowing uncontrolled cell division, can lead to the development of:',
 "options":{"A":'Apoptosis', "B":'Cancer (tumor formation)', "C":'Meiotic arrest', "D":'Cell senescence exclusively'},"answer":'B'},
{"id":28,"subject":'Biology',"topic":'Genetics',"difficulty":'Easy',
 "question":'In pea plants, round seed shape (R) is dominant over wrinkled (r). A cross between a heterozygous (Rr) and a homozygous recessive (rr) plant produces offspring in which phenotypic ratio?',
 "options":{"A":'All round', "B":'3 round : 1 wrinkled', "C":'1 round : 1 wrinkled', "D":'All wrinkled'},"answer":'C'},
{"id":29,"subject":'Biology',"topic":'Genetics',"difficulty":'Medium',
 "question":'A cross between two heterozygous round-seeded pea plants (Rr x Rr) yields what expected genotypic ratio?',
 "options":{"A":'1 RR : 2 Rr : 1 rr', "B":'All Rr', "C":'3 RR : 1 rr', "D":'1 RR : 1 rr'},"answer":'A'},
{"id":30,"subject":'Biology',"topic":'Genetics',"difficulty":'Medium',
 "question":'A disorder is X-linked dominant. An affected father and an unaffected mother have children. What is expected of the offspring?',
 "options":{"A":'All sons will be affected, and no daughters will be affected', "B":'Half the children of both sexes will be affected', "C":'All daughters will be affected, and no sons will be affected', "D":'None of the children will be affected'},"answer":'C'},
{"id":31,"subject":'Biology',"topic":'Genetics',"difficulty":'Hard',
 "question":'In a dihybrid test cross, AaBb x aabb, what fraction of the offspring is expected to show the recessive phenotype for both traits?',
 "options":{"A":'1/2', "B":'1/4', "C":'1/8', "D":'1/16'},"answer":'B'},
{"id":32,"subject":'Biology',"topic":'Genetics',"difficulty":'Medium',
 "question":'A mother with blood type O and a father with blood type AB have children. Which blood types are possible in their children?',
 "options":{"A":'A and B only', "B":'O and AB only', "C":'A, B, AB, and O', "D":'Only O'},"answer":'A'},
{"id":33,"subject":'Biology',"topic":'Genetics',"difficulty":'Hard',
 "question":'A trait shows a pattern in which affected individuals are typically only male, the trait is transmitted through unaffected carrier mothers, and affected fathers never transmit the trait to their sons. This is most consistent with:',
 "options":{"A":'Autosomal dominant inheritance', "B":'Y-linked inheritance', "C":'X-linked recessive inheritance', "D":'Mitochondrial inheritance'},"answer":'C'},
{"id":34,"subject":'Biology',"topic":'Genetics',"difficulty":'Medium',
 "question":'In certain plant species, a cross between a red-flowered and a white-flowered variety produces offspring with flowers that are spotted red and white, rather than blended pink. This phenomenon is best described as:',
 "options":{"A":'Incomplete dominance', "B":'Epistasis', "C":'Complete dominance', "D":'Codominance'},"answer":'D'},
{"id":35,"subject":'Biology',"topic":'Molecular Biology',"difficulty":'Easy',
 "question":'The two strands of DNA are complementary because adenine always pairs with thymine, and guanine always pairs with:',
 "options":{"A":'Cytosine', "B":'Adenine', "C":'Thymine', "D":'Uracil'},"answer":'A'},
{"id":36,"subject":'Biology',"topic":'Molecular Biology',"difficulty":'Easy',
 "question":'A codon consists of how many nucleotides?',
 "options":{"A":'One', "B":'Two', "C":'Three', "D":'Four'},"answer":'C'},
{"id":37,"subject":'Biology',"topic":'Molecular Biology',"difficulty":'Medium',
 "question":'The lagging strand during DNA replication is synthesized discontinuously because DNA polymerase can only synthesize new DNA in the:',
 "options":{"A":"3' to 5' direction", "B":'Either direction, interchangeably', "C":'A direction unrelated to the template strand', "D":"5' to 3' direction"},"answer":'D'},
{"id":38,"subject":'Biology',"topic":'Molecular Biology',"difficulty":'Medium',
 "question":'Which of the following correctly describes the function of tRNA during protein synthesis?',
 "options":{"A":'It carries the genetic code directly from DNA to the ribosome', "B":'It catalyzes peptide bond formation without any ribosomal involvement', "C":'It serves as the template for DNA replication', "D":'It has an anticodon that base-pairs with an mRNA codon and delivers the corresponding amino acid'},"answer":'D'},
{"id":39,"subject":'Biology',"topic":'Molecular Biology',"difficulty":'Medium',
 "question":'A mutation in which a segment of DNA is reversed in orientation within the chromosome is called a(n):',
 "options":{"A":'Duplication', "B":'Insertion', "C":'Inversion', "D":'Substitution'},"answer":'C'},
{"id":40,"subject":'Biology',"topic":'Molecular Biology',"difficulty":'Hard',
 "question":"Which type of mutation is most likely to have no effect on the resulting protein's function?",
 "options":{"A":'A frameshift mutation occurring early in the gene', "B":'A nonsense mutation near the start of the gene', "C":'A silent (synonymous) mutation', "D":'A large deletion spanning multiple exons'},"answer":'C'},
{"id":41,"subject":'Biology',"topic":'Molecular Biology',"difficulty":'Hard',
 "question":"In eukaryotes, the addition of a 5' cap and a poly-A tail to pre-mRNA occurs mainly to:",
 "options":{"A":'Prevent the mRNA from ever leaving the nucleus', "B":'Directly code for additional amino acids', "C":'Terminate transcription of the gene', "D":'Protect the mRNA from degradation and assist in ribosome binding for translation'},"answer":'D'},
{"id":42,"subject":'Biology',"topic":'Molecular Biology',"difficulty":'Medium',
 "question":'Which of the following correctly identifies a pyrimidine base?',
 "options":{"A":'Adenine', "B":'Guanine', "C":'None of the four standard DNA bases are pyrimidines', "D":'Cytosine'},"answer":'D'},
{"id":43,"subject":'Biology',"topic":'Molecular Biology',"difficulty":'Medium',
 "question":"A gene's regulatory region that increases the rate of transcription when bound by specific proteins, sometimes located far from the gene itself, is called a(n):",
 "options":{"A":'Enhancer', "B":'Promoter', "C":'Terminator', "D":'Intron'},"answer":'A'},
{"id":44,"subject":'Biology',"topic":'Molecular Biology',"difficulty":'Easy',
 "question":'The genetic code is read by the ribosome in non-overlapping groups of three nucleotides called:',
 "options":{"A":'Genes', "B":'Alleles', "C":'Codons', "D":'Chromosomes'},"answer":'C'},
{"id":45,"subject":'Biology',"topic":'Evolution',"difficulty":'Easy',
 "question":'The gradual change in the genetic makeup of a population over successive generations is the basic definition of:',
 "options":{"A":'Homeostasis', "B":'Metabolism', "C":'Evolution', "D":'Development'},"answer":'C'},
{"id":46,"subject":'Biology',"topic":'Evolution',"difficulty":'Medium',
 "question":'Which of the following is the best example of an analogous structure, resulting from convergent evolution rather than shared ancestry?',
 "options":{"A":'The forelimbs of a human and a whale', "B":"The bones in a bat's wing and a bird's wing", "C":'The vertebral column of a fish and a mammal', "D":'The wings of a bird and the wings of a butterfly'},"answer":'D'},
{"id":47,"subject":'Biology',"topic":'Evolution',"difficulty":'Medium',
 "question":'A bottleneck effect occurs when:',
 "options":{"A":'A population is drastically reduced in size, leading to a loss of genetic diversity due to chance', "B":"A population's gene pool remains completely unchanged over time", "C":'Gene flow between populations increases dramatically', "D":'Natural selection has no effect on allele frequencies at all'},"answer":'A'},
{"id":48,"subject":'Biology',"topic":'Evolution',"difficulty":'Hard',
 "question":'In a population of 1000 individuals at Hardy-Weinberg equilibrium, allele frequencies are p = 0.6 and q = 0.4. How many individuals are expected to be homozygous recessive?',
 "options":{"A":'360', "B":'160', "C":'480', "D":'240'},"answer":'B'},
{"id":49,"subject":'Biology',"topic":'Classification & Diversity',"difficulty":'Easy',
 "question":"A species' full scientific (binomial) name consists of its genus name followed by its:",
 "options":{"A":'Family name', "B":'Species epithet', "C":'Kingdom name', "D":'Order name'},"answer":'B'},
{"id":50,"subject":'Biology',"topic":'Classification & Diversity',"difficulty":'Easy',
 "question":'Members of kingdom Animalia are distinguished from members of kingdom Plantae mainly because animals are:',
 "options":{"A":'Autotrophic and possess cell walls', "B":'Heterotrophic and generally lack cell walls', "C":'Prokaryotic', "D":'Composed of a single cell only'},"answer":'B'},
{"id":51,"subject":'Biology',"topic":'Classification & Diversity',"difficulty":'Medium',
 "question":'Which of the following best explains why fungi are classified in their own kingdom, separate from plants?',
 "options":{"A":'Fungal cell walls are made of chitin, and fungi are heterotrophic, absorbing nutrients rather than photosynthesizing', "B":'Fungi are prokaryotic while plants are eukaryotic', "C":'Fungi have no cell walls at all', "D":'Fungi are identical to plants in every respect'},"answer":'A'},
{"id":52,"subject":'Biology',"topic":'Classification & Diversity',"difficulty":'Medium',
 "question":'An organism identified as having true tissues, radial symmetry, and specialized stinging cells (cnidocytes) most likely belongs to phylum:',
 "options":{"A":'Porifera', "B":'Cnidaria', "C":'Platyhelminthes', "D":'Mollusca'},"answer":'B'},
{"id":53,"subject":'Biology',"topic":'Classification & Diversity',"difficulty":'Easy',
 "question":'Which taxonomic rank groups together several related genera?',
 "options":{"A":'Kingdom', "B":'Species', "C":'Family', "D":'Domain'},"answer":'C'},
{"id":54,"subject":'Biology',"topic":'Classification & Diversity',"difficulty":'Medium',
 "question":'Members of phylum Mollusca are characterized by a soft body, often protected by a calcium carbonate shell, and typically include a muscular structure used for locomotion called the:',
 "options":{"A":'Mantle', "B":'Foot', "C":'Radula', "D":'Siphon'},"answer":'B'},
{"id":55,"subject":'Biology',"topic":'Plant Biology',"difficulty":'Easy',
 "question":'The green pigment essential for absorbing light energy during photosynthesis is:',
 "options":{"A":'Carotenoid', "B":'Xanthophyll', "C":'Anthocyanin', "D":'Chlorophyll'},"answer":'D'},
{"id":56,"subject":'Biology',"topic":'Plant Biology',"difficulty":'Medium',
 "question":'In the light-dependent reactions of photosynthesis, the splitting of water (photolysis) occurs at:',
 "options":{"A":'Photosystem I only', "B":'Photosystem II', "C":'The stroma', "D":'The mitochondrial matrix'},"answer":'B'},
{"id":57,"subject":'Biology',"topic":'Plant Biology',"difficulty":'Medium',
 "question":'The stomata of a leaf typically close during periods of water stress mainly to:',
 "options":{"A":'Reduce water loss through transpiration', "B":'Increase the overall rate of photosynthesis', "C":'Increase CO2 uptake into the leaf', "D":'Promote pollination'},"answer":'A'},
{"id":58,"subject":'Biology',"topic":'Plant Biology',"difficulty":'Hard',
 "question":'A major advantage of C4 photosynthesis over C3 photosynthesis in hot, dry climates is that C4 plants:',
 "options":{"A":'Minimize photorespiration by spatially separating initial carbon fixation from the Calvin cycle', "B":'Have lower rates of photosynthesis overall', "C":'Do not require sunlight at all', "D":'Lack stomata entirely'},"answer":'A'},
{"id":59,"subject":'Biology',"topic":'Plant Biology',"difficulty":'Medium',
 "question":'Gibberellins, a class of plant hormones, are primarily known for promoting:',
 "options":{"A":'Leaf abscission', "B":'Stomatal closure exclusively', "C":'Stem elongation and seed germination', "D":'Root formation only'},"answer":'C'},
{"id":60,"subject":'Biology',"topic":'Plant Biology',"difficulty":'Easy',
 "question":'In flowering plants, the ovary of a flower typically develops into the:',
 "options":{"A":'Seed', "B":'Petal', "C":'Fruit', "D":'Stamen'},"answer":'C'},
{"id":61,"subject":'Biology',"topic":'Human Physiology - Digestion',"difficulty":'Easy',
 "question":'Bile, which aids in fat digestion, is produced by the:',
 "options":{"A":'Pancreas', "B":'Gallbladder', "C":'Stomach', "D":'Liver'},"answer":'D'},
{"id":62,"subject":'Biology',"topic":'Human Physiology - Digestion',"difficulty":'Medium',
 "question":'The enzyme pepsin functions optimally in the highly acidic environment of the stomach, which is maintained by:',
 "options":{"A":'Bicarbonate ions', "B":'Hydrochloric acid (HCl)', "C":'Bile salts', "D":'Pancreatic amylase'},"answer":'B'},
{"id":63,"subject":'Biology',"topic":'Human Physiology - Digestion',"difficulty":'Medium',
 "question":'Segmentation, a type of intestinal movement involving localized contractions, primarily functions to:',
 "options":{"A":'Mix chyme with digestive juices and increase contact with the intestinal wall for absorption', "B":'Propel food rapidly toward the rectum', "C":'Prevent any absorption from occurring', "D":'Produce digestive enzymes'},"answer":'A'},
{"id":64,"subject":'Biology',"topic":'Human Physiology - Digestion',"difficulty":'Hard',
 "question":'A deficiency of intrinsic factor, produced by stomach cells, would most directly impair the absorption of:',
 "options":{"A":'Vitamin B12', "B":'Glucose', "C":'Fat-soluble vitamins', "D":'Water'},"answer":'A'},
{"id":65,"subject":'Biology',"topic":'Human Physiology - Circulation',"difficulty":'Easy',
 "question":'The heart chamber that receives oxygenated blood directly from the lungs is the:',
 "options":{"A":'Right atrium', "B":'Left atrium', "C":'Right ventricle', "D":'Left ventricle'},"answer":'B'},
{"id":66,"subject":'Biology',"topic":'Human Physiology - Circulation',"difficulty":'Medium',
 "question":'Veins generally have thinner walls than arteries mainly because:',
 "options":{"A":'Veins carry blood under much higher pressure than arteries', "B":'Veins carry blood under much lower pressure than arteries', "C":'Veins never carry any blood at all', "D":'Arteries have no muscular tissue in their walls'},"answer":'B'},
{"id":67,"subject":'Biology',"topic":'Human Physiology - Circulation',"difficulty":'Medium',
 "question":'Erythropoietin, a hormone released by the kidneys, primarily stimulates:',
 "options":{"A":'White blood cell production', "B":'Platelet destruction', "C":'Blood clotting directly', "D":'Red blood cell production in bone marrow'},"answer":'D'},
{"id":68,"subject":'Biology',"topic":'Human Physiology - Circulation',"difficulty":'Hard',
 "question":'The diagram shows a cross-section of the human heart with its four valves labeled W, X, Y, and Z. During ventricular diastole (relaxation), which labeled valves are open, allowing blood to flow from the atria into the ventricles?',
 "image":'images/q_heart_valves_diagram.png',
 "options":{"A":'Y and Z (the semilunar valves)', "B":'W and X (the atrioventricular valves)', "C":'All four valves are open simultaneously', "D":'All four valves are closed at this point'},"answer":'B'},
{"id":69,"subject":'Biology',"topic":'Human Physiology - Respiration',"difficulty":'Easy',
 "question":'The two main bronchi branch off from the:',
 "options":{"A":'Larynx', "B":'Alveoli', "C":'Trachea', "D":'Pharynx'},"answer":'C'},
{"id":70,"subject":'Biology',"topic":'Human Physiology - Respiration',"difficulty":'Medium',
 "question":'The concentration of carbon dioxide in the blood is the primary factor regulating:',
 "options":{"A":'Heart rate exclusively', "B":'Blood clotting', "C":'Digestive enzyme secretion', "D":'Breathing rate, via chemoreceptors sensitive to blood CO2 and pH'},"answer":'D'},
{"id":71,"subject":'Biology',"topic":'Human Physiology - Respiration',"difficulty":'Medium',
 "question":'Vital capacity refers to:',
 "options":{"A":'The maximum volume of air that can be forcibly exhaled after a maximum inhalation', "B":'The total lung volume, including air that can never be expelled', "C":'The volume of air taken in during a single normal breath', "D":'The rate of breathing per minute'},"answer":'A'},
{"id":72,"subject":'Biology',"topic":'Human Physiology - Excretion',"difficulty":'Easy',
 "question":'The funnel-shaped structure that collects urine within the kidney before it enters the ureter is the:',
 "options":{"A":'Renal cortex', "B":'Glomerulus', "C":"Bowman's capsule", "D":'Renal pelvis'},"answer":'D'},
{"id":73,"subject":'Biology',"topic":'Human Physiology - Excretion',"difficulty":'Medium',
 "question":'Which process in the nephron involves the movement of substances from the peritubular capillaries directly into the tubular fluid?',
 "options":{"A":'Filtration', "B":'Reabsorption', "C":'Tubular secretion', "D":'Micturition'},"answer":'C'},
{"id":74,"subject":'Biology',"topic":'Human Physiology - Excretion',"difficulty":'Hard',
 "question":'A person suffering from severe dehydration would be expected to have:',
 "options":{"A":'Increased ADH secretion, leading to more concentrated, reduced-volume urine', "B":'Decreased ADH secretion, leading to dilute, increased-volume urine', "C":'No change at all in ADH secretion or urine concentration', "D":'Complete cessation of urine production'},"answer":'A'},
{"id":75,"subject":'Biology',"topic":'Human Physiology - Nervous & Endocrine',"difficulty":'Easy',
 "question":'The part of the brain primarily responsible for coordinating balance and fine motor control is the:',
 "options":{"A":'Medulla oblongata', "B":'Cerebrum', "C":'Hypothalamus', "D":'Cerebellum'},"answer":'D'},
{"id":76,"subject":'Biology',"topic":'Human Physiology - Nervous & Endocrine',"difficulty":'Medium',
 "question":'Neurotransmitters are stored in and released from structures at the end of the axon called:',
 "options":{"A":'Dendrites', "B":'The nucleus', "C":'The cell body', "D":'Synaptic vesicles at the axon terminal'},"answer":'D'},
{"id":77,"subject":'Biology',"topic":'Human Physiology - Nervous & Endocrine',"difficulty":'Medium',
 "question":'The hormones insulin and glucagon work together to regulate blood glucose levels through a system known as:',
 "options":{"A":'Positive feedback', "B":'No feedback mechanism at all', "C":'Negative feedback (antagonistic hormone control)', "D":'A single, one-directional pathway'},"answer":'C'},
{"id":78,"subject":'Biology',"topic":'Human Physiology - Nervous & Endocrine',"difficulty":'Hard',
 "question":'Damage to the cerebellum would most likely result in:',
 "options":{"A":'Loss of long-term memory', "B":'Complete loss of vision', "C":'Impaired coordination, balance, and fine motor control', "D":'Inability to regulate body temperature'},"answer":'C'},
{"id":79,"subject":'Biology',"topic":'Human Physiology - Reproduction',"difficulty":'Easy',
 "question":'The site of fertilization in the human female reproductive tract is normally the:',
 "options":{"A":'Fallopian tube (oviduct)', "B":'Uterus', "C":'Vagina', "D":'Ovary'},"answer":'A'},
{"id":80,"subject":'Biology',"topic":'Human Physiology - Reproduction',"difficulty":'Medium',
 "question":'Testosterone, produced mainly by the testes, is primarily responsible for:',
 "options":{"A":'Development and maintenance of male secondary sexual characteristics', "B":'Regulating the female menstrual cycle', "C":'Milk production', "D":'Triggering ovulation'},"answer":'A'},
{"id":81,"subject":'Biology',"topic":'Ecology',"difficulty":'Medium',
 "question":'A keystone species is one that:',
 "options":{"A":'Has little to no effect on its ecosystem', "B":'Has a disproportionately large effect on its ecosystem relative to its abundance', "C":'Is always the most abundant species in an ecosystem', "D":'Cannot be removed from any food web without consequence'},"answer":'B'},

# ============================================================
# CHEMISTRY (45 questions) - id 82-126
# ============================================================
{"id":82,"subject":'Chemistry',"topic":'Atomic Structure',"difficulty":'Easy',
 "question":"The number of protons in an atom's nucleus determines its:",
 "options":{"A":'Mass number', "B":'Atomic number (element identity)', "C":'Number of neutrons', "D":'Isotope form'},"answer":'B'},
{"id":83,"subject":'Chemistry',"topic":'Atomic Structure',"difficulty":'Medium',
 "question":'An atom of magnesium-24 (atomic number 12) contains how many neutrons?',
 "options":{"A":'24', "B":'36', "C":'12', "D":'2'},"answer":'C'},
{"id":84,"subject":'Chemistry',"topic":'Atomic Structure',"difficulty":'Medium',
 "question":'According to the Aufbau principle, electrons fill atomic orbitals:',
 "options":{"A":'Randomly, without any particular order', "B":'Starting from the highest energy orbitals first', "C":'Starting from the lowest energy orbitals and proceeding to higher energy orbitals', "D":'Only in the outermost shell first'},"answer":'C'},
{"id":85,"subject":'Chemistry',"topic":'Atomic Structure',"difficulty":'Hard',
 "question":'An atom has the electron configuration [Ar]3d10 4s2 4p1. This element most likely belongs to which group of the periodic table?',
 "options":{"A":'Group 12', "B":'Group 13', "C":'Group 14', "D":'Group 3'},"answer":'B'},
{"id":86,"subject":'Chemistry',"topic":'Periodic Table',"difficulty":'Easy',
 "question":'Elements within the same period of the periodic table have the same number of:',
 "options":{"A":'Valence electrons', "B":'Occupied electron shells (principal energy levels)', "C":'Protons', "D":'Isotopes'},"answer":'B'},
{"id":87,"subject":'Chemistry',"topic":'Periodic Table',"difficulty":'Medium',
 "question":'Which of the following correctly describes the general trend in first ionization energy across a period, from left to right?',
 "options":{"A":'It generally decreases', "B":'It remains exactly constant', "C":'It becomes negative', "D":'It generally increases, with some exceptions'},"answer":'D'},
{"id":88,"subject":'Chemistry',"topic":'Periodic Table',"difficulty":'Medium',
 "question":'An element located in Group 1, Period 4 of the periodic table would most likely:',
 "options":{"A":'Have a very high ionization energy', "B":'Readily gain seven electrons', "C":'Readily lose one electron to form a +1 cation', "D":'Be chemically inert'},"answer":'C'},
{"id":89,"subject":'Chemistry',"topic":'Chemical Bonding',"difficulty":'Easy',
 "question":'When a metal atom loses one or more electrons to a nonmetal atom, the metal forms a(n):',
 "options":{"A":'Anion', "B":'Neutral atom', "C":'Cation', "D":'Free radical'},"answer":'C'},
{"id":90,"subject":'Chemistry',"topic":'Chemical Bonding',"difficulty":'Medium',
 "question":'According to VSEPR theory, a molecule with two bonding pairs and no lone pairs on the central atom (e.g., BeCl2) has a molecular shape described as:',
 "options":{"A":'Bent', "B":'Trigonal planar', "C":'Linear', "D":'Tetrahedral'},"answer":'C'},
{"id":91,"subject":'Chemistry',"topic":'Chemical Bonding',"difficulty":'Medium',
 "question":'Ammonia (NH3) is a polar molecule mainly because:',
 "options":{"A":'It has a symmetrical trigonal pyramidal shape with no net dipole', "B":'Its trigonal pyramidal shape and the lone pair on nitrogen create an asymmetrical distribution of charge', "C":'Nitrogen and hydrogen have identical electronegativities', "D":'It contains only nonpolar bonds'},"answer":'B'},
{"id":92,"subject":'Chemistry',"topic":'Chemical Bonding',"difficulty":'Hard',
 "question":'The relatively low boiling points of noble gases compared to many other elements are mainly due to:',
 "options":{"A":'Strong covalent bonds between noble gas atoms', "B":'Strong ionic bonds between the atoms', "C":'Very weak London dispersion forces being the only intermolecular attraction present', "D":'Hydrogen bonding between noble gas atoms'},"answer":'C'},
{"id":93,"subject":'Chemistry',"topic":'States of Matter',"difficulty":'Easy',
 "question":'The graph shows a heating curve for a pure solid substance being heated at a constant rate, with two flat (plateau) regions visible. What do these plateau regions represent?',
 "image":'images/q_heating_curve_graph.png',
 "options":{"A":'Phase changes (such as melting and boiling), where added heat goes into changing state rather than raising temperature', "B":'Periods where the temperature is decreasing', "C":'Points where no heat is being supplied to the substance', "D":'Errors in the experimental data'},"answer":'A'},
{"id":94,"subject":'Chemistry',"topic":'States of Matter',"difficulty":'Medium',
 "question":'A gas occupies 3.0 L at a pressure of 5.0 atm. What volume will it occupy at 1.0 atm, assuming constant temperature?',
 "options":{"A":'0.6 L', "B":'3.0 L', "C":'8.0 L', "D":'15 L'},"answer":'D'},
{"id":95,"subject":'Chemistry',"topic":'States of Matter',"difficulty":'Hard',
 "question":'A sample of gas at 1 atm and 300 K occupies 8 L. If the pressure is increased to 2 atm and the temperature is increased to 450 K, what is the new volume?',
 "options":{"A":'4 L', "B":'12 L', "C":'8 L', "D":'6 L'},"answer":'D'},
{"id":96,"subject":'Chemistry',"topic":'Stoichiometry',"difficulty":'Easy',
 "question":'The molar mass of ammonia (NH3) is approximately:',
 "options":{"A":'17 g/mol', "B":'14 g/mol', "C":'16 g/mol', "D":'34 g/mol'},"answer":'A'},
{"id":97,"subject":'Chemistry',"topic":'Stoichiometry',"difficulty":'Medium',
 "question":'How many moles of hydrogen atoms are present in 2 moles of H2O?',
 "options":{"A":'1', "B":'4', "C":'2', "D":'6'},"answer":'B'},
{"id":98,"subject":'Chemistry',"topic":'Stoichiometry',"difficulty":'Hard',
 "question":'A 250 mL solution contains 12.5 g of NaOH (molar mass 40 g/mol). What is the molarity of the solution?',
 "options":{"A":'0.5 M', "B":'1.0 M', "C":'2.0 M', "D":'1.25 M'},"answer":'D'},
{"id":99,"subject":'Chemistry',"topic":'Stoichiometry',"difficulty":'Medium',
 "question":'In the reaction 2Al + 3H2SO4 -> Al2(SO4)3 + 3H2, how many moles of H2 gas are produced from 4 moles of Al reacting completely with excess H2SO4?',
 "options":{"A":'4', "B":'3', "C":'6', "D":'8'},"answer":'C'},
{"id":100,"subject":'Chemistry',"topic":'Thermochemistry',"difficulty":'Easy',
 "question":'A process that releases energy to the surroundings, often felt as warmth, is called:',
 "options":{"A":'Exothermic', "B":'Endothermic', "C":'Isothermal', "D":'Adiabatic'},"answer":'A'},
{"id":101,"subject":'Chemistry',"topic":'Thermochemistry',"difficulty":'Medium',
 "question":'The standard enthalpy of formation of an element in its most stable form (e.g., O2 gas) is defined as:',
 "options":{"A":'A large positive value', "B":'Zero', "C":'A large negative value', "D":'Undefined'},"answer":'B'},
{"id":102,"subject":'Chemistry',"topic":'Chemical Equilibrium',"difficulty":'Medium',
 "question":'For the reaction H2(g) + I2(g) <-> 2HI(g), which has equal moles of gas on both sides, changing the pressure of the system by changing volume will:',
 "options":{"A":'Strongly favor the products', "B":'Strongly favor the reactants', "C":'Completely stop the reaction', "D":'Have essentially no effect on the position of equilibrium, since moles of gas are equal on both sides'},"answer":'D'},
{"id":103,"subject":'Chemistry',"topic":'Chemical Equilibrium',"difficulty":'Hard',
 "question":'A reaction with a very small equilibrium constant (Keq much less than 1) indicates that at equilibrium:',
 "options":{"A":'The reaction mixture consists mostly of unreacted reactants', "B":'The reaction mixture consists mostly of products', "C":'The reaction has gone to completion', "D":'No reactants remain at all'},"answer":'A'},
{"id":104,"subject":'Chemistry',"topic":'Reaction Kinetics',"difficulty":'Easy',
 "question":'Which of the following would generally decrease the rate of a chemical reaction?',
 "options":{"A":'Decreasing the concentration of reactants', "B":'Increasing the temperature', "C":'Adding a catalyst', "D":'Increasing the surface area of a solid reactant'},"answer":'A'},
{"id":105,"subject":'Chemistry',"topic":'Reaction Kinetics',"difficulty":'Medium',
 "question":"A reaction's rate law is experimentally determined to be Rate = k[A]^2. This reaction is said to be:",
 "options":{"A":'Second order overall, and second order with respect to A', "B":'Zero order overall', "C":'First order overall', "D":'Third order overall'},"answer":'A'},
{"id":106,"subject":'Chemistry',"topic":'Electrochemistry',"difficulty":'Medium',
 "question":'In a standard galvanic cell, electrons flow through the external circuit from the:',
 "options":{"A":'Cathode to the anode', "B":'Salt bridge to the anode', "C":'Cathode to the salt bridge', "D":'Anode to the cathode'},"answer":'D'},
{"id":107,"subject":'Chemistry',"topic":'Electrochemistry',"difficulty":'Hard',
 "question":'In the reaction Sn(s) + 2AgNO3(aq) -> Sn(NO3)2(aq) + 2Ag(s), tin (Sn) is:',
 "options":{"A":'The oxidizing agent, being reduced', "B":'The reducing agent, being oxidized', "C":'Unchanged throughout the reaction', "D":'Acting only as a catalyst'},"answer":'B'},
{"id":108,"subject":'Chemistry',"topic":'Acids & Bases',"difficulty":'Easy',
 "question":'A solution with a pH less than 7 is classified as:',
 "options":{"A":'Basic', "B":'Acidic', "C":'Neutral', "D":'Amphoteric'},"answer":'B'},
{"id":109,"subject":'Chemistry',"topic":'Acids & Bases',"difficulty":'Medium',
 "question":'A solution has a pOH of 3. What is its pH (assuming Kw = 1x10^-14 at 25 degrees C)?',
 "options":{"A":'3', "B":'14', "C":'11', "D":'7'},"answer":'C'},
{"id":110,"subject":'Chemistry',"topic":'Acids & Bases',"difficulty":'Medium',
 "question":'According to the Bronsted-Lowry theory, an acid is defined as a species that:',
 "options":{"A":'Accepts a proton (H+)', "B":'Donates a proton (H+)', "C":'Accepts a pair of electrons', "D":'Always contains oxygen'},"answer":'B'},
{"id":111,"subject":'Chemistry',"topic":'Acids & Bases',"difficulty":'Hard',
 "question":'Adding a small amount of strong acid to a buffer solution containing a weak acid and its conjugate base causes:',
 "options":{"A":'A large, dramatic drop in pH', "B":'Only a small change in pH, since the conjugate base neutralizes most of the added acid', "C":'The buffer to immediately fail and behave like pure water', "D":'The pH to rise sharply'},"answer":'B'},
{"id":112,"subject":'Chemistry',"topic":'Organic Chemistry',"difficulty":'Easy',
 "question":"The functional group -O- linking two carbon-containing groups (R-O-R') characterizes:",
 "options":{"A":'Alcohols', "B":'Esters', "C":'Ethers', "D":'Ketones'},"answer":'C'},
{"id":113,"subject":'Chemistry',"topic":'Organic Chemistry',"difficulty":'Medium',
 "question":'Which type of hydrocarbon contains only single bonds between carbon atoms and is considered saturated?',
 "options":{"A":'Alkanes', "B":'Alkenes', "C":'Alkynes', "D":'Aromatic hydrocarbons'},"answer":'A'},
{"id":114,"subject":'Chemistry',"topic":'Organic Chemistry',"difficulty":'Medium',
 "question":'The combustion of a hydrocarbon in excess oxygen produces primarily:',
 "options":{"A":'Carbon monoxide and hydrogen gas', "B":'Only carbon and oxygen', "C":'Methane and nitrogen', "D":'Carbon dioxide and water'},"answer":'D'},
{"id":115,"subject":'Chemistry',"topic":'Organic Chemistry',"difficulty":'Hard',
 "question":'Optical isomers (enantiomers) of a compound are non-superimposable mirror images of each other mainly because the molecule contains:',
 "options":{"A":'A chiral (asymmetric) carbon atom bonded to four different groups', "B":'A double bond', "C":'An aromatic ring', "D":'No carbon atoms at all'},"answer":'A'},
{"id":116,"subject":'Chemistry',"topic":'Organic Chemistry',"difficulty":'Medium',
 "question":'Saponification is the reaction of a fat or oil with a strong base to produce glycerol and:',
 "options":{"A":'An ester', "B":'Soap (a salt of a fatty acid)', "C":'A ketone', "D":'An aldehyde'},"answer":'B'},
{"id":117,"subject":'Chemistry',"topic":'Organic Chemistry',"difficulty":'Easy',
 "question":'Which functional group characterizes a nitrile compound?',
 "options":{"A":'-C#N (carbon-nitrogen triple bond)', "B":'-OH', "C":'-COOH', "D":'-CHO'},"answer":'A'},
{"id":118,"subject":'Chemistry',"topic":'Inorganic Chemistry',"difficulty":'Medium',
 "question":'Group 2 elements (alkaline earth metals) are generally more reactive than transition metals but less reactive than Group 1 metals mainly because:',
 "options":{"A":'They have a completely filled outer electron shell', "B":'They have two valence electrons, more strongly held than a single Group 1 valence electron, but still relatively easy to remove', "C":'They have no valence electrons at all', "D":'They are always classified as non-metals'},"answer":'B'},
{"id":119,"subject":'Chemistry',"topic":'Inorganic Chemistry',"difficulty":'Medium',
 "question":'Noble gases have very high ionization energies mainly because:',
 "options":{"A":'They have incomplete outer electron shells', "B":'Their outer electron shell is completely filled, making removal of an electron energetically unfavorable', "C":'They have very large atomic radii', "D":'They readily lose electrons to other atoms'},"answer":'B'},
{"id":120,"subject":'Chemistry',"topic":'Inorganic Chemistry',"difficulty":'Hard',
 "question":"In the reaction 2KI + Cl2 -> 2KCl + I2, iodine's oxidation state changes from:",
 "options":{"A":'0 to -1 (reduction)', "B":'+1 to -1', "C":'-1 to 0 (oxidation)', "D":'No change occurs'},"answer":'C'},
{"id":121,"subject":'Chemistry',"topic":'Physical Chemistry',"difficulty":'Medium',
 "question":'The vapor pressure of a liquid at a given temperature is defined as:',
 "options":{"A":"The atmospheric pressure at the liquid's surface", "B":'The pressure required to freeze the liquid', "C":'The pressure exerted only by the liquid phase, not the vapor', "D":"The pressure exerted by the liquid's vapor when in equilibrium with the liquid phase"},"answer":'D'},
{"id":122,"subject":'Chemistry',"topic":'Physical Chemistry',"difficulty":'Hard',
 "question":'20 mL of 0.3 M Ba(OH)2 is required to completely neutralize 30 mL of HCl solution (Ba(OH)2 + 2HCl -> BaCl2 + 2H2O). What is the molarity of the HCl solution?',
 "options":{"A":'0.2 M', "B":'0.3 M', "C":'0.6 M', "D":'0.4 M'},"answer":'D'},
{"id":123,"subject":'Chemistry',"topic":'Environmental Chemistry',"difficulty":'Easy',
 "question":"Which of the following best describes the 'greenhouse effect'?",
 "options":{"A":"The cooling of Earth's atmosphere due to reflected sunlight", "B":'The depletion of the ozone layer', "C":"The trapping of infrared radiation by certain atmospheric gases, warming the Earth's surface", "D":'The formation of acid rain'},"answer":'C'},
{"id":124,"subject":'Chemistry',"topic":'Environmental Chemistry',"difficulty":'Medium',
 "question":'Which of the following human activities contributes most directly to deforestation and its associated environmental consequences?',
 "options":{"A":'Recycling programs', "B":'Renewable energy production', "C":'Wildlife conservation efforts', "D":'Clearing forests for agriculture, logging, and urban development'},"answer":'D'},
{"id":125,"subject":'Chemistry',"topic":'Chemical Bonding',"difficulty":'Easy',
 "question":'A double covalent bond involves the sharing of how many electron pairs?',
 "options":{"A":'One', "B":'Three', "C":'Two', "D":'Four'},"answer":'C'},
{"id":126,"subject":'Chemistry',"topic":'Atomic Structure',"difficulty":'Easy',
 "question":'The number of neutrons in an atom can differ between isotopes of the same element, while the number of ______ remains the same.',
 "options":{"A":'Electrons in excited states', "B":'Valence electrons only, but not protons', "C":'Energy levels', "D":'Protons'},"answer":'D'},

# ============================================================
# PHYSICS (36 questions) - id 127-162
# ============================================================
{"id":127,"subject":'Physics',"topic":'Kinematics',"difficulty":'Easy',
 "question":"A cyclist covers 90 km in 2 hours at constant speed. What is the cyclist's speed?",
 "options":{"A":'30 km/h', "B":'45 km/h', "C":'180 km/h', "D":'4.5 km/h'},"answer":'B'},
{"id":128,"subject":'Physics',"topic":'Kinematics',"difficulty":'Medium',
 "question":'A car accelerates from 15 m/s to 35 m/s in 5 seconds. What is its acceleration?',
 "options":{"A":'7 m/s^2', "B":'10 m/s^2', "C":'2 m/s^2', "D":'4 m/s^2'},"answer":'D'},
{"id":129,"subject":'Physics',"topic":'Kinematics',"difficulty":'Hard',
 "question":'An object is dropped from a height and hits the ground after 4 seconds (g = 10 m/s^2, ignoring air resistance). From what height was it dropped?',
 "options":{"A":'80 m', "B":'40 m', "C":'160 m', "D":'20 m'},"answer":'A'},
{"id":130,"subject":'Physics',"topic":'Dynamics',"difficulty":'Easy',
 "question":'The tendency of a moving object to continue moving in a straight line unless acted upon by a force is an example of:',
 "options":{"A":'Momentum', "B":'Inertia', "C":'Acceleration', "D":'Friction'},"answer":'B'},
{"id":131,"subject":'Physics',"topic":'Dynamics',"difficulty":'Medium',
 "question":'A net force of 45 N acts on a 9 kg object. What is its resulting acceleration?',
 "options":{"A":'5 m/s^2', "B":'0.2 m/s^2', "C":'54 m/s^2', "D":'405 m/s^2'},"answer":'A'},
{"id":132,"subject":'Physics',"topic":'Dynamics',"difficulty":'Medium',
 "question":"According to Newton's second law, the acceleration of an object is:",
 "options":{"A":'Inversely proportional to net force and directly proportional to mass', "B":'Directly proportional to net force and inversely proportional to mass', "C":'Unrelated to both force and mass', "D":'Always equal to zero, regardless of force'},"answer":'B'},
{"id":133,"subject":'Physics',"topic":'Dynamics',"difficulty":'Hard',
 "question":"A 5 kg box is pushed with a horizontal force of 25 N across a surface with a coefficient of kinetic friction of 0.2 (g = 10 m/s^2). What is the box's acceleration?",
 "options":{"A":'5 m/s^2', "B":'1 m/s^2', "C":'3 m/s^2', "D":'2 m/s^2'},"answer":'C'},
{"id":134,"subject":'Physics',"topic":'Work, Energy & Power',"difficulty":'Easy',
 "question":'Work is done on an object only when:',
 "options":{"A":'A force is applied, regardless of any resulting motion', "B":'The object remains completely stationary', "C":'A force causes displacement of the object in the direction of the force', "D":'No force is applied to the object at all'},"answer":'C'},
{"id":135,"subject":'Physics',"topic":'Work, Energy & Power',"difficulty":'Medium',
 "question":'A 2 kg object is raised to a height of 8 m (g = 10 m/s^2). What is its gravitational potential energy?',
 "options":{"A":'16 J', "B":'80 J', "C":'8 J', "D":'160 J'},"answer":'D'},
{"id":136,"subject":'Physics',"topic":'Work, Energy & Power',"difficulty":'Medium',
 "question":'A 4 kg object moving at 3 m/s has a kinetic energy of:',
 "options":{"A":'12 J', "B":'18 J', "C":'36 J', "D":'24 J'},"answer":'B'},
{"id":137,"subject":'Physics',"topic":'Work, Energy & Power',"difficulty":'Hard',
 "question":"A motor lifts a 50 kg load to a height of 12 m in 4 seconds (g = 10 m/s^2). What is the motor's power output?",
 "options":{"A":'600 W', "B":'1500 W', "C":'150 W', "D":'6000 W'},"answer":'B'},
{"id":138,"subject":'Physics',"topic":'Circular Motion & Gravitation',"difficulty":'Easy',
 "question":'In uniform circular motion, the net force acting on the object is called the:',
 "options":{"A":'Centripetal force', "B":'Centrifugal force', "C":'Frictional force', "D":'Normal force'},"answer":'A'},
{"id":139,"subject":'Physics',"topic":'Circular Motion & Gravitation',"difficulty":'Medium',
 "question":"According to Newton's law of universal gravitation, doubling the mass of one object while quadrupling the distance between two objects would change the gravitational force to:",
 "options":{"A":'2 times the original', "B":'1/2 of the original', "C":'8 times the original', "D":'1/8 of the original'},"answer":'D'},
{"id":140,"subject":'Physics',"topic":'Circular Motion & Gravitation',"difficulty":'Hard',
 "question":"A person's weight on the surface of a planet with the same mass as Earth but twice Earth's radius would be:",
 "options":{"A":'The same as their weight on Earth', "B":'One quarter of their weight on Earth', "C":'Half of their weight on Earth', "D":'Four times their weight on Earth'},"answer":'B'},
{"id":141,"subject":'Physics',"topic":'Fluid Mechanics',"difficulty":'Easy',
 "question":'The SI unit for measuring pressure is the:',
 "options":{"A":'Pascal', "B":'Newton', "C":'Joule', "D":'Watt'},"answer":'A'},
{"id":142,"subject":'Physics',"topic":'Fluid Mechanics',"difficulty":'Medium',
 "question":'A ship made of steel floats on water, despite steel being denser than water, mainly because:',
 "options":{"A":'Steel is actually less dense than water', "B":'Ships do not experience any buoyant force', "C":'Water has essentially zero density', "D":"The ship's shape displaces a large volume of water, so its average density (including the air-filled hull) is less than water's density"},"answer":'D'},
{"id":143,"subject":'Physics',"topic":'Fluid Mechanics',"difficulty":'Hard',
 "question":"According to Bernoulli's principle, in a horizontal pipe with varying diameter, as fluid speed increases through a narrower section, the fluid's pressure:",
 "options":{"A":'Increases', "B":'Stays exactly the same', "C":'Decreases', "D":'Becomes zero'},"answer":'C'},
{"id":144,"subject":'Physics',"topic":'Oscillations & Waves',"difficulty":'Easy',
 "question":'The time required to complete one full cycle of oscillation is called the:',
 "options":{"A":'Frequency', "B":'Amplitude', "C":'Period', "D":'Wavelength'},"answer":'C'},
{"id":145,"subject":'Physics',"topic":'Oscillations & Waves',"difficulty":'Medium',
 "question":"A simple pendulum's period depends on its length and:",
 "options":{"A":'Its mass', "B":'Its color', "C":'The acceleration due to gravity', "D":'Its amplitude, at all amplitudes'},"answer":'C'},
{"id":146,"subject":'Physics',"topic":'Oscillations & Waves',"difficulty":'Medium',
 "question":'A wave has a frequency of 25 Hz and a wavelength of 8 m. What is its speed?',
 "options":{"A":'3.125 m/s', "B":'33 m/s', "C":'17 m/s', "D":'200 m/s'},"answer":'D'},
{"id":147,"subject":'Physics',"topic":'Oscillations & Waves',"difficulty":'Hard',
 "question":'Resonance occurs when a system is driven at a frequency that matches its:',
 "options":{"A":'Wavelength only', "B":'Amplitude', "C":'Speed of sound', "D":'Natural (or fundamental) frequency'},"answer":'D'},
{"id":148,"subject":'Physics',"topic":'Thermodynamics',"difficulty":'Easy',
 "question":'The transfer of heat via electromagnetic waves, without requiring a medium, is called:',
 "options":{"A":'Conduction', "B":'Radiation', "C":'Convection', "D":'Diffusion'},"answer":'B'},
{"id":149,"subject":'Physics',"topic":'Thermodynamics',"difficulty":'Medium',
 "question":'In an isobaric process, which of the following remains constant?',
 "options":{"A":'Temperature', "B":'Pressure', "C":'Volume', "D":'Internal energy'},"answer":'B'},
{"id":150,"subject":'Physics',"topic":'Thermodynamics',"difficulty":'Hard',
 "question":'A gas undergoes a process in which 250 J of work is done BY the gas on its surroundings, while the gas absorbs 400 J of heat. What is the change in internal energy of the gas?',
 "options":{"A":'150 J', "B":'650 J', "C":'-150 J', "D":'-650 J'},"answer":'A'},
{"id":151,"subject":'Physics',"topic":'Electrostatics',"difficulty":'Easy',
 "question":'A material that does not allow electric charge to flow through it easily is called a(n):',
 "options":{"A":'Conductor', "B":'Semiconductor', "C":'Insulator', "D":'Superconductor'},"answer":'C'},
{"id":152,"subject":'Physics',"topic":'Electrostatics',"difficulty":'Medium',
 "question":'The electric field strength at a point due to a point charge is:',
 "options":{"A":'Directly proportional to the square of the distance from the charge', "B":'Completely independent of distance', "C":'Inversely proportional to the square of the distance from the charge', "D":'Directly proportional to distance'},"answer":'C'},
{"id":153,"subject":'Physics',"topic":'Current Electricity',"difficulty":'Easy',
 "question":'The device used to measure electrical resistance directly is called a(n):',
 "options":{"A":'Ammeter', "B":'Ohmmeter', "C":'Voltmeter', "D":'Galvanometer only'},"answer":'B'},
{"id":154,"subject":'Physics',"topic":'Current Electricity',"difficulty":'Medium',
 "question":'In the circuit shown, resistors R1 (10 ohm) and R2 (10 ohm) are connected in parallel with each other, and this parallel combination is then connected in series with R3 (2 ohm). What is the total resistance of the circuit?',
 "image":'images/q_circuit_r1r2_parallel_r3_series.png',
 "options":{"A":'22 ohm', "B":'7 ohm', "C":'5 ohm', "D":'12 ohm'},"answer":'B'},
{"id":155,"subject":'Physics',"topic":'Current Electricity',"difficulty":'Hard',
 "question":'Two resistors, 6 ohm and 3 ohm, are connected in parallel. What is their equivalent resistance?',
 "options":{"A":'2 ohm', "B":'9 ohm', "C":'4.5 ohm', "D":'18 ohm'},"answer":'A'},
{"id":156,"subject":'Physics',"topic":'Current Electricity',"difficulty":'Medium',
 "question":'A circuit operates at 12 V and draws 3 A of current. What is the power consumed?',
 "options":{"A":'36 W', "B":'4 W', "C":'15 W', "D":'9 W'},"answer":'A'},
{"id":157,"subject":'Physics',"topic":'Electromagnetism',"difficulty":'Medium',
 "question":'Which of the following best describes electromagnetic induction?',
 "options":{"A":'A magnetic field is created by a stationary charge', "B":'An electric field creates a permanent magnet', "C":'A changing magnetic field through a conductor induces an electric current in that conductor', "D":'Current always flows without any external influence'},"answer":'C'},
{"id":158,"subject":'Physics',"topic":'Electromagnetism',"difficulty":'Hard',
 "question":"An electric bell uses an electromagnet to repeatedly strike a bell. When the electromagnet's circuit is broken, the magnetic field:",
 "options":{"A":'Remains permanently magnetized', "B":'Increases in strength', "C":'Collapses, since the magnetic field depends on current flow through the coil', "D":'Reverses direction spontaneously'},"answer":'C'},
{"id":159,"subject":'Physics',"topic":'Modern Physics',"difficulty":'Easy',
 "question":'An atom that has gained or lost one or more electrons, resulting in a net charge, is called a(n):',
 "options":{"A":'Isotope', "B":'Molecule', "C":'Neutron', "D":'Ion'},"answer":'D'},
{"id":160,"subject":'Physics',"topic":'Modern Physics',"difficulty":'Medium',
 "question":'In nuclear fission, a large unstable nucleus:',
 "options":{"A":'Combines with another nucleus to form a heavier one', "B":'Emits only gamma radiation with no structural change', "C":'Splits into two smaller nuclei, releasing energy', "D":'Remains completely stable and unreactive'},"answer":'C'},
{"id":161,"subject":'Physics',"topic":'Modern Physics',"difficulty":'Hard',
 "question":'A sample of a radioactive isotope has a half-life of 5 days. Starting with 100 g, approximately how much remains after 15 days?',
 "options":{"A":'50 g', "B":'25 g', "C":'12.5 g', "D":'6.25 g'},"answer":'C'},
{"id":162,"subject":'Physics',"topic":'Optics',"difficulty":'Medium',
 "question":'The ray diagram shows an object placed between the pole and the focal point (F) of a concave mirror. Based on the diagram, the image formed is:',
 "image":'images/q_concave_mirror_object_within_f.png',
 "options":{"A":'Real, inverted, and diminished', "B":'Virtual, upright, and magnified, formed behind the mirror', "C":'Real, upright, and the same size as the object', "D":'Virtual, inverted, and diminished'},"answer":'B'},

# ============================================================
# ENGLISH (9 questions) - id 163-171
# ============================================================
{"id":163,"subject":'English',"topic":'Synonyms',"difficulty":'Easy',
 "question":"Choose the word most nearly similar in meaning to 'BENEVOLENT':",
 "options":{"A":'Selfish', "B":'Indifferent', "C":'Cruel', "D":'Kind'},"answer":'D'},
{"id":164,"subject":'English',"topic":'Antonyms',"difficulty":'Easy',
 "question":"Choose the word most nearly opposite in meaning to 'CONCISE':",
 "options":{"A":'Brief', "B":'Verbose', "C":'Clear', "D":'Precise'},"answer":'B'},
{"id":165,"subject":'English',"topic":'Grammar',"difficulty":'Easy',
 "question":'Choose the grammatically correct sentence:',
 "options":{"A":'There is many reasons to celebrate.', "B":'There are many reasons to celebrate.', "C":'There is many reason to celebrate.', "D":'There be many reasons to celebrate.'},"answer":'B'},
{"id":166,"subject":'English',"topic":'Grammar',"difficulty":'Medium',
 "question":'Choose the correct sentence:',
 "options":{"A":'She has been living here for 2015.', "B":'She is living here since 2015.', "C":'She has been living here since 2015.', "D":'She lives here since 2015.'},"answer":'C'},
{"id":167,"subject":'English',"topic":'Sentence Correction',"difficulty":'Medium',
 "question":'Choose the sentence that is grammatically correct:',
 "options":{"A":'The jury has reached its verdict.', "B":'The jury have reached its verdict.', "C":'The jury have reached their verdict individually.', "D":'The juries has reached its verdict.'},"answer":'A'},
{"id":168,"subject":'English',"topic":'Vocabulary',"difficulty":'Medium',
 "question":"Choose the word that best completes the sentence: 'The committee's decision was ______, leaving no room for further discussion.'",
 "options":{"A":'Tentative', "B":'Final', "C":'Uncertain', "D":'Debatable'},"answer":'B'},
{"id":169,"subject":'English',"topic":'Idioms',"difficulty":'Medium',
 "question":"Choose the meaning closest to the idiom 'to spill the beans':",
 "options":{"A":'To make a mess accidentally', "B":'To reveal secret information', "C":'To cook a meal quickly', "D":'To waste food'},"answer":'B'},
{"id":170,"subject":'English',"topic":'Sentence Correction',"difficulty":'Hard',
 "question":"Choose the option that best corrects the sentence: 'Walking down the street, the tall buildings impressed the tourists.'",
 "options":{"A":'Walking down the street, the tourists were impressed by the tall buildings.', "B":'Walking down the street, the buildings were impressed by the tourists.', "C":'The tourists impressed the tall buildings, walking down the street.', "D":'No correction is needed.'},"answer":'A'},
{"id":171,"subject":'English',"topic":'Prepositions',"difficulty":'Hard',
 "question":"Choose the correct preposition: 'The volunteers were praised ______ their tireless efforts during the crisis.'",
 "options":{"A":'for', "B":'about', "C":'with', "D":'at'},"answer":'A'},

# ============================================================
# LOGICAL REASONING (9 questions) - id 172-180
# ============================================================
{"id":172,"subject":'Logical Reasoning',"topic":'Number Series',"difficulty":'Easy',
 "question":'Find the next number in the series: 1, 4, 9, 16, ?',
 "options":{"A":'25', "B":'20', "C":'24', "D":'22'},"answer":'A'},
{"id":173,"subject":'Logical Reasoning',"topic":'Number Series',"difficulty":'Easy',
 "question":'Find the missing number: 12, 24, 36, 48, ?',
 "options":{"A":'60', "B":'50', "C":'52', "D":'58'},"answer":'A'},
{"id":174,"subject":'Logical Reasoning',"topic":'Analogies',"difficulty":'Easy',
 "question":'Bee is to Hive as Bird is to:',
 "options":{"A":'Feather', "B":'Sky', "C":'Nest', "D":'Egg'},"answer":'C'},
{"id":175,"subject":'Logical Reasoning',"topic":'Analogies',"difficulty":'Medium',
 "question":'Library is to Books as Museum is to:',
 "options":{"A":'Visitors', "B":'Tickets', "C":'Buildings', "D":'Artifacts'},"answer":'D'},
{"id":176,"subject":'Logical Reasoning',"topic":'Blood Relations',"difficulty":'Medium',
 "question":"Introducing a man, a woman said, 'His wife is the only daughter of my father.' How is the woman related to the man?",
 "options":{"A":'Sister', "B":'Mother', "C":'Wife', "D":'Cousin'},"answer":'C'},
{"id":177,"subject":'Logical Reasoning',"topic":'Coding-Decoding',"difficulty":'Medium',
 "question":'If in a certain code, WATER is written as XBUFS, how is EARTH written in the same code?',
 "options":{"A":'FBSUJ', "B":'FASUI', "C":'EBSUI', "D":'FBSUI'},"answer":'D'},
{"id":178,"subject":'Logical Reasoning',"topic":'Syllogism',"difficulty":'Hard',
 "question":'All teachers are educators. No educators are careless. Which conclusion logically follows?',
 "options":{"A":'Some teachers are careless', "B":'All careless people are teachers', "C":'Some educators are teachers', "D":'No teachers are careless'},"answer":'D'},
{"id":179,"subject":'Logical Reasoning',"topic":'Pattern Recognition',"difficulty":'Hard',
 "question":'Find the next term in the series: 5, 10, 20, 35, 55, ?',
 "options":{"A":'85', "B":'80', "C":'75', "D":'70'},"answer":'B'},
{"id":180,"subject":'Logical Reasoning',"topic":'Direction Sense',"difficulty":'Medium',
 "question":'A boy walks 8 km north, then turns right and walks 6 km. How far is he from his starting point?',
 "options":{"A":'10 km', "B":'14 km', "C":'2 km', "D":'48 km'},"answer":'A'},
]


# ------------------------------------------------------------
# Sanity-check / summary utility
# ------------------------------------------------------------
def summarize(questions):
    from collections import Counter
    subj = Counter(q["subject"] for q in questions)
    diff = Counter(q["difficulty"] for q in questions)
    ans = Counter(q["answer"] for q in questions)
    ids = [q["id"] for q in questions]
    dup_ids = [i for i in set(ids) if ids.count(i) > 1]
    dup_q = [q["question"] for q in questions]
    dup_questions = [t for t in set(dup_q) if dup_q.count(t) > 1]
    images = [q for q in questions if "image" in q]

    print(f"Total questions: {len(questions)}")
    print("\nBy subject:")
    for s, c in subj.items():
        print(f"  {s}: {c}")
    print("\nBy difficulty:")
    for d, c in diff.items():
        print(f"  {d}: {c}")
    print("\nBy correct-answer letter (should be roughly balanced):")
    for L in ["A", "B", "C", "D"]:
        print(f"  {L}: {ans[L]}")
    print(f"\nDuplicate IDs: {dup_ids if dup_ids else 'None'}")
    print(f"Duplicate question text: {dup_questions if dup_questions else 'None'}")
    print(f"\nImage-based questions ({len(images)}):")
    for q in images:
        print(f"  Q{q['id']} [{q['subject']}] -> {q['image']}")

    for q in questions:
        assert set(q["options"].keys()) == {"A", "B", "C", "D"}, f"Q{q['id']} missing an option"
        assert q["answer"] in q["options"], f"Q{q['id']} answer key invalid"
    print("\nAll questions have exactly 4 options (A-D) and a valid answer key. OK.")


def print_answer_key(questions):
    print("\nANSWER KEY")
    print("-" * 40)
    for q in questions:
        print(f"{q['id']:>3}. {q['answer']}", end="   ")
        if q["id"] % 10 == 0:
            print()
    print()


if __name__ == "__main__":
    summarize(QUESTIONS)
    print_answer_key(QUESTIONS)