# Generated by Django 6.1 on 2026-08-12 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0004_question_is_verified_conceptnote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('practice', 'Practice'), ('mock', 'Mock Test'), ('past_paper', 'Past Paper'), ('sectional', 'Sectional Mock')], max_length=15)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('score_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('allow_breaks', models.BooleanField(default=True)),
                ('integrity_flagged', models.BooleanField(default=False)),
                ('device_class', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet')], default='desktop', max_length=10)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='content.exam')),
                ('past_paper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='content.pastpaper')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='content.subject')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='content.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AttemptQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_in_attempt', models.PositiveSmallIntegerField()),
                ('selected_option', models.CharField(blank=True, choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], max_length=1, null=True)),
                ('is_correct', models.BooleanField(null=True)),
                ('time_spent_seconds', models.PositiveIntegerField(default=0)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quiz.attempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='content.question')),
            ],
            options={
                'ordering': ['order_in_attempt'],
            },
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['user', '-started_at'], name='quiz_attemp_user_id_67c6ee_idx'),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['mode', '-started_at'], name='quiz_attemp_mode_563743_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attemptquestion',
            unique_together={('attempt', 'order_in_attempt'), ('attempt', 'question')},
        ),
    ]
