# Generated by Django 6.1 on 2026-08-13 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_question_is_verified_conceptnote'),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MockTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kind', models.CharField(choices=[('full', 'Full Mock'), ('sectional', 'Sectional Mock')], max_length=15)),
                ('duration_minutes', models.PositiveSmallIntegerField()),
                ('total_questions', models.PositiveSmallIntegerField()),
                ('is_free', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mock_tests', to='content.exam')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sectional_mocks', to='content.subject')),
            ],
            options={
                'ordering': ['exam', 'kind', 'name'],
            },
        ),
        migrations.AddField(
            model_name='attempt',
            name='mock_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='quiz.mocktest'),
        ),
    ]
