# Generated by Django 6.1 on 2026-08-13 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_question_is_verified_conceptnote'),
        ('quiz', '0002_mocktest_attempt_mock_test'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coverage_pct', models.FloatField(default=0)),
                ('subtopics_attempted', models.PositiveIntegerField(default=0)),
                ('subtopics_total', models.PositiveIntegerField(default=0)),
                ('questions_attempted', models.PositiveIntegerField(default=0)),
                ('accuracy_pct', models.FloatField(default=0)),
                ('last_computed', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='content.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user', 'subject'],
                'unique_together': {('user', 'subject')},
            },
        ),
    ]
