# Generated by Django 6.1 on 2026-08-13 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_userprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttemptViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_type', models.CharField(choices=[('tab_hidden', 'Tab Hidden'), ('window_blur', 'Window Blur'), ('fullscreen_exit', 'Fullscreen Exit'), ('copy_attempt', 'Copy Attempt')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='quiz.attempt')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['attempt', 'created_at'], name='quiz_attemp_attempt_a91ef5_idx')],
            },
        ),
    ]
