# Generated by Django 6.1 on 2026-08-18 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_question_explanation_options'),
        ('quiz', '0004_attemptviolation'),
    ]

    operations = [
        migrations.AddField(
            model_name='mocktest',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='fixed_in_mock_tests', to='content.question'),
        ),
    ]
