# Generated by Django 6.1 on 2026-08-30 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_pastpaper_student_note'),
        ('quiz', '0005_mocktest_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='subtopic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='content.subtopic'),
        ),
    ]
