# Generated by Django 6.1 on 2026-09-03 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_attempt_subtopic'),
    ]

    operations = [
        migrations.AddField(
            model_name='attemptquestion',
            name='attempts_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
