# Generated by Django 6.1 on 2026-09-05 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_attemptquestion_attempts_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mocktest',
            options={'ordering': ['exam', 'kind', 'id']},
        ),
    ]
