# Generated by Django 6.1 on 2026-08-12 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0004_question_is_verified_conceptnote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('city', models.CharField(blank=True, max_length=60)),
                ('current_class', models.CharField(blank=True, choices=[('fsc1', 'FSc Part 1'), ('fsc2', 'FSc Part 2'), ('repeater', 'Repeater'), ('matric', 'Matric'), ('other', 'Other')], max_length=20)),
                ('target_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('preferred_break_interval_minutes', models.PositiveSmallIntegerField(choices=[(40, '40 min'), (60, '60 min'), (90, '90 min')], default=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('primary_exam', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='content.exam')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
