# Generated by Django 6.1 on 2026-08-18 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('post_type', models.CharField(choices=[('blog', 'Blog'), ('announcement', 'Announcement')], default='blog', max_length=15)),
                ('excerpt', models.CharField(blank=True, help_text='Short teaser shown on the list page. Falls back to a trimmed body if left blank.', max_length=300)),
                ('body', models.TextField()),
                ('cover_image_url', models.URLField(blank=True)),
                ('author_name', models.CharField(blank=True, max_length=120)),
                ('is_published', models.BooleanField(default=False)),
                ('is_pinned', models.BooleanField(default=False, help_text='Pinned + published + announcement shows in the app-wide banner.')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_pinned', '-published_at', '-created_at'],
            },
        ),
    ]
