# Generated by Django 6.1 on 2026-09-05 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Overrides the meta/og description. Falls back to excerpt. Keep to ~155 chars.', max_length=160),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Overrides the <title>/og:title for search & social. Falls back to title. Keep to ~60 chars.', max_length=70),
        ),
    ]
