# Generated by Django 6.1 on 2026-09-07 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_meta_description_post_meta_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='faqs',
            field=models.JSONField(blank=True, default=list, help_text='Optional FAQ list: [{"question": "...", "answer": "..."}, ...]. Leave empty to skip the FAQ section on this post.'),
        ),
    ]
