# Generated by Django 6.1 on 2026-09-07 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_faqs'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='inline_images',
            field=models.JSONField(blank=True, default=list, help_text='Optional in-body images: [{"slug": "...", "src": "/blog/foo.svg", "alt": "...", "caption": "...", "width": 720, "height": 400, "insert_after_heading": "Exact H2 text" or null}, ...].'),
        ),
    ]
