"""One-off: 3 questions in mock5_data.json (generated by mdcat_mock_5.py)
coincidentally share (question_text, option_a) with existing questions
from mocks 1-4 -- the DB dedupe key for past_paper IS NULL rows. Same
fix pattern as mock_4: swap two option slots that do NOT include the
correct answer, per colliding question, so the correct letter and the
answer-letter balance stay untouched.
"""
import json
from pathlib import Path

PATH = Path(__file__).parent.parent / "mdcat-content" / "mock5_data.json"
data = json.loads(PATH.read_text(encoding="utf-8"))
by_id = {q["id"]: q for q in data}

SWAPS = {
    2: ("B", "C"),    # correct = A
    163: ("A", "C"),  # correct = B
    175: ("A", "B"),  # correct = C
}

for qid, (l1, l2) in SWAPS.items():
    q = by_id[qid]
    assert q["answer"] not in (l1, l2), f"Q{qid}: correct answer {q['answer']} is one of the swap letters!"
    opts = q["options"]
    opts[l1], opts[l2] = opts[l2], opts[l1]
    print(f"Q{qid}: swapped {l1}<->{l2} (correct stays at {q['answer']})")

PATH.write_text(json.dumps(data, indent=2), encoding="utf-8")
print(f"rewrote {PATH}")
