"""One-off: 2 questions in mock9_data.json (generated by mdcat_mock_9.py)
coincidentally share (question_text, option_a) with existing questions
from mocks 1-8 -- the DB dedupe key for past_paper IS NULL rows.

Q174 (correct=B): option_a is a distractor, so swap two non-correct
slots (A<->C) to change option_a without touching the correct answer.

Q141 (correct=A): the correct answer's own content sits in slot A, so it
must move out of A -- swap A<->B (correct moves A->B). To keep the
answer-letter distribution at 45/45/45/45, a non-colliding B-correct
question (2) is also swapped A<->B (correct moves B->A) to compensate.
"""
import json
from pathlib import Path

PATH = Path(__file__).parent.parent / "mdcat-content" / "mock9_data.json"
data = json.loads(PATH.read_text(encoding="utf-8"))
by_id = {q["id"]: q for q in data}

q = by_id[174]
assert q["answer"] not in ("A", "C")
opts = q["options"]
opts["A"], opts["C"] = opts["C"], opts["A"]
print(f"Q174: swapped A<->C (correct stays at {q['answer']})")

q = by_id[141]
assert q["answer"] == "A"
opts = q["options"]
opts["A"], opts["B"] = opts["B"], opts["A"]
q["answer"] = "B"
print("Q141: swapped A<->B, correct moved A->B")

q = by_id[2]
assert q["answer"] == "B"
opts = q["options"]
opts["A"], opts["B"] = opts["B"], opts["A"]
q["answer"] = "A"
print("Q2: swapped A<->B, correct moved B->A (balance compensation)")

from collections import Counter
balance = Counter(q["answer"] for q in data)
print("new balance:", dict(balance))

PATH.write_text(json.dumps(data, indent=2), encoding="utf-8")
print(f"rewrote {PATH}")
