# -*- coding: utf-8 -*-
"""Manually assign (topic, subtopic) to all 112 MDCAT_2013.json MCQs, using the
exact vocabulary strings from pmdc_mdcat_syllabus.json, instead of waiting on
the rate-limited Groq tagger.
"""
import json

TAGS = {
    # ---- PHYSICS ----
    1: ("Waves", "Characteristics of Waves"),
    2: ("Work and Energy", "Power"),
    3: ("Rotational and Circular Motion", "Relation Between Angular and Linear Quantities"),
    4: ("Force and Motion", "Newton''s Second Law and Linear Momentum"),
    5: ("Fluid Dynamics", "Fluid Drag"),
    6: ("Fluid Dynamics", "Equation of Continuity"),
    7: ("Fluid Dynamics", "Bernoulli''s Equation"),
    8: ("Waves", "Characteristics of Waves"),
    9: ("Waves", "Characteristics of Waves"),
    10: ("Waves", "Characteristics of Waves"),
    11: ("Waves", "Characteristics of Waves"),
    12: ("Waves", "Simple Harmonic Motion (SHM)"),
    13: ("Waves", "Speed of Sound (Newton''s Formula)"),
    14: ("Force and Motion", "Stress and Strain"),
    15: ("Waves", "Simple Harmonic Motion (SHM)"),
    16: ("Force and Motion", "Stress and Strain"),
    17: ("Thermodynamics", "Cp minus Cv Relation for Ideal Gas"),
    18: ("Thermodynamics", "Thermal Equilibrium and Heat"),
    19: ("Thermodynamics", "First Law of Thermodynamics"),
    20: ("Thermodynamics", "Isothermal Process"),
    21: ("Thermodynamics", "First Law of Thermodynamics"),
    22: ("Electrostatics", "Charging and Discharging of Capacitor"),
    23: ("Alternating Current", "Phase of Alternating Current"),
    24: ("Current Electricity", "Ohm''s Law"),
    25: ("Electromagnetism", "Magnetic Flux Density"),
    26: ("Electromagnetism", "Magnetic Flux Density"),
    27: ("Electronics", "PN Junction (Forward and Reverse Bias)"),
    28: ("Current Electricity", "Ohm''s Law"),
    29: ("Electromagnetism", "Motion of Charged Particle in Magnetic Field"),
    30: ("Dawn of Modern Physics", "Quantum Theory and Radiation (Photons)"),
    31: ("Dawn of Modern Physics", "Quantum Theory and Radiation (Photons)"),
    32: ("Atomic Spectra", "Atomic Spectra / Line Spectrum"),
    33: ("Dawn of Modern Physics", "Quantum Theory and Radiation (Photons)"),
    34: ("Dawn of Modern Physics", "Quantum Theory and Radiation (Photons)"),
    35: ("Dawn of Modern Physics", "Quantum Theory and Radiation (Photons)"),
    36: ("Dawn of Modern Physics", "Quantum Theory and Radiation (Photons)"),
    37: ("Nuclear Physics", "Spontaneous and Random Nuclear Decay"),
    38: ("Nuclear Physics", "Spontaneous and Random Nuclear Decay"),
    39: ("Nuclear Physics", "Spontaneous and Random Nuclear Decay"),
    40: ("Nuclear Physics", "Biological and Medical Uses of Radiation"),
    41: ("Nuclear Physics", "Composition of Atomic Nuclei"),
    42: ("Nuclear Physics", "Spontaneous and Random Nuclear Decay"),
    43: ("Nuclear Physics", "Spontaneous and Random Nuclear Decay"),
    44: ("Waves", "Simple Harmonic Motion (SHM)"),

    # ---- CHEMISTRY ----
    45: ("Fundamental Concepts of Chemistry", "Moles and Avogadro''s Number"),
    46: ("Fundamental Concepts of Chemistry", "Moles and Avogadro''s Number"),
    47: ("Solids", "Crystal Lattice"),
    48: ("Gases", "Real and Ideal Gases"),
    49: ("Atomic Structure", "Electronic Configuration"),
    50: ("Atomic Structure", "Electronic Configuration"),
    51: ("Chemical Bonding", "VSEPR Theory"),
    52: ("Liquids", "Hydrogen Bonding"),
    53: ("Thermochemistry and Energetics", "Enthalpy of Reaction"),
    54: ("Thermochemistry and Energetics", "Exothermic and Endothermic Reactions"),
    55: ("Liquids", "Properties of Liquids (Kinetic Theory)"),
    56: ("Liquids", "Properties of Liquids (Kinetic Theory)"),
    57: ("Electrochemistry", "Redox Reactions"),
    58: ("Reaction Kinetics", "Activation Energy and Activated Complex"),
    59: ("Electrochemistry", "Oxidation and Reduction"),
    60: ("Chemical Equilibrium", "Buffer Solutions"),
    61: ("Chemical Equilibrium", "Buffer Solutions"),
    62: ("Reaction Kinetics", "Order of Reaction"),
    63: ("s and p Block Elements", "Periodic Trends (Radii, IE, EA, Electronegativity)"),
    64: ("s and p Block Elements", "Periodic Trends (Radii, IE, EA, Electronegativity)"),
    65: ("s and p Block Elements", "Group II Reactions"),
    66: ("Chemical Bonding", "Sigma and Pi Bonds"),
    67: ("Transition Elements", "Electronic Structure of d-block"),
    68: ("Transition Elements", "Electronic Structure of d-block"),
    69: ("Chemical Equilibrium", "Buffer Solutions"),
    70: ("Chemical Equilibrium", "Buffer Solutions"),
    71: ("Chemical Bonding", "Bond Energy"),
    72: ("Chemical Equilibrium", "Haber''s Process"),
    73: ("Fundamental Principles of Organic Chemistry", "Isomerism (Stereoisomerism)"),
    74: ("Alkyl Halides", "Nucleophilic Substitution Mechanisms"),
    75: ("Chemistry of Hydrocarbons", "Friedel-Crafts alkylation reaction"),
    76: ("Chemistry of Hydrocarbons", "Structure and Reactivity of Alkenes"),
    77: ("Alkyl Halides", "Nomenclature, Structure, Reactivity"),
    78: ("Alkyl Halides", "Elimination Mechanisms"),
    79: ("Alcohols and Phenols", "Chemistry of Alcohols (Ethers, Esters)"),
    80: ("Alcohols and Phenols", "Nomenclature, Structure, Reactivity of Phenols"),
    81: ("Aldehydes and Ketones", "Reactivity of Aldehydes and Ketones"),
    82: ("Alcohols and Phenols", "Electrophilic Aromatic Substitution in Phenols"),
    83: ("Carboxylic Acids", "Reactivity of Carboxylic Acids"),
    84: ("Aldehydes and Ketones", "Oxidation Reactions"),
    85: ("Aldehydes and Ketones", "Nomenclature and Structure"),
    86: ("Carboxylic Acids", "Conversion to Derivatives (Acyl Halides, Anhydrides, Esters)"),
    87: ("Carboxylic Acids", "Nomenclature, Structure, Preparation"),
    88: ("Macromolecules", "Classification and Structure of Proteins"),
    89: ("Carboxylic Acids", "Conversion to Derivatives (Acyl Halides, Anhydrides, Esters)"),
    90: ("Macromolecules", "Classification and Structure of Proteins"),
    91: ("Macromolecules", "Classification and Structure of Proteins"),
    92: ("Macromolecules", "Classification and Structure of Proteins"),
    93: ("Macromolecules", "Classification and Structure of Proteins"),
    94: ("Macromolecules", "Classification and Structure of Proteins"),
    95: ("Industrial Chemistry", "Polymers (Condensation and Addition)"),
    96: ("Macromolecules", "Classification and Structure of Proteins"),
    97: ("Macromolecules", "Importance of Proteins"),
    98: ("Industrial Chemistry", "Polymers (Condensation and Addition)"),
    99: ("Macromolecules", "Classification and Structure of Proteins"),
    100: ("Macromolecules", "Classification and Structure of Proteins"),
    101: ("Macromolecules", "Enzymes as Biocatalysts"),
    102: ("Reaction Kinetics", "Factors Affecting Rate of Reaction"),

    # ---- ENGLISH ----
    103: ("Formal and Lexical Aspect of Language", "Contextual Vocabulary"),
    104: ("Formal and Lexical Aspect of Language", "Contextual Vocabulary"),
    105: ("Formal and Lexical Aspect of Language", "Contextual Vocabulary"),
    106: ("Formal and Lexical Aspect of Language", "Contextual Vocabulary"),
    107: ("Writing Skills", "Errors of Function and Spelling"),
    108: ("Writing Skills", "Errors of Function and Spelling"),
    109: ("Writing Skills", "Errors of Function and Spelling"),
    110: ("Writing Skills", "Errors of Function and Spelling"),
    111: ("Writing Skills", "Errors of Function and Spelling"),
    112: ("Writing Skills", "Errors of Function and Spelling"),

    # ---- ENGLISH (continued, 113-132) ----
    113: ("Formal and Lexical Aspect of Language", "Prepositions"),
    114: ("Writing Skills", "Subject-Verb Agreement"),
    115: ("Formal and Lexical Aspect of Language", "Active and Passive Voice"),
    116: ("Formal and Lexical Aspect of Language", "Prepositions"),
    117: ("Formal and Lexical Aspect of Language", "Pronoun-Antecedent Agreement"),
    118: ("Formal and Lexical Aspect of Language", "Tenses"),
    119: ("Formal and Lexical Aspect of Language", "Prepositions"),
    120: ("Formal and Lexical Aspect of Language", "Tenses"),
    121: ("Formal and Lexical Aspect of Language", "Prepositions"),
    122: ("Writing Skills", "Subject-Verb Agreement"),
    123: ("Formal and Lexical Aspect of Language", "Contextual Vocabulary"),
    124: ("Formal and Lexical Aspect of Language", "Contextual Vocabulary"),
    125: ("Formal and Lexical Aspect of Language", "Contextual Vocabulary"),
    126: ("Formal and Lexical Aspect of Language", "Contextual Vocabulary"),
    127: ("Formal and Lexical Aspect of Language", "Contextual Vocabulary"),
    128: ("Formal and Lexical Aspect of Language", "Contextual Vocabulary"),
    129: ("Formal and Lexical Aspect of Language", "Contextual Vocabulary"),
    130: ("Formal and Lexical Aspect of Language", "Contextual Vocabulary"),
    131: ("Formal and Lexical Aspect of Language", "Contextual Vocabulary"),
    132: ("Formal and Lexical Aspect of Language", "Contextual Vocabulary"),

    # ---- BIOLOGY (133-220) ----
    133: ("Cell Structure and Function", "Cell Structure (Animal vs Plant)"),
    134: ("Cell Structure and Function", "Cytoplasmic Organelles"),
    135: ("Biotechnology", "Biotechnology and Health Care"),
    136: ("Biotechnology", "Biotechnology and Health Care"),
    137: ("Biotechnology", "Biotechnology and Health Care"),
    138: ("Cell Structure and Function", "Cell Structure (Animal vs Plant)"),
    139: ("Cell Structure and Function", "Cytoplasmic Organelles"),
    140: ("Cell Structure and Function", "Cytoplasmic Organelles"),
    141: ("Cell Structure and Function", "Cytoplasmic Organelles"),
    142: ("Cell Structure and Function", "Cytoplasmic Organelles"),
    143: ("Cell Structure and Function", "Cytoplasmic Organelles"),
    144: ("Cell Structure and Function", "Cytoplasmic Organelles"),
    145: ("Cell Structure and Function", "Cytoplasmic Organelles"),
    146: ("Cell Structure and Function", "Chromosomes"),
    147: ("Biological Molecules", "Carbohydrates"),
    148: ("Biological Molecules", "Carbohydrates"),
    149: ("Biological Molecules", "Proteins"),
    150: ("Biological Molecules", "Lipids"),
    151: ("Biological Molecules", "Structure of DNA"),
    152: ("Enzymes", "Co-factors of Enzymes"),
    153: ("Enzymes", "Factors Affecting Enzyme Action"),
    154: ("Enzymes", "Mode of Enzyme Action"),
    155: ("Enzymes", "Co-factors of Enzymes"),
    156: ("Acellular Life", "Viruses"),
    157: ("Biotechnology", "Biotechnology and Health Care"),
    158: ("Cell Structure and Function", "Prokaryotic and Eukaryotic Cell"),
    159: ("Acellular Life", "Viruses"),
    160: ("Digestion", "Human Digestive System"),
    161: ("Acellular Life", "Viruses"),
    162: ("Acellular Life", "Viruses"),
    163: ("Cell Structure and Function", "Prokaryotic and Eukaryotic Cell"),
    164: ("Digestion", "Human Digestive System"),
    165: ("Digestion", "Human Digestive System"),
    166: ("Digestion", "Human Digestive System"),
    167: ("Digestion", "Human Digestive System"),
    168: ("Digestion", "Human Digestive System"),
    169: ("Respiration", "Human Respiratory System"),
    170: ("Circulation", "Blood Vessels (Arteries, Veins, Capillaries)"),
    171: ("Circulation", "Lymphatic System"),
    172: ("Circulation", "Human Heart"),
    173: ("Homeostasis", "Kidney Structure and Function"),
    174: ("Homeostasis", "Glomerular Filtration and Reabsorption"),
    175: ("Homeostasis", "Glomerular Filtration and Reabsorption"),
    176: ("Homeostasis", "Kidney Structure and Function"),
    177: ("Homeostasis", "Glomerular Filtration and Reabsorption"),
    178: ("Coordination and Control", "Nerve Impulse and Reflexes"),
    179: ("Coordination and Control", "Brain"),
    180: ("Coordination and Control", "Brain"),
    181: ("Coordination and Control", "Brain"),
    182: ("Reproduction", "Human Reproductive System"),
    183: ("Reproduction", "Sexually Transmitted Diseases"),
    184: ("Reproduction", "Human Reproductive System"),
    185: ("Reproduction", "Human Reproductive System"),
    186: ("Reproduction", "Menstrual Cycle"),
    187: ("Support and Movement", "Skeletal Muscle Ultra-structure"),
    188: ("Support and Movement", "Muscle Contraction"),
    189: ("Support and Movement", "Joints"),
    190: ("Support and Movement", "Skeletal Muscle Ultra-structure"),
    191: ("Support and Movement", "Human Skeleton (Cartilage, Muscle, Bone)"),
    192: ("Biological Molecules", "Proteins"),
    193: ("Coordination and Control", "Neurons"),
    194: ("Digestion", "Biological Importance of Water"),
    195: ("Digestion", "Biological Importance of Water"),
    196: ("Immunity", "Specific Defense Mechanism"),
    197: ("Immunity", "Specific Defense Mechanism"),
    198: ("Biological Molecules", "Conjugated Molecules"),
    199: ("Immunity", "Specific Defense Mechanism"),
    200: ("Immunity", "Specific Defense Mechanism"),
    201: ("Bioenergetics", "Respiration"),
    202: ("Bioenergetics", "Respiration"),
    203: ("Bioenergetics", "Respiration"),
    204: ("Bioenergetics", "Respiration"),
    205: ("Bioenergetics", "Respiration"),
    206: ("Biotechnology", "Biotechnology and Health Care"),
    207: ("Enzymes", "Mode of Enzyme Action"),
    208: ("Biotechnology", "Biotechnology and Health Care"),
    209: ("Biotechnology", "Biotechnology and Health Care"),
    210: ("Biological Molecules", "Structure of DNA"),
    211: ("Evolution", "Concept of Evolution"),
    212: ("Evolution", "Concept of Evolution"),
    213: ("Evolution", "Concept of Evolution"),
    214: ("Evolution", "Concept of Evolution"),
    215: ("Evolution", "Concept of Evolution"),
    216: ("Evolution", "Concept of Evolution"),
    217: ("Inheritance", "Mendel's Laws of Inheritance"),
    218: ("Inheritance", "Mendel's Laws of Inheritance"),
    219: ("Inheritance", "Mendel's Laws of Inheritance"),
    220: ("Inheritance", "Mendel's Laws of Inheritance"),
}

path = "mdcat-content/parsed-mcqs/MDCAT_2013.json"
mcqs = json.load(open(path, encoding="utf-8"))

missing = []
for mcq in mcqs:
    qn = mcq["question_number"]
    if qn not in TAGS:
        missing.append(qn)
        continue
    topic, subtopic = TAGS[qn]
    mcq["topic"] = topic
    mcq["subtopic"] = subtopic

print("missing tags for:", missing)
print("total tagged:", len(mcqs) - len(missing))

with open(path, "w", encoding="utf-8") as f:
    json.dump(mcqs, f, indent=2, ensure_ascii=False)
print("wrote", path)
