# Generated by Django 6.1 on 2026-08-09 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('board', models.CharField(choices=[('PMDC', 'PMDC (Pakistan Medical & Dental Council)'), ('FBISE', 'Federal Board'), ('Punjab', 'Punjab Board'), ('Sindh', 'Sindh Board'), ('KP', 'KP Board'), ('Cambridge', 'Cambridge International')], max_length=20)),
                ('level', models.CharField(choices=[('entry-test', 'Entry Test'), ('matric', 'Matric'), ('intermediate', 'Intermediate / FSc'), ('o-level', 'O-Level'), ('a-level', 'A-Level')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
