# Generated by Django 6.1 on 2026-08-09 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_subject_topic_subtopic'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('year', models.PositiveSmallIntegerField()),
                ('is_free', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='past_papers', to='content.exam')),
            ],
            options={
                'ordering': ['exam', '-year'],
                'unique_together': {('exam', 'slug'), ('exam', 'year', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('option_a', models.CharField(max_length=500)),
                ('option_b', models.CharField(max_length=500)),
                ('option_c', models.CharField(max_length=500)),
                ('option_d', models.CharField(max_length=500)),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('explanation_short', models.TextField(blank=True, default='')),
                ('explanation_long', models.TextField(blank=True, default='')),
                ('explanation_trick', models.TextField(blank=True, default='')),
                ('explanation_generated_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('past_paper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='content.pastpaper')),
                ('subtopic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='content.subtopic')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['subtopic', 'difficulty'], name='content_que_subtopi_342035_idx'), models.Index(fields=['past_paper'], name='content_que_past_pa_e93066_idx')],
            },
        ),
    ]
