# Generated by Django 6.1 on 2026-08-14 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_question_is_verified_conceptnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_visual_required',
            field=models.BooleanField(default=False),
        ),
    ]
