# Generated by Django 6.1 on 2026-08-14 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_question_is_visual_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='question_images/')),
                ('source_name', models.CharField(blank=True, max_length=200)),
                ('source_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('page_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='content.question')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
