# Generated by Django 6.1 on 2026-08-17 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_questionimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='paper_order',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['past_paper', 'paper_order'], name='content_que_past_pa_89f55e_idx'),
        ),
    ]
