# Generated by Django 6.1 on 2026-08-18 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_question_paper_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='explanation_options',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
