# Generated by Django 6.1 on 2026-08-19 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_question_explanation_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='board',
            field=models.CharField(blank=True, choices=[('PMDC', 'PMDC (Pakistan Medical & Dental Council)'), ('FBISE', 'Federal Board'), ('Punjab', 'Punjab Board'), ('Sindh', 'Sindh Board'), ('KP', 'KP Board'), ('Cambridge', 'Cambridge International'), ('University', 'University / Admitting Body')], max_length=20),
        ),
    ]
