# Generated by Django 6.1 on 2026-08-19 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_alter_exam_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='level',
            field=models.CharField(choices=[('entry-test', 'Entry Test'), ('o-level', 'O-Level'), ('a-level', 'A-Level')], max_length=20),
        ),
    ]
