# Generated by Django 6.1 on 2026-08-20 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_alter_exam_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastpaper',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
