# Generated by Django 6.1 on 2026-08-20 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_pastpaper_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastpaper',
            name='student_note',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
