# Generated by Django 6.1 on 2026-09-17 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_pastpaper_student_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('wrong_answer', 'Marked answer looks wrong'), ('typo', 'Typo or formatting problem'), ('image', 'Missing or unreadable image'), ('explanation', 'Explanation is wrong or unclear'), ('other', 'Something else')], default='other', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('new', 'New'), ('accepted', 'Accepted — question fixed'), ('rejected', 'Rejected — question was right'), ('duplicate', 'Duplicate')], default='new', max_length=12)),
                ('resolution', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='content.question')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='content_que_status_0bec89_idx')],
            },
        ),
    ]
